### ISSUE TITLE
Finetuned model importing to h2ogpt.

### ISSUE THREAD

**Issue by Cansiano** [h2oai/h2ogpt#1000]
Can you help me to understand how can I import/use finetune model from H2O studio into h2ogpt please? If I do export experiment it gives me bunch of files, dont know what to do next.

Thank you.

**Comment by pseudotensor** [comment]
You could export your model from LLM studio onto HF, then use that in h2oGPT as any normal HF model with --base_model=<HF link name> as usual or start with no options and add model in Models tab, then load it.

**Comment by Cansiano** [comment]
Its finetuned on sensitive data I do not want to load on internet.

**Comment by pseudotensor** [comment]
You can check with LLM Studio team on export options.
