### ISSUE TITLE
How do I chat with my uploaded documents using gradio client? I am developing a flask API that will get a question in JSON and an API key in the header, and I want to return the answer by calling the gradio client from my flask app.

### ISSUE THREAD

**Issue by prateekrana17** [h2oai/h2ogpt#1002]
I am developing a flask API that will get a question in JSON and an API key in the header, and I want to return the answer in JSON by calling the gradio client from my flask app. I have tried the following function to get the response, but I only get responses from the AI model that are not relevant to my uploaded documents:

from gradio_client import Client
import ast
import json

HOST_URL = "http://localhost:7860"
client = Client(HOST_URL)

def query():
     kwargs = dict(instruction_nochat='What does it mean when a result of a CDD check indicates a money launderirng risk, and what follow up actions may be required in such cases? ')
    res = client.predict(str(dict(kwargs)), api_name='/submit_nochat_api')
     #string of dict for output
    response = ast.literal_eval(res)['response']
    response_dict = {'Answer': response}
    j = json.dumps(response_dict)
    print(response_dict)

query()

I am new to this stuff, so can somebody please help me get the right function call? I would be really grateful if you could also guide me on how to use this function in my flask REST API. I have developed it, but it is not working.

Thanks a lot

**Comment by pseudotensor** [comment]
Review https://github.com/h2oai/h2ogpt/blob/main/docs/README_CLIENT.md

and the lower code fragment that explains how to add files/text/url and ask question.

Also see the steps3 test that has many more uses: https://github.com/h2oai/h2ogpt/blob/main/tests/test_client_calls.py#L2030

**Comment by FreshLucas-git** [comment]
@pseudotensor Hi, I tried to run the following example code to understand how to add files, but it occurered the error message which showed "ValueError: Cannot find a function with `api_name`: /model_names." Do you have any idea to solve this? Thank you.
https://github.com/h2oai/h2ogpt/blob/7a364e3afffccf9f43ff24ce178c8d941a120c6e/docs/README_CLIENT.md?plain=1#L84

**Comment by pseudotensor** [comment]
@FreshLucas-git Not sure, it works for me on gpt.h2o.ai and locally.  What is your run command for the server?
