### ISSUE TITLE
h2oGPT - Windows GPU & CPU Version - Model not loading

### ISSUE THREAD

**Issue by Macxy007** [h2oai/h2ogpt#1003]
Hi 
I have tried both GPU and CPU versions of windows installer. In both the versions, I am not able to load the LLM models. 

The chosen LLM model is downloaded into .Cache folder, but not sure how to link it with the H2oGPT UI?  Can somebody help please?

**Comment by pseudotensor** [comment]
If you have a huggingface model, the cache should already be used by huggingface inside h2ogpt (outside our direct control).  i.e. usually it's in ~/.cache/huggingface/hub/

For GGUF/GGML models, you choose llama as model in models tab, then provide the full http link from TheBloke (raw download resolve in url, not html link to info page) into the  model_llama_path (`Choose LLaMa.cpp Model Path/URL (for Base Model: llama)` in UI) to avoid having to worry about where the file is.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/db29e30e-abb7-4b61-99f8-ac220165e312)
