### ISSUE TITLE
docker compose latest - multiple stack errors when adding a  --pre_prompt_summary and --prompt_summary

### ISSUE THREAD

**Issue by dingzhongshan** [h2oai/h2ogpt#1005]
Good afternoon,
I'm using the latest docker runtime image (10-26-2023) and everything seems to be fine in my current config, except:
I'm attempting to add the following:

`--pre_prompt_summary="In order to write a multi-paragraph or bulleted list summary, pay attention to the following text"`
and/or
`--prompt_summary="Using only the information in the document sources above, write a multi-paragraph summary of key results (preferably as bullet points):"`
** slight modification to the default (but continuing to adjust). I see "improve summarization" issue, so if I need to mod .py for now, let me know

When adding a "--pre_prompt_summary" or "--prompt_summary" to gen.py as indicated 
`
:param pre_prompt_summary: prompt before documents to summarize/extract from, if None then use internal defaults
:param prompt_summary: prompt after documents to summarize/extract from, if None then use internal defaults
           For summarize/extract, normal to have empty query (nothing added in ask anything in UI or empty string in API)
           If pass query, template is "Focusing on %s, %s" % (query, prompt_summary)
           If pass query and iinput, template is "Focusing on %s, %s, %s" % (query, iinput, prompt_summary)
`

I get these/this errors:
`
<img width="845" alt="Screenshot 2023-10-26 at 10 39 59 AM" src="https://github.com/h2oai/h2ogpt/assets/217438/cc7b5ba4-b1db-46fa-a2f1-e801a4c11364">

`
Thanks (ding)

**Comment by pseudotensor** [comment]
You probably are passing --model_lock but don't have it in double quotes.  Or you have a typo and missing space between parameters that you added and existing parameters, etc.
