### ISSUE TITLE
Question about document chunks

### ISSUE THREAD

**Issue by a3nima** [h2oai/h2ogpt#1014]
On the left hand side, if a document has been added to the database, I see for example: 

> Collection: UserData
> Docs: =1
> Chunks: 353

while in expert settings (default) it's set up:

> Number of document chunks (query) or pages/parts (summarize) (-1 = auto fill model context, all pages/docs for summarize)
`3`

Does this mean that only 3 chunks are used? Or are these different kind of chunks?

**Comment by pseudotensor** [comment]
Yes, top_k_docs=3 by default.  For highest quality I recommend top_k_docs=-1, but it will be slower.  A good balance might be 10.  We will manage things in any case to reduce the count to not exceed the context of the LLM.

**Comment by pseudotensor** [comment]
b5996103ce8f1fda8d2612587da68f82302d3923
