### ISSUE TITLE
Show two different llama models by a 'name' vs the same base_name in visible_models 

### ISSUE THREAD

**Issue by dingzhongshan** [h2oai/h2ogpt#1017]
Good evening,
Is there any way in "--visible_models" (or other method) to show a param model_name or name_of_model when using the base_name of 'llama'?  I would like to be able to show and select two different base_name 'llama' models with different llamacpp_dict in the dropdown. I see a few places I could mod gradio_utils/prompt_form.py but not sure if there is already a way to accomplish this.

In the example, both models 'base_name llama' and llamacpp_dict are loaded successfully, however,  I am unable to select 1 model b/c they are both base_name 'llama' however, they have separate model_path_llama and llamacpp_dict entries.

Example:
`
MODEL_PATH="$HOME/Downloads/_models"
MODEL_LOCK=[{'base_model':"llama",'prompt_type':'mistral','llamacpp_dict':"{'model_path_llama':'../_models/mistral-7b-instruct-v0.1.Q4_K_M.gguf'}"},{'base_model':'llama','prompt_type':'wizard_lm','llamacpp_dict':"{'model_path_llama':'../_models/wizardlm-13b-v1.2.Q4_0.gguf'}"}]
VIS=[0,1]

python generate.py --model_lock="$MODEL_LOCK" --hf_embedding_model='../_models/sentence-transformers/all-MiniLM-L6-v2' --share=False --prompt_type=mistral --gradio_size=small --visible_h2ogpt_header=False --model_lock_columns=1 --visible_visible_models=True --visible_models="$VIS" --pre_prompt_summary="This is a pre summary prompt" --prompt_summary="This is a summary prompt"
`

Thanks! (ding)

**Comment by pseudotensor** [comment]
llama.cpp is not thread safe, so can't do it for multiple local models, all but one has to be through inference server.

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/pull/1050
