### ISSUE TITLE
Data model finetuned in H2O Studio, how to use in local H2OGPT?

### ISSUE THREAD

**Issue by Cansiano** [h2oai/h2ogpt#1020]
I'm sorry to put this here again but I have sensitive data finetuned in H2O studio (I do not want to upload to hugging face) and do not understand how to export this model and use it on my local H2OGPT 
Can you help? 

Thank you.

**Comment by pseudotensor** [comment]
You should be able to use the model by passing the location of the folder where the pytorch bin files are etc, instead of a HF link name.
