### ISSUE TITLE
[server side]: failed to parse pdf files.

### ISSUE THREAD

**Issue by mahmodDAHOL** [h2oai/h2ogpt#1021]
Failed to ingest /tmp/gradio/86095159b38911060cecd6c0fb2ce0ed96fa950b/airline tickets.pdf due to Traceback (most recent call last):
  File "/content/myh2ogpt/src/gpt_langchain.py", line 2553, in path_to_doc1
    res = file_to_doc(file,
  File "/content/myh2ogpt/src/gpt_langchain.py", line 2407, in file_to_doc
    raise ValueError("%s had no valid text and no meta data was parsed: %s" % (file, str(e)))
ValueError: /tmp/gradio/86095159b38911060cecd6c0fb2ce0ed96fa950b/airline tickets.pdf had no valid text and no meta data was parsed: None

**Comment by pseudotensor** [comment]
This is the generic message, but a detailed message would be in the console and UI in document selection tab under document exceptions.

**Comment by trendsetter37** [comment]
@pseudotensor I'm getting the same error today. This is a fresh local install. Below is the error from the terminal.

Also, i'm using archlinux x86_64 and python 3.11.3

```
Failed to ingest /tmp/gradio/09664c49d54657a7e9a143e131de82a548a24116/XXXXXXXXXX.pdf due to Traceback (most recent call last):
  File "/home/jsullivan/Code/h2ogpt/src/gpt_langchain.py", line 2718, in path_to_doc1
    res = file_to_doc(file,
          ^^^^^^^^^^^^^^^^^
  File "/home/jsullivan/Code/h2ogpt/src/gpt_langchain.py", line 2552, in file_to_doc
    raise ValueError("%s had no valid text and no meta data was parsed: %s" % (file, str(e)))
ValueError: /tmp/gradio/09664c49d54657a7e9a143e131de82a548a24116/XXXXXXXXXX.pdf had no valid text and no meta data was parsed: None
```

**Comment by pseudotensor** [comment]
That's a generic error later after, there should be an earlier console error or one in document selection tab under document exceptions

**Comment by pseudotensor** [comment]
You can also try adding --verbose --debug to CLI to see more things in console, but I think it should show already.

**Comment by trendsetter37** [comment]
@pseudotensor Still working through this but I reverted #787 and then made the following change

```
diff --git a/src/gpt_langchain.py b/src/gpt_langchain.py
index 1d963e2c..85afb43a 100644
--- a/src/gpt_langchain.py
+++ b/src/gpt_langchain.py
@@ -2869,7 +2869,7 @@ def path_to_docs(path_or_paths, verbose=False, fail_any_exception=False, n_jobs=
         n_jobs_image = 1
     else:
         n_jobs_image = n_jobs
-    if enable_doctr or enable_pdf_doctr in [True, 'auto', 'on']:
+    if enable_doctr in [True, 'auto', 'on']:
         if doctr_loader and not isinstance(doctr_loader, (bool, str)) and doctr_loader.device != 'cpu':
             # can't fork cuda context
             n_jobs = 1

```
And now I can upload documents and use them as context. I see on the most recent commit you reverted that as well but also added your own code. I decided to start from the most recent touch of that code and not include your changes to get to a working state without too many changes to reason about. 

So the error is coming from somewhere in that PR. Just haven't dug into it deep enough yet. Hope this info helps!

**Comment by trendsetter37** [comment]
Which btw, can confirm that this is not just an issue for @mahmodDAHOL

**Comment by pseudotensor** [comment]
The code you are referring to tries DocTR, if that fails, before would fail everything, the above commit should fix.
