### ISSUE TITLE
CLI instructions entry via a file?

### ISSUE THREAD

**Issue by devinrouthuzh** [h2oai/h2ogpt#1023]
Hello,

I have a working installation of H2OGPT on my university's cluster via the interactive CLI mode, meaning I can submit instructions to the model manually when prompted on the command line interface. I.e., I use the following code to accomplish this:

`python generate.py --base_model=h2oai/h2ogpt-4096-llama2-7b-chat --cli=True --answer_with_sources=False`

However, I'd now like to augment the command to input the instructions via a path to a prepared text file then receive the model's response also as a text file (to obviate the need for interactive input on the command line).

I used `python generate.py --help` to view the relevant flags hoping I could use `--input_file` or `--output_file`, but neither flag exists within the `generate.py` script. I also tried using the various `--eval...` flags (e.g., `--eval_filename=test_prompts.json --eval_prompts_only_num=2 --eval_as_output=True`) to no avail.

Could you please provide some guidance on using the `generate.py` script to run models from the CLI and submit instructions via prepared text files (receiving the response also as text)? Or is there a docs page / README somewhere that you could reference?

Thanks!

**Comment by pseudotensor** [comment]
All of the CLI options can be controlled via ENV with prefix H2OGPT_ or h2ogpt_ and all caps or all lower, respectively.

See bottom of: https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#what-envs-can-i-pass-to-control-h2ogpt
