### ISSUE TITLE
Runtime error while uploading documents

### ISSUE THREAD

**Issue by emil-jose** [h2oai/h2ogpt#1025]
Suddenly I am getting the following error, whenever I am trying to upload a document and ask questions. I am using 4 GPUs with gpu_id=False and without any docs models like llama2 and mistral runs fine. However whenever I use a document the following error occurs, `RuntimeError: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.`
Any guidance here would be highly appreciated. Thanks in advance

**Comment by pseudotensor** [comment]
I'm guessing you upgraded torch but your driver is too old for it. You can do as it says.
