### ISSUE TITLE
https://github.com/h2oai/h2ogpt/tree/main/client H2OGPT_KEY key name should not be "H2OGPT_H2OGPT_KEY'

### ISSUE THREAD

**Issue by surenH2oai** [h2oai/h2ogpt#1030]
https://github.com/h2oai/h2ogpt/tree/main/client H2OGPT_KEY key name should not be "H2OGPT_H2OGPT_KEY', rather like
H2OGPT_SERVER
H2OGPT_KEY 
etc.

**Comment by pseudotensor** [comment]
It's designed to be both because the server has argument h2ogpt_key and we allow a general way to set such arguments via an ENV, which is by adding H2OGPT_ to front and capitalizing the function argument.
