### ISSUE TITLE
API integration 

### ISSUE THREAD

**Issue by lee-jian-hui** [h2oai/h2ogpt#1040]
I want to be able to use h2ogpt as an API service, how would I be able to do that? I am sorry as I am new to the project and am unsure if questions go here.

**Comment by lee-jian-hui** [comment]
in particular, in what manner is the ingestion invoked in the gradio UI so that I could be able to model that as a REST endpoint

**Comment by pseudotensor** [comment]
There is a gradio client for all operations: https://github.com/h2oai/h2ogpt/blob/main/docs/README_CLIENT.md

For some basic ops see: https://github.com/h2oai/h2ogpt/blob/main/docs/README_CLIENT.md#h2ogpt-gradio-wrapper

For advanced ops see "steps3" test that goes through many things with extra asserts you don't need: https://github.com/h2oai/h2ogpt/blob/main/tests/test_client_calls.py#L2101

There is no REST API apart from just chat as given in the curl test: https://github.com/h2oai/h2ogpt/blob/main/docs/README_CLIENT.md#curl-client-api
