### ISSUE TITLE
Issues with huggingface model compatibility

### ISSUE THREAD

**Issue by bw-Deejee** [h2oai/h2ogpt#1043]
I am trying to test LLMs which are finedtuned to german language. However, I can't get to run any of them.
Some of them are listed here:

- **TheBloke/SauerkrautLM-13B-v1-GPTQ**
`ValueError: Exllama kernel does not support query/key/value fusion with act-order. Please either use inject_fused_attention=False or disable_exllama=True.`
I already tried using it with --load_exllama=False, without success
run:
`python generate.py --base_model=TheBloke/SauerkrautLM-13B-v1-GPTQ --score_model=None --load_gptq=model --use_safetensors=True`

- **TheBloke/em_german_leo_mistral-GPTQ**
`TypeError: mistral isn't supported yet.`
run:
`python generate.py --base_model=TheBloke/em_german_leo_mistral-GPTQ --score_model=None --load_gptq=model --use_safetensors=True`

- **TheBloke/leo-hessianai-13B-chat-bilingual-GPTQ**
`subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmpge9dlvqe/main.c', '-O3', '-I/usr/local/cuda/include', '-I/home/ubuntu/miniconda3/envs/h2ogpt/include/python3.10', '-I/tmp/tmpge9dlvqe', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmpge9dlvqe/rotary_kernel.cpython-310-x86_64-linux-gnu.so']' returned non-zero exit status 1.`
run:
`python generate.py --TheBloke/leo-hessianai-13B-chat-bilingual-GPTQ" --prompt_type=mptchat --score_model=None --load_gptq=model --use_safetensors=True`

I also tried their AWQ versions where I also receive errors:
- **TheBloke/SauerkrautLM-7B-v1-AWQ**
`AttributeError: 'LlamaAWQForCausalLM' object has no attribute 'config'`
run:
`python generate.py --base_model=TheBloke/SauerkrautLM-7B-v1-AWQ --load_awq=model --score_model=None --use_safetensors=True`

Can anyone help me with some suggestions as to why they dont run?

**Comment by pseudotensor** [comment]
Please provide your run commands.

**Comment by bw-Deejee** [comment]
@pseudotensor 
Thank you for your response. I updated/added them in the issue but here they are as well:

- **TheBloke/SauerkrautLM-13B-v1-GPTQ**
`python generate.py --base_model=TheBloke/SauerkrautLM-13B-v1-GPTQ --score_model=None --load_gptq=model --use_safetensors=True`

- **TheBloke/em_german_leo_mistral-GPTQ**
`python generate.py --base_model=TheBloke/em_german_leo_mistral-GPTQ --score_model=None --load_gptq=model --use_safetensors=True`

- **TheBloke/SauerkrautLM-7B-v1-AWQ**
`python generate.py --base_model=TheBloke/SauerkrautLM-7B-v1-AWQ --load_awq=model --score_model=None --use_safetensors=True`

- **TheBloke/Llama-2-13B-German-Assistant-v4-GPTQ** (runs but doesnt give any answers at all)
`python generate.py --base_model=TheBloke/Llama-2-13B-German-Assistant-v4-GPTQ --load_gptq=model --use_safetensors=True --prompt_type=llama2`
(probably wrong prompt_type, but im not sure how to add custom prompt_types yet)

**Comment by pseudotensor** [comment]
* TheBloke/SauerkrautLM-13B-v1-GPTQ
```
python generate.py --base_model=TheBloke/SauerkrautLM-13B-v1-GPTQ --score_model=None --load_gptq=model --use_safetensors=True
```
No Issue hit in PR sum_fixes:
![image](https://github.com/h2oai/h2ogpt/assets/2249614/8efe7653-26bb-4f83-9e10-32e61841a031)
![image](https://github.com/h2oai/h2ogpt/assets/2249614/f09b1480-b9c2-4c70-9574-64cf5124033b)

* TheBloke/em_german_leo_mistral-GPTQ
```
python generate.py --base_model=TheBloke/em_german_leo_mistral-GPTQ --score_model=None --load_gptq=model --use_safetensors=True
```
See: https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GPTQ/discussions/3
```
Yes, AutoGPTQ doesn't support Mistral GPTQ yet. You need to use Transformers GPTQ, or ExLlama.
```
I'll add transformers way soon.

* TheBloke/leo-hessianai-13B-chat-bilingual-GPTQ
```
python generate.py --base_model=TheBloke/leo-hessianai-13B-chat-bilingual-GPTQ --prompt_type=mptchat --score_model=None --load_gptq=model --use_safetensors=True
```

Runs but prompt choice is wrong:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/a6f0f4e1-9276-4054-ad97-c9fd5a328f2c)


* TheBloke/SauerkrautLM-7B-v1-AWQ
```
python generate.py --base_model=TheBloke/SauerkrautLM-7B-v1-AWQ --load_awq=model --score_model=None --use_safetensors=True
```
Fixed by: b26817621e8b7736a5435b3d430fbeda2455b1c7

![image](https://github.com/h2oai/h2ogpt/assets/2249614/4b1c5a14-57e0-4a8c-956f-151bf89b2e1b)

**Comment by pseudotensor** [comment]
2c302f5f76b7f13d0615b57f8becc75362afe62d

**Comment by bw-Deejee** [comment]
For: **TheBloke/SauerkrautLM-7B-v1-AWQ**
I'm getting the following error now:
`CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.`

I am on cuda 12.3 and just reinstalled cuda and cudnn to make sure everything is up to date.

`nvcc --version` returns cuda version 12.3

I'm using a Nvidia Tesla V100 in an EC2 instance.

`nvidia-smi` returns Driver Version: 545.23.06 and CUDA Version: 12.3

I'm using torch==2.0.1 according to the requirements.txt, however it seems to be an pytorch issue.

Any idea what's the problem?

**Comment by pseudotensor** [comment]
Unsure.  I google to see:

https://github.com/pytorch/pytorch/issues/31285
https://discuss.pytorch.org/t/gpu-compute-capability-support-for-each-pytorch-version/62434/2



```bash
(h2ogpt) jon@pseudotensor:~$ python -c "import torch; print(torch.cuda.get_arch_list())" 
['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86']
```

Seems V100 should still be supported by torch.

I presume basic torch tests also fail? E.g. just try some transformers huggingface code to load the model like given in any model card.
