### ISSUE TITLE
AttributeError: module 'numpy' has no attribute '_no_nep50_warning'

### ISSUE THREAD

**Issue by mahmodDAHOL** [h2oai/h2ogpt#1047]
when I upload pdf file it gives this error:
"ValueError: xyz.pdf had no valid text and no meta data was parsed: None
but when I check source code, I realized what is the reason for this error, this error is raised because of there is no library could parse the pdf.
when I try parsing pdf with unstructured library with standalone cell, it gives me this error:
   AttributeError: module 'numpy' has no attribute '_no_nep50_warning'
So, this error is the reason of first error.
And I can't find the solution for that.

**Comment by pseudotensor** [comment]
FYI when a doc is not parsed, it shows up in console and UI in Document Selection at bottom under Document Exceptions.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/e438b368-336d-485e-9dfc-e711597ee25a)

**Comment by pseudotensor** [comment]
I've never seen that error, but googling shows things like this: https://stackoverflow.com/questions/77064579/module-numpy-has-no-attribute-no-nep50-warning

I'd guess your env is mixed up, not fresh?
