### ISSUE TITLE
Option to only show already-downloaded models, keep track like LM Studio

### ISSUE THREAD

**Issue by basemaly** [h2oai/h2ogpt#1048]
Hello. Thank you for such a wonderful product. I'd like to test this to show my colleagues, but I'd like to only show downloaded local models in the model selection pull-down menu rather than showing a whole bunch of models that aren't downloaded. 

I'd also love to see a list of all available CLI launch switches we could use. I can't seem to find it in the documentation. Any help would be greatly appreciated. Thanks!

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/pull/1045 will help with too many models in UI and general model issues.

It's a good feature to only show what you have downloaded already.  Will keep this issue and rename for that.

For CLI just do:
```
python generate.py --help
```

Also check out docs/* in repo for various topics.
