### ISSUE TITLE
simple demand

### ISSUE THREAD

**Issue by asholino** [h2oai/h2ogpt#1051]
Hello
i have an old workstation with 32 giga of ram double xeon cpu is that possible to run h2ogpt .. so running the installer on Windows will install everything and after i will need ro run it ?

**Comment by pseudotensor** [comment]
On CPU smaller quantized models use 32GB ram, but it will be tight if you only have 32GB.

E.g. https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF

Or the mistral ones, you can try the smaller versions of such models like he lists.
