### ISSUE TITLE
Minor issue in Launching the browser.

### ISSUE THREAD

**Issue by MSZ-MGS** [h2oai/h2ogpt#1054]
When launching two H2oGPT, the second launch will not find the default port available (7860) so it will go to the default port +1 (7861). However, the auto launch of the browser (--open_browser=True) will still go to the default port (7860).
![image](https://github.com/h2oai/h2ogpt/assets/65172063/e71a2f52-e1d1-4173-87d4-a8c7dfff97c8)

**Comment by pseudotensor** [comment]
Hi, it'll be too late inside the gradio logic for me to catch that. Instead you should specify the port when launching by running each generate like:

```
GRADIO_SERVER_PORT=7680 python generate.py ...
GRADIO_SERVER_PORT=7681 python generate.py ...
```

Then the web browser will open up
