### ISSUE TITLE
Symlink in spaces/demo/ has wrong target

### ISSUE THREAD

**Issue by sebastianlutter** [h2oai/h2ogpt#1059]
The symlink https://github.com/h2oai/h2ogpt/blob/main/spaces/demo/h2oai_pipeline.py has the non-existing target `../../h2oai_pipeline.py`. It should be `../../src/h2oai_pipeline.py`

To fix it:
```
cd spaces/demo/
rm h2oai_pipeline.py
ln -s ../../src/h2oai_pipeline.py
```

I'm not allowed to create branches with pull request, so I created an issue instead

**Comment by pseudotensor** [comment]
Thanks!  We don't test that demo code for last 7 months, I'm still unsure if it will work.  The chatbot code may be out of date, but as of the time last was committed it was working.
