### ISSUE TITLE
How can use 32k Spanish model context ?

### ISSUE THREAD

**Issue by johnfelipe** [h2oai/h2ogpt#1061]
Can u suggest me steps, models and all for create instance with 32k model context for create markdown files using transcripts, freely?

**Comment by pseudotensor** [comment]
I added some notes here, including example for Chinese: https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#non-english-languages

For spanish we found llama-2 works fine, so you could try to use the long alpaca 32k model and use the tricks mentioned there to force it to speak spanish.
