### ISSUE TITLE
video -> text (e.g. simple way is to do every second of frame -> blip and doctr, then summarize with LLM over all results

### ISSUE THREAD

**Issue by davidezari** [h2oai/h2ogpt#1063]
Not sure if true but reading as supported file formats also .mpg and .mpeg I tried to load an .mpg MPEG-4, FullHD, 30 fps fixed frame rate, h264 video encoding, AAC LC audio encoding file, getting previous error as result.

Wanted to know if videos are in fact not supported as file format

**Comment by pseudotensor** [comment]
If you want audio transcription, I just added that capability, including for mp4.

**Comment by pseudotensor** [comment]
1895d39e2a0260da0f803396f47902c4aef56ede

**Comment by davidezari** [comment]
Was interested into video to text, but also audio transcription is nice, thanks!

**Comment by pseudotensor** [comment]
video -> text is done too
