### ISSUE TITLE
Can I get another model?

### ISSUE THREAD

**Issue by findkh** [h2oai/h2ogpt#1068]
Hello, I'm studying LLM.
Windows 10 + CPU environment
`python generate.py --base_model='llama' --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=user_path`
I tried to run h2ogpt using the above command above.
When I ask questions in English, I get a normal answer,
When I ask a question in Korean, there is a problem that I can't answer in Korean.

1. Based on the manual, you said that you can use the model if it's an LLM model released on Hugging Face, but I wonder if it's possible.
2. In the case of answers based on user-provided documents, I wonder if the user-provided documents take precedence over pre-trained data.

**Comment by pseudotensor** [comment]
Hi, I added docs tot he FAQ for Chinese case.  You'll need to find a good LLM, embedding model, and replace the prompts as in the docs.  Since I don't know Korean I cannot evaluate the goodness of such models or prompts.
