### ISSUE TITLE
Document summarization issue

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#1069]
Hi,
Uploaded the doc to MyData and started "Summarize". 
Got the summary, but after few seconds the text of summary is disappeared and only list of sources left
<img width="555" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/f52f65e8-d97d-4a90-a210-cc60d96d3517">

Thanks

**Comment by pseudotensor** [comment]
Maybe it failed during reduction.  When streaming summary it shows each page summarized at a time, for example for PDFs, and then in end does reduction.   If model gets confused by the reduction process it can lead to issues.

**Comment by slavag** [comment]
@pseudotensor Seems that llama-cpp-python breaks something starting from 0.2.14, reverted back to 0.2.13 working good.

**Comment by pseudotensor** [comment]
Yes, many packages are very sensitive inter-dependencies.

**Comment by slavag** [comment]
@pseudotensor opened bug to llama-cpp-python

**Comment by MSZ-MGS** [comment]
> @pseudotensor Seems that llama-cpp-python breaks something starting from 0.2.14, reverted back to 0.2.13 working good.

What is the issue, I am working on 0.2.14 flawlessly...
For the 0.2.15 and 0.2.16 they can't be installed.

**Comment by pseudotensor** [comment]
One can't really use any other versions except for what we require.  There are many packages with breaking changes all the time.

i.e. in instructions:

```
    * GGUF ONLY for CUDA GPU (keeping CPU package in place to support CPU + GPU at same time):
      ```bash
      pip uninstall -y llama-cpp-python-cuda
      pip install https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.2.10+cu118-cp310-cp310-manylinux_2_31_x86_64.whl
      ```
    * GGUF ONLY for CPU-AVX (can be used with -cuda one above)
      ```bash
      pip uninstall -y llama-cpp-python
      pip install https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/cpu/llama_cpp_python-0.2.9+cpuavx2-cp310-cp310-manylinux_2_31_x86_64.whl
    ```
```

gives for pip freeze:
```
llama_cpp_python @ https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/cpu/llama_cpp_python-0.2.9+cpuavx2-cp310-cp310-manylinux_2_31_x86_64.whl#sha256=45196fbcbb5acee4177fd90bb35a90a682bb9c3a5e7a3bdd96c53a1471e7de0f
llama_cpp_python_cuda @ https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.2.10+cu118-cp310-cp310-manylinux_2_31_x86_64.whl#sha256=74921f52363024a2a4744a47fd0f58b979e2c5c9f9b2961cb07f9c7e4ae1bf11

```

**Comment by cedarice** [comment]
Similar issue. When click the submit botton to summarize a document, I will quicky get the summary text. But it is still running in the background, and after a period of time, the summary text disappeared and another summary text showed (in list format).

**Comment by cedarice** [comment]
> @cedarice That's normal. It's streaming each result of the map operation. It's just a way to show progress. If you want to avoid that, just click "stream output" unchecked in expert settings and wait.

I see, thanks

**Comment by cedarice** [comment]
> @cedarice That's normal. It's streaming each result of the map operation. It's just a way to show progress. If you want to avoid that, just click "stream output" unchecked in expert settings and wait.

Is there any way to keep the summary text priviously displayed?

**Comment by pseudotensor** [comment]
@cedarice You can use the "extract" and that just avoids the final reductions and shows the maps for each block.
