### ISSUE TITLE
is it possible to create plot in h2oGPT?

### ISSUE THREAD

**Issue by hpxiong** [h2oai/h2ogpt#1077]
This is what I see today with h2oGPT. any suggestions to make this work?

![image](https://github.com/h2oai/h2ogpt/assets/17347604/814679e2-d4df-4d98-97dd-bec3f8b99fcd)

**Comment by pseudotensor** [comment]
We don't have good Advanced data analytics like OpenAI at moment.  Langchain ways with agents are not reliable, so we are looking into other means.
