### ISSUE TITLE
Deployment in Azure

### ISSUE THREAD

**Issue by bw-Deejee** [h2oai/h2ogpt#1080]
What is the recommended way to deploy h2oGPT in Azure?
I'm relatively new to cloud services, especially Azure.
Main problem is, I don't want to run a virtual machine and pay big money during its uptime.
I've heard about AWS Lamda + Sagemaker in the AWS universe which is pay-per-use.
How would this work in Azure (I've read some about Azure Functions and Azure ML) but I'm not in the clear yet as to how exactly this would work.
Docs about this would be very helpful

Best regards

**Comment by pseudotensor** [comment]
If you use Azure OpenAI as LLM endpoint, then you can run h2oGPT itself on single T4 on AWS or equivalent on Azure to get good performance.  At that point, OpenAI is useful since per token cost, and you aren't worried about privacy if you are on cloud already.
