### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by mbbutt** [h2oai/h2ogpt#1081]
Hello everybody,

I took the latest commit.
My GPU has only 4GB Dedicated GPU memory. 
I am getting below error for ingest few PDFs.
earlier (few weeks ago) I was able to ingest a large number of pdf without such problem (with same GPU).

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 4.00 GiB total capacity; 3.34 GiB already allocated; 0 bytes free; 3.39 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

could some please help me to avoid such error.

Thanks

**Comment by Mathanraj-Sharma** [comment]
@mbbutt may I know which model you are trying to run?

please share the Python command you use to start the server 

This error normally occurs when you try to run the model with high precision. try loading the model with low precision

i.e
```bash
python generate.py --base_model=h2oai/h2ogpt-4096-llama2-7b-chat --score_model=None --langchain_mode='UserData' --user_path=user_path --load_4bit=True
```

**Comment by mbbutt** [comment]
Hello @Mathanraj-Sharma 

Thank you for the message. below is the python command i am using.
`C:\h2ogpt_10Nov>"C:\miniconda3\envs\h2ogpt\python.exe" "generate.py" --share=False  --model_path_llama=C:\GPT_models\llama-2-7b-chat.Q6_K.gguf  --gradio_offline_level=1  --base_model='llama'  --prompt_type=llama2  --score_model=None  --load_4bit=True  --dark=True  --llamacpp_dict="{'n_gpu_layers':1}"  --cli=False  --gradio=True`

I would like to add something, I am using multiple db folders and multiple user_paths. like in below image Folder-1 to .. Folder-4

![image](https://github.com/h2oai/h2ogpt/assets/38038964/b6b70c2d-a16d-4453-9e0b-728dee2da5ce)

When I put documents in Folder-1 everything works fine.
When I put documents in Folder-4  would get "CUDA out of memory"

so might need to free up memory during ingest loop.
could you guide if we need to set NULL some db variable when running function `db = prep_langchain(..)` in gen.py
or something else..

Thanks

**Comment by EkamLabs** [comment]
I had the same issue, got hint from [here](https://github.com/h2oai/h2ogpt/blob/bdee0da0daf92cd75ef9b763593c27d74ca98473/docs/README_GPU.md) and used --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2

**Comment by pseudotensor** [comment]
4GB is tough, might need to offload less onto GPU.  See https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#low-memory-mode

and try a very small GGUF model: https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF/resolve/main/zephyr-7b-beta.Q2_K.gguf?download=true

i.e.

```
python generate.py --base_model=https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF/resolve/main/zephyr-7b-beta.Q2_K.gguf --prompt_type=zephyr --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --score_model=None --llamacpp_dict="{'n_gpu_layers':10}" --max_seq_len=1024 --enable_tts=False --enable_stt=False
```
