### ISSUE TITLE
Using `openai_chat` and `add_chat_history_to_context` in UserData mode

### ISSUE THREAD

**Issue by sebastianlutter** [h2oai/h2ogpt#1092]
I want to use `openai_chat` API with UserData mode, and noticed this comment in [gen.py](https://github.com/h2oai/h2ogpt/blob/bdee0da0daf92cd75ef9b763593c27d74ca98473/src/gen.py#L767-L769):
```
    :param add_chat_history_to_context: Include chat context when performing action
           Not supported yet for openai_chat when using document collection instead of LLM
           Also not supported when using CLI mode
```
I want to understand what the limitation/issue is, and if it is possible to use openai_chat API with UserData and chat history for continuous conversation.

I run main function of `generate.py` like this:
```
inference_server='openai_chat'
base_model='gpt-4'
prompt_type='openai_chat'
langchain_mode="UserData"
user_path='user_path'
use_openai_embedding=True
use_openai_model=False
db_type='chroma'
```

What is exactly meant by `openai_chat`, the [promptType](https://github.com/h2oai/h2ogpt/blob/bdee0da0daf92cd75ef9b763593c27d74ca98473/src/enums.py#L27) or when using OpenAI API in general?

When running with debug/verbose=True and inspecting the rendered Prompt template, the context is filled with data from VectorDB, no chat history is added. Some comment in the code states that the openai_chat API magically remembers and manages the history (but I'm not able to find the snipped again), is this correct?

Where at the code is the chat history added? Or where is the decision made that no chat history should be used when using UserData queries? 

Would be great if someone could shed some light on this

**Comment by pseudotensor** [comment]
1a3cb28f2e05fad2e34b7f76ce8fa820d189d3f6

**Comment by pseudotensor** [comment]
Hi, that's an old comment, will remove.

**Comment by pseudotensor** [comment]
The chat history is added as a real conversation when using openai_chat as inference server.

E.g. for non-document case, it's done here:

https://github.com/h2oai/h2ogpt/blob/5397e0c0ce2eff0997d9420377643543c7b90c5c/src/gen.py#L3321-L3333

Note that this differs from openai (non-chat) that just adds it to the context, like we do for vLLM with vllm (plain).

For document QA case it is here:

https://github.com/h2oai/h2ogpt/blob/ab8a3e81d11efdc2d257e42d08e48dd2d072b4c2/src/gpt_langchain.py#L1179-L1197

A simple way to test is to ask the model what one just asked, to see if it remembers.  One can use a trivial document to ensure things are not confused for it.  E.g. just upload the text fragment "Yulu i Hot".  Then ask the model if Yulu is hot.  Then ask "What did I just ask?"

If it doesn't work, let me know.
