### ISSUE TITLE
use_llm_if_no_docs=False not working?

### ISSUE THREAD

**Issue by ssa38** [h2oai/h2ogpt#1093]
I'm trying to prevent the LLM from generating an answer when no document sources are found, but the '--use_llm_if_no_docs=False' parameter doesn't seem to be working for me. Below is an example. 

![image](https://github.com/h2oai/h2ogpt/assets/150259455/992cc2a0-dc23-48a8-8bed-7e5cf217a8c1)

The CL:
python generate.py --base_model=h2oai/h2ogpt-4096-llama2-7b-chat --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --score_model=None --load_4bit=True --top_k_docs=4 --langchain_modes="['Coll_e5_large', 'Coll_MiniLM_Fiets']" --cut_distance=1.5 --use_llm_if_no_docs=False

**Comment by sebastianlutter** [comment]
Same here: Setting `use_llm_if_no_docs=False`, using commit [`3e23bab1`](https://github.com/h2oai/h2ogpt/tree/3e23bab19f03c716b79d419fd57dd75299facc10) from 10.11.2023

The `user_path` folder is empty. When I do provide an existing database in `db_dir_UserData` then `query` mode is used, if the `db_dir_UserData` is empty then mode `llm` is used (and thus `use_llm_if_no_docs=False` is not applied). 

Then I did some debugging to better understand the issue. I expected that the prompt template is the same in both cases, with and without data if  `use_llm_if_no_docs=False`.  But in this [code block in gpt_langchain.py](https://github.com/h2oai/h2ogpt/blob/3e23bab19f03c716b79d419fd57dd75299facc10/src/gpt_langchain.py#L5797-L5808):
```
    if langchain_action == LangChainAction.QUERY.value:
        if iinput:
            query = "%s\n%s" % (query, iinput)
        if not got_any_docs:
            template_if_no_docs = template = """{context}%s""" % question_fstring
        else:
            template = """%s%s{context}%s%s%s""" % (
                triple_quotes, pre_prompt_query, triple_quotes, prompt_query, question_fstring)
            if doc_json_mode:
                template_if_no_docs = """{context}{{"question": {question}}}"""
            else:
                template_if_no_docs = """{context}{question}"""
```

The template with `got_any_docs=False` ignores the  `pre_prompt_query` and `prompt_query` strings that are set in my case with some instructions. Why there are two different template? Why not only using a single template and insert the empty context?

@ssa38 : I guess you also expected the same template is used.

**Comment by pseudotensor** [comment]
Been busy with TTS and STT this week in development mode.  Got to this finally, simple fix.  Thanks.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/15dcc2c3-5eb9-4839-9de4-8ddb77ce8aa4)
