### ISSUE TITLE
No GPUs detected

### ISSUE THREAD

**Issue by An28212** [h2oai/h2ogpt#1094]
I tried to run the application but it says "No GPUs detected". I am using following command to run application.
python generate.py --base_model='llama' --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=user_path --model_path_llama=https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF/resolve/main/llama-2-7b-chat.Q6_K.gguf --max_seq_len=4096

**Comment by Mathanraj-Sharma** [comment]
@An28212 please give more context to reproduce the issue

- which platform you are on? (Linux/Mac/windows)
- which instructions did you follow to set up h2oGPT?

**Comment by pseudotensor** [comment]
@An28212 It means you have no CUDA GPUs or no MPS.
