### ISSUE TITLE
Add XwinCoder prompt template

### ISSUE THREAD

**Issue by MSZ-MGS** [h2oai/h2ogpt#1098]
Please add XwinCoder prompt template (it might be the same of Xwin-LM family that already defined)
https://huggingface.co/Xwin-LM/XwinCoder-7B
https://huggingface.co/Xwin-LM/XwinCoder-13B
https://huggingface.co/Xwin-LM/XwinCoder-34B

![rader](https://github.com/h2oai/h2ogpt/assets/65172063/942631af-8569-49a4-9eec-5c3fcdb175eb)

**Comment by pseudotensor** [comment]
deepseek coder does better job and is already supported.

https://deepseekcoder.github.io/

![image](https://github.com/h2oai/h2ogpt/assets/2249614/8a7d10fc-db8b-45b5-9b72-c6ffb7f5001b)

**Comment by pseudotensor** [comment]
I still added it.  You can see it's very easy to add prompts, esp. when small changes.
