### ISSUE TITLE
Option to hide model name when using single model

### ISSUE THREAD

**Issue by Blacksuan19** [h2oai/h2ogpt#1102]
is there a way to hide the box with text `h2oGPT [Model: ...]` at the top of the response chat box? I'm using a single model so this seems redundant.

![image](https://github.com/h2oai/h2ogpt/assets/10248473/58bd9732-b5d8-4619-8a88-99a65c243299)

**Comment by pseudotensor** [comment]
Will add option in upcoming merge from an unrelated PR.  Thanks!

**Comment by Blacksuan19** [comment]
Thanks for the prompt response and implementation!
