### ISSUE TITLE
ValueError: Trying to set a tensor of shape torch.Size([32000, 4096])

### ISSUE THREAD

**Issue by fahadshery** [h2oai/h2ogpt#1105]
Hi,

I successfully ran the example model using the following Docker command:
```bash
docker run \
       --gpus all \
       --runtime=nvidia \
       --shm-size=2g \
       -p 7860:7860 \
       --rm --init \
       --network host \
       -e CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES \
       -v /etc/passwd:/etc/passwd:ro \
       -v /etc/group:/etc/group:ro \
       -u `id -u`:`id -g` \
       -v "${HOME}"/.cache:/workspace/.cache \
       -v "${HOME}"/save:/workspace/save \
       -v "${HOME}"/user_path:/workspace/user_path \
       -v "${HOME}"/db_dir_UserData:/workspace/db_dir_UserData \
       -v "${HOME}"/users:/workspace/users \
       -v "${HOME}"/db_nonusers:/workspace/db_nonusers \
       gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0 /workspace/generate.py \
          --base_model=h2oai/h2ogpt-4096-llama2-7b-chat \
          --use_safetensors=True \
          --prompt_type=llama2 \
          --save_dir='/workspace/save/' \
          --use_gpu_id=False \
          --score_model=None \
          --max_max_new_tokens=2048 \
          --max_new_tokens=1024
```

But when I wish try the `base_model=h2oai/h2ogpt-16k-codellama-7b-python` model, it gives the following error:
```bash
Starting get_model: h2oai/h2ogpt-16k-codellama-7b-python
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/generate.py", line 16, in <module>
    entrypoint_main()
  File "/workspace/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/workspace/src/utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/src/gen.py", line 1487, in main
    model0, tokenizer0, device = get_model_retry(reward_type=False,
  File "/workspace/src/gen.py", line 1809, in get_model_retry
    model1, tokenizer1, device1 = get_model(**kwargs)
  File "/workspace/src/gen.py", line 2054, in get_model
    return get_hf_model(load_8bit=load_8bit,
  File "/workspace/src/gen.py", line 2289, in get_hf_model
    model = model_loader(
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
    return model_class.from_pretrained(
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3307, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3695, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 741, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 285, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([32000, 4096]) in "weight" (which has shape torch.Size([32016, 4096])), this look incorrect.
```

I tried passing the `ignore_mismatched_sizes=True` but no result.

Any ideas?

**Comment by pseudotensor** [comment]
Which docker build are you using?

Note that this is a foundational model, not instruct tuned.  Not sure you intended to use that.

I've not used this model myself.  The error is during loading.  The error is related to the vocabulary.   i.e. the model has `"vocab_size": 32016`:  https://huggingface.co/h2oai/h2ogpt-16k-codellama-7b-python/blob/main/config.json#L25


E.g. you can try instead: https://huggingface.co/codellama/CodeLlama-7b-Instruct-hf

Has same config.json vocab size.

**Comment by pseudotensor** [comment]
However, I have no problem loading that model from non-docker case:

```
python generate.py --base_model=h2oai/h2ogpt-16k-codellama-7b-python
```

starts fine.

**Comment by pseudotensor** [comment]
I see the same thing when I run this:

```
docker run \
       --gpus all \
       --runtime=nvidia \
       --shm-size=2g \
       -p 7860:7860 \
       --rm --init \
       --network host \
       -e CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES \
       -v /etc/passwd:/etc/passwd:ro \
       -v /etc/group:/etc/group:ro \
       -u `id -u`:`id -g` \
       -v "${HOME}"/.cache:/workspace/.cache \
       -v "${HOME}"/save:/workspace/save \
       -v "${HOME}"/user_path:/workspace/user_path \
       -v "${HOME}"/db_dir_UserData:/workspace/db_dir_UserData \
       -v "${HOME}"/users:/workspace/users \
       -v "${HOME}"/db_nonusers:/workspace/db_nonusers \
       gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0 /workspace/generate.py \
          --base_model=h2oai/h2ogpt-16k-codellama-7b-python \
          --use_safetensors=True \
          --prompt_type=llama2 \
          --save_dir='/workspace/save/' \
          --use_gpu_id=False \
          --score_model=None \
          --max_max_new_tokens=2048 \
          --max_new_tokens=1024

```

**Comment by pseudotensor** [comment]
I am able to run this on latest docker image ensuring CVD is not set, i.e.:

```
unset CUDA_VISIBLE_DEVICES
docker run \
       --gpus all \
       --runtime=nvidia \
       --shm-size=2g \
       -p 7860:7860 \
       --rm --init \
       --network host \
       -v /etc/passwd:/etc/passwd:ro \
       -v /etc/group:/etc/group:ro \
       -u `id -u`:`id -g` \
       -v "${HOME}"/.cache:/workspace/.cache \
       -v "${HOME}"/save:/workspace/save \
       -v "${HOME}"/user_path:/workspace/user_path \
       -v "${HOME}"/db_dir_UserData:/workspace/db_dir_UserData \
       -v "${HOME}"/users:/workspace/users \
       -v "${HOME}"/db_nonusers:/workspace/db_nonusers \
       gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0 /workspace/generate.py \
          --base_model=h2oai/h2ogpt-16k-codellama-7b-python \
          --use_safetensors=True \
          --prompt_type=llama2 \
          --save_dir='/workspace/save/' \
          --use_gpu_id=False \
          --score_model=None \
          --max_max_new_tokens=2048 \
          --max_new_tokens=1024
```

However, again, it's a foundational model and not appropriate for chat without extra effort like the "one_shot" prompt_type.

**Comment by pseudotensor** [comment]
45ebfb1d4669a6790853e9046fdf543e17b948ad

**Comment by fahadshery** [comment]
> Which docker build are you using?
latest i.e.
```
docker --version
Docker version 24.0.7, build afdd53b
```
> 
> Note that this is a foundational model, not instruct tuned. Not sure you intended to use that.
> 
> I've not used this model myself. The error is during loading. The error is related to the vocabulary. i.e. the model has `"vocab_size": 32016`: https://huggingface.co/h2oai/h2ogpt-16k-codellama-7b-python/blob/main/config.json#L25
> 
> E.g. you can try instead: https://huggingface.co/codellama/CodeLlama-7b-Instruct-hf
> 
> Has same config.json vocab size.

I wish to try the models that h2ogpt published. if the model's are there then they should run or at least have clear docker run commands: `--base_model=h2oai/h2ogpt-16k-codellama-7b-python`

**Comment by fahadshery** [comment]
> However, I have no problem loading that model from non-docker case:
> 
> ```
> python generate.py --base_model=h2oai/h2ogpt-16k-codellama-7b-python
> ```
> 
> starts fine.

Docker is easier to spin up and clean up once you're done with the model. Not planning on running anything in non docker environment at this stage tbh

**Comment by fahadshery** [comment]
> I see the same thing when I run this:
> 
> ```
> docker run \
>        --gpus all \
>        --runtime=nvidia \
>        --shm-size=2g \
>        -p 7860:7860 \
>        --rm --init \
>        --network host \
>        -e CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES \
>        -v /etc/passwd:/etc/passwd:ro \
>        -v /etc/group:/etc/group:ro \
>        -u `id -u`:`id -g` \
>        -v "${HOME}"/.cache:/workspace/.cache \
>        -v "${HOME}"/save:/workspace/save \
>        -v "${HOME}"/user_path:/workspace/user_path \
>        -v "${HOME}"/db_dir_UserData:/workspace/db_dir_UserData \
>        -v "${HOME}"/users:/workspace/users \
>        -v "${HOME}"/db_nonusers:/workspace/db_nonusers \
>        gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0 /workspace/generate.py \
>           --base_model=h2oai/h2ogpt-16k-codellama-7b-python \
>           --use_safetensors=True \
>           --prompt_type=llama2 \
>           --save_dir='/workspace/save/' \
>           --use_gpu_id=False \
>           --score_model=None \
>           --max_max_new_tokens=2048 \
>           --max_new_tokens=1024
> ```

Sorry what do you mean you see the same thing? Does it work?

**Comment by fahadshery** [comment]
> I am able to run this on latest docker image ensuring CVD is not set, i.e.:
> 
> ```
> unset CUDA_VISIBLE_DEVICES
> docker run \
>        --gpus all \
>        --runtime=nvidia \
>        --shm-size=2g \
>        -p 7860:7860 \
>        --rm --init \
>        --network host \
>        -v /etc/passwd:/etc/passwd:ro \
>        -v /etc/group:/etc/group:ro \
>        -u `id -u`:`id -g` \
>        -v "${HOME}"/.cache:/workspace/.cache \
>        -v "${HOME}"/save:/workspace/save \
>        -v "${HOME}"/user_path:/workspace/user_path \
>        -v "${HOME}"/db_dir_UserData:/workspace/db_dir_UserData \
>        -v "${HOME}"/users:/workspace/users \
>        -v "${HOME}"/db_nonusers:/workspace/db_nonusers \
>        gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0 /workspace/generate.py \
>           --base_model=h2oai/h2ogpt-16k-codellama-7b-python \
>           --use_safetensors=True \
>           --prompt_type=llama2 \
>           --save_dir='/workspace/save/' \
>           --use_gpu_id=False \
>           --score_model=None \
>           --max_max_new_tokens=2048 \
>           --max_new_tokens=1024
> ```
> 
> However, again, it's a foundational model and not appropriate for chat without extra effort like the "one_shot" prompt_type.

What do you mean CVD? This docker run command looks exactly the same as what I posted above which isn't running?

**Comment by pseudotensor** [comment]
CVD = CUDA_VISIBLE_DEVICES

Try the latest docker image (pull latest nightly).  I have no issues with the command I ran above without the CVD stuff.

**Comment by fahadshery** [comment]
Do you know where the definitions are for `max_max_new_tokens`, `max_new_tokens`...
I am testing 
```--model-id TheBloke/openchat_3.5-16k-GPTQ --port 3000 --quantize gptq --max-input-length 3696 --max-total-tokens 4096 --max-batch-prefill-tokens 4096```

would `max_new_tokens` = `--max-input-length 3696`??
and `max_max_new_tokens` = `--max-total-tokens 4096`??

Many thanks for your help

**Comment by pseudotensor** [comment]
For h2oGPT: https://github.com/h2oai/h2ogpt/blob/5397e0c0ce2eff0997d9420377643543c7b90c5c/src/gen.py#L653-L658
