### ISSUE TITLE
model parameters mapping with Text Generation Inference (TGI)

### ISSUE THREAD

**Issue by fahadshery** [h2oai/h2ogpt#1107]
Hi,

H2ogpt has params like `--max_seq_len` `--max_new_tokens` `--max_max_new_tokens` etc.
some times it is easier to look at TGI params and pass it to the docker command. For example:
```
--model-id TheBloke/Python-Code-13B-GPTQ --port 3000 --quantize gptq --max-input-length 3696 --max-total-tokens 4096 --max-batch-prefill-tokens 4096
```

It would be wonderful if we could follow the same naming convention for easy param mapping?

Cheers

**Comment by pseudotensor** [comment]
TGI convention differs from vLLM and differs from transformers native etc.

**Comment by fahadshery** [comment]
understood
