### ISSUE TITLE
simple custom prompt not working

### ISSUE THREAD

**Issue by fahadshery** [h2oai/h2ogpt#1109]
Hi,

my prompt looks like this:
```
GPT4 User: {prompt}<|end_of_turn|>GPT4 Assistant:
```

I tried to set it up like this:
```
--prompt_type=custom \
--prompt_dict="{humanstr=GPT4 User: ,terminate_response=<|end_of_turn|>, botstr=GPT4 Assistant: }" \
```

but getting the error:
```
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/src/gen.py", line 1215, in main
    get_generate_params(model_lower,
  File "/workspace/src/gen.py", line 4015, in get_generate_params
    raise RuntimeError("Prompt wrong: %s" % error0)
RuntimeError: Prompt wrong: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (<unknown>, line 1)
```

what am I missing?

**Comment by sebastianlutter** [comment]
I guess this is just an syntax issue. The value of the parameter string that arrives in python needs to be a valid python dict, try:
```
--prompt_dict="{ 'humanstr': 'GPT4 User: ', 'terminate_response': '<|end_of_turn|>', 'botstr': 'GPT4 Assistant: '}"
```

**Comment by fahadshery** [comment]
Is there a definition available for how to pass or make a prompt from this simple prompt? 
`GPT4 User: {prompt}<|end_of_turn|>GPT4 Assistant:`?

**Comment by pseudotensor** [comment]
Note that h2oGPT already has that prompt:

https://github.com/h2oai/h2ogpt/blob/4e1f55d15d1ffd3c441e58008e5b5323a477380a/src/prompter.py#L1052-L1084

For completeness, if one loads the UI with that, you can see how prompt_dict is defined, and then pass that as a custom prompt if desired.

Then one will see:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/a8107a64-a0a8-43a9-962a-f59cc1ed0d4b)


i.e. and one can copy-paste that text in custom prompt:

```
{'promptA': '', 'promptB': '', 'PreInstruct': 'GPT4 User: ', 'PreInput': None, 'PreResponse': 'GPT4 Assistant:', 'terminate_response': ['GPT4 Assistant:', '<|end_of_turn|>'], 'chat_sep': '<|end_of_turn|>', 'chat_turn_sep': '<|end_of_turn|>', 'humanstr': 'GPT4 User: ', 'botstr': 'GPT4 Assistant:', 'generates_leading_space': False, 'system_prompt': ''}
```

Then suppose one wants to use it, then one runs:

```
python generate.py --base_model=TheBloke/openchat_3.5-GGUF --prompt_type=custom --prompt_dict="{'promptA': '', 'promptB': '', 'PreInstruct': 'GPT4 User: ', 'PreInput': None, 'PreResponse': 'GPT4 Assistant:', 'terminate_response': ['GPT4 Assistant:', '<|end_of_turn|>'], 'chat_sep': '<|end_of_turn|>', 'chat_turn_sep': '<|end_of_turn|>', 'humanstr': 'GPT4 User: ', 'botstr': 'GPT4 Assistant:', 'generates_leading_space': False, 'system_prompt': ''}"
```

That is I just literally copy-pasted the thing from the UI into `--prompt_type="<past here>"`

Then one sees:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/763f8922-ad78-4a3f-b8b1-61701a23b4d5)


![image](https://github.com/h2oai/h2ogpt/assets/2249614/f55f6ed5-55a8-4ae8-9357-e448008c59db)



![image](https://github.com/h2oai/h2ogpt/assets/2249614/f54ed72b-62bd-49cd-8fbc-af970a72ec18)


In general, when passing things from command line, good to put in quotes when list or dict, we convert to list or dict inside code.


Overall I think it's pretty flexible and easy, but I'll add this example to docs.
