### ISSUE TITLE
How do I use previously downloaded GGUF models?

### ISSUE THREAD

**Issue by scarecrow2k6** [h2oai/h2ogpt#1115]
I have several GGUF models. Is it possible to use them? If so, how? I have looked everywhere for an answer and couldn't find anything. If I paste the link to the folder, it gives me errors. Sorry if this has already been discussed before. Thanks!

**Comment by pseudotensor** [comment]
You should be able to put the full path into the "Choose/Enter Base Model" text box.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/938c7249-2103-4b00-a1cd-c5269058d394)


then click load model:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/0bfa778b-e598-4eac-927f-9cba3381dbc0)


To unload click the unload model, or just choose a new GGUF file and click load -- it'll unload old one for you.

**Comment by fahadshery** [comment]
Hi,

I have also downloaded several models using docker like this:
```
export CUDA_VISIBLE_DEVICES=0
docker run -d \
       --gpus all \
       --runtime=nvidia \
       --shm-size=2g \
       -p 7860:7860 \
       --rm --init \
       --network host \
       -e CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES \
       -v /etc/passwd:/etc/passwd:ro \
       -v /etc/group:/etc/group:ro \
       -u `id -u`:`id -g` \
       -v "${HOME}"/.cache:/workspace/.cache \
       -v "${HOME}"/save:/workspace/save \
       -v "${HOME}"/user_path:/workspace/user_path \
       -v "${HOME}"/db_dir_UserData:/workspace/db_dir_UserData \
       -v "${HOME}"/users:/workspace/users \
       -v "${HOME}"/db_nonusers:/workspace/db_nonusers \
       gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0 /workspace/generate.py \
          --base_model=TheBloke/zephyr-7B-alpha-GPTQ \
          --use_safetensors=True \
          --prompt_type=zephyr \
          --save_dir='/workspace/save/' \
          --use_gpu_id=False \
          --score_model=None \
          --max_seq_len=4096 \
          --max_new_tokens=100000
```
There needs to be a way to download models in a specific directory and then change them in a GUI. For that, one might need to create a models directory and mount it inside the docker container.
How do we achieve that? Can we set the location of the models? Where are the docker models currently downloaded?

**Comment by pseudotensor** [comment]
If you set the env `LLAMACPP_PATH` then all models that are not HF-based will be downloaded there.  i.e. any llama.cpp mdoels like GGUF.
