### ISSUE TITLE
No UI-Window to upload files, bulk upload with Docker

### ISSUE THREAD

**Issue by caxschoen** [h2oai/h2ogpt#1122]
I installed h2oGPT via Docker successfully (Ubuntu 20.4.m, NVIDIA-SMI 470.223.02   Driver Version: 470.223.02   CUDA Version: 11.4)
Version h2ogpt-runtime:0.1.0-150 had a drop window at the Gradio UI  to add additional files. I was able to add some files to UserData.
In Later Version h2ogpt-runtime:0.1.0-180 that is not possible any longer? No drop window. 
How to add files via to UI?
How to add a bulk of files via a directory?
PS: Last version of docker h2ogpt-runtime:0.1.0-194 showed the following error at start: “Found an incompatible version of auto-gptq. Found version 0.4.2+cu118, but only version above 0.4.99 are supported”

**Comment by pseudotensor** [comment]
There is "Upload" button on right inside the prompt window.  There is Ingest button for adding the text entered as url, text, youtube, etc.
