### ISSUE TITLE
Document selection on sidebar

### ISSUE THREAD

**Issue by Blacksuan19** [h2oai/h2ogpt#1123]
Can we have an option to show the document selection dropdown on the sidebar under resource? the current way requires several steps to select specific documents to query and is confusing to people with no technical knowledge, in addition, if document selection tab is disabled, there would be no way to select documents in collection while it is still possible to change collection from sidebar.

in particular this dropdown
![image](https://github.com/h2oai/h2ogpt/assets/10248473/418af450-f9d0-4b39-a53e-a9272d22723c)

should be also available on resources sidebar (below collections makes sense)
![image](https://github.com/h2oai/h2ogpt/assets/10248473/dcc377ba-a73c-4664-a88d-8ed2e4339e75)

**Comment by bw-Deejee** [comment]
I would love this option as well. For Document Q&A it would be great to easily distinquish between querying a whole collection or querying one specific document

**Comment by pseudotensor** [comment]
![image](https://github.com/h2oai/h2ogpt/assets/2249614/21514e73-20da-4e96-84a7-617f54e55371)
