### ISSUE TITLE
Error: H2OOCRLoader: `doctr` package not found

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2ogpt#1124]
When installing your latest version with full document capability according to the instruction that are mentioned in the given link [https://github.com/h2oai/h2ogpt/blob/main/docs/README_LINUX.md](url) it create some dependencies conflicts in between torch and torchvision so that i think **doctr** is not working when hit **max ingest quality** and showing the following error:

`miniconda3/envs/h2ogpt/lib/python3.10/site-packages/doctr/models/classification/effnet/pytorch.py", line 11, in <module>
    from torchvision.models import efficientnet_v2_m as tv_effnetv2
ImportError: cannot import name 'efficientnet_v2_m' from 'torchvision.models' (/home/hemant/.local/lib/python3.10/site-packages/torchvision/models/__init__.py)`

During handling of the above exception, another exception occurred:

`Traceback (most recent call last):
  File "/home/hemant/Documents/Client/narad_221123_client/weseecore/src/gpt_langchain.py", line 2862, in path_to_doc1
    res = file_to_doc(file,
  File "/home/hemant/Documents/Client/narad_221123_client/weseecore/src/gpt_langchain.py", line 2639, in file_to_doc
    model_loaders['doctr'].load_model()
  File "/home/hemant/Documents/Client/narad_221123_client/weseecore/src/image_doctr.py", line 51, in load_model
    raise ValueError(
ValueError: `doctr` package not found, please install with `pip install git+https://github.com/h2oai/doctr.git`.

**Comment by llmwesee** [comment]
Like for **peft** it's also same for **doctr**
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
peft 0.5.0 requires torch>=1.13.0, but you have torch 1.11.0 which is incompatible.`

**Comment by pseudotensor** [comment]
For numpy it's true that happens, but it can be ignored as far as I know.  Never seen any issues, so some package is overconstrained.

I've never seen torch 1 be downgraded to.  What installed torch 1?

**Comment by llmwesee** [comment]
Yep! it first uninstall torch 2.x.x then install torch 1.x.x

**Comment by pseudotensor** [comment]
torch 1 will not work with h2ogpt.
