### ISSUE TITLE
HYDE - quick question and feature request

### ISSUE THREAD

**Issue by bw-Deejee** [h2oai/h2ogpt#1128]
So in the UI HYDE Level 0, 1, and 2 are explained:

> Whether to use HYDE approach for LLM getting answer to embed (0=disabled, 1=non-doc LLM answer, 2=doc-based LLM answer)

I'm not sure if i understand correctly but it seems like in the first HYDE answere it uses only the inherent LLM knowledge, in HYDE answere 2 it uses some additional information for my documents.

- Is this correct, and if so, what do HYDE levels 3-5 do?

Additional questions/requests:
- Why is the model so overly "creative", poetic and using all kinds of emojis in the first couple HYDE answers? This seems a bit over the top as its just making up some literally "magical stuff"
- It would be nice to have the option to only receive the final answere and not see the model generating the weird HYDE responses in between
- Unrelated question: What is the unit of the Chunk size for document chunking in the expert settings? Is it characters, tokens, ...?

**Comment by pseudotensor** [comment]
Hi thanks for questions.

I allow you to change the HYDE prompt now.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/4acffc19-25c0-4155-9ef1-0066ce858daa)

**Comment by pseudotensor** [comment]
* 3-5 just keep iterating using all prior outputs + original query for embedding search.
* It's overly creative in emoji stuff because of your chosen model mostly.
* For now, set stream=False to only get final answer.
* chunk is characters.  So chunk_size=512 is 512 characters.

**Comment by pseudotensor** [comment]
Added ability to only see final result either as CLI option or change in UI/API.

**Comment by ddchan1** [comment]
Hi, how would i configure it so that only the HYDE response displays and not the final response from UserData? The HYDE response gets overwritten by the the final response. Thanks

**Comment by pseudotensor** [comment]
Good idea.  I added another option, on by default, where I accordion the intermediate steps instead of just losing them.

`--hyde_show_intermediate_in_accordion=True` by default now.
