### ISSUE TITLE
problem finding llm's response

### ISSUE THREAD

**Issue by fmoschidi** [h2oai/h2ogpt#1129]
Hi there!i would really appreciate if someone could help me with the location of the llm output response. i would like to elaborate it and with a custom format to it. to make it more clear i'm looking in which object does a new reponse of the llm is saved.

Thanks in advance.

**Comment by pseudotensor** [comment]
What do you want to adjust?  API or UI or both?

The easiest place to adjust is at the very top, in gradio_runner.py for each evaluate_nochat(), bot(), and all_bot().
