### ISSUE TITLE
How to switch between downloaded models

### ISSUE THREAD

**Issue by Zirgite** [h2oai/h2ogpt#1130]
The documentation is unclear how to switch between models. I have downloaded a base model. However when I want to switch to another downloaded model, I cannot do that. All downloaded models are stored C:\Users\User under windows 10. How to switch between them?

**Comment by Zirgite** [comment]
I solved the issue. In fact when downloading the model it is not enough to switch the model from the central drop down menu and press the load button.

It is necessary to make one more step. 
There is a menu that is on the right that may be hidden  but you need to open.'
Choose LLaMa.cpp Model Path/URL (for Base Model: llama)
Here on the path it is the old model. So actually you wont#t switch the model but you will load the old model.

In my case I have downloaded a custom model from the bloke:
https://huggingface.co/TheBloke/digital-socrates-13B-GGUF/resolve/main/digital-socrates-13b.Q6_K.gguf

Then I had not just to use this path in the central menu but also to put the same path to the menu on the right.

https://huggingface.co/TheBloke/digital-socrates-13B-GGUF/resolve/main/digital-socrates-13b.Q6_K.gguf

**Comment by pseudotensor** [comment]
This and other UX related issues with selecting models should be fixed now, thanks!
