### ISSUE TITLE
I am using the code below to use flask to create a rest API for the h2oGPT server: I am getting the responses that I want, but the model does not remember its previous responses. The response received is also given below. Do I need to change the model, and if yes then how do I do it and swtch to what?

### ISSUE THREAD

**Issue by prateekrana17** [h2oai/h2ogpt#1132]
**Error:** 

### I'm sorry, but I cannot summarize my previous answer as I am a language model and do not have the ability
to access or recall previous answers. Each time you ask me a question, I generate a new response based on my training
data and the context of the question. So, I cannot provide a summary of a previous answer as it does not exist in my
memory. Is there anything else I can help you with?**

### Code for API and gradio client:

import json
from gradio_client import Client
import ast
import flask, requests
from flask import Flask, jsonify, request
import logging
import os

HOST_URL = "http://localhost:7860"
client = Client(HOST_URL)

API_KEY = "secret123"

api_name = '/submit_nochat_api'

app = Flask(__name__)

def authorize_request():
    # Check if the 'X-API-KEY' header is present and has the correct value
    api_key = request.headers.get('X-API-KEY')
    if not api_key or api_key != API_KEY:
        response = jsonify({"error": "Unauthorized"})
        response.status_code = 401
        return response

@app.route("/api/prompt_route", methods=["GET", "POST"])
def prompt_route():
    # Authorization check
    auth_response = authorize_request()
    if auth_response:
        return auth_response
    try:
        user_prompt = request.form.get("user_prompt")
        kwargs = dict(instruction=user_prompt, langhain_mode='UserData', langchain_action='Query',
                      top_k_docs=-1, stream_output=False)
        # get result
        res = client.predict(str(dict(kwargs)), api_name=api_name)
        response = ast.literal_eval(res)['response']
        response_dict = {'Answer': response}
        return json.dumps(response_dict)

    except Exception as e:
        logging.error(f"An error occurred: {str(e)}")
        return jsonify({"error": "Internal Server Error"})

if __name__ == "__main__":
    logging.basicConfig(format="%(asctime)s - %(levelname)s - %(filename)s:%(lineno)s - %(message)s", level=logging.INFO)
    app.run(debug=True, port=5110)

**Comment by tkarstaedt** [comment]
Don't know if that's the issue, but you have a typo in "langhain_mode" where a "c" is missing --> "langchain_mode". This way "UserData" is not handed over and I guess this contains the chat history.

**Comment by pseudotensor** [comment]
If you use the OpenAI compliant API, it keeps track of conversations.  Else you need to do yourself on client side using `chat_conversation`  argument that is a list of tuples like [(human, bot), (human, bot), etc.]
