### ISSUE TITLE
Orca 2 and h2oGPT not working with gguf

### ISSUE THREAD

**Issue by Zirgite** [h2oai/h2ogpt#1139]
Has anybody managed to run the hottest model Orca 2 with gguf. 
I manage to run custom models with no problems. But for some reason Orca 2 loads but when prompted fails to show any result. The model work fine with Oobabooga. I wonder as the main advantage of this model is to be a performant brain and use local knoledge.

**Comment by Zirgite** [comment]
Thank you a lot that works.

**Comment by Zirgite** [comment]
![orca1](https://github.com/h2oai/h2ogpt/assets/127785097/6a90ab2b-a2d0-4012-a265-feec8f593476)
![orca2](https://github.com/h2oai/h2ogpt/assets/127785097/f943f07b-8839-420f-849d-ea0fae04fcf7)

**Comment by pseudotensor** [comment]
FYI @Zirgite , the name in the chat shows wrong "llama2-7b" but that will be fixed soon.  It's just a cosmetic bug in UI.

**Comment by bluciano212** [comment]
thanks for your description , I also was trying to use orca2 but  not working , mptchat , solved

ulimit -l unlimited && python3 generate.py --base_model='llama' --model_path_llama=orca-2-7b.Q4_K_M.gguf --max_seq_len=4096 --prompt_type=mptchat --score_model=None --add_chat_history_to_context=True --langchain_mode='UserData' --user_path=/home/lucio/book

I just see the latest UI you added "include web search" and "include chat history" that really good update!
![Screenshot (11)](https://github.com/h2oai/h2ogpt/assets/142985563/83430a9b-d5ef-43a1-a7fd-571e8e0f615a)
