### ISSUE TITLE
Best RAG Settings to Optimize Best Answers

### ISSUE THREAD

**Issue by dakotal4** [h2oai/h2ogpt#1140]
I am dealing with very long documents that may contain very repetitive information and structure. What would be the best optimized RAG settings for long-form documents in regards to top_p, top_k, and chunk sizes? Right now I am using the mistral model because it has a longer context window and can use more sources to create an answer. I have more gpus if I need to work with a higher parameter model but trying to maximize the outputs of mistral. Thank you.

**Comment by pseudotensor** [comment]
I recommend zephyr 7b beta for RAG to avoid hallucinations or misrepresenting cases where there is no answer in doc.

However, we've found that it does poorly beyond 4k tokens, so I'd set --max_seq_len=4096 still.

Whatever mistral did is great, but not good for long context.
