### ISSUE TITLE
Model responding from other documents that are not selected

### ISSUE THREAD

**Issue by Blacksuan19** [h2oai/h2ogpt#1142]
I have multiple files in userData and specify a particular document to use for context before doing a query, however, the model still provides results from other documents that are not explicitly selected on the document selection page.

in the example below I explicitly selected the file for patient with name `Tamisha203 Moira454 Collier206`, however the model still used the other patient's data and provided response from that data instead of the selected file.

File selection
![image](https://github.com/h2oai/h2ogpt/assets/10248473/06956488-7b8a-48c8-86ac-70470b000c90)

Model response (includes files that were not selected as context)
![image](https://github.com/h2oai/h2ogpt/assets/10248473/423b4975-7108-46f8-8744-2c0b82b203dd)

I can reproduce this behavior with both `TheBloke/Mistral-7B-Instruct-v0.1-GGUF` and `TheBloke/OpenHermes-2-Mistral-7B-GGUF`

**Comment by pseudotensor** [comment]
Thanks will check  if there is some regression.

**Comment by llmwesee** [comment]
I'm also facing the same issue.

**Comment by pseudotensor** [comment]
So far unable to reproduce.   I started fresh in UI and no collections.  I uploaded 2 files. One has to do with AWS, the other is some funeral pdf.  I selected the funeral one and asked about AWS, and the model says nothing relevant and only showed funeral (no AWS) docs.

**Comment by pseudotensor** [comment]
We also have specific tests for this doc selection stuff:

https://github.com/h2oai/h2ogpt/blob/089e94d38fd4f25feb7ec24ef968a6167c5f0781/tests/test_langchain_units.py#L1789



Are you able to repro with any docs at all?  Or perhaps the names are special in some way when it happens?  Need more info, thanks!

**Comment by Blacksuan19** [comment]
I can replicate the issue with files from `user_path` in shared mode while using Query action to be specific.

selected only immunization document.
![image](https://github.com/h2oai/h2ogpt/assets/10248473/87526a0c-f4c4-4eaf-a4b2-7f1873d2492a)


ask about encounters and receive answers from encounters document despite it not being selected.
![image](https://github.com/h2oai/h2ogpt/assets/10248473/83fc423a-01f6-4709-86d7-62ed5205af3b)

here's another example with very different documents.

explicitly selecting encounters file.
![image](https://github.com/h2oai/h2ogpt/assets/10248473/e3d3c874-ea25-4f92-ae13-3aef59d3cc4a)


ask about blockchain and get response from a non-selected document.
![image](https://github.com/h2oai/h2ogpt/assets/10248473/ec89cc7d-10ce-4de9-972e-22c686356c33)

**Comment by Blacksuan19** [comment]
I think the issue occurs because the files are in nested folders inside `user_path`. uploading files from the UI places them in the root of `user_path` which works as expected.

select blockchain document
![image](https://github.com/h2oai/h2ogpt/assets/10248473/3940cd07-ca65-41d3-be4b-6db3d4ec222d)


ask about non-selected document
![image](https://github.com/h2oai/h2ogpt/assets/10248473/2f7d0f7a-d780-44a1-9472-9e924b97f612)

we intend to upload files to `user_path` via an external API grouped by folders (`uuid/patient_name`) instead of uploading files manually from the web UI due to the number of files and need for grouping, it would be perfect if the selection menu can also allow selecting entire folders within `user_path` instead of only specific files.

**Comment by pseudotensor** [comment]
Even with nesting I see no problem. 

I have:
```
(/data/conda/h2ogpt) jon@pseudotensor:~/h2ogpt$ find user_path
user_path
user_path/sub1
user_path/sub1/README.md
user_path/sub1/whisper.pdf
user_path/sub2
user_path/sub2/next.txt
user_path/sub2/gpu_mem_track.py
```

And I select readme.md and get:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/1b0a3e9a-a42c-4f9c-8d07-64cfffb7ea65)


So asking specifically about the other doc that would match normally, and it only sees the readme.

**Comment by pseudotensor** [comment]
```
(/data/conda/h2ogpt) jon@pseudotensor:/workspace/user_path$ mkdir -p /workspace/user_path/9ab046dc-e150-480a-b3db-324eaf6143aa/Tamisha203Moira454Collier206/res
(/data/conda/h2ogpt) jon@pseudotensor:/workspace/user_path$ echo "Zulu is hot" > /workspace/user_path/9ab046dc-e150-480a-b3db-324eaf6143aa/Tamisha203Moira454Collier206/res/Encounter1.json
(/data/conda/h2ogpt) jon@pseudotensor:/workspace/user_path$ echo "Zulu is fun" > /workspace/user_path/9ab046dc-e150-480a-b3db-324eaf6143aa/Tamisha203Moira454Collier206/res/Encounter2.json
(/data/conda/h2ogpt) jon@pseudotensor:/workspace/user_path$ echo "Monkey Island is cold" > /workspace/user_path/9ab046dc-e150-480a-b3db-324eaf6143aa/Tamisha203Moira454Collier206/res/Encounter3.json
(/data/conda/h2ogpt) jon@pseudotensor:/workspace/user_path$ echo "Monkey Island has balls" > /workspace/user_path/9ab046dc-e150-480a-b3db-324eaf6143aa/Tamisha203Moira454Collier206/res/Encounter4.json
(/data/conda/h2ogpt) jon@pseudotensor:/workspace/user_path$ echo "Monkey teeth are green" > /workspace/user_path/9ab046dc-e150-480a-b3db-324eaf6143aa/Tamisha203Moira454Collier206/res/Encounter5.json

```

**Comment by pseudotensor** [comment]
I'm able to repro the problem, not sure what the issue is yet exactly.  But the filter fails to work for some reason, and h2oGPT knows one intended to get documents from a non-empty database, so it reverts to no filter.

**Comment by pseudotensor** [comment]
I didn't really repro exact thing I think.  The jsons I made were not really json, just text, and those exceptional docs didn't have all metadata in them, and shouldn't have been selectable.  I fixed that in the above linked PR.

FYI I ran with:
```
python generate.py --verbose=True --score_model=None --pre_load_embedding_model=False --gradio_offline_level=2 --base_model=llama --model_path_llama=zephyr-7b-beta.Q5_K_M.gguf --user_path=/workspace/user_path/ --langchain_mode=UserData2 --langchain_modes="['UserData2', 'LLM']" --langchain_mode_paths="{'UserData2': '/workspace/user_path/'}" --langchain_mode_types="{'UserData2': 'shared'}"
```


Now trying real json:

```
mkdir -p /workspace/user_path2/9ab046dc-e150-480a-b3db-324eaf6143aa/Tamisha203Moira454Collier206/res
echo '{"content": "Zulu is hot"}' > /workspace/user_path2/9ab046dc-e150-480a-b3db-324eaf6143aa/Tamisha203Moira454Collier206/res/Encounter1.json
echo '{"content": "Zulu is fun"}' > /workspace/user_path2/9ab046dc-e150-480a-b3db-324eaf6143aa/Tamisha203Moira454Collier206/res/Encounter2.json
echo '{"content": "Monkey Island is cold"}' > /workspace/user_path2/9ab046dc-e150-480a-b3db-324eaf6143aa/Tamisha203Moira454Collier206/res/Encounter3.json
echo '{"content": "Monkey Island has balls"}' > /workspace/user_path2/9ab046dc-e150-480a-b3db-324eaf6143aa/Tamisha203Moira454Collier206/res/Encounter4.json
echo '{"content": "Monkey teeth are green"}' > /workspace/user_path2/9ab046dc-e150-480a-b3db-324eaf6143aa/Tamisha203Moira454Collier206/res/Encounter5.json

python generate.py --verbose=True --score_model=None --pre_load_embedding_model=False --gradio_offline_level=2 --base_model=llama --model_path_llama=zephyr-7b-beta.Q5_K_M.gguf --user_path=/workspace/user_path2/ --langchain_mode=UserData3 --langchain_modes="['UserData3', 'LLM']" --langchain_mode_paths="{'UserData3': '/workspace/user_path2/'}" --langchain_mode_types="{'UserData3': 'shared'}"
```


If I select the first doc, that is the only doc that shows up.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/d4036b88-2c16-49e7-84ee-aab4c1b94f9a)





So I'm still unable to repro, unless your jsons were invalid.

**Comment by pseudotensor** [comment]
Can you guys make an example like the above that reproduces?

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/pull/1151 adds the filtering by content or source file you asked about, it's good idea.

I still cannot reproduce the original problem.  Please give an example like I shared.

**Comment by pseudotensor** [comment]
Checking...

Bit confused by your lines here:
```
        --visible_langchain_actions="['Query', 'Summarize']" \
        --langchain_action='Extract' \
```

You want visible modes to be query and summarize but default to be extract, I don't know what that will do but I'm expecting you didn't intend to do that.

**Comment by pseudotensor** [comment]
What I ran:

```
(/data/conda/h2ogpt) jon@pseudotensor:~/h2ogpt$ ls -alrt ~/user_path/
total 132
-rw-rw-r--   1 jon jon  3415 Dec  1 10:17 _meta.json
-rw-rw-r--   1 jon jon 49406 Dec  1 10:17 Encounters.json
-rw-rw-r--   1 jon jon 14161 Dec  1 10:17 Immunization.json
drwxrwx--- 324 jon jon 53248 Dec  1 19:46 ../
drwx------   2 jon jon  4096 Dec  1 22:18 ./

```

```bash
mkdir -p ~/.cache
mkdir -p ~/save
mkdir -p ~/user_path
mkdir -p ~/db_dir_UserData
mkdir -p ~/users
mkdir -p ~/db_nonusers
docker run \
       --gpus '"device=0"' \
       --runtime=nvidia \
       --shm-size=2g \
       -p 7860:7860 \
       --rm --init \
       --network host \
       -v /etc/passwd:/etc/passwd:ro \
       -v /etc/group:/etc/group:ro \
       -u `id -u`:`id -g` \
       -v "${HOME}"/.cache:/workspace/.cache \
       -v "${HOME}"/save:/workspace/save \
       -v "${HOME}"/user_path:/workspace/user_path \
       -v "${HOME}"/db_dir_UserData:/workspace/db_dir_UserData \
       -v "${HOME}"/users:/workspace/users \
       -v "${HOME}"/db_nonusers:/workspace/db_nonusers \
       gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0 /workspace/generate.py \
          --base_model=h2oai/h2ogpt-4096-llama2-7b-chat \
          --use_safetensors=True \
          --prompt_type=llama2 \
          --save_dir='/workspace/save/' \
          --use_gpu_id=False \
          --user_path=/workspace/user_path \
          --langchain_mode="UserData" \
          --langchain_modes="['UserData', 'LLM']" \
          --score_model=None \
          --max_max_new_tokens=2048 \
          --max_new_tokens=1024
```

after loading, I go to document selection tab and click synchronize and see:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/e2c8f41f-15af-4ca0-b22c-147255d181d1)

I then select only one doc:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/12fdbf14-5811-49d8-ab44-611a2447b686)


Then in a query I see:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/5b543dac-dfce-43b6-ac73-58636c7558aa)



So seems I am able to repro!

**Comment by pseudotensor** [comment]
Repros outside docker too:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/248795ec-820f-42e3-a0fc-973e73cd8eea)

**Comment by pseudotensor** [comment]
Ok fixed:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/dc390269-30aa-46fb-a5c2-e2b91d582f6f)

**Comment by pseudotensor** [comment]
47946fb1123522452a6dfbd9ad32d46a2b5c210e

**Comment by pseudotensor** [comment]
I added work-around so search even with old db works.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/956bfbee-e657-4c02-80f6-bdfff5505293)


Just the doc view for json for these old files doesn't work.

**Comment by Blacksuan19** [comment]
thank you! I can confirm the issue is now resolved.
