### ISSUE TITLE
Very Urgent : Please help to use offline downloaded model as huggingface is blocked

### ISSUE THREAD

**Issue by sanket038** [h2oai/h2ogpt#1143]
My organization has blocked huggingface link and unblocking any url takes around 20-25 days after request. While using personal laptop, it works like a charm and I was able to ingest and get responses but I now want to use in my office laptop to present.

I have downloaded GGUF offline models from Gpt4all website (https://gpt4all.io) as it is not blocked. You can see these models in the bottom of the page when you visit the link. I then copied these models to home directory of h2ogpt and using them in --base_model=xxxx

Now, I have tried multiple times, changed things, referred to FAQ on changing models but still after executing the '''python generate.py xxxxxxxx''' it tries to connect to huggingface and fails.

Please let me know how to solve this, trying since 2 days with no luck 🙁

@pseudotensor @Mathanraj-Sharma Requesting your help here please. Thank you

**Comment by Mathanraj-Sharma** [comment]
@sanket038 could you please add the stack trace of the error?

**Comment by sanket038** [comment]
@Mathanraj-Sharma Thank you for replying. Sorry I am pasting from mobile phone so don't have code characters to paste. So pasted directly.

Please see below. 


Traceback (most recent call last):
File "D:|LLM|h2ogpt-main\generate.py", line 16, in <module>
entrypoint_main()
File "D:ILLM|h2ogpt-main\generate.py", line 12, in entrypoint_main
H2O_Fire (main)
File "D:ILLM|h2ogpt-main|sre\utils.py", line 65, in
H20_Fire fire.Fire (component=component, command=args)
File "C:
ProgramData Anaconda3\envs\h20|ib|site-
packages|fire|core.py", line 141, in Fire
component_trace = _Fire(component, args,
parsed_flag_args, context, name)
File "C:
ProgramData Anaconda3\envs|h20| ib|site-packages|fire|core.py", line 475, in _Fire component, remaining_args =
_CallAndUpdateTrace(
File "C:
ProgramData Anaconda3|envs|h20ib|site-
packages|fire\core.py", line 691, in _CallAndUpdateTrace
component = fn(*varargs,
, **kwargs)
File "D:ILLMh2ogpt-main sro\gen.py", line 1414,
in main
model=get_embedding(use_openai_embedding, hf_embedding_model=hf_embedding_model,
File "D:ILLM|h2ogpt-main\src\gpt_langchain.py",
line 423, in get_embedding
embedding =
HuggingFaceEmbeddings (model_name=hf_embed ding_model, model_kwargs=model_kwargs)
File "C:
\ProgramData|Anaconda3\envs|h20|lib|site-
packages|langchain\embeddings|huggingface py", line 65, in _init_ self.client =
sentence_transformers.SentenceTransformer(
File "C:
ProgramData Anaconda3|envs|h20ib|site-
packages|sentence_transformers|SentenceTransfo rmer.py", line 87, in _init.
snapshot_download (model_name_or_path,
File "C:
ProgramData Anaconda3\envs|h2o|lib|site-packages\sentence_transformers\util.py", line 442, in snapshot_download

model_info = _api.model_info(repo_id=repo_id,
revision=revision, token=token)
File "C:
\ProgramData|Anaconda3\envs|h2o|lib|site-
packages|huggingface_hub|utils validators.py", line 118, in.
_inner_fn
return fn(*args,
**kwargs)
File "C:
\ProgramData\Anaconda3\envs|h2o|lib|site-
packages|huggingface_hub|hf_api.py", line 1677, in model_info
r = get_session().get(path, headers=headers,
timeout=timeout, params=params)
File "C:
\ProgramData|Anaconda3\envs|h20|lib|site-
packages|requests\sessions.py", line 602, in get return self.request ("GET", url, **kwargs)
File "C:
ProgramData Anaconda3|envs|h20ib|site-
packages|requests\sessions.py", line 589, in request
resp = self.send (prep, **send_kwargs)
File "C:
\ProgramData|Anaconda3\envs|h20|lib|site-
packages|requests|sessions.py", line 703, in send
r = adapter.send (request, **kwargs)
File "C:
ProgramData Anaconda3\envs\h20|ib|site-
packages|huggingface_hub|utils\_http.py", line 63, in send
return super).send (request, *args,
**kwargs)
File "C:
ProgramData Anaconda3\envs\h20|ib|site-
packages|requests|adapters.py", line 519, in send raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError:
(MaxRetryError ("HTTPSConnectionPool(host='hug.
gingface.co', port=443): Max retries exceeded with url: api models/sentence-transformers/all-MiniLM-L6-v2 (Caused by
NewConnectionError('<urllib3.connection.HTTPSC
onnection object at 0x0000022B15BBAD40>:
Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"), '(Request ID:
15db5c5f-0d43-4b3a-a082-ba4a16680a6e)')

**Comment by sanket038** [comment]
> @sanket038 could you please add the stack trace of the error?
> 
> 
> 
> Also did you try everything mentioned here https://github.com/h2oai/h2ogpt/blob/6a2f160efc2d94e20000c9081996d1cc320dbf62/docs/README_offline.md?plain=1?

I have tried these steps but nothing worked. The solution of having things work offline is to let the UI run first and connect to huggingface to download required model. Once done, it generates all the necessary folders, paths, cache files and other dependencies, after that, we can make it work offline just by replacing models in the path or update ./cache folders.

**Comment by Mathanraj-Sharma** [comment]
@pseudotensor any suggestions for this?

**Comment by pseudotensor** [comment]
@sanket038 The https://github.com/h2oai/h2ogpt/blob/main/docs/README_offline.md#moderately-easy-way is not running the UI but instead looks at what would run and populates the ~/.cache folder and other folders with some required things.  You can run that online, then zip-up the folders mentioned in the readme, then use that in your office.

**Comment by pseudotensor** [comment]
If you follow offline (and have the .cache folder unzipped from online original use), then you  just do to run:
```
HF_DATASETS_OFFLINE=1;TRANSFORMERS_OFFLINE=1 python generate.py --gradio_offline_level=2 --gradio_offline_level=2 --base_model=llama --llama_model_path=zephyr-7b-beta.Q5_K_M.gguf
```

as in the docs.

The only issue is that if you are using a non-HF GGUF file or something, you need to specify the actual file instead of the HF name, since we can only make it easy to map HF name -> file name if have internet, as in the above.

You cannot do:

```
HF_DATASETS_OFFLINE=1;TRANSFORMERS_OFFLINE=1 python generate.py --gradio_offline_level=2 --gradio_offline_level=2 --base_model=TheBloke/zephyr-7B-beta-GGUF
```
since the mapping from that name to get file etc. is not trivial and only possible with internet.


I ran above fully offline and get this:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/96ef21f6-695f-4cc1-9b80-a568789b90e4)


So all works as in the docs.
