### ISSUE TITLE
Error: Replacing 'langchain' with 'langchain_experimental'

### ISSUE THREAD

**Issue by MSZ-MGS** [h2oai/h2ogpt#1144]
I have updated all the new dependencies today and I started receiving below error:

![image](https://github.com/h2oai/h2ogpt/assets/65172063/6f7f3d00-5ba0-4a64-810f-c152a17b040f)

Attached file is the full log.
[Error Log.txt](https://github.com/h2oai/h2ogpt/files/13501324/Error.Log.txt)

**Comment by pseudotensor** [comment]
You must still have old langchain.  Probably best to start with fresh env as the gradio4 changes were extensive in terms of packages.

**Comment by MSZ-MGS** [comment]
You are right, I found the code somehow not updated.

It worked after the update.
Thank you very much!
