### ISSUE TITLE
Can not use the max_seq_len for mistral model

### ISSUE THREAD

**Issue by dakotal4** [h2oai/h2ogpt#1145]
For some reason I can not apply the highest max_seq_len of the mistral model when using it. In this instance, I am using half of the maximum position embeddings it has to offer. After 8192 context length, I can not even get answer and I have enough gpu memory to withstand it. I have changed the LLM to instruct with the correct prompt_type @pseudotensor, but still getting weird outputs. Is it a with my max_max_new_tokens value or something different?

![image](https://github.com/h2oai/h2ogpt/assets/145373637/99948a6f-c4c0-4192-8fda-21c10fb78f5b)
![image](https://github.com/h2oai/h2ogpt/assets/145373637/3d92b5f9-fbf9-45e8-8af8-86c9eede9646)
![image](https://github.com/h2oai/h2ogpt/assets/145373637/39289862-707c-44a6-8ec8-7c881540955e)
![image](https://github.com/h2oai/h2ogpt/assets/145373637/4343990a-5cad-4659-81c5-8669bc7c7860)

**Comment by pseudotensor** [comment]
While they advertise mistral at 8k and the embeddings are 32k, the model is not trained to handle more than 4k as we have found.  It does quite poorly if info is outside 4k.  So I'd stick to max_seq_len=4096 or use a model specifically fine-tuned for long context.
