### ISSUE TITLE
What does "Daily maintenance at midnight PST will not allow reconnection to state otherwise." mean?

### ISSUE THREAD

**Issue by cherrerajobs** [h2oai/h2ogpt#1146]
Do I have to be connected to the internet to use h20gpt? I'm confused because a when using the software and adding PDFs to the database when I restarted the app all that work dissapeared and there was no database. Does it mean I have to create an account to upload the database to the internet, but do it before midnight?

**Comment by pseudotensor** [comment]
I should show that only for public instances case, will fix.

You should login via login tab to persist your state of collections and chats.

No, it doesn't use internet to do that.

**Comment by cherrerajobs** [comment]
Ah gotcha, thank you so much for this program, it's awesome!
