### ISSUE TITLE
Error: list' object has no attribute 'update' |  When attempting to login

### ISSUE THREAD

**Issue by cherrerajobs** [h2oai/h2ogpt#1147]
![image](https://github.com/h2oai/h2ogpt/assets/8894763/c1734a5b-dadb-4edd-a401-1567c6d6140c)
![image](https://github.com/h2oai/h2ogpt/assets/8894763/f64195b8-804e-428f-abc7-48d48a2f01a2)

When I try to login to an existing account I "made" (By typing a new username and password and "logging in) I get an error. What is the proper way of logging in to a single account?

Edit: Is the caused by failing to shut down properly using the button below?
![image](https://github.com/h2oai/h2ogpt/assets/8894763/35886e39-1858-4347-9d26-8cdc79a742fa)

**Comment by pseudotensor** [comment]
Thanks for reporting.  Should be fixed now.  Login stuff is harder to test since less automatic to test.
