### ISSUE TITLE
Beginner Question: How to generate responses programmatically with h2ogpt?

### ISSUE THREAD

**Issue by lancejpollard** [h2oai/h2ogpt#115]
My ideal use case would be to give it a prompt and read the output either through a bash script or a Node.js script. It it possible to do this with h2ogpt? If so, what is a brief example of some code/pseudocode to get started. Do I need to train my own model or does it have a robust model already built out of terabytes of web data like ChatGPT? If it is not like ChatGPT in its robustness, how is it different?

Thank you for having this _open source_ version! Excited to learn more about this use case and start exploring :)

**Comment by pseudotensor** [comment]
I'm probably not answering your actual question, but let me know!

The repository includes the gradio chatbot and all models are on Huggingface as publicly available.  So once everything is pip installed, just do:

```
python generate.py --base_model=h2oai/h2ogpt-oig-oasst1-256-6.9b
```
to get started very quickly.  If one wants to load-unload various models in gradio app, you should just do:

```
python generate.py
```
and load in models tab.

===

If one wants to use it as a client, we provide client code that talks to the gradio server:

https://github.com/h2oai/h2ogpt/blob/main/client_test.py

===

If one wants to use it as just a model, then it's like usual on HF with typical usage:

https://huggingface.co/h2oai/h2ogpt-oig-oasst1-256-6.9b#usage

**Comment by lancejpollard** [comment]
@pseudotensor thanks for the initial response! I am completely new to language models so I don't have the context to know a lot of where to begin. All I know is I want to invoke a chatgpt-like call with a prompt, and get a response (as JSON/text/whatever), from like a bash/Python/Node.js script. I don't see how to do that still from your example, and still unclear how this compares in quality/knowledge of ChatGPT.

What does this do, do I pass it a prompt and get a response?

```bash
python generate.py --base_model=h2oai/h2ogpt-oig-oasst1-256-6.9b
```

For example, ChatGPT's API is like this in Node.js:

```js
getResponseAsText().then(text => console.log(text))

async function getResponseAsText() {
  const completion = await openai.createCompletion({
    model: "text-davinci-003",
    prompt: "How are you today?",
  });
  return completion.data.choices[0].text;
}
```

I can easily make this into a shell/bash script. How can I do the same sort of thing with h2ogpt's python API or CLI?

**Comment by pseudotensor** [comment]
@this added an OpenAI like API which should satisfy that particular need.  It's still a bit WIP due to some package dependency issues.

Otherwise, the simplest gradio client call would be:
```
from gradio_client import Client
client = Client(os.getenv('HOST', "http://localhost:7860"))

# string of dict for input
kwargs = dict(instruction_nochat='Who are you?')
res = client.predict(str(dict(kwargs)), api_name='/submit_nochat_api')

# string of dict for output
response = ast.literal_eval(res)['response']
assert 'I am h2oGPT' in response or "I'm h2oGPT" in response or 'I’m h2oGPT' in response
```

**Comment by jiapei100** [comment]
@pseudotensor 
What if **NO** `gradio` but  just a **huggingface** server?

Which **client** is to be adopted??

**Comment by pseudotensor** [comment]
The text-generation-inference server has a client that we use to talk to it.  That also has a REST API one can curl to.

**Comment by jiapei100** [comment]
@pseudotensor 
I'm using `client.generate_stream`. it looks the replied messages are **NOT quite accurate** ????
