### ISSUE TITLE
Question: Does CaptionBlip2 keep the model in memory if attempting to caption multiple images?

### ISSUE THREAD

**Issue by cherrerajobs** [h2oai/h2ogpt#1153]
![image](https://github.com/h2oai/h2ogpt/assets/8894763/8353bfcc-5950-4e3e-ab99-dffe3f146a2d)
I'm not sure why it errors (Probably ran out of memory?) Wondering, _if it did work_, whether it would process everything without needing to load those shards again.

**Comment by pseudotensor** [comment]
Probably something bad happened yes and it's cascade.  Do you have more complete logs?  I pushed fix for the cascade I think.
