### ISSUE TITLE
Slow on RAG with ChromaDB of 5GB

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#1159]
Hi,
With the latest code I see some degradation from the issue that was fixed here : https://github.com/h2oai/h2ogpt/issues/870
It's takes about 20 seconds to get a response with -1 (Number of documents)  and with 3 docs it takes about 8 seconds.

Thanks

**Comment by slavag** [comment]
@pseudotensor any thoughts on that ? Thanks

**Comment by pseudotensor** [comment]
Downloading the 5GB old chroma and 9GB new chroma I was testing before.

**Comment by pseudotensor** [comment]
@slavag What is slow exactly?  What operation?  I don't see any slowness so far.

**Comment by slavag** [comment]
@pseudotensor The start up time is not an issue, takes about 10-15 sec, that's fine.
Loading DB also quick : Docs: >=4028 Chunks: 500956 (Chroma >= 0.4), 5GB
But Q&A is slow, as any question (with params -1 docs with temp 0.01, top P 0.001, Top K 3) takes about ~19 sec. Not only first question. This was much faster sometime ago, also with Chroma >= 0.4.
I can't say where those 19 seconds spend, it would be nice to have some logs in that area, to see where exactly time is spent. 

Thanks

**Comment by pseudotensor** [comment]
@slavag Please run with --verbose=True --debug=True and look at what is logged.  You should see some stuff from langchain about prompt and output once LLM picks it up before generation.

What is time between your click for query and that LLM langchain stuff showing up?

**Comment by slavag** [comment]
@pseudotensor Thanks, well indeed db query takes ~1.3 seconds. So it's not DB. I'm doing a simple Q&A on the collection.
So, left ~16 seconds spent in different langchain chains for preparing the answer.

Thanks

**Comment by pseudotensor** [comment]
The rest then is just the LLM, there's nothing left after the db part, as long as you are doing query.  If you are doing summarization/extraction, that can be more.

You can tune the speed of the LLM part if you tune top_k_docs.  -1 fills the context, which is not always preferred.  E.g. if using mistral/zephyr by default, it'll fill up to 32k tokens, which is nuts, as model doesn't actually perform well.

Apart from top_k_docs, more direct control over context filling can be done with max_input_tokens (setting default or choosing each query) or for LLM setup choose --max_seq_len=4096 or something smaller so overall the model isn't over-used.

I'll close for now, I expect some of what I shared just now should help with the LLM side.  If you have details about the command you run etc. I  can help further.
