### ISSUE TITLE
overlapping record, ingest, and upload buttons

### ISSUE THREAD

**Issue by Blacksuan19** [h2oai/h2ogpt#1160]
with sst disabled
![image](https://github.com/h2oai/h2ogpt/assets/10248473/a7455533-9a6a-4f07-9d59-6de60212cd23)

with sst enabled
![image](https://github.com/h2oai/h2ogpt/assets/10248473/1dae513d-ca02-48c5-be38-06143e0fa748)

### how to reproduce
run the latest docker image with sst disabled or enabled

**Comment by pseudotensor** [comment]
Thanks.  I don't see it, I presume it's details of browser and OS that are hard to control.

If you want to change the code you can fudge with the numbers here:

https://github.com/h2oai/h2ogpt/blob/6955b9b3a694014d1a0f62fcc838e0785050c11d/gradio_utils/css.py#L94-L146

i.e. "right" ones.
