### ISSUE TITLE
How to update  to the most recent `MAIN` (or nightly) release if I have used the one click installer for windows for my current installation?

### ISSUE THREAD

**Issue by grabani** [h2oai/h2ogpt#1175]
Hi there, how can I update H2OGPT to the most recent `MAIN` (or nightly) release if I have used the one click installer for windows for my current installation?

**Comment by pseudotensor** [comment]
I think others like @cherrerajobs are doing that.  Maybe he can contribute some docs to what he does.

**Comment by grabani** [comment]
The outline you are describing above does not seem to take advantage of the fact that you already have an installed version of H2OGPT using the installer.

What I was looking to identify was a method by which we could simply update a **few** files (which had been updated as part of a bug / feature release) manually, or simply copy the recently available `main `release folders into the installed file structure of H2OGPT (which had been previously installed using the on-click method).

The steps that I took, which did not ultimately work were to, download the latest `main `release and simply replace all of the H2O GPT folders on my laptop (e.g. `C:\Users\xxx\AppData\Local\Programs\h2oGPT` with the source code files of the `main ` release and then starting/clicking or executing the .exe file for H2O GPT. Unfortunately this resulted in the browser tab not appearing which obviously suggests that the copying of the files did not work. Maybe I am slightly naïve but I thought that would be sufficient as the updates were made in only a few files. Simply exchanging those source files within the installed H2O GPT would solve the problem and update the installation.

Could you take a few minutes to explain why that approach would not work? I could have done that at the beginning and that undermines the whole question of updating a current installation rather than doing a completely new **manual** installation. Thank you.

**Comment by grabani** [comment]
Hi There
Any update? I know, I Know. Its the holiday season! 😊

**Comment by pseudotensor** [comment]
The installation often changes packages, so I'm not sure it's super easy to identify what to add to the one-click installer files.

However, the python env can be activated and used like normal, and packages can be installed, but i'm not sure this is reliable since the packages are often complex in changes.

Probably the best option is to have the one-click installer installed, but overwrite the installed env with a new env that is manual install.

I'll try to get a windows one-click up by Jan 4, but yes holidays slow things down.

**Comment by grabani** [comment]
Thank you for the update; and your continued efforts, they are much appreciated.

**Comment by pseudotensor** [comment]
Hi, I updated windows support for both one-click and batch script (new) installation.  Should be easier to install "manual" way now.

I now include `pip` as well in the packages, and one can update to new versions of packages more easily now.  See README.md and the example of torch itself.
