### ISSUE TITLE
pydantic.v1.error_wrappers.ValidationError: 1 validation error for H2OChatOpenAI

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2ogpt#1183]
My previous h2ogpt version works well with vllm inference server without openai api key but when i switched to the latest version and do inferencing with vllm server without openai api key then it throws the following error:

`File "/home/miniconda3/envs/gpt051223/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for H2OChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)
`
Can you make vllm server flexible for work well without openai api key inside h2ogpt.

**Comment by llmwesee** [comment]
After making changes now got this:
`File "/home/miniconda3/envs/gpt051223/lib/python3.10/site-packages/openai/_utils/_utils.py", line 301, in wrapper
    return func(*args, **kwargs)
TypeError: Completions.create() got an unexpected keyword argument 'batch_size'`

**Comment by pseudotensor** [comment]
Do you have a more complete stack trace?

**Comment by pseudotensor** [comment]
Also, I don't understand why you have `H2OChatOpenAI` .  Are you using `vllm_chat`?  Can you give details about how you run things?

**Comment by pseudotensor** [comment]
I pushed a change in case you are using vllm_chat.  I have never tested that option.

**Comment by llmwesee** [comment]
@pseudotensor I attaching the screenshot for your reference like which commands i ran:

First I activate the vllm environment & hit the command
![Screenshot from 2023-12-08 13-54-49](https://github.com/h2oai/h2ogpt/assets/137979399/cbb274da-2c1a-4b7b-b74d-8cb76035e006)

Then in separate  environment for inferencing through H2ogpt I hit the command
![Screenshot from 2023-12-08 13-56-08](https://github.com/h2oai/h2ogpt/assets/137979399/585e2aab-3986-4463-86cd-b48b4eec1716)

Till now both things ran smoothly but when I ask query like "hi" then it throws the error
![Screenshot from 2023-12-08 14-03-36](https://github.com/h2oai/h2ogpt/assets/137979399/2f0cda82-736e-4521-8bee-c11c2a00023e)

**Comment by llmwesee** [comment]
@pseudotensor okk Thanks!  I understand where i made mistake.

SOLVED!!!

**Comment by pseudotensor** [comment]
@llmwesee What was the resolution?  Avoid vllm_chat and use vllm?  I think even vllm_chat will work now after most recent commit.  Least it shouldn't complain about batch_size being passed at that location.

Just ensure the prompt is known so "plain" not used for instruct models.  The particular one you used is there in src/prompter.py.

**Comment by llmwesee** [comment]
@pseudotensor Yeah, It solved by avoiding vllm_chat and using vllm instead.
