### ISSUE TITLE
Problem getting h2o client and client tests to work

### ISSUE THREAD

**Issue by hpxiong** [h2oai/h2ogpt#1185]
I'm not able to get h2o client to work. Your suggestion is appreciated. 

I tried to run h2o_client tests with local h2oGPT server running and getting the below error. 

```console
tests/test_client.py::test_readme_example[True] HTTPConnectionPool(host='0.0.0.0', port=7860): Max retries exceeded with url: 
/config (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFEAB04AD0>: Failed to establish a 
new connection: [WinError 10049] The requested address is not valid in its context'))
```

I tried to run the same test from another system, remotely connecting to the server with h2oGPT running, I'm getting a different error:

```console
            raise RedirectHandshake(response_headers["Location"])
        elif status_code != 101:
>           raise InvalidStatusCode(status_code, response_headers)
E           websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 403

.venv\Lib\site-packages\websockets\legacy\client.py:329: InvalidStatusCode
============================== warnings summary ===============================
tests\test_client.py:20
  c:\repo\h2ogpt\client\tests\test_client.py:20: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

.....

tests\test_client.py:63
  c:\repo\h2ogpt\client\tests\test_client.py:63: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ===========================
FAILED tests/test_client.py::test_readme_example[True] - websockets.exception...
======================== 1 failed, 3 warnings in 8.39s ========================
```

**Comment by pseudotensor** [comment]
Hi, I ran:

```
(/data/conda/h2ogpt) jon@pseudotensor:~/h2ogpt$ python generate.py --base_model=llama --model_path_llama=https://huggingface.co/TheBloke/Orca-2-7B-GGUF/resolve/main/orca-2-7b.Q4_K_M.gguf?download=true --max_seq_len=4096 --prompt_type=orca2 --score_model=None
```

and in same env ran:
```
pytest -s -v tests/test_client_readme.py::test_readme_example
```

And it runs fine for both remote and local (False and True).

I think you are running the OpenAI compatible client test right?  Is that intentional?

@this Can you look please?

**Comment by this** [comment]
> I tried to run h2o_client tests with local h2oGPT server running and getting the below error.
> 
> ```
> tests/test_client.py::test_readme_example[True] HTTPConnectionPool(host='0.0.0.0', port=7860): Max retries exceeded with url: 
> /config (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFEAB04AD0>: Failed to establish a 
> new connection: [WinError 10049] The requested address is not valid in its context'))
> ```

Seems like the h2oGPT server is not available at http://localhost:7860. May be it didn't get started or that address is incorrect. How did you execute the tests?

**Comment by hpxiong** [comment]
> > I tried to run h2o_client tests with local h2oGPT server running and getting the below error.
> > ```
> > tests/test_client.py::test_readme_example[True] HTTPConnectionPool(host='0.0.0.0', port=7860): Max retries exceeded with url: 
> > /config (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFEAB04AD0>: Failed to establish a 
> > new connection: [WinError 10049] The requested address is not valid in its context'))
> > ```
> 
> Seems like the h2oGPT server is not available at http://localhost:7860. May be it didn't get started or that address is incorrect. How did you execute the tests?

The h2oGPT server is running at localhost:7860. It is accessible from both local env and remote. There is nothing special how the test is executed.

**Comment by hpxiong** [comment]
Now, if I change local server address from 0.0.0.0:7860 to 127.0.0.0.1:7860, then I can create Client, and ended in HTTP 403 error. this is running test from the same env as the h20GPT server.

<img width="618" alt="image" src="https://github.com/h2oai/h2ogpt/assets/17347604/efa90b86-a53a-4f17-9e3e-579fce181391">

**Comment by hpxiong** [comment]
My latest update. 

I was able to pass the test_readme_example.py  local=True by changing:
 
host = "http://0.0.0.0:7860" --> host = "http://127.0.0.1:7860". 

Also I suggest the test code does not include the following for local_server=True testing. I don't think it does anything useful when using local server, or am I missing something?  

https://github.com/h2oai/h2ogpt/blob/fae3d909b589d9ac10423933a97805484cf42de0/tests/test_client_readme.py#L6-L8

This code does not work for me since my environment is behind firewall, even I tried to force offline mode using local model file,  prepare_offline_level=2, gradio_offline_level=2. 
It keeps on retrying to connect to huggingface.co for many dependencies.

**Comment by pseudotensor** [comment]
Yes, some systems cannot handle 0.0.0.0 and need localhost or 127.0.0.1, like windows/mac.

The launch of the server is required if no server was up.

The test code is meant to be run with certain keys and other choices set, not all can be run without that.  E.g. OpenAI tests need to be done, but we can't publish keys in the repo.
