### ISSUE TITLE
vllm inference server without internet: vLLM: raise ConnectionError(e, request=request)

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2ogpt#1186]
When I ran **vllm inference server** without internet connection then it throws the following error

`File "/home/miniconda3/envs/vllm/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /api/models/meta-llama/Llama-2-13b-chat-hf/revision/main (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fb471e53400>: Failed to resolve \'huggingface.co\' ([Errno -3] Temporary failure in name resolution)"))'), '(Request ID: 180aa8f1-bd8d-4f1e-bc19-2ba285227928)')`

When i power on the server, it ask for internet connection to run vllm. However, I want to use h2ogpt with vllm inferencing on my private server without internet connection. 

Please help me regarding this!

****Command I hit:
`python -m vllm.entrypoints.openai.api_server --port=5000 --host=0.0.0.0 --model meta-llam a/Llama-2-13b-chat-hf --tokenizer=hf-internal-testing/llama-tokenizer --tensor-parallel-size=1 --seed 1234 --max-num-batched-tokens=4096`

**Comment by pseudotensor** [comment]
@tomkraljevic You had this issue with vLLM's bug that no internet was an issue. Was there a resolution?

**Comment by pseudotensor** [comment]
@llmwesee Please also check vllm github repo for any solutions, and share if you find.  Thanks!

**Comment by pseudotensor** [comment]
@tomkraljevic said there's no direct known solution by us.  For air-gap case, we anyways had to mirror HF, so once we did that it was not an issue anymore.

**Comment by llmwesee** [comment]
@pseudotensor Yeah, I already raised the same issue on vllm github repo also. And there was also the same issue related to this but that was still open.

**Comment by pseudotensor** [comment]
I wonder if the same options can be passed into vllm as we would use for h2ogpt, i.e.

https://github.com/h2oai/h2ogpt/blob/4f48491b694b0b4b2da0e1e83754e1d0f5a7d727/docs/README_offline.md#run-h2ogpt-in-offline-mode

i.e.

```
TRANSFORMERS_OFFLINE=1 
```
maybe that env helps vllm too?

**Comment by tomkraljevic** [comment]
i spent a day narrowing it down a few months ago.  i was able to run it in a pycharm debugger and more or less find the issue (where it was ignoring the env var saying don't use network).

but i had issues properly rebuilding vllm C/C++ pieces themselves.  they actually built, but didn't run right for reasons i never got to the bottom of.

at about that point i gave up because our on-prem in-cluster downloading approach panned out, which was more aligned with what we are trying to do anyway.

**Comment by llmwesee** [comment]
@pseudotensor @tomkraljevic We can use vLLM server without internet by giving the model to the absolute path like 
`python -m vllm.entrypoints.openai.api_server --port=5000 --host=0.0.0.0 --model "/home/hemant/.cache/huggingface/hub/models--meta-llama--Llama-2-13b-chat-hf/snapshots/c2f3ec81aac798ae26dcc57799a994dfbf521496" --tokenizer=hf-internal-testing/llama-tokenizer --tensor-parallel-size=1 --seed 1234 --max-num-batched-tokens=4096`

![vllminternate](https://github.com/h2oai/h2ogpt/assets/137979399/c2eb1476-2da4-4ab8-82fc-68f5dfefe93a)

And I run the h2ogpt by hit the command 

`python generate.py --inference_server="vllm:0.0.0.0:5000" --base_model=meta-llama/Llama-2-13b-chat-hf  --score_model=None --langchain_mode='UserData' --user_path=user_path --use_auth_token=True --max_seq_len=4096 --max_max_new_tokens=2048 --concurrency_count=64 --batch_size=16
Using Model meta-llama/llama-2-13b-chat-hf`

![vllminternate4](https://github.com/h2oai/h2ogpt/assets/137979399/7c186786-16dc-4383-b863-a32203c00893)

But it through the error like

` return self._request(
  File "/home/hemant/miniconda3/envs/gpt051223/lib/python3.10/site-packages/openvllm/_base_client.py", line 908, in _request
    raise self._make_status_error_from_response(err.response) from None
openvllm.NotFoundError: Error code: 404 - {'object': 'error', 'message': 'The model `meta-llama/Llama-2-13b-chat-hf` does not exist.', 'type': 'invalid_request_error', 'param': None, 'code': None}
`

![vllminternate5](https://github.com/h2oai/h2ogpt/assets/137979399/a09b535d-e339-4049-8f2e-c9783e886210)

but  when I gave the absolute path in the base_model of the h2ogpt also like the following command 

`python generate.py --inference_server="vllm:0.0.0.0:5000" --base_model='/home/hemant/.cache/huggingface/hub/models--meta-llama--Llama-2-13b-chat-hf/snapshots/c2f3ec81aac798ae26dcc57799a994dfbf521496' --score_model=None --langchain_mode='UserData' --user_path=user_path --use_auth_token=True --max_seq_len=4096 --max_max_new_tokens=2048 --concurrency_count=64 --batch_size=16`

![vllminternate2](https://github.com/h2oai/h2ogpt/assets/137979399/94ceffa5-2373-4691-8b65-2fdf316edf5f)

Then it does not generate the error like above but gave wrong responses all the time like the following screenshot

![vllminternate3](https://github.com/h2oai/h2ogpt/assets/137979399/3571a8b6-523e-4c64-a56e-33c19b789223)

**Comment by pseudotensor** [comment]
Thanks.  The above wrong responses is just because it doesn't recognize the model name.   You need to pass `--prompt_type=llama2` in this case because we don't have your model path in our src/prompter.py dict lookup.
