### ISSUE TITLE
Flag to retrieve neighborhood chunks.

### ISSUE THREAD

**Issue by vitalyshalumov** [h2oai/h2ogpt#1191]
It is often the case when the chunks in the neighborhood of the high-score chunk contain relevant information, while having a much lower score.
Can you add an option to retrieve them as well - say a chunk before and a chunk after of the high-score chunk.
Thank you!

**Comment by pseudotensor** [comment]
Hi, it's a good idea, and commonly tried, but in our testing it was not main issue.  And it wastes context and can confuse the model.  So I do not plain to add this specifically.
