### ISSUE TITLE
Login with new user after having chat history with old user leads to old chats being consumed for new user

### ISSUE THREAD

**Issue by us8945** [h2oai/h2ogpt#1198]
After a user logs in with one user and then logs in with a different user, chat history from the first user is visible.

<img width="1022" alt="image" src="https://github.com/h2oai/h2ogpt/assets/9545684/625cfe9c-a5ac-4404-981e-298b950e0186">

Steps to recreate:
- Login with user-1
- Save chats using "Save" button
- Open new Browser window and login with user-1
- Login with a user-2
- Now user-2 can see chats saved by user-1

**Comment by pseudotensor** [comment]
Currently this is by design.  Normally users don't login as other users, so this shouldn't be an issue.

The idea is that one may *not* be logged in, and then have saved chats.  We don't want you to lose those chats just because you decided to login or create new user.

**Comment by pseudotensor** [comment]
Normal usage pattern of single user logged in per browser session/tab has no issue:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/a061e551-915d-47a1-ac94-ca3dbf09d5e7)

new user in new tab:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/55b1f94f-4103-4013-bec3-2e7f40671859)
