### ISSUE TITLE
Web search Agent triggering

### ISSUE THREAD

**Issue by bonswouar** [h2oai/h2ogpt#1200]
I've been playing a bit with the web search functionality. The basic one (Include Web Search option) works pretty well with Mistral-7B-Instruct-v0.2 already.
Although the Agent seems even more interesting!

But I encounter an issue, sometimes the search is just not triggered, it looks like the model is actually hallucinating the answer.

Better than explaining, here is an example:

> **What is Mixtral 8x7B ?**
![image](https://github.com/h2oai/h2ogpt/assets/615053/4892b430-e422-4064-9faa-d8e3910de765)

> **What are Mixtral 8x7B recent news?**
![image](https://github.com/h2oai/h2ogpt/assets/615053/235698e3-e64d-4e76-ac44-ac78878244bc)
As you can see this time it did trigger the web search _(this specific one fails after with a "Could not parse LLM output" error though, but that's another issue)_

Is it because of the model I'm using? Any way to fine tune that or the 7B models are still just not powerful enough?

EDIT. Got one fully working, just to show this model is pretty capable :
![image](https://github.com/h2oai/h2ogpt/assets/615053/4fe62ac7-3e28-4029-9c3c-2a309c483a17)

**Comment by pseudotensor** [comment]
The agent stuff in langchain, e.g. search, is pretty fragile.  It's a standard problem for agents.

**Comment by bonswouar** [comment]
Sorry I've totally forgot I opened this issue, for reference an easy fix is to add "Observation:" to the model's stop word.
Search then work very well, even for small models!

**Comment by pseudotensor** [comment]
@bonswouar can you say what your changes are?

For all models I checked, I see `['\nObservation:', '\n\tObservation:']` is present.  But I think you   may be saying that Observation was missing a new line when went bad?

I didn't see that particular problem.  Seems to work fine.

I don't see a missing \n before Observation: in your example, but I can see it is all green.

So maybe you can explain which model type failed for you (HF transformers, GGUF, etc.).

![image](https://github.com/h2oai/h2ogpt/assets/2249614/d8c2a207-7d9d-45c3-80e8-0830e10204ab)


![image](https://github.com/h2oai/h2ogpt/assets/2249614/c9209771-a6bb-426f-b140-b1395d38b3df)

**Comment by pseudotensor** [comment]
Also, the biggest problem I've seen with search is that  most models even 70B llama-2 don't know when to stop.  I've not had the issue of missing stop word so could to know what your start command so I can reproduce, and if you can share your changes that's good too.

**Comment by bonswouar** [comment]
> So maybe you can explain which model type failed for you (HF transformers, GGUF, etc.). Maybe there is a specific code path that is not doing the right thing.

I've been testing with `TheBloke/Mistral-7B-Instruct-v0.2-GGUF`

>For all models I checked, I see ['\nObservation:', '\n\tObservation:'] is present. But I think you may be saying that Observation was missing a new line when went bad?

Do you mean  `['\nObservation:', '\n\tObservation:']` is already set as stop sequences?

I actually "fixed" in a small local project only, when playing with basic langchain Agents (as I was often having the same issue), uding `ollama`. Not in h2ogpt directly.

Not sure how it works exactly with `llamacpp`, but with `ollama` you can add any STOP parameters and it will reliably stop the generation.
I did a quick search, apparently that's called `reverse-prompt` with llamacpp, but not sure if it works exactly the same way. I don't find any reference in h2ogpt, do you actually use it? Maybe I'm totally on the wrong track though :)

**Comment by bonswouar** [comment]
> Ya langchain already adds those stop words.

Are you sure about that? I didn't dig much into langchain's mechanisms but I feel like it adds those as instructions (or system prompt?), but it doesn't utilise the proper `reverse_prompt` feature in this case.
Or maybe `reverse_prompt` implementation is somewhat unreliable with `llama-cpp-python`?

For example if you look at crewAI, it also uses langchain, with ollama, and [recommends adding the custom stop word](https://github.com/joaomdmoura/crewAI/#local-open-source-models)
And I confirm it does make it much more reliable (it never continues after "Observation:" after adding it to the Modelfile)

**Comment by pseudotensor** [comment]
Yes, langchain adds them as I can see when debugging and seeing how things work, and h2oGPT never adds them.  Each agent type adds specific stop words.

The issue is that depending upon the model type, langchain has some bugs, so that the stop words don't get passed along properly. I think this is still true.  So I had to add a bit of code just so that the stop words are passed along for some LLM types.  I'll check llama.cpp again for h2oGPT, thanks.

**Comment by pseudotensor** [comment]
Thanks,  it was just my mistake of not allowing the stop words to pass through, I pushed a fix.

**Comment by pseudotensor** [comment]
```
python generate.py --base_model=TheBloke/Mistral-7B-Instruct-v0.2-GGUF --score_model=None
```

![image](https://github.com/h2oai/h2ogpt/assets/2249614/29265e7d-b680-4851-937b-4cb075ce769f)

![image](https://github.com/h2oai/h2ogpt/assets/2249614/40779851-b95f-4046-b76b-71d36e820602)

**Comment by bonswouar** [comment]
Awesome, thanks @pseudotensor 
(and great question to ask the llm btw)

I can confirm it now works with the original example:
![image](https://github.com/h2oai/h2ogpt/assets/615053/3d30e195-6e7a-4bf1-a79a-1ee37c04a089)
Can't wait to see even more capable small models :)
