### ISSUE TITLE
Ability to pass page title as an argument to generate.py

### ISSUE THREAD

**Issue by Blacksuan19** [h2oai/h2ogpt#1201]
is there a way to change the page title? I can't find where it's set.

**Comment by pseudotensor** [comment]
I'm not 100% sure what is meant by a title page, but maybe the top few things?

* --h2ocolors=False -- can disable the color scheme
* src/gradio_themes.py -- is there get_h2o_title is, which uses an svg directly in code.
* various other "visible" options in src/gen.py CLI args control other things, e.g. qr code, links, title, can all be removed each with extra CLI options.

There's no specific way to pass in a title page without changing the code.  But it's super easy to do so by changing `h2o_logo` in gradio_themes.py to some new image.

**Comment by pseudotensor** [comment]
i.e. all these control various things, see doc string or run `python generate.py --help`

![image](https://github.com/h2oai/h2ogpt/assets/2249614/52fb1fc9-645b-47f9-933c-bab080483f2b)

**Comment by Blacksuan19** [comment]
I mean the title of the gradio based web page, currently the title is always h2oGPT and there is no way to change it

**Comment by Blacksuan19** [comment]
here's an image for reference, the gradio UI web page's title is always h2ogpt and there is no way to change it currently @pseudotensor 

![image](https://github.com/h2oai/h2ogpt/assets/10248473/c2589d53-1ad6-434e-853e-c7b172351025)

**Comment by pseudotensor** [comment]
The favicon code is here:

https://github.com/h2oai/h2ogpt/blob/main/src/gradio_runner.py#L5618-L5630

It only requires you to change the h2o-logo.svg file to something else.
