### ISSUE TITLE
Error: Mixtral-8x7B-Instruct-v0.1 issue with Llama-cpp-python

### ISSUE THREAD

**Issue by MSZ-MGS** [h2oai/h2ogpt#1202]
New comment regarding Llama-cpp-python & Mixtral-8x7B-Instruct-v0.1-GGUF.

![image](https://github.com/h2oai/h2ogpt/assets/65172063/cdb8c125-698c-4dd0-b166-9e959899f486)

For more info:
https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF/commit/89336ec93914225f1f816feb99cf5871c10d0f3f

I am using windows, Llama-cpp-python V0.2.99 and V0.2.22.
It didn't work with me, error log:
[Mixtral Error.txt](https://github.com/h2oai/h2ogpt/files/13664428/Mixtral.Error.txt)

**Comment by pseudotensor** [comment]
Hi, will try, thanks.

**Comment by pseudotensor** [comment]
You hit:
```
error loading model: create_tensor: tensor 'blk.0.ffn_gate.weight' not found
llama_load_model_from_file: failed to load model
```

Maybe llama cpp python not updated even if llama.cpp is.  There is usually lag.

**Comment by MSZ-MGS** [comment]
Just an update:
https://github.com/abetlen/llama-cpp-python/issues/1000

**Comment by pseudotensor** [comment]
This works:

```
pip uninstall llama_cpp_python
pip uninstall llama_cpp_python_cuda
git clone --recurse-submodules https://github.com/abetlen/llama-cpp-python.git
cd llama-cpp-python/
git fetch origin pull/1007/head:1007
git switch 1007
git submodule update --remote
git submodule update
CMAKE_ARGS="-DLLAMA_CUBLAS=on" pip install -e .
cd ~/h2ogpt/
python generate.py --base-model=TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF --prompt_type=zephyr
```
Takes a while to download the single monster GGUF file.

I see it mention context is auto-set to 4096, seems wrong.  But let's see.

Will add to FAQ.  Use appropriate system things for building as in https://github.com/abetlen/llama-cpp-python#installation

![image](https://github.com/h2oai/h2ogpt/assets/2249614/9b73b0a4-7350-4a1d-bd60-68025f724766)

**Comment by pseudotensor** [comment]
ab70fcdd69c022587e55e3cf4c51261e640f9cce

**Comment by MSZ-MGS** [comment]
Just cross check is it --prompt_type=zephyr?
I think it was written "plain" in the prompter?! Maybe I am mistaken

**Comment by pseudotensor** [comment]
mistral is correct prompt, zephyr works but is a typo in trying to move quickly.  Thanks a673e6fdb0072d04c71e0284db061005ece5a7d4

![image](https://github.com/h2oai/h2ogpt/assets/2249614/8cb7191e-535a-45aa-8643-fbbb40aaada4)

**Comment by pseudotensor** [comment]
a673e6fdb0072d04c71e0284db061005ece5a7d4

**Comment by pseudotensor** [comment]
FYI plain is only relevant for foundational base models

**Comment by alexg711** [comment]
What about in a docker deployment model? The following errors out with

pydantic.v1.error_wrappers.ValidationError: 1 validation error for H2OLlamaCpp
__root__
  Could not load Llama model from path: llamacpp_path/mixtral-8x7b-instruct-v0.1.Q5_K_M.gguf. Received error  (type=value_error)


sudo docker run \
       --gpus all \
       --runtime=nvidia \
       --shm-size=2g \
       -p 7860:7860 \
       --rm --init \
       --network host \
       -v /etc/passwd:/etc/passwd:ro \
       -v /etc/group:/etc/group:ro \
       -u `id -u`:`id -g` \
       -v /mnt/ssd/cache:/workspace/.cache \
       -v /mnt/ssd/h2ogpt/save:/workspace/save \
       -v /mnt/ssd/h2ogpt/user_path:/workspace/user_path \
       -v /mnt/ssd/h2ogpt/db_dir_UserData:/workspace/db_dir_UserData \
       -v /mnt/ssd/h2ogpt/users:/workspace/users \
       -v /mnt/ssd/h2ogpt/db_nonusers:/workspace/db_nonusers \
       -v /mnt/ssd/h2ogpt/llamacpp_path:/workspace/llamacpp_path \
       gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0 /workspace/generate.py \
          --base-model=TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF \
          --load_gptq=model \
          --use_safetensors=True \
          --prompt_type=mistral \
          --save_dir='/workspace/save/' \
          --use_gpu_id=False \
          --score_model=None \

**Comment by pseudotensor** [comment]
The docker build is still using original installation instructions.  When we push a change to main, we only build docker nightly.

**Comment by pseudotensor** [comment]
As of now, llama_cpp_python has merged the required llama.cpp changes.  However, llama.cpp with Mixtral is still unstable for >4096 context, likely bugs in llama.cpp.

**Comment by pseudotensor** [comment]
I have much more hope for AWQ instead of llama.cpp.

**Comment by pseudotensor** [comment]
https://github.com/casper-hansen/AutoAWQ/issues/259

**Comment by MSZ-MGS** [comment]
It is confirmed, it worked with llama-cpp-python==0.2.23 official release
