### ISSUE TITLE
Second agent to review the first answer

### ISSUE THREAD

**Issue by Pedrojosejimenez** [h2oai/h2ogpt#1209]
I am working on an LLM project with confidential documents using H2OGPT and I notice that the system answers me with some "hallucinations" for very specific questions. To correct this, I want to program a critical agent in the code so that once the answer is received, it will make me a new joint prompt with the question asked and the answer received, and ask if the answer to the question is correct. (As long as the maximum token length of 4096 is not exceeded). and only show the previous answer if the answer to this second prompt is affirmative. In which module of the whole H2OGPT application should I program it? Thank you.

**Comment by pseudotensor** [comment]
I recommend something like what I'm doing here: https://github.com/h2oai/h2ogpt/pull/1267 using Prometheus as replacement for GPT-4.
