### ISSUE TITLE
h2oGPT as middleware (API in, API out)

### ISSUE THREAD

**Issue by StefanDanielSchwarz** [h2oai/h2ogpt#1217]
I've tinkered with this but couldn't get farther so I'm asking about if/how my use case is supported by h2oGPT:

I already have a frontend that connects to OpenAI-compatible API endpoints, and a backend that offers an OpenAI-compatible API endpoint. My goal is to put h2oGPT in the middle, to accept incoming OpenAI-compatible requests, do its RAG magic with the prompt, then pass it on to the inference backend.

TGI, vLLM, and other backends are already supported - but I couldn't connect to either [oobabooga's text-generation-webui](https://github.com/oobabooga/text-generation-webui) or [koboldcpp](https://github.com/LostRuins/koboldcpp) as the backend. Both have their own APIs as well as OpenAI-compatible ones. Did anyone manage to connect to them from h2oGPT or are there any pointers I could follow? Tried to set --inference_server to their URLs and ports, but couldn't connect.

Same with the Gradio server h2oGPT opens up - does that actually offer an OpenAI-compatible API endpoint for my actual frontend to connect to? Or what's the intended way to work with that?

Would be happy to integrate h2oGPT into my pipeline as this looks to be a feature-rich and mature RAG solution. Grateful for any pointers and suggestions how to fit it into my setup.

**Comment by pseudotensor** [comment]
If text webui or koboldcpp have OpenAI compatible endpoints, they should be supported by just treating them as OpenAI endpoints like vLLM would be handled.  The actual openai_chat and openai are restricted to models that OpenAI supports through asserts, but vllm is same as OpenAI and has no such restrictions.  E.g. so one would do:

```
python generate.py --inference_server="vllm:192.168.1.56:10513" --base_model=Mixtral-Instruct --prompt_type=mistral
```

The IP and port are fake above, but you get idea.  This mode is very well tested and assumes vllm is using OpenAI compliant mode, so any other endpoint would workk too.  "vllm_chat" mode is also possible, then one would do:

```
python generate.py --inference_server="vllm_chat:192.168.1.56:10513" --base_model=Mixtral-Instruct --prompt_type=plain
```
This forces h2oGPT not to do prompting, but let the server handle it.  That requires the endpoint to handle prompting, which text web ui or koboldcpp might.

**Comment by pseudotensor** [comment]
However, if you want API in and API out, currently h2oGPT can work with OpenAI-like (or other) inference servers, it does not expose itself as an OpenAI endpoint. The RAG behavior requires much more than a normal LLM would take, such as documents or other things.

It's possible with openai 1.x API that with assistants we can *now* start to expose h2oGPT as an OpenAI server and it make some sense, but until recently it wasn't a big priority to try since too much wouldn't be possible to do.

You can of course always  use the gradio API to talk to h2oGPT.  The API is not at all complex, and we have many examples, tests, etc.  The simplest wrapper code we have is `test_readme_example` in `tests/test_client_readme.py`.  But that is a one-shot go at document+question -> answer.  That might be perfectly fine for your use-case and only requires using gradio_utils/grclient.py as a copy-paste file in your project.

More fine-grained is using that wrapper code to access another inner wrapper code that is GradioClient class, which  shows how one can add a file, url, or text, and ask a question or get a summary or extract information.  One could follow GradioClient and make a version that works for your application with fairly minor changes.

That might also be perfectly fine for your use-case and again only requires using gradio_utils/grclient.py as a copy-paste file in your project, but any tweaks you can keep in your project.

**Comment by StefanDanielSchwarz** [comment]
Thank you for the detailed information. I'll experiment with that and report back if/how it works.

Regarding the API in and API out, I was hoping I could use h2oGPT as a UI to handle uploading documents into the vector DB, then pass normal OpenAI requests through it and it would modify the prompt, injecting relevant information from the DB, then pass it on to the inference backend. Basically a transparent proxy in-between frontend and backend, pretty much a RAG middleware.

**Comment by pseudotensor** [comment]
Ya, right now you'd need to use the gradio client (or GradioClient etc.) to do the "pass normal OpenAI requests through it and it would modify the prompt, injecting relevant information from the DB, then pass it on to the inference backend" part.

The "use h2oGPT as a UI to handle uploading documents into the vector DB" is fine yes as-is.  E.g. you'd upload to some shared collection UserData and specify that as the only allowed thing with `--langchain_modes="['UserData']"` so no matter any API call would use that collection instead of (say) default of pure LLM.

We'll get actual OpenAI inference instead of gradio sometime soon.

**Comment by StefanDanielSchwarz** [comment]
> We'll get actual OpenAI inference instead of gradio sometime soon.

That's great news! I'm looking forward to that...

**Comment by pseudotensor** [comment]
Basic chat stream and non-stream is merged: https://github.com/h2oai/h2ogpt/pull/1231

**Comment by StefanDanielSchwarz** [comment]
Oh wow, that's faster than I expected, thanks a lot! I'll check it out over the weekend and let you know how it's working for me...

**Comment by StefanDanielSchwarz** [comment]
Hello again! Hope you had happy holidays. I've now had time to experiment with h2oGPT in between my frontend SillyTavern and backends KoboldCpp and oobabooga's text-generation-webui.

My first problem was when trying to use turboderp/Mixtral-8x7B-instruct-exl2 which is my go-to Mixtral EXL2 model. The issue here is that fails with "OSError: turboderp/Mixtral-8x7B-instruct-exl2 does not appear to have a file named config.json. Checkout 'https://huggingface.co/turboderp/Mixtral-8x7B-instruct-exl2/main' for available files."

This HF repository uses branches for the individual quantizations, so the config.json is at https://huggingface.co/turboderp/Mixtral-8x7B-instruct-exl2/resolve/5.0bpw/config.json in my case of 5.0bpw quantization. oobabooga solves that by specifying the branch name as part of the repo path after a colon, e. g. turboderp/Mixtral-8x7B-instruct-exl2:5.0bpw - maybe you could implement it similarly when resolving the config.json download?

To be able to proceed, I switched to TheBloke/Llama-2-7B-Chat-GGUF, which worked. But it never tried to access the files I uploaded, which works from h2oGPT's UI. Do I need to do anything special to make h2oGPT insert the RAG prompt and information when the query is passing through?

Other potential issues:

Console shows three times "Used max_position_embeddings=512 as base model (pre-rope) max_seq_len.  If not desired, pass --max_seq_len and set to some integer value." despite me passing --max_seq_len=4096 on the command line (which is confirmed by output "Overriding max_seq_len -> 4096" after "max_seq_length  512".

Also getting this warning multiple times: "UserWarning: Field "model_name" has conflict with protected namespace "model_". You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`."

**Comment by pseudotensor** [comment]
The way HF transformers manages branches is via revision parameter, which we have too.  i.e.
```
python --base_model=turboderp/Mixtral-8x7B-instruct-exl2 --revision=2.4bpw
```

is like direct transformers:
```
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('turboderp/Mixtral-8x7B-instruct-exl2', revision='2.4bpw')
```

However, the model is "output" some special exllamav2 type I guess?

But I'm not sure your goal.  I expect you don't want to use the model itself, but use another backend as an inference server like openai compatible type.  So then one would do:

```
python --base_model=turboderp/Mixtral-8x7B-instruct-exl2 --revision=2.4bpw --inference_server=vllm:192.168.0.1:5000
```
which works fine because this got the config and tokenizer and that's all that's required when connecting to an inference server.

**Comment by pseudotensor** [comment]
I can't quite follow this: " But it never tried to access the files I uploaded, which works from h2oGPT's UI. Do I need to do anything special to make h2oGPT insert the RAG prompt and information when the query is passing through?"

What are you uploading to if not using the UI?   The only thing you need to use is the shared collection UserData.  If you upload to that via API or UI, not MyData that is scratch/personal collection, and by default setup h2oGPT to use UserData by default/only collection, then any query will take that route.

**Comment by pseudotensor** [comment]
On "Console shows three times "Used max_position_embeddings=512 as base model (pre-rope) max_seq_len. If not desired, pass --max_seq_len and set to some integer value." despite me passing --max_seq_len=4096 on the command line (which is confirmed by output "Overriding max_seq_len -> 4096" after "max_seq_length 512"."

The 512 message is from the embedding model.

**Comment by pseudotensor** [comment]
Let's ignore the warning for now: "Also getting this warning multiple times: "UserWarning: Field "model_name" has conflict with protected namespace "model_". You may be able to resolve this warning by setting model_config['protected_namespaces'] = ().""

**Comment by pseudotensor** [comment]
On "Only vllm worked, vllm_chat did not. With KoboldCpp and ooba, vllm_chat produced "TypeError: Completions.create() got an unexpected keyword argument 'batch_size'" when sending a query from h2oGPT."

Will take a look.  If you have full stack trace it may help, but I suspect that one code path in the openvllm package did not add batch_size or something like that.

**Comment by pseudotensor** [comment]
I pushed fixes for the vllm_chat issues.

**Comment by StefanDanielSchwarz** [comment]
Hello again! Thanks a lot, I finally got around to try again and it's working much better now:

- vllm_chat works!
- revision works!
- RAG passthrough works!

That was with TheBloke/Llama-2-7B-Chat-GGUF. Unfortunately I must still be missing something, since when I try to use turboderp/Mixtral-8x7B-instruct-exl2, I see my input in the text-generation-webui console, but no response is generated (0.00 tokens/s, 0 tokens),

Any idea how to troubleshoot this further? Mixtral is a much better model than Llama 2 7B Chat, so to make proper use of this integration, I have to find a way to make this work. I'm grateful for any pointers or suggestions!

**Comment by pseudotensor** [comment]
I still don't fully grasp the setup.  Are you using vllm_chat to talk to ooba?

I'll assume so, then few things you can check:
* Look at ooba repo for docs on using OpenAI like client to talk to ooba.  The use some SSE and curl etc.
* Maybe ooba is not 100% OpenAI compliant or something, and it breaks.  So try actual OpenAI client to ooba with streaming etc.

If ooba works perfectly in every scenario, then hopefully you see log messages somewhere.

If ooba gets response but sends nothing back, that's already a concern with ooba.  h2oGPT is just acting like a client talking to ooba.

Another alternative is to add exllama2 to h2oGPT, but I'm not sure what else in ooba you are relying upon (characters etc.)

**Comment by StefanDanielSchwarz** [comment]
My setup is SillyTavern as the frontend, connecting it through its OpenAI API connector to h2oGPT as "middleware" which is connecting to my ooba backend. The purpose of h2oGPT is to insert the RAG stuff into the prompt as it's passing through, like a proxy. This works, I see the information from ingested documents added into the prompt, everything looks good as it hits ooba.

Now when using Llama 2 Chat, everything works as expected. ooba returns a response that takes into account the retrieval-augmented generation.

The problem is, Llama 2 Chat is pretty bad, so I'd like to use my favorite model, Mixtral. But when I try to use that, ooba is not generating any output, despite the input looking good (as far as I can tell).

Now I wonder if the tokenizer or prompt format could be causing this, if it's not properly tokenizing or formatting the output, or any other generation settings being askew for ooba's inference engine Exllamav2 in the background or the Mixtral model itself. I don't notice any issue when looking at ooba's console, but something must be wrong, otherwise I should be getting output as usual.

When connecting directly, bypassing h2oGPT, everything works as usual. So there must be something that's happening when passing through that's causing generation to fail.

**Comment by pseudotensor** [comment]
I agree, I suspect it is issue with prompting.

Did you try avoiding vllm_chat and just using vllm for the inference server type?  Then h2oGPT would talk to ooba in text completion mode instead of chat completion mode, and h2oGPT would handle all prompting.

**Comment by pseudotensor** [comment]
Another option is to change in `src/gpt_langchain.py` this line:
```
use_template = not use_openai_model and prompt_type not in ['plain'] or langchain_only_model
```
to:
```
use_template = not use_openai_model or langchain_only_model
```

and then instead of `--prompt_type=mistral` you set `--prompt_type=plain` for h2oGPT, and let ooba handle LLM specific prompting and keep vllm_chat mode.

**Comment by StefanDanielSchwarz** [comment]
Finally got it working!

After upgrading ooba and all its components, I eventually got an actual error message:

> ValueError: `temperature` (=0.0) has to be a strictly positive float, otherwise your next token scores will be invalid. If you're looking for greedy decoding strategies, set `do_sample=False`.

I assume that's output by ExLlamav2. The message is actually misleading, because I was using `do_sample=False` in SillyTavern, and h2oGPT also had Expert > LLM Control > Sample OFF. Which makes sense since we want precise, not creative, output. But when I enabled sampling, the error message disappeared and I finally got the LLM to respond!

I didn't notice any difference between inference_server "vllm" or "vllm_chat", or prompt_type "mistral" or "plain". I suppose that's because either SillyTavern set the proper prompt format with plain, or h2oGPT did with "mistral", but both resulted in apparently the same input to ooba/ExLlamav2.

Either way, it works really well, especially with a smart model and big context like Mixtral. Here's the command line I'm using:

`python generate.py --base_model=turboderp/Mixtral-8x7B-instruct-exl2 --revision=5.0bpw --prompt_type=mistral --max_seq_len=32768 --verbose=True --openai_port=5001 --inference_server=vllm_chat:192.168.178.78:5000 --langchain_mode=UserData --langchain_modes="['UserData']" --langchain_mode_paths="{'UserData': 'user_path'}" --langchain_mode_types="{'UserData':'shared'}" --user_path=user_path`

**Comment by pseudotensor** [comment]
Cool thanks!  Ya, some frameworks don't handle some values well.  Replicate.com does same thing, it's kinda silly because temperature=0 does mean no sampling, so it should have handled it.  For replicate, and maybe ooba/exllama2, you might have to set temperature=0.01 and then disable sampling to be deterministic.

**Comment by pseudotensor** [comment]
> Only issue now: It often doesn't stop inferencing after the response is done, instead it keeps going and generating additional question-answer pairs. Looks like the EOS token isn't handled or stopping strings don't trigger.

That still sounds like a prompting issue.  Try to get only one framework to add prompting.

**Comment by StefanDanielSchwarz** [comment]
Regarding the ValueError: `temperature` (=0.0) has to be a strictly positive float, otherwise your next token scores will be invalid. If you're looking for greedy decoding strategies, set `do_sample=False`:

The problem is that temperature 0 is considered invalid and we're supposed to use do_sample=False instead. But h2oGPT apparently does it the opposite way: I can't set temperature 0, the slider's minimum value is 0.01 as long as Sample is ON, but when I turn Sample OFF, it's 0 yet the generation parameter `do_sample` remains `True`.

To fix that, when Sample is OFF, `do_sample` should be `False`. That's probably how ooba handles it, too, as I remember llama.cpp just like ExLlama having special cases for temperature 0. @pseudotensor: Could you implement it like that? To set `do_sample=False` when the Sample option is OFF? Then it would work and you don't have to change anything about how you're already handling temperature.

I think that's how other frontends handle it, too, and it's also more consistent with how your UI presents these options. If the temperature slider went all the way down to 0 to indicate Sample OFF, there would be no need for a Sample checkbox. So I consider the UI to do it the right way already, now only the code would need to follow that.

**Comment by pseudotensor** [comment]
On temperature/sample, it varies.  Replicate.com simply fails if you pass temp=0, it also has slider that only goes down to temp=0.01, but it doesn't even have option for no sampling.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/e61c7e7b-799d-49e1-8829-aafa313d04db)

The way some other things handle is they allow to control sampling bool,but if you pass temp=0 they just fail, like you are explaining.  They say one must disable sampling.  I think that's not useful, since why ask user to do that if it should be automatic.  h2oGPT does things automatically, but the  issue is downstream things may not.  i.e. they do not even let you pass any temperature, top_k, top_p when sampling is disabled, they just fail.  I also think that is not useful.

The reason why a floor of temp=0.01 makes sense is because when sampling is enabled and temperature is used, then it cannot be 0.  If I allow temp=0 selected, some frameworks will start to fail because they cannot handle.

**Comment by StefanDanielSchwarz** [comment]
Sorry for being not clear enough, it took a while for me to finally understand the problem, too. It's quite complicated dealing with the chain of frontend (SillyTavern), "middleware" (h2oGPT), API backend (ooba), inference backend (ExLlamav2).

What would be very helpful would be extended debug output: Seeing what enters h2oGPT and what leaves h2oGPT. Right now, I can only see that the problem is generation parameters not getting passed through, but I'm not sure where they get lost.

Same with command line arguments like `--max_new_tokens=1024 --temperature=1 --do_sample=False`, they either don't get set, don't get passed on, or something behind h2oGPT is dropping/replacing them. Extended debug output would help find out if h2oGPT is doing everything correctly.

Because no matter what I set in the very front in SillyTavern (like do_sample, temperature, repetition penalty, etc.) it's never showing up in the very end in ExLlama. So I wonder if h2oGPT is getting those settings, if it's sending them out to ooba, if ooba gets them correctly and passes them on to ExLlama - I only see that in the inference log they are missing in the end.

**Comment by pseudotensor** [comment]
I guess you can test each stage separately.
* If you use h2oGPT UI, do those settings get down to ooba?
* If you use OpenAI client to talk to h2oGPT, do those settings get down to ooba?
* What is an example frontend (SillyTavern) call look like for its OpenAI call?
* Yes, you can add `--save_dir=save_dir --verbose --debug` .  In ./save_dir/history.json will be alot of details about each call, including generation parameters, and verbose + debug will show more things in console.

**Comment by kagevazquez** [comment]
This thread helped me get LM Studio working but I cant seem to get more than 1 question asked before getting an error 


[2024-01-13 09:22:00.240] [ERROR] [Server Error] {"title":"'messages' array must only contain objects with a 'content' field that is not empty"}


Autogen has a way to take care of such an issue with agentchat.user_proxy_agent


default_auto_reply str or dict or None - the default auto reply message when no code execution or llm based reply is generated


is there such a setting in h2oGPT?

**Comment by StefanDanielSchwarz** [comment]
@pseudotensor Here's what I found out by looking into the h2oGPT history and ooba logs:

- In history.json, I see the values as set and sent by SillyTavern, e. g. "do_sample": false, "temperature": 1.23, etc.
- In ooba, I see GENERATE_PARAMS= 'temperature': 0.0, 'do_sample': True, and that causes the ValueError: `temperature` (=0.0) has to be a strictly positive float, otherwise your next token scores will be invalid. If you're looking for greedy decoding strategies, set `do_sample=False`.
- I put a debug statement into ooba's extensions/openai/script.py into the openai_completions and openai_chat_completions functions, so I see that this is the actual request that ooba receives, which indicates that h2oGPT is sending the wrong values and not passing on the correct ones from SillyTavern! Doesn't make a difference if it's the Text or Chat Completion endpoint, both get the illegal values.

**Comment by pseudotensor** [comment]
Hi,

* history.json would show what h2oGPT recorded as the generation parameters, so if do_sample=False is there, then that is what h2oGPT used, not just received from client.
* OpenAI API (and so vLLM) does not have a do_sample parameter.
* ooba has do_sample=True by default, which is likely origin of the value.  Note h2oGPT defaults to do_sample=False, so getting it to be true would take effort somewhere.

https://github.com/oobabooga/text-generation-webui/blob/d8c3a5bee814f09b0868474002105dcf21a3ff1a/extensions/openai/typing.py#L30

**Comment by StefanDanielSchwarz** [comment]
@pseudotensor Great info, now it makes more sense. So you can't send do_sample since the OpenAI API doesn't have that. That explains why many apps, SillyTavern included, have specific ooba configs.

Knowing the cause, I modified the openai_completions and openai_chat_completions functions in extensions/openai/script.py:

```
    if request_data.temperature == 0:
        request_data.do_sample = False
```

An ugly monkey patch, but it works. Although that produces a "UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`." But that doesn't block generation. And unsetting (deleting) the request_data.temperature variable would break things, so I'd rather get a warning than a breaking error.

Not sure if there's a better way to handle this - if that's truly what's necessary, I'd submit it as a patch to ooba. Otherwise I'd just patch the file locally so I can use h2oGPT with ooba.

**Comment by pseudotensor** [comment]
It's complex, because every underlying LLM framework ultimately deals with things differently.

i.e. ooba could set do_sample=False if temperature=0 is passed.  One might hope to remove your warning, that if temperature=0 is passed, then set do_sample=False and then *do not pass* temperature, top_p, top_k at all.  This will work for some underlying models but not all.

**Comment by pseudotensor** [comment]
I'll close for now since seems most issues are resolved.  Feel free to ask more questions still and I'm happy to respond in this same issue. I'll still get pinged even though closed.

**Comment by pseudotensor** [comment]
* Yes, that warning is ok.  I had to modify OpenAI client for vLLM so I can pass stop_token IDs (not just stop words) so vLLm stops properly without fragments of stop word.  I didn't get around to cleaning up langchain pydantic stuff to avoid the warning.

* If there is no proper stopping, this is up to ooba->exllamav2 that is handling the prompting.

* Perhaps your lack of control over tokens is related to something I noticed few hours ago: e5a1ecf51531b4019fdff52e83e47219752ac2ab .  But that temperature doesn't get through is not good.  It should be reproducible by just using the client with h2oGPT openai server, I'll check, thanks.

**Comment by pseudotensor** [comment]
I pushed some changes that might help with the temperature passing through, related to do_sample again.

**Comment by StefanDanielSchwarz** [comment]
@pseudotensor Great, thanks for those changes! Max (New) Tokens, Temperature, Frequence Penalty, and Presence Penalty are now passed through properly.

Noticed that as soon as I set Top P to a value between 1 and 0, generation doesn't start, instead I see this log entry:

127.0.0.1:35850 - "POST /v1/chat/completions HTTP/1.1" 422 Unprocessable Entity

Only Top P 0 or 1 work. Also, Seed isn't appearing anywhere despite it being set. Why did you set it to 1234 in your patch, wouldn't -1 for a random seed be the usual default?

**Comment by pseudotensor** [comment]
Ok will check on it, thanks.

**Comment by pseudotensor** [comment]
I think you have things setup to prompting (including system prompt) is all handled by ooba.  It shouldn't matter, since that's pure LLM thing, and how it's put in should be either wrong or right given the documentQA prompt.

**Comment by stakeSAUCE** [comment]
Is there any plan to support exllamav2 in the future?

**Comment by pseudotensor** [comment]
@stakeSAUCE I'll open issue and see how many people would like that.

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/issues/1341
