### ISSUE TITLE
How to use my llm inference api url

### ISSUE THREAD

**Issue by iamrajaraj** [h2oai/h2ogpt#1226]
For example, 
Api - https://host.com/api/v1/llama/infer

Which accept input as
{
Input: "what is GenAI",
Parameter:{temperature:1,...}
}

**Comment by pseudotensor** [comment]
See curl test here: https://github.com/h2oai/h2ogpt/blob/11145c99783c84700455be665926536290058722/docs/README_InferenceServers.md#testing
