### ISSUE TITLE
[Q] Which prompt type should I use for Starling?

### ISSUE THREAD

**Issue by NightMachinery** [h2oai/h2ogpt#1240]
[TheBloke/Starling-LM-7B-alpha-GGUF · Hugging Face](https://huggingface.co/TheBloke/Starling-LM-7B-alpha-GGUF) seems to be the highest ranked small LLM as of now. In the installation guide, which prompt type should I specify for this model?

```zsh
(
setopt PIPE_FAIL PRINT_EXIT_VALUE ERR_RETURN SOURCE_TRACE XTRACE

base_model=TheBloke/Starling-LM-7B-alpha-GGUF
prompt_type='?'

export PIP_EXTRA_INDEX_URL="https://download.pytorch.org/whl/cpu"

git clone https://github.com/h2oai/h2ogpt.git
cd h2ogpt
pip install -r requirements.txt
pip install -r reqs_optional/requirements_optional_langchain.txt
pip install -r reqs_optional/requirements_optional_gpt4all.txt
pip install -r reqs_optional/requirements_optional_langchain.urls.txt
# GPL, only run next line if that is ok:
pip install -r reqs_optional/requirements_optional_langchain.gpllike.txt

python generate.py --base_model="${base_model}" --prompt_type="${prompt_type}" --max_seq_len=4096
)
```

**Comment by pseudotensor** [comment]
Hi, it's in the list of models we have prompt for already, i.e. from UI it would be seen, but if you are still in CLI we dont make it easy to find out except from code in src/prompter.py.

But it's `--prompt_type=open_chat_correct`

**Comment by pseudotensor** [comment]
Also, probably 'openchat/openchat-3.5-1210' is better model.
