### ISSUE TITLE
Load evaluations json in UTF

### ISSUE THREAD

**Issue by vlsav** [h2oai/h2ogpt#1244]
Hi,
Encountered issue with evaluations loaded from --eval_filename under Windows.
By default they are loading with non-utf codepage, thus non-English characters typically are loaded incorrectly.
Suggest to change
           data = json.load(open(eval_filename, 'rt'))
to
           data = json.load(open(eval_filename, 'rt'), , encoding="utf-8")
Also langchain is not-working in eval mode, is it possible to add it as well?
I just copied from cli.py to eval.py this section at similar location, changing eval_vars to corresponding name and it works:
            # grab other parameters, like langchain_mode
            for k in eval_func_param_names:
                if k in locals():
                    eval_vars[eval_func_param_names.index(k)] = locals()[k]

**Comment by pseudotensor** [comment]
Fixed, thanks!

**Comment by vlsav** [comment]
Thanks! I mispinted correction, sorry. Corrected it now. As I understood now json.load doesn't support encode parameter.
It is possible while file loading.

**Comment by pseudotensor** [comment]
Ok please test new changes.  The test I added didn't fail, so I didn't notice the issue either.  Please test with relevant file.

**Comment by vlsav** [comment]
The code itself works. But need to put it inside else block also, where custom eval.json is loaded (line 174).
Thanks in advance.
