### ISSUE TITLE
Maintain context with Gradio Client

### ISSUE THREAD

**Issue by syllith** [h2oai/h2ogpt#1247]
I am using the following code to send a simple query to h2ogpt:

```
import sys
from gradio_utils.grclient import GradioClient

def read_prompt_from_file(file_path):
    with open(file_path, 'r') as file:
        return file.read()

if __name__ == "__main__":
    instruction = sys.argv[1]
    
    system_prompt = read_prompt_from_file("prompt.txt")

    kwargs = {
        'system_prompt': system_prompt,
        'langchain_mode': "UserData",
        'document_subset': "Relevant",
    }
    
    client = GradioClient("http://localhost:7860/")
    response = client.query(instruction, **kwargs)
    
    print(response)
```

This is working, however, I don't understand how I am supposed to get h2ogpt to maintain context throughout a conversation. I've built this python program into a standalone executable that gets called from an express server. This effectively provides a friendly API that I can just supply the query to, which in turn invokes the python program and returns an answer. 

It is my understanding that if we were to send another request, it would be a completely new context, so the new answer wouldn't factor in anything from the old answer. I've tried looking for documentation and in the grclient.py file for anything that will help me maintain a "session", but I've yet to find anything. It's capable of doing this in h2ogpt's web interface, but is there a way for me to do this such as supplying some sort of session ID or token that lets h2ogpt know which conversation it should be answer to?

**Comment by pseudotensor** [comment]
Hi, by default GradioClient() is only for one-off actions that don't preserve the session state.  This is controlled by the piece of code:
```
client = self.clone()
```
inside the helper wrapper `query_or_summarize_or_extract`.  If you want it to persist the session hash of the gradio client, then remove that line.

**Comment by syllith** [comment]
Interesting. I think I may have found another approach that works for me and was hoping to get some feedback on it. I noticed that there was a chat_conversation variable that seems to do what I need. Here's what I came up with:

Instead of the python script simply taking in a query, instead I take in a query and a chat ID number, which can be generated from another program. This creates a file in a chat_history folder and effectively stores the queries and responses of the user and LLM. Each time we send a query that has an existing chat ID number, it sends that data into gradio using the chat_conversation variable. 

To test if this worked, I asked it what 2+2 was, then made a separate query that said "Add 5 to the previous answer", and it replied with 9. So it certainly seems like it's working now. Do you see this as a rational approach for me to handle chat history? 

```
import sys
import os
from gradio_utils.grclient import GradioClient

def read_prompt_from_file(file_path):
    with open(file_path, 'r') as file:
        return file.read()

def get_chat_history(chat_id):
    chat_history_file = f'chat_history/{chat_id}.txt'
    if os.path.exists(chat_history_file):
        with open(chat_history_file, 'r') as file:
            return [tuple(line.strip().split('||')) for line in file.readlines()]
    return []

def update_chat_history(chat_id, user_input, bot_response):
    chat_history_file = f'chat_history/{chat_id}.txt'
    with open(chat_history_file, 'a') as file:
        file.write(f'{user_input}||{bot_response}\n')

if __name__ == "__main__":
    instruction = sys.argv[1]
    chat_id = sys.argv[2]
    
    system_prompt = read_prompt_from_file("prompt.txt")
    chat_history = get_chat_history(chat_id)

    kwargs = {
        'system_prompt': system_prompt,
        'langchain_mode': "UserData",
        'document_subset': "Relevant",
        'chat_conversation': chat_history
    }
    
    client = GradioClient("http://localhost:7860/")
    response = client.query(instruction, **kwargs)
    
    update_chat_history(chat_id, instruction, response)
    print(response)
```

**Comment by pseudotensor** [comment]
Yes for chat history, chat_conversation is like gradio history, client side can maintain history so no other state needs to be persisted.

For document uploads to be persisted to some client, you’ll need my changes and pass persist=True.
