### ISSUE TITLE
Windows manual install, some error and strange behaviour

### ISSUE THREAD

**Issue by Werve** [h2oai/h2ogpt#1248]
In my attempt to use a newer version of the available one-click installer, I tried the manual installation procedure on Windows. 
After numerous trials (and several days of deleting and starting over), I noticed some discrepancies and errors which I report:

- In the readme there is the following line 
`set PIP_EXTRA_INDEX_URL="https://download.pytorch.org/whl/cu118"`
but I noticed that the expected behavior occurs by removing the quotes or writing instead 
`set "PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu118"`

- After all the reported installations I tried to load the model `TheBloke/zephyr-7B-beta-AWQ` but it reported the following errors:
```
Starting get_model: TheBloke/zephyr-7B-beta-AWQ
Starting get_model: TheBloke/zephyr-7B-beta-AWQ
Starting get_model: TheBloke/zephyr-7B-beta-AWQ
Starting get_model: TheBloke/zephyr-7B-beta-AWQ
Traceback (most recent call last):
  File "F:\h2oGPT\installer_files\env\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "F:\h2oGPT\installer_files\env\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\h2oGPT\installer_files\env\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "F:\h2oGPT\installer_files\env\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\h2oGPT\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\h2oGPT\installer_files\env\lib\site-packages\anyio\backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\h2oGPT\installer_files\env\lib\site-packages\anyio\backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\h2oGPT\installer_files\env\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "F:\h2oGPT\h2ogpt\src\gradio_runner.py", line 5170, in load_model
    model1, tokenizer1, device1 = get_model_retry(**gradio_model_kwargs)
  File "F:\h2oGPT\h2ogpt\src\gen.py", line 2263, in get_model_retry
    model1, tokenizer1, device1 = get_model(**kwargs)
  File "F:\h2oGPT\h2ogpt\src\gen.py", line 2413, in get_model
    model_loader, tokenizer_loader, conditional_type = get_loaders(**loader_kwargs)
  File "F:\h2oGPT\h2ogpt\src\loaders.py", line 100, in get_loaders
    from awq import AutoAWQForCausalLM
  File "F:\h2oGPT\installer_files\env\lib\site-packages\awq__init__.py", line 2, in <module>
    from awq.models.auto import AutoAWQForCausalLM
  File "F:\h2oGPT\installer_files\env\lib\site-packages\awq\models\__init__.py", line 1, in <module>
    from .mpt import MptAWQForCausalLM
  File "F:\h2oGPT\installer_files\env\lib\site-packages\awq\models\mpt.py", line 1, in <module>
    from .base import BaseAWQForCausalLM
  File "F:\h2oGPT\installer_files\env\lib\site-packages\awq\models\base.py", line 12, in <module>
    from awq.quantize.quantizer import AwqQuantizer
  File "F:\h2oGPT\installer_files\env\lib\site-packages\awq\quantize\quantizer.py", line 11, in <module>
    from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
  File "F:\h2oGPT\installer_files\env\lib\site-packages\awq\modules\linear.py", line 4, in <module>
    import awq_inference_engine # with CUDA kernels
ImportError: DLL load failed while importing awq_inference_engine
```
I also tried running the llama-cpp-python compilation as described:
```
pip uninstall -y llama-cpp-python
set LLAMA_CUBLAS=1
set CMAKE_ARGS=-DLLAMA_CUBLAS=on
set FORCE_CMAKE=1
pip install llama-cpp-python==0.2.23 --no-cache-dir --verbose
```
but the same situation occurs.

Strangely if instead I load the same GGUF model, which from prompt window it reports loaded correctly, then I unload it and try to load the AWQ one again this time the error does not occur and it works.

- I followed in the last attempt the installation as described of cuda:
 ```
conda install cudatoolkit=11.7 -c conda-forge -y
 set CUDA_HOME=$CONDA_PREFIX
```
but in the rest of the procedure we refer to version 11.8, it is not clear to me if 11.7 is needed then or it is a typo

- I have used a miniconda environment with the same mode (.bat files) as used in oobabooga/text-generation-webui for convenience and at startup always gets this warning which does not seem to affect operation:
```
F:\h2oGPT\installer_files\env\lib\site-packages\pydantic_internal\_fields.py:149: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
F:\h2oGPT\installer_files\env\lib\site-packages\pydantic_internal\_fields.py:149: UserWarning: Field "model_names" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
OpenAI API URL: http://0.0.0.0:5000
OpenAI API key: EMPTY
```

- When I select a different model, this warning (which does not seem to affect operation) also appears: 
```
F:\h2oGPT\installer_files\env\lib\site-packages\gradio\components\dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: or set allow_custom_value=True.
  warnings.warn(
Got prompt_type 1:
```

**Comment by pseudotensor** [comment]
Hi, the AWQ thing looks like its specific to AWQ.  I don't have any good ideas w.r.t. that.

Note that GGUF and AWQ are independent.  If you are finding AWQ sometimes works, probably some race/bug in AWQ.  Please check their repo: https://github.com/casper-hansen/AutoAWQ and post an issue if you can just follow their basic instructions.

If you find their basic instructions work but h2oGPT does not, I can look again.

**Comment by pseudotensor** [comment]
I don't think `set "PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu118"` is correct, it probably makes it use non-cuda torch and then since AWQ only supports cuda then it would fail, might explain your situation.

Closing for now until get evidence that not AWQ issue.

**Comment by Werve** [comment]
> I'm sure about:
> 
> ```
> F:\h2oGPT\installer_files\env\lib\site-packages\gradio\components\dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: or set allow_custom_value=True.
>   warnings.warn(
> Got prompt_type 1:
> ```
> 
> Can you explain exactly what you did to hit this?

If I remember correctly I loaded and then unloaded, with the relative buttons, the same model

**Comment by Werve** [comment]
> I don't think `set "PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu118"` is correct, it probably makes it use non-cuda torch and then since AWQ only supports cuda then it would fail, might explain your situation.
> 
> Closing for now until get evidence that not AWQ issue.

I mean in the readme for Windows it said:
https://github.com/h2oai/h2ogpt/blob/89a56df379a2b7a39cc58846bd801013dbc6ac81/docs/README_WINDOWS.md?plain=1#L58
but then looking at the pip command response it seems to have loaded the url with quotes. 
Writing instead:
`set "PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu118"`
brings back the intended url.

**Comment by Werve** [comment]
> > I'm sure about:
> > ```
> > F:\h2oGPT\installer_files\env\lib\site-packages\gradio\components\dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: or set allow_custom_value=True.
> >   warnings.warn(
> > Got prompt_type 1:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can you explain exactly what you did to hit this?
> 
> If I remember correctly I loaded and then unloaded, with the relative buttons, the same model

I noticed now that in the list of models the same one appears twice, but I don't see it downloaded in any folder.

![image](https://github.com/h2oai/h2ogpt/assets/13850028/2c3d7dbc-b25e-484e-b86c-5c685d367371)
