### ISSUE TITLE
Context driven conversations

### ISSUE THREAD

**Issue by thusithaC** [h2oai/h2ogpt#126]
Hi Devs,

Great work! There is a lot of potential for OSS LLMs, especially coming from a group like H2O. 

Regarding some tests I've been doing: How do you include context in an instruction? e.g. tasks like summarization, Q&A based on a passage etc. When i was testing Dolly, there was a section under langchain where you can explicitly provide a context (https://huggingface.co/databricks/dolly-v2-12b#langchain-usage) 

Is there a way to get this working with h2oGPT? Ive tried manaully appending a context before / after the instruction, but the model seems to ignore this. I saw a PR for Langchanin integration https://github.com/h2oai/h2ogpt/pull/111, and when this is merged would h2oGPT also support similar examples like what I pointed under Dolly?

Thanks,

**Comment by pseudotensor** [comment]
First, I'll make sure to have a description like DB provide for langchain integration.  It basically involves using our pipeline, but I'll make sure it's tested etc.

As for context, in the langchain case it's just another f string one sets in the prompt format.  langchain by default hides alot of extra contextual things in its prompt for various tasks that are not really well suited for instruct-tuned models.  But I'll make sure to describe that in any doc updates.

Kinda related, but not exactly answering your question:

In the gradio app and API there is a "context" variable.  This is like the system instruction that is pre-appended (only once if in chat mode).

E.g. in expert mode at bottom:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/1e9a8748-815c-4a5a-9dc3-7b75497e696c)


Or for client API:

https://github.com/h2oai/h2ogpt/blob/e7835139eee24d5c371a435710298154c15806cd/client_test.py#L62

**Comment by thusithaC** [comment]
Thanks, interested in server side implementations so will try the api you provided.
