### ISSUE TITLE
Followed instructions exactly, error about H2O_Fire and Fire on run?

### ISSUE THREAD

**Issue by EmmaWebGH** [h2oai/h2ogpt#1260]
Hi
Win 11, manual install. 2x 4090 GPUs. 

Followed all instructions exactly, from this link: https://github.com/h2oai/h2ogpt/blob/main/docs/README_WINDOWS.md#run

As a side note, this instruction makes it look at the URL for EVERYTHING, which is weird.
```
Prefix each pip install with --extra-index-url https://download.pytorch.org/whl/cu118 for GPU install:
 # Required for Doc Q/A: LangChain:
 pip install -r reqs_optional/requirements_optional_langchain.txt
 # Required for CPU: LLaMa/GPT4All:
 pip install -r reqs_optional/requirements_optional_gpt4all.txt
 # Optional: PyMuPDF/ArXiv:
 pip install -r reqs_optional/requirements_optional_langchain.gpllike.txt
 # Optional: Selenium/PlayWright:
 pip install -r reqs_optional/requirements_optional_langchain.urls.txt
 # Optional: for supporting unstructured package
 python -m nltk.downloader all
 # Optional but required for PlayWright
 playwright install --with-deps
 # Note: for Selenium, we match versions of playwright so above installer will add chrome version needed
```
Anyway aside from that URL thing, everything appeared to install. 

Then I try
`python generate.py --base_model=TheBloke/zephyr-7B-beta-GGUF --prompt_type=zephyr --max_seq_len=4096`
(another aside, there are no "run" instructions on that Win page. There is an anchor link at the top of the page but no corresponding section/anchor).

And I get the following in the anaconda shell:
```
(h2ogpt) C:\AI\Text\h2ogpt>python generate.py --base_model=TheBloke/zephyr-7B-beta-GGUF --prompt_type=zephyr --max_seq_len=4096
Using Model llama
Traceback (most recent call last):
  File "C:\AI\Text\h2ogpt\generate.py", line 16, in <module>
    entrypoint_main()
  File "C:\AI\Text\h2ogpt\generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "C:\AI\Text\h2ogpt\src\utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "C:\Users\MyCompy\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\MyCompy\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\MyCompy\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\AI\Text\h2ogpt\src\gen.py", line 1620, in main
    from src.gpt_langchain import get_embedding
  File "C:\AI\Text\h2ogpt\src\gpt_langchain.py", line 34, in <module>
    from langchain.callbacks import streaming_stdout
  File "C:\Users\MyCompy\miniconda3\envs\h2ogpt\lib\site-packages\langchain\callbacks\__init__.py", line 45, in <module>
    from langchain_core.tracers.context import (
ImportError: cannot import name 'tracing_enabled' from 'langchain_core.tracers.context' (C:\Users\MyCompy\miniconda3\envs\h2ogpt\lib\site-packages\langchain_core\tracers\context.py)
```

Can anyone point me as to what I've done wrong?

I didn't want to use the one-click installer as it looks like this is not updated very much. Last version is from November.

Thanks!

**Comment by EmmaWebGH** [comment]
Additionally on the note about the Windows docs:
Looking at a 3month old YT video, I can see the windows docs did used to have a RUN section. 
https://www.youtube.com/watch?v=aE8rxzTLld8

It's no longer there, but the hyperlink at the top seems to imply it should be.

Just mentioning this in case there is an additional step or few we should have done?

Final note: I followed the instructions on the page, but did compare back to that YT vid.
But I took the Win documentation page as the steps and order - not the out-of-date vid, in case that question came up.

**Comment by EmmaWebGH** [comment]
One more note, the URL issue I mentioned above is also discussed by the OP of this issue:https://github.com/h2oai/h2ogpt/issues/1248

So possibly my installation is flawed, since I did exactly what the docs said to do, but this user is saying the quote marks are in the wrong place for that URL to properly apply during install?

**Comment by EmmaWebGH** [comment]
Update
Due the semantics error detailed in 1248, I deleted the conda env and tried again from scratch.
This time, I got zero red or yellow text (errors).
On the other hand, basically everything it said was using cached version.
So what I can't work out is, if the first time around the extra index had characters out of place, so it DIDN'T look at the correct index, it got whatever, then 2nd time around despite clearing the env, it's still using the wrong things, because it was using the stuff from first time around from the cache.
Because
I get the same error after getting to the end of the Windows/GPU doc, then running
`python generate.py --base_model=TheBloke/zephyr-7B-beta-GGUF --prompt_type=zephyr --max_seq_len=4096`

Error is:
```
(h2ogpt) C:\AI\Text\h2ogpt>python generate.py --base_model=TheBloke/zephyr-7B-beta-GGUF --prompt_type=zephyr --max_seq_len=4096
Using Model llama
Traceback (most recent call last):
  File "C:\AI\Text\h2ogpt\generate.py", line 16, in <module>
    entrypoint_main()
  File "C:\AI\Text\h2ogpt\generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "C:\AI\Text\h2ogpt\src\utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "C:\Users\MyCompy\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\MyCompy\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\MyCompy\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\AI\Text\h2ogpt\src\gen.py", line 1620, in main
    from src.gpt_langchain import get_embedding
  File "C:\AI\Text\h2ogpt\src\gpt_langchain.py", line 34, in <module>
    from langchain.callbacks import streaming_stdout
  File "C:\Users\MyCompy\miniconda3\envs\h2ogpt\lib\site-packages\langchain\callbacks\__init__.py", line 45, in <module>
    from langchain_core.tracers.context import (
ImportError: cannot import name 'tracing_enabled' from 'langchain_core.tracers.context' (C:\Users\MyCompy\miniconda3\envs\h2ogpt\lib\site-packages\langchain_core\tracers\context.py)
```

I even put this into ChatGPT and it said I should try uninstalling/reinstalling Langchain Core, and/or upgrading it to latest version, both of which do nothing to stop the error.

Should I try a third time, with caches cleared, and the correctly formatted extra-index line?

**Comment by pseudotensor** [comment]
Langchain broke their package updates with unpinned changes.      I've adding pinnings so things don't drift.  So fixed in main, docker image being built.

**Comment by pseudotensor** [comment]
5674a758c6c529bc0c6bdb0f9ca4a47c9c6b74af

**Comment by pseudotensor** [comment]
If you want to just fix your already-present env, do:
```
pip install langchain==0.0.350 langchain_experimental==0.0.47 langchain-community==0.0.8 langsmith==0.0.77 langchain-core==0.1.6
```

**Comment by EmmaWebGH** [comment]
Awesome, thank you so much!

**Comment by EmmaWebGH** [comment]
Sorry to add to this, just one last question.
The fix worked, gradio UI is up. Thankyou @pseudotensor!

Just wanted to check if these errors should be any concern?

```
C:\Users\REDACTED\miniconda3\envs\h2ogpt\lib\site-packages\pydantic\_internal\_fields.py:149: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
C:\Users\REDACTED\miniconda3\envs\h2ogpt\lib\site-packages\pydantic\_internal\_fields.py:149: UserWarning: Field "model_names" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
```

Cheers

**Comment by pseudotensor** [comment]
No concern.
