### ISSUE TITLE
Download folder / .cache file settings==> MISSING!!

### ISSUE THREAD

**Issue by cocobeach** [h2oai/h2ogpt#1261]
This software goes to show that even the greatest developments can fail a basic UAT!!!

Why not allowing users to chose a download folder, or alter it in settings? 

Sop is that we are dealing with huge files, why on C:/ drive, knowing that it is in the intrinsic nature of the application to download file in the tens of gigabytes?

Also, I already have a lot of models on my drive, why do I have to re-download them again?

**Comment by pseudotensor** [comment]
If you mean llama.cpp type models, that is controllable:

https://github.com/h2oai/h2ogpt/blob/3db5ad906a961f5b5e76bacc388f9461ba042711/src/gen.py#L553-L555

If you mean HF transformer models, that uses its own path, ~/.cache is just default and can be changed however you like according to their documentation.

**Comment by cocobeach** [comment]
Fair enough, but you are going to annoy a lot of peeps that don't know where their cache is, or which one of those 5000 lines does that, and don't even understand what HF vs llama is.
I was just so happy you had an installed I didn't have to fiddle in-line.

You guys need to add this to the high priority bug list, because YOU MUST allow users to chose where to download such big files when installing, chiding the install directory is marginally less critical, it's not a luxury.

Very little people have system SSD that can accomodate several gb like this.

Other UI parameters are luxury, this is not, this omission is a mistake.

Otherwise congrats on the smoothness on how the model runs! It's very fast on xwin, and very accurate.

**Comment by cocobeach** [comment]
And thank you for such a quick answer!

**Comment by pseudotensor** [comment]
I understand.  We depend upon many packages, and that things go to /tmp or ~/.cache by default is quite standard.  I'll add note in FAQ about your question.

  One should set env `TRANSFORMERS_CACHE` to change the ~/.cache location

![image](https://github.com/h2oai/h2ogpt/assets/2249614/43b4c760-7ed8-4fc7-be52-ef70313c89f6)
