### ISSUE TITLE
Can't change model, httpx module not found

### ISSUE THREAD

**Issue by Someguitarist** [h2oai/h2ogpt#1265]
Hey, just trying to get started here using Ubuntu and a 2080Ti and docker-compose.  Been using text-gen for a while, but wanted to test this out as well.

I see that I'm running out of memory just starting the docker-compose.  So I looked at the low memory options and just trying to run

python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --score_model=None --load_8bit=True --langchain_mode='UserData'

I get 

Traceback (most recent call last):
  File "/home/stokley/AI/h2ogpt-main/h2ogpt-main/generate.py", line 7, in <module>
    from src.gen import main
  File "/home/stokley/AI/h2ogpt-main/h2ogpt-main/src/gen.py", line 15, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

What am I missing here?  My first thought was I need to execute the python command inside the container, but since the container keeps crashing with out of memory I'm not sure how I'm supposed to do that?

Thanks for your help!

**Comment by pseudotensor** [comment]
What does `pip freeze` show?  Seems like install is incomplete.

**Comment by davide445** [comment]
I go the same problem, exexcuting
python3.10 ./generate.py --base_model=TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ --load_gptq=model --load_4bit=True --use_safetensors=True --prompt_type=mistral --save_dir='/workspace/save/' --use_gpu_id=False --score_model=None --max_max_new_tokens=2048 --max_new_tokens=1024

I got


Traceback (most recent call last):
  File "/workspace/./generate.py", line 7, in <module>
    from src.gen import main
  File "/workspace/src/gen.py", line 15, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

pip freeze show

anyio==4.2.0
cachetools==5.3.2
certifi==2019.11.28
chardet==3.0.4
dbus-python==1.2.16
distro-info==0.23+ubuntu1.1
exceptiongroup==1.2.0
h11==0.14.0
httpcore==0.17.3
httpx==0.24.1
idna==2.8
nvidia-ml-py==12.535.133
nvitop==1.3.2
pipx==0.12.3.1
psutil==5.9.7
PyGObject==3.36.0
python-apt==2.0.1+ubuntu0.20.4.1
requests==2.22.0
requests-unixsocket==0.2.0
six==1.14.0
sniffio==1.3.0
termcolor==2.4.0
typing-extensions==4.9.0
unattended-upgrades==0.1
urllib3==1.25.8

**Comment by pseudotensor** [comment]
It's there

https://github.com/h2oai/h2ogpt/blob/main/requirements.txt#L71

**Comment by pseudotensor** [comment]
From your pip freeze it seems like you are showing inside of docker?

```
/workspace/./generate.py
```

Or not?  

Can you even do:
```
python
```
then do:
```
import httpx
```
?

I suspect your pip ran in different environment than the generate.py uses.

**Comment by davide445** [comment]
Yes it's running in a cloud docker image on an A6000. I have only access to it inside a docker image.
It's not clear to me what env generate.py is running on.

**Comment by Someguitarist** [comment]
Yeah, I couldn't get this to work on either Windows or a Linux PC through docker-compose.  Kept getting the same error listed above.  I might try to just run it without docker.  It's unfortunate, because I'm running like ~30 containers so I'm not super new to docker or anything.  :/

**Comment by pseudotensor** [comment]
FYI we run docker compose with h2ogpt docker all the time.  @achraf-mer any idea what could be wrong?

**Comment by davide445** [comment]
I have overcomed this problem working as root inside the container, when I created a new user and used sudo I got always this problem. On the contrary of someuitarist I'm not a Docker expert so no idea why, maybe there is a way to make it work also with an user without root privileges.

**Comment by pseudotensor** [comment]
I use docker all the time myself, and the way to set the user is shown in the instructions.

https://github.com/h2oai/h2ogpt/blob/main/docs/README_DOCKER.md#run-h2ogpt-using-docker

**Comment by Someguitarist** [comment]
Sorry, just to be clear, I'm definitely no expert at all!  I just run a lot of them!

Yeah, just to follow up I'm using the docker-compose instructions mentioned at the link below, not the regular docker setup instructions, and I'm getting the same error on Linux and Windows.

https://github.com/h2oai/h2ogpt/blob/main/docs/README_DOCKER.md#docker-compose-setup--inference

**Comment by Someguitarist** [comment]
Hey, just to update, changing the docker-compose to gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0-275 worked for me!  Thanks for ya'lls help.

**Comment by pseudotensor** [comment]
@achraf-mer can confirm, but when you compose with :latest I think it doesn't by default download any new image.  You have to docker pull first.  :latest is just a tag, and otherwise refers to just the local tag.

**Comment by achraf-mer** [comment]
> @achraf-mer can confirm, but when you compose with :latest I think it doesn't by default download any new image. You have to docker pull first. :latest is just a tag, and otherwise refers to just the local tag.

yes, have to pull first, or use the latest code which will build fro the Dockerfile instead of pulling.

**Comment by pseudotensor** [comment]
let's assume that is the issue.
