### ISSUE TITLE
Avatars do not display

### ISSUE THREAD

**Issue by Symbolics** [h2oai/h2ogpt#1268]
```
INFO:     127.0.0.1:3254 - "GET /file%3Dmodels/human.jpg HTTP/1.1" 403 Forbidden
INFO:     127.0.0.1:3255 - "GET /file%3Dmodels/lama2.jpeg HTTP/1.1" 403 Forbidden
INFO:     127.0.0.1:3255 - "GET /file%3Dmodels/human.jpg HTTP/1.1" 403 Forbidden
INFO:     127.0.0.1:3254 - "GET /file%3Dmodels/lama2.jpeg HTTP/1.1" 403 Forbidden
INFO:     127.0.0.1:3255 - "GET /file%3Dmodels/lama2.jpeg HTTP/1.1" 403 Forbidden
```

This is on MS Windows, from HEAD checked out  6 Jan 2024.  The files exist and are readable by all; it's the URL that's incorrect.

**Comment by pseudotensor** [comment]
Not sure about that.  This is what I see:

```
INFO:     3.96.18.57:34292 - "GET /file%3Dmodels/mistralai.png HTTP/1.1" 200 OK
INFO:     3.96.18.57:34308 - "GET /file%3Dmodels/meta.png HTTP/1.1" 200 OK
INFO:     3.96.18.57:34310 - "GET /file%3Dmodels/human.jpg HTTP/1.1" 200 OK
INFO:     3.96.18.57:34334 - "GET /file%3Dmodels/hf-logo.png HTTP/1.1" 200 OK
INFO:     3.96.18.57:34344 - "GET /file%3Dmodels/openai.png HTTP/1.1" 200 OK
```

So same thing.  Probably in windows the path is not quite right for some reason.

**Comment by snunez1** [comment]
It's not a firewall error.  [Error 403](https://en.wikipedia.org/wiki/HTTP_403) is:

> HTTP 403 is an [HTTP status code](https://en.wikipedia.org/wiki/HTTP_status_code) meaning access to the requested resource is forbidden. The server understood the request, but will not fulfill it, if it was correct.

However I have found the problem: I am running it from a network share and I believe MS Windows restricts access to these files over the network somehow.  Running it from a local drive works fine.

**Comment by pseudotensor** [comment]
"firewall like" meaning access if forbidden, file-network issue in agreement with what you found.
