### ISSUE TITLE
Windows installer is missing web search, downloaded models disappear.

### ISSUE THREAD

**Issue by arduiron** [h2oai/h2ogpt#1271]
After enabling web search and restarting h2oGTP the previously loaded model was lost.
Nothing worked anymore. Web search became available but no model could be loaded or downloaded.
Local GGFU Models cannot be used from their original location, they have to be imported, causing unneccessary space usage on the harddisk. Everytime "submit" is clicked many dos-windows popups appear and quickly disappear.
Other products like privateGPT, LM Studio and localGPT clearly show the location of models.

Uninstalled h2oGPT because it is an unfinished product. 
Even stopping it requires killing python process.
LM Studio is much more practical for local use.

**Comment by pseudotensor** [comment]
The one-lock windows installer is from Nov 5 and doesn't have certain features yet that cover all your pain points.
