### ISSUE TITLE
unstructured[local-inference] issue

### ISSUE THREAD

**Issue by MSZ-MGS** [h2oai/h2ogpt#1277]
When I install "unstructured[local-inference]==0.11.8", it automatically downgrade "torch==2.1.2"

Screenshot below for reference.
![image](https://github.com/h2oai/h2ogpt/assets/65172063/42844513-d19d-4dd9-8f36-2936d1140ed0)

**Comment by pseudotensor** [comment]
Hmm, I didn't see that.

Are you using GPU case?  Why is torch without cu118?   Are you missing the setting of `PIP_EXTRA_INDEX_URL` ?

It may be too late to see, but what happens if you do:
```
pip install unstructured[local-inference]==0.11.8 -c requirements.txt
```
For me this doesn't complain and just is happy with torch 2.1.2+cu118

**Comment by pseudotensor** [comment]
FYI in my case I just updated with pip install -r on some req files.

But I also tested fresh env, and of course our nightly docker tests that too.

Sharing the result of my
```
GPLOK=1 bash docs/linux_install.sh &> install1.log
GPLOK=1 bash docs/linux_install.sh &> install2.log
```

firs time my system hit issue with bad repo I had to remove from ubuntu, unsigned, not related to h2oGPT.

[install2.log](https://github.com/h2oai/h2ogpt/files/13896150/install2.log)
[install1.log](https://github.com/h2oai/h2ogpt/files/13896151/install1.log)

Once that's done, I see no problem with torch

pip freeze shows:
```
(/data/conda/h2ogpt_test) jon@pseudotensor:~/h2ogpt$ pip freeze | grep torch
torch==2.1.2+cu118
torchaudio==2.1.2+cu118
torchvision==0.16.2+cu118
```

**Comment by MSZ-MGS** [comment]
I tried pip install unstructured[local-inference]==0.11.8 -c requirements.txt, it looks fine.

Log
[Anaconda Prompt (miniconda3).txt](https://github.com/h2oai/h2ogpt/files/13929115/Anaconda.Prompt.miniconda3.txt)

System:
Windows 11 : Insider.
Using latest llama.cpp from llama repo.

**Comment by pseudotensor** [comment]
Yes, that worked fine.  But I don't know what led to reversion to torch 2.0.0 before.

What if you run yet again without the -c part?  Does it go back to torch 2.0.0?
