### ISSUE TITLE
Document selection not working

### ISSUE THREAD

**Issue by snunez1** [h2oai/h2ogpt#1280]
Asking htogpt to summarise a document doesn't seem to be working.  It summarises the 'wrong' document.  Here's what I did.

1. Placed a PDF file in `user_path`.  On startup it was added to the DB
2. 'ingested' a second PDF file via a URL.  It shows up in the DB (but not in the filesystem)
3. In `Document Selection` tab, select the ingested PDF document
4. In `Chat` tab, select the `summarise` radio box and click `submit`

What I _expect_ is a summarisation of the selected document.
What I _get_ is a summarisation of the first document (the one in `user_path`)

**Comment by pseudotensor** [comment]
Are you sure you didn't keep "All" selected?

**Comment by snunez1** [comment]
Yes, that was it. Perhaps a more intuitive selection mechanism?

**Comment by pseudotensor** [comment]
I'm open to ideas.

I have to work within confines of gradio. Here I'm not sure what to do.

I could make it so if nothing is selected it means all, so that once something is selected it means that one thing, but then confusing that nothing selected means all.

**Comment by snunez1** [comment]
I can think of two possibilities:

1. Use the 'all' selection as a toggle: if you click it, then all of the documents appear with a check.  Click it again, and they are all deselected.  This would be convenient for the 'all except' use case (user selects all and then individually deselects those he doesn't want).
2. Use a widget other than a drop-down.  I think a list widget, scrollable, would make it more clear as to which documents are selected.

**Comment by pseudotensor** [comment]
Thanks, good ideas.

There's no list widget, but another alternative is to use the file explorer in gradio 4 to effectively explore more easily the list of items.

The only problem with select all vs. not all or this is that at some point the list is too large (e.g. all of wikipedia) and I can't push the whole list to the UI, so it wouldn't work in that large mode, but I can consider it for default mode.
