### ISSUE TITLE
Launching h20GPT from cmd line deletes my models folder. 500gb GONE

### ISSUE THREAD

**Issue by Rotoslider** [h2oai/h2ogpt#1283]
Windows 10 with fresh fresh install on Jan 10th of the windows installer. I have a 2tb m2 drive that I **had** a folder called models on. I stored all my LLM models there.**500+gb** of downloads. When I run `K:\h2oGPT\Python\python.exe "K:\h2oGPT\h2oGPT.launch.pyw"` it deletes the models folder. Which was located at K:\models. This was not an issue on the Nov windows installer.
I created a replacement folder and watched it as I launched h20GPT and poof it was gone again. Not cool to be deleting folders that are not part of the install. I have slow internet. This will take me weeks to get back what it stole. Unfortunately not all was backed up on a separate drive. 
`K:\h2oGPT\..\src
K:\h2oGPT\pkgs\..\src
K:\h2oGPT\..\iterators
K:\h2oGPT\pkgs\..\iterators
K:\h2oGPT\..\gradio_utils
K:\h2oGPT\pkgs\..\gradio_utils
K:\h2oGPT\..\metrics
K:\h2oGPT\pkgs\..\metrics
K:\h2oGPT\..\models
K:\h2oGPT\pkgs\..\models
K:\h2oGPT\..\.
K:\h2oGPT\pkgs\..\.
Traceback (most recent call last):
  File "K:\h2oGPT\h2oGPT.launch.pyw", line 35, in <module>
    main()
  File "K:\h2oGPT\pkgs\win_run_app.py", line 145, in main
    _main()
  File "K:\h2oGPT\pkgs\win_run_app.py", line 81, in _main
    setup_paths()
  File "K:\h2oGPT\pkgs\win_run_app.py", line 65, in setup_paths
    copy_tree(base0, os.environ['MODEL_BASE'])
  File "K:\h2oGPT\pkgs\win_run_app.py", line 37, in copy_tree
    shutil.copytree(src, dst)
  File "shutil.py", line 554, in copytree
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'K:\\h2oGPT\\..\\models'`

**Comment by pseudotensor** [comment]
Sorry this happened.  There is a "models" folder that is part of the install and it should only be moving those contents into a new folder.

I'll comment out the relevant code until this is understood better.

**Comment by pseudotensor** [comment]
If it's any consolation, just today I lost all data on gpt.h2o.ai and gpt-docs.h2o.ai due to some random engineer at fluid stack that deleted the instances.  About 4TB of data.

**Comment by pseudotensor** [comment]
Added more conditions so only the expected directory with expected contents is copied, and only the specified path (default installation) handles models folder.
