### ISSUE TITLE
local  Release' no longer has a Release file: error code 100:  during Linux installation.

### ISSUE THREAD

**Issue by RACMUP** [h2oai/h2ogpt#1289]
In Ubuntu 22.04.3 LTS following README_LINUX.md installation
On executing “bash docs/linux_install.sh”, This error occurs:

Reading package lists... Done
E: The repository 'file:/var/cuda-repo-ubuntu2004-12-1-local  Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'file:/var/cuda-repo-ubuntu2204-11-8-local  Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Failed to install browsers
Error: Installation process exited with code: 100

On executing : “import torch”, this error occurs:
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/426.

Restarted and rerun script returns same error.

**Comment by pseudotensor** [comment]
Your package list file is messed up.  

Google search "remove repo from package list ubuntu"

Use UI or remove manually from the files until the `E:` are no longer present.

**Comment by pseudotensor** [comment]
BTW, if you want to keep the latest chrome and you are using chrome, you should avoid the chromedriver steps
