### ISSUE TITLE
allow_upload_to_user_data=False ignored

### ISSUE THREAD

**Issue by wypiki** [h2oai/h2ogpt#1296]
I'd like to have 3 shared collections and 1 pure LLM mode (default) available for everyone, and a way for them to add their own temporary private documents which are not available to others, only for that user and that session. The way I understood it (and tested it), I have to use the following parameters:

`generate.py (...)

--langchain_modes=['Temp_docs','shared1','shared2','shared3']

--langchain_mode_paths="{'Temp_docs':'C:\\temp_docs','shared1':'C:\\shared1','shared2':'C:\\shared2','shared3':'C:\\shared3'}"

--langchain_mode_types={'Temp_docs':'personal','shared1':'shared','shared2':'shared','shared3':'shared'}

--allow_upload_to_user_data=False

--langchain_mode='LLM'`

The problem with this is: despite allow_upload_to_user_data being set to False, everyone can add documents to every collection. They should only be able to add documents to their own temporary location. It would even be ok if it would be persistent, but they shouldn't be able to add to every collection.
What would I need to do for that?

**Comment by pseudotensor** [comment]
Thanks, it's been fixed.  It was not implemented as deeply as the comments int he code would suggest, but now it's fixed.

**Comment by wypiki** [comment]
Thanks, that was quick! What's the quickest way to upgrade to the new code? (manual install on Windows)

**Comment by pseudotensor** [comment]
I only changed the code, no packages, so  just `git pull` for manual install in windows.
