### ISSUE TITLE
For summarization, if map does full job in single pass, no need for reduce if same prompt

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#1298]
Can make `H2OMapReduceDocumentsChain` be used, but return single entry if kwarg says to do so.

**Comment by wypiki** [comment]
Answering here because the duplicate is closed. Extract gives a much simpler, less detailed summary than the first pass of summary. Also answer appears in brackets and without line breaks.

**Comment by pseudotensor** [comment]
Extract is the exact same operation (map) with same prompt and everything as map_reduce would do, just without the reduce.  Yes, if in the UI, one gets back list instead of string, which isn't pretty.  It's mostly for API use.
