### ISSUE TITLE
Wrong/different CUDA version requirement

### ISSUE THREAD

**Issue by Werve** [h2oai/h2ogpt#1300]
I updated with git pull and re-running the windows bat file installation.
I noticed that the templates were no longer using the GPU so I investigated and I think the problem is the following inconsistent version:
https://github.com/h2oai/h2ogpt/blob/1945d3091aefef140b63672987d855eb7d70a720/reqs_optional/requirements_optional_gpt4all.txt#L17

Instead of
` https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.2.26+cu118avx-cp310-cp310-win_amd64.whl; platform_system == "Windows" 
`
or to flag AVX2=1 
` https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.2.26+cu118-cp310-cp310-win_amd64.whl; platform_system == "Windows" 
`

**Comment by pseudotensor** [comment]
Thanks, I changed it, and it's true that one-click installer used cu118avg for GPU.
