### ISSUE TITLE
Problem with responding to h2ogpt from websites 

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1302]
Why, when uploading a link to a website or web pages to h2ogpt, only flocks appear?
<img width="957" alt="لقطة الشاشة 2024-01-18 185507" src="https://github.com/h2oai/h2ogpt/assets/85692636/e9a0d40e-756f-4264-8312-ab17ebde4ef4">

**Comment by pseudotensor** [comment]
What's a flock?  And what do you expect to happen?

**Comment by odai1001** [comment]
> ما هو القطيع؟ وماذا تتوقع أن يحدث؟

Why, when I add the website link, does the cutting not appear?

**Comment by odai1001** [comment]
> ما هو القطيع؟ هل تتوقع أن يحدث؟

I also want to respond from the site uploaded to h2ogpt without the Internet؟

**Comment by pseudotensor** [comment]
I'm sorry, I can't understand.

**Comment by pseudotensor** [comment]
Will close for now until sufficient details added.
