### ISSUE TITLE
How to import web pages in h2ogpt

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1304]
How to import web pages in h2ogpt ?

**Comment by odai1001** [comment]
<details><summary><font size="2">Document Ingestion (maybe partial) Failure.  Click Undo to remove this message.</font></summary><font size="2">https://en.m.wikipedia.org/wiki/Yemen Exception: Executable doesn't exist at C:\Users\odai\AppData\Local\ms-playwright\chromium-1076\chrome-win\chrome.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝</font></details>

**Comment by odai1001** [comment]
![Uploading Screenshot 2024-01-21 205046.png…]()

**Comment by odai1001** [comment]
<details><summary><font size="2">Document Ingestion (maybe partial) Failure.  Click Undo to remove this message.</font></summary><font size="2">https://en.m.wikipedia.org/wiki/Yemen Exception: Executable doesn't exist at C:\Users\odai\AppData\Local\ms-playwright\chromium-1076\chrome-win\chrome.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝</font></details>

**Comment by pseudotensor** [comment]
How about other URL methods?

**Comment by odai1001** [comment]
libmagic is unavailable but assists in filetype detection on file-like objects. Please consider installing libmagic for better results.
Error fetching or processing https://en.m.wikipedia.org/wiki/Yemen, exception: Invalid file. The FileType.UNK file type is not supported in partition.

**Comment by odai1001** [comment]
> How about other URL methods?

libmagic is unavailable but assists in filetype detection on file-like objects. Please consider installing libmagic for better results.
Error fetching or processing https://en.m.wikipedia.org/wiki/Yemen, exception: Invalid file. The FileType.UNK file type is not supported in partition.

**Comment by pseudotensor** [comment]
Ok, see your other issue.
