### ISSUE TITLE
Starting get_model: llama  Cannot connect

### ISSUE THREAD

**Issue by rdhillbb** [h2oai/h2ogpt#1306]
after a massive effort to change the code to meet the new langchain import standaard, the system starts. However, I am not able to connect to the suggested ports http://127.0.0.1:7860/ or http://localhost:7860/.   Nothing happens. Cannot connect

python generate.py --base_model=TheBloke/zephyr-7B-beta-GGUF --prompt_type=zephyr --max_seq_len=4096

soundfile, librosa, and wavio not installed, disabling STT
soundfile, librosa, and wavio not installed, disabling TTS
Using Model llama
Must install DocTR and LangChain installed if enabled DocTR, disabling
Starting get_model: llama

**Comment by rdhillbb** [comment]
I am on a mac book/Intel running ventura.

**Comment by rdhillbb** [comment]
Found the issue. Still not connecting.

**Comment by pseudotensor** [comment]
Hi, I haven't yet tried to update to new langchain, I'm sure there are issues.
