### ISSUE TITLE
MACBook Pro Intel 32GB: Is this suitable to run h2gpt: Loading model error.

### ISSUE THREAD

**Issue by rdhillbb** [h2oai/h2ogpt#1307]
I get the following error. Is my mac book hardware not suitable ?

Could not load Llama model from path: llamacpp_path/zephyr-7b-beta.Q5_K_M.gguf.

My MacBook is dated. Below are the HW configurations:

2.9 GHz 6-Core Intel Core i9
Radeon Pro 560X 4 GB
Intel UHD Graphics 630 1536 MB
32 GB 2400 MHz DDR4

**Comment by pseudotensor** [comment]
I don't see your error.  It should run fine.

@Mathanraj-Sharma please take look.

**Comment by Mathanraj-Sharma** [comment]
@rdhillbb could you please share the exact error message you are getting
