### ISSUE TITLE
windows version doesn't start because of missing path

### ISSUE THREAD

**Issue by tfriedel** [h2oai/h2ogpt#1313]
I installed the one-click-installer version for windows.
It doesn't start. The log shows this error:

```Traceback (most recent call last):
  File "C:\Users\Thomas\AppData\Local\Programs\h2oGPT\pkgs\win_run_app.py", line 149, in main
    _main()
  File "C:\Users\Thomas\AppData\Local\Programs\h2oGPT\pkgs\win_run_app.py", line 83, in _main
    setup_paths()
  File "C:\Users\Thomas\AppData\Local\Programs\h2oGPT\pkgs\win_run_app.py", line 65, in setup_paths
    shutil.rmtree(os.environ['H2OGPT_MODEL_BASE'])
  File "shutil.py", line 739, in rmtree
  File "shutil.py", line 598, in _rmtree_unsafe
  File "shutil.py", line 595, in _rmtree_unsafe
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Users\\Thomas\\AppData\\Local\\Temp/gradio/\\h2oGPT\\pkgs\\..\\models'
```

**Comment by hudoh** [comment]
I have same issue, I commented this out in win_run_app.py and it started, only temporary solution I suppose, but at least it started.

    # for app, avoid forbidden for web access
    #if os.getenv('H2OGPT_MODEL_BASE'):
    #    base0 = os.environ['H2OGPT_MODEL_BASE']
    #    if 'Programs' in os.environ['H2OGPT_MODEL_BASE']:
    #        os.environ['H2OGPT_MODEL_BASE'] = os.environ['H2OGPT_MODEL_BASE'].replace('Programs', 'Temp/gradio/')
    #        shutil.rmtree(os.environ['H2OGPT_MODEL_BASE'])
    #        if os.path.isfile(os.path.join(base0, 'human.jpg')):
    #            copy_tree(base0, os.environ['H2OGPT_MODEL_BASE'])

**Comment by pseudotensor** [comment]
Thanks!

**Comment by pseudotensor** [comment]
The new one-click loader is uploaded, same location as before.
