### ISSUE TITLE
ingestion takes forever

### ISSUE THREAD

**Issue by carlo088** [h2oai/h2ogpt#1316]
What is the difference between a simple "Upload" of a document and an "Ingestion"? Cause ingestion seems to take forever on my machine and I don't quite understand if I really need it

**Comment by pseudotensor** [comment]
```
Enter to Submit, Shift-Enter adds lines. Just Click Submit for simple Summarize/Extract. Clicking Ingest adds text as URL/ArXiv/YouTube/Text.
```

Ingestion literally takes that url, youtube, text and adds to database for query.

**Comment by carlo088** [comment]
Ok, got it. Thank you
