### ISSUE TITLE
Windows installer - h2oGPT wont load

### ISSUE THREAD

**Issue by ChapmanKU** [h2oai/h2ogpt#1317]
Installed using the latest Jan 2024 one click installer, all goes through smoothly until load time, giving the following errors:

__file__: C:\Users\andyj\AppData\Local\Programs\h2oGPT\pkgs\win_run_app.py
path1 C:\Users\andyj\AppData\Local\Programs\h2oGPT\pkgs
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\andyj\AppData\Local\Programs\Python\Python312\Scripts\;C:\Users\andyj\AppData\Local\Programs\Python\Python312\;C:\Users\andyj\AppData\Local\Microsoft\WindowsApps;;C:\Users\andyj\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\andyj\AppData\Local\Programs\h2oGPT\poppler/Library/bin/;C:\Users\andyj\AppData\Local\Programs\h2oGPT\poppler/Library/lib/;C:\Users\andyj\AppData\Local\Programs\h2oGPT\Tesseract-OCR;C:\Users\andyj\AppData\Local\Programs\h2oGPT\ms-playwright;C:\Users\andyj\AppData\Local\Programs\h2oGPT\ms-playwright/chromium-1076/chrome-win;C:\Users\andyj\AppData\Local\Programs\h2oGPT\ms-playwright/ffmpeg-1009;C:\Users\andyj\AppData\Local\Programs\h2oGPT\ms-playwright/firefox-1422/firefox;C:\Users\andyj\AppData\Local\Programs\h2oGPT\ms-playwright/webkit-1883;C:\Users\andyj\AppData\Local\Programs\h2oGPT\rubberband/
C:\Users\andyj\AppData\Local\Programs\h2oGPT\..\src
C:\Users\andyj\AppData\Local\Programs\h2oGPT\pkgs\..\src
C:\Users\andyj\AppData\Local\Programs\h2oGPT\..\iterators
C:\Users\andyj\AppData\Local\Programs\h2oGPT\pkgs\..\iterators
C:\Users\andyj\AppData\Local\Programs\h2oGPT\..\gradio_utils
C:\Users\andyj\AppData\Local\Programs\h2oGPT\pkgs\..\gradio_utils
C:\Users\andyj\AppData\Local\Programs\h2oGPT\..\metrics
C:\Users\andyj\AppData\Local\Programs\h2oGPT\pkgs\..\metrics
C:\Users\andyj\AppData\Local\Programs\h2oGPT\..\models
C:\Users\andyj\AppData\Local\Programs\h2oGPT\pkgs\..\models
C:\Users\andyj\AppData\Local\Programs\h2oGPT\..\.
C:\Users\andyj\AppData\Local\Programs\h2oGPT\pkgs\..\.
Traceback (most recent call last):
  File "C:\Users\andyj\AppData\Local\Programs\h2oGPT\h2oGPT.launch.pyw", line 35, in <module>
    main()
  File "C:\Users\andyj\AppData\Local\Programs\h2oGPT\pkgs\win_run_app.py", line 149, in main
    _main()
  File "C:\Users\andyj\AppData\Local\Programs\h2oGPT\pkgs\win_run_app.py", line 83, in _main
    setup_paths()
  File "C:\Users\andyj\AppData\Local\Programs\h2oGPT\pkgs\win_run_app.py", line 65, in setup_paths
    shutil.rmtree(os.environ['H2OGPT_MODEL_BASE'])
  File "shutil.py", line 739, in rmtree
  File "shutil.py", line 598, in _rmtree_unsafe
  File "shutil.py", line 595, in _rmtree_unsafe
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\andyj\\AppData\\Local\\Temp/gradio/\\h2oGPT\\pkgs\\..\\models'

Has anyone else had these issues, and how should I overcome them.

Many thanks

**Comment by pseudotensor** [comment]
Yes it's same as: https://github.com/h2oai/h2ogpt/issues/1313

I need to rebuild the installer, for now please remove the `shutil.rmtree(os.environ['H2OGPT_MODEL_BASE'])` line in that file `win_run_app.py`.

**Comment by ChapmanKU** [comment]
Thank you!
