### ISSUE TITLE
Error fetching or processing https://en.m.wikipedia.org/wiki/Yemen, exception: Invalid file. The FileType.UNK file type is not supported in partition.

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1319]
Error fetching or processing https://en.m.wikipedia.org/wiki/Yemen, exception: Invalid file. The FileType.UNK file type is not supported in partition ?

**Comment by odai1001** [comment]
![Uploading Screenshot 2024-01-22 184105.png…]()

**Comment by pseudotensor** [comment]
Hi, I don't have any such problem with gpt.h2o.ai or local install.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/d927d2b4-bbd3-4e08-94f6-65fa76c3040a)


Your screen shot shows nothing, you didn't wait long enough before clicking comment button.

Closing for now.
