### ISSUE TITLE
Why is there no response quickly?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1321]
Why is there no response quickly?
<img width="960" alt="Screenshot 2024-01-22 205907" src="https://github.com/h2oai/h2ogpt/assets/85692636/1040984b-bb53-4607-a5fc-2cd54d501d33">

**Comment by pseudotensor** [comment]
Ensure you pass --prompt_type=llama2 for this model or pick it in the list of prompt types in the UI.
