### ISSUE TITLE
How does h2ogpt respond to images?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1327]
**How does h2ogpt respond to images?**

**Comment by pseudotensor** [comment]
upload the file, it transcribes using blip or other image transcription methods listed.

e.g.

https://github.com/h2oai/h2ogpt/blob/f5d0b627cb5bacf4e838a80b22fb4890a498e0b2/src/gen.py#L1029-L1049
https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#controlling-quality-and-speed-of-parsing
https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#llava-vision-models
