### ISSUE TITLE
Contents in angle brackets are removed from responses and can break WebUI.

### ISSUE THREAD

**Issue by ChiNoel-osu** [h2oai/h2ogpt#1330]
Model: Mistral-7B-Instruct-v0.2

Contents from angle brackets (`<` and `>`) are removed from responses (or being interpreted as format characters). I suppose it's used to delete extra undesired output from the LLM, but sometimes the actual response might contain angle brackets.
For example:
![image](https://github.com/h2oai/h2ogpt/assets/39649720/565d5549-6011-4365-941c-651f156fa270)
While in the console, I could see that the response is correctly generated:
![image](https://github.com/h2oai/h2ogpt/assets/39649720/0a8932a0-fb53-47fe-b1df-992b22236685)

In some cases, it will straight up break the WebUI and a refresh is mandatory.
![image](https://github.com/h2oai/h2ogpt/assets/39649720/89f82f07-fe65-41c3-a7ce-10743646e458)
However response was actually generated:
![image](https://github.com/h2oai/h2ogpt/assets/39649720/dddfdf57-a9af-4dec-8f7e-7abd4d7698f1)

If the angle brackets are in a `code block` then there'll be no problem.

**Comment by pseudotensor** [comment]
https://github.com/gradio-app/gradio/issues/7198

**Comment by pseudotensor** [comment]
![image](https://github.com/h2oai/h2ogpt/assets/2249614/7bf67d8c-9d78-4b7d-83b9-bac158e7ffcf)

**Comment by pseudotensor** [comment]
![image](https://github.com/h2oai/h2ogpt/assets/2249614/164a17b6-7b76-4465-b63e-c114d628ef6e)

**Comment by pseudotensor** [comment]
![image](https://github.com/h2oai/h2ogpt/assets/2249614/66323c04-2cb6-46e8-8a86-0d0f1c1db64f)

**Comment by pseudotensor** [comment]
![image](https://github.com/h2oai/h2ogpt/assets/2249614/ad4f1a15-5374-4fbd-9e2c-1553da90c007)

**Comment by pseudotensor** [comment]
Least covers a few common patterns, but certainly not exhaustive.  Should be handled by gradio.
