### ISSUE TITLE
Can you explain how the options shown in the picture work?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1332]
<img width="128" alt="Screenshot 2024-01-24 175745" src="https://github.com/h2oai/h2ogpt/assets/85692636/256782fd-597d-4c5f-b4a0-359ae80a3e8f">
Can you explain how the options shown in the picture work?

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/blob/main/docs/README_ui.md
