### ISSUE TITLE
Can you explain how the image works?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1333]
<img width="100" alt="Screenshot 2024-01-24 231434" src="https://github.com/h2oai/h2ogpt/assets/85692636/85947a2a-7290-4b4b-877d-e65b450eaab4">
Can you explain how the image works?

**Comment by pseudotensor** [comment]
Agents are experimental, see: https://python.langchain.com/docs/modules/agents/

Best ones are search for many models and csv if you have openai
