### ISSUE TITLE
Can you explain how the image works?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1334]
<img width="106" alt="Screenshot 2024-01-25 175605" src="https://github.com/h2oai/h2ogpt/assets/85692636/a8f8edf8-1301-4377-9a36-3d31521a5b7a">
Can you explain how the image works?

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/blob/main/docs/README_ui.md
