### ISSUE TITLE
How can I make the h2ogpt response in Arabic?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1346]
How can I make the h2ogpt response in Arabic?

**Comment by pseudotensor** [comment]
Chinese example here, you can do same for Arabic:

https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#non-english-languages

But a good arabic model is jais, e.g.:

https://huggingface.co/core42/jais-13b-chat
https://huggingface.co/core42/jais-30b-chat-v1

We support their prompt, although their model is known to be fussy and issues with getting output.

**Comment by pseudotensor** [comment]
I updated the jais prompt, at least in english 13b works well:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/a9db29b6-34a7-47e8-bcc9-a47019569dcc)


Feel free to experiment with Arabic after changing all those prompts like in Chinese example.

**Comment by pseudotensor** [comment]
I also updated the FAQ with jais for Arabic and which embedding model to use.
