### ISSUE TITLE
Failed to build sentencepiece

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#135]
ERROR: Could not build wheels for sentencepiece, which is required to install pyproject.toml-based projects

https://www.reddit.com/r/LocalLLaMA/comments/13iy44r/privategpt_like_langchain_in_h2ogpt/jkdq0v2/?%2524deep_link=true&onboarding_redirect=%2Fr%2FLocalLLaMA%2Fcomments%2F13iy44r%2Fcomment%2Fjkdq0v2%2F%3F%2524deep_link%3Dtrue%26correlation_id%3D2908cc38-abd7-4ae6-972c-c648f8fbddef%26ref%3Demail_post_reply%26ref_campaign%3Demail_post_reply%26ref_source%3Demail%26%25243p%3De_as%26_branch_match_id%3D1169851963107380735%26utm_medium%3DEmail%2BAmazon%2BSES%26_branch_referrer%3DH4sIAAAAAAAAA3VO226DMAz9GvYGdElE6aRqmlT1iX5D5CYGMkKSmVDUv5%252FRtsdJtnV0Ljoec07LW10TWutyBSlV3oWplum9EEqmM2pYXhhGcoML4PVK%252FjzuqUJ%252BFOLKs21b9Zs3cWaCeLtowHcd3HYT0zOGvDB8le6p1O5I5B6QcUhZezeh9hAGM4ILmmcUkQV2fU726%252FAQe5PkMmURk95fLOQl04qFaEwkQg%252FZRY5a5sXp0Boj2xLu9lgqwKY8HYUpTaPavu3v1mLPOeIrLziD8zrFJWvC5J8%252FgjYwJ3BD%252BN%252BxxJUM%252FunfOUyn5kkBAAA%253D&%25243p=e_as&_branch_match_id=1169851963107380735&newUser=true&correlation_id=2908cc38-abd7-4ae6-972c-c648f8fbddef&_branch_referrer=H4sIAAAAAAAAA3VO226DMAz9GvYGdElE6aRqmlT1iX5D5CYGMkKSmVDUv5%2FRtsdJtnV0Ljoec07LW10TWutyBSlV3oWplum9EEqmM2pYXhhGcoML4PVK%2FjzuqUJ%2BFOLKs21b9Zs3cWaCeLtowHcd3HYT0zOGvDB8le6p1O5I5B6QcUhZezeh9hAGM4ILmmcUkQV2fU726%2FAQe5PkMmURk95fLOQl04qFaEwkQg%2FZRY5a5sXp0Boj2xLu9lgqwKY8HYUpTaPavu3v1mLPOeIrLziD8zrFJWvC5J8%2FgjYwJ3BD%2BN%2BxxJUM%2FunfOUyn5kkBAAA%3D

**Comment by Inquisitor228rus** [comment]
I tried to change the version in the dependencies to sentencepiece-0.1.98 and everything was successfully installed

**Comment by pseudotensor** [comment]
Yes, I've seen no issues in mac, windows, or linux with current dependencies.
