### ISSUE TITLE
Chat with "private" collection via API.

### ISSUE THREAD

**Issue by ChiNoel-osu** [h2oai/h2ogpt#1354]
How can I chat with "private" collections (Like in UI you need to login to see such collection) via API call? I looked around and saw something about using `UserData`. But the thing is I have multiple collections in h2oGPT and in my application I want user to be able to select one and chat with that collection.
Also I can't find where I can pass the argument such as `prompt_query` and `system_prompt` in API, it would be great if anyone could point that out to me.

I appreciate your help!

**Comment by pseudotensor** [comment]
Unless one logs in, no way to match client with server for specific non-shared collections.

I think gradio 4 allows auth based API access, so if auth were enabled on server one could still use API access for a specific user, but I'm not sure.

Once gradio > 4.16.0 is out (need bugs fixed) I'll see if I can have user send user/pass via API to access their collections and/or use auth way.

**Comment by pseudotensor** [comment]
This is solved with gradio 4 upgrade, I added docs in FAQ.
