### ISSUE TITLE
How come no 4bit?

### ISSUE THREAD

**Issue by bbecausereasonss** [h2oai/h2ogpt#136]
Curious why no 4bit models. Would really amplify the ability to use larger models.

**Comment by arnocandel** [comment]
https://github.com/h2oai/h2ogpt/pull/107 we are working on 4-bit quantization

**Comment by chris-aeviator** [comment]
is 4 bit usable with the latest merge?

**Comment by pseudotensor** [comment]
@chris-aeviator , for GPU models on newer GPUs, the latest bitsandbytes supports 4-bit yes.

See the middle part of readme.md for GPU section: https://github.com/h2oai/h2ogpt#gpu-cuda

**Comment by pseudotensor** [comment]
bitsbytes supplorts
