### ISSUE TITLE
Not able to use OpenAI embedding

### ISSUE THREAD

**Issue by davide445** [h2oai/h2ogpt#1361]
Due performing RAG on non-English documents and emails, and needing an answer in a non-English language, I tried loading using this:

OPENAI_API_KEY=xxxx python3 ./generate.py --base-model=TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF --use_safetensors=True --prompt_type=mistral --use_openai_embedding=True --llamacpp_dict="{'n_gpu_layers':15}" --save_dir='/workspace/save/' --use_gpu_id=False --score_model=None --max_max_new_tokens=2048 --max_new_tokens=1024

I got his message

OpenAI API URL: http://0.0.0.0:5000
INFO:__name__:OpenAI API URL: http://0.0.0.0:5000
OpenAI API key: EMPTY
INFO:__name__:OpenAI API key: EMPTY

I tried using also export OPENAI_API_KEY=xxxx and using echo $OPENAI_API_KEY provide the correct value.

Testing the model seems is not using OpenAI embedding.

**Comment by pseudotensor** [comment]
You had some typos, e.g. `--base_model` vs. `--base-model`  and `--prompt_type=mixtral` vs. `--prompt_type=mistral`.  FYI `--use_gpu_id=False` has no effect for GGUF, llama.cpp always uses all visible GPUs.

For the embedding, maybe you have an existing UserData with older embedding, then need to do:
```
mv db_dir_UserData db_dir_UserData_other
```

Then run:
```
OPENAI_API_KEY=xxxx python generate.py --base_model=TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF --use_safetensors=True --prompt_type=mixtral --use_openai_embedding=True --llamacpp_dict="{'n_gpu_layers':15}" --save_dir='/workspace/save/' --use_gpu_id=False --score_model=None --max_max_new_tokens=2048 --max_new_tokens=1024
```

h2oGPT doesn't migrate database if switch embeddings, just keeps original.   You can still use the old database by adding it as new name as shared collection in UI or on command line.

With this, it does actually use OpenAI, but doesn't show that fact in the UI or saved in embed_info file in the database directory.  I pushed fix for that, so you should see:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/bbef82f8-cf7b-45ee-a359-f65f88975363)
