### ISSUE TITLE
Is it possible to solve the problem of why there is no response in Arabic?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1363]
<img width="960" alt="Screenshot 2024-02-05 160435" src="https://github.com/h2oai/h2ogpt/assets/85692636/71e73fc1-9055-4df3-a928-57db8d554939">
Is it possible to solve the problem of why there is no response in Arabic?

**Comment by pseudotensor** [comment]
I gave you an example where Arabic was working perfectly with a specific model and adding that to the FAQ.  You've not given any details like your run line and your model name is just some path I can't recognize.

**Comment by odai1001** [comment]
i had convert the arabic Jais model to safetensor format and i have it locally, so i want to run this converted models from my computer like the picture above. Do you think it doesnt work with safetensor format?

**Comment by pseudotensor** [comment]
I'm not sure, what is your exact run line and how did you download the model and place it into the folder?

E.g. did you add `--prompt_type=jais` ?  Since h2oGPT doesn't have the normal name, you need to tell it the prompt_type.
