### ISSUE TITLE
Is it possible to solve the problem of why there is no response in Arabic on ubuntu?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1364]
Is it possible to solve the problem of why there is no response in Arabic on ubuntu?

**Comment by odai1001** [comment]
![Uploading Screenshot 2024-02-05 160435.png…]()

**Comment by pseudotensor** [comment]
Hi, you keep adding to github without letting it wait for images to finish.  I'll close for now since I can't see anything.
