### ISSUE TITLE
Is it possible to solve the problem of why there is no response in Arabic on ubuntu?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1365]
![Uploading Screenshot 2024-02-05 160435.png…]()

**Comment by pseudotensor** [comment]
Hi, you keep adding to github without letting it wait for images to finish.  I'll close for now since I can't see anything.

**Comment by odai1001** [comment]
<img width="960" alt="Screenshot 2024-02-05 160435" src="https://github.com/h2oai/h2ogpt/assets/85692636/962da273-7419-4374-8b17-1a4058e875e6">

**Comment by pseudotensor** [comment]
Ok, I responded to this in separate issue.  You need to provide run command, and compare with jais that I shared full details for Arabic example.

**Comment by odai1001** [comment]
Thank you very much you are a great person
