### ISSUE TITLE
How to make a chat-only interface without options or buttons on h2ogpt?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1370]
<img width="702" alt="555555555555555555555555555" src="https://github.com/h2oai/h2ogpt/assets/85692636/4f20abf1-7ace-44c5-91e5-ab48e13887ff">

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/blob/main/docs/README_ui.md#sidebar-submit-buttons-and-tab-control
