### ISSUE TITLE
--temperature and --top_p ignored when using inference server

### ISSUE THREAD

**Issue by wypiki** [h2oai/h2ogpt#1372]
Temperature is always 0 and top_p is always 1. Where can that be changed?
I'm successfully using KoboldCPP as an inference server.

**Comment by pseudotensor** [comment]
Please set do_sample to True first.  Sampling doesn't occur otherwise.  It's described in the UI and FAQ and is normal for HF transformers inference, so we go by that.   If you still have issues let me know, but will close for now.

**Comment by wypiki** [comment]
Thank you, that solved it. Interestingly, I get much more factual results with temp=0.1 and top_p=0.3.

**Comment by pseudotensor** [comment]
@wypiki It might be just anecdotal, it's easy to be persuaded by sampling a few cases after you switched.
