### ISSUE TITLE
How do I make h2ogpt fast in responding? Do the device’s resources have anything to do with the slowness of the response?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1375]
How do I make h2ogpt fast in responding? Do the device’s resources have anything to do with the slowness of the response?

**Comment by pseudotensor** [comment]
Use GGUF models and have a GPU.

**Comment by odai1001** [comment]
How could i convert the models, which in bin format, to gguf format؟

**Comment by pseudotensor** [comment]
You should just download GGUF files from TheBloke at HF portal, e.g. https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF

**Comment by odai1001** [comment]
> يجب عليك فقط تنزيل ملفات GGUF من TheBloke على بوابة HF، على سبيل المثال https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF

Is there an Arabic model in GGUF format?

**Comment by pseudotensor** [comment]
jais is native arabic model, but you might get ok results using zephyr if you use the CLI options I shared for jais.  Just change the --base_model to https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF

**Comment by odai1001** [comment]
> jais هو نموذج عربي أصلي، ولكن قد تحصل على نتائج جيدة باستخدام zephyr إذا كنت تستخدم خيارات CLI التي شاركتها مع jais. ما عليك سوى تغيير --base_model إلى https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF

This is an Arabic model. Can you take a picture while you are using it?🙏

**Comment by pseudotensor** [comment]
Ok nevermind, zephyr doesn't do good with arabic.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/f6ebe945-e161-4413-8d19-65a8cb255e3d)


So please share your run command, document, and question, and I can see if we can improve stopping behavior with jais.
