### ISSUE TITLE
How can I display the h2ogpt interface, the same interface shown in the picture?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1378]
<img width="532" alt="3333333333333333374008" src="https://github.com/h2oai/h2ogpt/assets/85692636/c5e55810-9ec6-43a5-b8ba-9a59faa4eca2">

**Comment by pseudotensor** [comment]
You can toggle the various --visible- options on CLI, but this above is older version that is more normal gradio style we don't have anymore.

**Comment by odai1001** [comment]
Can I return the right to write the question at the bottom of the interface?

**Comment by odai1001** [comment]
When modifying a visual, just running the program again, is the optimization cancelled?

**Comment by odai1001** [comment]
> You can toggle the various --visible- options on CLI, but this above is older version that is more normal gradio style we don't have anymore.
When modifying a visual, just running the program again, is the optimization cancelled?

**Comment by pseudotensor** [comment]
I added CLI option --visible_ask_anything_high in PR, will be merged soon.

**Comment by odai1001** [comment]
We ask you to make the interface professional and hide the appearance of the model name in the interface... Thank you

**Comment by pseudotensor** [comment]
Already can with `--visible_chatbot_label=False`
