### ISSUE TITLE
Is there a way to build an Arabic and English NLP model?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1381]

**Comment by pseudotensor** [comment]
The jais models I shared instructions for are LLMs for that.  What do you mean by NLP model, the embedding model?

**Comment by odai1001** [comment]
I want to build a model of the same model as the llama.... Can I and what is the plan?

**Comment by pseudotensor** [comment]
You can ask in H2O LLM Studio, h2oGPT github project isn't focused on fine-tuning.
