### ISSUE TITLE
How are models linked?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1382]
How are models linked?

**Comment by pseudotensor** [comment]
I don't know what that means.

**Comment by odai1001** [comment]
How to add more than one model in h2ogpt?

**Comment by pseudotensor** [comment]
See "model_lock" in docs, e.g. https://github.com/h2oai/h2ogpt/blob/main/docs/README_InferenceServers.md#locking-models-for-easy-start-up-or-in-app-comparison
