### ISSUE TITLE
AVG flags installer as EvoGen malware

### ISSUE THREAD

**Issue by Sierbahnn** [h2oai/h2ogpt#1388]
![image](https://github.com/h2oai/h2ogpt/assets/68108749/43409600-cb1e-4793-915e-66f10918ff93)

I was surprised, but this apparently happens from time to time.
https://www.gsmarena.com/no_our_android_app_doesnt_contain_a_virus-news-52893.php
Honestly not sure what you could possibly do about it, but I thought I should let you know anyway.

**Comment by pseudotensor** [comment]
Yes, it's come up before, I'm not quite sure what to do about it.  It's a false positive.

I think in some cases one can add a signed credential to bias the virus scanners, but I haven't looked into it.
