### ISSUE TITLE
How do I make h2ogpt follow a link and answer based on the content or the specific question, the answer, and the information specified in the signed link without increasing or decreasing?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1389]

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/blob/8cf991f99d53054fc19a3ecfcf9fabb9fd9e485a/docs/README_SerpAPI.md?plain=1

Once you have that setup, the 
![image](https://github.com/h2oai/h2ogpt/assets/2249614/4542ea7c-e606-47d8-9e86-e4cab8fd2109)


will appear.

Also, under agents a "search" agent will appear.
