### ISSUE TITLE
How to use Model: gpt-3.5-turbo-0613 in my local h2ogpt?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1390]
<img width="960" alt="Screenshot 2024-02-09 174520" src="https://github.com/h2oai/h2ogpt/assets/85692636/f013f3cb-161d-40e9-b655-4891aab2ecb3">

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/blob/main/docs/README_InferenceServers.md#openai-inference-server-client

The same parameters can be added to a model_lock line as separate model that's an inference_server case.
