### ISSUE TITLE
Can you explain this addition in the new version... How is it used Vision Models?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1391]
<img width="960" alt="Screenshot 2024-02-09 180805" src="https://github.com/h2oai/h2ogpt/assets/85692636/5329b954-9478-4ba8-9192-ea64417dc5cd">

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#llava-vision-models
