### ISSUE TITLE
Can i connect h2ogpt own my own Database

### ISSUE THREAD

**Issue by ibraheem-abusnineh** [h2oai/h2ogpt#1394]
i have a data in my database and want to use it on h2ogpt can i do it and how

**Comment by pseudotensor** [comment]
If you have a data database, you should dump out all data to disk in some raw form, then make a new h2oGPT chroma vector database using make_db.py.

https://github.com/h2oai/h2ogpt/blob/main/docs/README_LangChain.md#database-creation
