### ISSUE TITLE
unable to add document to collection to chat

### ISSUE THREAD

**Issue by sameermahajan** [h2oai/h2ogpt#1399]
https://docs.h2o.ai/h2ogpte-docs/guide/collections/add-documents-to-a-collection states to click on "Add documents" however I do not see this button in the UI.

I copied my document to the Directory of my collection and clicked on "Update DB with new/changed files on disk" as well as "Synchronize DB and UI" but it still shows 0 documents in my collection.

Any ideas?

**Comment by pseudotensor** [comment]
Hi, you are looking at the Enterprise h2oGPT docs.

These are closer: https://github.com/h2oai/h2ogpt/blob/main/docs/README_ui.md

But still a bit out of date.

The main UI should explain:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/d86749ef-5447-47e3-9c3a-6b30d98a3fa9)


i.e. put text, url, youtube, arxiv into the "ask or ingest" and click "Ingest" to add that to db.
or click "Upload" to add files of any kind.

**Comment by sameermahajan** [comment]
what worked for me is to manually run python src/make_db.py --add_if_exists=True --user_path=... with my data in user_path. Though it got added to UserData collection...

**Comment by pseudotensor** [comment]
Yes, that builds shared collections.
