### ISSUE TITLE
How to deploy vicuna-13b with h2gpt ? 

### ISSUE THREAD

**Issue by qmzpg** [h2oai/h2ogpt#141]
I see the readme.md says "Variety of models (h2oGPT, WizardLM, Vicuna, OpenAssistant, etc.) supported". so How to deploy vicuna-13b with h2gpt ?

**Comment by pseudotensor** [comment]
These are the vicuna that work OOTB:

https://github.com/h2oai/h2ogpt/blob/main/prompter.py#L62

But you can always do:
```
python generate.py --base_model=<your vicuna model on HF or in a path> --prompt_type=instruct_vicuna
```

This assumes that the vicuna model was trained with same prompt as other vicuna models.

**Comment by pseudotensor** [comment]
If have you have issues after trying, let us know!
