### ISSUE TITLE
No GPU Detected - AMD GPU Radeon Instinct MI25 MxGPU Discrete

### ISSUE THREAD

**Issue by parag7732** [h2oai/h2ogpt#1413]
Hi I am testing in Azure.

Windows 11 AMD Software: pro edition is able to detect the GPU Radeon Instinct MI25 MxGPU Discrete however h2ogpt is not able to.

I am using windows.

**Comment by pseudotensor** [comment]
Hi, you'll need to pip install the specific package that fits your system best from here:

https://github.com/h2oai/h2ogpt/blob/bbadfe875c957aa43e840f778faf5a2cff20844f/reqs_optional/requirements_optional_gpt4all.txt

If you are using one-click installer, it would be same as how torch for cuda is pip installed in main README.md in windows section.
