### ISSUE TITLE
Reading documents content: File not allowed

### ISSUE THREAD

**Issue by mgaionWalit** [h2oai/h2ogpt#1414]
Hello team

i just updated the h2ogpt on revision 0b05d4d1bed5539668e8801cf31728cb3ac147d5 (i had a really old version from sept 2023, before update) and i encounter a problem once i click on the documents details on the "source" response or on the "document selection" tab, that the app isnt able to show me the contents.

To be precise i get this error:
`{"detail":"File not allowed: documents/XXXX.pdf."}`

I'm running the app with this parameters:
`OPENAI_API_KEY=:-* python generate.py --inference_server="openai_chat" --base_model=gpt-4 --use_openai_embedding=True --h2ocolors=False --langchain_mode=UserData --langchain_mode='UserData' --user_path=documents --hf_embedding_model="hkunlp/instructor-large" --save_dir="logs"`

There is my enviroment:
Ubuntu 22.04
python 3.10
NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0   

I solved it adding the parameter "allowed_paths" on the gradio launcher like this: 
```
demo.launch(share=kwargs['share'],
                allowed_paths=['documents'],
```
in the file:
`src/gradio_runner.py`

i've done it correctly? maybe there is a starting parameter or a better way to do it?

Thanks.

**Comment by pseudotensor** [comment]
Can you reproduce on gpt.h2o.ai?

I am able to ask a question about a PDF, see sources, then click on the pdf link, and then it downloads that pdf as expected.

To view the pdf directly in the app you need to use the "Document Viewer" page.

Did you reinstall all dependencies as in README_linux.md?  Since back then, there's simple script to use.

**Comment by mgaionWalit** [comment]
First thanks for you fast reply:

> Can you reproduce on gpt.h2o.ai?
> I am able to ask a question about a PDF, see sources, then click on the pdf link, and then it downloads that pdf as expected.
> To view the pdf directly in the app you need to use the "Document Viewer" page.

i just tried on gpt.h2o.ai and i see a difference:
on h2ogpt i get the url like:
https://gpt.h2o.ai/file//ephemeral/gradio/....
on my installation i gthe url like:
https://localhost:7860/file/documents/foo.pdf

in the fact if i put a single `/` on h2ogpt i get the same error as in my localhost,
but if i put the double slash (`//`) on my localhost i get anyway the same error.

I will try to delete the DB and upload all the files again, maybe is something connected to this (i simply updated the code but i kept the same DB).

> Did you reinstall all dependencies as in README_linux.md? Since back then, there's simple script to use.

yes, i readed the docs and i used the docs/linux_install.sh and updated (i think) everything. 
Maybe i've done something uncorrect during the update, or maybe is the DB problem:
monday i will make a try starting from scratch and update this issue with news.

Thanks again and have a good weekend.

**Comment by pseudotensor** [comment]
If I run h2oGPT locally, I see links like:
```
http://0.0.0.0:7860/file//tmp/gradio/b852e91aec6aa0a62934ba33f2217f1a9b50169b/2402.01032.pdf
```
or
```
http://0.0.0.0:7860/file//tmp/gradio/ee06795f09742b34a9c12e51f42fdc699a4a196f/2015_Felix%201.pdf
```

chrome complains that those are insecure downloads and asks me to click to keep, else is fine.


If I go to localhost:7860 and use h2oGPT, I see:
```
http://localhost:7860/file//tmp/gradio/fc0da5441121b26fdafd06ea9c14b3d31a24b030/2401.03462%202.pdf
```
and still downloads.

**Comment by StefanDanielSchwarz** [comment]
Having the same issue here: When clicking a file link on the Document Selection page, I get a JSON viewer with error message "File not allowed".

I'm using the current docker image gcr.io/vorvan/h2oai/h2ogpt-runtime@sha256:3234fe093a97fe625bd54c842222c65105cef71ef1ef6b4a4e88dab265f2e767.

**Comment by pseudotensor** [comment]
I only so far see this when the /tmp/gradio location is some kind of link and not a real physical directory.  E.g. in linux, if /tmp/gradio is a soft link to /ephemeral/gradio then gradio won't allow /tmp/gradio access.

**Comment by pseudotensor** [comment]
I suspect it's something to do with firewall

Probably dev console would help in chrome, maybe shows errors there.

Probably basic gradio demo would have same issues.

**Comment by jarulsamy** [comment]
I am running into the same issue, adding the document folder to `allowed_paths` also fixes it for me. Perhaps adding the value of `--user_path` to `allowed_paths` automatically would solve this?

**Comment by pseudotensor** [comment]
Even an absolute path works for me:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/5b7b5371-a738-4168-b33a-66bdf9820209)

**Comment by pseudotensor** [comment]
But yes clicking on source fails:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/2b2c6021-2483-4632-bdbb-353e13f27787)
