### ISSUE TITLE
Why does it take time to load the form?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1415]
No GPUs detected
soundfile, librosa, and wavio not installed, disabling STT
soundfile, librosa, and wavio not installed, disabling TTS
Using Model core42/jais-13b-chat
fatal: not a git repository (or any of the parent directories): .git
Must install DocTR and LangChain installed if enabled DocTR, disabling
Starting get_model: core42/jais-13b-chat 
Downloading shards:   0%|                                                                                                                                             | 0/6 [00:00<?, ?it/s]/home/odai/miniconda3/lib/python3.11/site-packages/huggingface_hub/file_download.py:450: UserWarning: 'hf_transfer' does not support `resume_size`: falling back to regular download method
  warnings.warn("'hf_transfer' does not support `resume_size`: falling back to regular download method")

pytorch_model-00001-of-00006.bin:  63%|██████████████████████████████████████████████████████████████████████▍                                         | 6.28G/9.99G [00:36<24:56, 2.48MB/s]

**Comment by pseudotensor** [comment]
The model core42/jais-13b-chat is being downloaded

**Comment by odai1001** [comment]
Why does it take more than two hours to download the form?

**Comment by odai1001** [comment]
Why is the form not downloaded without the Internet?offline

**Comment by pseudotensor** [comment]
Models are only downloaded from online sites.
