### ISSUE TITLE
Why does it take time to load the form?

### ISSUE THREAD

**Issue by odai1001** [h2oai/h2ogpt#1416]
(base) odai@odai-HP-ZBook-14u-G5:~/h2ogpt-main$ python generate.py --base_model=core42/jais-13b-chat
No GPUs detected
soundfile, librosa, and wavio not installed, disabling STT
soundfile, librosa, and wavio not installed, disabling TTS
Using Model core42/jais-13b-chat
fatal: not a git repository (or any of the parent directories): .git
Must install DocTR and LangChain installed if enabled DocTR, disabling
Starting get_model: core42/jais-13b-chat 
Downloading shards:   0%|                                                                                                                                             | 0/6 [00:00<?, ?it/s]/home/odai/miniconda3/lib/python3.11/site-packages/huggingface_hub/file_download.py:450: UserWarning: 'hf_transfer' does not support `resume_size`: falling back to regular download method
  warnings.warn("'hf_transfer' does not support `resume_size`: falling back to regular download method")

pytorch_model-00001-of-00006.bin:  66%|█████████████████████████████████████████████████████████████████████████▉                                      | 6.60G/9.99G [02:56<26:07, 2.17MB/s]

**Comment by pseudotensor** [comment]
dup
