### ISSUE TITLE
Enable Vision Models window in the UI via docker

### ISSUE THREAD

**Issue by vitalyshalumov** [h2oai/h2ogpt#1420]
Please provide guidelines for enabling Vision Models window in the UI for image upload.

**Comment by pseudotensor** [comment]
The FAQ for launching llava and arguments for h2ogpt are the same.

https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#llava-vision-models

Docker arguments are nothing special, but one should ensure to pass through ports gradio llava uses, e.g. 7861 in the above FAQ example.  Options like `--llava_model` need to be passed along.

**Comment by pseudotensor** [comment]
Did you try the 2 things I mentioned?  llava stuff is unrelated to TGI.

**Comment by vitalyshalumov** [comment]
I'm trying to use TGI for llava inference, as I would for any other model. Besides the --llava_model option, how is this different from LLM usecases?

**Comment by pseudotensor** [comment]
I don't think TGI, vLLM, etc. support llava.  I know ollama does, which maybe better esp for smaller systems.
