### ISSUE TITLE
How to connect to vLLM endpoint using HTTPS (SSL/TLS)

### ISSUE THREAD

**Issue by StefanDanielSchwarz** [h2oai/h2ogpt#1421]
I've enabled SSL/TLS for my vLLM endpoint for improved security. Now how can I make h2oGPT connect properly?

`--inference_server=vllm_chat:https://host.docker.internal:5000` isn't working and when I do the normal `--inference_server=vllm_chat:host.docker.internal:5000`, it's not connecting, either. What's the proper syntax to use a HTTPS backend?

**Comment by StefanDanielSchwarz** [comment]
Just after posting this, found this essential note on https://github.com/h2oai/h2ogpt/blob/main/docs/README_InferenceServers.md:

> If add `https://` or `http://` as prefix to IP address for vLLM, then also need to add rest of full address with `/v1` at end

Added that and now I'm one step further. However, since I'm accessing it through the docker host, the certificate doesn't fit. I have `--ssl_verify=False`, but looks like it doesn't apply here?

Changing the hostname to the one in the certificate doesn't help as the docker host resolves that to 127.0.1.1, which in the h2oGPT container is itself, not the vLLM container. Quite complicated unfortunately if you strive for security.

**Comment by StefanDanielSchwarz** [comment]
After setting up a different hostname (with valid certificate) and pointing DNS at this one, I now get through to the vLLM instance. Final (hopefully!) problem is now this:

`openai.AuthenticationError: Error code: 401 - {'detail': 'Invalid API Key'}`

I've tried all of the following:

Envvars:
```
API_KEY=sk-example
H2OGPT_KEY=sk-example
H2OGPT_OPENAI_API_KEY=sk-example
OPENAI_API_KEY=sk-example
```
CLI args:
```
  --api_key=sk-example
  --h2ogpt_api_keys=\"['sk-example']\"
  --h2ogpt_key=sk-example
```
How do I tell h2oGPT which key to use to auth with vLLM? (The key itself is correct.)

**Comment by pseudotensor** [comment]
In recent h2oGPT, one would add the key to the model inference itself.  e.g.

```
vllm:<url>:None:/<page>/v1:<key>
```

e.g.
```
vllm:https://model.h2o.ai/:None:/0b1219f7-4bb4-43e9-801e-ea8fa9fe6e04/v1:123ABCD
```

This is explained in the gen.py file doc string when discussing inference_server.

**Comment by StefanDanielSchwarz** [comment]
Oh wow, I'd never have guessed that, and searching for "key" and such in the repo didn't find this for some reason. So thanks a lot for pointing this out, now it's working.

One option that would be really useful would be a way to set "ssl_verify=False" for those requests. In my case, I don't need TLS since the connection is between containers on the same host, but the endpoint is also accessible over the network so I want TLS there, and I can only have that port either with or without TLS.

Also a suggestion: Wouldn't a better prefix than vllm be more appropriate since it's not necessarily vLLM this type of connection uses, but in general an OpenAI-compatible API. I'm also using vllm_chat with ollama, for instance, and that has nothing to do with vLLM anymore.

**Comment by StefanDanielSchwarz** [comment]
So if I use ollama – which isn't vLLM but not fully OpenAI-compatible, either – would you recommend the vllm endpoint or setting OPENAI_BASE_URL to use the OpenAI-like connection?

**Comment by pseudotensor** [comment]
I recommend vLLM probably, and only using openai/openai_chat for real OpenAI model.

I did relax the checks for openai and openai_chat to only warn if something seems off, so it might still work fine.  But it's not tested.

**Comment by StefanDanielSchwarz** [comment]
OK. Thank you for the help, I appreciate it! I'll close this issue as it's working for me now.
