### ISSUE TITLE
how can use type gemma model of google in h2ogpt?

### ISSUE THREAD

**Issue by linhcentrio** [h2oai/h2ogpt#1427]
how can use type gemma model of google in h2ogpt?

**Comment by pseudotensor** [comment]
`python generate.py --base_model=google/gemma-7b-it`

**Comment by linhcentrio** [comment]
is this really ready run offline or through by HF?

**Comment by pseudotensor** [comment]
It can run offline once downloaded and follow normal offline procedures.
