### ISSUE TITLE
AttributeError: module 'psutil' has no attribute 'RLIMIT_AS'

### ISSUE THREAD

**Issue by linhcentrio** [h2oai/h2ogpt#1430]
after git pull latest i got this error:
(C:\Users\Admin\Downloads\h2ogpt-main\venv) C:\Users\Admin\Downloads\h2ogpt-main>python generate.py --share=False --gradio_offline_level=1 --base_model=google/gemma-7b-it --max_seq_len=4096 --load_4bit=True --score_model=None
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\h2ogpt-main\generate.py", line 11, in <module>
    from src.gen import main
  File "C:\Users\Admin\Downloads\h2ogpt-main\src\gen.py", line 22, in <module>
    from src.image_utils import get_image_file
  File "C:\Users\Admin\Downloads\h2ogpt-main\src\image_utils.py", line 6, in <module>
    from src.utils import have_cv2, have_pillow
  File "C:\Users\Admin\Downloads\h2ogpt-main\src\utils.py", line 40, in <module>
    from src.utils_procs import reulimit
  File "C:\Users\Admin\Downloads\h2ogpt-main\src\utils_procs.py", line 7, in <module>
    psutil.RLIMIT_AS, psutil.RLIMIT_CORE, psutil.RLIMIT_CPU, psutil.RLIMIT_DATA,
AttributeError: module 'psutil' has no attribute 'RLIMIT_AS'

`(C:\Users\Admin\Downloads\h2ogpt-main\venv) C:\Users\Admin\Downloads\h2ogpt-main>pip show psutil
Name: psutil
Version: 5.9.8
Summary: Cross-platform lib for process and system monitoring in Python.
Home-page: https://github.com/giampaolo/psutil
Author: Giampaolo Rodola
Author-email: g.rodola@gmail.com
License: BSD-3-Clause
Location: c:\users\admin\downloads\h2ogpt-main\venv\lib\site-packages
Requires:
Required-by: accelerate, fiftyone, neptune, peft, py7zr, trainer`

**Comment by pseudotensor** [comment]
Hi, sorry about that, can you try pulling again?  I lost my windows machine and have to reinstall windows to check, faster if you checked.

**Comment by linhcentrio** [comment]
yeah, i try again a it good well amazing work! thank you very much!
