### ISSUE TITLE
Why does the local UI have trackers?

### ISSUE THREAD

**Issue by TonyWeimmer40** [h2oai/h2ogpt#1431]
The private local host UI has this tracker: http://cdn.heapanalytics.com/
Why does an application made for privacy have a tracker. I do not understand?

From Heap's front page: "Heap is the only digital insights platform that gives you complete understanding of your customers’ digital journeys, so you can quickly improve conversion, retention, and customer delight."

**Comment by pseudotensor** [comment]
Many of the packages we use have telemetry.  See this to fully disable: 

https://github.com/h2oai/h2ogpt/blob/main/docs/README_offline.md#to-fully-disable-chroma-telemetry-which-documented-options-still-do-not-disable-run
