### ISSUE TITLE
Why does the local UI have trackers?

### ISSUE THREAD

**Issue by oldmanjk** [h2oai/h2ogpt#1437]
https://github.com/h2oai/h2ogpt/issues/1431#issue-2153002144
This question is too important to cover up

**Comment by pseudotensor** [comment]
If you are offline, then nothing is tracked (by definition).  If you follow the offline docs, then you can disable any telemetry I'm aware of.

If you are online, there are many packages with telemetry.  I'm not sure we remove all trackers, sometimes it's hard.  We make it extremely easy to avoid our own telemetry.

What has telemetry:
* Chroma via posthog
* HF for anything model downloaded
* h2oGPT for which UI elements are clicked.  No data is send, just the button clicked.  Primarily just used to see if anyone 

As is usual for any telemetry, it is used to see what parts of the product are used.  E.g. if chat tab was never used, we'd remove it.

It's very easy to change.  What about the opt-out instructions is not understood?  It's just:

```
H2OGPT_ENABLE_HEAP_ANALYTICS=False python generate.py ...
```
or
```
python generate.py --enable-heap-analytics=False ...
```

**Comment by pseudotensor** [comment]
Related, tools like llama index used by privateGPT also have posthog with telemetry that are hard to remove.  I give an example of how to really remove, as the suggestion for posthog removal by llama index or chroma actually don't work.

**Comment by pseudotensor** [comment]
That was my preference, but the rest of the company did not like that.  @mmalohlava can chime in if he wants.

**Comment by pseudotensor** [comment]
I think you'll find it an intense discussion for opt-in vs. opt-out, just one random googled example that sides on opt-in after being opt-out for a while: https://blog.notesnook.com/telemetry-opt-in-vs-opt-out/

**Comment by pseudotensor** [comment]
I don't think there exists any solution that doesn't have some telemetry from some packages that require either simple or complex opt-outs.  None are opt-in.

**Comment by pseudotensor** [comment]
Your title was vague and mine is specific to the exact thing.  The UI does not have a tracker, that is not correct description.

**Comment by pseudotensor** [comment]
> It's obviously the correct decision from an ethical and moral standpoint and I appreciate you sharing that view. From a business perspective, it looks shady. Just because everyone else is doing it doesn't make it right. I understand your points and therefore I think a reasonable compromise would be to include an opt-out option in the UI. The instructions are definitely confusing me at least. I'll explain why: "run:"
> 
> ```
> sp=`python -c 'import site; print(site.getsitepackages()[0])'`
> sed -i 's/posthog\.capture/return\n            posthog.capture/' $sp/chromadb/telemetry/posthog.py
> ```
> 
> throws an error on windows. "or the equivalent for windows/mac using." is not helpful. I (and I assume many others) don't know what "sp" even is, let alone the windows equivalent. I gave up there because you're already asking far too much from the user to opt-out and I'm already thinking about moving on considering my experience with other instructions for this project. "Or edit the file manually to just return in the capture function." Edit what file? What do you mean, "return in the capture function?" Again, all I'm trying to do is opt out of something that should have been opt in in the first place. At the very least, give me a button to click. "set the ENV H2OGPT_ENABLE_HEAP_ANALYTICS=False pass --enable-heap-analytics=False to generate.py" "set the ENV" is going to confuse a lot of users. Do you mean add that line to path? What does "pass" mean? Do you mean use that line as an argument to generate.py? How do I run generate.py? (I know how, but this probably isn't obvious to many users). Why am I running generate.py anyway? I did this and it appears to run some process but I don't know what's going on. This might all seem very obvious to you, but I promise you, this will confuse many users. A lot of the other instructions are similarly unclear and frustrating. Many people probably give up and move on. You guys are just lucky I'm willing to take the time to try and figure these things out and ask questions. Most probably aren't. This is just a classic case of why coders need someone inbetween them and the users to interpret. You're speaking a completely different language and you don't realize it. Again, at the very least, put an option in the UI.

With gradio this can't be an option in the UI, and there's no need if one can change options.  If you are using the one-click installer, then we explain in the readme.md in that section how one can change the options.
