### ISSUE TITLE
How do I access administrative controls if I set those tabs to visible=false? 

### ISSUE THREAD

**Issue by Biggetit** [h2oai/h2ogpt#1441]
I want to provide a UI for testing that is just chat, no access to other tabs such as models, expert, etc.  But then I don't have access to those tabs as an admin.  Is there a way to run more than one gradio server on different ports with different configs?

**Comment by pseudotensor** [comment]
One can have multiple gradio servers talk to some other gradio server that hosts the actual model or talks to vllm/tgi etc.  That's the gradio inference server case in the readme_inferenceservers.md.

But then still all other operations like parsing and embedding would be on both main gradio servers.  However, if you used TEI server as in FAQ.md, that at least is offloaded to that inference server for both main gradio servers.

It's not yet possible to only have thin UI layer that does nothing except handle chats and no documents.

**Comment by pseudotensor** [comment]
See 2nd bullet for example of how to setup gradio to gradio to get this working

https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#running-ollama-vs-h2ogpt-as-inference-server

More generally:

https://github.com/h2oai/h2ogpt/blob/main/docs/README_InferenceServers.md#gradio-inference-server-client
