### ISSUE TITLE
How to get a less cluttered UI like the one shown on the h2oai website?

### ISSUE THREAD

**Issue by Mayorc1978** [h2oai/h2ogpt#1445]
Instead of the fully cluttered version of the UI, is it possible to have an interface like this?
![image](https://github.com/h2oai/h2ogpt/assets/32271686/23d8356a-58c0-420e-947f-5895bd5e36bf)

**Comment by pseudotensor** [comment]
That's the enterprise h2oGPT UI.

The open-source one can be controlled, as explained here: https://github.com/h2oai/h2ogpt/blob/main/docs/README_ui.md#sidebar-submit-buttons-and-tab-control
