### ISSUE TITLE
Windows CUDA GPU support

### ISSUE THREAD

**Issue by ramz35** [h2oai/h2ogpt#1448]
I followed the instructions but couldn't get the GPU to be recognised....kept getting BLAS=0

I had to compile llama-cpp-python anyway for another environment so I did that for h2ogpt and it worked.

I installed all the requirements
then uninstalled llama-cpp-python
then installed llama-cpp-python forcing a compile for CUDA.

It works but... I still get 
`python generate.py --base_model=llama --model_path_llama=llama-2-7b-chat.Q3_K_S.gguf --prompt_type=zephyr --max_seq_len=4096`

> No GPUs detected

[I then get a ton(!) of langchain messages about deprecation ]

then further down

> ggml_init_cublas: found 1 CUDA devices

> llm_load_tensors: offloading 32 repeating layers to GPU
> llm_load_tensors: offloading non-repeating layers to GPU
> llm_load_tensors: offloaded 33/33 layers to GPU

and 

> AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 | MATMUL_INT8 = 0 

Inference makes the GPU sweat and CPU relax so I know it's using the GPU.

so 2 questions

1) how is the install really supposed to work for Windows CUDA?  I have 12.3 and install instructions reference 12.1 (eg. index and wheels are 121) - does that matter?
2) Why the message no gpus found (or what kind find the gpu) at the beginning when later it (llama-cpp-python?) does find it?

**Comment by pseudotensor** [comment]
1. Yes, the llama_cpp_python wheels are specific.  I would have people always compile that, but that brings extra dependencies.
2. The No GPUs detected means torch had issue with finding GPUs. This won't directly affect llama_cpp_python.  You can just do in your env:

```python
   import torch
   print(torch.cuda.is_available())
```

Should say fails, which is messed up.

**Comment by ramz35** [comment]
It does come back with 

> False

I'm redownloading torch with CUDA support now but while it's doing that (slow) I checked another environment and here torch comes back with 

> True 

(which I kinda knew already because been using torch with CUDA before).  So not sure what happened here.  Hopefully reinstall works and I'll put it down to one of those things.

Any chance for a quick explanation when h2ogpt uses Torch and when llama-cpp-python?

**Comment by ramz35** [comment]
okay did:
1. the reinstall (quick start) this time with the constraints 
2. requirements_optional_gpt4all failed with 

> ERROR: llama_cpp_python_cuda-0.2.26+cu121avx-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.
as expected, so I pip installed llama_cpp_python myself having it compile for my system

3. wouldn't start due to 

> ModuleNotFoundError: No module named 'librosa'
so as reported elsewhere I have to pip install librosa

4. successful start, torch sees GPU and llama_cpp sees GPU

5. inference now has a huge pause (slow, several secs) before streaming out the output.  CPU not used, GPU is....still slow compared to the first environment I cobbled h2ogpt together on (same model, same parameters, same prompts, max 1 sec pause before streaming).  Don't know enough to debug so just leaving my findings here fwiw.

**Comment by pseudotensor** [comment]
If you only do:
```
pip install llama_cpp_python
```
then it won't install the GPU version.

Check this for which env to set: https://github.com/abetlen/llama-cpp-python?tab=readme-ov-file#supported-backends

**Comment by ramz35** [comment]
yes, I took it for granted that I had set the CUBLAS arguments correctly - I should have been more explicit but I think I found the issue.  And I'm kind of glad I had it (and found it) as it brings another question.

so my original cobbled together quickstart h2ogpt install **with fast prompt eval**, visible GPU usage, fast output gave me this:

> Starting get_model: llama
> ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   **yes**   <-----
> ggml_init_cublas: CUDA_USE_TENSOR_CORES: **no**      <-----
> ggml_init_cublas: found 1 CUDA devices:
> 
> llm_load_tensors: using CUDA for GPU acceleration   <-----
> llm_load_tensors: system memory used  =   53.82 MiB
> llm_load_tensors: VRAM used           = 2757.30 MiB   <-----
> llm_load_tensors: offloading 32 repeating layers to GPU
> llm_load_tensors: offloading non-repeating layers to GPU
> llm_load_tensors: offloaded 33/33 layers to GPU
> 
> AVX = 1 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 |
> 

my install with requirement constraints and GPU compiled llama-cpp-python with **slow prompt eval**, but still visible GPU usage and fast output gave me this:

> Starting get_model: llama
> Failed to listen to n_gpus: No module named 'llama_cpp_cuda'  <-----
> ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   **no** <-----
> ggml_init_cublas: CUDA_USE_TENSOR_CORES: **yes** <-----
> ggml_init_cublas: found 1 CUDA devices:
> 
> _<no lines about GPU acceleration, VRAM used, etc>_
> llm_load_tensors: offloading 32 repeating layers to GPU
> llm_load_tensors: offloading non-repeating layers to GPU
> llm_load_tensors: offloaded 33/33 layers to GPU
> 
> _<AVX2=1, FMA=1, F16C=1, SSE3=1 which were not set in the original>_
> AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 | MATMUL_INT8 = 0 |

both models are were using a relatively small GGUF model for ease of experimenting.

I managed to figure out that `requirements_optional_gpt4all.txt` was not being run and that means 
`llama_cpp_python_cuda @ https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.2.26+cu121avx-cp310-cp310-win_amd64.whl` was not installed

It wouldn't run because in the new environment I has python 3.11 (!)
Once I substituted that command for 
`llama_cpp_python_cuda @ https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.2.26+cu121avx-cp31**1**-cp31**1**-win_amd64.whl

it installed and I finally got the output of the original install.  So installing this wheel had some impact which changed the differences of the outputs of generate.py

I admit I'm picking stuff up as I go along but I'd love to know: 

1. either GGML_CUDA_FORCE_MMQ set to yes or CUDA_USE_TENSOR_CORES set to no gives me faster prompt eval.  Which is it and why? 
1.1 what do GGML_CUDA_FORCE_MMQ and CUDA_USE_TENSOR_CORES do? 
1.2 can they both be set to yes?
 
2. Maybe AVX2=1, FMA=1, F16C=1, SSE3=1 is responsible for the slower prompt eval.   

3. because llama-cpp-python-cuda is installed does that mean llama-cpp-python not enough?  what does llama-cpp-python-cuda do?  I don't have it installed in my other llama-cpp-python environments
3.1 I mean I saw llama-cpp-python get compiled with CUDA support and without the llama-cpp-python-cuda wheel I still get BLAS support, and GPU is clearly used.
3.2 how to compile llama-cpp-python-cuda (so I can get my compilation to decide what features my system has) because if I don't specify the wheel pip can't find it

I know it's a lot but partly I'm saving my results so far, partly leaving this searchable for future users, partly asking for info :)

**Comment by pseudotensor** [comment]
Yes, if user has GPUs, we look for `llama_cpp_cuda` as that's the name of the module from jlllll.  But if we don't find, we try the llama_cpp still, because like here they may have installed manually.

It's good question, maybe other options are required for good speed.

This is how jllllll compiles:

https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/blob/89862684fa6d409f54d6e54d0dbd630b3f84f053/.github/workflows/build-wheels-oobabooga.yml#L192

I don't think avx matters, AVX2 is default.

Maybe 0.2.26 vs. latest llama_cpp_python is an issue.  Latest is 0.2.55.

You could try:
```
pip uninstall llama_cpp_python llama_cpp_python_cuda -y
CMAKE_ARGS="-DLLAMA_CUBLAS=on" pip install llama_cpp_python==0.2.26
```
so the same version is used.

**Comment by pseudotensor** [comment]
What I tried:
```
(h2ogpt) jon@pseudotensor:~/h2ogpt$ CMAKE_ARGS="-DLLAMA_CUBLAS=on" pip install llama_cpp_python==0.2.26
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu123, https://huggingface.github.io/autogptq-index/whl/cu123
Collecting llama_cpp_python==0.2.26
  Using cached llama_cpp_python-0.2.26-cp310-cp310-manylinux_2_35_x86_64.whl
Requirement already satisfied: typing-extensions>=4.5.0 in /home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages (from llama_cpp_python==0.2.26) (4.9.0)
Requirement already satisfied: numpy>=1.20.0 in /home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages (from llama_cpp_python==0.2.26) (1.26.4)
Requirement already satisfied: diskcache>=5.6.1 in /home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages (from llama_cpp_python==0.2.26) (5.6.3)
DEPRECATION: textract 1.6.5 has a non-standard dependency specifier extract-msg<=0.29.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of textract or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: llama_cpp_python
```

Then ran:
```
python generate.py --base_model=llama
```
which uses `llama-2-7b-chat.Q6_K.gguf` by default

Then I see only large CPU usage, and slow response like you see.  So something is wrong.

**Comment by ramz35** [comment]
the cached copy maybe CPU only?  when you generate do you get BLAS=1?

**Comment by ramz35** [comment]
> Yes, if user has GPUs, we look for `llama_cpp_cuda` as that's the name of the module from jlllll. But if we don't find, we try the llama_cpp still, because like here they may have installed manually.
> 
> It's good question, maybe other options are required for good speed.
> 
> This is how jllllll compiles:
> 
> https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/blob/89862684fa6d409f54d6e54d0dbd630b3f84f053/.github/workflows/build-wheels-oobabooga.yml#L192
> 
> I don't think avx matters, AVX2 is default.
> 
> Maybe 0.2.26 vs. latest llama_cpp_python is an issue. Latest is 0.2.55.
> 
> You could try:
> 
> ```
> pip uninstall llama_cpp_python llama_cpp_python_cuda -y
> CMAKE_ARGS="-DLLAMA_CUBLAS=on" pip install llama_cpp_python==0.2.26
> ```
> 
> so the same version is used.

**Comment by pseudotensor** [comment]
Yes, their docs aren't great.  I had documented this before, but only in isolated place.  Updated the new docs with this, which works:

```
pip uninstall llama_cpp_python llama_cpp_python_cuda -y
export LLAMA_CUBLAS=1
export CMAKE_ARGS="-DLLAMA_CUBLAS=on -DCMAKE_CUDA_ARCHITECTURES=all"
export FORCE_CMAKE=1
pip install llama_cpp_python==0.2.26 --force-reinstall --no-cache-dir
```

Thanks!

**Comment by pseudotensor** [comment]
For windows do:
```cmdline
pip uninstall llama_cpp_python llama_cpp_python_cuda -y
set CMAKE_ARGS=-DLLAMA_CUBLAS=on -DCMAKE_CUDA_ARCHITECTURES=all
set LLAMA_CUBLAS=1
set FORCE_CMAKE=1
pip install llama_cpp_python==0.2.26 --force-reinstall --no-cache-dir
```


I updated readme_windows with this.

**Comment by ramz35** [comment]
> Maybe 0.2.26 vs. latest llama_cpp_python is an issue. Latest is 0.2.55.
> 
> You could try:
> 
> ```
> pip uninstall llama_cpp_python llama_cpp_python_cuda -y
> CMAKE_ARGS="-DLLAMA_CUBLAS=on" pip install llama_cpp_python==0.2.26
> ```
> 
> so the same version is used.

well what do you know!!!

I checked my HWINFO and I have AVX2, SSE-3, and FMA available on the CPU so the 2nd environment is closer to the system spec.  However, I tried your suggestion.

You suggested to uninstall both, then only install one: llama-cpp-python.  Which is what I did.

On generate py I got:

> Starting get_model: llama
> Failed to listen to n_gpus: No module named 'llama_cpp_cuda'
> ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
> ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
> ggml_init_cublas: found 1 CUDA devices:

llama_cpp_cuda error (as to be expected as it was uninstalled)
then the No, Yes not consistent with the original, fast prompt eval environment :(

> llm_load_tensors: **using CUDA for GPU acceleration**
> llm_load_tensors: system memory used  =   53.82 MiB
> llm_load_tensors: **VRAM used**           = 2757.30 MiB
> llm_load_tensors: offloading 32 repeating layers to GPU
> llm_load_tensors: offloading non-repeating layers to GPU
> llm_load_tensors: offloaded 33/33 layers to GPU

that's looking better and more consistent with the original, fast prompt eval model :)

Finally I see this the proper use of the CPU features and BLAS=1 !!

> AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 |

but the proof is in the running of the model.... and it's a fast prompt eval, minimal CPU usage, fast output  !!!

so what changed:
- not using llama_cpp_python
- self-compiled version of llama-cpp-python 0.2.26

**so good call on the suggestion (thanks!)** but I'm at a lost to explain the variations I've seen. python and dependencies eh?

would love to understand the reason behind using llama-cpp-python-cuda over just llama-python-cpp (of course compiled for cuda)?

**Comment by ramz35** [comment]
> set LLAMA_CUBLAS=1

I've never used that so far in compiling llama-cpp-python.  What does **set LLAMA_CUBLAS=1** do?

**Comment by pseudotensor** [comment]
Actually 0.2.55 is much faster:

Linux:
```bash
pip uninstall llama_cpp_python llama_cpp_python_cuda -y
export LLAMA_CUBLAS=1
export CMAKE_ARGS="-DLLAMA_CUBLAS=on -DCMAKE_CUDA_ARCHITECTURES=all"
export FORCE_CMAKE=1
pip install llama_cpp_python==0.2.55 --force-reinstall --no-cache-dir
```

Windows the equivalent is:
```cmdline
pip uninstall llama_cpp_python llama_cpp_python_cuda -y
set CMAKE_ARGS=-DLLAMA_CUBLAS=on -DCMAKE_CUDA_ARCHITECTURES=all
set LLAMA_CUBLAS=1
set FORCE_CMAKE=1
pip install llama_cpp_python==0.2.55 --force-reinstall --no-cache-dir
```

Metal equivalent is:
```bash
pip uninstall llama_cpp_python llama_cpp_python_cuda -y
export LLAMA_CUBLAS=1
export CMAKE_ARGS="-DLLAMA_METAL=on"
export FORCE_CMAKE=1
pip install llama_cpp_python==0.2.55 --force-reinstall --no-cache-dir
```

**Comment by ramz35** [comment]
ok so final tests and `llama_cpp-python-cuda` seems to be the culprit.

if I uninstall `llama_cpp-python-cuda` everything speeds up - regardless if I use `llama-cpp-python==0.024 or ==0.2.55`

also it seems that llama_cpp-python-cuda sets GGML_CUDA_FORCE_MMQ: yes and after its removal CUDA_USE_TENSOR_CORES: is set to yes instead.  From a (very) quick search GGML_CUDA_FORCE_MMQ: yes is for older HW and TENSOR_CORES are preferred.  So that's odd behaviour.

Anyway, I now have a working h2ogpt with GPU support and acceptable performance on Windows, and I've got some more insights into under the hood stuff.  Now I'll be focussing on the features of h204gpt.  **Thanks again** for staying the course, it was helpful bouncing off your comments and suggestions.

**I am still curious though why llama-cpp-python-cuda is used at all.**

**Comment by pseudotensor** [comment]
For me 0.55 is much faster than 0.26.  So I recommend sticking with .55.

 llama-cpp-python-cuda is built by jllll as prebuilt wheels so user doesn't have to build them, which may require installing some things or taking time.  It also allows for separate CPU and GPU use with same installation, since each package will be used separately if using CUDA or not.
