### ISSUE TITLE
HYDE question

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#1451]
Hi, 
When I'm trying to Q&A using HYDE, from my understanding the level 1 should provide answer based on the LLM without using any documents from the collection, am I correct ?

But I see in the code and the debug output that even level 0 is retrieving documents and sends them to llm.

Can you please explain the difference then between level 1 and level 2 ?

Thanks

**Comment by pseudotensor** [comment]
Level 0 is pure LLM.

Does this help explain level 1 vs. 2?

https://github.com/h2oai/h2ogpt/blob/4d3cc7662a5bcf25eef4ef07b4dd3a9476ab31d2/src/gen.py#L848-L857

The UI also shows accordions with names to help guide.

E.g. here, I chose level 2, and since the intermediate results are by default added to UI with accordion, those 0 and 1 intermediate results are shown.  level 2 has no separate accordion, it's the final answer.

**Comment by pseudotensor** [comment]
github is messing up right now, can't share image.

**Comment by slavag** [comment]
@pseudotensor Thanks, I saw that explanation, but I think (ofc maybe I'm wrong) that even with level 1 it goes to DB, at least this is what I see in the debugger. Please correct me if I'm wrong.

**Comment by pseudotensor** [comment]
Can you show me an example of the first level (level 0) doing that?

**Comment by slavag** [comment]
@pseudotensor  I mean when I'm doing HYDE level 2, in the run_hyde method it does for from 0 to hyde_level, so, even with 0 stage it goes to db. In that for loop there's a get_chain method that brings documents from the DB by using ```
docs_with_score_chroma = sim_search(db, query=query, k=k_db, with_score=True,
                                            filter_kwargs=filter_kwargs,
                                            chunk_id_filter=chunk_id_filter,
                                            where_document_dict=where_document_dict,
                                            verbose=verbose)
```

**Comment by pseudotensor** [comment]
It's same code path but different settings.  E.g. db=None etc.

https://github.com/h2oai/h2ogpt/blob/37976707489946df4d1b0844ecdac4929f01ddc1/src/gpt_langchain.py#L6112-L6115

**Comment by slavag** [comment]
@pseudotensor  maybe I was not clear, 
When entering into run_hyde , the code does retrieval from the DB inside that for loop for every level in the range(hyde_level).
I'm in the debugger in the level 0 of 1, and it brings documents from the DB, see the attached screenshot
<img width="1387" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/f6a97611-edb2-44c8-a07f-90abe0d6f9e0">

Thanks

**Comment by pseudotensor** [comment]
If I just do all defaults but just change HYDE to level 1, I don't see any docs.

Maybe something else you are changing or doing is leading to this result, but it's hard to tell.  If you can look in debugger, then you should see that db=None and text_context_list=[] are passed to get_chain(), so where it is getting any docs from?

**Comment by slavag** [comment]
@pseudotensor  well, started from clean, in browser incognito mode. hyde_level 1.
On the level 0 it goes to DB

<img width="1480" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/2e636034-4a65-46f6-a1ec-49a1908bb2e1">

<img width="1434" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/a9f9e4bf-ed23-4b95-9810-bb9df036d577">

<img width="1533" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/ec15b198-e13a-4f35-8052-a4d706480363">

<img width="1484" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/6a1347dd-a476-4dfe-84c0-bc440a2cdfa7">

<img width="1474" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/3b4de75d-1fc2-4a76-9986-6e23324bcd6d">

Please direct me to place that you want me to check.

**Comment by pseudotensor** [comment]
So db=None before going into get_chain() right?  So can you step into get_chain() and see that docs is still empty.

If it's not, something else may be adding to text_context_list etc., e.g. search would do that.

**Comment by slavag** [comment]
Web search is not enabled
<img width="243" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/573de8c6-fa8e-4be2-8af2-1b959218815e">

db== None. Correct
and docs  empty in get_chain

<img width="1326" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/0da305c6-4c77-4407-8713-9eba66e2f54a">

Execution command generate.py --base_model=llama --prompt_type=llama2 --score_model=None --langchain_modes="['UserGuidesWithSupport', 'ZenDeskTickets', 'SecurityQuestionaries', 'LLM']" --langchain_mode_types="{'UserGuidesWithSupport':'shared', 'ZenDeskTickets':'shared', 'SecurityQuestionaries':'shared'}" --chunk_size=256 --top_k_docs=3 --h2ocolors=False --model_path_llama=/Users/slava/Development/private/AI/Models/TheBloke/Mistral-7b-Instruct/mistral-7b-instruct-v0.2.Q5_K_M.gguf --max_seq_len=16536 --verbose=True --cut_distance=1.4 --debug=True

Now, in get_chain db_type is Chroma and db is loaded 
<img width="1570" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/90624e0d-e1b0-4105-974e-3dad3197b7d4">

<img width="1621" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/f647c255-0301-4ef0-9438-9aa8e511108f">

**Comment by slavag** [comment]
@pseudotensor Maybe if I choose collection in the resources, it'll go to the DB even in level 0 of level 1 ?
