### ISSUE TITLE
Git Pull breaks install. What's the standard update process?

### ISSUE THREAD

**Issue by ewebgh33** [h2oai/h2ogpt#1453]
Windows 11.

```
git pull
python generate.py
```

Error:
```
  File "C:\AI\Text\h2ogpt\src\gpt_langchain.py", line 47, in <module>
    from langchain_mistralai import ChatMistralAI
ModuleNotFoundError: No module named 'langchain_mistralai'
```
Hmm OK. New requirements?
Check requirements.txt
Eh
`pip install -r requirements.txt`
Cool cool
`python generate.py`
Same error.

I have to say, the install process for h2o is crazy complicated compared to practically every other LLM app out there.
On top of that, a simple git pull to update has broken it.
So what is the recommended update process please?

If I git pull, what else do I need to do (as new requirements install doesn't seem to give it langchain_mistralai"
Do I need to start over from scratch??

**Comment by ewebgh33** [comment]
Answering my own question for anyone else who has this.
You have to do BOTH
pip install -r requirements.txt
pip install -r reqs_optional/requirements_optional_langchain.txt

Here's the thing. If it's optional why does it HAVE to be run to start h2o, after a git pull?

Anyway, run both.

**Comment by pseudotensor** [comment]
langchain_mistralai is in reqs_optional/requirements_optional_langchain.txt correct.  that package was added 2 days ago to that file.  If don't want langchain mode you can pass to CLI `--langchain_model=Disabled` to avoid that.

But I suspect you just did the right thing.
