### ISSUE TITLE
Is it possible to change the name of the ai models?

### ISSUE THREAD

**Issue by mooodali** [h2oai/h2ogpt#1454]
Hi guys
Is it possible to change the name of the ai models?
Let me give an example
I want whenever the user asks a question like "Can you introduce yourself" or "Hello, how are you?"
I don't want him to answer this
"I am an AI language model developed by OpenAI called GPT-3"
rather say
"My name is Jack and I am an intelligent robot"

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#system-prompting

In CLI this is done by passing
```
python generate.py --system_prompt="My name is Jack and I am an intelligent robot" ...
```

In UI this is done by going to expert and adding that text to the "System prompt" text box.
