### ISSUE TITLE
How can I create a REST API for Flutter SDK?

### ISSUE THREAD

**Issue by mooodali** [h2oai/h2ogpt#1455]
Hi guys
How can I create a REST API for FlutterSDK?
thank you

**Comment by pseudotensor** [comment]
OpenAI proxy server is rest API.  Maybe use that?

**Comment by mooodali** [comment]
Thank you for your reply
  No, I want to install h2ogpt on the server and create a REST API
Do you think it is possible?
If possible, tell me the method

**Comment by mohamed-alired** [comment]
?

**Comment by pseudotensor** [comment]
The OpenAI proxy can be accessed as REST API.
