### ISSUE TITLE
Question cut_distance vs document score

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#1461]
When there's a docs retrieved from the chromadb in the code, it uses similarity_search_with_score.
What is the relation between score and cut_distance.
As I tried to reduce cut_distance , 1.4 or 1.0 and don't see differences, as all returned docs have score < 1.0,
So, is  0< = score <= 1.0 ? or it can be any float number ?
Screenshot of the code where code takes everything that is < cut_distance 
   
<img width="1138" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/2bb00136-e501-492e-ab6e-353fd3aa90ae">

Thanks

**Comment by pseudotensor** [comment]
The cut distance was optimized for the "mini all" embedding model with cut at 1.64.  For instructor-large it's ok, but that model has very flat distribution of scores.  For bge, need to avoid the cut, i.e. make it large like 10000.

So in general best to tune it for your embedding model.

https://github.com/h2oai/h2ogpt/issues/1095
