### ISSUE TITLE
Document sources (.txt) not showing the correct HEAD value in table

### ISSUE THREAD

**Issue by vanboom** [h2oai/h2ogpt#1466]
I have ingested some .txt files into UserData data using the standard procedure in the docs.  When showing the Document Select tab, the `head` column in the document sources table is showing what appears to be some truncated info.  

![image](https://github.com/h2oai/h2ogpt/assets/251706/02591acc-efd4-4545-b2eb-400e1c6a823e)

Is this an issue with the UI or are my docs not being ingested properly?  It is possible to debug ingested data?  Appreciate any tips on where in the code to search for this as I am happy to contribute PRs if possible.    Thanks all!

**Comment by pseudotensor** [comment]
You can review the entire document and how it appears in the database in the document view tab.  See what that looks like for one of those docs.

**Comment by vanboom** [comment]
Thanks @pseudotensor, 

Ok yes, I had to pull the main branch now it is working.  This helps for now.  I am still curious it appears that the `head` column in the sources table is showing the last 'chunk' and not the first one.   (Still learning!)
