### ISSUE TITLE
How to --add_chat_history_to_context=True ?

### ISSUE THREAD

**Issue by planetMatrix** [h2oai/h2ogpt#1474]
Enter an instruction: what is 2+2?
According to basic arithmetic, the sum of two (2) is four (4), so the answer to your question is four (4).
Enter an instruction: add 5 to it
Sure! What number would you like me to add 5 to? Please provide the initial number.
Enter an instruction:

``python generate.py  --score_model=None --base_model='llama' --model_path_llama=zephyr-7b-beta.Q6_K.gguf --prompt_type=zephyr --max_seq_len=1024 --cli=True --max_new_tokens=1024 --add_chat_history_to_context=True --load_4bit=True --llamacpp_dict="{'n_gpu_layers':20}"

**Comment by pseudotensor** [comment]
add_chat_history_to_context is by default true.

Under what case are you having some issue with history?  cli mode?

**Comment by planetMatrix** [comment]
yes cli

**Comment by pseudotensor** [comment]
Try again, I fixed some excessive limits.  But also consider making max_seq_len larger to 2048 and max_new_tokens smaller like 512.

**Comment by planetMatrix** [comment]
Perfect! This is working marvelously.

However is there any way to enable it when --langchain_mode=UserData?

Many thanks for your unwavering support really appreciate it.

**Comment by pseudotensor** [comment]
Is it not working with langchain mode enabled?

**Comment by gotititu** [comment]
No it is not unfortunately

**Comment by planetMatrix** [comment]
No it is not unfortunately

**Comment by pseudotensor** [comment]
Your choices of CLI options is too limiting.  The 2nd round of chat would have something quite large in terms of number of tokens, esp. if you allow 1024 new tokens and 1024 is max tokens.

Also, your choice of llamacpp_dict is very limiting in terms of speed, it's about 10x slower than defaults.

Also, you don't need to pass load_4bit (unused for llama.cpp models) or add_chat_history_to_context (default is True).

A better version that is fast and can handle the long history with documents is (zephyr is not good for chat history + rag):
```
CUDA_VISIBLE_DEVICES=0 python generate.py --cli=True --langchain_model=UserData --score_model=None --base_model=https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q4_K_M.gguf --prompt_type=mistral --max_seq_len=2048 --max_new_tokens=128 --top_k_docs=3 --metadata_in_context=False --chunk-size=128 --add_disk_models_to_ui=False --pre_load_embedding_model=True --embedding_gpu_id=cpu --cut_distance=10000 --hf_embedding_model=BAAI/bge-base-en-v1.5
```

![image](https://github.com/h2oai/h2ogpt/assets/2249614/4a988f58-99ea-4a68-bedf-a28ee27072c1)
