### ISSUE TITLE
How to use exllama v2 with local GPTQ file ? 

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#1478]
Hi,
Tried to find how to use h2ogpt chat with exllama v2 with local GPTQ file, like I can do this with GGUF and llama.cpp ?

And also another question : 
when I'm using llama.cpp with local GGUF file, I'm passing --base_model=llama parameter, but actually the mode is Mistral-instruct, how can I tell to h2ogpt that I'm using Mistral and not llama ?

Thanks 
P.S. maybe you know , if the tokens/sec is higher in exllama v2 than in llama.cpp ?

**Comment by pseudotensor** [comment]
With latest builds of llama.cpp, there's no need for exllama v2 anymore in terms of speed or stability.

**Comment by slavag** [comment]
@pseudotensor  with that run command python generate.py --base_model=TheBloke/Mistral-7B-Instruct-v0.2-GGUF --prompt_type=mistral --max_seq_len=4096

Can I specify the path for the model file ?
Thanks

**Comment by pseudotensor** [comment]
Yes, for path you just do `--base_model=llama --model_path_llama=<path>` .

https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#gguf--ggml

We check for the actual path (e.g. local or absolute) or if it is inside `--llamacpp_path` which defaults to `./llamacpp_path` folder where we download stuff too.
