### ISSUE TITLE
add support for qdrant

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#149]
https://qdrant.tech/

**Comment by AyeshGK** [comment]
Looking forward to contributing, could you please provide more details to help me better understand the task?

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/issues/145#issuecomment-1552281087

**Comment by nnWhisperer** [comment]
@AyeshGK , it would be nice if you've added this. Also, don't forget to add the tests pseudotensor mentioned in the reference comment. Tests make the quality (I came to this repository after seeing no tests in imartinez/privateGPT and su77ungr/CASALIOY repos and many issues compared to having lower features than here.
