### ISSUE TITLE
Error: not enough values to unpack (expected 8, got 5)

### ISSUE THREAD

**Issue by MaximdeWinter** [h2oai/h2ogpt#1492]
Hello, i have a fairly large issue using https://gpt-gm.h2o.ai/. (The terms of service led me here, so i hope im at the right place)
I have the Error written in the title for like 9 hours now, i reopened the website but it didnt help, in the following image you can see what happens when i open the site:
![afa](https://github.com/h2oai/h2ogpt/assets/164397117/ae44382e-0caa-43c8-b70d-eb4c281e1829)
I hope someone can help me out.

**Comment by pseudotensor** [comment]
Thanks for reporting.  Please:

1) What were you doing when you hit the error?  Trying to login?  Can you say if there's something special about your choices?
2) Try again, we've restarted with a fix to a return, but that should only matter if you had an invalid password.

**Comment by MaximdeWinter** [comment]
Hello, thanks for the response. So i only logged and that itself worked. LLM´s loaded up like they usually do and after a few seconds the error appears. The picture above is about 5 seconds after login
