### ISSUE TITLE
[Errno 28] No space left on device

### ISSUE THREAD

**Issue by MaximdeWinter** [h2oai/h2ogpt#1494]
Hello, it seems i have encountered another problem. I first thought, maybe i just have to clear my browser cache, but that didnt help, and  i checked and none of my discs are remotely close to full.  
When i try to log in with my username and password, nothing will happen. So i tried logging in with the guest account and that worked, but when i then tried to communicate with the LLM the error in the title appears and the LLM doesnt answer
![Error](https://github.com/h2oai/h2ogpt/assets/164397117/0316ab2c-fbb7-4e63-84d9-2c307a5b7986)

**Comment by pseudotensor** [comment]
Thanks, it's back up with /tmp mapped to another disk with plenty of free space.  Forgot to do that after last round of provider messing up the system.
