### ISSUE TITLE
  ERROR: Failed building wheel for sentencepiece

### ISSUE THREAD

**Issue by peterchanws** [h2oai/h2ogpt#151]
macOS 13.3; i7, 16 GB RAM
Got this running pip install -r requirements.txt 

         raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./build_bundled.sh', '0.1.97']' returned non-zero exit status 127.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sentencepiece
  Running setup.py clean for sentencepiece
  Building wheel for peft (pyproject.toml) ... done
  Created wheel for peft: filename=peft-0.3.0.dev0-py3-none-any.whl size=40691 sha256=95ab9313644133ab4119d02de8e13e4a54303ee6f5c32d77cd9326692788da00
  Stored in directory: /Users/pchan3/Library/Caches/pip/wheels/79/e1/5e/290ff7370e9bc139bd06fca1874fe480fff7bb45f0fd741cd4
Successfully built peft
Failed to build sentencepiece
ERROR: Could not build wheels for sentencepiece, which is required to install pyproject.toml-based projects

**Comment by peterchanws** [comment]
no problem with the current release

**Comment by pseudotensor** [comment]
Hi @peterchanws thanks for checking.

I am relatively newbie for MAC use.  What are the typical requirements for MAC use?  I only have a macbook pro.  Does one require a special M1 chip for MPS?  I can add MPS support back.

Also, does one use the native operating system, or run in docker, or some other virtual machine?

Thanks!

**Comment by peterchanws** [comment]
I am not a technical person. I past the pip install -r requirements.txt phase. But, I am stuck in the next phase "python generate.py --base_model=h2oai/h2ogpt-oig-oasst1-512-6.9b".

Anyway, I am using a 10 years old MacPro and macOS 12.6.5 to try installing the software.

**Comment by pseudotensor** [comment]
I tested it with mac using instructions for env:

https://github.com/h2oai/h2ogpt/blob/main/FAQ.md#env-installation

and specific mac thing:

https://github.com/h2oai/h2ogpt/blob/main/FAQ.md#macos

and it worked fine on my 4 years old macbook pro
