### ISSUE TITLE
sources not visible in ngrok app

### ISSUE THREAD

**Issue by santosh-gkg** [h2oai/h2ogpt#1512]
![image](https://github.com/h2oai/h2ogpt/assets/150844949/4109e183-0322-44eb-a13c-6f924b1ba7cb)
they are working fine in localhost but not in a ngrok app

**Comment by pseudotensor** [comment]
I don't think it's ngrok or not.  If that is a shared doc, you'll need to ensure that is added to `extra_allowed_paths` so gradio knows it's ok to allow that to be downloaded.

This works on gpt.h2o.ai, which uses ngrok for MyData that uses a "users" directory.

**Comment by pseudotensor** [comment]
If you still see issues, it might be good to give me an example, and I can reach out to gradio team if it's not h2ogpt issue.

**Comment by santosh-gkg** [comment]
thank you very much it's working 
i added the collections folder name in paths
![WhatsApp Image 2024-03-29 at 21 11 48_06e34013](https://github.com/h2oai/h2ogpt/assets/150844949/019957ed-774c-436a-b2c5-0981e344869c)

**Comment by pseudotensor** [comment]
Great.  It should work if you just pass as an extra_allowed_paths on CLI instead of changing code.

**Comment by santosh-gkg** [comment]
Okay
