### ISSUE TITLE
Shared collection problem with multiple users

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2ogpt#1515]
I created multiple shared collection through UI like UserData1, UserData2 And UserData3. When i run the h2ogpt with enabling the login then UserData2 and UserData3 is not shown in the Collections Tab. 

`HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 python generate.py --inference_server="vllm:127.0.0.1:5000" --base_model='/home/xyz/.cache/huggingface/hub/models--meta-llama--Llama-2-13b-chat-hf/snapshots/c2f3ec81aac798ae26dcc57799a994dfbf521496' --score_model=None --langchain_modes="['UserData','UserData2','LLM','MyData']" --user_path=user_path --use_auth_token=True --max_seq_len=4096 --max_max_new_tokens=2048 --max_new_tokens=2048 --min_new_tokens=128  --prompt_type=llama2 --enable_stt=False --enable_tts=False --auth_filename=$auth_filename --auth_access=open --guest_name=abc --auth="[(admin, admin)`

How can we make shared collection is accessible for all the users?

**Comment by pseudotensor** [comment]
If they are existing users, you can add them to their auth.json entries and/or they can push the sync button in the UI.

For new users, one would pass additional things, e.g.

```
--langchain_modes="['UserData','UserData2','LLM','MyData']"  --langchain_mode_paths="{'UserData': 'user_path', 'UserData2': 'user_path2'}" --langchain_mode_types="{'UserData': 'shared', 'UserData2': 'shared'}"
```
i.e.
```
(h2ogpt) jon@pseudotensor:~/h2ogpt$ python generate.py --langchain_modes="['UserData','UserData2','LLM','MyData']"  --langchain_mode_paths="{'UserData': 'user_path', 'UserData2': 'user_path2'}" --langchain_mode_types="{'UserData': 'shared', 'UserData2': 'shared'}" 
```

gives in UI for random new user:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/34551899-ed61-44a2-9392-b8310b8dd8f0)

**Comment by pseudotensor** [comment]
Closing, if issues, let me know and I'll still respond.

**Comment by llmwesee** [comment]
Still Not working. Suppose h2ogpt with multiple collections is hosted on the server, now i want all the users/clients must have access those Collections.

`HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 python generate.py --inference_server="vllm:127.0.0.1:5000" --base_model='/home/xyz/.cache/huggingface/hub/models--meta-llama--Llama-2-13b-chat-hf/snapshots/c2f3ec81aac798ae26dcc57799a994dfbf521496' --score_model=None --langchain_modes="['UserData','UserData2','LLM','MyData']"  --langchain_mode_paths="{'UserData': 'user_path', 'UserData2': 'user_path2'}" --langchain_mode_types="{'UserData': 'shared', 'UserData2': 'shared'}" --use_auth_token=True --max_seq_len=4096 --max_max_new_tokens=2048 --max_new_tokens=2048 --min_new_tokens=128 --concurrency_count=64 --batch_size=16 --prompt_type=llama2 --enable_stt=False --enable_tts=False --auth_filename=$auth_filename --auth_access=open --guest_name=abc --auth="[(admin, admin)]"` 

One thing I noticed when i just remove the `--auth="[(admin, admin)]"`  then it works perfectly and all the users have access to those Collections.

**Comment by pseudotensor** [comment]
Hi, I'm still not seeing any issues.

I ran like this:
```
(h2ogpt) jon@pseudotensor:~/h2ogpt$ python generate.py --langchain_modes="['UserData','UserData2','LLM','MyData']"  --langchain_mode_paths="{'UserData': 'user_path', 'UserData2': 'user_path2'}" --langchain_mode_types="{'UserData': 'shared', 'UserData2': 'shared'}" --auth="[(admin, admin)]" --auth_filename=auth_test.json --auth_access=open --guest_name=guest
```

Note that if you use an auth file, the ` --auth="[(admin, admin)]"` is ignored and only used to indicate a non-empty --auth parameter that (as opposed to `--auth=''` will enable auth.

Since access is open, I can use any new user.  I used 'jon' and see this:
![image](https://github.com/h2oai/h2ogpt/assets/2249614/6da7b820-4959-4159-a845-768dc4e73f5b)

**Comment by llmwesee** [comment]
Yes, the existing users and also the new user don't see newly created  shared collections

**Comment by pseudotensor** [comment]
Should be fixed now. Wasn’t bug just feature request.
