### ISSUE TITLE
Does this tool guarantee that all data is private?

### ISSUE THREAD

**Issue by jaysunl** [h2oai/h2ogpt#1528]
I saw in the README that this tool completely protects all data, is that right? Meaning if I choose to upload documents for the chatbot to ingest, that information will not be collected/retained by any third party companies?

**Comment by santosh-gkg** [comment]
if you are doing on your system then obviously not, can't say about website but i hope no

**Comment by pseudotensor** [comment]
I do best to make sure h2oGPT avoids all telemetry (various packages like chroma, HF, gradio, etc. etc. all enable by default, but I disable them by default).  I also change code for other packages that actually don't listen to their options, like posthog related stuff. 

However, we have our own that only tracks IP address during login, but that can be easily disabled like:

https://github.com/h2oai/h2ogpt/blob/a0ba89a99ed774f37aa3de595a57f02f12c1f440/docs/README_offline.md#L186-L192
