### ISSUE TITLE
about Add Doc to Chat

### ISSUE THREAD

**Issue by zjudongze** [h2oai/h2ogpt#1535]
I don't know whats the point of option "Add Doc to Chat". 

I tried to query with it on or off. I didn't see any difference.

and in the source code, it seems it does nothing except the following line
"do_show = gradio_upload_to_chatbot1 or gradio_errors_to_chatbot1"

and the default setting will set gradio_errors_to_chatbot1 to true, so gradio_upload_to_chatbot1  has no effect.

can this option be used to feed full content of a selected document into llm?

**Comment by pseudotensor** [comment]
It works, it's just a bit confusing as was since CLI option overwhelmed UI option. I fixed that.

What it looks like when upload image or audio:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/906138e9-cb78-4ccb-8807-9c928df1ff62)
