### ISSUE TITLE
One Click Installers for MacOS not working on MacMini M2

### ISSUE THREAD

**Issue by VillaesterModerneMedien** [h2oai/h2ogpt#1536]
Hello,

I am currently trying to install H2O GPT on my MacMini and am not getting anywhere with the One Click Installers.

---
Mar 07, 2024

[h2ogpt-osx-m1-cpu](https://h2o-release.s3.amazonaws.com/h2ogpt/Mar2024/h2ogpt-osx-m1-cpu)
[h2ogpt-osx-m1-gpu](https://h2o-release.s3.amazonaws.com/h2ogpt/Mar2024/h2ogpt-osx-m1-gpu)
Nov 08, 2023

[h2ogpt-osx-m1-cpu](https://h2o-release.s3.amazonaws.com/h2ogpt/Nov2023/h2ogpt-osx-m1-cpu)
[h2ogpt-osx-m1-gpu](https://h2o-release.s3.amazonaws.com/h2ogpt/Nov2023/h2ogpt-osx-m1-gpu)
---

I have started the file for installation, but after a short time (it looks as if it is being installed), the file (e.g. h2ogpt-osx-m1-gpu) is simply opened in a text editor and then it doesn't go any further.
I have enabled the installation of the extension in the system settings before...

Is it because the install is actually for an M1 Mac?
Does anyone have a similar problem?
I can't install H2O GPT at the moment...

System Specs:
Mac mini 2023
Apple M2 Pro
32 GB
macOS: Sonoma 14.4.1

Any help would be appreciated, thank you very much.

**Comment by pseudotensor** [comment]
I've asked @Mathanraj-Sharma for help.

**Comment by USMCM1A1** [comment]
Same--would love for this to work.

**Comment by pseudotensor** [comment]
I'll probably need to remove the mac installer and just document use of docker for mac.
