### ISSUE TITLE
auth related feature

### ISSUE THREAD

**Issue by zjudongze** [h2oai/h2ogpt#1544]
How to implement such features:

1. Anonymous use is not allowed; that is, when the webpage is opened, it prompts for login, and it can only be used after logging in.
2. Allow the registration of new users.

currently auth related feature can only fullfil the 2nd feature
I don't how to disable anonymous usage.
H2OGPT will silently create a new user for any new web sessions, resulting lots of uuid folders in users,
such as this one:
![image](https://github.com/h2oai/h2ogpt/assets/24449983/5100357f-f662-4e1d-ba3b-a395fc6ba650)

**Comment by zjudongze** [comment]
there are also no hints in login page. I mean when I register for a website, chrome usually will promt for new password and save it. When I login again, chrome will auto fill username and password.

but chrome can't recognize h2ogpt's login page. even if I save username and password in chrome manually, when I open the login page, there is no prompt or autofill from chrome.

**Comment by zjudongze** [comment]
third: when I did login in h2ogpt, if I refresh the page, I am logout silently. 
I wish I am still in login state even if I refresh the page

**Comment by santosh-gkg** [comment]
for your first query of no anonymous usage not allowed you can pass --auth_access=closed in CLI, that will allow only registered users to sign in, you can also enable google auth, for me chrome detects the username and password and it also prompts to save it

new users can register themselves and save their history by logging again in the login tab

**Comment by santosh-gkg** [comment]
![image](https://github.com/h2oai/h2ogpt/assets/150844949/753a6cc2-4bf5-454d-9b35-f77802b1acbc)

**Comment by zjudongze** [comment]
> for your first query of no anonymous usage not allowed you can pass --auth_access=closed in CLI, that will allow only registered users to sign in, you can also enable google auth, for me chrome detects the username and password and it also prompts to save it
> 
> new users can register themselves and save their history by logging again in the login tab

--auth_access=closed only prohibit new register. but h2ogpt still siliently create a new user (ID is like uuid, such as 8220ae76-51a3-4bb7-aa33-1069ebf0ea95) for  sessions that does not login explicitly.

I want to prohibit usage of h2ogpt if a user does not login manually and explicilty.

**Comment by pseudotensor** [comment]
@zjudongze Use `--auth='closed'` .  It does not create a new user.  It's a full authentication block if they don't have the correct user name and password, nothing gets passed it, no gradio_runner.py etc. commands are run.

**Comment by zjudongze** [comment]
> @zjudongze Use `--auth='closed'` . It does not create a new user. It's a full authentication block if they don't have the correct user name and password, nothing gets passed it, no gradio_runner.py etc. commands are run.
> 
> If you are (perhaps) referring to client session hash, that's set by client and not the server.

when I use --auth='closed', it almost fulfill my need. but there is still a bug.
when I first open the website, it promt for login. I can use my previous registered user or create a new user.
but in both cases, after I login , the status in log-in/out page show "Invalid password for user xxxx"
![image](https://github.com/h2oai/h2ogpt/assets/24449983/56fd6fba-6f19-4674-920d-f2a6b5039a69)

when I refresh the main page, the chat history I saved under this user disappear under the chats tab. If I login in log-in/out tab, the chats tab will correctly show the chat history I save under that user.

**Comment by pseudotensor** [comment]
with `--auth_access='closed'` you shouldn't be able to create a new user.

**Comment by pseudotensor** [comment]
Hi, I did fix the bug of saying "not successful login"  That's in main now.
