### ISSUE TITLE
vLLM GROQ issue

### ISSUE THREAD

**Issue by chrissas** [h2oai/h2ogpt#1552]
@pseudotensor

GROQ url mentioned in the documentation is wrong, I had confirmation from the groq team https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md.

https://api.groq.com/openai:None:/v1: is deprecated and unused.

<img width="1050" alt="image" src="https://github.com/h2oai/h2ogpt/assets/22572193/5a759861-2c8b-48c5-8316-edaa10fe4281">

I tried their url but I still get this error
Exception: Error code: 404 - {'error': {'message': 'Unknown request URL: POST /openai/v1/completions:/completions. Please check the URL for typos, or see the docs at https://console.groq.com/docs/', 'type': 'invalid_request_error', 'code': 'unknown_url'}}
<img width="1210" alt="image" src="https://github.com/h2oai/h2ogpt/assets/22572193/bd5d64f0-767b-4551-99f5-b319dba47d54">

 command :
python generate.py --model_lock="[{'inference_server':'vllm:https://api.groq.com/openai/v1/chat/completions:<myAPIkey>', 'base_model':'mixtral-8x7b-32768', 'max_seq_len': 31744, 'prompt_type':'plain'}]" 

command :
python generate.py --model_lock="[{'inference_server':'vllm:https://api.groq.com/openai:None:/v1/chat:GroqAPIkey', 'base_model':'mixtral-8x7b-32768', 'max_seq_len': 31744, 'prompt_type':'plain'}]"

![image](https://github.com/h2oai/h2ogpt/assets/22572193/814f3b47-1ee5-4375-ab8e-81701f8deb08)

**Comment by chrissas** [comment]
python generate.py --model_lock="[{'inference_server':'vllm:https://api.groq.com/openai:None:/v1/chat:GroqAPIkey', 'base_model':'mixtral-8x7b-32768', 'max_seq_len': 31744, 'prompt_type':'plain'}]"

![image](https://github.com/h2oai/h2ogpt/assets/22572193/814f3b47-1ee5-4375-ab8e-81701f8deb08)

**Comment by pseudotensor** [comment]
Use the other way mentioned for groq a bit lower in the FAQ, i.e. 

![image](https://github.com/h2oai/h2ogpt/assets/2249614/07acd843-ecec-4d10-b613-827565e5b1d3)
