### ISSUE TITLE
RuntimeError: An error occurred while downloading using `hf_transfer`.

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2ogpt#1554]
I created fresh environment with latest h2ogpt repo. After doing all the necessary steps I launched the h2ogpt with the the following command: 

```
python generate.py --base_model=meta-llama/Llama-2-13b-chat-hf --score_model=None --langchain_mode=UserData --user_path=user_path --use_auth_token=True --max_seq_le
n=4096 --max_max_new_tokens=2048 --max_new_tokens=2048 --min_new_tokens=128  --prompt_type=llama2
```

when I doing it  and the model downloading is getting started and after sometime it getting stucked in between and sometimes throws the following error:
`RuntimeError: An error occurred while downloading using `hf_transfer`. Consider disabling HF_HUB_ENABLE_HF_TRANSFER for better error handling.`

Note:  The mistral 7b is downloading and running perfectly. 

![Screenshot from 2024-04-12 14-22-50](https://github.com/h2oai/h2ogpt/assets/137979399/6ba31a5e-0b54-41f7-a422-2b035e9af806)

**Comment by pseudotensor** [comment]
You can set 
```
export HF_HUB_ENABLE_HF_TRANSFER=0
```
and we'll not use hf_transfer in latest main.  It's vastly faster for those that have high speed internet, so why it's default.
