### ISSUE TITLE
Why this: admin_pass = os.getenv("ADMIN_PASS")

### ISSUE THREAD

**Issue by kiancn** [h2oai/h2ogpt#158]
As I was reading through the source I stumbled across this:
generate.py ln 236: `admin_pass = os.getenv("ADMIN_PASS")`
It seems nothing accesses admin_pass - and my Windows 10 environment does not have such a variable, so admin_pass ends up being  NoneType.

After looking into it a little my guess is that it is a sort of joke to get people's paranoia going.

Is there a reason for trying to scrape the admin password? Hopefully I am reading the code wrong.

🖖

**Comment by pseudotensor** [comment]
If you set ADMIN_PASS as env and you enter that password into the gradio UI in "system" tab, you will be able to access system info (GPU memory usage) and download or push (to s3, your bucket/etc) any logs collected.

Just some example ENVs one can set:
```
ADMIN_PASS
AWS_BUCKET
AWS_SERVER_PUBLIC_KEY
AWS_SERVER_SECRET_KEY
HEIGHT=800
HUGGINGFACE_API_TOKEN
LANGCHAIN_MODE
SAVE_DIR
SCORE_MODEL
```
The ADMIN+AWS ones are relevant for collecting logs.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/fcdb58b3-fb5d-49ed-abae-83bda4f5fc32)

I'll make sure to document these somewhere.

**Comment by kiancn** [comment]
Thank you for the very good explanation!
