### ISSUE TITLE
Document Storage

### ISSUE THREAD

**Issue by jaysunl** [h2oai/h2ogpt#1580]
I want to change this repository so that when I open the chatbot, it already has the documents pre-loaded and I don't have to manually upload the documents myself everytime I start it up (even without logging in). I'm guessing the db directory is created somewhere everytime I ingest some docs so if I pre-create the db directory and call python generate.py, does that load up the chatbot with the docs knowledge already? And also where is the db directory located?

**Comment by santosh-gkg** [comment]
use make_db.py to create database as shared folders refer the documentations in docs/readme_langchain

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/blob/main/docs/README_LangChain.md#database-creation
