### ISSUE TITLE
Question: correct prompts template for llama3-instruct

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#1587]
Hi,
What is correct prompts template for llama3-instruct, that I can choose from the existing to be able to work with model ?

Thanks

**Comment by pseudotensor** [comment]
It works OOTB in newer h2ogpt.  Uses chat template with end of turn stopping added.

**Comment by slavag** [comment]
@pseudotensor Thanks, can you please elaborate more, as I'm not fully understand :) Sorry

**Comment by pseudotensor** [comment]
e.g. this is sufficient:
```
python generate.py --base_model=meta-llama/Meta-Llama-3-8B-Instruct
```

It uses the chat template that is in the HF model repo.  This doesn't have a system prompt, so we add that as a pre-conversation.

**Comment by slavag** [comment]
@pseudotensor Thanks, but if I'm using GGUF version, this not happens.

**Comment by pseudotensor** [comment]
llama-3 prompting is tricky and so to ensure it is done right, please use latest h2oGPT as of the recent merge and run:
```
python generate.py --base_model=llama --model_path_llama=https://huggingface.co/QuantFactory/Meta-Llama-3-8B-Instruct-GGUF/resolve/main/Meta-Llama-3-8B-Instruct.Q5_K_M.gguf?download=true --tokenizer_base_model=meta-llama/Meta-Llama-3-8B-Instruct --max_seq_len=8192
```

**Comment by slavag** [comment]
@pseudotensor Thanks, using the latest code and example you provided, it's working fine, can you just provide a bit more details on from where model prompt template is taken in that case and why need to provide  --tokenizer_base_model ? Also if using full off-line mode will the --tokenizer_base_model work ?

**Comment by pseudotensor** [comment]
Yes, once off line then do:
To use offline, then do:
```bash
python generate.py --base_model=llama --model_path_llama=Meta-Llama-3-8B-Instruct.Q5_K_M.gguf --tokenizer_base_model=meta-llama/Meta-Llama-3-8B-Instruct --max_seq_len=8192 --gradio_offline_level=2 --share=False --add_disk_models_to_ui=False
```
which assumes the model was downloaded to location set by `llamacpp_path` (default is llamacpp_path folder).  This works for offline if previously used the earlier command that got the tokenizer.

**Comment by pseudotensor** [comment]
The model prompt template is taken from

https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/tokenizer_config.json#L2053

if using that as the tokenizer_base_model

**Comment by slavag** [comment]
@pseudotensor Thanks a lot !!

**Comment by dimm0** [comment]
It keeps repeating my question when I run meta-llama/Meta-Llama-3-8B-Instruct... What am I doing wrong? (Can post my params, but I tried the ones from here, everything else is same with llama2 which works fine)

**Comment by pseudotensor** [comment]
Your command looks fine, although you don't need to pass that --tokenizer_base_model unless you are using GGUF models.

E.g. when I run your command, I get:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/2ada24f0-e750-4f4b-8f57-7cf8f4dac1d0)

**Comment by dimm0** [comment]
Should the prompt type be unknown? I think I'm having issues with that..

**Comment by dimm0** [comment]
<img width="454" alt="Screenshot 2024-05-31 at 7 40 36 AM" src="https://github.com/h2oai/h2ogpt/assets/1425007/8e8a7ff4-0d7d-4fb8-a010-eac45c8363e7">

**Comment by bw-Deejee** [comment]
I'm on a fresh installation on newest repo version and i get this error when running
`python generate.py --base_model=meta-llama/Meta-Llama-3-8B-Instruct --hf_embedding_model=intfloat/multilingual-e5-large --auth=None`

`Error
Prompt was not set: ['Traceback (most recent call last):\n File "/home/bw/h2ogpt/src/prompter.py", line 2405, in apply_chat_template\n prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n File "/home/bw/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1817, in apply_chat_template\n compiled_template = self._compile_jinja_template(chat_template)\n File "/home/bw/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1894, in _compile_jinja_template\n raise ImportError(\nImportError: apply_chat_template requires jinja2>=3.1.0 to be installed. Your version is 3.0.3.\n', 'Traceback (most recent call last):\n File "/home/bw/h2ogpt/src/prompter.py", line 2405, in apply_chat_template\n prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n File "/home/bw/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1817, in apply_chat_template\n compiled_template = self._compile_jinja_template(chat_template)\n File "/home/bw/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1894, in _compile_jinja_template\n raise ImportError(\nImportError: apply_chat_template requires jinja2>=3.1.0 to be installed. Your version is 3.0.3.\n']`

**Comment by pseudotensor** [comment]
It's some transformers bug in their packaging.  But I noticed it and added a while back `jinja2>=3.1.0` in requirements.txt, so should work fine.

When I check the latest 799 docker image built, I see no issue with jinja2.
```
bash-5.2$ python
Python 3.10.14 (main, May  1 2024, 21:48:03) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jinja2
>>> jinja2.__version__
'3.1.4'
>>> 
```

**Comment by bw-Deejee** [comment]
Works. Ty
