### ISSUE TITLE
branding capitalization

### ISSUE THREAD

**Issue by TallTed** [h2oai/h2ogpt#1593]
Branding is often important. I want to use your intended branding when I talk about H2O.ai and h2oGPT, but I am not sure what your intentensions are.

[`H2O.ai`](https://h2o.ai/) appears to be (mostly) consistent for your company.

But do you intend "H2O GPT", "H2o GPT", "h2oGPT", "h2ogpt", something else?

**Comment by pseudotensor** [comment]
h2oGPT, thanks.
