### ISSUE TITLE
shared / personal collections

### ISSUE THREAD

**Issue by InesBenAmor99** [h2oai/h2ogpt#1596]
Hello, can someone answer my question? For collection types, shared or personal, does that mean if I'm signed in as user1 and I create some shared collections, then sign out and log in as user2, am I supposed to find the collections that user1 created?

**Comment by pseudotensor** [comment]
Yes, they are accessible, but by default the user would need to add it to their list in document selection, or add to CLI as default, or one adds to a specific user's auth.json entry.

https://github.com/h2oai/h2ogpt/issues/1515
