### ISSUE TITLE
Failed to initial linux full script intallation 

### ISSUE THREAD

**Issue by juerware** [h2oai/h2ogpt#1599]
Currently in the last commit: 4059a2c9
Executing this script to install everything needed in linux system:
```bash docs/linux_install_full.sh```
It has the following error:
```
+++ google-chrome --version
++ echo Google Chrome 124.0.6367.118
+ chromeVersion=124.0.6367.118
+ sudo rm -rf chromedriver_linux64.zip chromedriver LICENSE.chromedriver
+ sudo wget https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.118/linux64/chromedriver-linux64.zip
--2024-05-06 13:16:55--  https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.118/linux64/chromedriver-linux64.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.184.187, 142.250.185.27, 142.250.201.91, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.184.187|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-06 13:16:55 ERROR 404: Not Found.
```
As you can see this URL does not exist:
```https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.118/linux64/chromedriver-linux64.zip```

**Comment by pseudotensor** [comment]
Hi, it should be fixed now.  Google hasn't uploaded a matching version of chrome driver yet for some reason, so I use the last one for now if that happens to fail.

It was actually already updated in the repo, but not on s3.  And it happens that linux_install_full.sh references the s3 file.

**Comment by aramirezarsys** [comment]
Ok, right now in the las version is working, thanks.
