### ISSUE TITLE
Failed to load models

### ISSUE THREAD

**Issue by ikergar7** [h2oai/h2ogpt#1609]
Currently in the last commit: https://github.com/h2oai/h2ogpt/commit/d806f1fae80500414297841fa1ebbb4c1e4321dd
Executing this script to load a model in a linux system:

TOKENIZERS_PARALLELISM=true python generate.py \
    --base_model=SciPhi/SciPhi-Self-RAG-Mistral-7B-32k --prompt_type=sciphi --use_gpu_id=True --gpu_id=-1 --max_seq_len=8192 \
    --user_path=/opt/myDocuments/arsys.es/html --langchain_mode='UserData' --max_quality=True \
    --add_chat_history_to_context=True --keep_sources_in_context=True --enable_ocr=True --enable_doctr=True \
    --answer_with_sources=True --show_link_in_sources=True --append_sources_to_chat=True \
    -–hf_embedding_model="intfloat/multilingual-e5-small" \
    --memory_restriction_level=0 --score_model=None --verbose=True \
    --show_examples=True --compile_model=True \
    --src_lang='Spanish' --tgt_lang='Spanish' \
    --debug=True --concurrency_count=1 \
    --pre_prompt_query='Always answer as helpfully as possible and follow ALL given instructions. Do not speculate or make up information.' \
    --share=True \
    --load_8bit=True

It has the following error:
<img width="492" alt="image" src="https://github.com/h2oai/h2ogpt/assets/113558949/e7afc178-7cfd-4e7f-b584-20203832523e">

**Comment by pseudotensor** [comment]
Hi, the packages were updated.  You'll need to at least:
```
pip install -r reqs_optional/requirements_optional_langchain.txt
```

or re-install the env from scratch is always safe.

**Comment by ikergar7** [comment]
ok, right now just having updated those packages is working
