### ISSUE TITLE
[Question] how model learn data from new document ?

### ISSUE THREAD

**Issue by Ninlawat-Puhu** [h2oai/h2ogpt#1617]
Users can upload any document to the model via portal UI. From my understand, when we have new document, it usually uses third-party llamaindex or Langchain to make index, then, will find similarity with model.

My question:
For this process, how h2ogpt work ?

**Comment by pseudotensor** [comment]
We use chroma, langchain is just thin layer into chroma, but we have many things that langchain does that like filtering etc.
