### ISSUE TITLE
Enchance h2oGPT UI to have librechat like features.

### ISSUE THREAD

**Issue by hemenkapadia** [h2oai/h2ogpt#1626]
Enhancement request coming from a customer for h2oGPT UI

1. Enhance UI to give a more OpenAI-UI-like experience
2. Option to choose/change model in between a chat session without losing context
3. Persistent chat history with the ability to share it using a URL
4. Admin capability to monitor usage / chats etc
5. Integration with OIDC for authentication

They suggested Librechat https://www.librechat.ai/ meets their requirements and want something similar natively in the platform. 

cc @somanathghalimath @shivam5992 @genrichards

**Comment by hemenkapadia** [comment]
Discussion on the topic at https://h2oai.slack.com/archives/C05MUTAHKU5/p1715925510510869
- Suggest using OpenWebUI over librechat - https://h2oai.slack.com/archives/C05MUTAHKU5/p1715925510510869
- https://openwebui.com/
- https://github.com/open-webui/open-webui

**Comment by pseudotensor** [comment]
h2oGPT backend can be used for Open Web UI:

https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#open-web-ui
