### ISSUE TITLE
Q and A not working for Youtube 

### ISSUE THREAD

**Issue by anushaharish538** [h2oai/h2ogpt#1643]
Hi,

when I add YouTube video url and click on ingest it says docs:1 chunks:3, but when I ask any question about the video its connecting to internet and giving answer. It's working fine for pdf.

Regards,
Anusha

**Comment by pseudotensor** [comment]
Review the document viewer and what is in the database.  Nominally for youtube video, will get both 10 frames + audio transcription.

What does the console say when you upload a video?  It should show lots of details if you ran in --verbose mode.

**Comment by anushaharish538** [comment]
@pseudotensor  Thank you for the reply. I'm using CPU. will  the YouTube chat works with CPU?

**Comment by pseudotensor** [comment]
Try setting `--asr_gpu=False`

**Comment by anushaharish538** [comment]
@pseudotensor I think its issue with database . can you please confirm. I'm getting  python src/make_db.pyExceptions: 0/0 []Traceback (most recent call last):  File "/home/anushaharish538/as/h2ogpt/src/make_db.py", line 403, in <module>
    H2O_Fire(make_db_main)
  File "/home/anushaharish538/as/h2ogpt/src/utils.py", line 73, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/home/anushaharish538/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/anushaharish538/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/anushaharish538/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/anushaharish538/as/h2ogpt/src/make_db.py", line 389, in make_db_main
    assert len(sources) > 0 or not fail_if_no_sources, "No sources found"
AssertionError: No sources found

It's issue with only YouTube . Pdfs working good

**Comment by anushaharish538** [comment]
@pseudotensor  can you please tell me , will the YouTube chat works with CPU?

Thank you.

**Comment by pseudotensor** [comment]
asr_gpu -> False already if no GPUs, so it's not that.
