### ISSUE TITLE
sentence transformer version

### ISSUE THREAD

**Issue by chengchu88** [h2oai/h2ogpt#1644]
Hello all,
Just wondering, is newer sentence transformer (2.3.0 or newer) compatible with the current h2ogpt? I upgraded it since I need to try out a new embedding model, "Salesforce/SFR-Embedding-Mistral". But afterwards gen.py and make_db.py got issue with hkunlp embedding model.
thanks,
C

**Comment by pseudotensor** [comment]
There's some things in langchain etc. that required <2.3.0 so we  have:
```
reqs_optional/requirements_optional_langchain.txt:sentence_transformers>=2.2.2,<2.3.0
```

**Comment by chengchu88** [comment]
Thank you!
