### ISSUE TITLE
Logging/Saving Settings and Instructions for Inference Jobs

### ISSUE THREAD

**Issue by mohammedouhibi** [h2oai/h2ogpt#1646]
There needs to be a way to log or save all settings and instructions provided for every inference job that the vLLM inference server receives. This would be useful for debugging purposes, as it would allow us to track and analyze the input data and configurations used for each job.

Proposed solution :

Implement a logging mechanism that captures and stores the following information for each inference job:
   - Model parameters (e.g., model name, version, quantization settings)
   - Input data (e.g., prompt, context, or other input files)
   - Inference settings (e.g., temperature, top-k, top-p, number of tokens, etc.)
   - Timestamp and other relevant metadata

**Comment by pseudotensor** [comment]
Alot of information is stored in the save directory in history.json for every inference job.  It has everything you mentioned, except not perhaps as much detail -- e.g.no input files, but just whether there are input files.

In addition, vLLM or TGI can also change its logging.

**Comment by pseudotensor** [comment]
Hi, the API call and history.json does contain 'save_dict['sources']` as the list of sources used.

**Comment by mohammedouhibi** [comment]
I see, thanks!
