### ISSUE TITLE
Youtube ingestion doesn't work

### ISSUE THREAD

**Issue by anushaharish538** [h2oai/h2ogpt#1648]
Hi,
Youtube ingestion doesn't work .Its converting to audio but 3).
[download] Destination: /tmp/gradio/6ce6b3f2-2e2a-4a1f-81e8-a58785d61295/What Is LangChain？ - LangChain + ChatGPT Overview.m4a
[download] 100% of    5.92MiB in 00:00:00 at 39.03MiB/s
[FixupM4a] Correcting container of "/tmp/gradio/6ce6b3f2-2e2a-4a1f-81e8-a58785d61295/What Is LangChain？ - LangChain + ChatGPT Overview.m4a"
[ExtractAudio] Not converting audio /tmp/gradio/6ce6b3f2-2e2a-4a1f-81e8-a58785d61295/What Is LangChain？ - LangChain + ChatGPT Overview.m4a; file is already in target format m4a
Transcribing part /tmp/gradio/6ce6b3f2-2e2a-4a1f-81e8-a58785d61295/What Is LangChain？ - LangChain + ChatGPT Overview.m4a!
Due to a bug fix in https://github.com/huggingface/transformers/pull/28687 transcription using a multilingual Whisper will default to language detection followed by transcription instead of translation to English.This might be a breaking change for your use case. If you want to instead always translate your audio to English, make sure to pass `language='en'`.

Taking long run and killing automatically after sometime.

@pseudotensor I think its issue with database . can you please confirm. I'm getting python src/make_db.pyExceptions: 0/0 []Traceback (most recent call last): File "/home/anushaharish538/as/h2ogpt/src/make_db.py", line 403, in
H2O_Fire(make_db_main)
File "/home/anushaharish538/as/h2ogpt/src/utils.py", line 73, in H2O_Fire
fire.Fire(component=component, command=args)
File "/home/anushaharish538/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
component_trace = _Fire(component, args, parsed_flag_args, context, name)
File "/home/anushaharish538/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
component, remaining_args = _CallAndUpdateTrace(
File "/home/anushaharish538/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
component = fn(*varargs, **kwargs)
File "/home/anushaharish538/as/h2ogpt/src/make_db.py", line 389, in make_db_main
assert len(sources) > 0 or not fail_if_no_sources, "No sources found"
AssertionError: No sources found

It's issue with only YouTube . Pdfs working good

**Comment by pseudotensor** [comment]
I fixed CPU mode: https://github.com/h2oai/h2ogpt/issues/1643

However, yes, CPU ASR is very very slow.  I tried same video as you used in CPU vs. GPU, and CPU ASR goes for a while on my i9 8 core system.

So I don't think ASR is good on CPU.

**Comment by pseudotensor** [comment]
Seems to be stuck in DocTR for me.

I should disable DocTR if have CPU mode.

**Comment by pseudotensor** [comment]
![Uploading image.png…]()


should work now, not hang at least.
