### ISSUE TITLE
Document Content Presentation Difference Between Built-In UI and Custom UI using Gradio client

### ISSUE THREAD

**Issue by mohammedouhibi** [h2oai/h2ogpt#1653]
When querying from the h2oGPT built-in UI, document content is presented in a clean format, for example:

content: "This is the document content."

However, when querying using my custom UI using a Gradio client, the document content is presented with additional metadata, for example:

content : "Begin Document:

Metadata:
chunk_id = 4
date = 2024-03-13 13:01:30.138822
input_type = .docx
source = user_path/File.docx

Document Contents:
"""
This is the document content.

"""
End Document
"

The presence of this additional metadata seems to be causing the language model to behave differently, potentially leading to suboptimal performance.

Requested Change:

Provide an option or configuration setting to control the presentation format of the document content. This would allow users to choose between the clean format (as seen in the built-in UI) or the format with metadata (as seen in the custom UI). Alternatively, provide a way to remove or exclude the metadata when presenting the document content to the language model.

Steps to Reproduce:
1. Run the h2oGPT built-in UI and query with a document.
2. Run the same query with a Gradio client set to your h2oGPT URL.
3. Observe the difference in the content presentation format and the language model's behavior in your history.json file under "sources.content" . (make sure to include "--save_dir=your_save_folder_name" in your startup arguments or h2o will not generate a history.json file)

**Comment by pseudotensor** [comment]
If you have issues with the metadata, you can pass to CLI `--metadata_in_context='None'`
