### ISSUE TITLE
Change AutoGPT Agent Embeddings Model

### ISSUE THREAD

**Issue by rohitnanda1443** [h2oai/h2ogpt#1656]
Hi how can we change the autogpt agent's embeddings model in /src
/gpt_langchain.py file line 7456 to Hf_Embeddings ?

**Comment by pseudotensor** [comment]
Ya, I should make that easier.  Will look soon.  I think just:
```
diff --git a/src/gpt_langchain.py b/src/gpt_langchain.py
index 23b52fa5..e4845786 100644
--- a/src/gpt_langchain.py
+++ b/src/gpt_langchain.py
@@ -7861,11 +7861,14 @@ def get_chain(query=None,
             tools.extend([sympy_tool])
 
         from langchain_community.docstore import InMemoryDocstore
-        from langchain_community.embeddings import OpenAIEmbeddings
         from langchain_community.vectorstores import FAISS
 
         # Define your embedding model
-        embeddings_model = OpenAIEmbeddings()
+        if use_openai_embedding:
+            from langchain_community.embeddings import OpenAIEmbeddings
+            embeddings_model = OpenAIEmbeddings()
+        else:
+            embeddings_model = get_embedding(use_openai_embedding, hf_embedding_model=hf_embedding_model)
         # Initialize the vectorstore as empty
         import faiss
```

**Comment by pseudotensor** [comment]
I fixed it, but I see that AutoGPT plugin is even more unstable than usual.  Can't even do 2+2

**Comment by rohitnanda1443** [comment]
File "/root/h2ogpt/generate.py", line 20, in <module>
    entrypoint_main()
  File "/root/h2ogpt/generate.py", line 16, in entrypoint_main
    H2O_Fire(main)
  File "/root/h2ogpt/src/utils.py", line 73, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/h2ogpt/src/gen.py", line 1947, in main
    from src.gpt_langchain import get_embedding
  File "/root/h2ogpt/src/gpt_langchain.py", line 67, in <module>
    from utils import wrapped_partial, EThread, import_matplotlib, sanitize_filename, makedirs, get_url, flatten_list, \
ImportError: cannot import name 'AsyncNullContext' from 'utils' (/root/h2ogpt/src/utils.py)

**Comment by pseudotensor** [comment]
Not sure, maybe you are in wrong directory.  It shouldn't fail like that and doesn't for me.

**Comment by rohitnanda1443** [comment]
Run Script in the root directory of H2oGPT:
python generate.py --auth_access=closed --auth=auth.json --guest_name='' --base_model=mistralai/Mixtral-8x7B-Instruct-v0.1 --max_seq_len=16384  --pre_load_embedding_model=True --enable_tts=False --enable_stt=False --enable_transcriptions=False --extra_allowed_paths=["Ai_test_data"] --use_gpu_id=False
