### ISSUE TITLE
Question:extracting preference data of clients' response

### ISSUE THREAD

**Issue by chengchu88** [h2oai/h2ogpt#1657]
Hello all,
I got a question regarding the 'thumb up'/'thumb down' feedback of the LLM response. Is there a way to accumulate/collect the Q&A pairs and the response in the backend? I looked at gen.py parameters but it is not obvious to me how to set it up, if possible.
Thank you,

**Comment by pseudotensor** [comment]
`--visible_ratings=True` .  Then you can specify the file `--reviews_file=reviews.csv` or it will be called that by default.

You can also allow a rating with `--visible_ratings=True`

**Comment by pseudotensor** [comment]
But regardless of `visible_ratings` being set, the up-down stuff goes to reviews.csv type file.

**Comment by chengchu88** [comment]
Thank you sir for the quick reply, appreciate your help!
