### ISSUE TITLE
tab visibility flag like --visible_system_tab=False not working

### ISSUE THREAD

**Issue by chengchu88** [h2oai/h2ogpt#1682]
Hello, 
Got a question regarding gradio appearance control.. I set --visible_system_tab=False at python generate.py for model lock mode but it doesn't seem to have the desired effect, I can still see the system tab, and this is true for all other similar tab visibility control flag when I set them = False. Did I miss anything? I'd like to have an interface with only the chat tab (or the bare minimum).
Thank you,

**Comment by pseudotensor** [comment]
Not sure.  Every case works for me.  Maybe you had typo?

For:
```
python generate.py --base_model=llama
```

![image](https://github.com/h2oai/h2ogpt/assets/2249614/4265224e-11e5-4717-8273-f3ff2a613437)

For:
```
python generate.py --base_model=llama --visible_system_tab=False
```

![image](https://github.com/h2oai/h2ogpt/assets/2249614/7ba3bffa-06ac-4335-a54a-072ae78eba12)

For:
```
(h2ogpt) jon@pseudotensor:~/h2ogpt$ python generate.py --model_lock="[{'base_model': 'llama', 'model_path_llama': 'Phi-3-mini-4k-instruct-q4.gguf', 'tokenizer_base_model': 'microsoft/Phi-3-mini-4k-instruct'}]"
```

For model lock case:

```
python generate.py --model_lock="[{'base_model': 'llama', 'model_path_llama': 'Phi-3-mini-4k-instruct-q4.gguf', 'tokenizer_base_model': 'microsoft/Phi-3-mini-4k-instruct'}]"
```

![image](https://github.com/h2oai/h2ogpt/assets/2249614/03abfa88-ccda-46d4-9ca8-294988f9b578)


```
python generate.py --model_lock="[{'base_model': 'llama', 'model_path_llama': 'Phi-3-mini-4k-instruct-q4.gguf', 'tokenizer_base_model': 'microsoft/Phi-3-mini-4k-instruct'}]" --visible_system_tab=False
```

![image](https://github.com/h2oai/h2ogpt/assets/2249614/746c0d18-927c-4eec-a910-221152ecbd5e)

**Comment by pseudotensor** [comment]
From https://github.com/h2oai/h2ogpt/blob/main/docs/README_ui.md#sidebar-submit-buttons-and-tab-control


One can do:
```
(h2ogpt) jon@pseudotensor:~/h2ogpt$ python generate.py --model_lock="[{'base_model': 'llama', 'model_path_llama': 'Phi-3-mini-4k-instruct-q4.gguf', 'tokenizer_base_model': 'microsoft/Phi-3-mini-4k-instruct'}]" --use_auth_token=$HUGGING_FACE_HUB_TOKEN --visible_submit_buttons=False --visible_side_bar=False --visible_submit_buttons=False --visible_side_bar=False --visible_chat_tab=False --visible_doc_selection_tab=False --visible_doc_view_tab=False --visible_chat_history_tab=False --visible_expert_tab=False --visible_models_tab=False --visible_system_tab=False --visible_tos_tab=False --visible_hosts_tab=False --chat_tabless=True  --visible_login_tab=False --visible_h2ogpt_logo=False --visible_h2ogpt_links=False --visible_h2ogpt_qrcode=False
```

That removes everything, e.g. if one doesn't want any UI control, only API.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/2565925b-2246-4508-9859-2e78ec5d264e)

**Comment by pseudotensor** [comment]
commit 0c0a5c7648c203f578a28a05b9b7761619334294 (HEAD -> main, origin/main, origin/HEAD)
Author: Jonathan C. McKinney <pseudotensor@gmail.com>
Date:   Wed Jun 12 23:16:51 2024 -0700

    Control more

commit 14ae688c2e44ac1062fe7cf70b4d97a41fa45f0a
Author: Jonathan C. McKinney <pseudotensor@gmail.com>
Date:   Wed Jun 12 23:10:09 2024 -0700

    Note

commit c666d21f109085f911784e218df22b56e0ac5747
Author: Jonathan C. McKinney <pseudotensor@gmail.com>
Date:   Wed Jun 12 23:08:02 2024 -0700

    Fix tabless case

**Comment by chengchu88** [comment]
Hello Sir, thank you for the quick reply. 

Here is what i tried and results:

root@b707bdcc6014:~# HF_DATABASE_OFFLINE=1 GRADIO_SERVER_PORT=7865 python generate.py  --visible_submit_buttons=False --visible_side_bar=False --visible_submit_buttons=False --visible_side_bar=False --visible_chat_tab=True --visible_doc_selection_tab=False --visible_doc_view_tab=False --visible_chat_history_tab=False --visible_expert_tab=False --visible_models_tab=False --visible_system_tab=False --visible_tos_tab=False --visible_hosts_tab=False --chat_tables=True  --visible_login_tab=False --visible_h2ogpt_logo=False --visible_h2ogpt_links=False --visible_h2ogpt_qrcode=False
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
load INSTRUCTOR_Transformer
max_seq_length  512
/workspace/gradio_utils/prompt_form.py:225: GradioUnusedKwargWarning: You have unused kwarg parameters in Chatbot, please remove them: {'likeable': True}
  text_output = gr.Chatbot(label=output_label0,
/workspace/gradio_utils/prompt_form.py:230: GradioUnusedKwargWarning: You have unused kwarg parameters in Chatbot, please remove them: {'likeable': True}
  text_output2 = gr.Chatbot(label=output_label0_model2,
Running on local URL:  http://0.0.0.0:7865

To create a public link, set `share=True` in `launch()`.
Started Gradio Server and/or GUI: server_name: localhost port: 7865
Use local URL: http://localhost:7865/
/h2ogpt_conda/envs/h2ogpt/lib/python3.10/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/h2ogpt_conda/envs/h2ogpt/lib/python3.10/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_names" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
OpenAI API URL: http://0.0.0.0:5000
INFO:__name__:OpenAI API URL: http://0.0.0.0:5000
OpenAI API key: EMPTY
INFO:__name__:OpenAI API key: EMPTY
[Errno 98] error while attempting to bind on address ('0.0.0.0', 5000): address already in use

And here is the screenshot:

![image](https://github.com/h2oai/h2ogpt/assets/39104888/53a6b7a7-12ef-47bd-9925-663123b4be20)

Two observations:
1. I can remove/hide everything else (side bar, QR code..) but all the tabs still present.
2. I think my code is of a different version than yours. I checked the version.txt and it is 0.2.0, and it is the  "latest version" that I downloaded around May 10, since this is the version that works well with Llama 3.
3. As you can see, I got a lot more tabs compared to your screenshot (ToS, Image Control, etc.)

Any idea? I will try out 0.2.1 to see if this is can be fixed.

Again, thank you very much for your time and support on this matter.

Best,,

**Comment by pseudotensor** [comment]
I think you may be using a gradio3 build perhaps, which didn't support tab removal.  In the past, 0.2.0 versions for docker might have come as gradio3 or gradio4, but now they are all gradio4.

**Comment by chengchu88** [comment]
I see. I just checked my version, it is gradio 3.50.2. Maybe this is the
issue.
Thank you very much again for your help!

**Comment by chengchu88** [comment]
I upgrade the gradio and now I can control the tab on/off. thanks!
