### ISSUE TITLE
can't add personal data db/collection to auth.json

### ISSUE THREAD

**Issue by rxng** [h2oai/h2ogpt#1684]
According to the instructions, we can add a make_db.py database to auth.json , but does not specify exactly how to do this. 
```
To make a new one for the user, fill `user_path_jon` with documents (can be soft or hard linked to avoid dups across multiple users), do:
```bash
python src/make_db.py --user_path=gptdocsdb/jon--collection_name=JonData --langchain_type=personal --hf_embedding_model=hkunlp/instructor-large --persist_directory=users/jon/db_dir_JonData
```

Then you'll have:
```text
(h2ogpt) jon@pseudotensor:~/h2ogpt$ ls -alrt users/jon/db_dir_JonData/
total 264
drwx------ 13 jon jon   4096 Apr 16 12:28 ../
drwx------  2 jon jon   4096 Apr 16 12:28 d7ccacb6-93fe-4380-9340-b7f5edffb655/
-rw-------  1 jon jon 249856 Apr 16 12:28 chroma.sqlite3
-rw-------  1 jon jon     41 Apr 16 12:28 embed_info
drwx------  3 jon jon   4096 Apr 16 12:28 ./
```

You can add that database to the `auth.json` for their entry if using `auth.json` type file, and they will see when they login.
```

h2ogpt is being run like so and everything works well except it does not load the correct collection for the user 
`python generate.py --base_model=mistral-7b-instruct-v0.2.Q8_0.gguf --score_model=None --prompt_type=instruct --auth_access=closed --auth=auth.json --guest_name='' --auth_freeze`

I have tried the following by adding db parameters but it does not work. 
```
{
  "jon": {
    "password": "jon1306",
    "userid": "acb8fef1a77d122b5e12b261202ada7a",
    "selection_docs_state": {
      "langchain_modes": [
        "JonData",
        "LLM",
        "Disabled"
      ],
      "langchain_mode_types": {
        "JonData": "personal"
      }
    },
    "dbs": "users/jon/db_dir_JonData",
    "load_db_if_exists": "users/jon/db_dir_JonData"
  }
}
```

How do we make it such that when user logs in, their  collection JonData is automatically added? 
Or, Any way to simply specify a per user user_path? that would be easiest.

**Comment by pseudotensor** [comment]
Hi, did you try the CLI options?

https://github.com/h2oai/h2ogpt/blob/main/docs/README_LangChain.md#multiple-embeddings-and-sources

i.e.

```
python generate.py --model_lock="[{'base_model': 'llama', 'model_path_llama': 'Phi-3-mini-4k-instruct-q4.gguf', 'tokenizer_base_model': 'microsoft/Phi-3-mini-4k-instruct'}]" --use_auth_token=$HUGGING_FACE_HUB_TOKEN --langchain_modes="['UserData', 'MyData', 'UserData2']"
```

Would show all users those 2 by default.

Even if a user logs in that already had a db entry, they will be forced to see those CLI ones.

If the system is online, there's currently no way to add to all users at once with e.g. some kind of global user added settings.  Is that what you are trying to achieve?

**Comment by pseudotensor** [comment]
For personal collections, there's no CLI options for that, it's only in the db/json file.  By default sqlite3 db is used in newer h2oGPT to address speed issues with json, so one would have to edit the db using operations like in the src/db_utils.py.

I'll think about how to handle this better, probably adding an option to add things via the admin page is best.  Would that work for you?

**Comment by rxng** [comment]
thanks for your quick response! Maybe I was confusing in my explanation. I was trying to achieve having a user logging in and then their own collection would be automatically loaded for them.

However, I tried every single parameter and just found a way to do it via the auth.json file, by adding the line 
`"langchain_mode": "JonData",` above the selection_docs_state entry, like so
```
"langchain_mode": "JonData",
    "selection_docs_state": {
```

The only question I have is, if we wanted to then add more documents to the collection via make_db.py , would we then have to restart the entire instance of h2ogpt to automatically use the updated collection?

It would definitely be great if there was an admin page where these things could easily be managed :)

**Comment by pseudotensor** [comment]
![image](https://github.com/h2oai/h2ogpt/assets/2249614/3d01dd56-6096-4912-81df-4958be59cfb6)


![image](https://github.com/h2oai/h2ogpt/assets/2249614/eb697291-b422-4df7-858c-95823892e4d7)

![image](https://github.com/h2oai/h2ogpt/assets/2249614/99dd9371-2758-434c-a671-d97d64b8926a)


![image](https://github.com/h2oai/h2ogpt/assets/2249614/815ecc52-c030-4236-a2aa-c4d2ccd05eca)

**Comment by rxng** [comment]
> ![image](https://private-user-images.githubusercontent.com/2249614/344014499-3d01dd56-6096-4912-81df-4958be59cfb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NDY4NjMsIm5iZiI6MTcxOTU0NjU2MywicGF0aCI6Ii8yMjQ5NjE0LzM0NDAxNDQ5OS0zZDAxZGQ1Ni02MDk2LTQ5MTItODFkZi00OTU4YmU1OWNmYjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMDM0OTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2E4YWI2NmY1NmJmNTllMzZiMGIxNzM5YTlkZjNhNzg5ODkzZjFiYmY2NWJjZTczZjU4MTNhMDRiNDg1OTNmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VovhZ0UFqrbLX5V641O87RZjzXpbp0Xpx5ZOmvjgwLI)
> 
> ![image](https://private-user-images.githubusercontent.com/2249614/344014591-eb697291-b422-4df7-858c-95823892e4d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NDY4NjMsIm5iZiI6MTcxOTU0NjU2MywicGF0aCI6Ii8yMjQ5NjE0LzM0NDAxNDU5MS1lYjY5NzI5MS1iNDIyLTRkZjctODU4Yy05NTgyMzg5MmU0ZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMDM0OTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmY0MjhkODJkYTllMDBmMDljMWExNjI0YmNiNjFlZGQ3NjE3YmRhODM0ODBlNmQwZmE4YjM2NjBlMjA1NDMwYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xhcqegxl8d6SrdBCi0jmNuOwXU0IHoE8Um7gEL7g7kA)
> 
> ![image](https://private-user-images.githubusercontent.com/2249614/344014659-99dd9371-2758-434c-a671-d97d64b8926a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NDY4NjMsIm5iZiI6MTcxOTU0NjU2MywicGF0aCI6Ii8yMjQ5NjE0LzM0NDAxNDY1OS05OWRkOTM3MS0yNzU4LTQzNGMtYTY3MS1kOTdkNjRiODkyNmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMDM0OTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmQyYmU4NjQ4MWVhYWUzMjYxYzM2MDcyN2FkZjhkMGU2ZjgyMTAzZWIxMDdmNzk5OTJmNzM4MWJlODRjNmUyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0jIwwX_hfgUqEdeVGKvpExcZiELLeG008tTtox_gAW0)
> 
> ![image](https://private-user-images.githubusercontent.com/2249614/344014739-815ecc52-c030-4236-a2aa-c4d2ccd05eca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NDY4NjMsIm5iZiI6MTcxOTU0NjU2MywicGF0aCI6Ii8yMjQ5NjE0LzM0NDAxNDczOS04MTVlY2M1Mi1jMDMwLTQyMzYtYTJhYS1jNGQyY2NkMDVlY2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMDM0OTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGUzMmVmMDczYTRmNTc5NTczNmYzN2Y3MjdjNmJmYjljODc1ZDk1Nzg1NDI2ZmFjZmNjZmQ1YWJjOTVkZTBlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Lye91otTrAkFdHY5OqMrLP1tDbpyk3xzAIdDBj1k_xs)

that's so amazing @pseudotensor !!

**Comment by pseudotensor** [comment]
Note that if you have an auth file that is .json, just pass to CLI that it is now .db and we'll migrate it to .db format that is required for this control

https://github.com/h2oai/h2ogpt/blob/3498b03fcd814458cea7e319039c42df48b1231a/src/db_utils.py#L80-L101
