### ISSUE TITLE
h2ogpt tries to download model from hugging face when using local inference server

### ISSUE THREAD

**Issue by hapatrick** [h2oai/h2ogpt#1686]
I am trying to follow the instructions at https://github.com/h2oai/h2ogpt/blob/main/docs/README_InferenceServers.md to run h2ogpt with a local inference server -- specifically, vLLM serving Mixtral8x22B using the OpenAI API.

When I run generate.py, it tries to download the mixtral model from HuggingFace. My understanding is it should not need to do this because it's going to be using the model served by my inference server!

Here is the command I'm trying to use:
python3.10 /workspace/generate.py --inference_server="vllm:http://vllm-mixtral8x22b:8000/v1/" --prompt_type=openai --base_model=mixtral

What am I doing wrong here?

**Comment by srimanreddy4** [comment]
I have done it recently with mixtral, it worked for me, compared to my command, in the base command I mentioned the whole model name that I was using, I have looked up the documentation, they did the same too, why don't you try that out once

**Comment by pseudotensor** [comment]
@hapatrick It should only be downloading the tokenizer, not the whole model.  You should use "vllm_chat" instead of "vllm" for the inference_server prefix and then avoid passing --prompt_type.  prompt_type openai will use no LLM prompting with vllm's text generation API and not work right.
