### ISSUE TITLE
ModuleNotFoundError: No module named 'tenacity.asyncio'

### ISSUE THREAD

**Issue by machinelearning2014** [h2oai/h2ogpt#1688]
I followed all of the installation and running below

HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 python generate.py --base_model=mistral-7b-instruct-v0.2.Q2_K.gguf --prompt_type=mistral --max_seq_len=512 --cli=True

get an error:

File "/home/letro/.conda/envs/h2ogpt_env/lib/python3.10/site-packages/tenacity/__init__.py", line 653, in <module>
    from tenacity.asyncio import AsyncRetrying  # noqa:E402,I100
ModuleNotFoundError: No module named 'tenacity.asyncio'

**Comment by pseudotensor** [comment]
Seeing same thing in docker image:
```
h2ogpt-1  | ModuleNotFoundError: No module named 'tenacity.asyncio'

```

**Comment by pseudotensor** [comment]
https://github.com/langchain-ai/langchain/issues/22972

**Comment by pseudotensor** [comment]
```
pip install tenacity==8.3.0 --upgrade
```

**Comment by machinelearning2014** [comment]
Thanks for looking into, seems the workaround is to install tenacity==8.3.0 , the bug is in tenacity>=8.4.0
https://github.com/langchain-ai/langchain/issues/22972#issuecomment-2172865393
