### ISSUE TITLE
Can we query Qdrant directly without needing sources?

### ISSUE THREAD

**Issue by andrewyuau** [h2oai/h2ogpt#1692]
I followed [instructions](https://github.com/h2oai/h2ogpt/blob/main/docs/README_LangChain.md#using-qdrant) to spin up Qdrant using Docker and passed the QDRANT_URL and QDRANT_API_KEY. 

I'm trying to get h2ogpt to query Qdrant directly by not having any files in /workspace/user_path and deleting the directory /workspace/db_dir_UserData. However, I am getting an error message "Did not generate db for UserData since no sources" which originates from line 6258 in [gpt_langchain.py](https://github.com/h2oai/h2ogpt/blob/main/src/gpt_langchain.py). 

Is it possible to use my own Qdrant without needing sources?

**Comment by andrewyuau** [comment]
My current workaround is to have one entry in /workspace/user_path and h2ogpt automatically adds that entry into my Qdrant DB. I then delete that entry manually from Qdrant DB and then h2ogpt can query the rest of the entries in my own Qdrant DB.

**Comment by pseudotensor** [comment]
@Anush008 may be able to help.

**Comment by Anush008** [comment]
Hey @andrewyuau, from the codebase, I see it should only be a log message and not an error. You should probably be able to continue to using it.

**Comment by andrewyuau** [comment]
The workaround works for me so I will close this, thank you.
