### ISSUE TITLE
extra fields not permitted (type=value_error.extra)

### ISSUE THREAD

**Issue by peterchanws** [h2oai/h2ogpt#170]
Got the following in terminal after enter a chat:

File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for H2OGPT4All
context_erase
  extra fields not permitted (type=value_error.extra)

macOS 12.6.6; Intel Xeon E5

**Comment by pseudotensor** [comment]
Hi, be sure you are using the version of gpt4all we specify in instructions, i.e.:
```
pip install -r requirements_optional_gpt4all.txt
```
with `gpt4all==0.2.3`.

As well as the langchain dependency specified when doing:
```
pip install -r requirements_optional_langchain.txt
```
with `langchain==0.0.178`

Any other version might not have that parameter.

The validation check failure you shared means that langchain version is probably wrong.  i.e. that 0.0.178 has this in code `/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/langchain/llms/gpt4all.py` :+1: 

```

    context_erase: float = 0.5
    """Leave (n_ctx * context_erase) tokens
    starting from beginning if the context has run out."""

    client: Any = None  #: :meta private:

    class Config:
        """Configuration for this pydantic object."""

        extra = Extra.forbid

    @staticmethod
    def _model_param_names() -> Set[str]:
        return {
            "n_ctx",
            "n_predict",
            "top_k",
            "top_p",
            "temp",
            "n_batch",
            "repeat_penalty",
            "repeat_last_n",
            "context_erase",
        }
```

So "context_erase" is there and validation cannot fail.

@NidhiMehta have you seen any issue like this on your recent mac install?

**Comment by peterchanws** [comment]
Thanks for the quick reply. It works!!!!
