### ISSUE TITLE
Use auto ingest with openai Api 

### ISSUE THREAD

**Issue by rmisire** [h2oai/h2ogpt#1705]
I would like to know if it is possible to automatically ingest files in a specific collection without going through the ui. After several searches I found nothing in the documentation. I looked at http://localhost:5001/ but nothing conclusive

Thank you for your feedback

**Comment by pseudotensor** [comment]
The gradio API is extensive and it can be done that way yes.  An example test is the `test_client_chat_stream_langchain_steps3` test.

For openai I need to to this issue:


https://github.com/h2oai/h2ogpt/issues/1563#issuecomment-2081301661
