### ISSUE TITLE
Changing response_format affects system context?

### ISSUE THREAD

**Issue by vanboom** [h2oai/h2ogpt#1718]
I am not 100% sure how to express this issue but I have found a strange behavior after some testing attempts to get a JSON output using `response_format='json_object'` or `json_code`.   I am querying the model using the API.   I set up this simple example during testing to help explore the issue.

The goal:  give the model some context in the `system` message and then ask some questions. 
**The issue:**  The model does not consider the given context if `response_format=json_object` is configured as an ARG

```
python generate.py --base_model=TheBloke/zephyr-7B-beta-GGUF --langchain_mode=LLM --response_format=json_object
```

### Test 1 - working context
```
python generate.py --base_model=TheBloke/zephyr-7B-beta-GGUF --langchain_mode=LLM
```

```
[
    [0] {
           :role => "system",
        :content => "      Reference the following context to answer questions:\n      *****\n      Kitty likes BBQ and golf.\n      *****\n"
    },
    [1] {
           :role => "user",
        :content => "      What does Kitty like?  Explain your answer.\n"
    }
]


"Kitty likes BBQ and golf, as stated in the given context. BBQ refers to barbecue, which is a method of cooking food slowly over low heat, usually involving smoking. Golf is a sport that involves hitting a small ball into a series of holes using a variety of clubs. Therefore, Kitty has a preference for both BBQ and golf."
```

### Test 2 - hallucinated answer with no consideration of the context

```
python generate.py --base_model=TheBloke/zephyr-7B-beta-GGUF --langchain_mode=LLM --response_format=json_object
```

```
[
    [0] {
           :role => "system",
        :content => "      Reference the following context to answer questions:\n      *****\n      Kitty likes BBQ and golf.\n      *****\n"
    },
    [1] {
           :role => "user",
        :content => "      What does Kitty like?  Explain your answer.\n"
    }
]

RESPONSE:  "{\"Kitty\": {\"likes\": [\"catnip\", \"laser pointers\", \"playtime\", \"treats\", \"cuddles\"]}}"

```

In the web app, it works perfectly even with `--response_format='json_code'` enabled on the command line. 
![image](https://github.com/h2oai/h2ogpt/assets/251706/88a7de7a-633b-4b1a-a244-b6112bc338bf)

Any ideas why the API would behave this way differently from the Gradio app?  I am not sure how to set `response_format` to JSON in the API calls so possibly there is a method that would work at that level.  Thanks!!

**Comment by pseudotensor** [comment]
Hi, we purposefully nuke the system_prompt when doing json mode.

https://github.com/h2oai/h2ogpt/blob/6d514a1b9d498f714fd3f06570a816ac169ad962/src/gen.py#L2930

As the comment says, we have seen issues with it messing up even normal models, if the system_prompt contains conflicting persona relative to JSON making.

But you can comment-out that line.

**Comment by pseudotensor** [comment]
I think even better than commenting out that line is to pass your lines of information as `text_context_list` list that would be considered same as if it were a document being referenced.

**Comment by pseudotensor** [comment]
As yet another alternative, if you need to input instructions, just change these prompts via API:

```
            "json_object_prompt",
            "json_object_prompt_simpler",
            "json_code_prompt",
            "json_code_prompt_if_no_schema",
            "json_schema_instruction",

```

**Comment by vanboom** [comment]
> Hi, we purposefully nuke the system_prompt when doing json mode.
> 
> https://github.com/h2oai/h2ogpt/blob/6d514a1b9d498f714fd3f06570a816ac169ad962/src/gen.py#L2930
> 
> As the comment says, we have seen issues with it messing up even normal models, if the system_prompt contains conflicting persona relative to JSON making.
> 
> But you can comment-out that line.

Thanks!  Will explore further per your suggestions.  Interestingly, setting the response_format to 'text' and requesting JSON yields good results, now curious why the system_prompt would mess things up when `response_format` is set to `json_code` or `json_object`.

**Comment by vanboom** [comment]
Yes setting `text_context_list` instead does appear to work to provide context to the model, however I am getting other failures when the `system_prompt` is cleared such as blank "" answers.  Why not let the user control that regardless of the response format setting?

**Comment by pseudotensor** [comment]
Just trying to lower the number of things one has to change for default case.
