### ISSUE TITLE
Running RAG optimized models (nvidia/Llama3-ChatQA-1.5-70B)

### ISSUE THREAD

**Issue by bw-Deejee** [h2oai/h2ogpt#1734]
Two questions:

1. Do you have any recommendation regarding best models for RAG applications?

2. Is it possible to run docQA optimized models like nvidia/Llama3-ChatQA-1.5-8B,
which seems to have two different promtp formats:

when context is available
```
System: {System}

{Context}

User: {Question}

Assistant: {Response}

User: {Question}

Assistant:
```

when context is not available
```
System: {System}

User: {Question}

Assistant: {Response}

User: {Question}

Assistant:
```

I'd be interested on how to run this properly.
I tested RAG with the normal Llama3 8b and it always mentioned chunk numbers in the response and overall didnt respond very cleanly.

Best regards

**Comment by pseudotensor** [comment]
That model has a chat template in the model HF repo, so it works OOTB.  You don't need to do anything else but something like:

```
python generate.py --base_model=nvidia/Llama3-ChatQA-1.5-8B
```

**Comment by pseudotensor** [comment]
![image](https://github.com/user-attachments/assets/b9c4d5e1-927c-4e6e-a970-776e222b6448)
