### ISSUE TITLE
Running model on multiple GPUs? How to do it? Does h2ogpt allows it do easily?

### ISSUE THREAD

**Issue by martinenkoEduard** [h2oai/h2ogpt#1750]
Running model on multiple GPUs? How to do it?
Can you show simple example?

What are the restrictions? Should be GPUs identical?
Or is it possible for instance to have
one RTX 3070 and one 3080? What about memory sharing?

Do mistal and llama support these features?

Also can you share a rig configuration with multiple GPUs for local LLM deployment?

**Comment by pseudotensor** [comment]
I recommend using vLLM, ollama, etc. as inference servers with h2oGPT to get most benefit if isolation and concurrency.

But you can use GGUF models, which automatically spread to multiple GPUs or however many are set as visible (CUDA_VISIBLE_DEVICES).

For HF models, just set `use_gpu_id=False` to spread it over multiple GPUs.

Lastly, there are many auxiliary models like embedding, TTS, STT, image generation, etc.  Those are controlled with embedding_gpu_id, caption_gpu_id, doctr_gpu_id, asr_gpu_id, stt_gpu_id, tts_gpu_id, image_gpu_ids (for each generation model added).
