### ISSUE TITLE
How to tell if the GPU is actually being used ?

### ISSUE THREAD

**Issue by lelapin123** [h2oai/h2ogpt#177]
The speed of generation that i have is a bit slow, so how can i tell of the software works how it should (and uses CUDA)?

**Comment by pseudotensor** [comment]
Hi, @lelapin123 .  If you are using the h2ogpt hugginface based models and you have a CUDA GPU, they will use GPUs.  You  should see it the usage in nvidia-smi.  Or you can `pip install nvitop` and see if it shows usage graphically over time.

GPT4ALL ones don't use GPUs, but LLaMa.cpp ones can use GPUs in some cases.

**Comment by lelapin123** [comment]
So today, it is much faster, so i guess that it finally uses the gpu.
What changed since yesterday ?
No idea... a reboot, may be
