### ISSUE TITLE
Implement custom function call.

### ISSUE THREAD

**Issue by anushaharish538** [h2oai/h2ogpt#1772]
Hi,

Can you please tell me how to implement custom function calling like. https://platform.openai.com/docs/guides/function-calling

Thank You
Anusha

**Comment by anushaharish538** [comment]
hi @pseudotensor Can you please tell me . Please I'm using open_ai

**Comment by pseudotensor** [comment]
Hi, function calling is now part of h2oGPT OpenAI API, with 'auto' tool_choice, but it's basic at moment.
