### ISSUE TITLE
Chat history silently fails to download

### ISSUE THREAD

**Issue by antoninadert** [h2oai/h2ogpt#1788]
No matter the chat history count, when I click "Exports chats to Download", it gives an empty file of 2.0b

See screenshot

<img width="1108" alt="image" src="https://github.com/user-attachments/assets/0489c5bf-2086-43a2-a35d-1f1941f455ff">

There is no error in the command line. 

Is this a known issue ?

**Comment by pseudotensor** [comment]
It only saves the "chat saved" items after clicking save.  The current chat view isn't saved except in database for the user.

**Comment by pseudotensor** [comment]
![image](https://github.com/user-attachments/assets/91820c73-a27d-4d87-916e-1d818f1a105f)


Make sure to click "save" among buttons to save it so it would be part of download.

I would prefer it saved all things, but the database takes care of saving things for that general purpose.
