### ISSUE TITLE
API Support

### ISSUE THREAD

**Issue by anushaharish538** [h2oai/h2ogpt#1799]
Hi,

Can I chat with files using api by giving file url or website url.

Regards,
Anusha

**Comment by pseudotensor** [comment]
Ya the full gradio-based API exists for uploading, managing, querying docs.  And the openAI API can be used for querying docs.

E.g. https://github.com/h2oai/h2ogpt/blob/e7c04e57b21dd412f4babd10aed8d3a7b686e446/tests/test_client_calls.py#L2972

This test shows many client calls for various tasks that are tested.

**Comment by anushaharish538** [comment]
I need for summarise the docs
