### ISSUE TITLE
a problem downloading GPT4ALL model and others such as faiss-cpu

### ISSUE THREAD

**Issue by leonpierrec** [h2oai/h2ogpt#180]
when installing h2oGPT, I noticed 2 problems:

the first problem:
>> is that when run this command in terminal (command prompt) in h2oGPT folder :
python generate.py --base_model=gptj --score_model=None --langchain_mode=UserData --user_path=user_path
I notice that when downloading the model, the command prompt crashes giving me an error message while closing this prompt unless I launch the terminal for example on visual studio.
Here is the error message (i had to take several screenshots.):
![image](https://github.com/h2oai/h2ogpt/assets/81476485/4d68c739-6ffe-4689-bd23-5982682faf2f)
![image](https://github.com/h2oai/h2ogpt/assets/81476485/be4b4d6c-c3b8-4b8b-863e-21fbaf184b12)
![image](https://github.com/h2oai/h2ogpt/assets/81476485/d1511212-6677-4e90-a741-77c2c535ee01)
![image](https://github.com/h2oai/h2ogpt/assets/81476485/2a9682ff-e1c5-400c-8ffa-71ef6c8a92ae)
It never downloads the whole model and if I replace the incomplete model with the full model, the program, the terminal crashes when I ask a question in the web interface. I imagine that there may still be some prerequisites to install or not.
----------------------------------
The second issue, 
>>which may be related to the first, is that when i run : pip install -r requirements_optional.txt
I get this error message:
![image](https://github.com/h2oai/h2ogpt/assets/81476485/47990b72-0257-4079-bdc5-b3f2349c8688)

>>the same when I run: pip install -r requirements_optional_langchain.txt -c req_constraints.txt
I get this error message:
![image](https://github.com/h2oai/h2ogpt/assets/81476485/15cb7a72-0092-44a6-9e98-7f64758d03ff)
However, I tried to install faires-cpu 1.7.2 via various methods without success. I knew how to install it with conda but I could only have a version above and there fore not desired for this case. 
-----------------------------------
On the other hand, the program works with other much larger models like h2oai/h2oGPT-oig-oasst1-256-6.9b. However, I have a laptop with a 16 GB Ram configuration, an RTX 3060 gpu laptop with 6 GB in Vram and a Ryzen 9. So the concern is that I am looking for a model that uses the least amount of ram or vram that using langchain. For the models I tested on h2oGPT, all of them use all my ram, I know it's already spelled out in the readme.md. I tried installing an alpaca model: 4bit/alpaca-7b-native-4bit , and obviously it didn't work since h2oGPT isn't ready for that yet.

**Comment by leonpierrec** [comment]
After some research and testing I found:
by changing in .env_gpt4all (see below), the model model_path_gptj by another such as ggml-gpt4all-j-v1.2-jazzy.bin.  

>>.env_gpt4all
#model path and model_kwargs
model_path_gptj=ggml-gpt4all-j-v1.2-jazzy.bin

I see that the download bug is "fixed" for some reason that is obscure to me. The program runs to display the localhost. However when I ask a question in the chat, the interface crashes again.
With other models the problem of crashing during download comes up again.

By trying something else like starting it via llama.cpp ,by executing in the command prompt this:
>> python generate.py --base_model=llama --load_8bit=True --langchain_mode=UserData --user_path=user_path

I notice that nothing runs as it should be or I omitted some modification to add but since the README.md is quite poor on the launch via the CPU, I do not really have a solution to solve this recurring problem.

**Comment by TopNotchSushi** [comment]
Have you gotten llama ggml to work? I've tried model_path_llama, and model_type=llama, and get other issues, such as 

`KeyError: 'model_path'`

**Comment by pseudotensor** [comment]
@leonpierrec Sorry you are having trouble.  Regarding requierments files, the `requirements_optional.txt` was only for flash attention that you probably didn't intend to install.  Indeed, yesterday, to avoid possible confusion, I moved that file to a new name and clarified in readme.md which files are required for which purpose:
```
requirements_optional_4bit.txt
requirements_optional_faiss.txt
requirements_optional_flashattention.txt
requirements_optional_gpt4all.txt
requirements_optional_langchain.gpllike.txt
requirements_optional_langchain.txt
requirements_optional_training.txt
requirements_optional_wikiprocessing.txt
requirements.txt
```

These are the only files right now, and I try to be clear in the readme when one should use some file or not.

**Comment by pseudotensor** [comment]
> Have you gotten llama ggml to work? I've tried model_path_llama, and model_type=llama, and get other issues, such as
> 
> `KeyError: 'model_path'`

This is fixed here: https://github.com/h2oai/h2ogpt/pull/197
