### ISSUE TITLE
Please tell me how to summarise local document using local API

### ISSUE THREAD

**Issue by anushaharish538** [h2oai/h2ogpt#1809]
Please tell me how to summarise local document using local API

**Comment by pseudotensor** [comment]
Check out the client code for the tests in tests/test_client_calls.py::test_client_summarization_from_url or test_client_summarization_from_text

It's very simple.

**Comment by pseudotensor** [comment]
There are 3 test codes, the other one is test_client_summarization that takes files like PDFs.  Is that what you want?
