### ISSUE TITLE
Faiss-gpu on windows

### ISSUE THREAD

**Issue by lelapin123** [h2oai/h2ogpt#181]
So i did an installation with a new conda env on windows, i was able to do a basic one (requirements.txt) but when i tried to install requirements_optional_langchain.txt i received an error related to "faiss-gpu==1.7.2".
I saw elsewhere that window is not compatible with faiss-gpu.
So i tried the same thing with linux and this time it worked.

**Comment by lelapin123** [comment]
but can i use the gpu on windows after that ?
Before i modified to faiss-cpu, and by fixing the bugs i saw, i was able to ask the information on a text.
The problem is that it was very slow

**Comment by pseudotensor** [comment]
By default h2oGPT doesn't use FAISS as its database, so it won't have any effect.  So I removed faiss entirely from deps and into optional deps only.
