### ISSUE TITLE
TypeError Can only concatenate str (not "bool") to str

### ISSUE THREAD

**Issue by btriw** [h2oai/h2ogpt#1810]
Hello i tried to connect h2ogpt with gradio so i can get the function from h2opgt, like this:

![image](https://github.com/user-attachments/assets/e16e1e43-6e74-4ed9-93b2-3c4c6e5e253b)

this is the code that use the vicuna_client:

![image](https://github.com/user-attachments/assets/781241f3-b2d4-4fd4-b440-c6786ae7a552)

it can be used as expected, but when i try to ask throught h2opgt it getting error like in the Title above, TypeError: can only concatenate str (not "bool") to str

![image](https://github.com/user-attachments/assets/779a154c-74f4-44f9-9381-f4e47048c858)

does anyone know what happen? i try to re-clone the repo but the probelm still exist
hope anyone can answer this :)

**Comment by pseudotensor** [comment]
I don't see enough code to have good idea.  E.g. how is "vicuna_client" defined?

If you are using gradio_utils/grclient.py's GradioClient class, you need to run client.setup() before using it.  Maybe related?

**Comment by pseudotensor** [comment]
What version of gradio do you have?  h2oGPT works with gradio 3.50.2 or gradio from requirements.txt:
```
gradio @ https://h2o-release.s3.amazonaws.com/h2ogpt/gradio-4.26.0-py3-none-any.whl
gradio_client @ https://h2o-release.s3.amazonaws.com/h2ogpt/gradio_client-0.15.1-py3-none-any.whl
```

It appears you have some other version.
