### ISSUE TITLE
Only returns the source documents, not an answer for all questions but one

### ISSUE THREAD

**Issue by Blake-Loveland** [h2oai/h2ogpt#182]
Thank you very much for this project and repo, a few download problems during install, but nothing I could not get sorted out.

I am using the CPU instructions and GPT4ALL with a user directory of about 30 small support docs in .md format.

This is running on a Windows 10 laptop, using the WLS and ubuntu 22.04 with 32GB ram.

I have one question I can ask and I get an good answer and the list of references after about 1 or 2 minutes.

Every other question I ask eventually just returns the references with no actual answer text generated. The references look good, they look like the correct documents.

They all looks similar to this in the cli window:
![image](https://github.com/h2oai/h2ogpt/assets/42970073/10f96ac1-fd72-429c-a1cc-cc72d3db90cc)

Any idea what might be going on or how I could address it? I have tried upping the max timeout to 300, but still does not help.

**Comment by pseudotensor** [comment]
Hi @Blake-Loveland , there seems to be a fundamental problem with the GPT4All model itself.  I mention it in the FAQ:

https://github.com/h2oai/h2ogpt/blob/main/FAQ.md#gpt4all-not-producing-output

even just native use (no h2oGPT at all) leads to no output for me *alot*.

I'll try to see if another base model does better.  I notice it gets confused by new lines or other things very easily, so it's a pretty bad model.

**Comment by Blake-Loveland** [comment]
Thank you very much! My apologies for not seeing the FAQ!

**Comment by pseudotensor** [comment]
@Blake-Loveland Try llama cpp instead.  It's still not as good as real full model, however.  Even our 12B pythia trained on 400B tokens is better than 7B llama trained on 1.4T tokens when quantized.
