### ISSUE TITLE
share=False

### ISSUE THREAD

**Issue by lelapin123** [h2oai/h2ogpt#183]
Is there any information shared with anyone if i use the "--share=False" option?

Sorry, it is not really an issue

**Comment by pseudotensor** [comment]
@lelapin123 , shared means it makes a shareable link for others to access the UI/client.

If you do --share=False, then only if someone can access your computer and the port 7860 like your browser can would anyone else have access.  If that's a concern, you can firewall that port to isolate it on that computer.

If you even want to not contact the internet at all, gradio has some challenges with that and one can follow the advices here: https://github.com/h2oai/h2ogpt/blob/main/FAQ.md#offline-mode and here: https://github.com/gradio-app/gradio/issues/1450#issuecomment-1504353760
