### ISSUE TITLE
Unable to get the login screen

### ISSUE THREAD

**Issue by rohitnanda1443** [h2oai/h2ogpt#1834]
Hi I am running a fresh install of H2O-GPT: 

Running script is: python generate.py --inference_server="vllm:0.0.0.0:5001" --guest_name=""  --enable_tts=False --enable_stt=False --base_model=mistralai/Mistral-7B-Instruct-v0.3 --enable_transcriptions=False & 

Even if we run without an inference server we get the same issue. Has there been any change in the gradio server files? 

![error](https://github.com/user-attachments/assets/c858df92-24de-44f5-9edc-777db9682b82)

**Comment by pseudotensor** [comment]
Hi, nothing seems wrong when I run a similar command.  I recommend checking the dev console in chrome browser for errors and posting or fixing.

**Comment by pseudotensor** [comment]
In some cases in past, I've noticed that the browser gets messed up, and one has to reset its cache.

![image](https://github.com/user-attachments/assets/f58c6117-8b46-442c-9bae-ce9ba38cfd86)

**Comment by rohitnanda1443** [comment]
Tried clearing the cache out and retried. Got the same issue.  

Installation steps:

1. Used: Vast.ai to get a server (Ubuntu with Cuda 12.1)
2. Installed H2O-GPT fallowing the Linux install steps
3. Installed Ngrok 
4. started H20 gradio server 
5. started Ngrok and got a web URL. 

This used to work previously. (Has there been any changes in the Gradio libraries?)

**Comment by rohitnanda1443** [comment]
![image](https://github.com/user-attachments/assets/c602848f-1c9d-4844-88a4-ae3904888aa0)

**Comment by pseudotensor** [comment]
Nothing comes to mind except that perhaps the env is not installed correctly and you have (e.g.) too new a gradio or something.

**Comment by rohitnanda1443** [comment]
Did a fresh install couple of days back. Should i give you the ngrok link.

**Comment by pseudotensor** [comment]
To be clear, alot of work in h2oGPT repo in last month has been on agents backend in openai_server that wouldn't be affecting anything for normal users.  So I'd guess something must have changed or broken for installation.

Can you do `pip freeze` and share the results?

**Comment by rohitnanda1443** [comment]
The gradio is old one 4.26.0 

`absl-py==2.1.0
accelerate==0.34.2
aiofiles==23.2.1
aiohappyeyeballs==2.4.0
aiohttp==3.10.5
aiosignal==1.3.1
altair==5.4.1
annotated-types==0.7.0
anthropic==0.25.8
antlr4-python3-runtime==4.9.3
anyascii==0.3.2
anyio==4.4.0
appdirs==1.4.4
APScheduler==3.10.4
argcomplete==3.5.0
arxiv==1.4.8
asgiref==3.8.1
async-timeout==4.0.3
attrs==24.2.0
audioread==3.0.1
Authlib==1.3.2
auto_gptq==0.7.1
autoawq==0.2.5
autoawq_kernels==0.0.6
babel==2.16.0
backoff==2.2.1
backports.tarfile==1.2.0
bangla==0.0.2
bcrypt==4.2.0
beautifulsoup4==4.12.3
bioc==2.1
bitsandbytes==0.43.3
blinker==1.8.2
blis==0.7.11
bnnumerizer==0.0.2
bnunicodenormalizer==0.1.7
boto3==1.35.14
botocore==1.35.14
Brotli==1.1.0
bs4==0.0.2
build==1.2.2
cachetools==5.5.0
catalogue==2.0.10
certifi==2024.8.30
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1725560520483/work
chardet==5.2.0
charset-normalizer==3.3.2
chroma-hnswlib==0.7.3
chromadb==0.4.23
click==8.1.7
cloudpathlib==0.19.0
colorama==0.4.6
coloredlogs==15.0.1
confection==0.1.5
contourpy==1.2.1
coqpit==0.0.17
cramjam==2.8.3
cryptography==43.0.1
cssselect2==0.2.1
cutlet==0.3.0
cycler==0.12.1
cymem==2.0.8
Cython==3.0.11
dacite==1.7.0
dataclasses-json==0.6.7
datasets==2.21.0
dateparser==1.1.8
decorator==5.1.1
deepdiff==8.0.1
deepspeed==0.15.1
defusedxml==0.7.1
Deprecated==1.2.14
diffusers==0.24.0
dill==0.3.8
diskcache==5.6.3
distro==1.9.0
dnspython==2.6.1
docopt==0.6.2
docutils==0.20.1
docx2txt==0.8
duckdb @ https://h2o-release.s3.amazonaws.com/h2ogpt/duckdb-0.8.2.dev4025%2Bg9698e9e6a8.d20230907-cp310-cp310-linux_x86_64.whl#sha256=0908cf14585903aae039ef36d769420fe0265d17de6440bb4eabab27a1bdde0f
duckduckgo_search==6.2.11
effdet==0.4.1
einops==0.8.0
emoji==2.12.1
encodec==0.1.1
et-xmlfile==1.1.0
eval_type_backport==0.2.0
evaluate==0.4.0
exceptiongroup==1.2.2
execnet==2.1.1
exllama @ https://github.com/jllllll/exllama/releases/download/0.0.18/exllama-0.0.18+cu121-cp310-cp310-linux_x86_64.whl#sha256=b4e4a8cb699757880cc2c96f8d3a35b6dd9f1fba73208c59f2f9dab9d49c4fae
exllamav2==0.0.16
faiss-gpu==1.7.2
fastapi==0.114.0
fastparquet==2024.5.0
feedparser==6.0.11
ffmpeg==1.4
ffmpeg-python==0.2.0
ffmpy==0.4.0
fiftyone==0.25.1
fiftyone-brain==0.17.0
fiftyone_db==1.1.5
filelock==3.16.0
filetype==1.2.0
fire==0.5.0
flash-attn==2.6.3
Flask==3.0.3
flatbuffers==24.3.25
fonttools @ file:///home/conda/feedstock_root/build_artifacts/fonttools_1725391240115/work
frozenlist==1.4.1
fsspec==2024.6.1
ftfy==6.2.3
fugashi==1.3.2
future==1.0.0
g2pkk==0.1.2
gekko==1.2.1
glob2==0.7
google-ai-generativelanguage==0.6.2
google-api-core==2.19.2
google-api-python-client==2.144.0
google-auth==2.34.0
google-auth-httplib2==0.2.0
google-generativeai==0.5.2
google_search_results==2.4.2
googleapis-common-protos==1.65.0
gpt4all==1.0.5
gradio @ https://h2o-release.s3.amazonaws.com/h2ogpt/gradio-4.26.0-py3-none-any.whl#sha256=922798c98b4954bd76a78633f85c2a91c9c8df3018a0237928b193033a78c0a5
gradio_client @ https://h2o-release.s3.amazonaws.com/h2ogpt/gradio_client-0.15.1-py3-none-any.whl#sha256=38d8f877aa2fcb9b56ddee352085f3ca58977f35b4da0853758053fbd6084ea1
gradio_pdf==0.0.15
gradio_tools==0.0.9
graphql-core==3.2.4
greenlet==3.0.3
groq==0.5.0
grpcio==1.66.1
grpcio-status==1.62.3
grpcio-tools==1.62.3
gruut==2.2.3
gruut-ipa==0.13.0
gruut_lang_de==2.0.1
gruut_lang_en==2.0.1
gruut_lang_es==2.0.1
gruut_lang_fr==2.0.2
h11==0.14.0
h2==4.1.0
h5py==3.11.0
hangul-romanize==0.1.0
hf_transfer==0.1.8
hjson==3.1.0
hpack==4.0.0
html2text==2024.2.26
html5lib @ file:///home/conda/feedstock_root/build_artifacts/html5lib_1592930327044/work
httpcore==1.0.5
httplib2==0.22.0
httptools==0.6.1
httpx==0.25.2
httpx-sse==0.4.0
huggingface-hub==0.24.6
humanfriendly==10.0
humanize==4.10.0
Hypercorn==0.17.3
hyperframe==6.0.1
idna==3.8
imageio==2.35.1
importlib_metadata==8.4.0
importlib_resources==6.4.4
imutils==0.5.4
inflate64==1.0.0
inflect==7.4.0
iniconfig==2.0.0
InstructorEmbedding==1.0.1
intervaltree==3.1.0
iopath==0.1.10
itsdangerous==2.2.0
jaconv==0.4.0
jamo==0.4.1
jaraco.context==6.0.1
jieba==0.42.1
Jinja2==3.1.4
jiter==0.5.0
jmespath==1.0.1
joblib==1.4.2
jq==1.8.0
json_repair==0.29.1
jsonlines==1.2.0
jsonpatch==1.33
jsonpath-python==1.0.6
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
kaleido==0.2.1
kiwisolver==1.4.7
kubernetes==30.1.0
langchain==0.2.16
langchain-anthropic==0.1.12
langchain-community==0.2.16
langchain-core==0.2.38
langchain-experimental==0.0.65
langchain-google-genai==1.0.3
langchain-groq==0.1.3
langchain-openai==0.1.23
langchain-text-splitters==0.2.4
langchain-together==0.1.1
langcodes==3.4.0
langdetect==1.0.9
langgraph==0.2.19
langgraph-checkpoint==1.0.9
langid==1.1.6
langsmith==0.1.116
language_data==1.2.0
layoutparser==0.3.4
lazy_loader==0.4
librosa==0.10.1
llama_cpp_python==0.2.56
llvmlite==0.43.0
lm-dataformat==0.0.20
loralib==0.1.2
lxml==5.3.0
marisa-trie==1.2.0
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.22.0
matplotlib==3.9.2
mdurl==0.1.2
mistralai==0.1.8
mmh3==4.1.0
mojimoji==0.0.13
mongoengine==0.24.2
monotonic==1.6
more-itertools==10.5.0
motor==3.5.1
mplcursors==0.5.3
mpmath==1.3.0
msg-parser==1.2.0
msgpack==1.0.8
multidict==6.0.5
multiprocess==0.70.16
multivolumefile==0.2.3
munkres==1.1.4
murmurhash==1.0.10
mutagen==1.47.0
mypy-extensions==1.0.0
narwhals==1.6.3
nest-asyncio==1.6.0
networkx==2.8.8
ninja==1.11.1.1
nltk==3.9.1
noisereduce==3.0.2
num2words==0.5.13
numba==0.60.0
numpy==1.23.0
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-ml-py==12.560.30
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.6.68
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.2
olefile==0.47
omegaconf==2.3.0
onnx==1.16.2
onnxruntime==1.15.0
onnxruntime-gpu==1.15.0
openai==1.44.0
opencv-python==4.10.0.84
opencv-python-headless==4.10.0.84
openpyxl==3.1.5
opentelemetry-api==1.27.0
opentelemetry-exporter-otlp-proto-common==1.27.0
opentelemetry-exporter-otlp-proto-grpc==1.27.0
opentelemetry-instrumentation==0.48b0
opentelemetry-instrumentation-asgi==0.48b0
opentelemetry-instrumentation-fastapi==0.48b0
opentelemetry-proto==1.27.0
opentelemetry-sdk==1.27.0
opentelemetry-semantic-conventions==0.48b0
opentelemetry-util-http==0.48b0
openvino==2022.3.0
optimum==1.17.1
orderly-set==5.2.2
orjson==3.10.7
outcome==1.3.0.post0
overrides==7.7.0
packaging==23.2
pandas==2.2.2
pdf2image==1.17.0
pdfminer.six==20231228
pdfplumber==0.11.4
peft==0.12.0
pikepdf==9.2.1
pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1719903544255/work
pillow_heif==0.18.0
pip-licenses==5.0.0
platformdirs==4.3.2
playsound==1.3.0
playwright==1.46.0
plotly==5.24.0
pluggy==1.5.0
pooch==1.8.2
portalocker==2.10.1
posthog==3.6.3
pprintpp==0.4.0
preshed==3.0.9
prettytable==3.11.0
primp==0.6.1
priority==2.0.0
proto-plus==1.24.0
protobuf==4.25.4
psutil==6.0.0
pulsar-client==3.5.0
py-cpuinfo==9.0.0
py7zr==0.22.0
pyarrow==17.0.0
pyasn1==0.6.0
pyasn1_modules==0.4.0
pybcj==1.0.2
pycairo==1.26.1
pyclipper==1.3.0.post5
pycocotools==2.0.8
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1711811537435/work
pycryptodomex==3.20.0
pydantic==2.9.0
pydantic-settings==2.4.0
pydantic_core==2.23.2
pydash==8.0.3
pydub==0.25.1
pydyf @ file:///home/conda/feedstock_root/build_artifacts/pydyf_1720856584155/work
pyee==11.1.0
Pygments==2.18.0
PyGObject==3.48.2
pymongo==4.8.0
PyMuPDF==1.24.10
PyMuPDFb==1.24.10
pynndescent==0.5.13
pynvml==11.5.3
pypandoc==1.13
pypandoc_binary==1.13
pyparsing==3.1.4
pypdf==4.3.1
pypdfium2==4.30.0
pyphen @ file:///home/conda/feedstock_root/build_artifacts/pyphen_1722357615489/work
PyPika==0.48.9
pypinyin==0.52.0
pyppmd==1.1.0
pyproject_hooks==1.1.0
pyrubberband==0.3.0
pysbd==0.3.4
PySocks==1.7.1
pytesseract==0.3.13
pytest==8.3.2
pytest-xdist==3.6.1
python-crfsuite==0.9.10
python-dateutil==2.9.0.post0
python-doctr @ git+https://github.com/h2oai/doctr.git@aee9b1c369e37af9e18265660935bce2c4447d65
python-docx==1.1.0
python-dotenv==1.0.1
python-iso639==2024.4.27
python-magic==0.4.27
python-multipart==0.0.9
python-pptx==0.6.23
pytube==15.0.0
pytz==2024.1
PyYAML==6.0.2
pyzstd==0.16.1
qdrant-client==1.11.1
rapidfuzz==3.9.7
rarfile==4.2
referencing==0.35.1
regex==2024.7.24
replicate==0.25.2
requests==2.32.3
requests-file==2.1.0
requests-oauthlib==2.0.0
responses==0.18.0
retrying==1.3.4
rich==13.8.0
rouge==1.0.1
rouge_score==0.1.2
rpds-py==0.20.0
rsa==4.9
ruff==0.6.4
s3transfer==0.10.2
sacrebleu==2.3.1
safetensors==0.4.5
scikit-image==0.24.0
scikit-learn==1.5.1
scipy==1.11.4
selenium==4.24.0
semantic-version==2.10.0
semanticscholar==0.8.4
sentence-transformers==2.2.2
sentencepiece==0.2.0
sgmllib3k==1.0.0
Shapely==1.8.5.post1
shellingham==1.5.4
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
smart-open==7.0.4
sniffio==1.3.1
sortedcontainers==2.4.0
soundfile==0.12.1
soupsieve==2.6
soxr==0.5.0.post1
spacy==3.7.6
spacy-legacy==3.0.12
spacy-loggers==1.0.5
SQLAlchemy==2.0.34
srsly==2.4.8
sse-starlette==0.10.3
sseclient-py==1.8.0
starlette==0.38.5
strawberry-graphql==0.138.1
SudachiDict-core==20240716
SudachiPy==0.6.8
sympy==1.13.2
tabulate==0.9.0
taskgroup==0.0.0a4
tenacity==8.5.0
tensorboard==2.17.1
tensorboard-data-server==0.7.2
termcolor==2.4.0
text-generation==0.7.0
textstat==0.7.4
texttable==1.7.0
thinc==8.2.5
threadpoolctl==3.5.0
tifffile==2024.8.30
tiktoken==0.7.0
timm==1.0.9
tinycss2 @ file:///home/conda/feedstock_root/build_artifacts/tinycss2_1713974937325/work
together==1.1.5
tokenizers==0.19.1
tomli==2.0.1
tomlkit==0.12.0
torch==2.2.1+cu121
torchaudio==2.2.1+cu121
torchvision==0.17.1+cu121
tqdm==4.66.5
trainer==0.0.36
transformers==4.40.0
trio==0.26.2
trio-websocket==0.11.1
triton==2.2.0
TTS==0.22.0
typeguard==4.3.0
typer==0.12.5
typing-inspect==0.9.0
typing_extensions==4.12.2
tzdata==2024.1
tzlocal==5.2
ujson==5.10.0
umap-learn==0.5.6
unicodedata2 @ file:///home/conda/feedstock_root/build_artifacts/unicodedata2_1695847980273/work
Unidecode==1.3.8
universal-analytics-python3==1.1.1
unstructured==0.12.5
unstructured-client==0.22.0
unstructured-inference==0.7.23
unstructured.pytesseract==0.3.13
uritemplate==4.1.1
urllib3==2.2.2
uvicorn==0.30.6
uvloop==0.20.0
validators==0.34.0
voxel51-eta==0.12.7
wasabi==1.1.3
watchfiles==0.24.0
wavio==0.0.8
wcwidth==0.2.13
weasel==0.4.1
weasyprint @ file:///home/conda/feedstock_root/build_artifacts/weasyprint_1719054467811/work/weasyprint-62.3-py3-none-any.whl#sha256=d31048646ce15084e135b33e334a61f526aa68d2f679fcc109ed0e0f5edaed21
weaviate-client==3.26.2
webencodings @ file:///home/conda/feedstock_root/build_artifacts/webencodings_1694681268211/work
websocket-client==1.8.0
websockets==11.0.3
Werkzeug==3.0.4
wikipedia==1.4.0
wolframalpha==5.1.3
wrapt==1.16.0
wsproto==1.2.0
xlrd==2.0.1
XlsxWriter==3.2.0
xmltodict==0.13.0
xxhash==3.5.0
yarl==1.10.0
yt-dlp==2023.10.13
zipp==3.20.1
zopfli==0.2.3
zstandard==0.23.0
`

[pip-output.txt](https://github.com/user-attachments/files/16941390/pip-output.txt)

**Comment by rohitnanda1443** [comment]
Still the same issue...

**Comment by pseudotensor** [comment]
The npm at the end is only needed for agents.  And it comes last after all other steps, so it shouldn't matter.

**Comment by pseudotensor** [comment]
We build docker images for main.  Have you tried that?  It would help eliminate installation issues.

We use the h2ogpte branch's docker build all the time (uses older gradio due to kubernetes issues)

**Comment by rohitnanda1443** [comment]
Noted, but Vast.ai loads a docker image and gives us a ssh / jupyter login into the image. Cannot run another docker image inside it. 

We can however load other docker images from https://hub.docker.com/search?q=h2ogpt , but the problem is that these images donot have the H2O directory from where I can fire the generate.py command and if one tries to clone the H2O-GPT git and then run again it does not function as conda etc is not installed. Reinstalling using the manual method again gives the same Login screen issue.

**Comment by pseudotensor** [comment]
What if you go back to an older version (i.e. older hash) like you used to use.  Does it work for you?

**Comment by rohitnanda1443** [comment]
On vast.ai I was using the same docker image "cuda12.1-Ubuntu22.04 -dev" all throughout. 

What all I have tried: 
1) Had a couple of months old H2O-GPT repo on PC. Uploaded that on vast and used the manual install. Got the same issue (maybe some versions of packages it is pulling have changed)
2) Tried installing with latest repo: Same issue 
3) Tried to change the docker image to Ubuntu 24.04 - No luck either
4) Tried the Quick Install - Errors out on llama_cpp_python 

It was quite simple a couple of weeks back to get a vast instance and just install and go without any errors in 20 mins. (There could be some package clash that has now come up with the dependency updates). 

Question: How can one check the eror logs of Gradio (I could not find it anywhere). That will throw some idea.

**Comment by pseudotensor** [comment]
The errors just go to the console.  I focused on browser cache issue since I've seen that before when nothing loads.  But your error in the console suggests it's something bad.

We constrain versions of things that caused issues at any point in time, but yes many are relaxed.  But note that I'm not seeing the same issue, so it's not a generic problem.

**Comment by rohitnanda1443** [comment]
Request if you could try out installing on the GPU sharing sites. You may be able to zero on the issue faster. 

I had taken 4-5 fresh servers from different data centres to try it and all ended up with the same screen. (Tried with different ubuntu images too).

Do you suggest trying with a Cuda > 12.1 image?

**Comment by pseudotensor** [comment]
Maybe vast.ai changed something if the old version also fails to work.

What are a list of GPU sharing services that you recommend might be reasonable?

cuda == 12.1 should be good.

You can also check if the client works, e.g. the gradio client or openai client.  Can it reach the server?  Would isolate if issue with your browser connecting to the host or not.

**Comment by rohitnanda1443** [comment]
Nope, some dependency conflicts on the main branch currently. The issue is with other servers also. I tried on runpod.io. Used the image pytorch:2.2.0-py3.10-cuda12.1.1-devel-ubuntu22.04. On Vast.ai (which is a marketplace) used various servers accross the world with different images. 

Below are the 2 errors during install on runpod.io. These also came on Vast.ai. 

![image](https://github.com/user-attachments/assets/4775364d-ffeb-407e-8d47-18f6209a9908)

![image](https://github.com/user-attachments/assets/eda2bb88-c9c6-40a6-ac18-c116f3c15cb7)


The same screen I am getting on ngrok: 
![image](https://github.com/user-attachments/assets/4288af1b-e992-49e1-9aef-370db92cf6fb)

Pod Screenshot: 
![image](https://github.com/user-attachments/assets/4904490a-61a1-4846-acd4-0b590fd21a9d)


**One way of resolution can be using the pip freeze command on your system and see which package versions have changed and then retry by installing the old packages**

**Comment by CodyNault** [comment]
I just did a manual installation on Windows today and am getting the same exact error.

![image](https://github.com/user-attachments/assets/7d336600-0da5-4a54-956b-7b9b21ae6cf1)
![image](https://github.com/user-attachments/assets/8fc4be22-8c18-4813-b2eb-74f67964d02b)

**Comment by pseudotensor** [comment]
Could you try doing:
```
pip uninstall gradio gradio_client -y
pip install gradio==3.50.2 # also installs client
```

and see if anything changed?

**Comment by CodyNault** [comment]
3.50.2 did the trick! Thank you!

**Comment by rohitnanda1443** [comment]
Update: Did some testing and may have zeroes on the issue for the Devs:

1) Further to above after a full Linux install, I thought to resolve Gradio I should manually install all its dependencies: From - https://deps.dev/pypi/gradio/4.26.0/dependencies got the dependencies list and installed: pip install aiofiles==23.2.1 altair==5.4.1 fastapi==0.114.1 ffmpy==0.4.0 gradio-client==0.15.1 httpx==0.27.2 huggingface-hub==0.24.6 importlib-resources==6.4.5 jinja2==3.1.4 markupsafe==2.1.5 matplotlib==3.9.2 numpy==1.26.4 orjson==3.10.7 packaging==24.1.0 pandas==2.2.2 pillow==10.4.0 pydantic==2.9.1 pydub==0.25.1 python-multipart==0.0.9 pyyaml==6.0.2 ruff==0.6.4 semantic-version==2.10.0 tomlkit==0.12.0 typer==0.12.5 typing-extensions==4.12.2 uvicorn==0.30.6 annotated-types==0.7.0 anyio==4.4.0 attrs==24.2.0 certifi==2024.8.30 charset-normalizer==3.3.2 click==8.1.7 contourpy==1.3.0 cycler==0.12.1 exceptiongroup==1.2.2 filelock==3.16.0 fonttools==4.53.1 fsspec==2024.9.0 h11==0.14.0 httpcore==1.0.5 idna==3.8.0 jsonschema==4.23.0 jsonschema-specifications==2023.12.1 kiwisolver==1.4.7 markdown-it-py==3.0.0 mdurl==0.1.2 narwhals==1.7.0 pydantic-core==2.23.3 pygments==2.18.0 pyparsing==3.1.4 python-dateutil==2.9.0.post0 pytz==2024.2.0 referencing==0.35.1 requests==2.32.3 rich==13.8.1 rpds-py==0.20.0 shellingham==1.5.4 six==1.16.0 sniffio==1.3.1 starlette==0.38.5 tqdm==4.66.5 tzdata==2024.1.0 urllib3==2.2.2 websockets==11.0.3 zipp==3.20.1

**It did not work**

2) Then I was told in an old PC the installation was not full and only requirements.txt was installed. Fired up a new server and instead of GPLOK=1 bash docs/linux_install.sh I did `pip install -r requirements.txt`. Fired up Gradio using GRADIO_SERVER_PORT=7860 python generate.py --base_model=togethercomputer/RedPajama-INCITE-Chat-3B-v1 --prompt_type=human_bot --score_model=None --langchain_mode=ChatLLM --visible_langchain_modes="['ChatLLM', 'UserData', 'MyData']" --user_path=user_path --share=False --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2

**Success, I got the Gradio screen**. But getting errors 
![WhatsApp Image 2024-09-12 at 12 47 18_68e8dfe0](https://github.com/user-attachments/assets/98726e58-9c04-4e36-832a-e9c9e85aaa47)


The Terminal shows: 
![WhatsApp Image 2024-09-12 at 12 40 39_dc7b40d0](https://github.com/user-attachments/assets/9faff49d-ef98-4f10-84b3-156ecf68544b)
 

**Issue:**
1) The other optional scripts that are being installed are creating some dependency issue 
2) During a full install, the optional scripts uninstalls and keeps reinstalling numpy and pandas (Both which are dependencies of Gradio)

**Resolution Requested**
1) Please help in isolating the package in optional install creating the dependency conflict and we can fix its version (Like in the requirements.txt script)

**Comment by DrNokkel** [comment]
> Could you try doing:
> 
> ```
> pip uninstall gradio gradio_client -y
> pip install gradio==3.50.2 # also installs client
> ```
> 
> and see if anything changed?

Thanks for your support this helped

**Comment by rohitnanda1443** [comment]
Installing the gradio 3.5 works but with lots of errors. Trying out of Gradio 4.2 etc.. gives the same screen error as the first screen 

![image](https://github.com/user-attachments/assets/08f8c7af-d450-4ceb-8485-b4fd39396a02)

**Comment by pseudotensor** [comment]
Hi, I'm not sure what is going on.  The above seems like an issue with the model-server not gradio itself.
