### ISSUE TITLE
h2ogpt with open WebUI

### ISSUE THREAD

**Issue by InesBenAmor99** [h2oai/h2ogpt#1844]
Hello, I would like to integrate H2O GPT with Open WebUI. Will it be possible to chat with all the documents that are already uploaded in collections created from the H2O GPT interface and stored in the vector database, or will it just be a simple chat without accessing the documents already uploaded in the background?

**Comment by pseudotensor** [comment]
The documents won't work across.

https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#open-web-ui

We use it here: https://gpt-docs.h2o.ai

**Comment by pseudotensor** [comment]
FYI I recommend the non-docker way so it can use h2oGPT OSS changes to the package so it works optimally.

**Comment by InesBenAmor99** [comment]
I don't actually understand the need for [](https://gpt-docs.h2o.ai/) when it's just an implementation of the LLM model, not H2O GPT functionalities. Can you explain the difference between these two options?

**Comment by pseudotensor** [comment]
As in the FAQ, open web ui is using h2oGPT for *all* backend activities (embedding, STT, TTS, image generation, document ingestion, etc.).  openweb ui is then just a UI front end.
