### ISSUE TITLE
Accessing and Uploading Files in MyData Using upload_api and add_file_api

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2ogpt#1845]
**Problem Description:**
I am uploading files to the `MyData `folder through the UI. The **sources_dir** already contains text files related to the LLM, `UserData`, and `MyData` which has information related to the files name. However, I am facing difficulty accessing the `MyData` folder and its files similarly to how I can access the` user_path` that contains documents uploaded to `UserData` through the UI.

**Expected Behavior:**
I would like to:
Access the` MyData` folder and retrieve the files stored in it, just like I can with the `user_path` for `UserData`.
Upload files to both `MyData` and `UserData` using the existing `upload_api` and` add_file_api`.

**Current Behavior:**
I am able to upload files to `UserData `via the UI, but I cannot access or interact with `MyData `in a similar manner.
Unclear on how to use the APIs to upload files directly to `MyData` and `UserData`.

**Request:**
Could you provide a solution or example code demonstrating how to:

Access and retrieve files from the `MyData `folder.
Upload files to both `MyData` and `UserData` using `upload_api` and `add_file_api`.

**Sample Code Request:**
I would appreciate a code example illustrating the following use cases:

Uploading files to `MyData` and `UserData` using `upload_api` and `add_file_api`.
Accessing and listing files in the `MyData` directory similarly to how it’s done with the `user_path`.

**Comment by pseudotensor** [comment]
Personal scratch collections like MyData are not persisted unless you use enable the auth db so that users can login.

I have a FAQ for the item you are asking about I think: https://github.com/h2oai/h2ogpt/blob/main/docs/README_LangChain.md#per-user-database
