### ISSUE TITLE
H2ogpt openai endpoints

### ISSUE THREAD

**Issue by CommitAndPray** [h2oai/h2ogpt#1849]
Hi, can someone explain how I can test these endpoints? I keep getting the same error as shown in the screenshot. If I need to get a key, how can I obtain it? 
![image](https://github.com/user-attachments/assets/4cd7cc00-0406-46d4-95d2-e52a94dfe336)
![image](https://github.com/user-attachments/assets/af26629a-4896-4ec3-ac1f-1028136da639)

**Comment by pseudotensor** [comment]
OpenAI endpoints are on port 5000 by default.

**Comment by CommitAndPray** [comment]
Thank you for responding. Do I need an API key to test the endpoints, or can I just set the api_key to empty

**Comment by pseudotensor** [comment]
EMPTY is default.   You can set the key, like I showed in the FAQ for how to setup gpt.h2o.ai

https://github.com/h2oai/h2ogpt/blob/0e1597644dfee5a2b368d753d84086d966647bd4/docs/FAQ.md#L408

**Comment by InesBenAmor99** [comment]
Thank you, I can now test H2O GPT on Open Web UI. My question is: will it use the documents I have already uploaded to H2O GPT, or will it follow the RAG process and parameters of Open Web UI? Does it interact with the files in my vector database?

**Comment by CommitAndPray** [comment]
Thank you, I can now test H2O GPT on Open Web UI. My question is: will it use the documents I have already uploaded to H2O GPT, or will it follow the RAG process and parameters of Open Web UI? Does it interact with the files in my vector database?

**Comment by pseudotensor** [comment]
The database is separate.  On the backend operations would use h2oGPT except for the database.
