### ISSUE TITLE
Where is the thumbs up/down results?

### ISSUE THREAD

**Issue by yokomizo-tech** [h2oai/h2ogpt#1862]
I find the results from the thumbs up/down buttons in chat tab useful; however, auth.json does not seem to store them. Are they stored somewhere else?

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/blob/70ef4f859762bac1543b8557611bf28c1629176e/gradio_utils/prompt_form.py#L141

So reviews.csv if reviews_file is not set on CLI.
