### ISSUE TITLE
So i asked some questions about a file

### ISSUE THREAD

**Issue by lelapin123** [h2oai/h2ogpt#187]
So i use this url:
https://query1.finance.yahoo.com/v7/finance/download/AAPL?period1=345427200&period2=1685145600&interval=1d&events=history&includeAdjustedClose=true

as data source. It is basically all the prices of the shares of apple.

with the model: [Model: **h2oai/h2ogpt-oasst1-512-12b]**

If i put this url as source for MyData (what is the difference with UserData?)
and then i select the url as only source of data.

and i ask:
"what are the prices on January 26th, 2023?"

(i expect this: | 143.17 | 144.25 | 141.90 | 143.96 | 143.54 | 54,105,100)

This is the answer that i get:
"The prices for January 26, 2023 are:

Gasoline: $2.50 per gallon
Electricity: $0.10 per kilowatt-hour
Natural gas: $1.70 per thousand cubic feet

These prices are based on current market conditions and may change over time. It’s important to note that prices can fluctuate significantly from day to day and from location to location, so it’s always a good idea to check local gas stations or electricity providers for the most up-to-date information."

Which doesnt make much sense.

***

Now instead i download the file and i add it to "MyData", i select the /tmp/gradio/... file
and i ask the same question:

The prices on January 26th, 2023 are:

Open: $150.00
High: $151.00
Low: $148.00
Close: $149.00
Adj Close: $148.50
Volume: $7,819,300

The answer suggests that this time, the software can access my file (before, no).
The problem is that the answer is wrong.
Changing the temperature doesnt change anything

**Comment by lelapin123** [comment]
it seems related to the model

**Comment by pseudotensor** [comment]
One thing you can do is in the UI to Choose "subset" of "Only". This will confirm the sources being found are reasonable.  If it shows no sources, then nothing actually was relevant.  Also, if any sources are used, they will show up in the source links after the response.  If that doesn't appear, there are no matching source documents.

When  you pass a url to the url box, it doesn't know it's a csv or pdf or other item.  It just treats it as an html page.  i.e. it's equivalent to doing:
```
wget https://query1.finance.yahoo.com/v7/finance/download/AAPL?period1=345427200&period2=1685145600&interval=1d&events=history&includeAdjustedClose=true
```

So when I do what you said (happen to be using vicuna here) I get:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/0ef86e0e-c254-4331-bf1d-37577b7a680a)


No interesting response and no sources.

However, if I upload the csv file, I get:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/2c4faa76-26ef-4ab3-ad58-699ea1d09bd6)


So clearly some sources.  Now if I go back to All (or select that csv file), I get:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/80dcc0c2-3fb1-4150-898b-a7b1c1069303)

**Comment by pseudotensor** [comment]
Even if I choose 20 document chunks in expert:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/fb3d8fb6-8455-4a7d-963e-7b2bbc8281c9)


Still no 2023.  Very curious.
