### ISSUE TITLE
So now i am able to change the model, it is just that if i change the model again.

### ISSUE THREAD

**Issue by lelapin123** [h2oai/h2ogpt#188]
So now i am able to change the model, it is just that if i change the model again.
Lets say from from Model: h2oai/h2ogpt-oig-oasst1-512-6_9b to h2oai/h2ogpt-oasst1-512-12b
then it return a out of memory error
I guess the model should also be released from the memory

_Originally posted by @lelapin123 in https://github.com/h2oai/h2ogpt/issues/185#issuecomment-1565788419_

**Comment by lelapin123** [comment]
and the unloading of the model doesn't free the memory

**Comment by pseudotensor** [comment]
Unloading the model only unloads when one didn't pass --base_model in the CLI.  I added a note about that to the models page next to compare model toggle.

So you have to avoid loading any models at CLI, and only load-unload from UI.

This requirement of not preloading a model to unload is just a limitation of torch and gradio.  I haven't found any way to work around it.

**Comment by pseudotensor** [comment]
I confirmed things are working like expected.  So I did:
```
python generate.py --share=False --score_model=None --langchain_mode=MyData
```

Then loaded a model:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/a69c7c75-86ab-4f3f-857b-43dec12dfcfa)


Then I see my GPU memory is used:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/1dde87e2-13bc-462b-85cf-34a3bb830a73)


Then I choose to unload by selecting [None, Remove]:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/d99439f0-6498-45ce-8305-4b163e35342b)


Then I click load/unload and get:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/6a237dc0-72b0-4279-beda-1c7d673ea54b)


and memory is back down:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/4cc1c7cf-0ef6-408e-a7dd-91b29b1db314)

**Comment by pseudotensor** [comment]
I improved the placement of the message in the UI about unloading.
