### ISSUE TITLE
[Errno 28] No space left on device

### ISSUE THREAD

**Issue by DorinDXN** [h2oai/h2ogpt#1908]
Hi there, hope you're well :)

I'm getting this error 
'[Errno 28] No space left on device'
 in the browser. 
I think it started 2-3 days ago. I thought the issue was on my machine, but maybe it's a server issue. 
Please check.

best regards,
Dorin

**Comment by pseudotensor** [comment]
You mean gpt.h2o.ai or gpt-docs.h2o.ai

Yes, I see that, I cleared some space and restarted the underlying gpt.h2o.ai server.  Both seem ok now.
