### ISSUE TITLE
Download the MinGW installer from the MinGW website. Run the installer and select the gcc component.

### ISSUE THREAD

**Issue by cibernicola** [h2oai/h2ogpt#193]
wich?
![image](https://github.com/h2oai/h2ogpt/assets/4579387/8412a3a7-6ecc-468a-b16f-d26495ba8635)

**Comment by leonpierrec** [comment]
normally this one
![image](https://github.com/h2oai/h2ogpt/assets/81476485/1383fe1e-4585-4c60-af6e-2fbc555540ac)
