### ISSUE TITLE
Latest problems May 28th 2023 on windows 10

### ISSUE THREAD

**Issue by lelapin123** [h2oai/h2ogpt#196]
***
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
sphinx 5.0.2 requires docutils<0.19,>=0.14, but you have docutils 0.19 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.2 which is incompatible.
***

On windows 10 with a new conda with python 3.10.11, with 
pip install -r requirements.txt

**Comment by lelapin123** [comment]
then when i start with:

python generate.py --base_model=h2oai/h2ogpt-oig-oasst1-512-6_9b --load_8bit=True

, i receive this warning:

(base) D:\download\AI\h2oai\h2ogpt>python generate.py --base_model=h2oai/h2ogpt-oig-oasst1-512-6_9b --load_8bit=True
bin C:\Users\lelapin\anaconda3\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
C:\Users\lelapin\anaconda3\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'

**Comment by lelapin123** [comment]
i am then able to get answers, but probably based on CPU (based on memory usage and speed)

**Comment by lelapin123** [comment]
If a do a:
pip install -r requirements_optional_langchain.txt

I receive this error:

Failed to build jq
ERROR: Could not build wheels for jq, which is required to install pyproject.toml-based projects

**Comment by lelapin123** [comment]
then:

python generate.py --base_model=h2oai/h2ogpt-oig-oasst1-512-6_9b  --load_8bit=True --langchain_mode=UserData

bin C:\Users\lelapin\anaconda3\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
C:\Users\lelapin\anaconda3\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
Using Model h2oai/h2ogpt-oig-oasst1-512-6_9b
Traceback (most recent call last):
  File "D:\download\AI\h2oai\h2ogpt\generate.py", line 1505, in <module>
    fire.Fire(main)
  File "C:\Users\lelapin\anaconda3\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\lelapin\anaconda3\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\lelapin\anaconda3\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "D:\download\AI\h2oai\h2ogpt\generate.py", line 364, in main
    from gpt_langchain import prep_langchain, get_some_dbs_from_hf
  File "D:\download\AI\h2oai\h2ogpt\gpt_langchain.py", line 30, in <module>
    from langchain.chains.qa_with_sources import load_qa_with_sources_chain
ModuleNotFoundError: No module named 'langchain'

**Comment by lelapin123** [comment]
on the installation process works fine

**Comment by pseudotensor** [comment]
# First problem:

You seem to be using an environment already filled with many things.  e.g. gensim and fuzzy etc. are all unrelated to h2oGPT.  It can be tough to make all packages consistent. You can try removing versions in all requirements*.txt files in h2oGPT to see if it helps get around that when mixing projects.

# Second problem

I added commands in readme under windows for bitsandbytes support.

# Third problem

If even langchain is not installed, something is off with your env or installation process.

**Comment by 512DuncanL** [comment]
I still get the `UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "` issue even after going through the Windows 10/11 instructions

**Comment by pseudotensor** [comment]
Ok, first thing tomorrow I will test again on windows.  We are getting automated testing going soon.  @achraf-mer

**Comment by pseudotensor** [comment]
FYI @lelapin123  ^^

**Comment by pseudotensor** [comment]
@512DuncanL Sorry about that, as in the other issue, I made a mistake and used `--index-url` but should have been `--extra-index-url` .  Was caused by checking process and having issues with GPU detection, and noticing torch not right one, and adding that fix for torch pip install after rest was already installed.
