### ISSUE TITLE
Is there an API that is related to this project?

### ISSUE THREAD

**Issue by lelapin123** [h2oai/h2ogpt#200]
I am not sure if my question makes actually sense, because i am sure that the LLM are provided with their demo source code.

However is there a way, for example, to request something from a python code to a server that is already online ?
Some kind of protocol of query that is not the web ui?

**Comment by pseudotensor** [comment]
Hi @lelapin123 , yes, a basic example of a test of client code (assuming there is a running server) is client_test.py.

Full test that launches server as well is in `tests/test_client_calls.py` .

This uses the gradio client to talk to the gradio server for any elements in gradio_runner.py that have a click etc. marked with `api_name=`.
