### ISSUE TITLE
Hallucinations on MyData

### ISSUE THREAD

**Issue by williamspindox** [h2oai/h2ogpt#201]
HI,
I just entered "William Blabla is a developer" in the "Paste Text" field and selected MyData.
Then I asked who William Blabla is and the answer was:

William Blabla is a developer known for his work on the OpenSCAD open source project. He is also the founder of the [OpenSCAD.org] website (http://openscad.org/), which provides information and tutorials on using OpenSCAD.

I've tried changing the temperature and so on to avoid hallucinations, but nothing changes. Why?
Thank you

William

**Comment by pseudotensor** [comment]
Yes, I've noticed too this scenario.  A pure vectordb + LLM needs more help.

If you you play with expert settings, you need to turn on sampling in expert too.  Did you do that?

But by default there is no sampling, so purely greedy answer, which should be more deterministic than sampling.

**Comment by williamspindox** [comment]
Yes I did, but I can't see any difference in the response by enabling sampling or changing the advanced settings. Have you tried entering a very simple sentence into MyData and asking a precise question on your topic with and without sampling?

**Comment by pseudotensor** [comment]
normal problem
