### ISSUE TITLE
How can I merge UserData and LLM / ChatLLM data ?

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#203]
Hi,
I generated db with my emails, downloaded from Gmail, and I can use UserData data source , or I can use LLM / ChatLLM data sources. Is there any option combine them ? As UserData contains only my email without anything else and LLM / ChatLLM contains everything, but my content.

Thanks

**Comment by slavag** [comment]
Well, I'm a bit confused :) I generated db using this command :
python generate.py --base_model=gptj --score_model=None --langchain_mode='UserData' --user_path=user_path
And when it was generated I can chat with UserData source, but it seems to be generated only from the UserData (many times just empty answer). But if I select LLM / ChatLLM I'm getting different result, which looks ok. So, maybe I'm doing something wrong ?

Thanks

**Comment by pseudotensor** [comment]
@slavag I know it's a bit confusing.  Especially without tooltips or other documentation, those names are not entirely clear.  Happy if you have suggestions.

This may help: https://github.com/h2oai/h2ogpt/blob/main/FAQ.md#explain-things-in-ui

**Comment by slavag** [comment]
Thanks, I found this : "To Chat with your docs, choose, e.g. UserData. To avoid including docs, and just chat with LLM, choose ChatLLM." , but when I'm trying to chat with UserData, I don't see results that I'm getting with LLM. So, how can this be fixed ?

**Comment by pseudotensor** [comment]
Hi @slavag can you show me what you mean by "I don't see results that I'm getting with LLM"?  I can't quite follow.  Thanks.

**Comment by slavag** [comment]
Hi,

Sure, in this screenshot I'm using UserData and result is empty:

-----------------------------------------------------------------
![image](https://github.com/h2oai/h2ogpt/assets/511540/f38b5948-9f93-465b-b1b1-3ec3d0669ae7)


And in this I'm using ChatLLM, which provides result
-------------------------------------------------------

![image](https://github.com/h2oai/h2ogpt/assets/511540/55730d8d-02e9-4e97-a9d5-8709d36d731f)


Thanks

**Comment by pseudotensor** [comment]
@slavag Thanks for explaining.  I think it might be related to https://github.com/h2oai/h2ogpt/issues/192 that I'll fix tomorrow.  Basically, the prompt is getting truncated away when the doc chunks added are too long, because of a rough estimate of the number of characters per token.

**Comment by pseudotensor** [comment]
BTW, you can also start the UI with `--h2ocolors=False` to get better colors in non-dark mode.

**Comment by pseudotensor** [comment]
Hi @slavag Great.  Will fix the general issue soon.

chunk_size makes sense if you already created the database, that would only help if one remade the db.

top_k_docs is good choice for now.  I'll even make it default for now until I resolve that issue.

**Comment by Sanjana8888** [comment]
How did you generate db?

**Comment by JettScythe** [comment]
I don't think the title of this issue quite matches OP's concern, but it's exactly what I'm looking for. @pseudotensor Is there a way I can use UserData with LLM mode? That is to say: If a user asks a question while in the LLM collection, but there is a document in UserData that contains relevant information - I would like the bot to output a mix of the two responses. I was thinking as a workaround I could upload a document to the LLM collection, but it seems to switch to MyData on upload. 

![image](https://github.com/h2oai/h2ogpt/assets/37233887/5f9e32b6-d05f-4e19-9efc-d636f4a4af2b)
![image](https://github.com/h2oai/h2ogpt/assets/37233887/523a5632-65b6-42f1-8fbb-37ed14bb02bc)

**Comment by pseudotensor** [comment]
I couldn't quite follow what is meant by "bot to output a mix of the two responses".  Can you explain? 

FYI `---use_llm_if_no_docs=True` is default again, for a while I had False, but it's a bit odd to get no "No related documents found" by default.

Yes, for gradio client, gradio server would just need to have that parameter set.  I confirm.

**Comment by JettScythe** [comment]
I would most likely make things worse by trying to explain. This is all very new to me & I'm still very much learning the terminology. 
`--use_llm_if_no_docs=True` is exactly what I was looking for. Thank you very much :)
