### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by bibi-b** [h2oai/h2ogpt#206]
Hi there,

I installed everything with the CPU method on my Linux 20 server.

After

python generate.py --base_model
=gptj --score_model=None

I received:

File "generate.py", line 50
    load_8bit: bool = False,
             ^
SyntaxError: invalid syntax

The PC is headless with a build in graphic card. Mybe that is the reason?
Or do I miss something?
I am new to all of that and doing copy&paste :-) 

Thanks
Meiko

**Comment by pseudotensor** [comment]
Hi @bibi-b , it must be something super basic, but I cannot tell from above what was done.

But roughly speaking, sounds like you didn't install any python environment, at least not a python 3.10 one we require.

Perhaps this will help? https://github.com/h2oai/h2ogpt/blob/main/INSTALL.md#install-python-environment

**Comment by bibi-b** [comment]
Thanks. I started from scratch, installed the python environment as linked above and am now running into this issue:

Failed to build hnswlib pycocotools
ERROR: Could not build wheels for hnswlib, pycocotools, which is required to install pyproject.toml-based projects

(when executing pip install -r reqs_optional/requirements_optional_langchain.txt)

I already tried:
conda install -c conda-forge hnswlib
and
conda install -c conda-forge pycocotools

Any ideas?

Thanks

**Comment by pseudotensor** [comment]
@bibi-b Can you share the full error?  The lines you shared only say what the final error was, not why, while the rest may indicate why.

**Comment by pseudotensor** [comment]
Hi @bibi-b , a couple things are off:
1) The above refers to python 3.8, while we require python 3.10
2) The above uses system python in `/usr/include/python3.8` and other places, while normal instructions use an isolated conda environment

It's like you are still not using the actual conda environment from https://github.com/h2oai/h2ogpt/blob/main/docs/INSTALL.md#install-python-environment

Can you confirm the outputs mentioned there, like from `python --version` and `python -c "import os, sys ; print('hello world')"` ?

**Comment by bibi-b** [comment]
Hi @pseudotensor  , thanks a lot for your help. Here are some outputs:

`
meiko@SERVER-LINUX:~$ conda activate

(base) meiko@SERVER-LINUX:~$ python -V
Python 3.10.11

(base) meiko@SERVER-LINUX:~$ python -c "import os, sys ; print('hello world')"
hello world

(base) meiko@SERVER-LINUX:~$ which python
/home/meiko/miniconda3/bin/python

(base) meiko@SERVER-LINUX:~$ conda activate h2ogpt

(h2ogpt) meiko@SERVER-LINUX:~$ which python
/home/meiko/miniconda3/envs/h2ogpt/bin/python

(h2ogpt) meiko@SERVER-LINUX:~$ python -c "import os, sys ; print('hello world')"
hello world
`

**Comment by bibi-b** [comment]
@pseudotensor Ha! The solution is to use pip3 instead. So
`
pip3 install -r reqs_optional/requirements_optional_langchain.txt
`
is working. ;-)

**Comment by pseudotensor** [comment]
Hmm, interesting.  In every system I've been on, installing python=3.10 would mean "pip" would be from that environment, not some random environment.  Maybe your $PATH has some system stuff as higher priority than conda.

I'll add to docs this suggestion.
