### ISSUE TITLE
Cannot install GPU support on Linux

### ISSUE THREAD

**Issue by mbecuwe** [h2oai/h2ogpt#219]
I cannot install h2ogpt with GPU on Debian on Python 3.10.9:

```
jupyter@h2ogpt:~/h2ogpt$ pip install -r requirements.txt --index-url https://download.pytorch.org/whl/cu117

Looking in indexes: https://download.pytorch.org/whl/cu117
Collecting git+https://github.com/huggingface/peft.git@3714aa2fff158fdfa637b2b65952580801d890b2 (from -r requirements.txt (line 22))
  Cloning https://github.com/huggingface/peft.git (to revision 3714aa2fff158fdfa637b2b65952580801d890b2) to /var/tmp/pip-req-build-kvzh5qmq
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/peft.git /var/tmp/pip-req-build-kvzh5qmq
  Running command git rev-parse -q --verify 'sha^3714aa2fff158fdfa637b2b65952580801d890b2'
  Running command git fetch -q https://github.com/huggingface/peft.git 3714aa2fff158fdfa637b2b65952580801d890b2
  Running command git checkout -q 3714aa2fff158fdfa637b2b65952580801d890b2
  Resolved https://github.com/huggingface/peft.git to commit 3714aa2fff158fdfa637b2b65952580801d890b2
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Looking in indexes: https://download.pytorch.org/whl/cu117
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.```

**Comment by adryanm2m** [comment]
Hi, getting the exact same while following windows install instructions

running
pip install -r requirements.txt --index-url https://download.pytorch.org/whl/cu117

---
× pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Looking in indexes: https://download.pytorch.org/whl/cu117
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0
      [end of output]
---

**Comment by pseudotensor** [comment]
@adryanm2m @mbecuwe Sorry about that.  When I was going through windows installation steps, I realized GPU  support in windows needed torch installed with that special index, so I added that to full pip install, but I forgot that would *only* use that as index.  So that's fixed now, should just have been `--extra-index-url` instead of `--index-url`

i.e.

```
pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu117
```

works and uses that index for torch as required.

**Comment by pseudotensor** [comment]
If in windows any issue is seen, there could be some pip bug/issue.  Then one would need to follow the instructions and end off with a separate:
```
pip uninstall torch
pip install torch==2.0.1 --index-url https://download.pytorch.org/whl/cu117
```
at very end after `pip install -r requirements.txt` is done.  I hope that's not required, but I can check windows again a bit later.
