### ISSUE TITLE
Add documentation on how to connect to weaviate

### ISSUE THREAD

**Issue by hsm207** [h2oai/h2ogpt#237]
We should have dedicated documentation on how to connect to a weavite instance based on #145 and #235

**Comment by hsm207** [comment]
@pseudotensor any advise on where we can write these docs? e.g. should we add a new md in the docs folder or can we edit an existing one?

**Comment by pseudotensor** [comment]
If it's short, like 1-2 paragraphs, it can be in docs/README_LangChain.txt, like after discussing databases.  Would be also good to explain there the benefits of weaviate, like storing original documents while chroma only stores chunks/vectors.

**Comment by hsm207** [comment]
> explain there the benefits of weaviate, like storing original documents while chroma only stores chunks/vectors.

@pseudotensor could you clarify what you mean by this? On chroma's [docs](https://docs.trychroma.com/), it mentions it can:

> * store embeddings and their metadata

so, I assume users can store the entire document if they wanted to just like users of weaviate can.

Or, did you mean something else when you say "storing original documents"?

**Comment by pseudotensor** [comment]
@hsm207 Yes, AFAIK, chroma stores chunks, their, embeddings, and their metadata.  But if you want to look back at the source document for those chunks, you better keep those files around.

i.e. For UserData or MyData, if you upload a pdf, we show the link if you click "show sources" or if you get source list in chat, but those links won't work if the original data files are no longer present.  Chroma doesn't need that original content, but as a user I want to go back to the source document to see what it was in totality.

However, AFAIK, weaviate allows one to also store the original source documents and they can be retrieved.

But maybe I'm confused, but maybe there are other benefits to weaviate.
