### ISSUE TITLE
Please povide OpenAI-compatible API

### ISSUE THREAD

**Issue by fishfree** [h2oai/h2ogpt#240]
When I access this path, it says:
![image](https://github.com/h2oai/h2ogpt/assets/1741341/5b636677-5246-4ba8-8760-3050b946d1b8)
But OpenAI says:
![image](https://github.com/h2oai/h2ogpt/assets/1741341/ddda2851-8a4e-4ebe-824f-7f11fc1f4bb2)

**Comment by pseudotensor** [comment]
Yes, @this is working on this https://github.com/h2oai/h2ogpt/pull/133

**Comment by jinqiupeter** [comment]
Seems #133 has been merged, but still got {"detail": "Not Found"} error .
Or maybe I didn't run it correctly. It's not clear how to enable Openai-compliant API access, could you please elaborate, thank you!

**Comment by this** [comment]
For the `h2ogpt_client` API, please refer https://github.com/h2oai/h2ogpt/tree/main/client#usage

**Comment by jinqiupeter** [comment]
Thanks @this . My understanding is the `h2ogpt_client` is a client that calls the backend h2ogpt's API, I don't need to run `h2ogpt_client` to get the backend API to work, right?

What I am trying to do is to use https://github.com/Yidadaa/ChatGPT-Next-Web to connect my h2ogpt backend. So far I've only got 404:
![image](https://github.com/h2oai/h2ogpt/assets/12045814/bebee983-b165-49ce-a342-dce27f5b596d)

**Comment by this** [comment]
> My understanding is that h2ogpt_client is a client that calls the backend h2ogpt's API, I don't need to run h2ogpt_client to get the backend API to work, right?

@jinqiupeter h2oGPT server API is not similar or compatible with OpenAI API, because h2oGPT HTTP API is implemented through the Gradio server. Hence, it would be much easier for you use the `h2ogpt_client` which provides a more user-friendly API.

**Comment by enriquedecote** [comment]
Did you get this working @jinqiupeter ? I'm on a similar boat. I'd like to use call the backend from a different frontend, maybe a Discord server or the next-web frontend you cite.

**Comment by pseudotensor** [comment]
done
