### ISSUE TITLE
cpu: No Errors But No Answer

### ISSUE THREAD

**Issue by quantumalchemy** [h2oai/h2ogpt#241]
what are the min req for cpu ? I ran this on i7 32g ram
but ran for over 20min with no answer / then killed it used the .env default models as noted in readme
anytricks to get this up and working on cpu only?

**Comment by quantumalchemy** [comment]
Yeah I ran the default 
model_path_llama=WizardLM-7B-uncensored.ggmlv3.q8_0.bin

No getting answer.. will try again
Thanks

**Comment by pseudotensor** [comment]
Ok.  Yes, that's our default case that's part of our test suite too.

Are you using CLI or UI?

**Comment by quantumalchemy** [comment]
The ui .. I will try on a gpu tomorrow 
Where is the cli version?

**Comment by pseudotensor** [comment]
Also windows or linux?

The CLI way is described here: https://github.com/h2oai/h2ogpt#cli-chat

**Comment by pseudotensor** [comment]
Streaming in UI for CPU models isn't supported yet.  Perhaps you didn't wait long enough?

```
error: requested results 1000 is greater than number of elements in index 266, updating n_results = 266
```
not actually an error, you can ignore

```
llama_tokenize: too many tokens
```
I see, probably large input and even tokenizer can't handle beyond some limit of input text.  Will review.

**Comment by pseudotensor** [comment]
![image](https://github.com/h2oai/h2ogpt/assets/2249614/366653f4-aca6-495a-978d-8bfd30266404)
