### ISSUE TITLE
Add option to replace attention with flash attention

### ISSUE THREAD

**Issue by ryanchesler** [h2oai/h2ogpt#25]
Flash attention has already been integrated into gpt-neox models here: https://github.com/HazyResearch/flash-attention/blob/main/flash_attn/models/gpt.py#L215 

Can add the swapped model definition as an option to the training and generation scripts and benchmark the speed difference.

Converting Llama and others might be more work. it uses a pretty standard looking attention, but not sure how it differs from the pytorch default. Might just need to remap some layer names https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L160

**Comment by arnocandel** [comment]
#128
