### ISSUE TITLE
is this really a GGML file? on WizardLM-7B-uncensored.ggmlv3.q8_0.bin

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#254]
Hi,
Tried to run :
python generate.py --base_model=llama --score_model=None --langchain_mode='UserData' --chunk_size=256 --top_k_docs=3 --h2ocolors=False

started to get that error recently, was working fine a week (or so) ago and after pulling it stopped to work.
Have llama-cpp-python version 0.1.48

Thanks.

Log :
llama.cpp: loading model from models/WizardLM-7B-uncensored.ggmlv3.q8_0.bin
error loading model: unknown (magic, version) combination: 67676a74, 00000003; is this really a GGML file?
llama_init_from_file: failed to load model
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/slava/Documents/Development/private/AI/h2ogpt/generate.py:1699 in <module>                │
│                                                                                                  │
│   1696 │                                                                                         │
│   1697 │   python generate.py --base_model=h2oai/h2ogpt-oig-oasst1-512-6_9b                      │
│   1698 │   """                                                                                   │
│ ❱ 1699 │   fire.Fire(main)                                                                       │
│   1700                                                                                           │
│                                                                                                  │
│ /Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/fire/core.py:141 in Fire        │
│                                                                                                  │
│   138 │   context.update(caller_globals)                                                         │
│   139 │   context.update(caller_locals)                                                          │
│   140                                                                                            │
│ ❱ 141   component_trace = _Fire(component, args, parsed_flag_args, context, name)                │
│   142                                                                                            │
│   143   if component_trace.HasError():                                                           │
│   144 │   _DisplayError(component_trace)                                                         │
│                                                                                                  │
│ /Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/fire/core.py:475 in _Fire       │
│                                                                                                  │
│   472 │     is_class = inspect.isclass(component)                                                │
│   473 │                                                                                          │
│   474 │     try:                                                                                 │
│ ❱ 475 │   │   component, remaining_args = _CallAndUpdateTrace(                                   │
│   476 │   │   │   component,                                                                     │
│   477 │   │   │   remaining_args,                                                                │
│   478 │   │   │   component_trace,                                                               │
│                                                                                                  │
│ /Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/fire/core.py:691 in             │
│ _CallAndUpdateTrace                                                                              │
│                                                                                                  │
│   688 │   loop = asyncio.get_event_loop()                                                        │
│   689 │   component = loop.run_until_complete(fn(*varargs, **kwargs))                            │
│   690   else:                                                                                    │
│ ❱ 691 │   component = fn(*varargs, **kwargs)                                                     │
│   692                                                                                            │
│   693   if treatment == 'class':                                                                 │
│   694 │   action = trace.INSTANTIATED_CLASS                                                      │
│                                                                                                  │
│ /Users/slava/Documents/Development/private/AI/h2ogpt/generate.py:442 in main                     │
│                                                                                                  │
│    439 │   │   # get default model                                                               │
│    440 │   │   all_kwargs = locals().copy()                                                      │
│    441 │   │   if all_kwargs.get('base_model') and not all_kwargs['login_mode_if_model0']:       │
│ ❱  442 │   │   │   model0, tokenizer0, device = get_model(reward_type=False,                     │
│    443 │   │   │   │   │   │   │   │   │   │   │   │      **get_kwargs(get_model, exclude_names  │
│    444 │   │   else:                                                                             │
│    445 │   │   │   # if empty model, then don't load anything, just get gradio up                │
│                                                                                                  │
│ /Users/slava/Documents/Development/private/AI/h2ogpt/generate.py:612 in get_model                │
│                                                                                                  │
│    609 │   │   print("Get %s model" % base_model, flush=True)                                    │
│    610 │   if base_model in non_hf_types:                                                        │
│    611 │   │   from gpt4all_llm import get_model_tokenizer_gpt4all                               │
│ ❱  612 │   │   model, tokenizer, device = get_model_tokenizer_gpt4all(base_model)                │
│    613 │   │   return model, tokenizer, device                                                   │
│    614 │                                                                                         │
│    615 │   if lora_weights is not None and lora_weights.strip():                                 │
│                                                                                                  │
│ /Users/slava/Documents/Development/private/AI/h2ogpt/gpt4all_llm.py:44 in                        │
│ get_model_tokenizer_gpt4all                                                                      │
│                                                                                                  │
│    41 │   │   func_names = list(inspect.signature(Llama.__init__).parameters)                    │
│    42 │   │   model_kwargs = {k: v for k, v in model_kwargs.items() if k in func_names}          │
│    43 │   │   model_kwargs['n_ctx'] = int(model_kwargs['n_ctx'])                                 │
│ ❱  44 │   │   model = Llama(model_path=model_path, **model_kwargs)                               │
│    45 │   elif base_model in "gpt4all_llama":                                                    │
│    46 │   │   if 'model_name_gpt4all_llama' not in model_kwargs and 'model_path_gpt4all_llama'   │
│    47 │   │   │   raise ValueError("No model_name_gpt4all_llama or model_path_gpt4all_llama in   │
│                                                                                                  │
│ /Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/llama_cpp/llama.py:159 in       │
│ __init__                                                                                         │
│                                                                                                  │
│    156 │   │   │   self.model_path.encode("utf-8"), self.params                                  │
│    157 │   │   )                                                                                 │
│    158 │   │                                                                                     │
│ ❱  159 │   │   assert self.ctx is not None                                                       │
│    160 │   │                                                                                     │
│    161 │   │   if self.lora_path:                                                                │
│    162 │   │   │   if llama_cpp.llama_apply_lora_from_file(                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError

**Comment by pseudotensor** [comment]
Hi, we have had `llama-cpp-python==0.1.55` for last 1.5 weeks and only before that for a day had 0.1.54.  So your environment is probably from some other installation I'm guessing.

The error you see is that the package llama-cpp-python can't handle version 3 quantization, which only the older package could not, so it makes sense.

Try using a consistent environment, e.g. re-pip install -r on the relevant files or check which environment you are in.

**Comment by pseudotensor** [comment]
To check if your requirements are correct for a given h2oGPT hash, you can run:
```
pytest -s -v tests/test_requirements.py::test_requirements
```

**Comment by pseudotensor** [comment]
```
(h2ollm) jon@pseudotensor:~/h2ogpt$ python generate.py --base_model=llama --score_model=None --langchain_mode='UserData' --chunk_size=256 --top_k_docs=3 --h2ocolors=False
bin /home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
Using Model llama
Prep: persist_directory=db_dir_UserData exists, using
llama.cpp: loading model from WizardLM-7B-uncensored.ggmlv3.q8_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32001
llama_model_load_internal: n_ctx      = 1792
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 7 (mostly Q8_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.07 MB
llama_model_load_internal: mem required  = 8620.72 MB (+ 1026.00 MB per state)
.
llama_init_from_file: kv self size  =  896.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
Running on local URL:  http://0.0.0.0:7860
```

![image](https://github.com/h2oai/h2ogpt/assets/2249614/08de5c4f-e81a-44ea-910a-47f1a2a4e67a)
