### ISSUE TITLE
Possibility to use GPTQ models?

### ISSUE THREAD

**Issue by LitenBuzzTh** [h2oai/h2ogpt#263]
Hi
I would love to know that is there a possibility for the GPTQ models to be used?

**Comment by DJJones66** [comment]
I've not had any success with that yet, I have loaded everything for 4bit as per the readme but when I attempt to load (for example the one model is .safetensors and it errors out for the json file being missing.. If I point to just the directory it complains the .bin is missing. 

Still doing research and trying new things myself.

**Comment by pseudotensor** [comment]
If you guys give an example model (point to HF location etc.), I can check it out to see what's required to make it work. Thanks!

**Comment by DJJones66** [comment]
TheBloke is where I mainly look for mine, so something like this.. 
https://huggingface.co/TheBloke/starcoderplus-GPTQ
or 
https://huggingface.co/TheBloke/CAMEL-13B-Role-Playing-Data-GPTQ
I think once the ball gets rolling then can start to play around more.. So far I just get a headache.. lol

**Comment by LitenBuzzTh** [comment]
> If you guys give an example model (point to HF location etc.), I can check it out to see what's required to make it work. Thanks!

GPTQ models are well optimized for lower end PCs, enabling more users to use h2ogpt locally. some of the top GPTQ models released by TheBloke are : 

https://huggingface.co/TheBloke/vicuna-13B-1.1-GPTQ-4bit-128g
https://huggingface.co/TheBloke/Nous-Hermes-13B-GPTQ
https://huggingface.co/TheBloke/wizard-vicuna-13B-GPTQ

it would be really nice if you could make GPTQ models compatible with h2ogpt

**Comment by pseudotensor** [comment]
https://github.com/huggingface/text-generation-inference/pull/438

**Comment by arnocandel** [comment]
```
model=huggingface/falcon-40b-gptq
num_shard=2
volumn=$PWD/data
docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:latest --model-id $model --num-shard $num_shard --quantize gptq
```

```
python generate.py --inference_server=http://localhost:8080 --base_model=huggingface/falcon-40b-gptq
```

works, but super slow

**Comment by arnocandel** [comment]
for
`model=TheBloke/wizard-vicuna-13B-GPTQ`
I get:
```
RuntimeError: weight gptq_bits does not exist
```

**Comment by arnocandel** [comment]
https://github.com/huggingface/text-generation-inference/pull/438#issuecomment-1598333590

**Comment by arnocandel** [comment]
https://github.com/huggingface/text-generation-inference/blob/70f485bf9f601b5450b00894f56e20b973d1c2e4/server/text_generation_server/utils/gptq/quantize.py#L818-L819 need to hack these into GPTQ model states first.

**Comment by DJJones66** [comment]
> for `model=TheBloke/wizard-vicuna-13B-GPTQ` I get:
> 
> ```
> RuntimeError: weight gptq_bits does not exist
> ```

Yeah, I am not sure on that model, if going for a Wizard based model I tend to stick with WizardLM like TheBloke/wizardLM-13B-1.0-GPTQ
