### ISSUE TITLE
AttributeError: module 'faulthandler' has no attribute 'register' on Windows

### ISSUE THREAD

**Issue by BFX-89** [h2oai/h2ogpt#271]
I'm trying to run H2Ogpt in windows environment and tried to follow every step in README for windows and everything seemed fine.

However when I tried to start the system I got the following error message:

(h2o) C:\H2O\h2ogpt>python generate.py --base_model=h2oai/h2ogpt-oig-oasst1-512-6_9b --load_8bit=True
Traceback (most recent call last):
  File "C:\H2O\h2ogpt\generate.py", line 26, in <module>
    start_faulthandler()
  File "C:\H2O\h2ogpt\utils.py", line 855, in start_faulthandler
    faulthandler.register(signal.SIGUSR1)
AttributeError: module 'faulthandler' has no attribute 'register'

Can someone enlighten me what I could have done wrong or any potential steps missing?
Thank you very much in advance.

**Comment by winblas** [comment]
same issue with me. i believe faulthandler with register is in python 3.3, intallation is using 3.1. i commented the line 855 in util.py just to get it working.

**Comment by pseudotensor** [comment]
Maybe not compatible with windows, will fix today. Yes can comment out function call for now.  Thanks!
