### ISSUE TITLE
Manual / Question regarding  making & using different user data db's

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#277]
Hi,
I created user date using generate.py from one source (email) of data, then I found that I can use make_db.py and I renamed db_dit_UserData to db_dir_emails and generated another user data from second source (csv) m renamed the db_dir_UserData to db_dir_csv, and then I downloaded wiki db from HuggingFace.
Now, when I'm running :
python generate.py --base_model=llama --score_model=None --langchain_mode=UserData --chunk_size=256 --top_k_docs=3 --visible_langchain_modes="['UserData', 'csv', 'wiki', 'MyData', 'emails']"

I see only UserData and wiki and don't see csv and emails.
During the loading I see that folders were read :

Prep: persist_directory=db_dir_UserData does not exist, regenerating
Chose UserData but user_path is empty/None
Prep: persist_directory=db_dir_csv exists, using
Prep: persist_directory=db_dir_wiki exists, using
Using embedded DuckDB with persistence: data will be stored in: db_dir_wiki
Prep: persist_directory=db_dir_emails exists, using
Using embedded DuckDB with persistence: data will be stored in: db_dir_emails

So, I'm definitely did / doing something wrong , is there any manual that can help ? I can't find it

Thanks

**Comment by slavag** [comment]
Thanks a lot.

**Comment by pseudotensor** [comment]
Hi I’ll keep this issue open as feature request.  Thanks!

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/pull/476
