### ISSUE TITLE
Clarify the embedding model for make db and generate when on a GPU

### ISSUE THREAD

**Issue by hsm207** [h2oai/h2ogpt#278]
In the [README_LangChain](https://github.com/h2oai/h2ogpt/blob/main/docs/README_LangChain.md) docs it is written that one way to run the project is:

```
python make_db.py
python generate.py --base_model=h2oai/h2ogpt-oig-oasst1-512-6_9b --langchain_mode=UserData
```

My understanding of the snippet above is that make_db.py will create the embeddings for the docs using the [sentence-transformers/all-MiniLM-L6-v2](https://github.com/h2oai/h2ogpt/blob/d7617cca5c49312d87a7969c91297f1c4aa914f8/make_db.py#L26)  model  which will embed a doc into a 384 dim vector.

Then, generate.py will use the [hkunlp/instructor-large](https://github.com/h2oai/h2ogpt/blob/d7617cca5c49312d87a7969c91297f1c4aa914f8/generate.py#L346-L349) when running on a GPU to [set up the db](https://github.com/h2oai/h2ogpt/blob/d7617cca5c49312d87a7969c91297f1c4aa914f8/generate.py#L415-L420). This model will embed the query into a 1024 dim vector to do the retrieval.

Is my understanding of the code correct?

**Comment by pseudotensor** [comment]
I see.  There is a bit of complication in the generate vs. make_db.  I'll make it symmetric.

**Comment by pseudotensor** [comment]
27fdea43647818b0ac369732d5bd26f851bbece7
