### ISSUE TITLE
gm models don't stop properly

### ISSUE THREAD

**Issue by arnocandel** [h2oai/h2ogpt#280]
https://533ab9273cfdaf1a7d.gradio.live/

![image_720](https://github.com/h2oai/h2ogpt/assets/6147661/f27b6bfa-0318-435a-b813-81342430db1f)
![image_720](https://github.com/h2oai/h2ogpt/assets/6147661/65580543-a2d5-4e56-95ef-fd9ec53e85ca)
![image_720](https://github.com/h2oai/h2ogpt/assets/6147661/8971e6b4-854d-4fb4-87ee-fd2e93b328f9)
![image_720](https://github.com/h2oai/h2ogpt/assets/6147661/6ce5ff7f-0d9a-44e0-8e3a-4f85192fec6a)

**Comment by arnocandel** [comment]
Prompt: `Write Python code for Fibonacci sequence.`

**Comment by pseudotensor** [comment]
![image](https://github.com/h2oai/h2ogpt/assets/2249614/e8fc3a7a-ed5d-4ed6-937e-9ad2ac29678d)

**Comment by pseudotensor** [comment]
![image](https://github.com/h2oai/h2ogpt/assets/2249614/6b318e4b-74f8-43ab-9ea5-b1b95db6f0f2)

**Comment by pseudotensor** [comment]
with 2048 max_new_tokens:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/2d7ba937-24da-4a9b-a73b-e594dc918115)

**Comment by pseudotensor** [comment]
After changing tokenization stuff a bit, now different answer.  Seems unexpected:


256 tokens:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/a730054d-91c0-4537-98ae-c8b79849b717)


2048:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/f5618760-1743-4391-8f2e-888a0f08d397)

**Comment by pseudotensor** [comment]
Even without padding_side='left" still different but same as with default padding.

256:
![image](https://github.com/h2oai/h2ogpt/assets/2249614/776224e7-1c66-4caa-8c23-15624ba3929c)

2048:
![image](https://github.com/h2oai/h2ogpt/assets/2249614/2e6ab8d2-26ce-4a90-8ae4-0132b5663674)

**Comment by pseudotensor** [comment]
With undoing GenerationConfig changes, still same:

2048:
![image](https://github.com/h2oai/h2ogpt/assets/2249614/1c99c817-7a79-4264-bc50-ce7710d1fed1)

**Comment by pseudotensor** [comment]
2048 back to mostly main code, still diff:


![image](https://github.com/h2oai/h2ogpt/assets/2249614/d8823f42-9a2a-4dcc-925a-f1f8cc21ed34)


```
diff --git a/generate.py b/generate.py
index 44d69b2..6e3576b 100644
--- a/generate.py
+++ b/generate.py
@@ -1208,10 +1208,7 @@ def evaluate(
         tgt_lang = languages_covered()[tgt_lang]
         gen_kwargs.update(dict(forced_bos_token_id=tokenizer.lang_code_to_id[tgt_lang]))
     else:
-        token_ids = ['eos_token_id', 'bos_token_id', 'pad_token_id']
-        for token_id in token_ids:
-            if hasattr(tokenizer, token_id) and getattr(tokenizer, token_id) is not None:
-                gen_kwargs.update({token_id: getattr(tokenizer, token_id)})
+        gen_kwargs.update(dict(pad_token_id=tokenizer.eos_token_id))
 
     decoder_kwargs = dict(skip_special_tokens=True,
                           clean_up_tokenization_spaces=True)

```

**Comment by pseudotensor** [comment]
Went back all the way to main, still same.  Must be something else different.  Not this PR.  Must be some dependencies like transformer version changed things, surprisingly.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/d5a9ecd0-faf6-4220-9416-4abbccdcf5b9)
