### ISSUE TITLE
Set user_path=user_path but files are uploaded in tmp/gradio/...

### ISSUE THREAD

**Issue by bibi-b** [h2oai/h2ogpt#291]
Hi there,

as the topic says. I run the script on a headless server and open the URL on another PC within my network. Maybe that is why the files do not upload in the given path?

Thanks

**Comment by pseudotensor** [comment]
That would be when you choose to add file/text/etc. to Scratch MyData collection instead of Shared UserData collection

**Comment by bibi-b** [comment]
@pseudotensor 
This is what I do: I click on "Hochladen" (=Upload) and select a PDF.
![Bildschirmfoto 2023-06-13 um 20 17 59](https://github.com/h2oai/h2ogpt/assets/59328072/0ee8ae15-10c6-4234-8212-48b00f499679)
When the file is uploaded I click on "Add files to UserData". 
The files are listed unter tmp/gradio
![Bildschirmfoto 2023-06-13 um 20 19 42](https://github.com/h2oai/h2ogpt/assets/59328072/df5bee64-db40-4c6e-a8a8-6957a2bf5142)

**Comment by bibi-b** [comment]
@pseudotensor 
May be that is why: I found this Info when starting...

Using Model llama
Prep: persist_directory=db_dir_UserData exists, **user_path=user_path passed,** adding any changed or new documents

**Comment by pseudotensor** [comment]
You mean you previously uploaded to UserData, and it's still re-using.  You can delete db_dir_UserData to get rid of it.

However, that '/tmp/...` path is only used if upload to the temporary MyData.

**Comment by pseudotensor** [comment]
Ah, sorry, the `/tmp/...` is just where the file was uploaded and placed by gradio.

Once processed as file for database in UserData, it'll be in the database and that reference location will still be there.

I should move the file to user_path if it was passed, yes.

**Comment by pseudotensor** [comment]
Thanks for great catch.  Nothing was broken, but makes more sense to move that temporary file to user_path if it was passed.
