### ISSUE TITLE
error :model weights are not tied

### ISSUE THREAD

**Issue by ildongo** [h2oai/h2ogpt#299]
Hi,i encounter the following error after i launch generate.py....someone know how can i fix it? im under ubuntu 22.04 LTS. Thank you. i will attach the terminal output:

python generate.py 
Using Model h2oai/h2ogpt-oig-oasst1-512-6_9b
Downloading (…)lve/main/config.json: 100%|█████| 779/779 [00:00<00:00, 9.08MB/s]
Downloading (…)okenizer_config.json: 100%|█████| 264/264 [00:00<00:00, 3.12MB/s]
Downloading (…)/main/tokenizer.json: 100%|█| 2.11M/2.11M [00:00<00:00, 3.46MB/s]
Downloading (…)cial_tokens_map.json: 100%|████| 99.0/99.0 [00:00<00:00, 536kB/s]
Downloading (…)model.bin.index.json: 100%|██| 42.0k/42.0k [00:00<00:00, 112MB/s]
Downloading (…)l-00001-of-00003.bin: 100%|█| 5.03G/5.03G [20:41<00:00, 4.05MB/s]
Downloading (…)l-00002-of-00003.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.02G/5.02G [28:27<00:00, 2.94MB/s]
Downloading (…)l-00003-of-00003.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.80G/3.80G [20:26<00:00, 3.10MB/s]
Downloading shards: 100%|█████████████████████| 3/3 [1:09:37<00:00, 1392.42s/it]██████████████████████████████████████████████████████████████████████████████████████| 3.80G/3.80G [20:26<00:00, 3.21MB/s]
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Loading checkpoint shards:  33%|███████████████████████████████████████████████                                                                                              | 1/3 [00:08<00:16,  8.24s/it]Killed

**Comment by pseudotensor** [comment]
Killed means ran out of system RAM.

The 
```
The model weights are not tied. Please use the tie_weights method before using the infer_auto_device function.
```
is just a warning.

**Comment by pseudotensor** [comment]
16GB GPU RAM or system ram?  If 16 GPU RAM, how much system ram?

If you have at least 15GB *free* RAM, and don't have a GPU, then should do wizardlm llama based one.
 
```
python generate.py --base_model='llama' --prompt_type=wizard2 --score_model=None --langchain_mode='UserData' --user_path=user_path
```

**Comment by ildongo** [comment]
System RAM..sorry..im a student and im working on a laptop.yes i need to run on CPU,because my GPU(3060 Mobile)has 6 GB of VRAM..My system RAM is 16 GB

**Comment by ildongo** [comment]
> 16GB GPU RAM or system ram? If 16 GPU RAM, how much system ram?
> 
> If you have at least 15GB _free_ RAM, and don't have a GPU, then should do wizardlm llama based one.
> 
> ```
> python generate.py --base_model='llama' --prompt_type=wizard2 --score_model=None --langchain_mode='UserData' --user_path=user_path
> ```

There is a way to use Gradio UI with cpu?

**Comment by ildongo** [comment]
> 16GB GPU RAM or system ram? If 16 GPU RAM, how much system ram?
> 
> If you have at least 15GB _free_ RAM, and don't have a GPU, then should do wizardlm llama based one.
> 
> ```
> python generate.py --base_model='llama' --prompt_type=wizard2 --score_model=None --langchain_mode='UserData' --user_path=user_path
> ```

ok Professor,i solve with that ,thank you. now i have this error: name 'NullContext' is not defined. Im a student of medicine and i need this for a project

**Comment by pseudotensor** [comment]
Yes, gradio UI works fine with cpu.

If the default llama model is too big, you can try one of the other ones here: https://huggingface.co/TheBloke/WizardLM-7B-uncensored-GGML/tree/main

You can choose a smaller model by size, and then change:

```
# GPT4ALl LLaMa type, supporting version 2 quantization, here from model explorer choice so downloads
model_name_gpt4all_llama=ggml-wizardLM-7B.q4_2.bin
```
with something new for `ggml-wizardLM-7B.q4_2.bin`
