### ISSUE TITLE
GPU mode with 8gb vram

### ISSUE THREAD

**Issue by mssc89** [h2oai/h2ogpt#309]
Readme states that 6.9B model in 8-bit mode uses 7gb of gpu vram, so i decided to test it on 8gb p104-100 (virtually same as gtx1070). In both 16-bit and 8-bit mode, generate.py throws 
`OutOfMemoryError: CUDA out of memory. Tried to allocate 158.00 MiB (GPU 0; 7.93 GiB total capacity; 7.37 GiB 
already allocated; 78.19 MiB free; 7.39 GiB reserved in total by PyTorch)`
error. Is readme wrong about minimum vram size or am I doing something wrong? I've tested it with both `oig-oasst1-512-6_9b` and `falcon-7b` models.

**Comment by pseudotensor** [comment]
Hi @mssc89 .  Please give the full command you are running.

Note that for documents, Instruct-large uses more GPU than the Mini one, so if you are limited on ram, I recommend that as in the readme.md, i.e.:

```
python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --score_model=None --load_8bit=True --langchain_model='MyData'
```
This also disables the score model that eats GPU too.

This uses 8344MB of GPU on my system to start-up things.

So let's try 6.9B:
```
python generate.py --base_model=h2oai/h2ogpt-oig-oasst1-512-6_9b --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --score_model=None --load_8bit=True
```

This uses 8314MB.  So still too much for your 8GB.

So let's try 4-bit:
```
python generate.py --base_model=h2oai/h2ogpt-oig-oasst1-512-6_9b --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --score_model=None --load_4bit=True
```

This only uses 5698MB to startup.  And it's not too slow.

So I'd recommend probably 7b model with 4-bit:

```
python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --score_model=None --load_4bit=True
```

This uses 5796MB to startup and up to 6046MB to ask a basic question.

Back to langchain, can do:

```
python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --score_model=None --load_4bit=True --langchain_mode='MyData'
```
This uses 5796MB to startup, then soon drops to 5074MB after torch cache is cleared.  Asking a simple question uses up to 6046MB again.  Adding a document uses no more new GPU memory.
