### ISSUE TITLE
Add vLLM support

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#312]
https://www.reddit.com/r/LocalLLaMA/comments/14em713/just_released_vllm_inference_library_that/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=2&utm_term=1

[Just released - vLLM inference library that accelerates HF Transformers by 24x](https://www.reddit.com/r/LocalLLaMA/comments/14em713/just_released_vllm_inference_library_that/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=2&utm_term=1)
Posted in r/LocalLLaMA by u/yanjb • 48 points and 8 comments

LLM is an open-source LLM inference and serving library that accelerates HuggingFace Transformers by 24x and powers Vicuna and Chatbot Arena.
Github: https://github.com/vllm-project/vllmBlog post: https://vllm.ai/
Edit - it wasn't "just released" apparently it's live for several days
https://preview.redd.it/nzceocfbg87b1.png?width=1532&format=png&auto=webp&v=enabled&s=30bcee178214cb8c88e05c37db1b2215c0a1bf73

**Comment by pseudotensor** [comment]
Faster than TGI by 3-4x, does it have continuous batching?

**Comment by rohitnanda1443** [comment]
Please recheck the installation guide at https://github.com/h2oai/h2ogpt/blob/main/docs/README_InferenceServers.md 

In the local install I think we missed out: 

pip install vllm

Due to which when one runs the inference server;  error is given that Module vllm not found.

**Comment by pseudotensor** [comment]
@rohitnanda1443 The block for installing it is there, but it's a bit old and setup for helping Mixtral work when it wasn't in vLLM yet.  I cleaned it up.
