### ISSUE TITLE
Where may I download WizardLM-7B-uncensored.ggmlv3.q8_0.bin

### ISSUE THREAD

**Issue by Marcos-gi** [h2oai/h2ogpt#314]
Hi, Where may I download this model and what do I must to change it to ggml-gpt4all-l13b-snoozy.bin?

/home/marcos/h2ogpt/generate.py:548 in main                                                      │
│                                                                                                  │
│    545 │   │   │   model_dict['prompt_dict'] = prompt_dict = model_dict.get('prompt_dict', prom  │
│    546 │   │   │   all_kwargs = locals().copy()                                                  │
│    547 │   │   │   if base_model and not login_mode_if_model0:                                   │
│ ❱  548 │   │   │   │   model0, tokenizer0, device = get_model(reward_type=False,                 │
│    549 │   │   │   │   │   │   │   │   │   │   │   │   │      **get_kwargs(get_model, exclude_n  │
│    550 │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   **all_kwargs))        │
│    551 │   │   │   else:                                                                         │
│                                                                                                  │
│ /home/marcos/h2ogpt/generate.py:747 in get_model                                                 │
│                                                                                                  │
│    744 │   assert not inference_server, "Malformed inference_server=%s" % inference_server       │
│    745 │   if base_model in non_hf_types:                                                        │
│    746 │   │   from gpt4all_llm import get_model_tokenizer_gpt4all                               │
│ ❱  747 │   │   model, tokenizer, device = get_model_tokenizer_gpt4all(base_model)                │
│    748 │   │   return model, tokenizer, device                                                   │
│    749 │                                                                                         │
│    750 │   if lora_weights is not None and lora_weights.strip():                                 │
│                                                                                                  │
│ /home/marcos/h2ogpt/gpt4all_llm.py:48 in get_model_tokenizer_gpt4all                             │
│                                                                                                  │
│    45 │   │   func_names = list(inspect.signature(Llama.__init__).parameters)                    │
│    46 │   │   model_kwargs = {k: v for k, v in model_kwargs.items() if k in func_names}          │
│    47 │   │   model_kwargs['n_ctx'] = int(model_kwargs['n_ctx'])                                 │
│ ❱  48 │   │   model = Llama(model_path=model_path, **model_kwargs)                               │
│    49 │   elif base_model in "gpt4all_llama":                                                    │
│    50 │   │   if 'model_name_gpt4all_llama' not in model_kwargs and 'model_path_gpt4all_llama'   │
│    51 │   │   │   raise ValueError("No model_name_gpt4all_llama or model_path_gpt4all_llama in   │
│                                                                                                  │
│ /home/marcos/h2ogpt/lib/python3.10/site-packages/llama_cpp/llama.py:281 in __init__              │
│                                                                                                  │
│    278 │   │   ### DEPRECATED ###                                                                │
│    279 │   │                                                                                     │
│    280 │   │   if not os.path.exists(model_path):                                                │
│ ❱  281 │   │   │   raise ValueError(f"Model path does not exist: {model_path}")                  │
│    282 │   │                                                                                     │
│    283 │   │   self.ctx = llama_cpp.llama_init_from_file(                                        │
│    284 │   │   │   self.model_path.encode("utf-8"), self.params                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Model path does not exist: WizardLM-7B-uncensored.ggmlv3.q8_0.bin
Exception ignored in: <function Llama.__del__ at 0x7eff70f41510>
Traceback (most recent call last):
  File "/home/marcos/h2ogpt/lib/python3.10/site-packages/llama_cpp/llama.py", line 1431, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'

**Comment by pseudotensor** [comment]
It's in the readme:

For 7B case, download [WizardLM-7B-uncensored.ggmlv3.q8_0.bin](https://huggingface.co/TheBloke/WizardLM-7B-uncensored-GGML/blob/main/WizardLM-7B-uncensored.ggmlv3.q8_0.bin) into local path. Then one sets model_path_llama in .env_gpt4all, which is currently the default.
