### ISSUE TITLE
open in local

### ISSUE THREAD

**Issue by Jeff1933** [h2oai/h2ogpt#316]
Hi,why can't I open the url (http://0.0.0.0:7860)

**Comment by pseudotensor** [comment]
@Jeff1933 Did you resolve your issue?  I was just going through issues.

**Comment by Jeff1933** [comment]
Yes,I have resolve this problem.

**Comment by Jeff1933** [comment]
Yes,I have resolve this problem.And I ask for how to remove the sources which already exist?

**Comment by pseudotensor** [comment]
```
rm -rf db_dirs_*
```
to remove old databases.  Or specifically for UserData:
```
rm -rf db_dir_UserData
```

Caution:
```
rm -rf user_path
```
to remove *your* data sources.

**Comment by Jeff1933** [comment]
Thank you for your reply.

**Comment by Jeff1933** [comment]
By the way,could you advise any models in TheBloke which support the cpu, thanks.

**Comment by pseudotensor** [comment]
Ya in readme:


So, for chatting, a better instruct fine-tuned LLaMa-based model for llama.cpp can be downloaded from [TheBloke](https://huggingface.co/TheBloke).  For example, [13B WizardLM Quantized](https://huggingface.co/TheBloke/wizardLM-13B-1.0-GGML) or [7B WizardLM Quantized](https://huggingface.co/TheBloke/WizardLM-7B-uncensored-GGML).  TheBloke has a variety of model types, quantization bit depths, and memory consumption.  Choose what is best for your system's specs.  However, be aware that LLaMa-based models are not [commercially viable](docs/FAQ.md#commercial-viability).

For 7B case, download [WizardLM-7B-uncensored.ggmlv3.q8_0.bin](https://huggingface.co/TheBloke/WizardLM-7B-uncensored-GGML/blob/main/WizardLM-7B-uncensored.ggmlv3.q8_0.bin) into local path.  Then one sets `model_path_llama` in `.env_gpt4all`, which is currently the default.

**Comment by Jeff1933** [comment]
Hi,When I change my model from WizardLM-7B-uncensored.ggmlv3.q8_0.bin to WizardLM-7B-uncensored.ggmlv3.q5_K_S.bin,it return a ValueError: Model path does not exist: ‪E:\WizardLM-7B-uncensored.ggmlv3.q5_K_S.bin.How should I do?

**Comment by Jeff1933** [comment]
I want to train the model that can let it to identify some Target objects on a picture,can I do that?

**Comment by pseudotensor** [comment]
h2oGPT is only able to train text.  One would need to use a different platform to train for images.

**Comment by Jeff1933** [comment]
Ok, I know, how can I train text?

**Comment by pseudotensor** [comment]
This has the steps: https://github.com/h2oai/h2ogpt/blob/main/docs/FINETUNE.md

**Comment by Jeff1933** [comment]
Thanks a lot
