### ISSUE TITLE
Add support for mosaicml/mpt-30b and mosaicml/mpt-30b-instruct

### ISSUE THREAD

**Issue by arnocandel** [h2oai/h2ogpt#319]
https://huggingface.co/mosaicml/mpt-30b Apache 2.0
https://huggingface.co/mosaicml/mpt-30b-instruct CC-SA

```
MPTForCausalLM(
  (transformer): MPTModel(
    (wte): SharedEmbedding(50432, 7168)
    (emb_drop): Dropout(p=0, inplace=False)
    (blocks): ModuleList(
      (0-47): 48 x MPTBlock(
        (norm_1): LPLayerNorm((7168,), eps=1e-05, elementwise_affine=True)
        (attn): MultiheadAttention(
          (Wqkv): Linear(in_features=7168, out_features=21504, bias=False)
          (out_proj): Linear(in_features=7168, out_features=7168, bias=False)
        )
        (norm_2): LPLayerNorm((7168,), eps=1e-05, elementwise_affine=True)
        (ffn): MPTMLP(
          (up_proj): Linear(in_features=7168, out_features=28672, bias=False)
          (act): GELU(approximate='none')
          (down_proj): Linear(in_features=28672, out_features=7168, bias=False)
        )
        (resid_attn_dropout): Dropout(p=0, inplace=False)
        (resid_ffn_dropout): Dropout(p=0, inplace=False)
      )
    )
    (norm_f): LPLayerNorm((7168,), eps=1e-05, elementwise_affine=True)
  )
)
```

**Comment by arnocandel** [comment]
`CUDA_VISIBLE_DEVICES=0 python finetune.py --base_model=mosaicml/mpt-30b --num_epochs=0.01 --lora_target_modules=['Wqkv'] --train_4bit=True --micro_batch_size=1 --batch_size=1`

fails with:
`ValueError: MPTForCausalLM does not support gradient checkpointing.`

**Comment by arnocandel** [comment]
TGI support: https://github.com/huggingface/text-generation-inference/issues/290

**Comment by monuminu** [comment]
anyplan on supporting mosaicml/mpt-30b-instruct ?

**Comment by pseudotensor** [comment]
@arnocandel Would you mind adding the prompt to prompter.py and the model to prompt_type_to_model_name?  Is it the same as older mosaicml?  Then easy.

**Comment by arnocandel** [comment]
This works out of the box: `python generate.py --base_model=mosaicml/mpt-30b-instruct`

**Comment by pseudotensor** [comment]
MPT is now supported for TGI: https://github.com/huggingface/text-generation-inference/pull/514

Just avoids flash attention, but they say that's not important for inference: https://github.com/huggingface/text-generation-inference/issues/491

**Comment by pseudotensor** [comment]
Looks like 0.9.1 has non flash MPT: https://github.com/huggingface/text-generation-inference/releases, released 10 hours ago

**Comment by pseudotensor** [comment]
62b41ead1bcb67cbf6556f455f6a5cf8bfb72d0b
