### ISSUE TITLE
error while running generate.py

### ISSUE THREAD

**Issue by Aashna2022** [h2oai/h2ogpt#340]
I got this error while running   python generate.py --base_model='llama' --prompt_type=wizard2 --score_model=None --langchain_mode='UserData' --user_path=user_path

ValueError: Model path does not exist: WizardLM-7B-uncensored.ggmlv3.q8_0.bin
Exception ignored in: <function Llama.__del__ at 0x00000214CF6BFD00>
Traceback (most recent call last):
  File "D:\h2ogpt\venv\lib\site-packages\llama_cpp\llama.py", line 1431, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'

How to resolve this ? And also I want to use gpt4all using cpu so how can I do that?

**Comment by pseudotensor** [comment]
Hi, the "error" at end is llama_cpp's fault.  But that's just a cascade and a known issue.

The actual issue is the `ValueError: Model path does not exist: WizardLM-7B-uncensored.ggmlv3.q8_0.bin`

Follow the readme where there's a line to download that file.
