### ISSUE TITLE
Error when running docker container with docker-compose

### ISSUE THREAD

**Issue by angel1st** [h2oai/h2ogpt#370]
Image built successfully, however, during container spin up, I have got, the following error:

`Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: WSL environment detected but no adapters were found: unknown`

To give some context, I am running Docker Desktop under Windows 10.

**Comment by angel1st** [comment]
After installing the most recent NVIDIA Windows GPU Driver, container starts, however, http://localhost:7860/ doesn't respond. 
This is container's log:

`Downloading (…)lve/main/config.json: 100%|██████████| 930/930 [00:00<00:00, 1.42MB/s]
Downloading (…)okenizer_config.json: 100%|██████████| 619/619 [00:00<00:00, 6.26MB/s]
Downloading (…)olve/main/vocab.json: 100%|██████████| 798k/798k [00:00<00:00, 1.57MB/s]
Downloading (…)olve/main/merges.txt: 100%|██████████| 456k/456k [00:00<00:00, 1.45MB/s]
Downloading (…)/main/tokenizer.json: 100%|██████████| 1.37M/1.37M [00:00<00:00, 2.19MB/s]
Downloading (…)in/added_tokens.json: 100%|██████████| 4.04k/4.04k [00:00<00:00, 9.86MB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████| 357/357 [00:00<00:00, 3.13MB/s]
Downloading pytorch_model.bin:  10%|█         | 2.49G/24.2G [02:19<21:45, 16.6MB/s]2023-07-01T15:28:55.300542918Z Using Model eleutherai/gpt-j-6b
2023-07-01 18:31:43 Using Model eleutherai/gpt-j-6b`

**Comment by pseudotensor** [comment]
@achraf-mer Please take a look and see if your new stuff will fix.  Thanks!

**Comment by achraf-mer** [comment]
@angel1st can you please confirm whether CUDA is enabled on your Windows machine like mentioned here: https://learn.microsoft.com/de-de/windows/ai/directml/gpu-cuda-in-wsl

Also, can try running a simple cuda container as mentioned in section 2.7.4 here: https://docs.nvidia.com/cuda/archive/11.4.0/wsl-user-guide/index.html

Please note that we are starting to publish public docker images and you can find a recipe here on how to pull/run: https://github.com/h2oai/h2ogpt/pull/381#issue-1786635375,

**Comment by angel1st** [comment]
@achraf-mer - I have ran cuba container locally, please see below the output:
````
Run "nbody -benchmark [-numbodies=<numBodies>]" to measure performance.
        -fullscreen       (run n-body simulation in fullscreen mode)
        -fp64             (use double precision floating point values for simulation)
        -hostmem          (stores simulation data in host memory)
        -benchmark        (run benchmark to measure performance)
        -numbodies=<N>    (number of bodies (>= 1) to run in simulation)
        -device=<d>       (where d=0,1,2.... for the CUDA device to use)
        -numdevices=<i>   (where i=(number of CUDA devices > 0) to use for simulation)
        -compare          (compares simulation results running once on the default GPU and once on the CPU)
        -cpu              (run n-body simulation on the CPU)
        -tipsy=<file.bin> (load a tipsy model file for simulation)

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.

> Windowed mode
> Simulation data stored in video memory
> Single precision floating point simulation
> 1 Devices used for simulation
GPU Device 0: "Turing" with compute capability 7.5

> Compute 7.5 CUDA device: [NVIDIA GeForce RTX 2060]
30720 bodies, total time for 10 iterations: 69.761 ms
= 135.278 billion interactions per second
= 2705.557 single-precision GFLOP/s at 20 flops per interaction
````

**Comment by achraf-mer** [comment]
@angel1st we have published a new image as with recent changes at `docker pull gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0`.
Can you please try to run it with the recipe described at: https://github.com/h2oai/h2ogpt/blob/main/docs/README_DOCKER.md#run-h2ogpt-using-docker. I expect this to work, but if you have issues, then likely problems loading models, so a log output of your container startup will help to identify the issue.

**Comment by achraf-mer** [comment]
The docker compose have been rewored to fix some lingering issues with permissions and is not using the latest image, closing.
