### ISSUE TITLE
Interested in contributing to H2O gpt

### ISSUE THREAD

**Issue by shivance** [h2oai/h2ogpt#371]
I'm interested in contributing to this repository but cannot find the perfect place to start.
I've experience in building LLMs from scratch.

Would like to ask if there is any feature that you folks are working on, where I can contribute?

cc : @pseudotensor

**Comment by pseudotensor** [comment]
Hi, feel free to check out the issues.  There's a large scope of tasks, from bug fixing to new fine-tuning models.  It's kind of chicken-and-egg.  You should review and see if there are a class of things you would like to do and are capable of doing.

Thanks!

**Comment by pseudotensor** [comment]
Let me know if you have more questions, will close this issue for now.
