### ISSUE TITLE
Number of requested results 1000 is greater than number of elements in index 3, updating n_results = 3

### ISSUE THREAD

**Issue by Haxeebraja** [h2oai/h2ogpt#383]
I am trying to run h2ogpt on google colab:

Followed running the following commands but getting error:
!pip3 install virtualenv
!sudo apt-get install -y build-essential gcc python3.10-dev
!virtualenv -p python3 h2ogpt
!source h2ogpt/bin/activate
!git clone https://github.com/h2oai/h2ogpt.git
!cd h2ogpt
!pip uninstall -y pandoc pypandoc pypandoc-binary
!for fil in requirements.txt reqs_optional/requirements_optional_langchain.txt reqs_optional/requirements_optional_gpt4all.txt reqs_optional/requirements_optional_langchain.gpllike.txt reqs_optional/requirements_optional_langchain.urls.txt ; do pip install -r $fil ; done

## Data file placed in user_path
!python make_db.py --user_path=user_path --collection_name=UserData
!python generate.py --base_model=gptj --cli=True --langchain_mode=UserData

It error out: Number of requested results 1000 is greater than number of elements in index 3, updating n_results = 3

**Comment by pseudotensor** [comment]
Hi, it's not actually an error, but a warning from chroma.  It might be able to be disabled by disabling all logger warnings.

**Comment by Haxeebraja** [comment]
This warning is followed by :
TypeError: GPT4All.generate() got an unexpected keyword argument 'n_ctx'

**Comment by Haxeebraja** [comment]
Moreover, no answers are returned (returns source without a response) while running it on UI with the following:
python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --score_model=None --load_8bit=True --langchain_mode=UserData

or

python generate.py --base_model=h2oai/h2ogpt-oasst1-512-12b --load_8bit=True  --score_model=None --langchain_mode=UserData

**Comment by pseudotensor** [comment]
> This warning is followed by : TypeError: GPT4All.generate() got an unexpected keyword argument 'n_ctx'

Will check, but if your versions of all packages are the same, we have many tests of GPT4All.  So I'd suspect you have different versions of some packages.  Related: https://github.com/hwchase17/langchain/pull/7093
