### ISSUE TITLE
Restrict the model to use only documents in UserData

### ISSUE THREAD

**Issue by Haxeebraja** [h2oai/h2ogpt#388]
Restrict responses to only the information in the provided documents.
Can return a generic response if the answer is not available.

**Comment by pseudotensor** [comment]
Hi, if you select UserData in UI, it'll only use that.  But I think what you mean is if no references are found, and shared, then it shouldn't go to the LLM at all.  But I guess one knows if no references are listed then that is the case.  Maybe give more details about why etc.

**Comment by Haxeebraja** [comment]
For example in case of a domain specific chatbot, it should not be answering generic questions. How can I restrict the chatbot to only share domain information in that is available in the documents.

**Comment by gerhean** [comment]
You can try adding "only answer domain questions in that is available in the input" or something like that in the prompt. I'm not sure how to configure it, but you can change the default prompt in 'prompter.py".

**Comment by pseudotensor** [comment]
It now says things like:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/ded83393-f396-4c12-a02a-bf848d254796)


And if you have documents but scores are such that nothing is relevant (harder with instructor-large), then it will say 
```
'No relevant documents to query.'
```

Similar for summarize.
