### ISSUE TITLE
problem initiating requirement.txt files, M1 Mac

### ISSUE THREAD

**Issue by rubenIGM** [h2oai/h2ogpt#395]
hallo I could not run -r requirements.txt as batch due to following issue:
I had to import modules one by one apon:

 ModuleNotFoundError: No module named 'tabulate'

-r requirements.txt file would not be read in...

Collecting textstat==0.7.3 (from -r requirements.txt (line 46))
  Using cached textstat-0.7.3-py3-none-any.whl (105 kB)
ERROR: Could not find a version that satisfies the requirement pypandoc_binary==1.11 (from versions: none)
ERROR: No matching distribution found for pypandoc_binary==1.11

Could you give more detail how to run h2ogpt on ARM M1 MAC, some how this falls short
Thx

**Comment by pseudotensor** [comment]
@Mathanraj-Sharma You have M1 mac.  Can you help?  If you have a small edit (you spoke of) can you make PR?  Thanks!

**Comment by Mathanraj-Sharma** [comment]
@pseudotensor will create a PR for my tweaks for M1
