### ISSUE TITLE
Allow customized collection for vector database (Chroma). 

### ISSUE THREAD

**Issue by gerhean** [h2oai/h2ogpt#398]
I have two folders of pdf, and I would like to ask questions on each group without one leaking into the other. But there is no way to switch between the two groups easily, I have to delete the database and reindex everything.

Hence, it would be nice to have some UI component to switch between different user_path.

For now, I have implemented `collection_name` as a cli argument to change which collection to use in my local copy. Would be happy to make it a PR if needed.

**Comment by pseudotensor** [comment]
@gerhean It's a great idea.  I'll try to add today: https://github.com/h2oai/h2ogpt/issues/277

**Comment by pseudotensor** [comment]
Can now do this:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/ee964d5b-a16b-432e-ba4f-571778d4a67d)
