### ISSUE TITLE
cookie based auth to preserve access to original db/docs so not lost, e.g. on gpt.h2o.ai

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#400]
https://stackoverflow.com/questions/66836600/cookie-based-authentication-in-fastapi
https://www.gradio.app/guides/sharing-your-app#mounting-within-another-fastapi-app
https://github.com/gradio-app/gradio/issues/461

**Comment by pseudotensor** [comment]
Or google auth

https://github.com/gradio-app/gradio/issues/2790

**Comment by fk0000** [comment]
Where should this source code file be placed?

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/pull/618

**Comment by tares003** [comment]
> Where should this source code file be placed?

this is a separate file, just make main.py or something similar

**Comment by pseudotensor** [comment]
This issue was closed because we already support native gradio way with --auth related options.  See gen.py.
