### ISSUE TITLE
CPU run apache2 licensed model

### ISSUE THREAD

**Issue by wanfuse123** [h2oai/h2ogpt#410]
what code downloads and installs the apache2 licenced models for CPU's I see no separate switch for enabling and disabling the CPU/GPU runtime

also is there a list of models this works with? or a way to query for the models available that also says what they are for?

Keep up the great work! much appreciated!

**Comment by pseudotensor** [comment]
If you mean llama.cpp and GPT4All CPU models, then there's a specific base_model for 'llama' and 'gptj' and 'gpt4all_llama'.  Using those models triggers their own loaders, although if one builds llama-cpp-python with CUDA support, as in GPU docs, then it'll use GPU.

If you have a GPU model but want to use CPU, you can but it'll be slow and use alot of memory, but you can run `CUDA_VISIBLE_DEVICES= python generate.py ...` to do that.
