### ISSUE TITLE
Hosted API somewhere? 

### ISSUE THREAD

**Issue by bruno-oliveira** [h2oai/h2ogpt#415]
Hi,
I've seen that there was work done to create a kind of completions endpoint similar to ChatGPT. That's absolutely awesome.

However it seems like it was running locally in the example provided there.

Is there a URL or examples of using a publicly available endpoint with this to integrate it into downstream applications?

I'm really loving the performance of this and we're now experimenting with this at my day job. I think this could be a great alternative to openai. Is there any docs or road map with details about this?

**Comment by arnocandel** [comment]
https://github.com/h2oai/h2ogpt#h2ogpt has links to live demos, but there is no hosted endpoint with per-token pricing for general consumption yet. If this is something you are interested in, please reach out to sales@h2o.ai.
