### ISSUE TITLE
Query through documents

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2ogpt#426]
After uploading the pdf document in user_path and run the following command 'python generate.py --base_model='llama' --prompt_type=wizard2 --score_model=None --langchain_mode='UserData' --user_path=user_path'  i got a error '
chroma_collection = cls(
TypeError: Chroma.__init__() got an unexpected keyword argument 'anonymized_telemetry' so can i resolve this error.

**Comment by pseudotensor** [comment]
Since h2oGPT in testing (about 220 tests taking 3 hours) doesn't see this, I would think maybe you are using a mixed environment with different packages than h2oGPT requires.  E.g. probably old chroma.

The chroma we use has this as option: https://docs.trychroma.com/telemetry#opting-out

Re-open issue if you think something else is wrong.  Thanks!

**Comment by ivannovak** [comment]
For anyone coming across this in the future, I ran into the same issue and the fix was to install the Document Q/A Dependencies as documented: https://github.com/h2oai/h2ogpt/blob/main/docs/README_MACOS.md#document-qa-dependencies

**Comment by pseudotensor** [comment]
Hi @ivannovak , which step exactly was missing or confusing?

**Comment by llmwesee** [comment]
> Since h2oGPT in testing (about 220 tests taking 3 hours) doesn't see this, I would think maybe you are using a mixed environment with different packages than h2oGPT requires. E.g. probably old chroma.
> 
> The chroma we use has this as option: https://docs.trychroma.com/telemetry#opting-out
> 
> Re-open issue if you think something else is wrong. Thanks!

My problem was solved when i do fresh installation in new virtual environment by following instruction in updated readme.md file.

**Comment by pseudotensor** [comment]
Ok great, makes sense.  It has to be different langchain in each case.

**Comment by llmwesee** [comment]
> Ok great, makes sense. It has to be different langchain in each case.

Please help me to solve this problem.

https://github.com/h2oai/h2ogpt/issues/430#issue-1802286071

**Comment by ivannovak** [comment]
@pseudotensor, the documentation was complete, but my familiarity was lacking is all :) I didn't understand what "Document Q/A" meant when initially setting things up. Once I wanted to play around with documents, I was struggling and eventually landed back at the docs realizing that there was a separate section for interpreting Documents!

**Comment by pseudotensor** [comment]
Got it, thanks!
