### ISSUE TITLE
Error: Running in offline mode without internet connection.

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2ogpt#430]
When i hit the generate.py after doing all the instillation and running it without internet connection it throws a following error after some time.
```
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't 
find it in the cached files and it looks like llama is not the path to a directory 
containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 
'https://huggingface.co/docs/transformers/installation#offline-mode'.
 
```
So how can i resolve this error because my top priority is run h2ogpt offline without internet connection to querying throw documents. 

![Screenshot from 2023-07-13 11-42-59](https://github.com/h2oai/h2ogpt/assets/137979399/4f63798a-7ab2-429f-8462-cb922e4c1dab)

**Comment by Mathanraj-Sharma** [comment]
@llmwesee you can point to your local model file using `--model_path_llama`

```bash
python generate.py --model_path_llama=./WizardLM-7B-uncensored-GGML --cli=True
```

also, you can set `--local_files_only=True` to avoid trying to HF for models. 

@pseudotensor please correct me if I am wrong.

**Comment by pseudotensor** [comment]
Please see the offline docs: https://github.com/h2oai/h2ogpt/blob/main/docs/README_offline.md

Let me know...

**Comment by llmwesee** [comment]
> --local_files_only=True

I tried but it didn't work for me when i hit generate.py in CPU using WizardLM-7B-uncensored-GGML.

**Comment by llmwesee** [comment]
> Please see the offline docs: https://github.com/h2oai/h2ogpt/blob/main/docs/README_offline.md
> 
> Let me know...

For offline mode in which script file I should put all these code for using WizardLM-7B-uncensored-GGML. in CPU and document question answering:
1. Download model and tokenizer of choice
f```
rom transformers import AutoTokenizer, AutoModelForCausalLM
model_name = 'TheBloke/WizardLM-7B-uncensored-GGML'
model = AutoModelForCausalLM.from_pretrained(model_name)
model.save_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.save_pretrained(model_name)
```
2.Download reward model, unless pass --score_model='None' to generate.py
# and reward model
```
reward_model = 'OpenAssistant/reward-model-deberta-v3-large-v2'
from transformers import AutoModelForSequenceClassification, AutoTokenizer
model = AutoModelForSequenceClassification.from_pretrained(reward_model)
model.save_pretrained(reward_model)
tokenizer = AutoTokenizer.from_pretrained(reward_model)
tokenizer.save_pretrained(reward_model)

```
3.For LangChain support, download embedding model:
```
hf_embedding_model = "sentence-transformers/all-MiniLM-L6-v2"
model_kwargs = 'cpu'
from langchain.embeddings import HuggingFaceEmbeddings
embedding = HuggingFaceEmbeddings(model_name=hf_embedding_model, model_kwargs=model_kwargs)
```

**Comment by pseudotensor** [comment]
Ok, I'll check on it.

**Comment by llmwesee** [comment]
Sure, I'll wait for it!

**Comment by a3nima** [comment]
> `--model_path_llama`
> 
> ```shell
> python generate.py --model_path_llama=./WizardLM-7B-uncensored-GGML --cli=True
> ```
> 
> also, you can set `--local_files_only=True` to avoid trying to HF for models.

Is there a documentation /list of the start parameters for generatel.py? Would be really interesting!

Can --model_path_... and --local_files_only be used to have all the models in a directory outside C:\  downloaded manually or already existing from another application that uses these models as well?

**Comment by pseudotensor** [comment]
```
python generate.py --help
```
shows all the parameters and their explanation and details, just what sits in src/gen.py and the way Fire package works.

**Comment by l3Lex** [comment]
Yeah if you can help out with the resolving of this would be very much appreciated

**Comment by pseudotensor** [comment]
@l3Lex What issue are you hitting?  Getting fully offline working?

Should just be able to one-time get all files loaded into ~/.cache (or for GGML files download manually) and once use product a bit generically, then after have all one needs for offline.

Downloading each piece is more difficult due to the local vs. .cache structure in finding all the files.

**Comment by l3Lex** [comment]
What do you mean by this can you expand a little bit more? I am trying to use the GGML files / model versions.

**Comment by pseudotensor** [comment]
For general offline, see updates here: https://github.com/h2oai/h2ogpt/blob/main/docs/README_offline.md from https://github.com/h2oai/h2ogpt/pull/877
