### ISSUE TITLE
Unable to delete uploaded documents

### ISSUE THREAD

**Issue by nithyaagorur** [h2oai/h2ogpt#434]
I am unable to delete uploaded documents from the frontend H20GPT UI. Is it possible to do so? 
Also, when I delete documents backend, the documents get deleted, however, if I ask a question pertaining to the document deleted, the model is still able to answer (although there was no fine tuning involved).

**Comment by pseudotensor** [comment]
Delete document is a good feature to add and easy to do for chroma.  I already have way to refresh sources off disk, and that deletes before adding a changed file, so deleting is only simpler.

The underlying document is not required once ingestion is complete, because it's put into the database.

**Comment by pseudotensor** [comment]
Also delete upload files, history.json, dbs, etc.
