### ISSUE TITLE
Try to use GUI, but cann't connect to 0.0.0.0:7860

### ISSUE THREAD

**Issue by doin4** [h2oai/h2ogpt#438]
Trying to use GUI version of h2ogpt, but I can't open local URL 0.0.0.0:7860. I tried firefox and edge, neither can connect to the 0.0.0.0:7860.
I can use cli to have conversation, so the model seems fine.

**Comment by pseudotensor** [comment]
If you are using windows/mac, use 127.0.0.1 as in readme.

**Comment by doin4** [comment]
![图片](https://github.com/h2oai/h2ogpt/assets/72700948/03e304fc-000d-4d71-a6d7-b2c20297aebe)
The readme seems also use the 0.0.0.0:7860. or is there other readme that I should checkout?

**Comment by pseudotensor** [comment]
The main readme is right and mentions, but the windows one doesn't say anything except shows that output.  I'll fix the windows readme to mention things.  Thanks!

**Comment by doin4** [comment]
Thanks for your help, appreciated!

**Comment by pseudotensor** [comment]
7ab9134d7596e1bfce8cb4c9ee3b45e09b6d85e1
