### ISSUE TITLE
--load_8bit=True

### ISSUE THREAD

**Issue by temp288** [h2oai/h2ogpt#442]
Hello, I was wondering if it's possible to use 16bit, 32bit, etc. I have a single 3090ti

**Comment by pseudotensor** [comment]
Sure, you can use 16-bit for some models, but you don't want to use 32-bit, that would be abnormal and waste memory.

I use up to 7B locally on GPU with my 3090Ti.  But 13B models can be fit with 8-bit, and you should probably try AutoGPTQ (TheBloke GPTQ) models for best balance of performance and accuracy.

**Comment by temp288** [comment]
Awesome, thanks bro. I asked the model what token size we're using and it said 512 (on the 2048 7b model you are referring to). It said it can be changed from the config file to 2048. Same with enabling local filesystem access. Is there a config file for each model or one main config file I'm not locating?

**Comment by temp288** [comment]
Actually, I think I'm using a different 7b version. Can you tell me the exact name of the one you are referring to?

**Comment by pseudotensor** [comment]
```
h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
```

**Comment by temp288** [comment]
Cheers big ears
