### ISSUE TITLE
Generation are very slow on Nvidia GPU

### ISSUE THREAD

**Issue by Yusseiin** [h2oai/h2ogpt#443]
Hi all, i am trying to make the h2ogpt working on my windows 11 laptop.
I have an i7-11800H and an RTX A2000, i have setup everything for using the GPU
```
import torch
print(torch.cuda.is_available())
```
Return True so i think everything is good, i am using [Model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3] and the GPU is going under load when generating an answer.
![immagine](https://github.com/h2oai/h2ogpt/assets/103202144/57594255-527a-4048-89d1-761eb47236df)

But regardless all of this the answer is taking ages to getting written on the dashboard or on the cli.

Can someone help me?

**Comment by Yusseiin** [comment]
4bit, 8bit, no bit specified takes the same time.
It seems from `nvidia-smi`

![immagine](https://github.com/h2oai/h2ogpt/assets/103202144/313e52af-690a-4f50-90ee-2523d3eab35d)
That no process is taking GPU Memory, but in Task Manager memory it's full used and it change if i use 4bit/8bit.

For answering "Hi, who are you?" it is taking almost 3 minutes, around 20 sec per word

**Comment by Mathanraj-Sharma** [comment]
How many GPUs do you have on your laptop?

And what is the capacity of your nvidia-gpu?

From the nvidia-smi screenshot you shared, I guess its only 4096MiB.

**Comment by Yusseiin** [comment]
I have the Intel GPU ( the one from the CPU ) and the Nvidia ones.

it should be 4GB dedicated

**Comment by Mathanraj-Sharma** [comment]
If the cuda is configured properly it should show the right amount of GPU memory on the nvidia-smi. Please verify it. 

@pseudotensor WDYT?

**Comment by Yusseiin** [comment]
I will try to reinstall it and check

**Comment by Yusseiin** [comment]
> I will try to reinstall it and check. nvidia-smi is reporting cuda 12.2, i need to install 11.8?

I reinstalled everything following the guide under the docs.
`print(torch.cuda.is_available())` is giving `True`

nvidia-smi still reporting N/A
task manager still reporting 99% use and 3.8GB Dedicated GPU used.

Same speed as before.

**Comment by Mathanraj-Sharma** [comment]
@Yusseiin open your Nvidia control panel and make sure the prime profile is in performance mode (or your system is using Nvidia graphics card). 

I think nothing wrong with h2ogpt, you need to figure out how to configure Nvidia and cuda properly on your system

**Comment by pseudotensor** [comment]
Hi, please give the full line you run to start h2oGPT.

 I'm unsure how the RTX A2000 should perform relative to what I have which is RTX 3090Ti.  However, if the GPU usage is maxed out, then seems the GPU and h2oGPT are doing the best they can.  However, maybe something is still wrong.  For example, 4-bit, 8-bit or offloading to disk would cause problems.  So it might not GPU OOM, but still be slow.  4GB is too small for 16-bit for 7B, need at least 12GB even for 8-bit for 7B model.

**Comment by Yusseiin** [comment]
Checked Nvidia Control panel and set "Performance Mode", i am using 
`python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --score_model=None --load_8bit=True`
i will try with other config and check if i can reach something usable :) 
Thanks

**Comment by pseudotensor** [comment]
Try the CPU mode with 'llama' as in readme and see how that performs.  I'd hope a GPU would be faster, so a good check, since one can run the windows GPU llama cpp python to install cuda version to see how that works.  Might be better than falcon 7b on such a system.

Will close for now unless you find a specific problem with h2oGPT.  I have another issue to add a system support matrix to help beyond the current "supported" section in the readme.
