### ISSUE TITLE
Is it possible to upload a document to summarise it

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#448]
Hi,
I'm trying to upload a document to summarise on it, but I don't see any option.
Do I need to generate a DB on that document and this is the only option ? 

Thanks

**Comment by pseudotensor** [comment]
Are you using UI or CLI?  In UI you just choose upload, then in database choose summarize, then hit submit.

**Comment by slavag** [comment]
Thanks, I'm using UI, uploaded PDF and summarize is chosen, getting next error :
<img width="2053" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/6a62c250-2fc0-43d3-b81f-86dfebfb60b8">

**Comment by pseudotensor** [comment]
Thanks.  Can you share full stacktrace from command line?  Looks like a missing entry in metadata.

**Comment by slavag** [comment]
Sure, sorry I didn't attached it with the screenshot :) 
```
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.72it/s]
0it [00:00, ?it/s]
Found 65 new sources (0 have no hash in original source, so have to reprocess for migration to sources with hash)
Removing 0 duplicate files from db because ingesting those as new documents
Traceback (most recent call last):
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/utils.py", line 341, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gradio_runner.py", line 1428, in bot
    for res in get_response(fun1, history):
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gradio_runner.py", line 1385, in get_response
    for output_fun in fun1():
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gen.py", line 1497, in evaluate
    for r in run_qa_db(query=instruction,
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 1851, in _run_qa_db
    docs, chain, scores, use_context, have_any_docs = get_chain(**sim_kwargs)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 2093, in get_chain
    doc_hashes = [x['doc_hash'] for x in db_metadatas]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 2093, in <listcomp>
    doc_hashes = [x['doc_hash'] for x in db_metadatas]
                  ~^^^^^^^^^^^^
KeyError: 'doc_hash'
/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py:293: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn(
```

**Comment by pseudotensor** [comment]
I suppose it may occur when you have old db and no hashes yet since those were added maybe month ago.

**Comment by slavag** [comment]
@pseudotensor this is command that I run :
python generate.py --base_model=llama --score_model=None --langchain_mode='UserData' --chunk_size=256 --top_k_docs=3
And yes, I did :
1. Upload PDF
2. Choose Action "Summarize"
3. Click submit.

**Comment by pseudotensor** [comment]
Can you try again after I made the changes in above commit?

**Comment by slavag** [comment]
@pseudotensor Working now, but strange, while in the first attempt I uploaded A.pdf and got the error I sent at the begging , I uploaded then B.pdf (was thinking, maybe A.pdf is corrupted)  , so now with the latest code it does summarization , but alway on A.pdf, and doesn't mater what PDFs I uploaded after. It's summarize only A.pdf.

**Comment by pseudotensor** [comment]
To choose which document to summarize, need to go to "Document Selection" tab and pick it.  Otherwise, by default, it'll just put in top_k_docs chunks of documents, so will effectively only summarize first document.

**Comment by slavag** [comment]
@pseudotensor Thanks.
Don't see option to pick the required document. Clicking on it just downloads the pdf. 
<img width="1364" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/b119d239-7e17-417c-9d36-55e17fa223e7">

Also, maybe it's will be good to be able to remove document.

**Comment by pseudotensor** [comment]
Agree about remove document, someone (maybe you?) made an issue.

"Select subset" means select docs.  First click "Update UI with.." button and then select the dropdown for "Select subset" and select your document.  Then all queries and summarizations will only use that.

**Comment by slavag** [comment]
@pseudotensor Thanks, will open an issue for remove document.

**Comment by slavag** [comment]
@pseudotensor Btw, showing documents with check box, instead of selecting subset and then buttons for "Remove" or "Use", I think can be more intuitive UX. IMHO.

**Comment by pseudotensor** [comment]
Good idea.  I've weary of case when there are thousands of documents, since I've tested scenarios like that.  So I'm a bit biased on handling those cases.  That's also why there is an "Update UI" at all.  I could do it automatically, but nominally it's too expensive if one has all of wikipedia with 20M articles.

However, I have thought to change behavior at some threshold, so if user has only (say) < 20 docs then can do things more automatically and do the checkbox list you mentioned, else go to the drop-down manual-update mode.

I'll file issue to remind myself, thanks!
