### ISSUE TITLE
llama not using GPUs for M1/MPS

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#449]
https://github.com/h2oai/h2ogpt/issues/304#issuecomment-1636190901

**Comment by pseudotensor** [comment]
@slavag FYI I think @Mathanraj-Sharma tested non-llama models like h2ogpt models.

However, to get GPU support for llama, one needs to specifically decide that and compile llama cpp python properly, like mentioned here:

https://github.com/h2oai/h2ogpt/blob/main/docs/README_GPU.md#gpu-with-llama

@Mathanraj-Sharma Please check if this works for MAC M1 and add/copy that to the MAC readme.

**Comment by slavag** [comment]
@pseudotensor Thanks, llama cpp python was complied using :
CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1 pip install llama-cpp-python

**Comment by pseudotensor** [comment]
@slavag You mean you compiled it for metal and it still doesn't use GPU?

**Comment by slavag** [comment]
@pseudotensor Correct.

**Comment by Mathanraj-Sharma** [comment]
@pseudotensor I tried `h2oai/h2ogpt-gm-oasst1-en-2048-open-llama-7b` and it is working with MPS. 

But when I try `WizardLM-7B-uncensored.ggmlv3` I couldn't see any GPU (MPS) activity. 

Could you please tell me what is the difference between both, isn't `h2ogpt-gm-oasst1-en-2048-open-llama-7b` a llama model?

**Comment by Mathanraj-Sharma** [comment]
Found the missing piece will update the readme in a PR

**Comment by pseudotensor** [comment]
Hi @Mathanraj-Sharma , when I mention "llama" i mean the ones from readme.md

``bash
wget https://huggingface.co/TheBloke/WizardLM-7B-uncensored-GGML/resolve/main/WizardLM-7B-uncensored.ggmlv3.q8_0.bin
python generate.py --base_model='llama' --prompt_type=wizard2 --score_model=None --langchain_mode='UserData' --user_path=user_path
```

This uses llama cpp python package, which needs to be compiled against metal.
