### ISSUE TITLE
Need an ability to remove uploaded document(s)

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#451]
Hi,

Once documents uploaded (like in the attached screenshot) , need to be able to remove the document(s).

![image](https://github.com/h2oai/h2ogpt/assets/511540/a45b9cfb-f74e-4db6-a431-5e46752ab2aa)

Thanks

**Comment by raymondtri** [comment]
It would also be phenomenal if there was a gradio api endpoint for this as well

**Comment by pseudotensor** [comment]
@slavag @raymondtri done.
