### ISSUE TITLE
Can H2ogpt be used to conduct RLHF?

### ISSUE THREAD

**Issue by zyzisastudyreallyhardguy** [h2oai/h2ogpt#455]
Is there any way that can use H2ogpt to easily conduct RLHF for a LLM?

Also, does H2ogpt support multi-gpu inference when the model is too larger?

For example, when using Falcon40b, it seems even an 80G GPU will encounter an out-of-memory issue. Instead of using quantization, is it possible to spread the memory burden on multiple GPU?

**Comment by pseudotensor** [comment]
RLHF is supported in LLM Studio by H2O.ai but not in h2oGPT.  HF implemented versions of RLHF and could be added to h2oGPT if someone desired it.

Yes, just pass `--use_gpu_id=False` and we'll spread model over GPUs for inference if the model supports it.

**Comment by zyzisastudyreallyhardguy** [comment]
Is there any guideline or instruction about how to use LLM studio to conduct RLHF?

**Comment by pseudotensor** [comment]
See https://github.com/h2oai/h2o-llmstudio and ask the primary authors @psinger  and @pascal-pfeiffer .

Also check out our discord where LLM studio is discussed: https://discord.com/channels/1097462770674438174/1100718594809147402

**Comment by zyzisastudyreallyhardguy** [comment]
Thank you very much!
