### ISSUE TITLE
AUTOGPTQ Error

### ISSUE THREAD

**Issue by a3nima** [h2oai/h2ogpt#460]
> ERROR: Invalid requirement: 'PK\x03\x04\x14\x00\x00\x00\x08\x00�.�V���/��\t\x00\x00`(\x00!\x00\x00\x00autogptq_cuda.cp310-win_amd64.pydĽ\t|TE\x120�f&\x03�\x11ޠ' (from line 1 of https://github.com/PanQiWei/AutoGPTQ/releases/download/v0.2.2/auto_gptq-0.2.2+cu118-cp310-cp310-win_amd64.whl)

when trying to run `pip install -r https://github.com/PanQiWei/AutoGPTQ/releases/download/v0.2.2/auto_gptq-0.2.2+cu118-cp310-cp310-win_amd64.whl` from the windows documentation

**Comment by a3nima** [comment]
"pip install" without "-r" works

**Comment by pseudotensor** [comment]
Oops thanks!
