### ISSUE TITLE
Error when run simple generate command?

### ISSUE THREAD

**Issue by luvwinnie** [h2oai/h2ogpt#461]
Error when ran with the following command. Does anyone know what is the cause?

python generate.py --load_8bit True --base_model 'h2oai/h2ogpt-oasst1-512-20b'
Auto set langchain_mode=ChatLLM.  Could use MyData instead.  To allow UserData to pull files from disk, set user_path and ensure allow_upload_to_user_data=True
Using Model h2oai/h2ogpt-oasst1-512-20b
Prep: persist_directory=db_dir_UserData does not exist, regenerating
Chose UserData but user_path is empty/None
Starting get_model: h2oai/h2ogpt-oasst1-512-20b
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/llm/h2ogpt/generate.py:16 in <module>                                │
│                                                                                                  │
│   13                                                                                             │
│   14                                                                                             │
│   15 if __name__ == "__main__":                                                                  │
│ ❱ 16 │   entrypoint_main()                                                                       │
│   17                                                                                             │
│                                                                                                  │
│ /home/llm/h2ogpt/generate.py:12 in entrypoint_main                         │
│                                                                                                  │
│    9                                                                                             │
│   10                                                                                             │
│   11 def entrypoint_main():                                                                      │
│ ❱ 12 │   fire.Fire(main)                                                                         │
│   13                                                                                             │
│   14                                                                                             │
│   15 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /home/usr16/cheesiang_leow/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py:141  │
│ in Fire                                                                                          │
│                                                                                                  │
│   138 │   context.update(caller_globals)                                                         │
│   139 │   context.update(caller_locals)                                                          │
│   140                                                                                            │
│ ❱ 141   component_trace = _Fire(component, args, parsed_flag_args, context, name)                │
│   142                                                                                            │
│   143   if component_trace.HasError():                                                           │
│   144 │   _DisplayError(component_trace)                                                         │
│                                                                                                  │
│ /home/usr16/cheesiang_leow/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py:475  │
│ in _Fire                                                                                         │
│                                                                                                  │
│   472 │     is_class = inspect.isclass(component)                                                │
│   473 │                                                                                          │
│   474 │     try:                                                                                 │
│ ❱ 475 │   │   component, remaining_args = _CallAndUpdateTrace(                                   │
│   476 │   │   │   component,                                                                     │
│   477 │   │   │   remaining_args,                                                                │
│   478 │   │   │   component_trace,                                                               │
│                                                                                                  │
│ /home/usr16/cheesiang_leow/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py:691  │
│ in _CallAndUpdateTrace                                                                           │
│                                                                                                  │
│   688 │   loop = asyncio.get_event_loop()                                                        │
│   689 │   component = loop.run_until_complete(fn(*varargs, **kwargs))                            │
│   690   else:                                                                                    │
│ ❱ 691 │   component = fn(*varargs, **kwargs)                                                     │
│   692                                                                                            │
│   693   if treatment == 'class':                                                                 │
│   694 │   action = trace.INSTANTIATED_CLASS                                                      │
│                                                                                                  │
│ /home/llm/h2ogpt/src/gen.py:671 in main                                    │
│                                                                                                  │
│    668 │   │   │   all_kwargs.update(dict(base_model=base_model1, tokenizer_base_model=tokenize  │
│    669 │   │   │   │   │   │   │   │      lora_weights=lora_weights1, inference_server=inferenc  │
│    670 │   │   │   if base_model1 and not login_mode_if_model0:                                  │
│ ❱  671 │   │   │   │   model0, tokenizer0, device = get_model(reward_type=False,                 │
│    672 │   │   │   │   │   │   │   │   │   │   │   │   │      **get_kwargs(get_model, exclude_n  │
│    673 │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   **all_kwargs))        │
│    674 │   │   │   else:                                                                         │
│                                                                                                  │
│ /home/llm/h2ogpt/src/gen.py:1008 in get_model                              │
│                                                                                                  │
│   1005 │   │   return model, tokenizer, device                                                   │
│   1006 │                                                                                         │
│   1007 │   # get local torch-HF model                                                            │
│ ❱ 1008 │   return get_hf_model(load_8bit=load_8bit,                                              │
│   1009 │   │   │   │   │   │   load_4bit=load_4bit,                                              │
│   1010 │   │   │   │   │   │   load_half=load_half,                                              │
│   1011 │   │   │   │   │   │   load_gptq=load_gptq,                                              │
│                                                                                                  │
│ /home/llm/h2ogpt/src/gen.py:1124 in get_hf_model                           │
│                                                                                                  │
│   1121 │   │   if not lora_weights:                                                              │
│   1122 │   │   │   # torch.device context uses twice memory for AutoGPTQ                         │
│   1123 │   │   │   context = NullContext if load_gptq else torch.device                          │
│ ❱ 1124 │   │   │   with context(device):                                                         │
│   1125 │   │   │   │                                                                             │
│   1126 │   │   │   │   if use_gpu_id:                                                            │
│   1127 │   │   │   │   │   config, model = get_config(base_model, return_model=True, raise_exce  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: __enter__

**Comment by pseudotensor** [comment]
Can you give more details about your system, OS, etc.?  One other person hit this too for windows running linux or something like that.

```
with torch.device AttributeError: __enter__
```

Can you replace `with context(device):` with `with NullContext()` and see if that works?

**Comment by luvwinnie** [comment]
@pseudotensor Yes it works with with NullContext()!

My system is with command lsb_release -a that have two RTX A6000 and using miniconda.
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

**Comment by pseudotensor** [comment]
@luvwinnie How did you choose torch v1 instead of v2?  The pip install process in instructions should install v2.

**Comment by luvwinnie** [comment]
@pseudotensor I installed pytorch on previously created environment, so is that means it must use torch v2 instead of v1?

**Comment by pseudotensor** [comment]
Yes, AFAIK need torch v2.  I've never tested v1.  And a clean env is in general required to avoid issues since many of these packages vary alot, like langchain.
