### ISSUE TITLE
PDF Upload/URL error

### ISSUE THREAD

**Issue by a3nima** [h2oai/h2ogpt#469]
On Windows 10, with 3090, Document Mode, trying to import this pdf: 

https://cdn.openart.ai/assets/Stable%20Diffusion%20Prompt%20Book%20From%20OpenArt%2011-13.pdf

I get the following error:

100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.99s/it]
0it [00:00, ?it/s]
load INSTRUCTOR_Transformer
max_seq_length  512
Traceback (most recent call last):
  File "E:\TEXT-AI\h2ogpt\src\gradio_runner.py", line 2358, in update_user_db
    return _update_user_db(file, db1=db1, chunk=chunk, chunk_size=chunk_size,
  File "E:\TEXT-AI\h2ogpt\src\gradio_runner.py", line 2489, in _update_user_db
    db = get_db(sources, use_openai_embedding=use_openai_embedding,
  File "E:\TEXT-AI\h2ogpt\src\gpt_langchain.py", line 99, in get_db
    db = Chroma.from_documents(documents=sources,
  File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\langchain\vectorstores\chroma.py", line 446, in from_documents
    return cls.from_texts(
  File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\langchain\vectorstores\chroma.py", line 414, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\langchain\vectorstores\chroma.py", line 159, in add_texts
    embeddings = self._embedding_function.embed_documents(list(texts))
  File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\langchain\embeddings\huggingface.py", line 158, in embed_documents
    embeddings = self.client.encode(instruction_pairs, **self.encode_kwargs)
  File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\InstructorEmbedding\instructor.py", line 539, in encode
    out_features = self.forward(features)
  File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\InstructorEmbedding\instructor.py", line 278, in forward
    assert torch.sum(attention_mask[local_idx]).item() >= context_masks[local_idx].item(),\
RuntimeError: CUDA error: invalid program counter
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

/some small pdf files have worked, others even crush my system (reboot)...

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/issues/462

**Comment by a3nima** [comment]
> Already up to date.
> Using Model h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
> Prep: persist_directory=db_dir_UserData does not exist, regenerating
> Did not generate db since no sources
> Removing old MyData: /tmp\db_dir_MyData_c63867a2-0806-4685-b7c7-3ebbaaf2b31a
> Starting get_model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
> device_map: {'': 0}
> bin e:\TEXT-AI\envs\h2ogpt\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
> Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:08<00:00,  4.19s/it]
> Model {'base_model': 'h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3', 'tokenizer_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'prompt_answer', 'prompt_dict': {'promptA': '', 'promptB': '', 'PreInstruct': '<|prompt|>', 'PreInput': None, 'PreResponse': '<|answer|>', 'terminate_response': ['<|prompt|>', '<|answer|>', '<|endoftext|>'], 'chat_sep': '<|endoftext|>', 'chat_turn_sep': '<|endoftext|>', 'humanstr': '<|prompt|>', 'botstr': '<|answer|>', 'generates_leading_space': False}}
> Running on local URL:  http://0.0.0.0:7860
> 
> To create a public link, set `share=True` in `launch()`.
> 100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.58it/s]
> 0it [00:00, ?it/s]
> load INSTRUCTOR_Transformer
> max_seq_length  512
> Traceback (most recent call last):
>   File "E:\TEXT-AI\h2ogpt\src\gradio_runner.py", line 2592, in update_user_db
>     return _update_user_db(file, db1s=db1s, chunk=chunk, chunk_size=chunk_size,
>   File "E:\TEXT-AI\h2ogpt\src\gradio_runner.py", line 2740, in _update_user_db
>     db = get_db(sources, use_openai_embedding=use_openai_embedding,
>   File "E:\TEXT-AI\h2ogpt\src\gpt_langchain.py", line 103, in get_db
>     db = Chroma.from_documents(documents=sources,
>   File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\langchain\vectorstores\chroma.py", line 446, in from_documents
>     return cls.from_texts(
>   File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\langchain\vectorstores\chroma.py", line 414, in from_texts
>     chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
>   File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\langchain\vectorstores\chroma.py", line 159, in add_texts
>     embeddings = self._embedding_function.embed_documents(list(texts))
>   File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\langchain\embeddings\huggingface.py", line 158, in embed_documents
>     embeddings = self.client.encode(instruction_pairs, **self.encode_kwargs)
>   File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\InstructorEmbedding\instructor.py", line 539, in encode
>     out_features = self.forward(features)
>   File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
>     input = module(input)
>   File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\InstructorEmbedding\instructor.py", line 278, in forward
>     assert torch.sum(attention_mask[local_idx]).item() >= context_masks[local_idx].item(),\
> RuntimeError: CUDA error: unspecified launch failure
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by pseudotensor** [comment]
I'll need to check in windows.  I don't see the same problem in linux.

A work-around is to disable parallel ingest by passing to generate `--n_jobs=1`

**Comment by a3nima** [comment]
Hello thanks, but with --n_jobs=1 it seems to be the same result:

> To create a public link, set `share=True` in `launch()`.
> 100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.17it/s]
> 0it [00:00, ?it/s]
> load INSTRUCTOR_Transformer
> max_seq_length  512
> Run time of job "clear_torch_cache (trigger: interval[0:00:20], next run at: 2023-07-22 12:27:04 CEST)" was missed by 0:00:05.583524
> Traceback (most recent call last):
>   File "E:\TEXT-AI\h2ogpt\src\gradio_runner.py", line 2596, in update_user_db
>     return _update_user_db(file, db1s=db1s, chunk=chunk, chunk_size=chunk_size,
>   File "E:\TEXT-AI\h2ogpt\src\gradio_runner.py", line 2744, in _update_user_db
>     db = get_db(sources, use_openai_embedding=use_openai_embedding,
>   File "E:\TEXT-AI\h2ogpt\src\gpt_langchain.py", line 103, in get_db
>     db = Chroma.from_documents(documents=sources,
>   File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\langchain\vectorstores\chroma.py", line 446, in from_documents
>     return cls.from_texts(
>   File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\langchain\vectorstores\chroma.py", line 414, in from_texts
>     chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
>   File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\langchain\vectorstores\chroma.py", line 159, in add_texts
>     embeddings = self._embedding_function.embed_documents(list(texts))
>   File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\langchain\embeddings\huggingface.py", line 158, in embed_documents
>     embeddings = self.client.encode(instruction_pairs, **self.encode_kwargs)
>   File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\InstructorEmbedding\instructor.py", line 539, in encode
>     out_features = self.forward(features)
>   File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
>     input = module(input)
>   File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "e:\TEXT-AI\envs\h2ogpt\lib\site-packages\InstructorEmbedding\instructor.py", line 278, in forward
>     assert torch.sum(attention_mask[local_idx]).item() >= context_masks[local_idx].item(),\
> RuntimeError: CUDA error: unspecified launch failure
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by pseudotensor** [comment]
Can you check the basic torch works, e.g.
```python
import torch
print(torch.cuda.is_available())
```

and check:
```bash
nvidia-smi
```

The `RuntimeError: CUDA error: unspecified launch failure` usually means GPU OOM or some other error.

**Comment by a3nima** [comment]
> (h2ogpt) E:\TEXT-AI\h2ogpt>nvidia-smi
> Sun Jul 23 11:43:39 2023
> +---------------------------------------------------------------------------------------+
> | NVIDIA-SMI 531.79                 Driver Version: 531.79       CUDA Version: 12.1     |
> |-----------------------------------------+----------------------+---------------------
> (...)

> (h2ogpt) E:\TEXT-AI\h2ogpt> python --version
> Python 3.10.12

> (h2ogpt) E:\TEXT-AI\h2ogpt>python -c "import torch ; print(torch.cuda.is_available())"
> True

**Comment by pseudotensor** [comment]
@a3nima I'm unsure, but can you try latest where I reverted transformers back to older version?  I noticed some problems I thought were spurious but found bugs in transformers. Do:
```
pip install transformers==4.30.2
```

**Comment by a3nima** [comment]
> @a3nima I'm unsure, but can you try latest where I reverted transformers back to older version? I noticed some problems I thought were spurious but found bugs in transformers. Do:
> 
> ```
> pip install transformers==4.30.2
> ```

I'm already using this version.

**Comment by pseudotensor** [comment]
I went through entire windows documentation and updated it, and confirmed GPU working etc. Please try updated docs: https://github.com/h2oai/h2ogpt/blob/main/docs/README_WINDOWS.md
