### ISSUE TITLE
Can not add documents.

### ISSUE THREAD

**Issue by elaarabi** [h2oai/h2ogpt#471]
Hi everyone,

How can i add a document to the model ?
Why the option is not available in the UI ?
Here is the command i used to launch the model : 

python generate.py \
--share=False \
--gradio_offline_level=0 \
--base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 \
--score_model=None \
--load_4bit=True \
--prompt_type=human_bot

![image](https://github.com/h2oai/h2ogpt/assets/5952221/5a3bf431-af21-49f8-ae15-b40ef90c1af1)

**Comment by a3nima** [comment]
what's the output in your prompt window, when launching the UI? there could be a hint.

**Comment by elaarabi** [comment]
@a3nima here is my prompt window.
![image](https://github.com/h2oai/h2ogpt/assets/5952221/056fb646-3aed-4f7e-b7ca-1a118a7552ce)

**Comment by a3nima** [comment]
hi, sorry, I meant the command line- prompt window/shell window output.  but nevertheless, you need to have langchain in your start parameters. like this for use with gpu:
`python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-open-llama-7b --langchain_mode=MyData --score_model=None

`

**Comment by elaarabi** [comment]
Auto set langchain_mode=Disabled
Using Model h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
Starting get_model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 
device_map: {'': 0}
bin /home/arbi/.conda/envs/h2ogpt/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.09s/it]
Model {'base_model': 'h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3', 'tokenizer_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'prompt_answer', 'prompt_dict': {'promptA': '', 'promptB': '', 'PreInstruct': '<|prompt|>', 'PreInput': None, 'PreResponse': '<|answer|>', 'terminate_response': ['<|prompt|>', '<|answer|>', '<|endoftext|>'], 'chat_sep': '<|endoftext|>', 'chat_turn_sep': '<|endoftext|>', 'humanstr': '<|prompt|>', 'botstr': '<|answer|>', 'generates_leading_space': False}}
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.

**Comment by podybman** [comment]
I'm having the same issue, but I believe, on my case that this is because the installation of `langchain` failed.

Here is the end of the installation logs: 
```
      ld: library not found for -lSystem
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      error: command '/Library/Developer/CommandLineTools/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lxml
  Running setup.py clean for lxml
  Building wheel for pycocotools (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pycocotools (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.1-arm64-cpython-310
      creating build/lib.macosx-11.1-arm64-cpython-310/pycocotools
      copying pycocotools/coco.py -> build/lib.macosx-11.1-arm64-cpython-310/pycocotools
      copying pycocotools/mask.py -> build/lib.macosx-11.1-arm64-cpython-310/pycocotools
      copying pycocotools/__init__.py -> build/lib.macosx-11.1-arm64-cpython-310/pycocotools
      copying pycocotools/cocoeval.py -> build/lib.macosx-11.1-arm64-cpython-310/pycocotools
      running build_ext
      /private/var/folders/yd/bd853l6d38328nl8tkh2vqz5sndn0m/T/pip-build-env-rmucd9b8/overlay/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /private/var/folders/yd/bd853l6d38328nl8tkh2vqz5sndn0m/T/pip-install-em02bt2h/pycocotools_7db0ffdf8eb24164b01edddd6441cd44/pycocotools/_mask.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      Compiling pycocotools/_mask.pyx because it changed.
      [1/1] Cythonizing pycocotools/_mask.pyx
      building 'pycocotools._mask' extension
      creating build/temp.macosx-11.1-arm64-cpython-310
      creating build/temp.macosx-11.1-arm64-cpython-310/common
      creating build/temp.macosx-11.1-arm64-cpython-310/pycocotools
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/pdybman/anaconda3/envs/h2ogpt/include -arch arm64 -fPIC -O2 -isystem /Users/pdybman/anaconda3/envs/h2ogpt/include -arch arm64 -I/private/var/folders/yd/bd853l6d38328nl8tkh2vqz5sndn0m/T/pip-build-env-rmucd9b8/overlay/lib/python3.10/site-packages/numpy/core/include -I./common -I/Users/pdybman/anaconda3/envs/h2ogpt/include/python3.10 -c ./common/maskApi.c -o build/temp.macosx-11.1-arm64-cpython-310/./common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
      ./common/maskApi.c:8:10: fatal error: 'math.h' file not found
      #include <math.h>
               ^~~~~~~~
      1 error generated.
      error: command '/Library/Developer/CommandLineTools/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
Failed to build hnswlib lxml pycocotools
ERROR: Could not build wheels for hnswlib, lxml, pycocotools, which is required to install pyproject.toml-based projects
```
This is on arm64 on MacOS. Unsure how to solve this for now

**Comment by podybman** [comment]
Confirmed, I was able to fix everything and properly install `langchain` and it solves the issue for me.

**Comment by elaarabi** [comment]
@podybman thank you for the reply, i don't believe it's the same problem, i did not have any errors regarding langchain.

**Comment by elaarabi** [comment]
@podybman i am having : Auto set langchain_mode=Disabled. How can i enable it ?

**Comment by a3nima** [comment]
> @podybman i am having : Auto set langchain_mode=Disabled. How can i enable it ?

just to be sure, you have set a langchain mode in the start parameters? --langchain_mode=MyData  for example ?

**Comment by elaarabi** [comment]
@a3nima yes, but unfortunately i can't make it right ! i tried installing the package and dependencies. But even with the package installed i can't make it work.

Traceback (most recent call last):
...
    raise RuntimeError("Asked for LangChain mode but langchain python package cannot be found.")
RuntimeError: Asked for LangChain mode but langchain python package cannot be found.

**Comment by elaarabi** [comment]
I solved the error by installing reqs_optional/requirements_optional_langchain.txt.
It seems working now. Thank you every one.

**Comment by pseudotensor** [comment]
@elaarabi Hi, yes all those other "optional" packages are required for various features as explained in readme.

Please let me know what was bad about docs that this was missed. Thanks!

**Comment by pseudotensor** [comment]
> Confirmed, I was able to fix everything and properly install `langchain` and it solves the issue for me.

@podybman , Hi, can you say how you solved your installation issue?  i.e. the `ld: library not found for -lSystem` etc.?  So I can add to readme for mac.

@Mathanraj-Sharma  is it clear to you?

**Comment by podybman** [comment]
@pseudotensor 
```export LDFLAGS=-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib``` 
Essentially, it seems like on Mac, LD just isn't where it's supposed to be on a Unix system.

**Comment by pseudotensor** [comment]
Thanks!

**Comment by Mathanraj-Sharma** [comment]
@pseudotensor I haven't faced any issues regarding langchain so far, but I will try a fresh environment and let you know if I come up with anything
