### ISSUE TITLE
minor: strange ui layout :)

### ISSUE THREAD

**Issue by wizzard0** [h2oai/h2ogpt#472]
See attached screenshot. I have a suspicion it should show up a bit differently))

browser: Chrome 114 on macOS Ventura

<img width="856" alt="image" src="https://github.com/h2oai/h2ogpt/assets/424619/9837598b-7fe9-4017-8dbc-be9e0a4f3db8">

**Comment by pseudotensor** [comment]
You  must be running in --verbose=True mode.  We don't often maintain that.

**Comment by pseudotensor** [comment]
3801bc1545ada42455373c851484307c0e0cdace

**Comment by wizzard0** [comment]
Ah i see. FYI the system info button on System tab doesnt work)

<img width="429" alt="image" src="https://github.com/h2oai/h2ogpt/assets/424619/2bba9399-4b38-4bd8-a11f-a6c96a367095">

**Comment by pseudotensor** [comment]
Your system doesn’t support some information
