### ISSUE TITLE
8bit memory fix

### ISSUE THREAD

**Issue by Frub3L** [h2oai/h2ogpt#474]
### I noticed that my 8bit model slows down really quick, I also get some messages in the terminal about memory and other things, is there a fix for these yet?:
python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --langchain_mode=MyData --score_model=None --share=False --prompt_type=human_bot --gradio_offline_level=1 --load_8bit=True
Using Model h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
fatal: detected dubious ownership in repository at 'C:/H2OGPT/h2ogpt'
'C:/H2OGPT/h2ogpt' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-1056238872-1434061026-3064136600-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory C:/H2OGPT/h2ogpt
Prep: persist_directory=db_dir_UserData does not exist, regenerating
Chose UserData but user_path is empty/None
Starting get_model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
device_map: {'': 0}
bin C:\Users\frube\miniconda3\envs\h2ogpt\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:29<00:00, 14.96s/it]
Model {'base_model': 'h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3', 'tokenizer_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'prompt_answer', 'prompt_dict': {'promptA': '', 'promptB': '', 'PreInstruct': '<|prompt|>', 'PreInput': None, 'PreResponse': '<|answer|>', 'terminate_response': ['<|prompt|>', '<|answer|>', '<|endoftext|>'], 'chat_sep': '<|endoftext|>', 'chat_turn_sep': '<|endoftext|>', 'humanstr': '<|prompt|>', 'botstr': '<|answer|>', 'generates_leading_space': False}}
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
C:\Users\frube\miniconda3\envs\h2ogpt\lib\site-packages\torch\distributed\distributed_c10d.py:293: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn(
GPU Memory Track | 17-Jul-23-01:59:51 | Total Tensor Used Memory:13310.8Mb Total Allocated Memory:7012.3 Mb

[W ..\torch\csrc\PyInterpreter.cpp:223] Warning: Deallocating Tensor that still has live PyObject references.  This probably happened because you took out a weak reference to Tensor and didn't call _fix_weakref() after dereferencing it.  Subsequent accesses to this tensor via the PyObject will now fail. (function decref)
[W ..\torch\csrc\PyInterpreter.cpp:223] Warning: Deallocating Tensor that still has live PyObject references.  This probably happened because you took out a weak reference to Tensor and didn't call _fix_weakref() after dereferencing it.  Subsequent accesses to this tensor via the PyObject will now fail. (function decref)
+ | 2 * Size:(9, 4544)            | Memory: 0.1560 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(14,)                | Memory: 5.3405 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(3, 4544)            | Memory: 0.0260 M | <class 'torch.Tensor'> | torch.float16
+ | 3 * Size:(1,)                 | Memory: 2.2888 M | <class 'torch.Tensor'> | torch.int64
+ | 32 * Size:(18176,)             | Memory: 2.2187 M | <class 'torch.Tensor'> | torch.float32
+ | 1 * Size:(17,)                | Memory: 6.4849 M | <class 'torch.Tensor'> | torch.int32
+ | 2 * Size:(9,)                 | Memory: 6.8664 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(19,)                | Memory: 7.2479 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(1, 464, 65024)      | Memory: 57.546 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(129, 4544)          | Memory: 1.1180 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(27,)                | Memory: 0.0001 M | <class 'torch.Tensor'> | torch.int32
+ | 64 * Size:(18176, 4544)        | Memory: 5041.0 M | <class 'bitsandbytes.nn.modules.Int8Params'> | torch.int8
+ | 7 * Size:(4, 4672)            | Memory: 0.2495 M | <class 'torch.Tensor'> | torch.float16
+ | 2 * Size:(6, 4544)            | Memory: 0.1040 M | <class 'torch.Tensor'> | torch.float16
+ | 8 * Size:(6, 18176)           | Memory: 1.6640 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(1, 1, 465, 465)     | Memory: 0.2062 M | <class 'torch.Tensor'> | torch.bool
+ | 1 * Size:(110, 4544)          | Memory: 0.9533 M | <class 'torch.Tensor'> | torch.float16
+ | 64 * Size:(4672, 4544)         | Memory: 1295.7 M | <class 'bitsandbytes.nn.modules.Int8Params'> | torch.int8
+ | 81 * Size:(1, 65024)           | Memory: 10.045 M | <class 'torch.Tensor'> | torch.float16
+ | 3 * Size:(5, 18176)           | Memory: 0.5200 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(17, 4544)           | Memory: 0.1473 M | <class 'torch.Tensor'> | torch.float16
+ | 2 * Size:(8, 18176)           | Memory: 0.5546 M | <class 'torch.Tensor'> | torch.float16
+ | 7 * Size:(1, 4544)            | Memory: 0.0606 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(7, 4544)            | Memory: 0.0606 M | <class 'torch.Tensor'> | torch.float16
+ | 5 * Size:(7,)                 | Memory: 0.0001 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(110,)               | Memory: 0.0004 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(129,)               | Memory: 0.0004 M | <class 'torch.Tensor'> | torch.int32
+ | 7 * Size:(1,)                 | Memory: 2.6702 M | <class 'torch.Tensor'> | torch.int32
+ | 0 * Size:(465,)               | Memory: 0.0 M | <class 'torch.Tensor'> | torch.float32
+ | 64 * Size:(18176, 4544)        | Memory: 5041.0 M | <class 'torch.Tensor'> | torch.int8
+ | 3 * Size:(5, 4672)            | Memory: 0.1336 M | <class 'torch.Tensor'> | torch.float16
+ | 0 * Size:(18176, 3)           | Memory: 0.0 M | <class 'torch.Tensor'> | torch.float32
+ | 2 * Size:(7, 18176)           | Memory: 0.4853 M | <class 'torch.Tensor'> | torch.float16
+ | 0 * Size:(45,)                | Memory: 0.0 M | <class 'torch.Tensor'> | torch.float16
+ | 2 * Size:(1, 465)             | Memory: 0.0070 M | <class 'torch.Tensor'> | torch.int64
+ | 64 * Size:(4544,)              | Memory: 1.1093 M | <class 'torch.Tensor'> | torch.float32
+ | 22 * Size:(1, 465, 64)         | Memory: 1.2487 M | <class 'torch.Tensor'> | torch.float16
+ | 3 * Size:(1, 385)             | Memory: 0.0088 M | <class 'torch.Tensor'> | torch.int64
+ | 0 * Size:(18176, 3)           | Memory: 0.0 M | <class 'torch.Tensor'> | torch.int8
+ | 32 * Size:(32,)                | Memory: 0.0039 M | <class 'torch.Tensor'> | torch.float32
+ | 64 * Size:(4544, 18176)        | Memory: 5041.0 M | <class 'bitsandbytes.nn.modules.Int8Params'> | torch.int8
+ | 2 * Size:(8, 4672)            | Memory: 0.1425 M | <class 'torch.Tensor'> | torch.float16
+ | 44 * Size:(1, 464, 64)         | Memory: 2.4921 M | <class 'torch.Tensor'> | torch.float16
+ | 18 * Size:(6,)                 | Memory: 0.0004 M | <class 'torch.Tensor'> | torch.int32
+ | 0 * Size:(45,)                | Memory: 0.0 M | <class 'torch.Tensor'> | torch.int32
+ | 2 * Size:(7, 4672)            | Memory: 0.1247 M | <class 'torch.Tensor'> | torch.float16
+ | 8 * Size:(5,)                 | Memory: 0.0001 M | <class 'torch.Tensor'> | torch.int32
+ | 66 * Size:(4544,)              | Memory: 0.5720 M | <class 'torch.nn.parameter.Parameter'> | torch.float16
+ | 3 * Size:(2, 4672)            | Memory: 0.0534 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(15,)                | Memory: 5.7220 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(27, 4544)           | Memory: 0.2340 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(65024, 4544)        | Memory: 563.56 M | <class 'torch.nn.parameter.Parameter'> | torch.float16
+ | 32 * Size:(4672,)              | Memory: 0.5703 M | <class 'torch.Tensor'> | torch.float32
+ | 1 * Size:(19, 4544)           | Memory: 0.1646 M | <class 'torch.Tensor'> | torch.float16
+ | 64 * Size:(4544, 4544)         | Memory: 1260.2 M | <class 'bitsandbytes.nn.modules.Int8Params'> | torch.int8
+ | 7 * Size:(2,)                 | Memory: 5.3405 M | <class 'torch.Tensor'> | torch.int32
+ | 64 * Size:(4544, 4544)         | Memory: 1260.2 M | <class 'torch.Tensor'> | torch.int8
+ | 15 * Size:(4,)                 | Memory: 0.0002 M | <class 'torch.Tensor'> | torch.int32
+ | 7 * Size:(3, 18176)           | Memory: 0.7280 M | <class 'torch.Tensor'> | torch.float16
+ | 7 * Size:(3, 4672)            | Memory: 0.1871 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(465, 4544)          | Memory: 4.0301 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(4, 4544)            | Memory: 0.0346 M | <class 'torch.Tensor'> | torch.float16
+ | 64 * Size:(4544, 18176)        | Memory: 5041.0 M | <class 'torch.Tensor'> | torch.int8
+ | 15 * Size:(3,)                 | Memory: 0.0001 M | <class 'torch.Tensor'> | torch.int32
+ | 4 * Size:(1, 465, 4544)       | Memory: 16.120 M | <class 'torch.Tensor'> | torch.float16
+ | 64 * Size:(4672, 4544)         | Memory: 1295.7 M | <class 'torch.Tensor'> | torch.int8
+ | 1 * Size:(14, 4544)           | Memory: 0.1213 M | <class 'torch.Tensor'> | torch.float16
+ | 7 * Size:(4, 18176)           | Memory: 0.9707 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(2, 4544)            | Memory: 0.0173 M | <class 'torch.Tensor'> | torch.float16
+ | 0 * Size:(465, 4544)          | Memory: 0.0 M | <class 'torch.Tensor'> | torch.int8
+ | 4 * Size:(8,)                 | Memory: 0.0001 M | <class 'torch.Tensor'> | torch.int32
+ | 3 * Size:(2, 18176)           | Memory: 0.2080 M | <class 'torch.Tensor'> | torch.float16
+ | 2 * Size:(5, 4544)            | Memory: 0.0866 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(15, 4544)           | Memory: 0.1300 M | <class 'torch.Tensor'> | torch.float16
+ | 8 * Size:(6, 4672)            | Memory: 0.4277 M | <class 'torch.Tensor'> | torch.float16

At C:\H2OGPT\h2ogpt\src\utils.py line 88: ping_gpu_memory Total Tensor Used Memory:13311.6Mb Total Allocated Memory:7014.6 Mb

GPU Memory Track | 17-Jul-23-02:09:40 | Total Tensor Used Memory:13434.1Mb Total Allocated Memory:7068.8 Mb

[W ..\torch\csrc\PyInterpreter.cpp:223] Warning: Deallocating Tensor that still has live PyObject references.  This probably happened because you took out a weak reference to Tensor and didn't call _fix_weakref() after dereferencing it.  Subsequent accesses to this tensor via the PyObject will now fail. (function decref)
[W ..\torch\csrc\PyInterpreter.cpp:223] Warning: Deallocating Tensor that still has live PyObject references.  This probably happened because you took out a weak reference to Tensor and didn't call _fix_weakref() after dereferencing it.  Subsequent accesses to this tensor via the PyObject will now fail. (function decref)
+ | 10 * Size:(4,)                 | Memory: 0.0001 M | <class 'torch.Tensor'> | torch.int32
+ | 4 * Size:(4, 18176)           | Memory: 0.5546 M | <class 'torch.Tensor'> | torch.float16
+ | 3 * Size:(1,)                 | Memory: 2.2888 M | <class 'torch.Tensor'> | torch.int64
+ | 32 * Size:(18176,)             | Memory: 2.2187 M | <class 'torch.Tensor'> | torch.float32
+ | 1 * Size:(34,)                | Memory: 0.0001 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(17,)                | Memory: 6.4849 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(129, 4544)          | Memory: 1.1180 M | <class 'torch.Tensor'> | torch.float16
+ | 64 * Size:(18176, 4544)        | Memory: 5041.0 M | <class 'bitsandbytes.nn.modules.Int8Params'> | torch.int8
+ | 2 * Size:(6, 4544)            | Memory: 0.1040 M | <class 'torch.Tensor'> | torch.float16
+ | 8 * Size:(6, 18176)           | Memory: 1.6640 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(110, 4544)          | Memory: 0.9533 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(8, 18176)           | Memory: 0.2773 M | <class 'torch.Tensor'> | torch.float16
+ | 66 * Size:(1, 718, 64)         | Memory: 5.7846 M | <class 'torch.Tensor'> | torch.float16
+ | 9 * Size:(7,)                 | Memory: 0.0002 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(9, 4544)            | Memory: 0.0780 M | <class 'torch.Tensor'> | torch.float16
+ | 64 * Size:(4672, 4544)         | Memory: 1295.7 M | <class 'bitsandbytes.nn.modules.Int8Params'> | torch.int8
+ | 10 * Size:(1,)                 | Memory: 3.8146 M | <class 'torch.Tensor'> | torch.int32
+ | 3 * Size:(5, 18176)           | Memory: 0.5200 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(17, 4544)           | Memory: 0.1473 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(7, 4544)            | Memory: 0.0606 M | <class 'torch.Tensor'> | torch.float16
+ | 2 * Size:(11, 4544)           | Memory: 0.1906 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(110,)               | Memory: 0.0004 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(129,)               | Memory: 0.0004 M | <class 'torch.Tensor'> | torch.int32
+ | 4 * Size:(4, 4672)            | Memory: 0.1425 M | <class 'torch.Tensor'> | torch.float16
+ | 0 * Size:(1, 719, 73, 64)     | Memory: 0.0 M | <class 'torch.Tensor'> | torch.float16
+ | 64 * Size:(18176, 4544)        | Memory: 5041.0 M | <class 'torch.Tensor'> | torch.int8
+ | 10 * Size:(1, 4544)            | Memory: 0.0866 M | <class 'torch.Tensor'> | torch.float16
+ | 0 * Size:(1, 718, 65024)      | Memory: 0.0 M | <class 'torch.Tensor'> | torch.float16
+ | 3 * Size:(5, 4672)            | Memory: 0.1336 M | <class 'torch.Tensor'> | torch.float16
+ | 2 * Size:(25,)                | Memory: 0.0001 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(10, 4544)           | Memory: 0.0866 M | <class 'torch.Tensor'> | torch.float16
+ | 0 * Size:(1, 1, 719, 719)     | Memory: 0.0 M | <class 'torch.Tensor'> | torch.bool
+ | 14 * Size:(3,)                 | Memory: 0.0001 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(9, 4672)            | Memory: 0.0802 M | <class 'torch.Tensor'> | torch.float16
+ | 65 * Size:(4544,)              | Memory: 1.1267 M | <class 'torch.Tensor'> | torch.float32
+ | 3 * Size:(1, 663)             | Memory: 0.0151 M | <class 'torch.Tensor'> | torch.int64
+ | 1 * Size:(10, 18176)          | Memory: 0.3466 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(21, 4544)           | Memory: 0.1820 M | <class 'torch.Tensor'> | torch.float16
+ | 4 * Size:(7, 4672)            | Memory: 0.2495 M | <class 'torch.Tensor'> | torch.float16
+ | 4 * Size:(7, 18176)           | Memory: 0.9707 M | <class 'torch.Tensor'> | torch.float16
+ | 0 * Size:(1, 719, 4672)       | Memory: 0.0 M | <class 'torch.Tensor'> | torch.float16
+ | 32 * Size:(32,)                | Memory: 0.0039 M | <class 'torch.Tensor'> | torch.float32
+ | 64 * Size:(4544, 18176)        | Memory: 5041.0 M | <class 'bitsandbytes.nn.modules.Int8Params'> | torch.int8
+ | 18 * Size:(6,)                 | Memory: 0.0004 M | <class 'torch.Tensor'> | torch.int32
+ | 2 * Size:(8,)                 | Memory: 6.1035 M | <class 'torch.Tensor'> | torch.int32
+ | 2 * Size:(11,)                | Memory: 8.3923 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(21,)                | Memory: 8.0108 M | <class 'torch.Tensor'> | torch.int32
+ | 66 * Size:(4544,)              | Memory: 0.5720 M | <class 'torch.nn.parameter.Parameter'> | torch.float16
+ | 2 * Size:(4, 4544)            | Memory: 0.0693 M | <class 'torch.Tensor'> | torch.float16
+ | 3 * Size:(10,)                | Memory: 0.0001 M | <class 'torch.Tensor'> | torch.int32
+ | 3 * Size:(9,)                 | Memory: 0.0001 M | <class 'torch.Tensor'> | torch.int32
+ | 0 * Size:(1, 719, 4544)       | Memory: 0.0 M | <class 'torch.Tensor'> | torch.float16
+ | 3 * Size:(2, 4672)            | Memory: 0.0534 M | <class 'torch.Tensor'> | torch.float16
+ | 2 * Size:(25, 4544)           | Memory: 0.4333 M | <class 'torch.Tensor'> | torch.float16
+ | 0 * Size:(1, 719)             | Memory: 0.0 M | <class 'torch.Tensor'> | torch.int64
+ | 1 * Size:(65024, 4544)        | Memory: 563.56 M | <class 'torch.nn.parameter.Parameter'> | torch.float16
+ | 32 * Size:(4672,)              | Memory: 0.5703 M | <class 'torch.Tensor'> | torch.float32
+ | 1 * Size:(8, 4672)            | Memory: 0.0712 M | <class 'torch.Tensor'> | torch.float16
+ | 64 * Size:(4544, 4544)         | Memory: 1260.2 M | <class 'bitsandbytes.nn.modules.Int8Params'> | torch.int8
+ | 7 * Size:(2,)                 | Memory: 5.3405 M | <class 'torch.Tensor'> | torch.int32
+ | 64 * Size:(4544, 4544)         | Memory: 1260.2 M | <class 'torch.Tensor'> | torch.int8
+ | 7 * Size:(3, 18176)           | Memory: 0.7280 M | <class 'torch.Tensor'> | torch.float16
+ | 7 * Size:(3, 4672)            | Memory: 0.1871 M | <class 'torch.Tensor'> | torch.float16
+ | 56 * Size:(1, 65024)           | Memory: 6.9453 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(9, 18176)           | Memory: 0.3120 M | <class 'torch.Tensor'> | torch.float16
+ | 64 * Size:(4544, 18176)        | Memory: 5041.0 M | <class 'torch.Tensor'> | torch.int8
+ | 1 * Size:(34, 4544)           | Memory: 0.2946 M | <class 'torch.Tensor'> | torch.float16
+ | 64 * Size:(4672, 4544)         | Memory: 1295.7 M | <class 'torch.Tensor'> | torch.int8
+ | 1 * Size:(2, 4544)            | Memory: 0.0173 M | <class 'torch.Tensor'> | torch.float16
+ | 6 * Size:(5,)                 | Memory: 0.0001 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(10, 4672)           | Memory: 0.0891 M | <class 'torch.Tensor'> | torch.float16
+ | 3 * Size:(2, 18176)           | Memory: 0.2080 M | <class 'torch.Tensor'> | torch.float16
+ | 0 * Size:(1, 719, 71, 64)     | Memory: 0.0 M | <class 'torch.Tensor'> | torch.float16
+ | 8 * Size:(6, 4672)            | Memory: 0.4277 M | <class 'torch.Tensor'> | torch.float16

At C:\H2OGPT\h2ogpt\src\utils.py line 88: ping_gpu_memory Total Tensor Used Memory:13350.3Mb Total Allocated Memory:7041.1 Mb

GPU Memory Track | 17-Jul-23-02:19:40 | Total Tensor Used Memory:13222.6Mb Total Allocated Memory:6918.7 Mb

+ | 2 * Size:(9, 4544)            | Memory: 0.1560 M | <class 'torch.Tensor'> | torch.float16
+ | 12 * Size:(4,)                 | Memory: 0.0001 M | <class 'torch.Tensor'> | torch.int32
+ | 9 * Size:(6, 4672)            | Memory: 0.4812 M | <class 'torch.Tensor'> | torch.float16
+ | 32 * Size:(18176,)             | Memory: 2.2187 M | <class 'torch.Tensor'> | torch.float32
+ | 1 * Size:(34,)                | Memory: 0.0001 M | <class 'torch.Tensor'> | torch.int32
+ | 64 * Size:(1, 719, 64)         | Memory: 5.6171 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(19,)                | Memory: 7.2479 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(129, 4544)          | Memory: 1.1180 M | <class 'torch.Tensor'> | torch.float16
+ | 2 * Size:(10,)                | Memory: 7.6293 M | <class 'torch.Tensor'> | torch.int32
+ | 64 * Size:(18176, 4544)        | Memory: 5041.0 M | <class 'bitsandbytes.nn.modules.Int8Params'> | torch.int8
+ | 1 * Size:(110, 4544)          | Memory: 0.9533 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(8, 18176)           | Memory: 0.2773 M | <class 'torch.Tensor'> | torch.float16
+ | 64 * Size:(4672, 4544)         | Memory: 1295.7 M | <class 'bitsandbytes.nn.modules.Int8Params'> | torch.int8
+ | 10 * Size:(1,)                 | Memory: 3.8146 M | <class 'torch.Tensor'> | torch.int32
+ | 2 * Size:(7, 4544)            | Memory: 0.1213 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(26, 4544)           | Memory: 0.2253 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(6, 4544)            | Memory: 0.0520 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(110,)               | Memory: 0.0004 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(129,)               | Memory: 0.0004 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(11,)                | Memory: 4.1961 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(16,)                | Memory: 6.1035 M | <class 'torch.Tensor'> | torch.int32
+ | 64 * Size:(18176, 4544)        | Memory: 5041.0 M | <class 'torch.Tensor'> | torch.int8
+ | 10 * Size:(1, 4544)            | Memory: 0.0866 M | <class 'torch.Tensor'> | torch.float16
+ | 2 * Size:(5, 18176)           | Memory: 0.3466 M | <class 'torch.Tensor'> | torch.float16
+ | 5 * Size:(4, 18176)           | Memory: 0.6933 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(26,)                | Memory: 9.9182 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(12,)                | Memory: 4.5776 M | <class 'torch.Tensor'> | torch.int32
+ | 4 * Size:(5,)                 | Memory: 7.6293 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(9, 4672)            | Memory: 0.0802 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(10, 18176)          | Memory: 0.3466 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(24, 4544)           | Memory: 0.2080 M | <class 'torch.Tensor'> | torch.float16
+ | 4 * Size:(7, 4672)            | Memory: 0.2495 M | <class 'torch.Tensor'> | torch.float16
+ | 64 * Size:(4544,)              | Memory: 1.1093 M | <class 'torch.Tensor'> | torch.float32
+ | 4 * Size:(7, 18176)           | Memory: 0.9707 M | <class 'torch.Tensor'> | torch.float16
+ | 32 * Size:(32,)                | Memory: 0.0039 M | <class 'torch.Tensor'> | torch.float32
+ | 64 * Size:(4544, 18176)        | Memory: 5041.0 M | <class 'bitsandbytes.nn.modules.Int8Params'> | torch.int8
+ | 19 * Size:(6,)                 | Memory: 0.0004 M | <class 'torch.Tensor'> | torch.int32
+ | 2 * Size:(5, 4672)            | Memory: 0.0891 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(16, 4544)           | Memory: 0.1386 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(12, 4544)           | Memory: 0.1040 M | <class 'torch.Tensor'> | torch.float16
+ | 2 * Size:(8,)                 | Memory: 6.1035 M | <class 'torch.Tensor'> | torch.int32
+ | 66 * Size:(4544,)              | Memory: 0.5720 M | <class 'torch.nn.parameter.Parameter'> | torch.float16
+ | 2 * Size:(4, 4544)            | Memory: 0.0693 M | <class 'torch.Tensor'> | torch.float16
+ | 3 * Size:(2, 4672)            | Memory: 0.0534 M | <class 'torch.Tensor'> | torch.float16
+ | 9 * Size:(6, 18176)           | Memory: 1.8720 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(65024, 4544)        | Memory: 563.56 M | <class 'torch.nn.parameter.Parameter'> | torch.float16
+ | 1 * Size:(8, 4672)            | Memory: 0.0712 M | <class 'torch.Tensor'> | torch.float16
+ | 32 * Size:(4672,)              | Memory: 0.5703 M | <class 'torch.Tensor'> | torch.float32
+ | 1 * Size:(19, 4544)           | Memory: 0.1646 M | <class 'torch.Tensor'> | torch.float16
+ | 64 * Size:(4544, 4544)         | Memory: 1260.2 M | <class 'bitsandbytes.nn.modules.Int8Params'> | torch.int8
+ | 7 * Size:(2,)                 | Memory: 5.3405 M | <class 'torch.Tensor'> | torch.int32
+ | 64 * Size:(4544, 4544)         | Memory: 1260.2 M | <class 'torch.Tensor'> | torch.int8
+ | 5 * Size:(4, 4672)            | Memory: 0.1782 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(24,)                | Memory: 9.1552 M | <class 'torch.Tensor'> | torch.int32
+ | 12 * Size:(3,)                 | Memory: 0.0001 M | <class 'torch.Tensor'> | torch.int32
+ | 1 * Size:(9, 18176)           | Memory: 0.3120 M | <class 'torch.Tensor'> | torch.float16
+ | 64 * Size:(4544, 18176)        | Memory: 5041.0 M | <class 'torch.Tensor'> | torch.int8
+ | 6 * Size:(3, 18176)           | Memory: 0.6240 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(34, 4544)           | Memory: 0.2946 M | <class 'torch.Tensor'> | torch.float16
+ | 64 * Size:(4672, 4544)         | Memory: 1295.7 M | <class 'torch.Tensor'> | torch.int8
+ | 1 * Size:(11, 4544)           | Memory: 0.0953 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(2, 4544)            | Memory: 0.0173 M | <class 'torch.Tensor'> | torch.float16
+ | 6 * Size:(3, 4672)            | Memory: 0.1604 M | <class 'torch.Tensor'> | torch.float16
+ | 1 * Size:(10, 4672)           | Memory: 0.0891 M | <class 'torch.Tensor'> | torch.float16
+ | 3 * Size:(2, 18176)           | Memory: 0.2080 M | <class 'torch.Tensor'> | torch.float16
+ | 10 * Size:(7,)                 | Memory: 0.0002 M | <class 'torch.Tensor'> | torch.int32
+ | 4 * Size:(9,)                 | Memory: 0.0001 M | <class 'torch.Tensor'> | torch.int32

At C:\H2OGPT\h2ogpt\src\utils.py line 88: ping_gpu_memory Total Tensor Used Memory:13222.6Mb Total Allocated Memory:6918.7 Mb

**Comment by pseudotensor** [comment]
Yes, added "fixes" for the excessive messages.  As for slow-down 8-bit, unsure details.  Please open a new issue if you see and give details about your GPU, timing, etc.
