### ISSUE TITLE
Prompts dictionary

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#480]
Hi, sorry for the silly question, tried to find the answer but can't.
In the console , when chat is tarted I see that text :
```
'prompt_dict': {'promptA': 'Below is an instruction that describes a task. Write a response that appropriately completes the request.', 'promptB': 'Below is an instruction that describes a task. Write a response that appropriately completes the request.', 'PreInstruct': '\n### Instruction:\n', 'PreInput': None, 'PreResponse': '\n### Response:\n', 'terminate_response': ['\n### Response:\n'], 'chat_sep': '\n', 'chat_turn_sep': '\n', 'humanstr': '\n### Instruction:\n', 'botstr': '\n### Response:\n', 'generates_leading_space': False}}
```
What is that dictionary and what are those entries in it ?

Thanks

**Comment by pseudotensor** [comment]
This is the exact way the model is prompted, and it can be edited and changed for an arbitrary new model if we didn't include a "prompt_type" already for that given model.  It can be passed on CLI to generate or edited in the UI.

It's like in https://github.com/oobabooga/text-generation-webui when one can specify the prompt template.
