### ISSUE TITLE
Custom model location of git clone download

### ISSUE THREAD

**Issue by auwsom** [h2oai/h2ogpt#481]
Hello, loving h2oai.. is it possible to customize the model location? I dont have enough storage on my OS drive and have downloaded the 7B h2oai model using git clone. How can I use it? (I think I've done this with other transformer models before, but not with the h2oai layer of python wrapper.)

I have the LLaMa WizardLM model working by just symlinking the file to the current h2oai dir. I could symlink the 7B model directory to the ~/.cache/hugginface/hub dir, but they are all stored in blob form (this is another reason I want to use my own downloaded models.. so I can read the names of the files, and even the json file if I want. As well as restart the download directly). Thanks

**Comment by auwsom** [comment]
I think I remembered.. just start the automatic download by h2oai with generate.py ... and then go in to the huggingface/hub/models--<model> dir and then into ../snapshots/<long_number> and it has human named symlinks to the blob files. Now rm that dir (or rename it) and symlink the git cloned dir to that <long_number> dir (using full paths of course).. and it finds the model. :+1:

**Comment by a3nima** [comment]
i think h2o should make an option to specify the  model directory or have it at least be inside the h2ogpt directory that you git cloned.

but thanks for the idea. another way, I was beginning to look into is to set up huggingface somehow to use another directory.

**Comment by auwsom** [comment]
@a3nima agreed, that would be good..

I think i researched that for a while before giving up and just symlinking.. i think i have a GH issue on Hugginface repo for it..

**Comment by Mathanraj-Sharma** [comment]
@auwsom  @a3nima did you tried setting this, to change the default hugging face cache dir

`export TRANSFORMERS_CACHE=your/cache/dir`

**Comment by a3nima** [comment]
thanks @Mathanraj-Sharma , I might try it, as soon as h2ogpt works without crashing for me :) I already went to the process to have the python environment outside C, because of the other packages that would have been downloaded to my c:\ drive.

**Comment by pseudotensor** [comment]
Both GPT4All and transformers have their own options to control the cache location.  For `--base_model='llama'` one downloads those manually to wherever and then specifies that in the .env_gpt4all file.

**Comment by auwsom** [comment]
> @auwsom @a3nima did you tried setting this, to change the default hugging face cache dir
> 
> `export TRANSFORMERS_CACHE=your/cache/dir`

I didnt test that var but HF_HOME does work:
https://huggingface.co/docs/huggingface_hub/guides/manage-cache
"The <CACHE_DIR> is usually your user’s home directory. However, it is customizable with the cache_dir argument on all methods, or by specifying either HF_HOME or HUGGINGFACE_HUB_CACHE environment variable."

**Comment by a3nima** [comment]
I use this as starting .bat file and it works.. But more user friendly would be a single file that you can specify inside the program, where models are stored or loaded from. I would prefer this from the HF Cache method. Store them as regular files (.bin/.safetensor, .json etc)

```
@echo off

REM Change the working directory to the location of your Python script
cd /d "e:\TEXT-AI\h2ogpt"

REM update
git pull

REM Activate the conda environment
call conda activate e:\TEXT-AI\venv\h2ogpt

REM set huggingface cache dir
set TRANSFORMERS_CACHE=e:\TEXT-AI\HuggingFaceCache\


REM Start the Python program with the desired arguments
```

**Comment by pseudotensor** [comment]
@a3nima Probably easiest is the windows installers that I added a couple days ago.  But depends, windows installer good for single user experience, but multi-user is not perfect since not easy to  pass arguments to "generate.py".  But will fix that soon: https://github.com/h2oai/h2ogpt/issues/655

**Comment by a3nima** [comment]
> @a3nima Probably easiest is the windows installers that I added a couple days ago. But depends, windows installer good for single user experience, but multi-user is not perfect since not easy to pass arguments to "generate.py". But will fix that soon: #655

ok, can you tell me, if the windows installer is set up the way that only the h2ogpt folder is used for the necessary files or will packages and models be downloaded to cache folders and the alike (which have their default locations at c:\) ?

**Comment by pseudotensor** [comment]
For windows installer, you no loner need the git repo at all.

**Comment by a3nima** [comment]
an option to have the models inside the application folder (or at a specific folder) as well and not use huggingface cache would be nice, so you could share the models folder with other applications more easily. 

I will have to look if the HF cache folder can be set for the installer version like I did it with the git version.

**Comment by pseudotensor** [comment]
There are envs for transformers to control where models go, i.e. `TRANSFORMERS_CACHE`.

**Comment by a3nima** [comment]
Yeah I know my startup file was setting this, but if I dont use it and instead the preinstalled version's exe or what it uses, then I'm not sure, where to set it.

**Comment by auwsom** [comment]
> Yeah I know my startup file was setting this, but if I dont use it and instead the preinstalled version's exe or what it uses, then I'm not sure, where to set it.

On Linux, is just an environment variable. On Windows, and thing but there's a good utility for setting them called Environment Manager or something like that.
