### ISSUE TITLE
Could you please explain what is the difference between different prompt_type?

### ISSUE THREAD

**Issue by zyzisastudyreallyhardguy** [h2oai/h2ogpt#486]
Dear H2ogpt team,

I would like to know the difference between different prompt_type? For example, what happens when i set the prompt_type to 'human_bot', and what will happen if use other options?

Best

**Comment by pseudotensor** [comment]
See src/prompter.py.  Each LLM model has a required type of prompting.  If it's a new model we don't have listed in that file, then need to use prompt_dict or add a new prompt_type and its entry.  Also see: https://github.com/h2oai/h2ogpt/issues/480
