### ISSUE TITLE
Create a new Database

### ISSUE THREAD

**Issue by ba2710** [h2oai/h2ogpt#493]
Hello, and thank you for such an excellent program. I'm trying to create a new custom DB by adding new names to the generate.py switches, like so: 

`--visible_langchain_modes="['UserData', 'wiki', 'LegalClinic', 'GPT', 'MyData']"`

But aside from 'wiki' it doesn't seem to create any new collections in the sidebar. Can you please tell me how I can create or setup a new DB entry that appears in the sidebar? Thank you!

**Comment by slavag** [comment]
https://github.com/h2oai/h2ogpt/issues/277

**Comment by pseudotensor** [comment]
It's nearly done: https://github.com/h2oai/h2ogpt/pull/476

**Comment by ba2710** [comment]
Thank you so much! You're the best!
