### ISSUE TITLE
Not getting the complete output

### ISSUE THREAD

**Issue by pranavvr-lumiq** [h2oai/h2ogpt#497]
HI. I have used anaconda prompt to run a the falcon 7b model on my local machine. I get the prompt to enter instructions, but I do not get the full output.

For example:

Enter an instruction: what is a tiger
A tiger is a large, powerful cat that is(This is where the output cuts off)

I cannot for the life of me understand why this is happening. I have a GPU and Cuda all working.

**Comment by m45t3rc0d3r** [comment]
I have the same problem too. Could it be due to lack of system/GPU memory? even with 4 bit, it shows the same issue..

**Comment by pseudotensor** [comment]
Hi, can you tell me your system type and the full generate line you are using so I know what model etc.?

**Comment by pranavvr-lumiq** [comment]
> Hi, can you tell me your system type and the full generate line you are using so I know what model etc.?

Hi, thanks for agreeing to help. I am using a windows system with an nvidia 3070 gpu. My generate line is pasted below. Please let me know if you need anything else from me.

python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --score_model=None --prompt_type=human_bot --cli=True --load_4bit=True

**Comment by m45t3rc0d3r** [comment]
Windows 10 with nvidia GTX 1050 ti

python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --score_model=None --load_4bit=True

**Comment by pseudotensor** [comment]
I revamped and fully tested the docs for windows, please try again: https://github.com/h2oai/h2ogpt/blob/main/docs/README_WINDOWS.md
