### ISSUE TITLE
how do i limit ram usage

### ISSUE THREAD

**Issue by Toaster496** [h2oai/h2ogpt#498]
i remember that once apon a time you could limit ram usage (my computer is crashing 16gb windows 11 falcon 7b 8bit.)

what is the command thigi i need to do that
?

**Comment by pseudotensor** [comment]
With torch there is no way to limit memory usage, like in tensorflow, AFAIK.

7b 8bit should only require 13GB of GPU memory, and I've run 6_9 model on 16GB GPU.  Please share your generate command and I can try.

**Comment by Toaster496** [comment]
This is it ...
python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v2 --load_8bit=True

**Comment by Toaster496** [comment]
![image](https://github.com/h2oai/h2ogpt/assets/124654952/ddede10c-090a-4bc9-b3c7-d5d84a4a2317)

**Comment by pseudotensor** [comment]
Did you read the low memory mode FAQ?  We also reference it in the discussion in readme.md about supported systems and memory usage.

i.e. try disabling the score model and using leaner embedding:

```
python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v2 --load_8bit=True --score_model=None --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2
```

This only uses 8GB for me.

https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#low-memory-mode
