### ISSUE TITLE
Custom embeddings

### ISSUE THREAD

**Issue by DhavalWI** [h2oai/h2ogpt#499]
How do i load a custom embedding to process my data? The embeddings are from huggingface and another embedding model that i have is stored on my local system. Thanks!

**Comment by pseudotensor** [comment]
We only support one embedding at a time for each database.  So you could use src/make_db.py to make the db for different embeddings (`--hf_embedding_model` like gen.py, any HF model) for each source folders, and then at generate.py time you can specify those different collection names in `--langchain_modes` and `--visible_langchain_modes`.
