### ISSUE TITLE
working examples

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#5]
![image](https://user-images.githubusercontent.com/2249614/228338854-b474c170-53f2-4bfd-a865-dc06d691ee93.png)

**Comment by lelapin123** [comment]
This seems to be "H2O-LLM" not "H2O-GPT".
Is it not a mistake ?

**Comment by pseudotensor** [comment]
The original repo was named h2o-llm.  It's still an alias, you can try it: https://github.com/h2oai/h2o-llm

You are looking at the very early version of the UI.  It's come a long way since then.
