### ISSUE TITLE
Cannot import files from user_path

### ISSUE THREAD

**Issue by naumfujimori** [h2oai/h2ogpt#504]
Hi Guys,
 I cant (using docker/ docker-compose up --build)
 run generate.py --score_model=None --langchain_mode='UserData' --user_path=user_path
 when my user_path is populated
 but if the user_path is empty run without problem.
 Find bellow the Logs
 Is running on AWS g5.4xlarge with A10 Nvidia 24gb
 
 h2ogpt-h2o-llm-1  | Loaded 1 new files as sources to add to UserData
h2ogpt-h2o-llm-1  | Loaded 1 sources for potentially adding to UserData
h2ogpt-h2o-llm-1  | load INSTRUCTOR_Transformer
h2ogpt-h2o-llm-1  | ╭───────────────────── Traceback (most recent call last) ──────────────────────╮
h2ogpt-h2o-llm-1  | │ /workspace/generate.py:16 in <module>                                        │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │   13                                                                         │
h2ogpt-h2o-llm-1  | │   14                                                                         │
h2ogpt-h2o-llm-1  | │   15 if __name__ == "__main__":                                              │
h2ogpt-h2o-llm-1  | │ ❱ 16 │   entrypoint_main()                                                   │
h2ogpt-h2o-llm-1  | │   17                                                                         │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /workspace/generate.py:12 in entrypoint_main                                 │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │    9                                                                         │
h2ogpt-h2o-llm-1  | │   10                                                                         │
h2ogpt-h2o-llm-1  | │   11 def entrypoint_main():                                                  │
h2ogpt-h2o-llm-1  | │ ❱ 12 │   fire.Fire(main)                                                     │
h2ogpt-h2o-llm-1  | │   13                                                                         │
h2ogpt-h2o-llm-1  | │   14                                                                         │
h2ogpt-h2o-llm-1  | │   15 if __name__ == "__main__":                                              │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /usr/local/lib/python3.10/dist-packages/fire/core.py:141 in Fire             │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │   138 │   context.update(caller_globals)                                     │
h2ogpt-h2o-llm-1  | │   139 │   context.update(caller_locals)                                      │
h2ogpt-h2o-llm-1  | │   140                                                                        │
h2ogpt-h2o-llm-1  | │ ❱ 141   component_trace = _Fire(component, args, parsed_flag_args, context,  │
h2ogpt-h2o-llm-1  | │   142                                                                        │
h2ogpt-h2o-llm-1  | │   143   if component_trace.HasError():                                       │
h2ogpt-h2o-llm-1  | │   144 │   _DisplayError(component_trace)                                     │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /usr/local/lib/python3.10/dist-packages/fire/core.py:475 in _Fire            │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │   472 │     is_class = inspect.isclass(component)                            │
h2ogpt-h2o-llm-1  | │   473 │                                                                      │
h2ogpt-h2o-llm-1  | │   474 │     try:                                                             │
h2ogpt-h2o-llm-1  | │ ❱ 475 │   │   component, remaining_args = _CallAndUpdateTrace(               │
h2ogpt-h2o-llm-1  | │   476 │   │   │   component,                                                 │
h2ogpt-h2o-llm-1  | │   477 │   │   │   remaining_args,                                            │
h2ogpt-h2o-llm-1  | │   478 │   │   │   component_trace,                                           │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /usr/local/lib/python3.10/dist-packages/fire/core.py:691 in                  │
h2ogpt-h2o-llm-1  | │ _CallAndUpdateTrace                                                          │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │   688 │   loop = asyncio.get_event_loop()                                    │
h2ogpt-h2o-llm-1  | │   689 │   component = loop.run_until_complete(fn(*varargs, **kwargs))        │
h2ogpt-h2o-llm-1  | │   690   else:                                                                │
h2ogpt-h2o-llm-1  | │ ❱ 691 │   component = fn(*varargs, **kwargs)                                 │
h2ogpt-h2o-llm-1  | │   692                                                                        │
h2ogpt-h2o-llm-1  | │   693   if treatment == 'class':                                             │
h2ogpt-h2o-llm-1  | │   694 │   action = trace.INSTANTIATED_CLASS                                  │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /workspace/src/gen.py:641 in main                                            │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │    638 │   │   │   │   continue                                              │
h2ogpt-h2o-llm-1  | │    639 │   │   │   persist_directory1 = 'db_dir_%s' % langchain_mode1  # sin │
h2ogpt-h2o-llm-1  | │    640 │   │   │   try:                                                      │
h2ogpt-h2o-llm-1  | │ ❱  641 │   │   │   │   db = prep_langchain(persist_directory1,               │
h2ogpt-h2o-llm-1  | │    642 │   │   │   │   │   │   │   │   │   load_db_if_exists,                │
h2ogpt-h2o-llm-1  | │    643 │   │   │   │   │   │   │   │   │   db_type, use_openai_embedding,    │
h2ogpt-h2o-llm-1  | │    644 │   │   │   │   │   │   │   │   │   langchain_mode1, langchain_mode_p │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /workspace/src/gpt_langchain.py:1529 in prep_langchain                       │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │   1526 │   │                                                                 │
h2ogpt-h2o-llm-1  | │   1527 │   │   langchain_kwargs = kwargs_make_db.copy()                      │
h2ogpt-h2o-llm-1  | │   1528 │   │   langchain_kwargs.update(locals())                             │
h2ogpt-h2o-llm-1  | │ ❱ 1529 │   │   db, num_new_sources, new_sources_metadata = make_db(**langcha │
h2ogpt-h2o-llm-1  | │   1530 │                                                                     │
h2ogpt-h2o-llm-1  | │   1531 │   return db                                                         │
h2ogpt-h2o-llm-1  | │   1532                                                                       │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /workspace/src/gpt_langchain.py:1646 in make_db                              │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │   1643 │   assert not missing_kwargs, "Missing kwargs for make_db: %s" % mis │
h2ogpt-h2o-llm-1  | │   1644 │   # only keep actual used                                           │
h2ogpt-h2o-llm-1  | │   1645 │   langchain_kwargs = {k: v for k, v in langchain_kwargs.items() if  │
h2ogpt-h2o-llm-1  | │ ❱ 1646 │   return _make_db(**langchain_kwargs)                               │
h2ogpt-h2o-llm-1  | │   1647                                                                       │
h2ogpt-h2o-llm-1  | │   1648                                                                       │
h2ogpt-h2o-llm-1  | │   1649 def save_embed(db, use_openai_embedding, hf_embedding_model):         │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /workspace/src/gpt_langchain.py:1759 in _make_db                             │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │   1756 │   │   │   │   print("Adding to db", flush=True)                     │
h2ogpt-h2o-llm-1  | │   1757 │   if not db:                                                        │
h2ogpt-h2o-llm-1  | │   1758 │   │   if sources:                                                   │
h2ogpt-h2o-llm-1  | │ ❱ 1759 │   │   │   db = get_db(sources, use_openai_embedding=use_openai_embe │
h2ogpt-h2o-llm-1  | │   1760 │   │   │   │   │   │   persist_directory=persist_directory, langchai │
h2ogpt-h2o-llm-1  | │   1761 │   │   │   │   │   │   hf_embedding_model=hf_embedding_model)        │
h2ogpt-h2o-llm-1  | │   1762 │   │   │   if verbose:                                               │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /workspace/src/gpt_langchain.py:68 in get_db                                 │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │     65 │   │   return None                                                   │
h2ogpt-h2o-llm-1  | │     66 │                                                                     │
h2ogpt-h2o-llm-1  | │     67 │   # get embedding model                                             │
h2ogpt-h2o-llm-1  | │ ❱   68 │   embedding = get_embedding(use_openai_embedding, hf_embedding_mode │
h2ogpt-h2o-llm-1  | │     69 │   assert collection_name is not None or langchain_mode != 'notset'  │
h2ogpt-h2o-llm-1  | │     70 │   if collection_name is None:                                       │
h2ogpt-h2o-llm-1  | │     71 │   │   collection_name = langchain_mode.replace(' ', '_')            │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /workspace/src/gpt_langchain.py:260 in get_embedding                         │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │    257 │   │   model_kwargs = dict(device=device)                            │
h2ogpt-h2o-llm-1  | │    258 │   │   if 'instructor' in hf_embedding_model:                        │
h2ogpt-h2o-llm-1  | │    259 │   │   │   encode_kwargs = {'normalize_embeddings': True}            │
h2ogpt-h2o-llm-1  | │ ❱  260 │   │   │   embedding = HuggingFaceInstructEmbeddings(model_name=hf_e │
h2ogpt-h2o-llm-1  | │    261 │   │   │   │   │   │   │   │   │   │   │   │   │     model_kwargs=mo │
h2ogpt-h2o-llm-1  | │    262 │   │   │   │   │   │   │   │   │   │   │   │   │     encode_kwargs=e │
h2ogpt-h2o-llm-1  | │    263 │   │   else:                                                         │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /usr/local/lib/python3.10/dist-packages/langchain/embeddings/huggingface.py: │
h2ogpt-h2o-llm-1  | │ 137 in __init__                                                              │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │   134 │   │   try:                                                           │
h2ogpt-h2o-llm-1  | │   135 │   │   │   from InstructorEmbedding import INSTRUCTOR                 │
h2ogpt-h2o-llm-1  | │   136 │   │   │                                                              │
h2ogpt-h2o-llm-1  | │ ❱ 137 │   │   │   self.client = INSTRUCTOR(                                  │
h2ogpt-h2o-llm-1  | │   138 │   │   │   │   self.model_name, cache_folder=self.cache_folder, **sel │
h2ogpt-h2o-llm-1  | │   139 │   │   │   )                                                          │
h2ogpt-h2o-llm-1  | │   140 │   │   except ImportError as e:                                       │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /usr/local/lib/python3.10/dist-packages/sentence_transformers/SentenceTransf │
h2ogpt-h2o-llm-1  | │ ormer.py:95 in __init__                                                      │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │    92 │   │   │   │   │   │   │   │   │   │   use_auth_token=use_auth_token) │
h2ogpt-h2o-llm-1  | │    93 │   │   │                                                              │
h2ogpt-h2o-llm-1  | │    94 │   │   │   if os.path.exists(os.path.join(model_path, 'modules.json') │
h2ogpt-h2o-llm-1  | │ ❱  95 │   │   │   │   modules = self._load_sbert_model(model_path)           │
h2ogpt-h2o-llm-1  | │    96 │   │   │   else:   #Load with AutoModel                               │
h2ogpt-h2o-llm-1  | │    97 │   │   │   │   modules = self._load_auto_model(model_path)            │
h2ogpt-h2o-llm-1  | │    98                                                                        │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /usr/local/lib/python3.10/dist-packages/InstructorEmbedding/instructor.py:47 │
h2ogpt-h2o-llm-1  | │ 4 in _load_sbert_model                                                       │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │   471 │   │   │   │   module_class = INSTRUCTOR_Pooling                      │
h2ogpt-h2o-llm-1  | │   472 │   │   │   else:                                                      │
h2ogpt-h2o-llm-1  | │   473 │   │   │   │   module_class = import_from_string(module_config['type' │
h2ogpt-h2o-llm-1  | │ ❱ 474 │   │   │   module = module_class.load(os.path.join(model_path, module │
h2ogpt-h2o-llm-1  | │   475 │   │   │   modules[module_config['name']] = module                    │
h2ogpt-h2o-llm-1  | │   476 │   │                                                                  │
h2ogpt-h2o-llm-1  | │   477 │   │   return modules                                                 │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /usr/local/lib/python3.10/dist-packages/InstructorEmbedding/instructor.py:30 │
h2ogpt-h2o-llm-1  | │ 6 in load                                                                    │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │   303 │   │                                                                  │
h2ogpt-h2o-llm-1  | │   304 │   │   with open(sbert_config_path) as fIn:                           │
h2ogpt-h2o-llm-1  | │   305 │   │   │   config = json.load(fIn)                                    │
h2ogpt-h2o-llm-1  | │ ❱ 306 │   │   return INSTRUCTOR_Transformer(model_name_or_path=input_path, * │
h2ogpt-h2o-llm-1  | │   307 │                                                                      │
h2ogpt-h2o-llm-1  | │   308 │   def tokenize(self, texts):                                         │
h2ogpt-h2o-llm-1  | │   309 │   │   """                                                            │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /usr/local/lib/python3.10/dist-packages/InstructorEmbedding/instructor.py:24 │
h2ogpt-h2o-llm-1  | │ 0 in __init__                                                                │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │   237 │   │   │   config = AutoConfig.from_pretrained(os.path.join(model_nam │
h2ogpt-h2o-llm-1  | │   238 │   │   else:                                                          │
h2ogpt-h2o-llm-1  | │   239 │   │   │   config = AutoConfig.from_pretrained(model_name_or_path, ** │
h2ogpt-h2o-llm-1  | │ ❱ 240 │   │   self._load_model(self.model_name_or_path, config, cache_dir, * │
h2ogpt-h2o-llm-1  | │   241 │   │                                                                  │
h2ogpt-h2o-llm-1  | │   242 │   │   self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_name_ │
h2ogpt-h2o-llm-1  | │   243                                                                        │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /usr/local/lib/python3.10/dist-packages/sentence_transformers/models/Transfo │
h2ogpt-h2o-llm-1  | │ rmer.py:47 in _load_model                                                    │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │    44 │   def _load_model(self, model_name_or_path, config, cache_dir):      │
h2ogpt-h2o-llm-1  | │    45 │   │   """Loads the transformer model"""                              │
h2ogpt-h2o-llm-1  | │    46 │   │   if isinstance(config, T5Config):                               │
h2ogpt-h2o-llm-1  | │ ❱  47 │   │   │   self._load_t5_model(model_name_or_path, config, cache_dir) │
h2ogpt-h2o-llm-1  | │    48 │   │   else:                                                          │
h2ogpt-h2o-llm-1  | │    49 │   │   │   self.auto_model = AutoModel.from_pretrained(model_name_or_ │
h2ogpt-h2o-llm-1  | │    50                                                                        │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /usr/local/lib/python3.10/dist-packages/sentence_transformers/models/Transfo │
h2ogpt-h2o-llm-1  | │ rmer.py:55 in _load_t5_model                                                 │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │    52 │   │   """Loads the encoder model from T5"""                          │
h2ogpt-h2o-llm-1  | │    53 │   │   from transformers import T5EncoderModel                        │
h2ogpt-h2o-llm-1  | │    54 │   │   T5EncoderModel._keys_to_ignore_on_load_unexpected = ["decoder. │
h2ogpt-h2o-llm-1  | │ ❱  55 │   │   self.auto_model = T5EncoderModel.from_pretrained(model_name_or │
h2ogpt-h2o-llm-1  | │    56 │                                                                      │
h2ogpt-h2o-llm-1  | │    57 │   def __repr__(self):                                                │
h2ogpt-h2o-llm-1  | │    58 │   │   return "Transformer({}) with Transformer model: {} ".format(se │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │ /usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py:2449  │
h2ogpt-h2o-llm-1  | │ in from_pretrained                                                           │
h2ogpt-h2o-llm-1  | │                                                                              │
h2ogpt-h2o-llm-1  | │   2446 │   │   │   │   │   │   " to load this model from those weights."     │
h2ogpt-h2o-llm-1  | │   2447 │   │   │   │   │   )                                                 │
h2ogpt-h2o-llm-1  | │   2448 │   │   │   │   else:                                                 │
h2ogpt-h2o-llm-1  | │ ❱ 2449 │   │   │   │   │   raise EnvironmentError(                           │
h2ogpt-h2o-llm-1  | │   2450 │   │   │   │   │   │   f"Error no file named {_add_variant(WEIGHTS_N │
h2ogpt-h2o-llm-1  | │   2451 │   │   │   │   │   │   f" {TF_WEIGHTS_NAME + '.index'} or {FLAX_WEIG │
h2ogpt-h2o-llm-1  | │   2452 │   │   │   │   │   │   f" {pretrained_model_name_or_path}."          │
h2ogpt-h2o-llm-1  | ╰──────────────────────────────────────────────────────────────────────────────╯
h2ogpt-h2o-llm-1  | OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or
h2ogpt-h2o-llm-1  | flax_model.msgpack found in directory
h2ogpt-h2o-llm-1  | /root/.cache/torch/sentence_transformers/hkunlp_instructor-large/.
h2ogpt-h2o-llm-1 exited with code 0

any model that I add is also crash with same result
command: generate.py --base_model=h2oai/h2ogpt-oasst1-512-12b --load_8bit=True  --score_model=None --langchain_mode='UserData' --user_path=user_path

**Comment by naumfujimori** [comment]
corrupted /root/.cache folder
after delete the folder looks like is working.

**Comment by pseudotensor** [comment]
Thanks!
