### ISSUE TITLE
Add support matrix for CPU/GPU and expected RAM/GPU/etc.

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#510]
https://github.com/h2oai/h2ogpt/issues/443#issuecomment-1642941619

**Comment by pseudotensor** [comment]
@Mathanraj-Sharma can you help for M1 side?  Are all MAC M1/M2's basically same goodness?

**Comment by Mathanraj-Sharma** [comment]
@pseudotensor Most of the items that work for M1 should work for M2 theoretically since the major difference between them is the number of cores and the amount of memory they support. 

What are the items we need to cover for the support matrix? An example might help

**Comment by pseudotensor** [comment]
too much work for now
