### ISSUE TITLE
Model runs on CPU instead of GPU

### ISSUE THREAD

**Issue by DuuuDik** [h2oai/h2ogpt#512]
Hello, I am kinda noobie in LLM models. Trying out this new UI h2ogpt on my local computer with 3070Ti 8GB.
I am launching 4b model from[Q&A section command](https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md)
python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --score_model=None --load_4bit=True --langchain_mode='MyData'

which runs very slow and it seems like, it does not use GPU memory at all. Instead it seems like CPU and RAM do all the work. 
I am confuced, please tell me what I am doing wrong

**Comment by brooqs** [comment]
Same problem i faced today. I am using conda. While conda activated "conda install cudatoolkit" this command solve my problem.

**Comment by pseudotensor** [comment]
You guys using linux, windows, or mac?

**Comment by DuuuDik** [comment]
I am using Windows 11. I was using step-by-step guide to set up UI, idk, it might be relevant.
@brooqs, thank you for sharing, I will try your solution on my machine in, approximatly, 8 hours :)

**Comment by brooqs** [comment]
> You guys using linux, windows, or mac?

I am using ubuntu 22.04 LTS.

**Comment by pseudotensor** [comment]
Did you check that torch uses GPU?
```
then check that can see CUDA from Torch:
```python
import torch
print(torch.cuda.is_available())
```
should print True.
```

Need to ensure torch is installed with 
```
pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu118
```

**Comment by DuuuDik** [comment]
I installed cudatoolkit in my venv and it didnt solve the problem 😞 
Activated command for torch installment on user while venv was active.
`pip install --user -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu118`

But model still runs w\o GRU resources, torch test still showing false
```python
python  
import torch  
print(torch.cuda.is_available())```

**Comment by pseudotensor** [comment]
Why do you have the `--user` option?  It's like your env isn't conda, you shouldn't need that.

**Comment by pseudotensor** [comment]
I revamped and fully tested the docs for windows, please try again: https://github.com/h2oai/h2ogpt/blob/main/docs/README_WINDOWS.md
