### ISSUE TITLE
Inadequate RAM usage in CPU only mode

### ISSUE THREAD

**Issue by pro100vald** [h2oai/h2ogpt#518]
I have a windows 11 system, with h2ogpt installation done exactly like in readme, with all of the optional requirements. The web ui is launched with a given command, all the settings are left to default, and the response is generated for a simple prompt "Hello!". 

`python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --score_model=None  --prompt_type=human_bot`

To generate the response, python.exe allocates 27GB of RAM, which is twice the amount of disk space used to store the entire model. Expected behavior: inference by CPU should use amount of RAM that is comparable to the size of the model files. 
I`ve also tested the program with launch options --load_half=True; --load_8bit=True and --load_4bit=True. The described RAM usage is the same for all of the mentioned options. Also, the amount of used RAM does not drop over time. It seems that regardless of launch options the model is always loaded in 32bit mode, or there is a memory leak.

**Comment by pseudotensor** [comment]
Do you have a GPU?  CPU mode for those Hugging Face models will operate in 32-bit mode since that is what the CPU supports in torch.  You'd need to use a GGML (i.e. --base_model='llama') type setup for CPU to get good performance.  Let me know!

**Comment by pro100vald** [comment]
I do have an rtx3060ti (8GB VRAM) that can run some models in 4bit mode, but 7B 4 bit model is quite limited in it`s cognitive abilities, and my local generation on GPU is much worse that the available public demo of the same model. That`s why I wanted to try falcon 7b specifically on CPU, without 4bit or 8bit optimization. It`s odd that cpu generation can`t load a model at least in 16 bit mode.
