### ISSUE TITLE
Weaviate: Investigate flaky integration tests

### ISSUE THREAD

**Issue by hsm207** [h2oai/h2ogpt#520]
From [discord](https://discord.com/channels/1097462770674438174/1131275074788397157/1131790323257983066):
>E.g. in an integration test: test_make_add_db when doing weaviate, the test sometimes hits an assertion assert len(docs) == 3 and is 4 instead.  I thought it was fixed with new weaviate, but while it passed once, more often later it does not

Might be related to weaviate/weaviate-python-client#349

**Comment by pseudotensor** [comment]
I thought it was because the server was still up, but I kill that process and still happens.  I guess it's accumulation during use, not sure.

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/pull/690/commits/fe8e4fe4982a5e3219103f0a025f2457add9f71b
