### ISSUE TITLE
Need help not recognising gpu

### ISSUE THREAD

**Issue by Toaster496** [h2oai/h2ogpt#525]
![image](https://github.com/h2oai/h2ogpt/assets/124654952/8b72bc15-3810-4f4f-9460-c2eb4271679c)

then does not work

**Comment by pseudotensor** [comment]
Hi, the only time I saw windows not use GPU was my first time installing and not doing this:
```
pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu118
```
i.e. need the --extra-index-url.

**Comment by multimokia** [comment]
Having the same issue here, Torch doesn't see my GPU for some reason

**Comment by pseudotensor** [comment]
I went through entire windows documentation and updated it, and confirmed GPU working etc.  Please try updated docs: https://github.com/h2oai/h2ogpt/blob/main/docs/README_WINDOWS.md

**Comment by billyisthegoat** [comment]
I'm not sure what's going on, but one of these uses my GPU, while one doesn't.

GPU: 3060 12GB

Uses GPU: `python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --score_model=None --load_8bit=True --langchain_mode='UserData'` This will use my GPU.

Cannot detect GPU: `python generate.py --base_model='llama' --prompt_type=llama2 --score_model=None --load_8bit=True --langchain_mode='UserData'` does not even find it. Very odd behavior.`

**Comment by pseudotensor** [comment]
The above must be because you didn't install llama_cpp_python for GPU.  If using windows, maybe try windows installer to avoid hassle.

**Comment by multimokia** [comment]
I found manually installing pytorch for your cuda version also works. You'll have to specify it but sometimes pip just doesn't get it right.

**Comment by pseudotensor** [comment]
@multimokia Ok thanks.  Yes, one has to be sure torch is installed and GPU visible by checking that basic torch available gpu command.

**Comment by multimokia** [comment]
yeah for me when getting the requirements pip only installed the +cpu version. Figure it might help for others to check which version got installed and correct if necessary

**Comment by pseudotensor** [comment]
@multimokia Is there something wrong or can be improved with this part of docs?

* Install primary dependencies.

  * For CPU Only:
      ```bash
      pip install -r requirements.txt --extra-index https://download.pytorch.org/whl/cpu
       ```
  * For GPU:
      ```bash
      pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu117
       ```

**Comment by multimokia** [comment]
for some reason even when doing that it kept keeping only the cpu version. However after completely uninstalling torch I replaced with

`pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu121`
to also get the latest supported version of CUDA. Which seems to run fine without issue on my end
