### ISSUE TITLE
how can i check the generation args when I set the share=True in python generation.py?

### ISSUE THREAD

**Issue by zyzisastudyreallyhardguy** [h2oai/h2ogpt#527]
Dear H2OGPT team,

Are there any ways that we can check the generation args easily? like every time we launch a transformer model, we can know the generation parameters like temperature, top_k, top_p, do_sample, etc, easily.

Warmest Regards

**Comment by pseudotensor** [comment]
The generation parameters are independent of the training, so one doesn't know ahead of time what will work somehow.  One can vary them and see what works best for your use case.

**Comment by zyzisastudyreallyhardguy** [comment]
Hi, 

I mean I want to see the default generation parameter setting for text generation.

Warmest Regards

**Comment by pseudotensor** [comment]
The default are shown in expert settings in UI.
