### ISSUE TITLE
Error when run simple generate command from go_gradio

### ISSUE THREAD

**Issue by Das1206** [h2oai/h2ogpt#528]
I followed the [CPU tutorial ](https://github.com/h2oai/h2ogpt/blob/main/docs/README_CPU.md) and at the last step I get this error. 

This issue was also [raised by](https://github.com/h2oai/h2ogpt/issues/503) which was [directed to ](https://github.com/h2oai/h2ogpt/issues/461)

I see that I have the right torch version 2.0.1 installed. I still get the same error. 

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\roshi\h2ogpt\generate.py:16 in <module>                                                 │
│                                                                                                  │
│   13                                                                                             │
│   14                                                                                             │
│   15 if __name__ == "__main__":                                                                  │
│ ❱ 16 │   entrypoint_main()                                                                       │
│   17                                                                                             │
│                                                                                                  │
│ C:\Users\roshi\h2ogpt\generate.py:12 in entrypoint_main                                          │
│                                                                                                  │
│    9                                                                                             │
│   10                                                                                             │
│   11 def entrypoint_main():                                                                      │
│ ❱ 12 │   fire.Fire(main)                                                                         │
│   13                                                                                             │
│   14                                                                                             │
│   15 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\roshi\anaconda3\envs\gpt_project\lib\site-packages\fire\core.py:141 in Fire             │
│                                                                                                  │
│   138 │   context.update(caller_globals)                                                         │
│   139 │   context.update(caller_locals)                                                          │
│   140                                                                                            │
│ ❱ 141   component_trace = _Fire(component, args, parsed_flag_args, context, name)                │
│   142                                                                                            │
│   143   if component_trace.HasError():                                                           │
│   144 │   _DisplayError(component_trace)                                                         │
│                                                                                                  │
│ C:\Users\roshi\anaconda3\envs\gpt_project\lib\site-packages\fire\core.py:475 in _Fire            │
│                                                                                                  │
│   472 │     is_class = inspect.isclass(component)                                                │
│   473 │                                                                                          │
│   474 │     try:                                                                                 │
│ ❱ 475 │   │   component, remaining_args = _CallAndUpdateTrace(                                   │
│   476 │   │   │   component,                                                                     │
│   477 │   │   │   remaining_args,                                                                │
│   478 │   │   │   component_trace,                                                               │
│                                                                                                  │
│ C:\Users\roshi\anaconda3\envs\gpt_project\lib\site-packages\fire\core.py:691 in                  │
│ _CallAndUpdateTrace                                                                              │
│                                                                                                  │
│   688 │   loop = asyncio.get_event_loop()                                                        │
│   689 │   component = loop.run_until_complete(fn(*varargs, **kwargs))                            │
│   690   else:                                                                                    │
│ ❱ 691 │   component = fn(*varargs, **kwargs)                                                     │
│   692                                                                                            │
│   693   if treatment == 'class':                                                                 │
│   694 │   action = trace.INSTANTIATED_CLASS                                                      │
│                                                                                                  │
│ C:\Users\roshi\h2ogpt\src\gen.py:775 in main                                                     │
│                                                                                                  │
│    772 │   │   │   caption_loader = False                                                        │
│    773 │   │                                                                                     │
│    774 │   │   # assume gradio needs everything                                                  │
│ ❱  775 │   │   go_gradio(**locals())                                                             │
│    776                                                                                           │
│    777                                                                                           │
│    778 def get_config(base_model,                                                                │
│                                                                                                  │
│ C:\Users\roshi\h2ogpt\src\gradio_runner.py:414 in go_gradio                                      │
│                                                                                                  │
│    411 │   │   │   │   │   │   interactive=True,                                                 │
│    412 │   │   │   │   │   │   visible=False)  # WIP                                             │
│    413 │   │   │   col_tabs = gr.Column(elem_id="col_container", scale=10)                       │
│ ❱  414 │   │   │   with (col_tabs, gr.Tabs()):                                                   │
│    415 │   │   │   │   with gr.TabItem("Chat"):                                                  │
│    416 │   │   │   │   │   if kwargs['langchain_mode'] == 'Disabled':                            │
│    417 │   │   │   │   │   │   text_output_nochat = gr.Textbox(lines=5, label=output_label0, sh  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: _  _ enter _  _

**Comment by pseudotensor** [comment]
What if you do the other work-around?

https://github.com/h2oai/h2ogpt/issues/461#issuecomment-1636886554

**Comment by Das1206** [comment]
I replaced the  `with context(device):`  with `with NullContext()`
In this part of the #461 │ /home/llm/h2ogpt/src/gen.py:1124 in get_hf_model │
│ │
│ 1121 │ │ if not lora_weights: │
│ 1122 │ │ │ # torch.device context uses twice memory for AutoGPTQ │
│ 1123 │ │ │ context = NullContext if load_gptq else torch.device │
│ ❱ 1124 │ │ │ with context(device): │
│ 1125 │ │ │ │ │
│ 1126 │ │ │ │ if use_gpu_id: │
│ 1127 │ │ │ │ │ config, model = get_config(base_model, return_model=True, raise_exce │

The original issue still persists

**Comment by pseudotensor** [comment]
Hmm, that's not even torch related, just a "with" for gradio.

**Comment by pseudotensor** [comment]
Sorry I confused original stack trace, I didn't look.  You are only seeing it for with in gradio.  Very odd.

**Comment by pseudotensor** [comment]
You must have python < 3.10 before the double "with" was supported.  I'll see if I can change that back to something supported in python 3.8, but is there some reason you are not using python 3.10?

**Comment by Das1206** [comment]
Thank you, it works on python 3.10, I was running 3.8 to run my own add-ons.
