### ISSUE TITLE
how to add bulk pdfs?

### ISSUE THREAD

**Issue by payanthe** [h2oai/h2ogpt#532]
I am going to add many pdfs (more than 100) to Q/A from them is there any easy way?

**Comment by pseudotensor** [comment]
Either use make_db as explained in docs https://github.com/h2oai/h2ogpt/blob/main/docs/README_LangChain.md#database-creation

Or just add them all to `user_path` (mentioned a bit lower in above link) and choose that for CLI like in docs and when generate starts it'll process them.  Later uses of generate won't need to pass `user_path`.
