### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

### ISSUE THREAD

**Issue by GitOverHere** [h2oai/h2ogpt#533]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
Downloading (…)l-00001-of-00003.bin:  48%|█████████████████████████████████████████████████████████████▎                                                                   | 4.70G/9.88G [00:22<03:06, 27.8MB/s]

**Comment by pseudotensor** [comment]
outage at huggingface, not easy to deal with, it shouldn't happen too often that they have outages.
