### ISSUE TITLE
Change model download directory

### ISSUE THREAD

**Issue by multimokia** [h2oai/h2ogpt#534]
Hi there, I'm trying to figure out how to change the download location of models since my primary drive is mostly full and I keep everything else on my secondary.

I've tried setting `HF_DATASETS_CACHE` to a location on the second drive however it seems to be ignored. Is there something I'm missing or is there no way to change the save location?

**Comment by sveinnpalsson** [comment]
Try TRANSFORMERS_CACHE or HF_HOME, setting these variables worked for me, not sure which one it's using though.

**Comment by a3nima** [comment]
`TRANSFORMERS_CACHE` works!


> REM set huggingface cache dir
> set TRANSFORMERS_CACHE=e:\TEXT-AI\HuggingFaceCache\
> 
I'm using this in my bat file

ps: another way might be to start without base model and then load the model from a drive, where it's already present.

**Comment by multimokia** [comment]
Got it, thank you! I'll give that a go

**Comment by multimokia** [comment]
Closing this as resolved
