### ISSUE TITLE
Error while installing dependancies

### ISSUE THREAD

**Issue by rfour92** [h2oai/h2ogpt#535]
hello, 
I am having difficulties installing the following tools : 

I keep on getting an error every time I install them using pip install -r requirments.txt
I tried to install them one by one and these are the ones that are giving me errors

I cannot seem to overcome this. can you please advise? 
thank you for your time. 

```
gradio==3.37.0
torch==2.0.1; sys_platform != "darwin" and platform_machine != "arm64"
scikit-learn==1.2.2
alt-profanity-check==1.2.2
numpy==1.24.3
pandas==2.0.2
matplotlib==3.7.1
peft==0.4.0
# optional for finetune
tensorboard==2.13.0
# for gradio client
gradio_client==0.2.10
# for gpt4all .env file, but avoid worrying about imports
python-dotenv==1.0.0
# for tokenization when don't have HF tokenizer
tiktoken==0.4.0

```
an example of an error : ```
ERROR: Ignored the following versions that require a different python version: 1.1.1 Requires-Python >=3.8; 1.1.2 Requires-Python >=3.8; 1.1.3 Requires-Python >=3.8; 1.2.1 Requires-Python >=3.8; 1.2.2 Requires-Python >=3.8; 1.3.0 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement alt-profanity-check==1.2.2 (from versions: 0.24.0, 0.24.2, 1.0, 1.0.1, 1.0.2, 1.0.2.1)
ERROR: No matching distribution found for alt-profanity-check==1.2.2
```

**Comment by pseudotensor** [comment]
Seems like you have python 3.7 or lower, but those packages need >=3.8.
