### ISSUE TITLE
Immediate stop of response generation without completing the previous one.

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2ogpt#538]
when we start asking the h2ogpt & it starts the generation of responses but sometimes i want to stop that generation of response with hitting the STOP then i stop the generation but when asking something new then first it completes the previous one and stop. And we have to ask the new information again. Why this happens and how we can resolve this kind of problem.
![Screenshot from 2023-07-25 15-45-34](https://github.com/h2oai/h2ogpt/assets/137979399/7a0afc78-a8ac-4ce8-b383-d44995228a65)

**Comment by pseudotensor** [comment]
Yes, the "stop" doesn't work perfectly.

I have a way to work-around the "bug"  in gradio: https://github.com/h2oai/h2ogpt/issues/298

**Comment by pseudotensor** [comment]
Actually gradio just released 3.38.0 and "stop" for generators was fixed.

https://github.com/gradio-app/gradio/blob/main/CHANGELOG.md

I tested it and it works.  2ce474016b640baa295773b42c6df647de9c4a66

Let me know...

**Comment by llmwesee** [comment]
I do a fresh installation according to the [h2ogpt](https://github.com/h2oai/h2ogpt/tree/main)/[docs](https://github.com/h2oai/h2ogpt/tree/main/docs)
/README_LINUX.md and after successfully installation when i hit ` python generate.py --base_model=h2oai/h2ogpt-oasst1-512-12b --load_8bit=True  --score_model=None --langchain_mode='UserData' --user_path=user_path` it open the chat interface and when i ask something it generate only 20 tokens and in expert tab also you can set only max 20.

**Comment by pseudotensor** [comment]
Hmm, I see same thing.  Must be new bug, thanks.  Debugging.

**Comment by llmwesee** [comment]
Hi, the new bug fixed or not?

**Comment by pseudotensor** [comment]
yes
