### ISSUE TITLE
Extract information through PDF

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2ogpt#539]
Right now h2ogpt only gives textual information from pdf files. if i want to know what kind of information images and tables have in pdf file then how we can extract information through pdf file which contains tables, images and text information.

**Comment by pseudotensor** [comment]
By default h2oGPT consumes as text, and only does OCR if nothing was there (i.e. image pdf).  However, if you pass
```
--enable_pdf_ocr='on'
```
it will parse the document both as textual PDF and do OCR on each page if possible.

See
```
python generate.py --help
```
for more, it's the last option.
