### ISSUE TITLE
Different answers on the same model running in h2ogpt and llama.cpp

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#541]
Hi,
I'm using model : NousResearch:Nous-Hermes-Llama2-13b-GGML/ggml-Hermes-2-step2559-q4_K_M.bin
When I'm running it in llama.cpp, I'm getting answer closer to reality than in h2ogpt (and in llama.cpp it takes less time).
Prompt : 
`what weights more: a pound of lead or a kilogram of feathers ?`

llama.cpp answer :
`Weight and mass are two different things. Weight refers to the force exerted on an object due to gravity. Mass is the amount of matter in an object. So, technically speaking, a pound of lead weighs less than a kilogram of feathers because feathers have more mass than lead since they occupy more space. However, if you are comparing them by volume, then one kilogram of feathers would take up less space than one pound of lead.`

h2ogpt answer : 
`A pound of lead weighs more than a kilogram of feathers. One pound is equal to 0.45359237 kilograms, so a pound of lead would weigh approximately 0.45359237 kilograms or 453.59237 grams. However, the specific gravity of lead is 11.34 g/cm³ and that of feathers is around 0.02 g/cm³. Therefore, a pound of lead would weigh more than a kilogram of feathers because it has a higher density.`

What can be an issue , why on the same model, same prompt (and basically same llama.cpp) I'm getting different answers ?

Thanks

**Comment by pseudotensor** [comment]
Are you using llama.cpp mode with h2ogpt using CPU or GPU?  We just use llama.cpp under the hood, so likely the GPU or CPU is configured differently as far as speed.  Let me know the details of what you are running and I can compare as well, else hard to be sure.

As for generation, that will depend upon the generation hyperparameters.  You will find arbitrary good or bad answers for different quantizations and generation hyper parameters.  So I'm not worried about that.

**Comment by slavag** [comment]
@pseudotensor both are using GPU, but I think it's working eventually with the same speed, maybe it was my Mac too busy.
As for different answers, when you mentioned hyperparameters and quantizations you mean during model training ? 
As I'm using exactly same model file.
Thanks

**Comment by pseudotensor** [comment]
Even with exact same model, llama.cpp defaults to sampling.  E.g. if you look at their readme they have in output:
```
sampling parameters: temp = 0.800000, top_k = 40, top_p = 0.950000
```

I mean these kinds of things:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/5e500ddf-4ee5-4599-8073-ca1875a25e44)


You are free to choose similar generation parameters.  The default is conservative and reproducible (do_sample=False), but if you enable sampling (do_sample=True) then can change temperature, etc. and get more creative responses.
