### ISSUE TITLE
GPU Only: Install CUDA in Windows installation guide 

### ISSUE THREAD

**Issue by DuuuDik** [h2oai/h2ogpt#544]
I notised a mistake in README_WINDOWS.md
```
 conda install cudatoolkit=11.7 -c conda-forge -y
 export CUDA_HOME=$CONDA_PREFIX
```
export does not work for Windows, it is unix shell command
Should be "Set" command instead

**Comment by pseudotensor** [comment]
Oops, thanks, fixed.
