### ISSUE TITLE
How to use other languages than English?

### ISSUE THREAD

**Issue by andypotato** [h2oai/h2ogpt#546]
Is it possible to use documents in other languages than English? Also how would you receive the answers in the language I'm using for my prompts?

**Comment by pseudotensor** [comment]
Yes, models like LLaMa2 support other languages pretty well, especially 70B.

Good to choose a multilingually trained model, but even focus on English isn't too bad.

**Comment by andypotato** [comment]
I tried Llama2 and it does work, there are some quirks however. In addition to writing the prompt in my language, I always need to explicitly specify in the prompt that I want the model to respond in my language. Is this something I can configure, or maybe by updating the prompt template? If so, how?

**Comment by pseudotensor** [comment]
For LLaMa2 we don't use English language prompting for LLM or collection queries at moment.  However, for summarization we have some english words.

If you want to add some changes to langchain prompting you can do it here:

https://github.com/h2oai/h2ogpt/blob/8f82409404bcbc8b7479719a80493eff5f67eae6/src/gpt_langchain.py#L2239-L2286

For direct LLM you can add any extra prompting here:

https://github.com/h2oai/h2ogpt/blob/fcfff881b9ce45e6de1313893bb5f8d5bc1574e9/src/prompter.py#L608-L631

i.e. you could always include a non-english system prompt, and that would also take care of langchain too.
