### ISSUE TITLE
Document Question & Answer With meta-llama/Llama-2-13b-chat-hf

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2ogpt#550]
I want to retrieve information from pdf documents using llama2 but when i hit `python generate.py --base_model=meta-llama/Llama-2-13b-chat-hf --load_8bit=True  --score_model=None --langchain_mode='UserData' --user_path=user_path` it didn't download the model even if i have the access of llama2 weight. so how can i download the model from huggingface using the auth_token and after downloading how can i inference through it.

**Comment by pseudotensor** [comment]
Has nothing directly to do with h2oGPT, just transformers thing.  There are 2 ways:
1)
```
export HUGGING_FACE_HUB_TOKEN=<token goes here>
```
token starts with `hf_` usually.

2) 
```bash
huggingface-cli login
```
in repo.  Then add to generate.py:
```
--use_auth_token=True
```
