### ISSUE TITLE
Cyrillic letters shown with error

### ISSUE THREAD

**Issue by DuuuDik** [h2oai/h2ogpt#552]
I was trying out code gpt model 
```
python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-multilang-2048-falcon-7b --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --score_model=None --load_4bit=True --langchain_mode='UserData'
```
Model works fine, but UI has trouble with cyrillic letters
Is cyrillic works with UI? Or is something else messes with letters?

![for h2ogpt](https://github.com/h2oai/h2ogpt/assets/70808276/ae982e8c-3ee0-49d6-94e3-b3c002877b3b)

**Comment by pseudotensor** [comment]
Good question.  I've seen the UI work fine with many different non-alphabetical languages.

This is freshly tried on gpt.h2o.ai using h2oGPT:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/40fc55a2-2df8-4e5b-94a1-fbde7120deb1)

**Comment by pseudotensor** [comment]
Russian:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/47b04c02-47ec-4566-ab46-6d08e6037e8f)

**Comment by pseudotensor** [comment]
Perhaps there is some locale settings on your system or your browser that mess up things.

You can pass `--save_dir=save` and get the history.json output.  And you can exports the chats to chat*.json file and share.

**Comment by pseudotensor** [comment]
fixed two weeks ago
