### ISSUE TITLE
Model Inference only outputting >>TITLE<<

### ISSUE THREAD

**Issue by bbrosint** [h2oai/h2ogpt#553]
I have tried running the Falcon-7b-v3 model, python 3.9 with cuda 12 :

`python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --score_model=None --prompt_type=human_bot --cli=True --load_8bit=True
Auto set langchain_mode=Disabled  Have langchain package: False
Using Model h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
Starting get_model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
device_map: {'': 0}
bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.19s/it]`

`Enter an instruction: Generic prompt`
`>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<
>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<^C`

The same happens when started with web-interface.

**Comment by pseudotensor** [comment]
I'm not sure.  I don't see the same thing with the same command line:
```
jon@pseudotensor:~/h2ogpt2$ python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --score_model=None --prompt_type=human_bot --cli=True --load_8bit=True
Auto set langchain_mode=LLM.  Could use MyData instead.  To allow UserData to pull files from disk, set user_path or langchain_mode_paths, and ensure allow_upload_to_user_data=True
Using Model h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
Prep: persist_directory=db_dir_UserData does not exist, regenerating
Did not generate db since no sources
Starting get_model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 
/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/configuration_utils.py:483: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1714: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
device_map: {'': 0}
/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/modeling_utils.py:2193: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
bin /home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:08<00:00,  4.20s/it]

Enter an instruction: Who are you?
I am h2oGPT, an open source chatbot that is designed to assist users with a wide range of tasks, including answering questions, providing information, and generating text. I was created by H2O.ai, a non-profit organization that aims to democratize access to advanced AI technologies.
Enter an instruction: 
```

**Comment by bbrosint** [comment]
I downloaded another model (openassistant/falcon-7b-sft-mix-2000)  and it works flawlessly. Hmm, maybe it is just this model version?

**Comment by pseudotensor** [comment]
Not sure, never seen it before, and I ran your same command with no issue.  @psinger any thoughts on that model?

**Comment by bbrosint** [comment]
Hmm, I loaded two other models, they are both fine, just reloaded this one and yes, error persists

[https://imgur.com/a/yY3p0rt](https://imgur.com/a/yY3p0rt)

**Comment by psinger** [comment]
Is this single GPU or sharded?
If sharded, you could check if single GPU makes a difference.

**Comment by bbrosint** [comment]
It is running on a single GPU, a 1080TI

**Comment by pseudotensor** [comment]
You are using prompt_type=human_bot when you shouldn't specify that.  Should be prompt_answer for that model, or let us determine it.

I didn't find any place in docs that did that, so will close.  Thanks
