### ISSUE TITLE
Fine-tuned model with H2OGPT

### ISSUE THREAD

**Issue by zeyund** [h2oai/h2ogpt#557]
Hello H2O team,

Thanks for building this amazing platform. I have a question below:

I have already fine-tuned a model with QLoRA and uploaded it on huggingface. 
While running the model on colab, I substituted the base_model with mine, will it automatically adapt 'tokenizer_base_model': '', and 'lora_weights': '? If not what's the proper way to do it, thanks!

**Comment by pseudotensor** [comment]
@arnocandel Is the HF bug with the lora fixed?  I can't recall.

**Comment by yanmengxiang123456899** [comment]
I also want to insert  a new model in h2ogpt,but I don't have ideas.

**Comment by zeyund** [comment]
@yanmengxiang123456899 
To insert the model, you can adjust the last lane from the colab that H2O provided, if you need additional help please let me know

**Comment by zeyund** [comment]
@pseudotensor hey, just wanna check in, is there any update so far? 

let me clarify my questions for you and your team, I think the previous question might be a little bit confusion. I fin-tuned Falcon-7B, and upload on huggingface. I sucessfully upload my own model on h2ogpt, however, I was wondering will it automatically use the fin-tuned one or the base model of falcon-7B

**Comment by pseudotensor** [comment]
If you uploaded a new model on your HF page, you'd just pass your model link in `--base_model=<your model>` e.g. `h2oai/h2ogpt-oasst1-4096-llama2-7b` as normally needed by HF transformers.  i.e. org/name.
