### ISSUE TITLE
no GPUs detected

### ISSUE THREAD

**Issue by aistartransformer** [h2oai/h2ogpt#559]
Hello,

I am trying to get llama2 installed on my laptop. I am using MacBook Pro, Apple M2 Max, MacOS Ventura 13.0 (22A8380). I have 32 GB unified memory. "32GB of unified memory makes everything you do fast and fluid"
"12-core CPU delivers speeds up to 20 percent faster to fly through pro workflows quicker than ever"
"30-core GPU with faster performance for graphics-intensive apps and games"

 Memory:	32 GB
  Type:	LPDDR5
  Manufacturer:	Hynix

But when I ran the following command,
`python generate.py --base_model='llama' --prompt_type=llama2`
the logs show there is no GPUs detected
```
Auto set langchain_mode=LLM.  Could use MyData instead.  To allow UserData to pull files from disk, set user_path or langchain_mode_paths, and ensure allow_upload_to_user_data=True
No GPUs detected
Using Model llama
```
I am thinking if GPU cannot be used, I may have to return this laptop.

Or changing this line of code
https://github.com/h2oai/h2ogpt/blob/main/src/gen.py#L570
could fix it? Thanks!

**Comment by pseudotensor** [comment]
Hi @Mathanraj-Sharma , please see if you can help, thanks!

**Comment by pseudotensor** [comment]
@aistartransformer Hi, If you followed the "getting started" alone that won't be enough to use GPU.  You'll need to go to the README_MACOS.md and ensure you compile llama_cpp_python package with Metal support.

I tried to make it easy to see what h2oGPT was about in main readme, while the other readmes go into details for full support of GPU or other things.

**Comment by pseudotensor** [comment]
You should download the file as in the windows readme:

[File](https://huggingface.co/TheBloke/WizardLM-7B-uncensored-GGML/resolve/main/WizardLM-7B-uncensored.ggmlv3.q8_0.bin)

**Comment by Mathanraj-Sharma** [comment]
@aistartransformer what did you got for this step

```python
#Verify whether torch uses MPS, run below python script:
 import torch
 if torch.backends.mps.is_available():
     mps_device = torch.device("mps")
     x = torch.ones(1, device=mps_device)
     print (x)
 else:
     print ("MPS device not found.")
```

**Comment by slavag** [comment]
Same here, while llama.cpp detects metal, I do see "No GPUI detected"
<img width="925" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/69a496b6-7adb-482c-b584-20d89a65fad3">

**Comment by pseudotensor** [comment]
The n_gpus issue is just that the number of GPUs registered there is number of CUDA GPUs, which is not relevant for Metal.

**Comment by Mathanraj-Sharma** [comment]
@pseudotensor I'll create a PR to adjust this

**Comment by pseudotensor** [comment]
Thanks.  In general any `torch.cuda` or `torch.backends.cudnn` needs to be avoided for MPS.  So can't go into that block still, but maybe the messaging can be improved.

Also, we should scan through the code to be sure no other such instances are triggered when using MPS.

**Comment by pseudotensor** [comment]
I merged a PR by @Mathanraj-Sharma to avoid the confusing message.

**Comment by 3koozy** [comment]
I have a similar issue running this on windows 10 using conda enviroment.
here is the logs:
nvidia-smi
Fri Jul 28 21:44:29 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.23                 Driver Version: 536.23       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1070      WDDM  | 00000000:01:00.0  On |                  N/A |
|  0%   49C    P8              12W / 230W |    752MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      3532    C+G   ...1.0_x64__8wekyb3d8bbwe\Video.UI.exe    N/A      |
|    0   N/A  N/A      4988    C+G   ...soft Office\root\Office16\EXCEL.EXE    N/A      |
|    0   N/A  N/A      5124    C+G   C:\Windows\explorer.exe                   N/A      |
|    0   N/A  N/A      7824    C+G   ...5n1h2txyewy\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A      7864    C+G   ...t.LockApp_cw5n1h2txyewy\LockApp.exe    N/A      |
|    0   N/A  N/A      8176    C+G   C:\Windows\System32\WWAHost.exe           N/A      |
|    0   N/A  N/A      8188    C+G   ...\cef\cef.win7x64\steamwebhelper.exe    N/A      |
|    0   N/A  N/A      8780    C+G   ...2txyewy\StartMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A      8788    C+G   ....Search_cw5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A      9220    C+G   ...64__8wekyb3d8bbwe\CalculatorApp.exe    N/A      |
|    0   N/A  N/A      9692    C+G   ....Search_cw5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A     10152    C+G   ..._8wekyb3d8bbwe\PaintStudio.View.exe    N/A      |
|    0   N/A  N/A     10608    C+G   ...oogle\Chrome\Application\chrome.exe    N/A      |
|    0   N/A  N/A     10948    C+G   ...CBS_cw5n1h2txyewy\TextInputHost.exe    N/A      |
|    0   N/A  N/A     11928    C+G   ..._8wekyb3d8bbwe\Microsoft.Photos.exe    N/A      |
|    0   N/A  N/A     12328    C+G   ...GeForce Experience\NVIDIA Share.exe    N/A      |
|    0   N/A  N/A     12668    C+G   ...siveControlPanel\SystemSettings.exe    N/A      |
|    0   N/A  N/A     12724    C+G   ...GeForce Experience\NVIDIA Share.exe    N/A      |
|    0   N/A  N/A     13824    C+G   ...inaries\Win64\EpicGamesLauncher.exe    N/A      |
|    0   N/A  N/A     14244    C+G   ...ne\Binaries\Win64\EpicWebHelper.exe    N/A      |
+---------------------------------------------------------------------------------------+


python generate.py --share=False --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --score_model=None --load_4bit=True --prompt_type=human_bot
Auto set langchain_mode=Disabled  Have langchain package: False
**No GPUs detected**
Using Model h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
Starting get_model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [08:00<00:00, 240.42s/it]
Model {'base_model': 'h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3', 'tokenizer_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'human_bot', 'prompt_dict': {'promptA': '', 'promptB': '', 'PreInstruct': '<human>: ', 'PreInput': None, 'PreResponse': '<bot>:', 'terminate_response': ['\n<human>:', '\n<bot>:', '<human>:', '<bot>:', '<bot>:'], 'chat_sep': '\n', 'chat_turn_sep': '\n', 'humanstr': '<human>:', 'botstr': '<bot>:', 'generates_leading_space': True}}
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.

**Comment by pseudotensor** [comment]
@3koozy , The original issue was that MAC MPS was used but print out was just wrong since really meant no CUDA GPUs.  

However, you have CUDA GPUs.  You should check that torch can see your GPUs, since that is all that fails in h2oGPT.

Perhaps you didn't install GPU version of torch as in the readme?

**Comment by 3koozy** [comment]
@pseudotensor 
I have followed the installation steps , and used the following command to install all requirements + CUDA :
`pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu117`

one thing to note is that when I tried running much smaller model : gpt2-xl , I didn't face this warning : "No GPUs detected" and was able to make it work , is this related to specific models ? or perhaps due to lower end hardware ? I am using GTX 1070

**Comment by pseudotensor** [comment]
Yes, that's odd.  That 
```
pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu117
```
should have ensured cuda torch was installed.

**Comment by 3koozy** [comment]
@pseudotensor 
It seems that I skipped some steps , and after doing the following everything worked :) 
1) installed cuda 11.8 version instead of 11.7 with 
`pip3 install torch --index-url https://download.pytorch.org/whl/cu118`

2) installed C++ libraries as in the readme.
3) installed MinGW as in readme.
4) installed : bitsandbytes 4-bit and 8-bit:
```
pip uninstall bitsandbytes -y
pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.40.1.post1-py3-none-win_amd64.whl
```

and now it works fine :D

**Comment by pseudotensor** [comment]
Cool!
