### ISSUE TITLE
not able to run inference on the docker

### ISSUE THREAD

**Issue by jcl2023** [h2oai/h2ogpt#56]
When I ran "sudo docker-compose up -d --build" and use  docker-compose logs -f to check, I got the following errors:
My system has 32 GB DRAM and TitanX GPU, 12GB VRAM:

h2ogpt-h2o-llm-1  |     python generate.py --base_model='togethercomputer/GPT-NeoXT-Chat-Base-20B' --prompt_type='human_bot' --lora_weights='GPT-NeoXT-Chat-Base-20B.merged.json.8_epochs.57b2892c53df5b8cefac45f84d019cace803ef26.28'
h2ogpt-h2o-llm-1  |
h2ogpt-h2o-llm-1  |
h2ogpt-h2o-llm-1  | Using Model eleutherai/gpt-j-6b
h2ogpt-h2o-llm-1  | Get EleutherAI/gpt-j-6B model
h2ogpt-h2o-llm-1  | Traceback (most recent call last):
h2ogpt-h2o-llm-1  |   File "/workspace/generate.py", line 1515, in <module>
h2ogpt-h2o-llm-1  |     fire.Fire(main)
h2ogpt-h2o-llm-1  |   File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 141, in Fire
h2ogpt-h2o-llm-1  |     component_trace = _Fire(component, args, parsed_flag_args, context, name)
h2ogpt-h2o-llm-1  |   File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 475, in _Fire
h2ogpt-h2o-llm-1  |     component, remaining_args = _CallAndUpdateTrace(
h2ogpt-h2o-llm-1  |   File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
h2ogpt-h2o-llm-1  |     component = fn(*varargs, **kwargs)
h2ogpt-h2o-llm-1  |   File "/workspace/generate.py", line 249, in main
h2ogpt-h2o-llm-1  |     go_gradio(**locals())
h2ogpt-h2o-llm-1  |   File "/workspace/generate.py", line 490, in go_gradio
h2ogpt-h2o-llm-1  |     model0, tokenizer0, device = get_model(**all_kwargs)
h2ogpt-h2o-llm-1  |   File "/workspace/generate.py", line 358, in get_model
h2ogpt-h2o-llm-1  |     device = get_device()
h2ogpt-h2o-llm-1  |   File "/workspace/generate.py", line 256, in get_device
h2ogpt-h2o-llm-1  |     raise RuntimeError("only cuda supported")
h2ogpt-h2o-llm-1  | RuntimeError: only cuda supported
h2ogpt-h2o-llm-1  | /usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:107: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
h2ogpt-h2o-llm-1  |   return torch._C._cuda_getDeviceCount() > 0
h2ogpt-h2o-llm-1  | /usr/local/lib/python3.10/dist-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
h2ogpt-h2o-llm-1  |   warn("The installed version of bitsandbytes was compiled without GPU support. "

**Comment by jcl2023** [comment]
@arnocandel 

    Any idea how to fix this issue?

Thanks,

**Comment by arnocandel** [comment]
`The installed version of bitsandbytes was compiled without GPU support` suggests that something is wrong with the base CUDA installation.

We updated the instructions, make sure to follow all steps: https://github.com/h2oai/h2ogpt/blob/main/INSTALL-DOCKER.md

Also, 12GB VRAM and older generation cards might not work, we develop and test on 3090/4090/A6000/A6000Ada/A100 only.
