### ISSUE TITLE
GPU management problem and Limited Max output tokens

### ISSUE THREAD

**Issue by Tonmoregulus** [h2oai/h2ogpt#562]
Hello,

I am trying to get meta-llama/Llama-2-13b-chat-hf on local machine but I encountered two problems.
I'm using Windows10 with 32GB memory and four 3090 graphics cards (each with 24GB of video memory)。
The first is when I ran the following code
```
python generate.py --base_model=meta-llama/Llama-2-13b-chat-hf --langchain_mode=UserData --score_model=None --use_auth_token=True 
```
It occured the following error
```
OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 24.00 GiB total capacity; 23.18 GiB already
allocated; 0 bytes free; 23.19 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting
max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
It seems that it just used my CPU0, but actually I have CPU0,1,2,3 and they all have 24GB memory. I tried to add 
```
CUDA_VISIBLE_DEVICES=0,1,2,3
```
but still didn't work.Also if I try to add
```
--use_gpu_id=False
```
then the model would restart downloading from hugging face.

So I had to add
```
--load_8bit=True
```
but then I encountered the second problem. The max output tokens were limited to 20 and wouldn't give any useful answer because of this limitation.
![image](https://github.com/h2oai/h2ogpt/assets/71698693/c4186917-bab3-4b99-af6f-07373d4b97cf)

I checked many readme files and recent issues but didn't find a solution. How can I solve these problems?Thanks!

**Comment by pseudotensor** [comment]
Yes there was a temporary bug about 6 days ago, it was fixed also 5 days ago.
