### ISSUE TITLE
Error:  Getting the Error "Expecting value: line 1 column 1 ( char 0)

### ISSUE THREAD

**Issue by Ajithunni** [h2oai/h2ogpt#567]
I am getting the error "Expecting value: line 1 column 1 ( char 0) whenever I submit a chat.  I am using an Ubuntu Server with gradio user interface for chat. The model I am using is h2ogpt tuned falcon-7b-v3. How can I resolve this error?

<img width="891" alt="Value Error" src="https://github.com/h2oai/h2ogpt/assets/14909760/8e1c1cae-a77e-43aa-b0b1-63a5e294c1b5">

**Comment by pseudotensor** [comment]
The console probably says something more useful.  Please share.

**Comment by Ajithunni** [comment]
Here is the console output -->
(h2ogpt) ajith@INPRJ-AIML01:~/h2ogpt$ export https_proxy="http://ajith.unnikrishnan:Leicester%4007@158.234.204.62:9090"                                      (h2ogpt) ajith@INPRJ-AIML01:~/h2ogpt$ python generate.py --share=True --gradio_offline_level=1 --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --load_8bit=True  --score_model=None  --user_path=user_path --prompt_type=human_bot
Auto set langchain_mode=LLM.  Could use UserData instead.
Using Model h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
Prep: persist_directory=db_dir_UserData does not exist, regenerating
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData
Starting get_model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
/home/ajith/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/configuration_utils.py:483: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
/home/ajith/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1714: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
device_map: {'': 0}
/home/ajith/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/modeling_utils.py:2193: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
bin /home/ajith/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:12<00:00,  6.19s/it]
Model {'base_model': 'h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3', 'tokenizer_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'human_bot', 'prompt_dict': {'promptA': '', 'promptB': '', 'PreInstruct': '<human>: ', 'PreInput': None, 'PreResponse': '<bot>:', 'terminate_response': ['\n<human>:', '\n<bot>:', '<human>:', '<bot>:', '<bot>:'], 'chat_sep': '\n', 'chat_turn_sep': '\n', 'humanstr': '<human>:', 'botstr': '<bot>:', 'generates_leading_space': True}}
Running on local URL:  http://0.0.0.0:7860
Running on public URL: https://4d591b14fe4b7aa53a.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)

**Comment by pseudotensor** [comment]
It's not intrinsic to h2oGPT, never seen.  But perhaps google can help, e.g.:

https://github.com/gradio-app/gradio/issues/3330#issuecomment-1449035815
https://stackoverflow.com/questions/74585557/downloading-shares-gives-jsondecodeerror-expecting-value-line-1-column-1-cha

i.e. seems some sort of JSON handling  issue caused by failuree of network.

**Comment by Ajithunni** [comment]
> The console probably says something more useful. Please share.

(h2ogpt) ajith:~/h2ogpt$ python generate.py --share=True --gradio_offline_level=1 --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --load_8bit=True  --score_model=None  --user_path=user_path --prompt_type=human_bot
Auto set langchain_mode=LLM.  Could use UserData instead.
Using Model h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
Prep: persist_directory=db_dir_UserData does not exist, regenerating
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData
Starting get_model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
/home/ajith/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/configuration_utils.py:483: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
/home/ajith/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1714: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
device_map: {'': 0}
/home/ajith/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/modeling_utils.py:2193: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
bin /home/ajith/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [01:03<00:00, 31.53s/it]
Model {'base_model': 'h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3', 'tokenizer_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'human_bot', 'prompt_dict': {'promptA': '', 'promptB': '', 'PreInstruct': '<human>: ', 'PreInput': None, 'PreResponse': '<bot>:', 'terminate_response': ['\n<human>:', '\n<bot>:', '<human>:', '<bot>:', '<bot>:'], 'chat_sep': '\n', 'chat_turn_sep': '\n', 'humanstr': '<human>:', 'botstr': '<bot>:', 'generates_leading_space': True}}
Running on local URL:

**Comment by lesong36** [comment]
I have same issue. @Ajithunni If you found the solution, could you please share, appreciate it.

**Comment by Ajithunni** [comment]
> I have same issue. @Ajithunni If you found the solution, could you please share, appreciate it.

This bug is a result of the proxy configuration in our network. I have not explore this further since I do not intent to use this through a public link.
