### ISSUE TITLE
AMD/ROCm support

### ISSUE THREAD

**Issue by CorneliusCornbread** [h2oai/h2ogpt#569]
A while ago Pytorch announced ROCm support: https://pytorch.org/blog/pytorch-for-amd-rocm-platform-now-available-as-python-package/

So I was wondering how feasible would it be for this project to support ROCm. While it may not be a particularly mature technology, it's definitely one that many users are stuck with due to their hardware choice.

It may also be the case that support for ROCm will have to wait several years for the technology to mature for it to be usable with such a large and complex project.

Cheers!

**Comment by pseudotensor** [comment]
It's probably similar to MPS support.  So you can follow PRs for that by @Mathanraj-Sharma or code that refers to it, and contribute to changes and documentation.  Thanks!

**Comment by nfrik** [comment]
I figured out how to make it work with amd gpu. Please check my fork: https://github.com/nfrik/h2ogpt-rocm

Similar for h2o llm studio: https://github.com/nfrik/h2o-llmstudio-rocm

Note that it depends on the environment and requires you to set appropriate backend variables.

**Comment by pseudotensor** [comment]
@nfrik Hi, cool!  Would you be willing to make a PR and add documentation?

**Comment by devloic** [comment]
I created a new docker image with h2ogpt running on amd GPUs on rocm 5.6.1 . 

docker image : https://hub.docker.com/repository/docker/devloic/rocm-h2ogpt/general

Instructions can be found here :
https://github.com/devloic/h2ogpt-rocm5.6.1/blob/main/rocm-5.6.1/README-rocm.md

Hope this helps

**Comment by pseudotensor** [comment]
Thanks!

**Comment by davidezari** [comment]
@devloic just following your instructions I just get h2ogpt running on an AMD Instinct Mi100 with ROCm 5.7.1

I haven't looked at the dependencies of your work, but if all is self-containeìd into the rocm dir (I suppose not, but you know better) I suggest to integrate it in main, will be so nice to allow others to use AMD GPUs with h2ogpt last release

**Comment by devloic** [comment]
@davidezari Unless you changed the Dockerfile, you have been running h2ogpt with rocm 5.6.1 inside the container ( even though you might have 5.7.1 installed on your host).

**Comment by pseudotensor** [comment]
it's supported via llama_cpp_python choices
