### ISSUE TITLE
Number of requested results 1000 is greater than number of elements in index

### ISSUE THREAD

**Issue by andypotato** [h2oai/h2ogpt#570]
I am getting lots of errors like this. Is this pointing to some problem in my configuration?

**Comment by pseudotensor** [comment]
Related too these two chromadb bugs:
* https://github.com/langchain-ai/langchain/issues/1946#issuecomment-1539597396
* https://github.com/h2oai/h2ogpt/issues/505

Nothing wrong with what you have.
