### ISSUE TITLE
Korean output for WizardLM/WizardLM-13B-V1.2 model (prompt_type=wizard3)

### ISSUE THREAD

**Issue by RohanKaran** [h2oai/h2ogpt#571]
I believe the correct prompt is """A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: hello, who are you? ASSISTANT: """ which is wizard3 in h2ogpt. But the responses are in Korean or Japanese.

**Comment by pseudotensor** [comment]
Yes, I see same thing, e.g. when I run:

```
python --base_model=WizardLM/WizardLM-13B-V1.2 --prompt_type=wizard3 --load_8bit=True
```

But this usually indicates an issue with a space somewhere.  I added a wizard3nospace prompt_type and that seems to work.  I added this model to h2oGPT.

Was:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/a07d9b8c-1a53-46b7-b9e1-d6e8500d21c0)


Now:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/efdadbe1-6341-4294-b058-e558ac571659)


Ref:
https://github.com/nlpxucan/WizardLM/blob/main/WizardLM/src/infer_wizardlm13b.py#L79
