### ISSUE TITLE
GGML_ASSERT ... llama.cpp/ggml-metal.m:795: false && "not implemented"

### ISSUE THREAD

**Issue by Croccodoyle** [h2oai/h2ogpt#572]
Running an M1 Pro MacBook Pro 

Have applied all required config. Can pass a prompt but am returned a blank response in UI and see following error in terminal:

"To create a public link, set `share=True` in `launch()`.
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData
'AsyncRequest' object has no attribute '_json_response_data'
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData
'AsyncRequest' object has no attribute '_json_response_data'
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData
Fatal Python error: Segmentation fault"``

h2ogpt % /Users/xxxxx/miniconda3/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

****************************************************
can also see 
******************************************************

(base) X@X-MBP h2ogpt % python generate.py --base_model='llama' --prompt_type=wizard2 --score_model=None --langchain_mode='UserData' --user_path=user_path
Using Model llama
Prep: persist_directory=db_dir_UserData does not exist, regenerating
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData
Starting get_model: llama 
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
llama.cpp: loading model from llama-2-7b-chat.ggmlv3.q8_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 1792
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 1.0e-06
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 7 (mostly Q8_0)
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: mem required  = 7210.73 MB (+  896.00 MB per state)
llama_new_context_with_model: kv self size  =  896.00 MB
ggml_metal_init: allocating
ggml_metal_init: using MPS
ggml_metal_init: loading '/Users/X/miniconda3/lib/python3.11/site-packages/llama_cpp/ggml-metal.metal'
ggml_metal_init: loaded kernel_add                            0x14ed3fcd0
ggml_metal_init: loaded kernel_add_row                        0x14ed49ee0
ggml_metal_init: loaded kernel_mul                            0x14ed4a140
ggml_metal_init: loaded kernel_mul_row                        0x14ed4a850
ggml_metal_init: loaded kernel_scale                          0x14ed4b670
ggml_metal_init: loaded kernel_silu                           0x14ed4bcf0
ggml_metal_init: loaded kernel_relu                           0x14ed4aeb0
ggml_metal_init: loaded kernel_gelu                           0x14ed4c390
ggml_metal_init: loaded kernel_soft_max                       0x14ed4c9b0
ggml_metal_init: loaded kernel_diag_mask_inf                  0x14ed4d030
ggml_metal_init: loaded kernel_get_rows_f16                   0x14ed4df20
ggml_metal_init: loaded kernel_get_rows_q4_0                  0x14ed4e630
ggml_metal_init: loaded kernel_get_rows_q4_1                  0x14ed4d770
ggml_metal_init: loaded kernel_get_rows_q2_K                  0x14ed4f590
ggml_metal_init: loaded kernel_get_rows_q3_K                  0x14ed4fc80
ggml_metal_init: loaded kernel_get_rows_q4_K                  0x14ed50370
ggml_metal_init: loaded kernel_get_rows_q5_K                  0x14ed50a60
ggml_metal_init: loaded kernel_get_rows_q6_K                  0x14ed51150
ggml_metal_init: loaded kernel_rms_norm                       0x14ed51840
ggml_metal_init: loaded kernel_norm                           0x14ed526c0
ggml_metal_init: loaded kernel_mul_mat_f16_f32                0x12a5c0d40
ggml_metal_init: loaded kernel_mul_mat_q4_0_f32               0x12a5c3510
ggml_metal_init: loaded kernel_mul_mat_q4_1_f32               0x12a5c3ca0
ggml_metal_init: loaded kernel_mul_mat_q2_K_f32               0x12a5c4430
ggml_metal_init: loaded kernel_mul_mat_q3_K_f32               0x12a5c4d70
ggml_metal_init: loaded kernel_mul_mat_q4_K_f32               0x12a5c5680
ggml_metal_init: loaded kernel_mul_mat_q5_K_f32               0x12a5c6480
ggml_metal_init: loaded kernel_mul_mat_q6_K_f32               0x12a5c7120
ggml_metal_init: loaded kernel_rope                           0x12a5c7720
ggml_metal_init: loaded kernel_alibi_f32                      0x12a5c8110
ggml_metal_init: loaded kernel_cpy_f32_f16                    0x12a5c8a00
ggml_metal_init: loaded kernel_cpy_f32_f32                    0x16d234d80
ggml_metal_init: loaded kernel_cpy_f16_f16                    0x16d235a30
ggml_metal_init: recommendedMaxWorkingSetSize = 10922.67 MB
ggml_metal_init: hasUnifiedMemory             = true
ggml_metal_init: maxTransferRate              = built-in GPU
llama_new_context_with_model: max tensor size =   132.81 MB
ggml_metal_add_buffer: allocated 'data            ' buffer, size =  6829.08 MB, ( 6829.53 / 10922.67)
ggml_metal_add_buffer: allocated 'eval            ' buffer, size =    10.00 MB, ( 6839.53 / 10922.67)
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =   898.00 MB, ( 7737.53 / 10922.67)
ggml_metal_add_buffer: allocated 'scr0            ' buffer, size =   212.00 MB, ( 7949.53 / 10922.67)
ggml_metal_add_buffer: allocated 'scr1            ' buffer, size =   160.00 MB, ( 8109.53 / 10922.67)
AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 | 
Model {'base_model': 'llama', 'tokenizer_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'wizard2', 'prompt_dict': {'promptA': 'Below is an instruction that describes a task. Write a response that appropriately completes the request.', 'promptB': 'Below is an instruction that describes a task. Write a response that appropriately completes the request.', 'PreInstruct': '\n### Instruction:\n', 'PreInput': None, 'PreResponse': '\n### Response:\n', 'terminate_response': ['\n### Response:\n'], 'chat_sep': '\n', 'chat_turn_sep': '\n', 'humanstr': '\n### Instruction:\n', 'botstr': '\n### Response:\n', 'generates_leading_space': False}}
Running on local URL:  http://0.0.0.0:7860
To create a public link, set `share=True` in `launch()`.

************************************************************
AFTER I PASS FIRST PROMPT
*************************************************************

0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData
'AsyncRequest' object has no attribute '_json_response_data'
GGML_ASSERT: /private/var/folders/f0/49kp3fz561v_ncy0t2v2gby40000gn/T/pip-install-irei900v/llama-cpp-python_11f2ad4bd47146de908b059125f0b0fa/vendor/llama.cpp/ggml-metal.m:795: false && "not implemented"
Fatal Python error: Aborted

Thread 0x00000004c9607000 (most recent call first):
  File "/Users/X/miniconda3/lib/python3.11/site-packages/llama_cpp/llama_cpp.py", line 678 in llama_eval
  File "/Users/X/miniconda3/lib/python3.11/site-packages/llama_cpp/llama.py", line 461 in eval
  File "/Users/X/miniconda3/lib/python3.11/site-packages/llama_cpp/llama.py", line 721 in generate
  File "/Users/X/miniconda3/lib/python3.11/site-packages/llama_cpp/llama.py", line 899 in _create_completion
  File "/Users/X/miniconda3/lib/python3.11/site-packages/langchain/llms/llamacpp.py", line 280 in Asserting on type 8
stream
  File "/Users/X/working/h2ogpt/src/gpt4all_llm.py", line 305 in _call
  File "/Users/X/miniconda3/lib/python3.11/site-packages/langchain/llms/base.pyGGML_ASSERT: /private/var/folders/f0/49kp3fz561v_ncy0t2v2gby40000gn/T/pip-install-irei900v/llama-cpp-python_11f2ad4bd47146de908b059125f0b0fa/vendor/llama.cpp/ggml-metal.m:738: false && "not implemented"
", line 602 in _generate
Asserting on type 8
  File "/Users/X/miniconda3/lib/python3.11/site-packages/langchain/llms/base.py"GGML_ASSERT: /private/var/folders/f0/49kp3fz561v_ncy0t2v2gby40000gn/T/pip-install-irei900v/llama-cpp-python_11f2ad4bd47146de908b059125f0b0fa/vendor/llama.cpp/ggml-metal.m:738: false && "not implemented"
, line 210 in _generate_helper
  File "Asserting on type 8
/Users/X/miniconda3/lib/python3.11/site-packages/langchain/llms/base.py", line GGML_ASSERT: /private/var/folders/f0/49kp3fz561v_ncy0t2v2gby40000gn/T/pip-install-irei900v/llama-cpp-python_11f2ad4bd47146de908b059125f0b0fa/vendor/llama.cpp/ggml-metal.m:738: false && "not implemented"
279 in generatezsh: abort      python generate.py --base_model='llama' --prompt_type=wizard2   
(base) X@X-MBP h2ogpt % /Users/X/miniconda3/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**********************************************************************************************
RUNNNING 
pip install -r requirements.txt --extra-index https://download.pytorch.org/whl/cpu
Get following error
*****************************************************************************************************

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
argilla 1.1.1 requires pandas<2.0.0,>=1.0.0, but you have pandas 2.0.2 which is incompatible.

**Comment by pseudotensor** [comment]
@Mathanraj-Sharma thoughts?  Seems they need to install metal version of llama-cpp-python.

**Comment by pseudotensor** [comment]
The original titled message is just a cascade of the other failure, so changing the title.

**Comment by Croccodoyle** [comment]
I installed metal version of llama-cpp-python.  Now seeing following:

(base) x@x-MBP h2ogpt % python generate.py --base_model='llama' --prompt_type=llama2                                     
Auto set langchain_mode=LLM.  Could use MyData instead.  To allow UserData to pull files from disk, set user_path or langchain_mode_paths, and ensure allow_upload_to_user_data=True
Using Model llama
Traceback (most recent call last):
  File "/Users/x/working/h2ogpt/generate.py", line 16, in <module>
    entrypoint_main()
  File "/Users/x/working/h2ogpt/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/Users/x/working/h2ogpt/src/utils.py", line 57, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/Users/x/miniconda3/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/x/miniconda3/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/x/miniconda3/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/x/working/h2ogpt/src/gen.py", line 681, in main
    from gpt_langchain import prep_langchain, get_some_dbs_from_hf
  File "/Users/x/working/h2ogpt/src/gpt_langchain.py", line 25, in <module>
    from langchain.callbacks import streaming_stdout
  File "/Users/x/miniconda3/lib/python3.11/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/Users/x/miniconda3/lib/python3.11/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/Users/x/miniconda3/lib/python3.11/site-packages/langchain/agents/agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "/Users/x/miniconda3/lib/python3.11/site-packages/langchain/agents/tools.py", line 4, in <module>
    from langchain.callbacks.manager import (
  File "/Users/x/miniconda3/lib/python3.11/site-packages/langchain/callbacks/__init__.py", line 3, in <module>
    from langchain.callbacks.aim_callback import AimCallbackHandler
  File "/Users/x/miniconda3/lib/python3.11/site-packages/langchain/callbacks/aim_callback.py", line 4, in <module>
    from langchain.callbacks.base import BaseCallbackHandler
  File "/Users/x/miniconda3/lib/python3.11/site-packages/langchain/callbacks/base.py", line 7, in <module>
    from langchain.schema.agent import AgentAction, AgentFinish
  File "/Users/x/miniconda3/lib/python3.11/site-packages/langchain/schema/__init__.py", line 3, in <module>
    from langchain.schema.language_model import BaseLanguageModel
  File "/Users/x/miniconda3/lib/python3.11/site-packages/langchain/schema/language_model.py", line 8, in <module>
    from langchain.schema.output import LLMResult
  File "/Users/x/miniconda3/lib/python3.11/site-packages/langchain/schema/output.py", line 31, in <module>
    class ChatGeneration(Generation):
  File "/Users/x/miniconda3/lib/python3.11/site-packages/langchain/schema/output.py", line 39, in ChatGeneration
    @root_validator
     ^^^^^^^^^^^^^^
  File "/Users/x/miniconda3/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "/Users/x/miniconda3/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.1.1/u/root-validator-pre-skip

**Comment by pseudotensor** [comment]
That looks like you have wrong version of dependencies.  Can you confirm you did:
```
    pip install -r reqs_optional/requirements_optional_langchain.txt
```

Should have `langchain==0.0.235`

**Comment by Croccodoyle** [comment]
I had spotted and fixed - thanks.  Model is running now - just very very slow.  Thanks for your help.

**Comment by pseudotensor** [comment]
Ok, can you confirm the Metal chip is used?

**Comment by slavag** [comment]
@pseudotensor have same issue, reported on it here : https://github.com/h2oai/h2ogpt/issues/561.
Have correct langchain:
```
pip freeze | grep langchain
langchain==0.0.235
```

Have M1 Max chip.

**Comment by pseudotensor** [comment]
@Mathanraj-Sharma any word?

**Comment by slavag** [comment]
@pseudotensor @Mathanraj-Sharma Hi, is there any update on that issue ? Thanks

**Comment by Mathanraj-Sharma** [comment]
@slavag @Croccodoyle which llama model you are using, is it `q8` or `q4`?

llama `q8` models won't work with MPS, you have to use llama `q4`. 

https://github.com/abetlen/llama-cpp-python/blob/main/docs/install/macos.md

this is documented on our MACOS GPU doc as well
