### ISSUE TITLE
I want to insert a new model in h2ogpt.What I should do ？Thanks!

### ISSUE THREAD

**Issue by yanmengxiang123456899** [h2oai/h2ogpt#576]
Like this new model https://huggingface.co/THUDM/chatglm2-6b，I guess that  I need to create a new promter but i can't do it .What I should do next？

**Comment by pseudotensor** [comment]
For a new model, you can pass `--prompt_type=custom --prompt_dict="{....}"` for some dict {....} that doesn't need to contain all these things, but should contain primary ones:
```
        promptA
        promptB
        PreInstruct
        PreInput
        PreResponse
        terminate_response
        chat_sep
        chat_turn_sep
        humanstr
        botstr
```
i.e. see how consumed:

https://github.com/h2oai/h2ogpt/blob/a51576cd174e9fda61f00c3889a26888a604172c/src/prompter.py#L130-L142


Alternatively, yes, you can change the code, but this isn't necessary.  For that case you'd do:

1) In prompter.py, add new key (prompt_type name) and value (model name) into `prompt_type_to_model_name`
2) In prompter.py, add new block in get_prompt()

A simple example to follow is vicuna11, with this block:

```
    elif prompt_type in [PromptType.vicuna11.value, str(PromptType.vicuna11.value),
                         PromptType.vicuna11.name]:
        preprompt = """A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. """ if not (
                chat and reduced) else ''
        start = ''
        promptB = promptA = '%s%s' % (preprompt, start)
        eos = '</s>'
        PreInstruct = """USER: """
        PreInput = None
        PreResponse = """ASSISTANT:"""
        terminate_response = [PreResponse]
        chat_sep = ' '
        chat_turn_sep = eos
        humanstr = PreInstruct
        botstr = PreResponse

        if making_context:
            # when making context, want it to appear as-if LLM generated, which starts with space after :
            PreResponse = PreResponse + ' '
        else:
            # normally LLM adds space after this, because was how trained.
            # if add space here, non-unique tokenization will often make LLM produce wrong output
            PreResponse = PreResponse
```

You can start by changing each thing that appears in the model card that tells about the prompting.


In either case, if the model card doesn't have that information, you'll need to ask or sometimes it'll be in their pipeline file in the files.  Or sometimes the model builds upon another, and you should look at that model card.  Some people who write-up model cards to bad job of adding prompting, then you need to ask in the community section.  TheBloke does pretty good job.

**Comment by yanmengxiang123456899** [comment]
@pseudotensor Thanks for your help!I have run it,but **where do I need to find these parms**{promptA,promptB,PreInstruct,PreInput,PreResponse,terminate_response,chat_sep,chat_turn_sep,humanstr,botstr}.
I edit some parms but error.So I want to know that when you insert a new model,how do you ensure that the parameters of the model are correct？**Can you give me some solutions？Thanks！**

**Comment by pseudotensor** [comment]
36aa2447f7debce2b35002e7f3d5f65e081719ae

**Comment by GitHaubica** [comment]
Edit the gen.py in the src directory

**Comment by pseudotensor** [comment]
You can just pass things on CLI if you don't want to edit gen.py
