### ISSUE TITLE
No DB is used despite it's existing

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#578]
Have DB generated from CSV file, was working fine up to few days ago.
Now log saying :
```
Using Model llama
Prep: persist_directory=db_dir_UserData exists, using
Starting get_model: llama 
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
llama.cpp: loading model from /Users/slava/Documents/Development/private/AI/Models/TheBloke/llama2-7b-GGML/llama-2-7b-chat.ggmlv3.q4_1.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 1792
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 1.0e-06
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 3 (mostly Q4_1)
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: mem required  = 4399.35 MB (+  896.00 MB per state)
llama_new_context_with_model: kv self size  =  896.00 MB
ggml_metal_init: allocating
ggml_metal_init: using MPS
ggml_metal_init: loading '/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/llama_cpp/ggml-metal.metal'
ggml_metal_init: loaded kernel_add                            0x15bdfd2c0
ggml_metal_init: loaded kernel_add_row                        0x15bdfd9e0
ggml_metal_init: loaded kernel_mul                            0x15bdfdf00
ggml_metal_init: loaded kernel_mul_row                        0x15bdfe420
ggml_metal_init: loaded kernel_scale                          0x15bdfe940
ggml_metal_init: loaded kernel_silu                           0x15bdfee60
ggml_metal_init: loaded kernel_relu                           0x15bdff380
ggml_metal_init: loaded kernel_gelu                           0x15bdff8a0
ggml_metal_init: loaded kernel_soft_max                       0x160e0a1b0
ggml_metal_init: loaded kernel_diag_mask_inf                  0x160e041c0
ggml_metal_init: loaded kernel_get_rows_f16                   0x160e04840
ggml_metal_init: loaded kernel_get_rows_q4_0                  0x160e05030
ggml_metal_init: loaded kernel_get_rows_q4_1                  0x160e056b0
ggml_metal_init: loaded kernel_get_rows_q2_K                  0x160e05d30
ggml_metal_init: loaded kernel_get_rows_q3_K                  0x160e063b0
ggml_metal_init: loaded kernel_get_rows_q4_K                  0x160e08550
ggml_metal_init: loaded kernel_get_rows_q5_K                  0x160e08bd0
ggml_metal_init: loaded kernel_get_rows_q6_K                  0x160e09250
ggml_metal_init: loaded kernel_rms_norm                       0x160e09910
ggml_metal_init: loaded kernel_norm                           0x160e0a970
ggml_metal_init: loaded kernel_mul_mat_f16_f32                0x160e0b1d0
ggml_metal_init: loaded kernel_mul_mat_q4_0_f32               0x160e0b890
ggml_metal_init: loaded kernel_mul_mat_q4_1_f32               0x160e0bf50
ggml_metal_init: loaded kernel_mul_mat_q2_K_f32               0x160e0c790
ggml_metal_init: loaded kernel_mul_mat_q3_K_f32               0x160e0ce50
ggml_metal_init: loaded kernel_mul_mat_q4_K_f32               0x160e0d510
ggml_metal_init: loaded kernel_mul_mat_q5_K_f32               0x160e0dbb0
ggml_metal_init: loaded kernel_mul_mat_q6_K_f32               0x160e0e6b0
ggml_metal_init: loaded kernel_rope                           0x160e0ebd0
ggml_metal_init: loaded kernel_alibi_f32                      0x160e0f490
ggml_metal_init: loaded kernel_cpy_f32_f16                    0x160e0fd20
ggml_metal_init: loaded kernel_cpy_f32_f32                    0x160893380
ggml_metal_init: loaded kernel_cpy_f16_f16                    0x1608b62e0
ggml_metal_init: recommendedMaxWorkingSetSize = 21845.34 MB
ggml_metal_init: hasUnifiedMemory             = true
ggml_metal_init: maxTransferRate              = built-in GPU
llama_new_context_with_model: max tensor size =    78.12 MB
ggml_metal_add_buffer: allocated 'data            ' buffer, size =  4017.70 MB, ( 4018.16 / 21845.34)
ggml_metal_add_buffer: allocated 'eval            ' buffer, size =    10.00 MB, ( 4028.16 / 21845.34)
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =   898.00 MB, ( 4926.16 / 21845.34)
ggml_metal_add_buffer: allocated 'scr0            ' buffer, size =   212.00 MB, ( 5138.16 / 21845.34)
ggml_metal_add_buffer: allocated 'scr1            ' buffer, size =   160.00 MB, ( 5298.16 / 21845.34)
AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 | 
Model {'base_model': 'llama', 'tokenizer_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'llama2', 'prompt_dict': {'promptA': '', 'promptB': '', 'PreInstruct': '<s>[INST] ', 'PreInput': None, 'PreResponse': '[/INST]', 'terminate_response': ['[INST]', '</s>'], 'chat_sep': ' ', 'chat_turn_sep': ' </s>', 'humanstr': '[INST]', 'botstr': '[/INST]', 'generates_leading_space': False}}
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Did not generate db since no sources
```

UI don't show any document (after clicking "Update UI with Document(s) from DB"):
<img width="1222" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/fbfe3e56-a988-4529-8ed1-4768ce31e18c">

Executing with that command line :
`python generate.py --base_model=llama --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --chunk_size=256 --top_k_docs=3 --h2ocolors=False --use_llm_if_no_docs=True --use_auth_token=True`

**Comment by pseudotensor** [comment]
The UserData database is stored in db_dirs_UserData.  Does that exist and is filled?

**Comment by pseudotensor** [comment]
FYI I have existing db_dirs_UserData, and running on head of main things work fine:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/40e2ca9d-03c1-441d-84b4-83dd073dd3db)

**Comment by slavag** [comment]
@pseudotensor yes, it's exists and filled
<img width="733" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/8ba3f937-4cdc-428d-802c-b4ffa4942542">
And in the start log I see : `Prep: persist_directory=db_dir_UserData exists, using`

What else I can check ?

**Comment by slavag** [comment]
@pseudotensor I removed entire project folder , cloned again from GitHub, and nothing. Getting : Did not generate db since no sources
When I click on Update UI with document(s) from DB, it just creates strange file in sources_dir, called sources_UserData_fdd2e4ad-9a89-446b-99e5-056db77c194e and shows it here
<img width="833" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/5e23dc17-bc50-4467-b41f-de209f558682">

I don't know what to do, but embedding is not workin.
Thanks

**Comment by pseudotensor** [comment]
Happy to chat in discord on call if that helps.  I can't understand what is wrong.

The download above is to provide a download file that lists the files in the collection.  Yours is empty.

**Comment by pseudotensor** [comment]
Note the original `Did not generate db since no sources` message just means no *new* sources are in the user_path directory.  It doesn't mean it can't find any sources in original database.

However, the rest of your experience suggests the problem still of inability to look up things in the db.

**Comment by slavag** [comment]
@pseudotensor Indeed, something strange. I'll try to explain steps I did. 
Everything, btw was working fine, up to last week, so I don't know  what changed or what I did to cause that issue.
I executed make_db.py (btw, I found that need to provide `--user_path`, without that flag it's failing), so I provided `--user_path=sources_dir`, db was created. then I ran generate.py and got :
`Prep: persist_directory=db_dir_UserData exists, using`. 

After clicking on "Update UI with Documents from DB" created sources_UserData_fdd2e4ad-9a89-446b-99e5-056db77c194e with content `None`, size of 4 bytes and didn't show any documents to choose. 

Then I decided to generate db using generate.py, so I removed previously generated DB, and provided `--user_path=sources_dir` flag, after DB was created by generate.py I can see now , after clicking on "Update UI with Documents from DB" the files that I can choose.
So, I don't know what is wrong, but DB created by make_db somehow not working in my case.

Thanks

**Comment by pseudotensor** [comment]
If you can reproduce with any public files, then feel free to zip your user_path *and* your db directory.  Then give me your exact generate command.  Then I can try to use it.

Yes, make_db needs --user_path else it makes no sense, since make_db's only purpose is to make a database.

**Comment by slavag** [comment]
@pseudotensor sure, will do. As for make_db.py I think in every example in the readme it's without - - user_path

**Comment by pseudotensor** [comment]
Sorry yes, I was just looking, default is "user_path".  If you don't use `user_path` as the location, then you'd need to pass yes.

**Comment by pseudotensor** [comment]
FYI I started from scratch as fresh env and make db using make_db and using it, and it works fine:

```
python src/make_db.py --user_path="/home/jon/Downloads/demo_data" --collection_name=VAData --enable_pdf_ocr='off' --selected_file_types="['pdf', 'html', 'htm']"
python generate.py --langchain_mode=VAData --langchain_modes=['VAData']
```

i.e. I added here:

https://github.com/h2oai/h2ogpt/blob/main/docs/README_LangChain.md#choosing-document-types

**Comment by slavag** [comment]
I'm creating now (2 days already) DB of 48GB of emails. Will see how it'll be created and if it will be loaded, then will try to reproduce with 2 small documents.

**Comment by slavag** [comment]
@pseudotensor it's working, but something strange. I have 3 data set :
1) UserData - was generated by gnerate.py from CSV
2) MailData - was generated by make.db from emls
3) TestData - was generated by make.db from 3 documents (pdf and txt)

 I run next command :
`python generate.py --base_model=llama --prompt_type=llama2 --score_model=None --langchain_modes="['MailData', 'LLM', 'TestData']" --langchain_mode='TestData' --chunk_size=256 --top_k_docs=3 --h2ocolors=False`

While I have MailData and TestData on the disk :
<img width="948" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/b75d8fe1-4268-4009-ac63-8d4814b25944">

The startup log say next :
```
Using Model llama
Prep: persist_directory=db_dir_UserData exists, using
Prep: persist_directory=db_dir_TestData exists, using
Starting get_model: llama 
```
While I didn't asked to work with UserData, and in the UI I see only TestData:
<img width="244" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/182b9a15-1d67-4dbd-b99f-6d1860c95341">

But, when I execute that (only MailData) :
`python generate.py --base_model=llama --prompt_type=llama2 --score_model=None --langchain_modes="['MailData', 'LLM']" --langchain_mode='MailData' --chunk_size=256 --top_k_docs=3 --h2ocolors=False`
Startup log says :
```
Using Model llama
Prep: persist_directory=db_dir_UserData exists, using
Prep: persist_directory=db_dir_MailData exists, using
Starting get_model: llama 
```

And I see MailData in UI and can see documents inside of it:
<img width="1759" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/70a0a147-4dd0-4a2b-acb5-d801224b98de">

Now, I run next command :
`python generate.py --base_model=llama --prompt_type=llama2 --score_model=None --langchain_modes="['UserData', 'TestData', 'LLM']" --langchain_mode='UserData' --chunk_size=256 --top_k_docs=3 --h2ocolors=False`
Startup log says :
```
Using Model llama
Prep: persist_directory=db_dir_UserData exists, using
Starting get_model: llama 
```
So, no TestData at all (but you can see in the 1st run that TestData was working fine), and I don't see it in UI:
<img width="1082" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/55dcd14f-4865-49ec-820c-f39efe6dfe42">
And UserData that was working fine previously now is empty in the document viewer, and nothing I can do to view UserData with documents, as it show for that DB file sources_UserData_e929aa94-04f7-4df6-ba60-eca134f291c8.txt which has 4 bytes, says None (file attached).
[sources_UserData_e929aa94-04f7-4df6-ba60-eca134f291c8.txt](https://github.com/h2oai/h2ogpt/files/12268911/sources_UserData_e929aa94-04f7-4df6-ba60-eca134f291c8.txt)

So, somehow DB or reference to it was corrupted during switches between DB, and behaviour is not consistent.

Thanks

**Comment by pseudotensor** [comment]
Can you also set:
```
--visible_langchain_modes="['MailData', 'LLM', 'TestData']"
```

I'll review the  need for both.

**Comment by pseudotensor** [comment]
I'll also try to repeat your steps, thanks.

**Comment by slavag** [comment]
@pseudotensor eventually all the data became unavailable, have a look on TestData file, from sources_dir (renamed to .txt for upload here), nothing changed in the DB foledrs since the creation:
[sources_TestData_56a7facd-93fe-4011-8beb-98c91191d545.txt](https://github.com/h2oai/h2ogpt/files/12326960/sources_TestData_56a7facd-93fe-4011-8beb-98c91191d545.txt) created on August 06 
[sources_TestData_4bd30bfc-41fb-4a55-8117-c4f37eca7971.txt](https://github.com/h2oai/h2ogpt/files/12326943/sources_TestData_4bd30bfc-41fb-4a55-8117-c4f37eca7971.txt) created on August 11.

Same for the UserData :
[sources_UserData_4b9d955e-8bc1-4b8f-833f-659902aa732e.txt] - Corrupted, contains None , created on August 06 (https://github.com/h2oai/h2ogpt/files/12326958/sources_UserData_4b9d955e-8bc1-4b8f-833f-659902aa732e.txt)
[sources_UserData_62f2c9bc-3a7b-4eab-9715-9e156dc29dca.txt] - Valid, created on August 03 (https://github.com/h2oai/h2ogpt/files/12326959/sources_UserData_62f2c9bc-3a7b-4eab-9715-9e156dc29dca.txt)

**Comment by pseudotensor** [comment]
@slavag I'm aware that after summarization was added, because "chunk_id" is not in metadata for older db, there is issue querying the database.

But in your case even getting list of sources fails, which is a very basic operation of just going through database and collecting all metadata and the "source" meta value.

I still can't reproduce or understand what is happening in your case, or why it's changing.

What I wondered before is if you could provide an example database that has issues.  Else it's hard to diagnose.

**Comment by slavag** [comment]
@pseudotensor Sure 
Attached db and files that DB was generated from them 
[db_dir_TestData.zip](https://github.com/h2oai/h2ogpt/files/12355268/db_dir_TestData.zip)
[files.zip](https://github.com/h2oai/h2ogpt/files/12355273/files.zip)

Thanks

**Comment by pseudotensor** [comment]
@slavag It works fine like this:
```
python generate.py --base_model=llama --langchain_modes=['TestData'] --langchain_mode_types="{'TestData':'shared'}"
```

Basically it assumes, since you didn't specify, that the type was "personal".  I'll make changes so if it isn't provided it's not assumed it's personal but could be either.

FYI if personal, it ends up in a different user folder.

**Comment by pseudotensor** [comment]
![image](https://github.com/h2oai/h2ogpt/assets/2249614/639f4baa-8787-4f77-b27c-b0bc90ef23d8)

**Comment by slavag** [comment]
@pseudotensor thanks a lot. it's working. Small question - if I want to see a TestData and just regular LLM, without TestData, in the same execution and not execute it without TestData, what should I add to the command line ?

Thanks

**Comment by pseudotensor** [comment]
LLM would be what you choose to avoid use of TestData.  But maybe I don't fully understand your question.

**Comment by slavag** [comment]
@pseudotensor 
Well, I don't see LLM here 
<img width="243" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/2ed39b4b-6358-425c-b496-0ccb0d90b19d">
And when I adding to command line `--langchain_modes="['TestData', 'LLM']"` db_dir_LLM folder is created for DB.

**Comment by pseudotensor** [comment]
Sure, it's minor bug that it creates a folder, you can ignore that.

**Comment by slavag** [comment]
Thanks, now it's ok. I see this message in the startup log, is it ok ?
```
Prep: persist_directory= does not exist, regenerating
Did not generate db since no sources
```
For this command line
```
python generate.py --base_model=llama --prompt_type=llama2 --score_model=None --langchain_modes="['TestData', 'MailData', 'LLM']" --langchain_mode_types="{'TestData':'shared', 'MailData':'shared'}" --chunk_size=256 --top_k_docs=3 --h2ocolors=False ----model_path_llama=/Users/slava/Documents/Development/private/AI/Models/TheBloke/llama2-7b-GGML/llama-2-7b-chat.ggmlv3.q4_1.bin  --max_seq_len=2048 --use_llm_if_no_docs=True
```
