### ISSUE TITLE
Reduce Startup Time by Avoiding Repeated Checks of Personal Documents

### ISSUE THREAD

**Issue by quartet** [h2oai/h2ogpt#580]
Hello,

I am using the h2ogpt project to interact with my personal documents. I am using the following command to start the application:

python generate.py \
    --base_model='TheBloke/Llama-2-7B-Chat-GGML' \
    --score_model=None \
    --prompt_type='llama2' \
    --user_path='source_documents' \
    --temperature=0.8 \
    --top_p=0.85 \
    --top_k=50 \
    --num_beams=2 \
    --max_new_tokens=1024 \
    --repetition_penalty=1.1 \
    --early_stopping=True \
    --max_time=180 \
    --num_doc_chunks=3 \
    --chunk_size=1024 \
    --langchain_mode='UserData' \
    --gradio=True

I have a large number of sizable PDF documents, and every time I start the application, it checks all of these documents. This process makes the startup time extremely long, often taking several hours to complete.

I want to know if there is a way to include my personal documents once and then omit the flags that include them for future runs to speed up the startup time. I want the application to remember my documents from previous runs and not check them every time I start the application.

Can you provide guidance on how I can achieve this? Any help would be greatly appreciated.

Thank you in advance for your assistance.

**Comment by pseudotensor** [comment]
Hi.  It shouldn't happen nominally. I'll look into it, thanks.

 It should happen only if:
* Files changed according to the hash
* Embedding was changed relative to database
* If the database didn't have a hash for the file (i.e. was using month old database).
* Embedding wasn't known before (i.e. was using month old database).

A work around is to not set `--user_path`.  If that's not passed during launch, we don't look at those files at all, and we'll just use the existing database.  Links to the files will still work etc.

**Comment by pseudotensor** [comment]
Some changes also to consider:
* If user passes `hf_embedding_model` or we switch due to CPU/GPU, just use existing db's embedding if set instead of migrating unless some extra option is passed.

**Comment by quartet** [comment]
Thank you for the thorough explanation. Just to clarify, if I don't include the --user_path parameter in future runs, will the system still be able to utilize the data from my personal documents to generate responses, as long as the information in those files remains the same? Can you verify this information? I can assure you that the data in these documents is unchanging, so this solution should be viable for me.

**Comment by pseudotensor** [comment]
Yes I verify that access to db still all normal, I confirmed again manually.

**Comment by raymondtri** [comment]
I've noticed an issue with this as well. Even without using --user_path if you include --langchain_mode_paths it will still crawl every url in our lists that we have, because they aren't hashed?

I'm assuming if we can somehow hash during the make_db.py command then it will stop needing to re-load all of the sources every boot?

> Existing db, potentially adding 1626 sources from user_path=/workspace/database_seeds/MyCollectionName
> Found 1626 new sources (1626 have no hash in original source, so have to reprocess for migration to sources with hash)
> Removing 190 duplicate files from db because ingesting those as new documents

Seems like it's re-running embeddings on boot every time

**Comment by pseudotensor** [comment]
I'm working on a PR to control better the migration of embeddings, and will investigate this issue as part of that: https://github.com/h2oai/h2ogpt/pull/585

**Comment by raymondtri** [comment]
Passing --langchain_mode_paths as "None" as the in-code docs suggest https://github.com/h2oai/h2ogpt/blob/f5217602760bcf50c70db7b224afeb6705621aec/src/gen.py#L365 leads to "NoneType" has no attribute 'get' as well, so we can't try to circumvent as the docs would suggest

**Comment by quartet** [comment]
Thanks everyone for looking into this for me. I will go ahead and close the ticket.

**Comment by pseudotensor** [comment]
@quartet Yes, the above PR fixes this problem.
