### ISSUE TITLE
Filelock and psutil issue?

### ISSUE THREAD

**Issue by githubboris** [h2oai/h2ogpt#581]
Please help with the below issue. I run the 'generate.py' but an error occurs in the src/gen.py. Using Python 3.10.12  and filelock module is installed.

(base) borischu@M1 Coding % /Users/borischu/miniconda3/bin/python /Users/coder/Coding/h2oGPT/src/gen.py
Traceback (most recent call last):
  File "/Users/borischu/Coding/h2oGPT/src/gen.py", line 14, in <module>
    import Filelock
ModuleNotFoundError: No module named 'Filelock'

![Screenshot 2023-07-30 at 15 59 03](https://github.com/h2oai/h2ogpt/assets/22012989/6fd7ff6c-97ea-43e7-a28e-8111d52b51a6)

![Screenshot 2023-07-30 at 15 59 33](https://github.com/h2oai/h2ogpt/assets/22012989/7eabd5ca-3cb9-4f61-b6d1-0e1f5875454b)

![Screenshot 2023-07-30 at 16 00 16](https://github.com/h2oai/h2ogpt/assets/22012989/67c83bcf-e956-4462-8ee0-50c9426e3221)

![Screenshot 2023-07-30 at 16 05 32](https://github.com/h2oai/h2ogpt/assets/22012989/7e3ae9fd-6879-4332-a53d-75f840f6e7c2)

**Comment by githubboris** [comment]
Issue was resolved with pulling new files on GitHub.

**Comment by pseudotensor** [comment]
I added those dependencies explicitly in case helps.  Unsure what pulls it in normally vs. why you didn't have it.

**Comment by rovstacion** [comment]
Im getting the same error of import psutil and filelock.

**Comment by pseudotensor** [comment]
@rovstacion Can you give more details?  The above was solved.  And currently psutil and filelock are explicitly listed in requirements.txt.

**Comment by rovstacion** [comment]
@pseudotensor 
![image](https://github.com/h2oai/h2ogpt/assets/92170847/defb394b-6fb3-44f7-88ec-5545ac04897b)
I kept the the codes 'import psutil' and  'import filelock' in generate.py but is still gives me the error to import them as I they already listed in requirements.txt.

**Comment by pseudotensor** [comment]
Must be a pure env issue.  I presume even you cannot do:
```python
import psutil
```
forgetting about h2oGPT.

I see you have `venv` as env name, while following instructions you would have used conda.  Maybe related and you are not using stable env?

**Comment by rovstacion** [comment]
@pseudotensor I already sorted those errors. Thank You!!
![image](https://github.com/h2oai/h2ogpt/assets/92170847/6c98e4ad-d0ff-42dc-a791-64f5cb582b91)
I cannot import enum module as I used 'pip import enum'. How can I import it. Thank You.

**Comment by pseudotensor** [comment]
Don't pip install enum, the enums it's looking for is part of h2oGPT.

You seem to have an odd install, but you  might make things work by doing:
```
setenv PYTHONPATH=.:src:$PYTHONPATH
python generate.py ...
```
with ... as whatever you are running.

If your env in windows is bash like ( I can't tell) then you need to do "export" instead of "setenv" with is tcsh like.  If you are using windows command line shell, that won't work AFAIK.

In general, the shell needs to be Miniconda shell as in docs to avoid various issues like you are experiencing maybe.

Or try one-click windows installer, which has everything in it.

**Comment by rovstacion** [comment]
@pseudotensor Hi mate, 
setenv PYTHONPATH=.:src:$PYTHONPATH
python generate.py ...
This code didn't work to install enums. Can I know another method to fix it in cmd. Thank You!!

**Comment by pseudotensor** [comment]
I can only suggest you try the windows installer if something is unresolved with installation setup.
