### ISSUE TITLE
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' 

### ISSUE THREAD

**Issue by JannikSchneider12** [h2oai/h2ogpt#584]
Hello,

I wanted to run the wizward model as described in the installation guideline for windows. However I am encountering this error when running this command: python generate.py --base_model='llama' --prompt_type=wizard2 --score_model=None --langchain_mode='UserData' --user_path=user_path in the miniconda environment.

I know that there was a similar issue (https://github.com/h2oai/h2ogpt/issues/282) but it didnt worked for me to run 
python -m pip install requests "urllib3<2" as described there.

Thanks for your time and help,

Have a nice day

**Comment by pseudotensor** [comment]
I'm guessing the environment is not fresh and other dependencies are ahead or behind.
