### ISSUE TITLE
Feature Request: Specify HTML Client

### ISSUE THREAD

**Issue by raymondtri** [h2oai/h2ogpt#586]
I see that the unstructured file loader is there by default, it would be awesome if we could instead force sites to be evaluated with selenium (or playwright) instead of that only occurring if there is a problem with loading the url, especially when loading large javascript or pwa-type sites.

**Comment by pseudotensor** [comment]
It already works by using those others as backup if the original failed to get any docs. But yes good to specify.

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/commit/091587f923ce3a35d154d8f2d2066750feee6af4

**Comment by pseudotensor** [comment]
![image](https://github.com/h2oai/h2ogpt/assets/2249614/b40b4a61-d28a-408e-8901-50a0142cac6b)
