### ISSUE TITLE
Allocation of memory between 3 gpus while running Falcon 7b model.

### ISSUE THREAD

**Issue by Shantan243** [h2oai/h2ogpt#589]
Hi Author,

Thanks for your code..

While running this command python generate.py --basemodel=h20ai/h20gpt-gm-osst1-2048-en-Falcon-7b --score_model=None --prompt_type=human_bot --low_8bit=True.

the model gives out ouput that CUDA out of memory with Tried to allocate .. in GPU:0. However, the model is not using GPU1 and GPU2 for any kind of processings. May i know the reason??

This is not only with one 7b model, it is happening for other models to. Every model is saved/stored in GPU:0 by default. We have not expicitly mentioned it.

Also, wanted to know what is the name change given to --infer_devices? I see in one of the issues that setting infer_devices =False and later it is said that infer_devices is given a "better name..:

 /root/.cache/huggingface/modules/transformers_modules/h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v │
│ 3/381b5e888699801426851281677b55f21a508396/modelling_RW.py:500 in __init__                       │
│                                                                                                  │
│    497 │   │   self.alibi = config.alibi                                                         │
│    498 │   │                                                                                     │
│    499 │   │   # Embedding + LN Embedding                                                        │
│ ❱  500 │   │   self.word_embeddings = nn.Embedding(config.vocab_size, self.embed_dim)            │
│    501 │   │                                                                                     │
│    502 │   │   # Transformer blocks                                                              │
│    503 │   │   self.h = nn.ModuleList([DecoderLayer(config) for _ in range(config.num_hidden_la  │
│                                                                                                  │
│ /root/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/torch/nn/modules/sparse.py:142 in       │
│ __init__                                                                                         │
│                                                                                                  │
│   139 │   │   self.norm_type = norm_type                                                         │
│   140 │   │   self.scale_grad_by_freq = scale_grad_by_freq                                       │
│   141 │   │   if _weight is None:                                                                │
│ ❱ 142 │   │   │   self.weight = Parameter(torch.empty((num_embeddings, embedding_dim), **facto   │
│   143 │   │   │   │   │   │   │   │   │   requires_grad=not _freeze)                             │
│   144 │   │   │   self.reset_parameters()                                                        │
│   145 │   │   else:                                                                              │
│                                                                                                  │
│ /root/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/torch/utils/_device.py:62 in            │
│ __torch_function__                                                                               │
│                                                                                                  │
│   59 │   │   kwargs = kwargs or {}                                                               │
│   60 │   │   if func in _device_constructors() and kwargs.get('device') is None:                 │
│   61 │   │   │   kwargs['device'] = self.device                                                  │
│ ❱ 62 │   │   return func(*args, **kwargs)                                                        │
│   63                                                                                             │
│   64 # NB: This is directly called from C++ in torch/csrc/Device.cpp                             │
│   65 def device_decorator(device, func):                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 564.00 MiB (GPU 0; 31.75 GiB total capacity; 0 bytes already allocated; 108.75 MiB free; 0 bytes 
reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory 
Management and PYTORCH_CUDA_ALLOC_CONF
(h2ogpt) root@6f85b083d82a:/workspace/Shantan_Data1/h2ogpt#

**Comment by pseudotensor** [comment]
Try this: https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#multiple-gpus
