### ISSUE TITLE
API documentation unreachable on  http://0.0.0.0:7860/?view=api

### ISSUE THREAD

**Issue by enriquedecote** [h2oai/h2ogpt#590]
I'd like to call the backend from a different frontend, through [next-web frontend](https://github.com/Yidadaa/ChatGPT-Next-Web) and/or a Discord server. 

AFAIK you should be able to reach the API documentation through something like http://0.0.0.0:7860/?view=api
but I just get a blank square with blurred background.

I also cannot reach any endpoint (e.g. http://0.0.0.0:7860/submit_nochat_api)

Am I missing something?

**Comment by pseudotensor** [comment]
I think you are assuming it's a REST API, but instead you should use gradio or our OpenAI compliant client to access the server.
