### ISSUE TITLE
Firewall Acces python exe

### ISSUE THREAD

**Issue by a3nima** [h2oai/h2ogpt#599]
When running the program Windows firewall asks me allow for incoming connection for python exe in the h2ogpt folder.
Does the program need access to function properly? What s going on at that moment?

**Comment by pseudotensor** [comment]
I think the UI needs to talk to the server, and the server is requesting to access the 7680 port for that to happen.

**Comment by a3nima** [comment]
other similar apps dont ask for firewall connection. 

I allowed it and checked with process monitor what connections are made. h2ogpt connects to amazons cloud service aws and there are several tcp connections made to these 3 servers:

```
ec2-52-35-251-35.us-west-2.compute.amazonaws.com
2600:9000:214f:f400:17:b174:6d00:93a1 (--> also amazon )
169.254.169.254:http (internal cloud service ip)
```

wireshark had some details with hugginface.co and gradio.app (or similar) listed. maybe you should perhaps add an offline modifier to the suggested default start parameters, (if it is really offline then) because users might not want to have connections by h2ogpt made to servers without being documented what they are and why they're done??

**Comment by pseudotensor** [comment]
Maybe it's the header that gets the github stars?        You can try passing:
```
--visible_h2ogpt_header=False
```

and see if that removes that traffic.

Also, please see the README_offline.md for chroma and other telemetry that can be disabled.
