### ISSUE TITLE
replicate API instead of local model?

### ISSUE THREAD

**Issue by kenhuang1964** [h2oai/h2ogpt#603]
Is it possible for me to use a replicate API model instead of downloading and running inference locally? Some of the models are too big for my PC to handle.

**Comment by pseudotensor** [comment]
Good idea. https://replicate.com/docs/reference/http

**Comment by pseudotensor** [comment]
Done!

**Comment by kenhuang1964** [comment]
Thank you @pseudotensor! I will let you know how well it works :)

**Comment by kenhuang1964** [comment]
Hey @pseudotensor, I have tried it and it works great! I love this!
