### ISSUE TITLE
Inference on M2 running extremely slow

### ISSUE THREAD

**Issue by jenochs** [h2oai/h2ogpt#605]
M2 32g Mac Pro inference running extremely slow on llama 7b. 

python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-open-llama-7b

Same system benchmark running Llama.cpp:

vicuna-7b-1.1.ggmlv3.q4_0.bin
(   36.22 ms per token,    27.61 tokens per second)

codeup-llama-2-13b-chat-hf.ggmlv3.q4_0.bin
(   68.98 ms per token,    14.50 tokens per second)

llama-30b.ggmlv3.q4_0.bin
(  165.31 ms per token,     6.05 tokens per second)

**Comment by jenochs** [comment]
pip list | grep torch
torch                     2.1.0.dev20230802
torchaudio                2.1.0.dev20230802
torchvision               0.16.0.dev20230802

**Comment by jenochs** [comment]
cpu show ~300% during inference with H20gpt
cpu shows >800% when using llama.cpp

**Comment by pseudotensor** [comment]
1) Torch's support of MPS is basic, so if you use a full HF model you cannot expect good performance as it's not quantized when you run like the above.

2) Can you check that torch can see MPS?

3) Please compile/install llama_cpp_python for MPS and then use GGML models that would be used with `--base_model=llama` after adding the model to the `.env_gpt4all` file.  Some discussion here may help clarify if the other readme's didn't help: https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#adding-models

**Comment by jenochs** [comment]
MPS Validation:

python mps.py 
tensor([1.], device='mps:0')

Compile/install llama_cpp:

pip uninstall llama-cpp-python -y
Found existing installation: llama-cpp-python 0.1.77
Uninstalling llama-cpp-python-0.1.77:
  Successfully uninstalled llama-cpp-python-0.1.77

(h2ocpu) jenochs@MacBook-Pro h2ogpt % CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1 pip install -U llama-cpp-python --no-cache-dir
...Successfully built llama-cpp-python
Installing collected packages: llama-cpp-python
Successfully installed llama-cpp-python-0.1.77

Updated .env_gpt4all:

cat .env_gpt4all                                                         
# GPT4ALL or llama-cpp-python model_kwargs

# GPT4ALl GPT-J type, from model explorer choice, so downloads
model_name_gptj=ggml-gpt4all-j-v1.3-groovy.bin

# llama-cpp-python type, supporting version 3 quantization, here from locally built llama.cpp q4 v3 quantization
# below uses prompt_type=llama2
model_path_llama=llama-2-7b-chat.ggmlv3.q8_0.bin
# below assumes max_new_tokens=256
max_tokens=1792
# uncomment below if using llama-cpp-pyton with cublas built in
n_gpu_layers=20

# GPT4ALl LLaMa type, supporting version 2 quantization, here from model explorer choice so downloads
model_name_gpt4all_llama=ggml-wizardLM-7B.q4_2.bin

# PDF_CLASS_NAME=UnstructuredPDFLoader

model_name_exllama_if_no_config=TheBloke/Nous-Hermes-Llama2-GPTQ

download base model:
wget https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q8_0.bin

Saving to: ‘llama-2-7b-chat.ggmlv3.q8_0.bin’

llama-2-7b-chat.ggmlv3.q8_0.b 100%[==============================================>]   6.67G  70.6MB/s    in 84s     

2023-08-03 03:03:27 (80.8 MB/s) - ‘llama-2-7b-chat.ggmlv3.q8_0.bin’ saved [7160799872/7160799872]

 python generate.py --base_model=llama --prompt_type=llama2 --score_model=None

Auto set langchain_mode=LLM.  Could use MyData instead.  To allow UserData to pull files from disk, set user_path or langchain_mode_paths, and ensure allow_upload_to_user_data=True
Using Model llama
Prep: persist_directory=db_dir_UserData does not exist, regenerating
Did not generate db since no sources
Starting get_model: llama 
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Fatal Python error: Illegal instruction

Whane i run it like this i get an error...Am i missing something. what location should I download the .bin?

**Comment by Mathanraj-Sharma** [comment]
@jenochs AFAIK currently llama only supports `q4` models for MPS

![image](https://github.com/h2oai/h2ogpt/assets/30664910/2b4b3f74-cdc0-4480-9735-4a252dd1d9ad)

So download https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q4_0.bin and try it

**Comment by Mathanraj-Sharma** [comment]
@jenochs any updates?

**Comment by jenochs** [comment]
will update asap thank you

**Comment by zorgonred** [comment]
I had the same issue on the same hardware specs and your solution works! @Mathanraj-Sharma .

(1) I downloaded the link to the repo using:

`wget https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q4_0.bin
`

(2) Then i ran 

`python3 generate.py -base_model=llama --model_path_llama=llama-2-7b-chat.ggmlv3.q4_0.bin --max_seq_len=4096 --prompt_type=llama2
`

**Comment by jenochs** [comment]
> @jenochs any updates?

Validated is working with:

python3 generate.py -base_model=llama --model_path_llama=llama-2-7b-chat.ggmlv3.q4_0.bin --max_seq_len=4096 --prompt_type=llama2

**Comment by kevinschaich** [comment]
@jenochs if you have it working could you share some dots on the performance you've seen here? https://github.com/h2oai/h2ogpt/issues/881
