### ISSUE TITLE
Isn't the point of a demo to demo a working product?

### ISSUE THREAD

**Issue by aodrasa** [h2oai/h2ogpt#61]
Can't even get a response generated and I know I'm not the only one.

**Comment by pseudotensor** [comment]
Sorry you are having trouble.  On HF spaces the instance hits GPU OOM sometimes due to memory fragmentation, but we are seeing if we can help avoid that as much as possible.

**Comment by arnocandel** [comment]
Closing since nothing else to do. It's been working fine all day today, we are using 2x A100 to shard the 20B model.
