### ISSUE TITLE
No module named 'fitz'

### ISSUE THREAD

**Issue by pavelhym** [h2oai/h2ogpt#610]
Getting this issue ater updates. Installing this package leads to another issues frontend package. Finally stuck with error of unexisting directory "static/".

**Comment by pseudotensor** [comment]
Hi, can you share the full stacktrace for last error with static/?

Also, can you explain if you updated all your packages after the update of commit hash?  i.e. did you redo pip install -r .... for all deps?

**Comment by pseudotensor** [comment]
I pushed a HOTFIX that may help the fitz situation.  In meantime I'll try to understand.

**Comment by pseudotensor** [comment]
FYI I did fully fresh install and going through all the package installs leaves me able to import fitz.  So I must assume you didn't install the new langchain etc. dependencies.

**Comment by pavelhym** [comment]
Updated, now works, thanks!

**Comment by pavelhym** [comment]
Fixed by update
