### ISSUE TITLE
Can we use OpenAI API as model in CPU installation?

### ISSUE THREAD

**Issue by MirzaAreebBaig** [h2oai/h2ogpt#611]
Hey,
Just wondering can i use OpenAI API as model because on CPU installation its very slow & i just want the output to be done so is this possible? If yes then how can i get this done?

**Comment by pseudotensor** [comment]
Yes, you can use OpenAI or Replicate

https://github.com/h2oai/h2ogpt/blob/main/docs/README_InferenceServers.md#openai-inference-server-client

https://github.com/h2oai/h2ogpt/blob/main/docs/README_InferenceServers.md#replicate-inference-server-client

Replicate is really cool, just added support yesterday: https://replicate.com/
