### ISSUE TITLE
add vLLM to docker image

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#615]

**Comment by auwsom** [comment]
Hello, can I ask: is there a docker image on Dockerhub that contains all the requirements to run?

**Comment by ChathurindaRanasinghe** [comment]
> Hello, can I ask: is there a docker image on Dockerhub that contains all the requirements to run?
> 
> https://hub.docker.com/u/h2oai
> 
> https://hub.docker.com/r/huggingface/transformers-pytorch-gpu ?

Hello @auwsom currently there is no official docker image for h2ogpt on DockerHub.
However public nightly images are available on GCR: https://console.cloud.google.com/gcr/images/vorvan/global/h2oai/h2ogpt-runtime
