### ISSUE TITLE
.bat file to start h2ogpt webui

### ISSUE THREAD

**Issue by Ron-Caster** [h2oai/h2ogpt#616]
I think you got the idea. 

Like in AUTOMATIC1111's "stable diffsuion web_ui" clicking a .bat file to open would be fantastic. Just sharing my thought as a feedback.

I find it difficult to remember and type the command to start h2ogpt every time.

I create and use .bat files to make opening these easier. Just a suggestion. Please consider.

I will attach the small simple ones just to express what I am meaning.

___________________________________________________________________________________

Filename: alarm.bat
Purpose: It opens alarm.py for me
Content:

start pythonw "%~dp0\alarm.py"

**Comment by pseudotensor** [comment]
I recommend windows installer for this easiness.
