### ISSUE TITLE
Langchain JSON documents

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#619]
Hi,
Is there any plans to add JSON to be supported native data type for Langchain ?

Thanks

**Comment by llmwesee** [comment]
I'm trying to load json file which are 4 mb in size using UI about 15 minutes ago and it still showing "Uploading"  and not showing this json document in "Document Section" nor any embedding created in vector store.

**Comment by pseudotensor** [comment]
@llmwesee It's pretty slow for json I agree, when doing default schema.  Maybe try to set the schema to your specific case, using expert settings for that: https://python.langchain.com/docs/modules/data_connection/document_loaders/json#json-file
