### ISSUE TITLE
Cannot import name 'set_seed'

### ISSUE THREAD

**Issue by donnadulcinea** [h2oai/h2ogpt#622]
I'm stuck with H2oGPT, I can't let it run.

I am running on a Windows PC with

* 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz 2.30 GHz
* 32GB memory 64bit
* GPU Nvidia GeForce RTX 3050

I followed all the procedure described in the [H2oGPT Windows Installation Page](https://github.com/h2oai/h2ogpt/blob/main/docs/README_WINDOWS.md).

This is the command I launch.

`$ python generate.py --base_model='llama' --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=user_path`

This is the error stack trace:

```
Traceback (most recent call last):
  File "C:\Users\dulcin\Documents\Java\UltraGPT\h2ogpt\generate.py", line 7, in <module>
    from src.gen import main
  File "C:\Users\dulcin\Documents\Java\UltraGPT\h2ogpt\src\gen.py", line 32, in <module>
    from utils import set_seed, clear_torch_cache, NullContext, wrapped_partial, EThread, get_githash, \
ImportError: cannot import name 'set_seed' from 'utils' (C:\Users\dulcin\AppData\Local\Programs\Python\Python310\lib\site-packages\utils\__init__.py)
```

I don't understand what I could possibly messed up. I already repeated the setup procedure carefully.

**Comment by pseudotensor** [comment]
Looks like you have a package "utils" installed and it's looking there instead of the local code.

Maybe try:
```
setenv PYTHONPATH=$PYTHONPATH:.:src
python generate.py ...
```

**Comment by donnadulcinea** [comment]
Thank you so much. That was the issue.
In windows I solved setting up the environment variable to the C:\...\h2ogpt\src folder.
But I think the best solution will be to setup a virtual environment.

**Comment by pseudotensor** [comment]
Probably now using windows installer is best, but I'll add note for full readme.
