### ISSUE TITLE
Chat with Docs

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2ogpt#630]
I made a spreadsheet which contain around 2000 question-answer pair and use **meta-llama/Llama-2-13b-chat-hf** model. But when start querying  through it using the above model it gives wrong answers most of the time & also repeat it many times.
So I want to know that what kind of docs format i should try for question-answering & how can i resolve the above problem.

Kindly help me!

**Comment by pseudotensor** [comment]
Can you give example of what you run and then maybe a case when it fails?  Semantic search used in h2oGPT is not a literal search like BM_25 etc., so it's not really good for literal search at moment.
