### ISSUE TITLE
problem installing onnxruntime and chromadb (MACOS - CPU)

### ISSUE THREAD

**Issue by rfour92** [h2oai/h2ogpt#631]
Hello, 

I am following the macos installation tutorial https://github.com/h2oai/h2ogpt/blob/main/docs/README_MACOS.md and I am experiencing this problem bellow. both python and python3 are version 3.10.12, pip and pip3 are version 23.2.1. I am doing the CPU configuration. 

I have tried to install chromadb using conda and it was installed but the problem is it seems that there are a lot of discrepancies. I have also tried to install any version of onnxruntime but it did not work. 

can you please advise? 

> packages (from chromadb==0.3.25->-r reqs_optional/requirements_optional_langchain.txt (line 15)) (0.23.2)
INFO: pip is looking at multiple versions of chromadb to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement onnxruntime>=1.14.1 (from chromadb) (from versions: none)
ERROR: No matching distribution found for onnxruntime>=1.14.1

**Comment by pseudotensor** [comment]
I'm unsure why chroma  needs it, probably doesn't really need it so maybe you can ignore.  Or you can ask chroma-core team what is wrong since it doesn't have to do with h2oGPT specifically.

I can try on my mac (CPU) a bit later.

**Comment by Mathanraj-Sharma** [comment]
@pseudotensor I'll test this on Mac (M1)

**Comment by Mathanraj-Sharma** [comment]
Installation working as expected in `main`!
