### ISSUE TITLE
Missing Kwargs (Requests_State)

### ISSUE THREAD

**Issue by saadtariq-ds** [h2oai/h2ogpt#636]
I am running following command: python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --score_model=None --prompt_type=human_bot --cli=True --use_auth_token=True and facing below error

assert not missing_kwargs, "Missing %s" % missing_kwargs
AssertionError: Missing ['requests_state']

**Comment by pseudotensor** [comment]
Was a bug in main I fixed in PRs that were recently merged.
