### ISSUE TITLE
Cant start with multiple (two) embeddings

### ISSUE THREAD

**Issue by 94bb494nd41f** [h2oai/h2ogpt#637]
When trying to load two separate embeddings i get the following error:
```(venv) PS C:\Users\XXX\PycharmProjects\h2ogpt> python generate.py --base_model="llama" --prompt_type=llama2 --langchain_modes=[ "UserData_JohnerHTML","UserData_60601" ] --visible_langchain_modes=[ "UserData_JohnerHTML","UserData_60601" ]
Traceback (most recent call last):
  File "C:\Users\XXX\PycharmProjects\h2ogpt\generate.py", line 16, in <module>
    entrypoint_main()
  File "C:\Users\XXX\PycharmProjects\h2ogpt\generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "C:\Users\XXX\PycharmProjects\h2ogpt\src\utils.py", line 57, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "C:\Users\XXX\PycharmProjects\h2ogpt\venv\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\XXX\PycharmProjects\h2ogpt\venv\lib\site-packages\fire\core.py", line 475, in _Fire
  File "C:\Users\XXX\PycharmProjects\h2ogpt\venv\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\XXX\PycharmProjects\h2ogpt\src\gen.py", line 517, in main
    visible_langchain_modes = ast.literal_eval(os.environ.get("visible_langchain_modes", str(visible_langchain_modes)))
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 0

SyntaxError: invalid syntax```

When loading just one embedding every thing works as expected.

The two embeddings were created using the commands below:
```
python src/make_db.py --user_path=C:\Users\XXX\Downloads\Y\html\ --collection_name=UserData_JohnerHTML --hf_embedding_model=thenlper/gte-small
python src/make_db.py --user_path=C:\Users\XXX\Downloads\60601_reihe\ --collection_name=UserData_60601 --hf_embedding_model=thenlper/gte-small
```

**Comment by llmwesee** [comment]
I'm also want to try multiple embedding at the same time and want to see how it can improve the generation results.

**Comment by 94bb494nd41f** [comment]
I managed to start it but had to omit the '--langchain_mode_paths' I used pycharm with CMD

`python generate.py  --base_model="llama" --prompt_type=llama2 --langchain_mode="UserData" --langchain_modes="["UserData_JohnerHTML","UserData_60601", "UserData"]" --visible_langchain_modes="["UserData_JohnerHTML","UserData_60601", "UserData"]"`

**Comment by pseudotensor** [comment]
FYI `visible_langchain_modes` is not gone and only `langchain_modes` remains.  But for original issue, you should only get syntax error if didn't quote the string, or you over-quoted it in pycharm for example.  pycharm strings shouldn't have quotes, while bash command line needs quotes if going to include spaces in the string.  If no spaces in the string, just =[] is ok.

**Comment by pseudotensor** [comment]
@94bb494nd41f You can use make_db building of db with 2 different embeddings with 2 different collections (say A and B) both pointing to the same user_path data.    Once both are made, you can tell h2oGPT about them using `--langchain_modes="['A', 'B']"`.  Then you can try same query for each collection in UI, e.g. by disabling chat context and switching collections and hitting "redo" for a given query.
