### ISSUE TITLE
llama2-70B-chat's hardware requirements

### ISSUE THREAD

**Issue by yanmengxiang123456899** [h2oai/h2ogpt#639]
hello！I want to run llama-70B-chat in the h2ogpt.How much **gpu** and **memory** should I prepare？If I have 30G RAM and 8*24G A10g ，can I run it ？Thanks！

**Comment by pseudotensor** [comment]
I mention here you can use AutoGPTQ in exllama to run 70B with only single A6000 worth of memory (i.e. < 48GB):  https://github.com/h2oai/h2ogpt/blob/main/docs/README_GPU.md#exllama
