### ISSUE TITLE
Unable to change context

### ISSUE THREAD

**Issue by gpnath82** [h2oai/h2ogpt#640]
I uploaded 2 pdfs, but bot keep answering question from 1st PDF

I tried document selection, specifically selected 2nd document, but still question are answered from 1st document 

Am I missing something for right document selection 

![image](https://github.com/h2oai/h2ogpt/assets/139639287/cb42f928-5056-462b-8cdb-dcaae1261078)

**Comment by pseudotensor** [comment]
I can't tell from snapshot, but make sure "All" is not still selected.  Also, filter only works for default chroma database.

Here's what I did:

Ingested couple PDFs:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/bcc6e7bf-97d9-4656-a910-06b788c94b06)

Update UI from DB, select dropdown, deselect All, pick 555 PDF.


![image](https://github.com/h2oai/h2ogpt/assets/2249614/1748f7c0-2ab6-40c5-a684-1e9396c08894)

put in a dummy query that would match anything, and see only 555 pdf referenced:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/02942463-6f73-4947-939a-ca8a8ef025d1)

Choose other PDF:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/d402b8f5-701b-4b32-b8fa-e2b34f7bfd06)


Click "redo":

![image](https://github.com/h2oai/h2ogpt/assets/2249614/47315e80-60d2-4150-af2a-2968adc34d1c)


get other PDF only.
