### ISSUE TITLE
Gradio_Runner.py incompatibility with JS client

### ISSUE THREAD

**Issue by raymondtri** [h2oai/h2ogpt#641]
I am attempting to access the gradio api and can do so successfully using the gradio javascript client.

However, when I attempt to access the "add_url" gradio endpoint, the javascript process crashes immediately with the following error:

```
file://node_modules/@gradio/client/dist/index.js:705
  return data.map((d, i) => {
              ^
TypeError: Cannot read properties of undefined (reading 'returns')
```

My lack of python skills is really showing through here, but I was able to fix this issue by updating the js gradio client to use optional chaining off of api_info in the transform_output function.

**Comment by pseudotensor** [comment]
I'm not familiar with the javascript client, but glad you worked around.

Is there something that can be improved in h2oGPT or is this just a gradio issue?

**Comment by raymondtri** [comment]
I'm unsure if it is an h2oGPT or a gradio issue, the gradio PR fixes it, but I was able to produce the error with the h2oGPT repo, I don't have another gradio repo to test it on in isolation so it could be an h2ogpt gradio implementation issue, or it could be a core gradio implementation issue - I am unsure, still working on that python proficiency

**Comment by raymondtri** [comment]
For example, the gradio client file:

```
import * as gradio from "@gradio/client"

export default await gradio.client("http://localhost:7860")
```

Then the javascript client invocation

```
client.predict("add_url", [
      url,
      null, // state?
      null, // another state?
      true, // should chunk? true by default
      512, // chunk size, 512 by default, 128 is minimum
      collection
    ])
```
