### ISSUE TITLE
Feature Request: Multithreaded URL Uploading via Gradio API

### ISSUE THREAD

**Issue by raymondtri** [h2oai/h2ogpt#642]
When using the /add_url endpoint of the gradio_runner API it only works on one url at a time

It would be phenomenal to have a url endpoint for multiple URLs to be passed in, which would then multithread the http requests before loading them into the transformer, going one at a time can be quite slow, obviously make_db is the better solution for bulk.

I tried uploading a .urls file to the upload_files and upload_files_api endpoints but it seemed to think they were all blobs (coming from the nodejs gradio client) and couldn't locate the blob on disk / had no file handler for a blob type

**Comment by pseudotensor** [comment]
Hi @raymondtri , url ingestion is parallel in BE.  For API you just need to pass list of urls.

**Comment by pseudotensor** [comment]
In addition, you could use the async gradio client to communicate the the server asyncronously and do anything in parallel that way too.

**Comment by pseudotensor** [comment]
Above commit allows passing a list from client and fixes it being stringified.  Test is added too.
