### ISSUE TITLE
 lmsys/fastchat-t5-3b-v1.0

### ISSUE THREAD

**Issue by hemantkumar0506** [h2oai/h2ogpt#650]
When I use lmsys/fastchat-t5-3b-v1.0 for inferencing through documents it doesn't generate responses at all and takes a lot of time to generate responses & gives the same answer for all the queries.
I just want to know why it's happening at all and how I can resolve it.

**Comment by pseudotensor** [comment]
I'd expect the prompt_type is wrong.         See https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#adding-models
