### ISSUE TITLE
Hmmm… can't reach this page

### ISSUE THREAD

**Issue by Julianbullmagic** [h2oai/h2ogpt#660]
When I run python generate.py --base_model='llama' --prompt_type=llama2 and I go to the link http://0.0.0.0:7860 the browser shows the message "Hmmm… can't reach this page. It looks like the webpage at http://0.0.0.0:7860/ might be having issues, or it may have moved permanently to a new web address.
ERR_ADDRESS_INVALID"

This is everything I can see in the terminal "Auto set langchain_mode=LLM.  Could use MyData instead.  To allow UserData to pull files from disk, set user_path or langchain_mode_paths, and ensure allow_upload_to_user_data=True
No GPUs detected
Using Model llama
Prep: persist_directory=db_dir_UserData exists, using
Starting get_model: llama
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Already have llama-2-7b-chat.ggmlv3.q8_0.bin from url https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q8_0.bin, delete file if invalid
llama.cpp: loading model from llama-2-7b-chat.ggmlv3.q8_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 7 (mostly Q8_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: mem required  = 8500.72 MB (+ 1026.00 MB per state)
llama_new_context_with_model: kv self size  = 1024.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
Model {'base_model': 'llama', 'tokenizer_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'llama2', 'prompt_dict': {'promptA': '', 'promptB': '', 'PreInstruct': '<s>[INST] ', 'PreInput': None, 'PreResponse': '[/INST]', 'terminate_response': ['[INST]', '</s>'], 'chat_sep': ' ', 'chat_turn_sep': ' </s>', 'humanstr': '[INST]', 'botstr': '[/INST]', 'generates_leading_space': False, 'system_prompt': None}}
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`."

**Comment by pseudotensor** [comment]
If you are on windows/mac, as in docs, need to go to http://localhost:7860 or http://127.0.0.1:7860
