### ISSUE TITLE
Quantized models of Falcon-40B or MPT-30B for CPU?

### ISSUE THREAD

**Issue by dlippold** [h2oai/h2ogpt#661]
Are there quantized chat or instruct models of Falcon-40B or MPT-30B for usage on CPU? I tried the one from https://huggingface.co/TheBloke/h2ogpt-gm-oasst1-en-2048-falcon-40b-v2-GGML but that seems to be not usable.

I would prefer to download the model file manually because I want to use h2oGPT in offline mode.

If there is such a model which parameter I have to use on the command line for `generate.py`?

**Comment by pseudotensor** [comment]
for CPU 40B model, even if quantized, will be quite heavy.  You'd get better results from llama2 7B or 13B that's GGLM on CPU, which runs relatively fast for 7B.

When you use --base_model='llama' or choose that in UI, llama2 7b is default GGML from TheBloke URL, so I think you don't need to change anything.  If you download that model, you can pass:

```
python generate.py --base_model='llama' --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=user_path --model_path_llama=llama-2-7b-chat.ggmlv3.q8_0.bin
``` 
but you should still get embedding model etc.  like mentioned here: https://github.com/h2oai/h2ogpt/blob/main/docs/README_offline.md#offline-mode

Or use for various tasks and then the ~/.cache/huggingface/hub folder will contain any HF files for HF models (including the embedding), but not GGML files that should be downloaded separately.

https://github.com/h2oai/h2ogpt/blob/main/docs/README_offline.md#offline-mode
