### ISSUE TITLE
user specified persist_directory path ?

### ISSUE THREAD

**Issue by jdurago-rebellion** [h2oai/h2ogpt#677]
I'm running h2ogpt in kubernetes, anytime a new h2ogpt pod is spun up the persist_directory gets created since it's hardcoded as a relative path. However this causes the vector db to get uploaded with the same set of documents that were already available. 

Is there a way to specify the persist_directory path through an env var or a parameter into generate.py?

**Comment by pseudotensor** [comment]
You can set env `H2OGPT_BASE_PATH` for the base path, or you can set pass `--langchain_mode_paths` with exact paths (absolute or relative).  Similar to in the UI or API, when adding a collection and you specify the path, it doesn't have to be relative, it can be absolute.

**Comment by jdurago-rebellion** [comment]
Hmm, I tried that and it's still recognizing the persist_directory as a new path. Does the `get_persist_directory` function need to get updated to pull in the `H2OGPT_BASE_PATH` env var? https://github.com/h2oai/h2ogpt/blob/776f36d9488e429a66875628a8bbf1d6c009e79b/src/gpt_langchain.py#L2127

**Comment by pseudotensor** [comment]
I recommend using langchain_mode_paths, did you try that?

**Comment by jdurago-rebellion** [comment]
Yeah, I've tried that, so here's what my deployment command roughly looks like:
```
export USER_PATH=/h2o/data/documents
export H2OGPT_BASE_PATH=/h2o/data
export LANGCHAIN_PATH=/h2o/data/db_dir_UserData

huggingface-cli login --token $HUGGING_FACE_HUB_TOKEN && python3.10 generate.py --base_model=meta-llama/Llama-2-13b-chat-hf --use_auth_token=True --load_8bit=True --user_path=$USER_PATH --langchain_mode=UserData --langchain_mode_paths="{'UserData':'$LANGCHAIN_PATH'}" --visible_h2ogpt_header=False --db_type=weaviate 
```

In the logs I'm still seeing that the persist_directory doesn't exist and all the existing documents are re-processed for the vectordb
```
Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: read).
Your token has been saved to /h2o/data/hf/misc/token
Login successful
Using Model meta-llama/llama-2-13b-chat-hf
Prep: persist_directory=db_dir_UserData does not exist, regenerating

  0%|          | 0/1 [00:00<?, ?it/s]
1/1 [00:00<00:00, 44.56it/s]

[00:00, ?it/s]
[00:00, ?it/s]
Loaded 1 new files as sources to add to UserData
Loaded 1 sources for potentially adding to UserData
```

**Comment by pseudotensor** [comment]
Ok checking

**Comment by pseudotensor** [comment]
I made changes in above commit (PR will be merged soon) so weaviate respects the persist_directory, so would then respect the base dir too.

**Comment by jdurago-rebellion** [comment]
🙌 Thanks!
