### ISSUE TITLE
How to evaluate the model.

### ISSUE THREAD

**Issue by Shantan243** [h2oai/h2ogpt#685]
Could you please share the CLI Command to Evaluate the model.

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/issues/440#issuecomment-1636312159
https://github.com/h2oai/h2ogpt/blob/9e0e35286d6ae022ae41e46659b3786e95a11f11/tests/test_eval.py#L19-L42

**Comment by Shantan243** [comment]
thanks!!
Appreciate if you can add a readme file about evaluation, in case it is not available already. Kindly ignore, otherwise.
