### ISSUE TITLE
Fine-tuning the model like LLama2-70B，thanks！

### ISSUE THREAD

**Issue by babytdream** [h2oai/h2ogpt#691]
Hello！There are few tutorials on fine-tuning this large model LLama2-70B. In, h2ogpt, what instruction should I use to fine tune it（like Lora）？
**GPU**：16 * A10（16 * 24G）
**Data**：10,000+ pieces of data，like：{**"instruction"**: "Summarize this Ethereum transaction.",**"input"**: ":'block_timestamp': '2023-08-15 04:18:47', 'from_address': '0xc16a101973403a71a1d42fdc12fed3c5f45e5bfe', 'from_address_label': 'topensdoc.eth', 'to_address': '0x0a791089acf48912a9cfde00e3a6afe9edbc3221',  .......",**"output"**: "summary text",}
Can you give some advice, thank you very much？If you have some idea，, what is the recommended setting for the **epoch** parameter for data of this order of magnitude?
If fine-tuning is successful, I will also disclose my steps in the community and indicate the use of your h2ogpt.Thanks！

**Comment by pseudotensor** [comment]
@arnocandel any advice as far ass 16 A10  training?  He has issues with inference too, but maybe need to effectively avoid P2P for 2 groups of 8 GPUs and use network distributed for the rest of communication?

**Comment by babytdream** [comment]
8 gpu is ok！But more gpu is helpful!
Do you use "torch.nn.DataParalle" or "torch.nn.parallel.DistributedDataParallel" in h2ogpt?
