### ISSUE TITLE
No GPUs detected problem

### ISSUE THREAD

**Issue by SilonovSA** [h2oai/h2ogpt#693]
Hello. I stack with the same problem as [sw016428](https://stackoverflow.com/questions/76783848/running-h2o-falcon-7b-powershell-7-says-no-gpu-detected). 
I do all step by step from [windows.md](https://github.com/h2oai/h2ogpt/blob/main/docs/README_WINDOWS.md) without any issues.
CUDA ver - 12.2;
bitsandbytes - 0.41.1;
nvidia-smi show my GPUs, but after running
`python generate.py --base_model='llama' --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=user_path`
I see [no GPUs detected]. 
I can go to http://127.0.0.1:7860/ and get chat responce, but it's very slowly.
Have you heard about this GPUs problem and maybe you know the solution?
Regards, Sergey

**Comment by pseudotensor** [comment]
Can you try the windows installer for GPU?

**Comment by SilonovSA** [comment]
Thank you very much for the quick response! 
Would you be so kind to attach a link to the installer? This one from the [h2ogpt site](https://h2o-release.s3.amazonaws.com/h2ogpt/h2oGPT_0.0.1.exe) shows the error `<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>h2ogpt/h2oGPT_0.0.1.exe</Key>
<RequestId>7021JT3D2W69CPSJ</RequestId>
<HostId>8jEepXlXMzGKbn25QJlzE1OkzaKrRwVbNr64UWxaNlIqOTs1bfphQ9IIgD2wcgUK/6Zf7oxSHCA=</HostId>
</Error>`

**Comment by pseudotensor** [comment]
Ah, your link is wrong, it's missing _cpu or _gpu in it.  The links on the main readme is correct.  I forgot to update the link in the readme for windows.

https://github.com/h2oai/h2ogpt#windows-1011-64-bit-with-full-document-qa-capability

**Comment by SilonovSA** [comment]
Thank you. Unfortunately, the error is still there.. Maybe it can't work on NVIDIA GeForce RTX 2070 ?
```
Auto set langchain_mode=LLM.  Could use MyData instead.  To allow UserData to pull files from disk, set user_path or langchain_mode_paths, and ensure allow_upload_to_user_data=True
No GPUs detected
Using Model llama
Prep: persist_directory=db_dir_UserData exists, using
```

**Comment by pseudotensor** [comment]
I don't see any reason it shouldn't work:

https://www.nvidia.com/en-us/geforce/graphics-cards/compare/?section=compare-20

![image](https://github.com/h2oai/h2ogpt/assets/2249614/1e6488eb-a74e-4ae7-ac91-087729c2618b)


has compute capability 7.5.

**Comment by pseudotensor** [comment]
@SilonovSA I'm confused, if you used windows installer, there's no error produced normally, can't see command line.  How did you run?

Outside of installer approach, just in conda env, did you confirm torch can see GPUs?  That is only thing, and has nothing directly to do with h2oGPT:
   ```python
   import torch
   print(torch.cuda.is_available())
   ```
    should print True.

**Comment by SilonovSA** [comment]
@pseudotensor thank you for your help! 
I found answer: torch in my cache was 2.1.0 version, so for unknown reasons installed 2.1.0 instead 2.0.1. Of course, `torch.cuda.is_available()` show `False`. I cleaned cache, reinstalled python and used [manual](https://github.com/h2oai/h2ogpt/blob/main/docs/README_WINDOWS.md) step by step without any problem. Now it's alive :)

**Comment by pseudotensor** [comment]
Great!
