### ISSUE TITLE
ssue with Document Loading in h2ogpt Chatbot

### ISSUE THREAD

**Issue by quartet** [h2oai/h2ogpt#695]
Description:

When running the h2ogpt chatbot with the generate.py script and specifying a user_path to load documents, the system recognizes new files but doesn't seem to add or process them as new sources. This has been consistently observed across multiple runs.

Environment:

OS: Ubuntu Ubuntu 20.04.6 LTS
Memory: 128 GB
Python Version: 3.10
GPU: Tesla V100-PCIE-16GB
VRAM Used: 6537 MB
h2ogpt Version: 0.1.0

Steps to Reproduce:

Activate the virtual environment: source h2ogptENV_8-17-2023/bin/activate.
Run the chatbot with the generate.py script and specific flags (detailed below).
Observe the output, specifically the section about loading new sources from user_path.

Script Configuration:
python generate.py \
--base_model='llama' \
--prompt_type='llama2' \
--user_path='source_documents' \
--temperature=0.8 \
--top_p=0.85 \
--top_k=50 \
--num_beams=2 \
--max_new_tokens=2000 \
--repetition_penalty=1.1 \
--early_stopping=True \
--max_time=180 \
--num_doc_chunks=3 \
--chunk_size=1024

Observed Output:
Loaded 52 new files as sources to add to UserData
Loaded 6033 sources for potentially adding to UserData
Existing db, potentially adding 6033 sources from user_path=source_documents
Found 0 new sources (0 have no hash in original source, so have to reprocess for migration to sources with hash)
Removing 0 duplicate files from db because ingesting those as new documents
Existing db, added 0 new sources from user_path=source_documents

Expected Behavior:

The newly recognized files should be added and processed as new sources in the system.

Additional Notes:

The documents in source_documents are mostly in PDF format.
No errors are thrown regarding file formats or content.
The ulimit settings were recently adjusted as per recommendations to ensure enough memory locks, but the issue persists.
Warnings related to joblib's multiprocessing (Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1) are observed but seem unrelated.
Please provide guidance on how to ensure that the new documents are loaded and processed correctly.

**Comment by pseudotensor** [comment]
If you run the same command repeatedly, the db will already have those sources in it, so at is says has 0 new sources (based upon name+hash).

I can't tell from your description of the issue what the actual problem is.  Is it that you can't query the documents or see them in UI?

If it's the latter, we by default don't load documents into UI as a list since it can be quite large at times (say entire wikipedia).  So if you want to see the sources list, you should click "show sources".  To see updated drop down of docs, you should click "Update UI".

**Comment by quartet** [comment]
Thank you for reaching out and seeking clarification. To address your inquiries:

Querying Documents: I am able to query the documents, but I've noticed that the querying process is significantly slower compared to just selecting the model. This has been affecting the overall efficiency of my interactions with the system.

Database Messages: I observed several messages related to the database during the startup, particularly:

"Prep: persist_directory=db_dir_UserData exists, user_path=source_documents passed, adding any changed or new documents."
"Did not generate db since no sources."
"Loaded 114 new files as sources to add to UserData."
"Loaded 87399 sources for potentially adding to UserData."
Given these messages, I'm uncertain about the current state of the sources in the database. Are the sources being correctly added and recognized? Could this be related to the slow querying issue I mentioned?

Could you kindly review these points and provide any insights or recommendations? Your expertise would be invaluable in resolving these concerns.

**Comment by quartet** [comment]
[startup-msg.txt](https://github.com/h2oai/h2ogpt/files/12385915/startup-msg.txt)
These are the startup messages.

**Comment by pseudotensor** [comment]
* Slowness: Can you tell me what is in run_chatbot.py.  I'm wondering if you are using top_k_docs=-1 etc.  A query will take longer the more chunks you use for top_k_docs.  Can you give a reproducible example with public documents and public command line so I can see what you mean?

* Messages: The current state of the database can be gathered by clicking show sources in the UI to see all the documents there.  In changes just today, you can review the full raw entries in the database in the document viewer tab.

There are many logged messages, and they aren't necessarily easy to understand.  Best to directly inspect if documents are loaded by using the UI.

**Comment by quartet** [comment]
Thanks for the updates. I used the information you provided to get around my issues.
