### ISSUE TITLE
add button to shutdown h2oGPT

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#697]

**Comment by weissalec05** [comment]
Lust press CTRL + C at the same time while in the terminal that will end the session

**Comment by pseudotensor** [comment]
For windows installer, one doesn't have direct access to the terminal.

**Comment by IVTore** [comment]
Guys, are you dealing with this? It is so annoying to shut it down from task manager.

**Comment by pseudotensor** [comment]
When new windows installer is built it'll have a shutdown button in system tab.
