### ISSUE TITLE
Web search option support [SERP API]

### ISSUE THREAD

**Issue by sayan1999** [h2oai/h2ogpt#699]
Hi

Do we have an web search option support in h2oGPT offline model?
If not is there a way to have a SERP API support using langchain.
I am new to this domain so I am not sure if there is an existing option to do this or it needs to designed, but I want to be able to force GPT to lookup using SERP for real time queries.

**Comment by pseudotensor** [comment]
https://ai.plainenglish.io/enhance-your-chatbots-web-search-capabilities-with-langchain-and-serpapi-c7c96265399f

https://github.com/meilisearch/meilisearch
