### ISSUE TITLE
pydantic.error_wrappers.ValidationError: 1 validation error for H2OLlamaCpp __root__   argument of type 'NoneType' is not iterable (type=type_error)

### ISSUE THREAD

**Issue by SurajPB** [h2oai/h2ogpt#700]
File "C:\ProgramData\Anaconda3\lib\site-packages\langchain\load\serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for H2OLlamaCpp
__root__
  argument of type 'NoneType' is not iterable (type=type_error)

**Comment by pseudotensor** [comment]
Hi, you must be not using a fresh env or have mixedup dependency versions.  If the installation steps are not clear, please use the windows installer.

**Comment by devloic** [comment]
Also try updating h2ogpt. It solved the same problem for me.

**Comment by pseudotensor** [comment]
Ya at the time we were using older langchain, and if you installed new langchain it would fail like that.  Now we are using new langchain, so even if you had wrong env it might still work.
