### ISSUE TITLE
7B HF model leads to GPU OOM

### ISSUE THREAD

**Issue by Hunanbean-Collective** [h2oai/h2ogpt#706]
Can this not self adjust VRAM allocation? This is the only local chat 'solution' that does this. this is just a 7B model..

![2023-08-20_02-51](https://github.com/h2oai/h2ogpt/assets/71809825/3ac458aa-51f8-48a8-87f5-5f294465c205)

**Comment by pseudotensor** [comment]
How did you start h2oGPT?  As the docs + button says, you can only unload-reload if you didn't pass --base_model  (i.e. message just under the error box).

So you should just start the app directly like `python generate.py` or at least without --base_model and choose once in app.

**Comment by Hunanbean-Collective** [comment]
h2oGPT\h2oGPT.launch.pyw launched with the launcher.

**Comment by pseudotensor** [comment]
FYI you are loading the base llama2 model, in case that was unintentional.  Perhaps you meant "h2oai/h2ogpt-4096-llama2-7b-chat".

The non-quantized 7B model takes 16-bits and will consume 14GB base + extra for inputs and cuda context.



```
(h2ogpt) jon@pseudotensor:~/h2ogpt$ nvidia-smi
Mon Aug 21 13:14:17 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090 Ti      On | 00000000:01:00.0 Off |                  Off |
|  0%   54C    P5               50W / 480W|  15445MiB / 24564MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 2080         On | 00000000:03:00.0 Off |                  N/A |
| 37%   47C    P8                6W / 215W|    499MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1546      G   /usr/lib/xorg/Xorg                          156MiB |
|    0   N/A  N/A      2412      G   /usr/lib/xorg/Xorg                          956MiB |
|    0   N/A  N/A      2545      G   /usr/bin/gnome-shell                         97MiB |
|    0   N/A  N/A      3236      G   /usr/bin/nvidia-settings                      0MiB |
|    0   N/A  N/A      5685      G   ...ures=SpareRendererForSitePerProcess       25MiB |
|    0   N/A  N/A     16632      G   ...4557871,15241731946435127899,262144      326MiB |
|    0   N/A  N/A    127451      C   ...niconda3/envs/h2ollm/bin/python3.10    13862MiB |
|    1   N/A  N/A      1546      G   /usr/lib/xorg/Xorg                            4MiB |
|    1   N/A  N/A      2412      G   /usr/lib/xorg/Xorg                            4MiB |
|    1   N/A  N/A    127451      C   ...niconda3/envs/h2ollm/bin/python3.10      486MiB |
+---------------------------------------------------------------------------------------+
(h2ogpt) jon@pseudotensor:~/h2ogpt$ 
```

You need to have at least 16GB for 16-bits.

I recommend using the GGML quantized model that is the 'llama' base model.

**Comment by Hunanbean-Collective** [comment]
Thank you for the information. In addition to the 12GB VRAM on the 3060, i also have 4GB VRAM on the 1050ti, but they do not seem to get allocated together. i will try the further quantized model, but i am usually able to run 7B GPTQ and even some 13B, but as you have mentioned the requirements seem a bit higher for this model. SO i suppose at this point the question is, should it allocate the VRAM from both cards, or will it never do that.   I understand that i may need to adjust things to make it use both, but i would not spend the time attempting to do so without confirmation that it is even capable of it. Thank you

p.s. at that point, i was randomly loading any models to see if i could get anything to work. I understand the previous assumptions perceived validity now

**Comment by pseudotensor** [comment]
GGML model will by default use both unless you restrict with CUDA_VISIBLE_DEVICES environment.  For HF models, you can pass `--use_gpu_id=False` to have it use all GPUs (or those specified by CUDA_VISIBLE_DEVICES).

**Comment by Hunanbean-Collective** [comment]
Thank you
