### ISSUE TITLE
Hello!Where to insert the code for context learning?

### ISSUE THREAD

**Issue by babytdream** [h2oai/h2ogpt#709]
I see this doc. If I use llama2, where should this text of this context learing **'[/INST] I am a pixie filled with fairy dust......'** be inserted, I can't find it, thanks！
![image](https://github.com/h2oai/h2ogpt/assets/74184102/7155f968-141c-4a13-99fb-c5ddae9eb5db)

      Can you give an example in this UI,I guss that I should insert text in **"""Input for Instruct prompt types"""**:
![image](https://github.com/h2oai/h2ogpt/assets/74184102/78424549-7508-40bc-928f-bbf40a8db580)

      But I don't want to have to type every time, I want to add directly in the code,where should I insert it?

**Comment by pseudotensor** [comment]
This one:
![image](https://github.com/h2oai/h2ogpt/assets/2249614/a82f5849-dc82-4737-9012-6f03b8c6e3a5)


I pushed changes to main so you don't have to change every time but can pass on command line when starting h2oGPT (or via env).


![image](https://github.com/h2oai/h2ogpt/assets/2249614/7924b87e-54e7-4559-a97b-30c6a739b3c9)
