### ISSUE TITLE
Windows installer issue, h2oGPT can't find GGML bin file after download

### ISSUE THREAD

**Issue by csocha** [h2oai/h2ogpt#710]
Hello,
  I have tried using both the CPU and GPU windows installer. It installs and I can get the page to come up fine. However, when I follow the steps to go to the _Models_ tab and select _Llama_, I click the Load Model button. After processing for a bit of time, I get this error every single time. 

1 validation error for H2OLlamaCpp __root__ Could not load Llama model from path: llama-2-7b-chat.ggmlv3.q8_0.bin. Received error [WinError -1073741795] Windows Error 0xc000001d (type=value_error)

I installed it in the default location. Anyone work through this error or have a suggestion? Thanks!

![image](https://github.com/h2oai/h2ogpt/assets/2837374/bef48183-46a8-46bf-91f6-59db8ce3227c)

**Comment by pseudotensor** [comment]
As in discord:

Yes, the error is consistent with it possibly downloading it but then not finding it.  Nominally the download goes to the directory where h2oGPT runs, and it loads it from same place.

A possible work-around is to provide the full absolute path when specifying the llama path in the UI, and predownload the file to that location.

You can also specify the path if you set an env for that application or a system-wide windows env.  Any gen.py:main() argument can be an env, e.g.:
```
h2ogpt_model_path_llama=<abs path>
```
inside windows system control in advanced for overall environment 

But probably in UI is easier.

**Comment by csocha** [comment]
thanks. I'll keep the conv in Discord so as not to duplicate here until we find a solution. Then I will update this with the solution for others.

**Comment by pseudotensor** [comment]
One should either specify the full path or set GGML_PATH environment variable
