### ISSUE TITLE
Nearly infinite document uploading

### ISSUE THREAD

**Issue by DuuuDik** [h2oai/h2ogpt#712]
I having troubles with understanding how much time is required for my machine to upload document for Q&A session.
One time i sit for nealy 2 hours waiting for an upload, in the end, interupt the process (photo below)
![photo_2023-08-21_11-03-38](https://github.com/h2oai/h2ogpt/assets/70808276/62a9a0ef-251b-43a1-9459-b88e676fffc3)

Other time right after that - it is read less than in a few seconds. And in these two cases I use the same file. 
I use GPU Nvidia Tesla P40. Document is 131k characters long in .txt format. 

Kind reader, can you help me with understanding how can i speed up upload process and improve answers quality based on given document

**Comment by MSZ-MGS** [comment]
That's almost equal to less than 60 pages.
I used to upload 600, 400, 800 pages per book.

It is not taking significant time, I never calculated that but it should be less than 5 minutes per book.
I can calculate if that is required.
But, you may take in consideration if the OCR is engaged or not.

**Comment by DuuuDik** [comment]
@MSZ-MGS, thank you for your reply! 
As I understand, OCR usually engaged in cases with text recognition when using pdf or image.
But why would OCR would be engaged, if we use raw .txt document, or it still can be the case?

**Comment by MSZ-MGS** [comment]
> @MSZ-MGS, thank you for your reply! As I understand, OCR usually engaged in cases with text recognition when using pdf or image. But why would OCR would be engaged, if we use raw .txt document, or it still can be the case?

Ok, so 8 seconds for 50 pages PDF file. No OCR.

In your case OCR is not applicable.

**Comment by pseudotensor** [comment]
@DuuuDik You can pass `--enable_pdf_ocr='off'` to avoid switching to OCR when a PDF has no content.

**Comment by DuuuDik** [comment]
@pseudotensor, mostly I use raw txt file for context. Probably this parameter won't solve my problem 😢

**Comment by pseudotensor** [comment]
Ok.  If text, the parser is trivial, just loads the file.  Then all embedding time.   You must have slow GPU or alot of docs.     Half of Wikipedia text takes 12 hours to embed on A6000.

**Comment by pseudotensor** [comment]
@DuuuDik I think your problem was fixed by https://github.com/h2oai/h2ogpt/pull/765
