### ISSUE TITLE
Facing Error While trying to run 40B Falcon Model. ("If `eos_token_id` is defined, make sure that `pad_token_id` is defined.")")

### ISSUE THREAD

**Issue by umang93769** [h2oai/h2ogpt#713]
raise ValueError("If `eos_token_id` is defined, make sure that `pad_token_id` is defined.")
ValueError: If `eos_token_id` is defined, make sure that `pad_token_id` is defined.

The model was working perfectly on Friday. But When I am running the model again it's giving us the above error while running the command 

python3 generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-40b-v2 --score_model=None --prompt_type=human_bot --load_8bit=True --use_gpu_id=False --share=False --cli=True

**Comment by pseudotensor** [comment]
@umang93769 Yes sorry, there was a temporary bug fixed this morning

2408d405e10b99cdfb1d16d2f223aeb24ea603a6

**Comment by Shantan243** [comment]
even for this model, we have eos and pad token issues persists..

CUDA_VISIBLE_DEVICES=0,1,2,4,5 python generate.py --base_model=h2oai/h2ogpt-oasst1-falcon-40b --prompt_type='human_bot' --cli=True --score_model=None --langchain_mode='UserData' --use_gpu_id=False


  **raise ValueError("If `eos_token_id` is defined, make sure that `pad_token_id` is defined.")**

**Comment by pseudotensor** [comment]
I think you must still have old hash.  E.g. this works fine for me:
```
--base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v2 --prompt_type='human_bot' --cli=True --score_model=None --langchain_mode='UserData' --use_gpu_id=False --answer_with_sources=False
```

**Comment by Shantan243** [comment]
hello author,

I think this is persistance in 40Bn models. I have checked for base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-40b-v2

i still see the issue:

('If `eos_token_id` is defined, make sure that `pad_token_id` is defined.')

**Comment by pseudotensor** [comment]
Hi, what if you run the command I gave?      Does it work or  not?

**Comment by Shantan243** [comment]
Hi Author,

Yes, have tried above model/command as well. Error still persists.

I had deleted previous instances - free'ed up space and waited for 12 Hrs..

Here it is: CUDA_VISIBLE_DEVICES=0,1,2,4,5 python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v2 --prompt_type='human_bot' --cli=True --score_model=None --langchain_mode='UserData' --use_gpu_id=False --answer_with_sources=False

File "/opt/conda/envs/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 2378, in greedy_search
    raise ValueError("If `eos_token_id` is defined, make sure that `pad_token_id` is defined.")
ValueError: If `eos_token_id` is defined, make sure that `pad_token_id` is defined.

**Comment by pseudotensor** [comment]
If this fails too: https://github.com/h2oai/h2ogpt/issues/713#issuecomment-1687688131

then I'm currently at a loss as to what is wrong.  It has to be an older hash.

What if you do:

```
git log|head -20
```
what does it say?

**Comment by Shantan243** [comment]
Hi Author,

I had done git pull and restarted the cmd again for 7b-v2 falcon model,
it's started working now.

I haven't checked above comments yet..
