### ISSUE TITLE
Falcon models create empty output

### ISSUE THREAD

**Issue by arnocandel** [h2oai/h2ogpt#722]
858664b4f3e6e1343da95b5be77525ba01ea903d is the first bad commit (for gpt.h2o.ai, falcon.h2o.ai was working fine still).

**Comment by arnocandel** [comment]
![image_720](https://github.com/h2oai/h2ogpt/assets/6147661/c3a43b79-f6a1-44e0-92c2-81d59ba8b04e)

**Comment by pseudotensor** [comment]
2ea50a93d2530287f689f92494e487a4913909d5
