### ISSUE TITLE
Hello！How to see the inference speed of the model in UI?

### ISSUE THREAD

**Issue by yanmengxiang123456899** [h2oai/h2ogpt#724]
Like:  xxx tokens / sec.

**Comment by pseudotensor** [comment]
We currently only save that in the history.json when using `--save_dir=foo` for some folder foo.  The code could be modified to show in UI (we used to do for summarize), but now for summarize it's under `verbose` flag only: https://github.com/h2oai/h2ogpt/blob/858664b4f3e6e1343da95b5be77525ba01ea903d/src/gpt_langchain.py#L3169

I don't plan to add to UI myself anytime soon.

**Comment by yanmengxiang123456899** [comment]
Thanks!
