### ISSUE TITLE
Installer got detected by TrendMicro with trojan.

### ISSUE THREAD

**Issue by phamtronglam** [h2oai/h2ogpt#735]
Hi,

Today when I started downloading the GPU installer, my antivirus jumped out and it said it detected a trojan inside the file that was being downloaded.
![image](https://github.com/h2oai/h2ogpt/assets/70121060/ccb7a513-7567-412b-8c5d-21c1e7503c85)

Do you know why it happened? Is there a way to address this?

Lam

**Comment by pseudotensor** [comment]
Either false positive, nsist package has trojan in it, or some package we use has trojan in it.  Highly likely false positive.

**Comment by phamtronglam** [comment]
Thank you for your reply!
