### ISSUE TITLE
Collections Duplication / Shared while set to personal

### ISSUE THREAD

**Issue by NashLexul** [h2oai/h2ogpt#739]
I've noticed that the personal collections are being duplicated to other logged in users
![image](https://github.com/h2oai/h2ogpt/assets/142926957/6781c370-0755-47c6-b56a-18419fd401c1)
This account should only be seeing "test", but I am able to see the collections of other users, while also being able to upload documents to the collections and view all the sources with in the collection despite them all being set to personal.
![image](https://github.com/h2oai/h2ogpt/assets/142926957/039ea4de-5b48-4abe-9bd6-5ea4d8b6b319)

There also appears to be some sort of duplication going on, I'm signed into a user, but these new randomly generated ones keep appearing containing a random collection from other users.
![image](https://github.com/h2oai/h2ogpt/assets/142926957/ffd57da9-49f6-4037-9b8d-f724c9d59c47)

I might just be misunderstanding how this last part works, but when I purge the test collection, it will come back when I log back in (I cleared my cache just to be sure).
![image](https://github.com/h2oai/h2ogpt/assets/142926957/306cf00b-e99d-474f-8620-fa731edad60c)

**Comment by pseudotensor** [comment]
Thanks!

I see that two users can see same name of collection, while directory for that user is specific.

I checked that one cannot see the documents from the other user.

Working on fix for the seeing of collection names and I'll look into the directories  you show.

Users who don't login will show up in db_non_users/db_dir_*  .  Perhaps you have older h2oGPT before such changes?  Before a user logs in, they will create one of those scratch directories.  I'll confirm behavior.
