### ISSUE TITLE
h2oGPT installed on Orange Pi 5 16Gb RAM operating system Armbian  : Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by bluciano212** [h2oai/h2ogpt#742]
Hi ! I have installed h2oGPT Linux (CPU) with full document Q/A capability on Orange Pi 5 16 Gb RAM with Armbian 23.08.0-trunk jammy. To launch h2oGPT I write : ulimit -l unlimited && python3 generate.py --base_model='llama' --model_path_llama=llama-2-7b-chat.ggmlv3.q4_1.bin --max_seq_len=2048 --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=/home/lucio/book

and after I open chrome at  http://0.0.0.0:7860
with the first question in chat it works perfectly !
at the second question I always receive the following :

Number of requested results 1000 is greater than number of elements in index 882, updating n_results = 882
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 16781920, available 10485760)
Fatal Python error: Segmentation fault

Please note that at the start of Armbian RAM use is 800 Mb of 16Gb,
after start of h2oGPT RAM usage rise to 5,6 Gb
Following the output at the launch of python3 generate.py 

No GPUs detected
Using Model llama
Prep: persist_directory=db_dir_UserData exists, user_path=/home/lucio/book passed, adding any changed or new documents
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData
Starting get_model: llama 
llama.cpp: loading model from llama-2-7b-chat.ggmlv3.q4_1.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 1.0e-06
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 3 (mostly Q4_1)
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: mem required  = 4415.35 MB (+ 1024.00 MB per state)
llama_new_context_with_model: kv self size  = 1024.00 MB
AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 0 | VSX = 0 | 
Model {'base_model': 'llama', 'tokenizer_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'llama2', 'prompt_dict': {'promptA': '', 'promptB': '', 'PreInstruct': '<s>[INST] ', 'PreInput': None, 'PreResponse': '[/INST]', 'terminate_response': ['[INST]', '</s>'], 'chat_sep': ' ', 'chat_turn_sep': ' </s>', 'humanstr': '[INST]', 'botstr': '[/INST]', 'generates_leading_space': False, 'system_prompt': None}}
Running on local URL:  http://0.0.0.0:7860

Any suggestion to solve the Fatal Python error: Segmentation fault at second question?

Moreover the Orange Pi 5 Rockchip RK3588S has NPU 6 Tops AI computing power support INT4/INT8/INT16 hybrid computing, anyone knows how to install python dependencies for NPU in h2oGPT

**Comment by pseudotensor** [comment]
Same as others have reported for: `ggml_new_tensor_impl: not enough space in the context's memory pool (needed 16781920, available 10485760)`  .  I'll close this issue, and wait for solution from llama.cpp repo, since we have another issue for this.
