### ISSUE TITLE
Bad output during Q&A on document 

### ISSUE THREAD

**Issue by DuuuDik** [h2oai/h2ogpt#745]
I having trouble with Q\A process in h2ogpt. After downloading my document, no matter what I ask, it prints out the same massage: 
It's not important what massage say, the important part is that it starts with question, and keeps printing it out with extra words: you may see that the sentense is getting longer in each row

```
[QUOTE=Dark_Soul;105437]Напиши мне основную суть политики закупок Теле2.
Почему они не покупают продукцию российских производителей?
Почему они покупают продукцию иностранных производителей?
Почему они покупают продукцию иностранных производителей, когда есть российские аналоги?
Почему они покупают продукцию иностранных производителей, когда есть российские аналоги, которые лучше?
Почему они покупают продукцию иностранных производителей, когда есть российские аналоги, которые лучше, дешевле и доступнее?
Почему они покупают продукцию иностранных производителей, когда есть российские аналоги, которые лучше, дешевле и доступнее, а также имеют более высокий рейтинг?
Почему они покупают продукцию иностранных производителей, когда есть российские аналоги, которые лучше, дешевле и доступнее, а также имеют более высокий рейтинг, но имеют более низкие технические характеристики?
Почему они покупают продукцию иностранных производителей, когда есть российские аналоги, которые лучше, дешевле и доступнее, а также имеют более высокий рейтинг, но имеют более низкие технические характеристики, но имеют более низкие цены?
```

Which doesn't included in document, probably a hallucination. 
The code I use:
```
python generate.py --base_model=h2oai/h2ogpt-4096-llama2-13b
  --prompt_type=llama2
  --score_model=None
  --use_gpu_id=False
  --langchain_mode=MyData
  --user_path=user_path
```

Bad output continues even after i reload model and tring to ask general question with LLM as source
Does h2ogpt has a feature of 'reseting memory'?  Simple reloading didn't help.
Sorry if it is already a feature, I am new in llm thing in general and struggling with adaptation

**Comment by DuuuDik** [comment]
Tested another model - getting familliar bad output. On another question asked I am getting:
```
TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<
```

**Comment by DuuuDik** [comment]
Probably the thing I am looking for is embeddings that are generated on documents I uploaded using UI. Can you tell where can i find them or how can i reset them?

**Comment by pseudotensor** [comment]
I'd guess that the LLM is failing to handle the complexity of the documents in the context.  Maybe try 13B llama-2, including non-quantized.  Capacity for document QA scales with LLM capability.

**Comment by pseudotensor** [comment]
Can you try your questions on https://gpt.h2o.ai and see what the 13B llama-2 gets there?  That's same one.  Our command for that is:

```
export MODEL=h2oai/h2ogpt-4096-llama2-13b-chat
export HF_PORT=3520
export GRADIO_SERVER_PORT=3521
export MODEL_NAME=`echo $MODEL | sed 's@/@_@g'`
export CUDA_VISIBLE_DEVICES=1

docker run -d --gpus all --shm-size 1g -e CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES -e HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN -e TRANSFORMERS_CACHE="/.cache/" -p $HF_PORT:80 -v $HOME/.cache:/.cache/ -v $HOME/.cache/huggingface/hub/:/data ghcr.io/huggingface/text-generation-inference:0.9.3 --model-id $MODEL --max-input-length 4096 --max-total-tokens 8192 --max-stop-sequences 6 --sharded false &>> logs.$MODEL_NAME.inference_server.txt

python generate.py --inference_server=http://127.0.0.1:$HF_PORT --base_model=$MODEL --height=500 --score_model=None --max_max_new_tokens=2048 --max_new_tokens=512 --save_dir=save.$MODEL_NAME &>> logs.$MODEL_NAME.gradio_chat.txt &

echo "done llama2 13b"
```

**Comment by DuuuDik** [comment]
@pseudotensor, thank you for your reply! I tried out your parameters and it seems that `--max_max_new_tokerns` and `--max_new_tokens` have solved my problem. 
And [gpt.h2o.ai/ ](https://gpt.h2o.ai/ ) also works flawlessly.
