### ISSUE TITLE
Differences in Answer both Length/Max token wise and quality wise between Falcon 40bn downloaded model and Falcon 40bn on https://gpt.h20.ai.

### ISSUE THREAD

**Issue by Shantan243** [h2oai/h2ogpt#746]
Hi Author,

I have found lot of differences between the outputs of Falcon 40bn model between Downloaded and executed on CLI and the one on gpt.h20.ai API/UI. can i know the reasons please?

for downloaded and executed model, i have used following command: "CUDA_VISIBLE_DEVICES=0,1,2,3,4,5 python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-40b-v2 --langchain_mode='MyData' --cli=True --prompt_type='human_bot' --use_gpu_id=False"

I have tested the model on common sense reasoning..

My instruction was: ""the trophy would not fit in the brown suitcase because it was too small. what was too small?". Orginal Answer is The Suitcase.
but the model predicted it as " the trophy was too small to fit in the brown suitcase.

Also, the answer predicted by same 40bn falcon model on gpt.h20.ai was "the suitcase".

So, why is this happening..

I have many more such examples, where downloaded model is not producing accurate answers while the same model on gpt.h20.ai ui produces the expected answer.

Would like to know the detailed reasons from you. Also, if there is issue on command line. kindly correct the same..
Please consider it as important and urgent one..

**Comment by Shantan243** [comment]
Requesting Authors to lookinto above issue/concern. Looking forward to hear from you!

**Comment by pseudotensor** [comment]
The commands we use on gpt.h2o.ai is:

```
export MODEL=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-40b-v2
export HF_PORT=6666
export GRADIO_SERVER_PORT=6667
export MODEL_NAME=`echo $MODEL | sed 's@/@_@g'`
export CUDA_VISIBLE_DEVICES=2,3
export MODEL_LOCK=$MODEL_LOCK"{'inference_server':'http://127.0.0.1:$HF_PORT', 'base_model':'$MODEL'},"

docker run -d --gpus all --shm-size 1g -e CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES -e HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN -e TRANSFORMERS_CACHE="/.cache/" -p $HF_PORT:80 -v $HOME/.cache:/.cache/ -v $HOME/.cache/huggingface/hub/:/data ghcr.io/huggingface/text-generation-inference:0.9.3 --model-id $MODEL --max-input-length 2048 --max-total-tokens 4096 --max-stop-sequences 6 --sharded true --num-shard 2 &>> logs.$MODEL_NAME.inference_server.txt
sleep 90
python generate.py --inference_server=http://127.0.0.1:$HF_PORT --base_model=$MODEL --height=500 --score_model=None --max_max_new_tokens=2048 --max_new_tokens=512 --save_dir=save.$MODEL_NAME --heap_app_id=1090178399 &>> logs.$MODEL_NAME.gradio_chat.txt &
ngrok http --domain=falcon.h2o.ai $GRADIO_SERVER_PORT &
echo "done falcon 40b"
```

**Comment by pseudotensor** [comment]
But in detail, variances can occur.  TGI server is not perfectly reproducible etc.
