### ISSUE TITLE
Windows Installer version loading a GPTQ 4bit llama2 model

### ISSUE THREAD

**Issue by a3nima** [h2oai/h2ogpt#749]
flozi00/Llama-2-13b-german-assistant-v6-4bit-autogptq

How do I load it ? I got it to be downloaded, but then the "processing" counter just goes on and on.. 

Do I need specific settings ? I noticed I had to check safetensors for it to be downloaded.

Also my RAM gets being nearly fully loaded but no VRAM usage, when trying to load the downloaded model.

when trying to load with not-windows installer (github version of h2ogpt): 

` e:\TEXT-AI\venv\h2ogpt\lib\site-packages\auto_gptq\modeling\_base.py:714 in from_quantized       │
│                                                                                                  │
│   711 │   │   │   │   │   break                                                                  │
│   712 │   │                                                                                      │
│   713 │   │   if resolved_archive_file is None: # Could not find a model file to use             │
│ ❱ 714 │   │   │   raise FileNotFoundError(f"Could not find model in {model_name_or_path}")       │
│   715 │   │                                                                                      │
│   716 │   │   model_save_name = resolved_archive_file                                            │
│   717                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: Could not find model in flozi00/Llama-2-13b-german-assistant-v6-4bit-autogptq`

`python generate.py --base_model=flozi00/Llama-2-13b-german-assistant-v6-4bit-autogptq --score_model=None --load_gptq=gptq_model-4bit-128g --use_safetensors=True --prompt_type=llama2 --langchain_mode=MyData --score_model=None --save_dir='7bgptqrope4` --rope_scaling="{'type':'dynamic', 'factor':4}" --max_max_new_tokens=15000 --max_time=12000 --share=False --gradio_offline_level=1`

with `python generate.py --base_model=flozi00/Llama-2-13b-german-assistant-v6-4bit-autogptq --load_gptq="gptq_model-4bit-128g" --use_safetensors=True --prompt_type=instruct --save_dir='save' --load_exllama=True  --rope_scaling="{'alpha_value':4}" --langchain_mode=MyData`

update: I got it to start, with the github version, but only when (for whatever reason) my TRANSFORMERS_CACHE (set in systemvariables AND in front of the starting bat was ignored and the .cache (on c users ...) was being used for downloading and running the model.

TIA!

**Comment by pseudotensor** [comment]
You should use "new" way like TheBloke uses, by passing `--load_gptq=model` instead, because that repo like TheBloke moved on to supporting transformers way.
