### ISSUE TITLE
Plugins ?

### ISSUE THREAD

**Issue by X3Coyote** [h2oai/h2ogpt#754]
Hello,
Not sure if this is the right place for this, but is it possible to build add-ons to this project?

Like for example if I want to add Wolfram alpha or one of my own api's to this project.

Where would I start?

**Comment by pseudotensor** [comment]
You can see a self-contained way to add a new parser: https://github.com/h2oai/h2ogpt/pull/752

As for agents, this is WIP and not easy to add at moment, but is planned.
