### ISSUE TITLE
Can't get llama-2 to use gpu on sagemaker

### ISSUE THREAD

**Issue by phwang4** [h2oai/h2ogpt#757]
I'm trying to setup llama-2 to run on a notebook instance but I can't get it to use the gpu. Here are the steps I'm running:

```
conda create -n h2ogpt -y
source ~/anaconda3/etc/profile.d/conda.sh
conda activate h2ogpt
conda install python=3.10 -c conda-forge -y
```

```
cd Sagemaker/h2ogpt
pip uninstall -y pandoc pypandoc pypandoc-binary
```

##### GPU only:
`pip install -r requirements.txt --extra-index https://download.pytorch.org/whl/cu117`

##### Required for Doc Q/A: LangChain:
`pip install -r reqs_optional/requirements_optional_langchain.txt`

```
conda install cudatoolkit-dev -c conda-forge -y
export CUDA_HOME=$CONDA_PREFIX
```

```
pip uninstall -y llama-cpp-python llama-cpp-python-cuda
pip install https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.1.73+cu117-cp310-cp310-linux_x86_64.whl
```

I run python generate.py --base_model='llama' --prompt_type=llama2 --cli=True --score_model=None --langchain_mode=UserData --user_path=user_path --temperature=0 --answer_with_sources=False
which will automatically download llama-2-7b by default. 

At this point I get the error: 

>   Could not load Llama model from path: llama-2-7b-chat.ggmlv3.q8_0.bin. Received error Failed to load shared library '/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/llama_cpp_cuda/libllama.so': /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/llama_cpp_cuda/libllama.so) (type=value_error)

  
 So next I tried to compile llama-cpp-python with CUDA support instead
 ```
 pip uninstall -y llama-cpp-python llama-cpp-python-cuda
 export LLAMA_CUBLAS=1
 export CMAKE_ARGS=-DLLAMA_CUBLAS=on
 export FORCE_CMAKE=1
 CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python==0.1.73 --no-cache-dir --verbose
```
However this gives me the error

> ERROR: Failed building wheel for llama-cpp-python
> Failed to build llama-cpp-python
> ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

And when I try to run python generate.py again it says 

> ModuleNotFoundError: Could not import llama-cpp-python library. Please install the llama-cpp-python library to use this embedding model: pip install llama-cpp-python

So I run pip install llama-cpp-python which lets me actually run the model for the first time but there's no message saying that it found a gpu nor a message saying how many layers it offloaded like in https://github.com/h2oai/h2ogpt/blob/main/docs/README_GPU.md#exllama

**Comment by pseudotensor** [comment]
Ya, the compiling of llama_cpp_python is not super trivial, and the binary wheels have specific requirements that may not be met on diverse systems.

The only solution is to try to resolve the compile issue on that specific system.  Your error fragment didn't show the actual error.  You can share and I can try to help.

**Comment by phwang4** [comment]
The error after running CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python==0.1.73 --no-cache-dir --verbose

```
  [4/8] Building C object vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o
  ninja: build stopped: subcommand failed.
  Traceback (most recent call last):
    File "/tmp/pip-build-env-v1z_is5y/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
      cmkr.make(make_args, install_target=cmake_install_target, env=env)
    File "/tmp/pip-build-env-v1z_is5y/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 697, in make
      self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
    File "/tmp/pip-build-env-v1z_is5y/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 742, in make_impl
      raise SKBuildError(msg)

  An error occurred while building with CMake.
    Command:
      /tmp/pip-build-env-v1z_is5y/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
    Install target:
      install
    Source directory:
      /tmp/pip-install-_j2949n2/llama-cpp-python_6347bc7cb4ca4b618c3632ca038b47cf
    Working directory:
      /tmp/pip-install-_j2949n2/llama-cpp-python_6347bc7cb4ca4b618c3632ca038b47cf/_skbuild/linux-x86_64-3.10/cmake-build
  Please check the install target is valid and see CMake's output for more information.

  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/ec2-user/anaconda3/envs/h2ogpt/bin/python3.10 /home/ec2-user/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpluibla5c
  cwd: /tmp/pip-install-_j2949n2/llama-cpp-python_6347bc7cb4ca4b618c3632ca038b47cf
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```

**Comment by pseudotensor** [comment]
Unfortunately, still don't see an actual specific error here, maybe it was above that block?  E.g. `ninja: build stopped: subcommand failed.` is generic.

But at least you know it's probably ninja related.  But it's probably going to be something you or someone figures out how to get running, or use different OS type on sagemaker, etc.  Hopefully someone can contribute to this.

**Comment by pseudotensor** [comment]
sagemaker is added explicitly as llm type now
