### ISSUE TITLE
Please clarify installation instructions for Linux and Windows

### ISSUE THREAD

**Issue by Waxwood** [h2oai/h2ogpt#760]
Hi, 
First, thank you for creating this outstanding open source tool! I am certain that many thousands of users are grateful!

My request- Please clarify installation instructions for Linux and Windows. I have tried using the instructions on Github to install the standalone h2oGPT on my Windows 10 and Linux computers but have not been successful in either case. 

- The Linux instructions are not clear enough for less-experienced users, but could easily be improved by providing clearer, step-by-step instructions. 

- While the Windows installer is indeed convenient, the instructions on Github that appear under the One-Click installers are really quite confusing and obscure. 

In Windows, when I click on the desktop shortcut, the interface opens in a browser window. The process of installing a model is completely unclear. It seems users should choose the base model Llama, but after selecting it from the list, how do we download it? There does not appear to be any "download" button. 

If anyone can help with this, I and many others would be appreciative. :)

**Comment by JSW888** [comment]
The UI is confusing, but there's a button on the top right to actually download the selected model. It will then show "processing" in the bottom right while downloading. You can also confirm it is actually downloading by monitoring disk usage and/or free space on the the drive.

**Comment by Waxwood** [comment]
Thank you JSW888! 

I will try that when I get back to my Windows machine. 

In the meantime, I have no idea how to start h2oGTP on my Linux computer. 
I have looked into the /h2oGTP folder where all of the related files exist, but I have no idea how to start the program so that it will open in my browser.

Can anyone please provide advice on how to start h2oGTP in Linux?

**Comment by ryanchesler** [comment]
A lot of the instructions are here for installing and running on linux https://github.com/h2oai/h2ogpt/blob/main/docs/README_LINUX.md

In general if you have been able to get python and the right dependencies installed then you will want to run something like this to download a model:
`wget https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q8_0.bin`

and then something like the following in order to run the code:
`python generate.py --base_model='llama' --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=user_path`

**Comment by pseudotensor** [comment]
@Waxwood Thanks for feedback.  I'll try to improve the models page some.  On the docs, I feel like I've improved it so many times I'm blind to what could be done.  If you have specific suggestions I can try.

**Comment by pseudotensor** [comment]
Hopefully a bit better:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/c69b956f-7f68-4e2c-8025-4e0d4e056090)

**Comment by Waxwood** [comment]
Thank you! That interface is a bit better. 
I found it confusing that the yellow text boxes in the MODELS tab are buttons that can be pressed, but in DOCUMENT SELECTION they are for explanation only. 

The tool ran in Linux after running 
```
wget https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q8_0.bin
python generate.py --base_model='llama' --prompt_type=llama2
```
in Terminal. But after I shutdown the system, I was unable to start h2oGPT. How can I restart it?

Thank you again for your work on this. Once these issues are resolved and users can easily install it, it will be outstanding.

**Comment by pseudotensor** [comment]
Ya good point.  Gradio uses same color for both.  @fazpu can we improve so clickable things are always different in some way than just "labels" by changing one or the other somehow?

**Comment by pseudotensor** [comment]
Can you explain " But after I shutdown the system, I was unable to start h2oGPT. How can I restart it?" more?  Do you mean after putting computer to sleep?  I'm not sure about what would be causing problems there.

**Comment by Waxwood** [comment]
> 

I finally figured out how to restart h2oGPT in Linux. Please consider adding these instructions in the explanation so that newcomers can better-understand how to run the software. 1) Navigate to the h2oGPT folder. 2) In the folder, open TERMINAL; 3) paste this command "python generate.py --base_model='llama' --prompt_type=llama2"  This will start h2oGPT. 4) IN your browser, go to http://127.0.0.1:7860/.  5), Once the h2oGPT interface opens, click on the MODELS tab. Curently, you should be using the default Llama model. You can choose other models by selecting it from a dropdown list, then clicking on "CONFIRM" button to the right. 

These types of clear, step-by-step instructions will help a lot of people. Thank you for considering this :)

**Also, one more question.** On my Windows computer, I have successfully installed the software, but cannot download any of the models. When I try to download them, an error window pops up saying: 
`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))"), '(Request ID: 665a05cd-34f5-4a77-90c9-3cee85c96`
![image](https://github.com/h2oai/h2ogpt/assets/26566207/515d29cc-9dae-418c-b368-833e3b396f89)

How can this be resolved? Thank you again!

**Comment by pseudotensor** [comment]
That seems to be an issue with HF or your setup.  E.g. for mac some have had to do https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error/42334357#42334357

**Comment by darshisam** [comment]
Hi 
can we manually download model from Huggingface site and place model in a directory after executing Windows installer. Model sizes are big and it is convenient to download it direct from HF site. In which directory we need to place model bin file?

**Comment by pseudotensor** [comment]
Yes, you can follow this for a particular model: 

https://github.com/h2oai/h2ogpt/blob/main/docs/README_offline.md#hard-way

Then in UI instead of providing the HuggingFace model "link" for the name of the model (e.g. `h2oai/h2ogpt-oasst1-512-12b`) you instead provide the full path to the model directory that contains the model files.
