### ISSUE TITLE
Download models in C:\users\.chace  How can i change that?

### ISSUE THREAD

**Issue by Reno0vacio** [h2oai/h2ogpt#761]

**Comment by pseudotensor** [comment]
GGML_PATH env

https://github.com/h2oai/h2ogpt/commit/ada9c5be5284bb2916dfb686b1b76047b6caab32

for GGLM/GPT4ALL.

Set envs for transformers from HF for other models.

https://stackoverflow.com/questions/63312859/how-to-change-huggingface-transformers-default-cache-directory
