### ISSUE TITLE
Support XML as langchain data type

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#763]
Hi,
It would be nice if I can use xml files for Q&A.
Thanks

**Comment by ryanchesler** [comment]
Added support to upload xml files. This is what you meant, correct?
https://github.com/h2oai/h2ogpt/pull/767

**Comment by slavag** [comment]
@slavag Correct. thanks

**Comment by pseudotensor** [comment]
![image](https://github.com/h2oai/h2ogpt/assets/2249614/934817cf-3781-46fc-ace3-1802bbae8f4b)

![image](https://github.com/h2oai/h2ogpt/assets/2249614/7ceece77-79bf-469c-95a1-64ed7dc2a147)
