### ISSUE TITLE
can I use api to access h2ogpt？

### ISSUE THREAD

**Issue by yanmengxiang1** [h2oai/h2ogpt#768]
If my Cloud Server's ip is `11.18.219.134`,the open port is` 7860`. can I use `https://11.18.219.134:7860` to access h2ogpt？Thanks！

**Comment by the-consultant-git** [comment]
Hi, @yanmengxiang1 , Can you try the following steps, and give it a try ? 

[https://github.com/h2oai/h2ogpt/blob/main/client/README.md](https://github.com/h2oai/h2ogpt/blob/main/client/README.md)

**Comment by yanmengxiang1** [comment]
@the-consultant-git 
Thanks. I can run it.
If I already have running h2oGPT server, how do I use my own words to input the model?
I want to use a linux command to give an output on the command line. what should I do?
