### ISSUE TITLE
Local document parsing - returns less rows

### ISSUE THREAD

**Issue by the-consultant-git** [h2oai/h2ogpt#776]
Hello there,

I was trying to build a local database using the following commands : 
```
python src/make_db.py --user_path=user_path 
``` 

The database (directory) have only 1 csv file and that has 250 rows. 

Then I started the local server using the bellow command : 
```
python generate.py --base_model='llama' --prompt_type=llama2
``` 

On `chat ui` I typed : "How many records are there in the uploaded csv file." 
`Response :` It gave only 3 records from the file. But the `source` was correct.

Can anyone please tell me , what am I doing wrong. Or how to extract all the data from all the files in the directory to database locally.  Do I need to make any server upgradation ?

**Comment by pseudotensor** [comment]
Hi.  The CSV/JSON approach at moment is just vector search, no agents (planned soon).  So it just looks for something similar in csv as in query and gives that to LLM.  It's not currently like pandas-ai.

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/issues/356
