### ISSUE TITLE
Unable to process uploaded image

### ISSUE THREAD

**Issue by kwseow** [h2oai/h2ogpt#777]
Hi there,
I uploaded an image.  No error message whatsoever.  However, the image did not show up in "Sources:" under "document selection".  I tested with the same image on gpt.h2o.ai.  I can see that image to text was performed and show up in "sources" under "document selection".  Am I missing something? 

Tested with both python sources and windows exe.

Thanks

**Comment by kwseow** [comment]
Many thanks for getting back.

(1) I used the same image on my local installation and gpt.h2o.ai.  So it is not a case of no parse able content imo.
(2) I tried with both WIndows installer and installation from the main head.  Looks like I may need to do some digging.

Noted your comment on blip.  I am new to this project, a quick question, is blip the model used in this project for image captioning?  Any advice will be helpful for me to quickly start :)

**Comment by pseudotensor** [comment]
Ya blip/bip2 for caption, but OCR/DocTR options for OCR of text in image.
