### ISSUE TITLE
pix2struct for better captions

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#782]
https://huggingface.co/docs/transformers/main/en/model_doc/pix2struct#transformers.Pix2StructTextModel
https://www.kaggle.com/code/alejopaullier/benetech-matcha-train-0-74
https://github.com/huggingface/notebooks/blob/main/examples/image_captioning_pix2struct.ipynb

**Comment by ryanchesler** [comment]
https://github.com/h2oai/h2ogpt/pull/792

added in pix2struct. Right now defaulting to textcaps-base, but there are many options that have been trained with different purposes. Can allow users to switch out which one they want if there is interest
<img width="1093" alt="Screen Shot 2023-09-01 at 1 03 25 PM" src="https://github.com/h2oai/h2ogpt/assets/26419230/8ed15f6a-46e2-418c-b548-a8c76ae7f484">

**Comment by ryanchesler** [comment]
https://github.com/h2oai/h2ogpt/pull/792 closed in this PR
