### ISSUE TITLE
Getting long answers using flacon 40B model

### ISSUE THREAD

**Issue by KGSSV** [h2oai/h2ogpt#784]
when i am trying to generate a response the answer is incomplete 

generate.py command used : python3 generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-40b-v2 --score_model=None --prompt_type=human_bot --load_8bit=True --use_gpu_id=False --share=False --gradio_offline_level=1 --max_max_new_tokens=2048 --max_new_tokens=512

i am using client_gradle to connect to model on port 7860

**Comment by pseudotensor** [comment]
That is the wrong prompt_type for the "gm" model.  Drop that option.  You can also make max_new_tokens 1024, e.g.:
```
python3 generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-40b-v2 --score_model=None ----load_8bit=True --use_gpu_id=False --share=False --gradio_offline_level=1 --max_max_new_tokens=2048 --max_new_tokens=1024
```

If you have large inputs, like docs, then you'll not want to push too large on max_new_tokens.  But if you are output dominated, then 1024 is good option for that model.
