### ISSUE TITLE
REG: Falcon 40B Model Output 

### ISSUE THREAD

**Issue by umang93769** [h2oai/h2ogpt#789]
Hello Folks I am currently using Falcon 40B Model in my setup and using the following command to run the model 

python3 generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-40b-v2 --score_model=None ----load_8bit=True --use_gpu_id=False --share=False --gradio_offline_level=1 --max_new_tokens=2048

Now I want my model to give maximum output while asked something. What I have observed is that when I give a big input while the model tris to give output. It gets stopped in the middle giving incomplete answer. 

Is there any way I can stop this from happening

**Comment by ryanchesler** [comment]
If you look in expert settings in the UI there is an option to change the maximum time. That might be what you are running into if the processing is slow. Increasing this number might fix it

**Comment by pseudotensor** [comment]
This model has maximum of 2048 token context.  So you must have 2048 = input + output.  If you have big input, you can't have big output.

Perhaps you should use a model with more tokens, like llama-2 with 4096.

In principle we can go beyond token limit by continuing generation and dropping prior tokens.  This is called "continue" and is an open issue: https://github.com/h2oai/h2ogpt/issues/248
