### ISSUE TITLE
Question: Usage of GPT4All model

### ISSUE THREAD

**Issue by dlippold** [h2oai/h2ogpt#798]
I downloaded the model `ggml-model-gpt4all-falcon-q4_0.bin` from the GPT4All page (https://gpt4all.io/index.html). How can I use that model? Which option for `generate.py` and which values for these options I have to use?

If that model is not usable, is there an other falcon model which I can download from https://huggingface.co/TheBloke ?

I want to use the falcon model and don't want to use a model of the Llama family. And I want to manually download the model for offline mode.

**Comment by pseudotensor** [comment]
I recommend llama.cpp based GGML models instead from TheBloke.  For running any such models, see https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#adding-models .  Re-open if you have questions.

**Comment by dlippold** [comment]
What do you mean with _I recommend llama.cpp based GGML models instead from TheBloke_? Does that mean that currently the falcon model cannot be used or that I should use the falcon model with a different model version (e.g. v3)?

Becase of the name of the file `ggml-model-gpt4all-falcon-q4_0.bin` I think it is a GGML file. But reading the FAQ from your link I suppose with "GGML model" you mean " GGML model v3" (cite from the FAQ: _GGML v3 quantized models are supported_).

Therefore I downloaded the model file `h2ogpt-gm-oasst1-en-2048-falcon-7b-v3.ggccv1.q4_0.bin` from the page https://huggingface.co/TheBloke/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3-GGML (i.e. GGML v3).

When I execute the command
`python generate.py --score_model=None --share=False --local_files_only=True --base_model=llama --model_path_llama=/home/h2ouser/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3.ggccv1.q4_0.bin --max_seq_len 2048`
I get the following output:

> Auto set langchain_mode=LLM.  Could use MyData instead.  To allow UserData to pull files from disk, set user_path or langchain_mode_paths, and ensure allow_upload_to_user_data=True
> No GPUs detected
> Using Model llama
> Prep: persist_directory=db_dir_UserData exists, using
> Starting get_model: llama 
> /home/h2ouser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:995: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
>   warnings.warn(
> llama.cpp: loading model from /home/h2ouser/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3.ggccv1.q4_0.bin
> llama_model_load_internal: format     = ggjt v3 (latest)
> llama_model_load_internal: n_vocab    = 65024
> llama_model_load_internal: n_ctx      = 2048
> llama_model_load_internal: n_embd     = 4544
> llama_model_load_internal: n_mult     = 71
> llama_model_load_internal: n_head     = 1
> llama_model_load_internal: n_layer    = 32
> llama_model_load_internal: n_rot      = 7
> llama_model_load_internal: freq_base  = 10000.0
> llama_model_load_internal: freq_scale = 1
> llama_model_load_internal: ftype      = 2 (mostly Q4_0)
> llama_model_load_internal: n_ff       = 12141
> llama_model_load_internal: model size = 7B
> llama_model_load_internal: ggml ctx size =    0.05 MB
> error loading model: llama.cpp: tensor 'tok_embeddings.weight' is missing from model
> llama_load_model_from_file: failed to load model
> Traceback (most recent call last):
>   File "/home/h2ouser/h2ogpt/generate.py", line 16, in <module>
>     entrypoint_main()
>   File "/home/h2ouser/h2ogpt/generate.py", line 12, in entrypoint_main
>     H2O_Fire(main)
>   File "/home/h2ouser/h2ogpt/src/utils.py", line 59, in H2O_Fire
>     fire.Fire(component=component, command=args)
>   File "/home/h2ouser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "/home/h2ouser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>   File "/home/h2ouser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "/home/h2ouser/h2ogpt/src/gen.py", line 1124, in main
>     model0, tokenizer0, device = get_model(reward_type=False,
>   File "/home/h2ouser/h2ogpt/src/gen.py", line 1579, in get_model
>     model, tokenizer, device = get_model_tokenizer_gpt4all(base_model, n_jobs=n_jobs,
>   File "/home/h2ouser/h2ogpt/src/gpt4all_llm.py", line 16, in get_model_tokenizer_gpt4all
>     model = get_llm_gpt4all(model_name, model=None,
>   File "/home/h2ouser/h2ogpt/src/gpt4all_llm.py", line 152, in get_llm_gpt4all
>     llm = cls(**model_kwargs)
>   File "/home/h2ouser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain/load/serializable.py", line 74, in __init__
>     super().__init__(**kwargs)
>   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 1 validation error for H2OLlamaCpp
> __root__
>   Could not load Llama model from path: /home/h2ouser/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3.ggccv1.q4_0.bin. Received error  (type=value_error)
> Exception ignored in: <function Llama.__del__ at 0x7fc33ef27760>
> Traceback (most recent call last):
>   File "/home/h2ouser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/llama_cpp/llama.py", line 1502, in __del__
>     if self.ctx is not None:
> AttributeError: 'Llama' object has no attribute 'ctx'
> 

What I can do to use a falcon model from TheBloke?

**Comment by pseudotensor** [comment]
I see the same error with that particular model file.  TheBloke must have not made it correctly.

If you try a llama based file like in the readme.md (and many others I've tried) there is no problem.
