### ISSUE TITLE
Missing kwargs for make_db: ['caption_loader', 'doctr_loader'] with recent pull

### ISSUE THREAD

**Issue by emil-jose** [h2oai/h2ogpt#800]
Hi, while running the following command I am getting this error `Missing kwargs for make_db: ['caption_loader', 'doctr_loader']` error. I recently updated my codebase and is getting this error.

`python generate.py --base_model=models--h2oai--h2ogpt-4096-llama2-13b-chat --load_8bit=True --langchain_mode='UserData' --user_path=/home/users/user_path1  --score_model=None --share=False --prompt_type=llama2  --use_safetensors=True --save_dir=save --max_max_new_tokens=2048 --max_new_tokens=1024`.

**Comment by pseudotensor** [comment]
You are a ~1week behind main or nightly docker when that was fixed.
