### ISSUE TITLE
Request to Use ClusterIP Instead of NodePort in Helm

### ISSUE THREAD

**Issue by ffalkenberg** [h2oai/h2ogpt#802]
Hello maintainers,

I've been reviewing the changes made in [PR #770](https://github.com/h2oai/h2ogpt/pull/770/files#diff-8c3c7eccd035185065de6a18b948390cade50e8fd3b860f996ab57c8d6729d66) and noticed that NodePort is being utilized. I'd like to request that ClusterIP be used instead of NodePort or, alternatively, make the choice between ClusterIP and NodePort configurable. Here are my reasons:

1. **Security Concerns:** NodePorts expose the service on each Node's IP at a static port in the 30000-32767 range. This can lead to potential security vulnerabilities, especially if not properly managed. In our company, due to these security concerns, NodePorts are not available.

2. **Use Case Specificity:** For the use case in question, it seems that the service would typically be accessed within a single cluster. In such scenarios, ClusterIP, which exposes the service on a cluster-internal IP, would be more appropriate and secure.

4. **Configurability:** While making the choice between ClusterIP and NodePort configurable would be a step in the right direction, it appears that the current implementation doesn't fully support this. Offering full configurability would provide users with the flexibility to choose the best option for their specific environment and security requirements.

I understand that there might be specific reasons for choosing NodePort, but considering the security implications, the typical use case, and the need for flexibility, I believe ClusterIP or full configurability would be better choices. I'd appreciate it if this could be taken into consideration.

Thank you for your time and understanding.

**Comment by achraf-mer** [comment]
addressed in https://github.com/h2oai/h2ogpt/pull/825

**Comment by achraf-mer** [comment]
Hi @ffalkenberg, thanks for the feedback, please checkout the latest changes in the main branch.

**Comment by ffalkenberg** [comment]
@achraf-mer thank you, that's amazing!
