### ISSUE TITLE
如何在虚拟环境中用pip安装新的模块包？

### ISSUE THREAD

**Issue by running-frog** [h2oai/h2ogpt#804]
当我加载qianwen模型时，提示如下：
Error
This modeling file requires the following packages that were not found in your environment: transformers_stream_generator. Run `pip install transformers_stream_generator`

如何在虚拟环境中用pip安装新的模块包？

**Comment by running-frog** [comment]
我用的是这个安装包。[h2oGPT GPU-CUDA Installer](https://h2o-release.s3.amazonaws.com/h2ogpt/h2oGPT_0.0.1_gpu.exe) (1.8GB file)

**Comment by michaelthecsguy** [comment]
uh... I don't think this is an issue.  You should not open an issue by asking how to install something.  Use email to ask for support.

**Comment by pseudotensor** [comment]
Hi, I can't quite follow.  Is it possible to report the problem in english?  I tried to use google translate but it didn't help.

I do recommend the windows installer for windows.
