### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by gpnath82** [h2oai/h2ogpt#812]
Why am I getting this warring with base model llama, can somebody put some light ?
I have enough RAM around 96 GB and 2 L4 GPU of 24 GB

llama_model_load_internal: total VRAM used: 8106 MB
warning: failed to mlock 139264000-byte buffer (after previously locking 0 bytes): Cannot allocate memory
Try increasing RLIMIT_MLOCK ('ulimit -l' as root).
llama_new_context_with_model: kv self size  = 1024.00 MB

**Comment by pseudotensor** [comment]
If you don't want to change your system, you can disable mlock, like doc string shows:
```
--llamacpp_dict="{'n_gpu_layers':25,'n_batch':128,'use_mlock': False}"
```
or whatever values you want to use.
