### ISSUE TITLE
How can I update DB from python client or via API?

### ISSUE THREAD

**Issue by anhdowastaken** [h2oai/h2ogpt#817]
I would like to update DB programmatically instead of via the button on web UI.

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/blob/main/docs/README_CLIENT.md

https://github.com/h2oai/h2ogpt/blob/354f4c45159f34eb3b3765394f78d4998d2a453a/tests/test_client_calls.py#L750-L1112
