### ISSUE TITLE
Please reopen issue 798

### ISSUE THREAD

**Issue by dlippold** [h2oai/h2ogpt#822]
As described on https://github.com/orgs/community/discussions/41926 there should be a _reopen button_ on a page with a closed issue. But I can't find it on the page of the closed issue #798 (where a added a new comment today). Can you tell me why?

Please reopen the issue #798.

**Comment by pseudotensor** [comment]
I still get notifications even if closed.  I think the original issue there is closed.  TheBloke's models are vast and many, and it's probable that not all are functional, but this isn't something I can help with.
