### ISSUE TITLE
h2oai/h2ogpt-gm-oasst1-en-2048-falcon-40b-v2 Models Token Limit and how to overcome it?

### ISSUE THREAD

**Issue by oxjohanndiep** [h2oai/h2ogpt#835]
Hello guys, 

I deployed the H2o Falcon-40b on SageMaker and run into the following issue: 

During inference, when my prompt consists of Instruction + relevant context from a document + chat history, the output gets cut off midway due to the models limited token size for input and output. It seems like on the web application, https://gpt.h2o.ai/, the same model can handle history quite well without the answers being truncated. I tried going through the source code to find how this issue has been overcome, but couldnt find anything relevant. Can someone pinpoint me where in the code this has been fixed, or how to generally solve this issue?

**Comment by pseudotensor** [comment]
Hi.  The only options we pass to generate.py that matter for token counts are:
```
--max_max_new_tokens=2048 --max_new_tokens=1024
```
the former is just for the UI, but the 2nd controls how much generation is allowed.  The default is 512 I think.
