### ISSUE TITLE
What is `auth.json.lock`?

### ISSUE THREAD

**Issue by jamesbraza** [h2oai/h2ogpt#838]
When running the below

```bash
python h2ogpt/generate.py --base_model=llama --prompt_type=llama2 \
		--model_path_llama=models/llama-2-13b-chat.Q4_K_S.gguf
```

An `auth.json.lock` file gets made.  What is this file, and should it be version controlled under Git?

**Comment by pseudotensor** [comment]
It's a lock file used to ensure that changes to auth.json (for login with auth used or login from Login tab) do not race among threads.

**Comment by jamesbraza** [comment]
Thanks for response.  Should it be added to Git?  Or `.gitignore`'d?

**Comment by pseudotensor** [comment]
It's a runtime thing,  so isn't related to git.  It's not a development thing.  But you can add it to your own .gitignore if you want.
