### ISSUE TITLE
Clarity in startup procedure windows 11

### ISSUE THREAD

**Issue by bodgeybodgeybodgey** [h2oai/h2ogpt#839]
Once everything is installed, I would like to know more about the startup procedure -

Is this the correct way to start the ui, via opening a conda prompt (as admin?) and activate the venv, and then load the model - 

 conda activate h2ogpt

python generate.py --base_model='llama' --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=--user_path=C:\Users\YourUsername\h2ogpt

--------------

Also I did the full install procedure - as per this page:

https://github.com/h2oai/h2ogpt/blob/main/docs/README_WINDOWS.md

 should I have used the windows 11 installer?

**Comment by pseudotensor** [comment]
For windows I recommend the windows installer, although its release is behind main hash.  But there aren't very significant differences in main vs. that windows installer release else I would have built a new windows release.

As for readme_windows.md.  I tried to show steps and show screen shots.  I didn't choose admin when I did it, so I don't think that is required.  But if you have a firewall you may need to play with that if it's too strict and the application can't even talk to itself and  you get connection errors.

Yes, everytime you get back into the miniconda shell, you should activate h2ogpt env again, go into the h2ogpt repo folder, and re-run the python generate.py command.
