### ISSUE TITLE
CPU Mode on TheBloke model llama-2-7b-chat.ggmlv3.q8_0.bin is no longer able to be initialized at start up after following README_MACOS instructions

### ISSUE THREAD

**Issue by michaelthecsguy** [h2oai/h2ogpt#840]
I am using Macbook Pro with M1 and OSX is 12.6.

After today git pull at master/main, try to run this for CPU mode:
`python generate.py --base_model='llama' --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=user_path`

I was able to start up the server by by following the "Getting Started" instructions for the CPU mode in main README before I followed README_MACOS.md setup instruction.  However, I tested out last week change and recent change by using git reset --hard.  **Recent changes does not cause the "fail to start" issue.**  Somewhere in the instructions from README_MACOS.md cause unable to start the server up.

Here is the "Fail to start" issue after following the "README_MACOS.md" setup instructions (don't know which part):

Fatal Python error: Illegal instruction
Thread 0x000000030c79e000 (most recent call first):
...
...
Current thread 0x0000000205553600 (most recent call first):
 File "Development/h2ogpt/src/gpt4all_llm.py", line 306 in validate_environment
  File "opt/miniconda3/envs/H2OGpt_3_10/lib/python3.10/site-packages/langchain/load/serializable.py", line 74 in __init__
  File "Development/h2ogpt/src/gpt4all_llm.py", line 152 in get_llm_gpt4all
  File "Development/h2ogpt/src/gpt4all_llm.py", line 16 in get_model_tokenizer_gpt4all
  File "Development/h2ogpt/src/gen.py", line 1583 in get_model
  File "Development/h2ogpt/src/gen.py", line 1127 in main
  File "opt/miniconda3/envs/H2OGpt_3_10/lib/python3.10/site-packages/fire/core.py", line 691 in _CallAndUpdateTrace
  File "opt/miniconda3/envs/H2OGpt_3_10/lib/python3.10/site-packages/fire/core.py", line 475 in _Fire
  File "/opt/miniconda3/envs/H2OGpt_3_10/lib/python3.10/site-packages/fire/core.py", line 141 in Fire
  File "Development/h2ogpt/src/utils.py", line 59 in H2O_Fire
  File "Development/h2ogpt/generate.py", line 12 in entrypoint_main
  File "Development/h2ogpt/generate.py", line 16 in <module>
Illegal instruction: 4
opt/miniconda3/envs/H2OGpt_3_10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

The alternative for running CPU mode with a successful initialization is following but I cannot get the response back (The prompt is just stuck there):
`python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-open-llama-7b --prompt_type=llama2 --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --langchain_mode=UserData --user_path=user_path --share=False --max_seq_len=2048`

**Comment by pseudotensor** [comment]
Hi, I haven't changed packages or code related to GGML that would cause illegal instruction.  Probably a bug in llama.cpp I'd guess.

It's also possible that your env is mixed up with different package versions after installing other software.  llama.cpp and langchain have very strict version requirements.

It's possible that

**Comment by michaelthecsguy** [comment]
@pseudotensor - I have changed the description of the issue after an investigation.  Basically, if I follow the "Getting Start" in main README on CPU Mode, I can start up the server.  If I follow the instructions from "README_MACOS.md", I fail to start the server up.

**Comment by pseudotensor** [comment]
@michaelthecsguy Can you ensure that you have the llama cpp python version for metal installed?

**Comment by michaelthecsguy** [comment]
@pseudotensor yes, it was installed.  It was a part of instructions from README_MACOS.

**Comment by michaelthecsguy** [comment]
FYI, from README_MACOS.md, despite to uninstall pytorch (2.0.1) and to install nightly build, there was an ERROR after pip install.
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.15.2 requires torch==2.0.1, but you have torch 2.2.0.dev20230912 which is incompatible.`

**Comment by michaelthecsguy** [comment]
@pseudotensor Found the issue that causes Fatal Python error on instruction.

After I executed this instruction in README_MACOS.md, I cannot start the server up and reproduce the same ERROR msg like before:

`pip uninstall llama-cpp-python -y
CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1 pip install -U llama-cpp-python==0.1.78 --no-cache-dir`

**Comment by michaelthecsguy** [comment]
Ok, dug a little bit more

If I do `pip install llama-cpp-python==0.1.78`, I can start up the server with CPU mode.  What does this `CMAKE_ARGS="-DLLAMA_METAL=on"` do after forcing CMAKE?

**Comment by michaelthecsguy** [comment]
@Mathanraj-Sharma, thanks for explanation.  Don't check the main README but recheck the README_MACOS.md

cc: @pseudotensor

**Comment by michaelthecsguy** [comment]
This has been tested without recompiling llama-cpp-python and without reinstall torch in MACOS CPU mode.  Just an FYI.

CC: @pseudotensor

**Comment by pseudotensor** [comment]
@Mathanraj-Sharma Please check readme and close this issue if docs are clarified.  Thanks!

**Comment by Mathanraj-Sharma** [comment]
@pseudotensor I followed the instructions on README_MACOS and everything worked as expected for me.

And since Pytorch released torch `2.1.0` we can use that for Mac m1/m2. no need to install from nightly
#911

**Comment by Mathanraj-Sharma** [comment]
A comment is added to doc, 

If `llama-cpp-python` is compiled for MPS usage (i.e `CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1 pip install -U llama-cpp-python==0.1.78 --no-cache-dir`) then by default it will run on GPU mode when we deploy a LLama model. 

to run in CPU mode we have to specify the `'n_gpu_layer': 0` in `--llamacpp_dict ` arg. 

I have added this to the doc as well #911 

@michaelthecsguy please try it and let me know

**Comment by pseudotensor** [comment]
Thanks for checking!
