### ISSUE TITLE
Query using API

### ISSUE THREAD

**Issue by AdityanThiruchuri** [h2oai/h2ogpt#842]
Is there a way where I can upload a pdf in HuggingFace and chat with it using API from outside HugginFace ?

**Comment by AdityanThiruchuri** [comment]
I am trying to implement a pdf chat functionality.  I've the space created in hugginface.  I will upload the necessary pdf's in the huggingface space.  I want to use the H2o API to be used to do chat with the pdf outside / inside hugginface by using API

**Comment by pseudotensor** [comment]
The gradio API with doc QA is shown here: https://github.com/h2oai/h2ogpt/blob/main/docs/README_CLIENT.md .  Many other examples of API calls are in the test code for "steps3" test: https://github.com/h2oai/h2ogpt/blob/main/tests/test_client_calls.py#L907

The gradio server would just be started and the gradio API calls would reference that server's IP/port.
