### ISSUE TITLE
Falcon-180B model now slow on gpt.h2o.ai

### ISSUE THREAD

**Issue by kiwipunch** [h2oai/h2ogpt#843]
The output generation speed for this model is now much slower than previously. When compared to the other models, it is now noticeably slower. Is there a fix for this on mobile devices?

**Comment by pseudotensor** [comment]
Hi, I see same thing, where it's probably 3x slower than usual at moment.  I don't think there is something wrong with the system, etc, but seems like heavy usage.  I'll review usage patterns to ensure access is fair across users.

**Comment by kiwipunch** [comment]
Sounds good, thank you for the reply. Just thought it was quite unusual for it to be the only model with that slow output speed.

**Comment by pseudotensor** [comment]
Looking into it more,  it is slow despite no heavy usage.  A restart of the inference server didn't help.  I don't think it was this slow before, we are looking into it.

**Comment by kiwipunch** [comment]
Okay great, thank you very much for looking into this issue.

**Comment by pseudotensor** [comment]
FYI it was our service provider's machine, after they migrated some things and system is back to normal.
