### ISSUE TITLE
How to pre-inject prompt behind the scenes

### ISSUE THREAD

**Issue by jamesbraza** [h2oai/h2ogpt#847]
I am using [`TheBloke/Llama-2-13B-chat-GGUF/llama-2-13b-chat.Q4_K_S.gguf`](https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/tree/main) with h2ogpt as a front end like so:

```bash
python h2ogpt/generate.py --base_model=llama --prompt_type=llama2 \
    --model_path_llama=models/llama-2-13b-chat.Q4_K_S.gguf \
    --llamacpp_dict="{n_gpu_layers:100, use_mlock:False, n_batch:1024, n_gqa:0}"
```

The question is, how can one pre-inject context information to the LLM behind the scenes?

I want to inject the LLM with some context like "you are superman, and you are talking with lois lane" behind the scenes, before the conversation even begins with "Ask anything":

![screenshot of conversational window](https://github.com/h2oai/h2ogpt/assets/8990777/5ff76fe5-f792-4d4e-9ba5-8168a9048184)

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#in-context-learning-via-prompt-engineering

**Comment by jamesbraza** [comment]
Thank you @pseudotensor, appreciated!
