### ISSUE TITLE
Loosen `requirements.txt` dependencies

### ISSUE THREAD

**Issue by jamesbraza** [h2oai/h2ogpt#848]
I am unable to `pip install -r requirements.txt` into certain projects given its exact pinning of:

- `gradio`
- `gradio_client`
- `numpy`

Can you loosen the dependencies in `requirements.txt` so it's based on supported ranges?

That way h2ogpt can be easily used in pre-existing projects.

**Comment by pseudotensor** [comment]
Many cannot be made loose, and every existing env will vary in its potential to work if things are made loose.  You can try relaxing the ones you hit.
