### ISSUE TITLE
Version incompatibilities with `llama-cpp-python[server]`

### ISSUE THREAD

**Issue by jamesbraza** [h2oai/h2ogpt#849]
https://github.com/h2oai/h2ogpt/issues/848 was closed for stability reasons, which is okay with me.

However, there are two hard-stop conflicts right now with [`llama-cpp-python[server]==0.2.5`](https://github.com/abetlen/llama-cpp-python/blob/v0.2.5/pyproject.toml#L30), which requires `pydantic>=2`:
- `requirements.txt` has `text-generation==0.6.0`, which requires `pydantic<2`
- `reqs_optional/requirements_optional_langchain.txt` has `langchain==0.0.250`, which requires `pydantic<2`

Newer versions of both of these packages support pydantic v2.  Is there any chance we can bump these versions?

Thank you in advance for your consideration

**Comment by jamesbraza** [comment]
Sigh, looks like `text-generation`'s support of `pydantic>=2` has not yet been released: https://github.com/huggingface/text-generation-inference/issues/1030.

**Comment by pseudotensor** [comment]
Hi @jamesbraza is it hard to just have 2 envs?

**Comment by jamesbraza** [comment]
I am using [`pip-compile`](https://github.com/jazzband/pip-tools) to compile my dependencies just to ensure global compatibility.  However, you're right, there could be two virtual environments, one for CI testing (requires `llama-cpp-python[server]`) and one for server running front end (`h2ogpt`).  This would remove the dependency resolution issue.
