### ISSUE TITLE
CUDA Error from the CPU version?

### ISSUE THREAD

**Issue by snunez1** [h2oai/h2ogpt#855]
Whilst trying to load `TheBloke/Llama-2-7b-Chat-GPTQ`, I get the following:

```
CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. 
```
This surprises me because, although I have a GPU, it's ancient.  I got this error when I started with the GPU version, then I uninstalled that one and installed the CPU version.  Any ideas why I'd be seeing a CUDA error on a GPU version of the system?

**Comment by pseudotensor** [comment]
I presume you are using autogptq mode?  What's  your command line?  I'm not aware if they support CPU: https://github.com/PanQiWei/AutoGPTQ .

For GGML, some binary wheels probably  have been compiled with specific arches in mind, and one might have to compile yourself as in the readme.

**Comment by snunez1** [comment]
I'm not using the command line.  I'm using the [Windows installer versions](https://github.com/h2oai/h2ogpt/blob/main/README.md#windows-1011-64-bit-with-full-document-qa-capability); it appears in the start menu.

**Comment by pseudotensor** [comment]
Can you share a screenshot of what you are entering into the UI?  E.g. for GPTQ models one needs to use autogptq option nominally, although TheBloke changed many of his repositories to be just "main" for that option.

**Comment by snunez1** [comment]
![Capture](https://github.com/h2oai/h2ogpt/assets/7775472/7cb8df61-fdb1-44b5-a985-bbe0307f16aa)

**Comment by snunez1** [comment]
I get a similar error from `h2oai/h2ogpt-4096-llama2-7b`

**Comment by pseudotensor** [comment]
If you are trying to use CPU, please add environment variable CUDA_VISIBLE_DEVICES and set as an empty string.  This forces the GPU to be ignored by torch/cuda.  I didn't make it possible to avoid using GPU from UI.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/0142e43b-d4d1-4dad-b6ac-05c39fc2e607)

**Comment by snunez1** [comment]
This works.  I'll leave open as a reminder that the CPU version of the installer should use the CPU.
