### ISSUE TITLE
chromamigdb error

### ISSUE THREAD

**Issue by a3nima** [h2oai/h2ogpt#859]
When trying to run I got the error:

> Using Model thebloke/llama-2-13b-chat-gptq
> Traceback (most recent call last):
>   File "E:\TEXT-AI\h2ogpt\generate.py", line 16, in <module>
>     entrypoint_main()
>   File "E:\TEXT-AI\h2ogpt\generate.py", line 12, in entrypoint_main
>     H2O_Fire(main)
>   File "E:\TEXT-AI\h2ogpt\src\utils.py", line 59, in H2O_Fire
>     fire.Fire(component=component, command=args)
>   File "e:\TEXT-AI\venv\h2ogpt\lib\site-packages\fire\core.py", line 141, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "e:\TEXT-AI\venv\h2ogpt\lib\site-packages\fire\core.py", line 475, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>   File "e:\TEXT-AI\venv\h2ogpt\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "E:\TEXT-AI\h2ogpt\src\gen.py", line 1017, in main
>     db = prep_langchain(persist_directory1,
>   File "E:\TEXT-AI\h2ogpt\src\gpt_langchain.py", line 2444, in prep_langchain
>     get_existing_db(None, persist_directory, load_db_if_exists,
>   File "E:\TEXT-AI\h2ogpt\src\gpt_langchain.py", line 2589, in get_existing_db
>     raise ValueError(
> ValueError: Detected chromadb<0.4 database, require migration, but did not detect chromamigdb package or did not choose auto_migrate_db=False (see FAQ.md)

I tried updating chromadb and auto_migrate_db=True, but that did nothing. also there is no chromadbmig package installed or available?!

**Comment by pseudotensor** [comment]
The requirements file was updated.  You should at least run through pip install for langchain req file. The FAQ.md explains as it mentions. Let me know…

**Comment by a3nima** [comment]
thank you! it solved the issue. perhaps, if you dont mind, can you help me with this:

> The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.

I have not specified tie_weights or _infer_auto_device in my starting bat file.

**Comment by pseudotensor** [comment]
Yes, by default we do not migrate, we just use the correct version of chroma package, else it would take long time to migrate (default chromadb team expectation).

The tie weights warning can be ignored.
