### ISSUE TITLE
Use FAISS as embeddings db. 

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#862]
Hi, 
In the readme there's a mention that FAISS is also supported, but I can't find to how to use it in readme or in the code.
Can you please provide the way how to use FAISS (including it's persistence) ?

Thanks

**Comment by pseudotensor** [comment]
There's no persistence for FAISS.  One could pickle its state, but that's way too slow.

**Comment by slavag** [comment]
Thanks, so read index from disk is too slow ?

**Comment by pseudotensor** [comment]
For FAISS there is no index, it's just a blob state one can pickle and each save would have to save the entire blob.

**Comment by slavag** [comment]
@pseudotensor strange, in their github they mentioned index
https://github.com/facebookresearch/faiss/wiki/Index-IO,-cloning-and-hyper-parameter-tuning
Thanks

**Comment by pseudotensor** [comment]
https://python.langchain.com/docs/integrations/vectorstores/faiss#saving-and-loading

but this is a large file and inefficient to persist incremental new documents.

I don't plain to extend faiss support, for many reasons related to detailed support of filtering.

**Comment by slavag** [comment]
Thanks
