### ISSUE TITLE
#Feature request Cpu docker compose 

### ISSUE THREAD

**Issue by bolavefasfas** [h2oai/h2ogpt#864]
Cpu docker compose file or instructions on how to run it on cpu in a docker contianer ?

**Comment by pseudotensor** [comment]
@ChathurindaRanasinghe are the instructions for CPU much different?

**Comment by ChathurindaRanasinghe** [comment]
@pseudotensor Yeah running on CPU is different since current docker-compose is for running on GPU with our Dockerfile based on CUDA base image.

**Comment by zorgonred** [comment]
Following, need this for my M2 Mac

**Comment by pseudotensor** [comment]
@achraf-mer @ChathurindaRanasinghe This is still needed in general for our other products.
