### ISSUE TITLE
pydantic.error_wrappers.ValidationError

### ISSUE THREAD

**Issue by chiru-maddala** [h2oai/h2ogpt#868]
File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for H2OLlamaCpp
__root__
  argument of type 'NoneType' is not iterable (type=type_error)

----
Running on Mac Book Pro (Intel). Please Suggest

**Comment by pseudotensor** [comment]
You probably have too new langchain.  Several dependencies are versioned for reason.  I get same thing if I use latest langchain.

**Comment by devloic** [comment]
I am getting the same error trying to load a GGUF model (llama-2-7b-chat.Q4_K_S.gguf) on linux
I am using:
llama-cpp-python     0.1.83+rocm5.6.1
gpt4all                      1.0.12
langchain                 0.0.300

any other dependency I should check maybe ?
