### ISSUE TITLE
slow db for large collection

### ISSUE THREAD

**Issue by pavelhym** [h2oai/h2ogpt#870]
I've created large collection of PDF's with hkunlp/instructor-large embedding model. But the response of the LLM is very slow, looking through the workload of the GPU the process of going-through vectorized db is run by CPU, while the only LLM response utilizes GPU. How this problem can be solved if it can be?

**Comment by pavelhym** [comment]
upd. The problem arises not only with large collections, the small ones also utilizes CPU first, then GPU to create response

**Comment by pseudotensor** [comment]
Hi, can you give more details?  What is the command line you run to get h2oGPT going?

In general there is parsing, embedding first, and then later search and LLM.  The search is very fast (ms) even for massive databases, although very first time db is hit it's loaded into memory.

However, if you use (e.g.) top_k_docs=-1 to fill entire context with docs, that will take LLM longer.  But nothing really should be using CPU much during the query time.

**Comment by pavelhym** [comment]
To create db I use:
`python src/make_db.py --user_path=path --collection_name=collection--langchain_type=shared --hf_embedding_model=hkunlp/instructor-large
`
Then to run the model I use:
`python generate.py --base_model=h2oai/h2ogpt-4096-llama2-13b-chat --load_4bit=True --prompt_type=llama2 --langchain_mode='collection' --langchain_modes="['LLM','collection']"`

When I try to run promt with created collection the first 30s GPU is no utilized at all, while after that GPU is loaded just for 1s and the result is given, which means that GPU runs only for the LLM output, but not for search through documents. The size of collection is near 1.9Gb.

**Comment by pseudotensor** [comment]
The very first time the db is hit, it loads into memory.  I have half of wikipedia database that is 20GB, and very first time accessed it would take 20s to load-up into memory.  But then every query after it would be instant.

So if you see one-time lag, that's what that is.  If you see lag every time, then that is not clear.  You can use `kill -s SIGUSR1 <pid>` for the <pid> shown in `top` to see a stack trace (all threads) of where h2oGPT is when it is lagging.

**Comment by pseudotensor** [comment]
Maybe chroma > 0.4 with sqlite is not good.  If you have a repro case that only involves chroma, good to share with them.

**Comment by pseudotensor** [comment]
I can make it so one can choose to create a chroma < 0.4 or >=0.4 database.  Maybe the duckdb one is faster.

**Comment by slavag** [comment]
@pseudotensor will try to create a db with chroma 0.4 for repro

**Comment by slavag** [comment]
@pseudotensor I submitted issue with chroma. Also, wanted to ask if it's possible to add log with statistics where time is spent, as for today I don't see it.

Thanks

**Comment by pseudotensor** [comment]
I see same thing.  I'll try to understand if they have a new usage pattern that I'm not following.  But the code involved is same as was used for duckdb.

**Comment by pseudotensor** [comment]
@slavag  and @pavelhym .  I added ability to use old chroma for new databases.  Just pass --db_type=chroma_old for src/make_db.py or generate.py and new databases will use the old chroma that should be fast again.

I didn't notice the slowness since all unit and integration tests are no more than 200 PDFs that wouldn't show up in major slowdown in testing.

Please try and give feedback.  Thanks!

**Comment by pseudotensor** [comment]
I see it not stuck in db.get() now, but I still see long similarty search:
```
Detected chroma<0.4 database but --auto_migrate_db=False, but detected chromamigdb package, so using old database that still requires duckdb
Thread 0x00007f008d7fe700 (most recent call first):
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/chromamigdb/db/duckdb.py", line 271 in _get
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/chromamigdb/db/clickhouse.py", line 494 in get
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/chromamigdb/db/clickhouse.py", line 574 in get_nearest_neighbors
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/chromamigdb/api/local.py", line 439 in _query
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/chromamigdb/api/models/Collection.py", line 230 in query
  File "/home/ubuntu/h2ogpt/src/chromamig.py", line 156 in __query_collection
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/langchain/utils/utils.py", line 30 in wrapper
  File "/home/ubuntu/h2ogpt/src/chromamig.py", line 323 in similarity_search_with_score
  File "/home/ubuntu/h2ogpt/src/gpt_langchain.py", line 3694 in get_docs_with_score
  File "/home/ubuntu/h2ogpt/src/gpt_langchain.py", line 4230 in get_chain
  File "/home/ubuntu/h2ogpt/src/gpt_langchain.py", line 3520 in _run_qa_db
  File "/home/ubuntu/h2ogpt/src/gen.py", line 2353 in evaluate
  File "/home/ubuntu/h2ogpt/src/gradio_runner.py", line 2968 in get_response
  File "/home/ubuntu/h2ogpt/iterators/timeout_iterator.py", line 99 in __lookahead
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/threading.py", line 953 in run
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/threading.py", line 973 in _bootstrap
```

This is unusual for duckdb.  I'll have to check how older code worked.  maybe the filters or something else make chroma go much slower.

**Comment by slavag** [comment]
@pseudotensor  tried to create new DB with flag --db_type=chroma_old and somehow getting it failed:
```
python src/make_db.py -user_path=/mnt/D184MB -collection_name=TestTextsOLDChroma --db_type=chroma_old
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 425/425 [00:02<00:00, 154.88it/s]
0it [00:00, ?it/s]
Exceptions: 0/491862 []
load INSTRUCTOR_Transformer
max_seq_length  512
Killed
```
Have no idea how to proceed from here.

**Comment by pseudotensor** [comment]
You probably ran out of memory.

**Comment by slavag** [comment]
@pseudotensor RAM or VRAM , as I see (started process again) not that much memory used, and with chroma 0.4 it's created fine.
<img width="1718" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/7103c75a-7fca-4eb9-9dd9-e33acb335e89">

**Comment by pseudotensor** [comment]
You can check `dmesg -T` to see why the process was killed.

**Comment by slavag** [comment]
@pseudotensor I generated the DB, but when I'm trying to start chat with that DB `python generate.py --base_model=llama --prompt_type=llama2 --model_path_llama=/mnt/AI/models/TheBloke/Llama-2-13B-chat-GGUF/llama-2-13b-chat.Q6_K.gguf  --langchain_modes="[LLM, TestTextsOLDChroma]" --h2ocolors=False --use_llm_if_no_docs=False --max_seq_len=4096 --temperature=0.01  --langchain_modes="[LLM, TestTextsOLDChroma]" --langchain_mode=TestTextsOLDChroma --langchain_mode_types="{'TestTextsOLDChroma':'shared'}" --db_type=chroma_old`

it shows 0 documents in it and version >=0.4
<img width="2536" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/82c79e0e-31b2-494b-9646-710f36bb0aa5">

Perhaps I'm doing something wrong
Please advise.

**Comment by slavag** [comment]
@pseudotensor strange, but with old chromadb now it's even slower than with new. And not GPU utilization at all, just CPU
<img width="863" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/a1d30628-37fd-49b5-9174-d58fb4683e82">

**Comment by slavag** [comment]
@pseudotensor  could be that this is the issue ? https://github.com/chroma-core/chroma/issues/1182

**Comment by pseudotensor** [comment]
I got an old and new chroma db, each about 5-9GB and see similar problems.

1) Figured out why old db was slower and it's possible to work-around.  Basically if doing a filtered similarity search, it's MUCH slower than non-filtered, by about 100x.  I had no idea.  If one is not filtering, it's back to very fast.  Unfortunately, this means cannot filter by document(s) without slowness.  And normally filtering by query or summarization will be as slow, but at least for the latter I can avoid filtering up front and only filter after the fact -- but this risks only getting "summarization" chunks (e.g. full pages per PDF) instead of chunks prepared for semantic search.

2) For new db, any full scan is slow already for 5-9GB, unlike duckdb, by about 20x.  This is bad, but I can avoid the full scan in most cases unless migrating data, but that never currently needs to be done for new chroma db or if changed (and asked to migrate) the embedding.

**Comment by slavag** [comment]
@pseudotensor thanks for the update. I think old chroma is not relevant at least for me. So, I think new one is ok, would be great if this can be fixed.  Btw, what filtering is done on queries, as I'm trying to find how can I prioritize newer documents over old one in the embeddings for Q&A, as old docs may have outdate information.
Thanks

**Comment by pseudotensor** [comment]
Understood AFAIK version desired to be fixed.

For new chroma, the filtering is here: https://github.com/h2oai/h2ogpt/blob/cdfe9316ba9f8f7676050d0cb90d9a0238da4c85/src/gpt_langchain.py#L4216-L4253

and for queries, the filtering is used here:

https://github.com/h2oai/h2ogpt/blob/cdfe9316ba9f8f7676050d0cb90d9a0238da4c85/src/gpt_langchain.py#L4335-L4342

If one goes into `get_docs_with_score` and just avoids any filter by changing:
```
docs_with_score_chroma = db.similarity_search_with_score(query, k=k_db, **filter_kwargs)
```
to 
```
docs_with_score_chroma = db.similarity_search_with_score(query, k=k_db)
```

Then the old chroma is fast.  The new chroma requires more changes to be fast.

But that describes where the primary filtering code is.  There is separate filtering code for document viewing for UI.

**Comment by pseudotensor** [comment]
@slavag and @pavelhym Try now with latest updates.  If use docker nightly we build, then need to wait till 6am PST or so.  AFAIK the PR #929 solved the primary issues.

**Comment by slavag** [comment]
@pseudotensor Great, thank, very fast !
