### ISSUE TITLE
directly access prompt and responses in terminal

### ISSUE THREAD

**Issue by elon-trump** [h2oai/h2ogpt#871]
How to generate prompt and responses through terminal?
I have a model already instruction tuned and able to respond to queries for user uploaded data. I want to now prompt the model through terminal and get the response in terminal as well. 
I want to prompt the model from a remote device by establishing a socket connection, thus i believe that being able to prompt as well as getting response in the terminal would help in making it happen. Kindly help me with the terminal prompt and response and your opinion on the remote prompting will be very valuable as well.
Thank you.

**Comment by pseudotensor** [comment]
--cli=True is for terminal use.

**Comment by elon-trump** [comment]
Thanks
