### ISSUE TITLE
ValueError: Expected where to have exactly one operator, got {''}, 'chunk_id': {'$gte': 0}}

### ISSUE THREAD

**Issue by MSZ-MGS** [h2oai/h2ogpt#873]
I keep receiving this error after selected one document from the interface.
ValueError: Expected where to have exactly one operator, got {'source': {'$eq': 'user_path\\Business_Conduct_Brochure.pdf'}, 'chunk_id': {'$gte': 0}}

![image](https://github.com/h2oai/h2ogpt/assets/65172063/c23a6bce-bca4-49a7-bf9e-de669fa91c7f)

**Comment by pseudotensor** [comment]
Sounds like you have new chroma but old h2oGPT.

https://github.com/chroma-core/chroma/issues/1136

**Comment by pseudotensor** [comment]
@MSZ-MGS Yes, I see same thing.  I must have no test of this somehow, I'm fixing and will review the tests.

**Comment by pseudotensor** [comment]
Fixed now, please try again
