### ISSUE TITLE
Document selection is broken

### ISSUE THREAD

**Issue by MSZ-MGS** [h2oai/h2ogpt#876]
Document selection is broken,
I have selected a specific documents, however, I still receive answers from non selected documents.

**Comment by pseudotensor** [comment]
Thanks for reporting, guess need even more testing, will do next.

**Comment by pseudotensor** [comment]
Thanks for reporting, fixed now with extensive tests for it as well as some improvements in information returned.

https://github.com/h2oai/h2ogpt/commit/22db5ebe67f0a4036fd1088458d10e1459a6847a
https://github.com/h2oai/h2ogpt/commit/bc9433f44db0e8721f82f3c1ebefbc3c0a8b4082
