### ISSUE TITLE
Incomplete response

### ISSUE THREAD

**Issue by aghasaadmohammad** [h2oai/h2ogpt#885]
I am running base_model : h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
and it runs slow but works until it stops being an incomplete answer and breaks to ask again to input instruction.
I am using cli version on windows. 
Thanks

**Comment by pseudotensor** [comment]
For windows and CPU or small GPUs  you should use GGML models instead.  I updated docs to reflect that recommendation better.  Thanks!
