### ISSUE TITLE
Add support for "source" document folder

### ISSUE THREAD

**Issue by lamw** [h2oai/h2ogpt#887]
First off, very cool project!

I think it would be extremely useful if there was an option to `generate.py` to simply include a folder that contains user source files, simliar to what privateGPT/localGPT supports? While the UI is certainly nice, I've found that it can't handle large number of files (in my case 1500+. I was hoping it would attempt to batch upload and then process the all the files ... right now, I've had to break it up into chunks of 25 files and using the UI. 

I saw in a few comments there's an API but not sure what would be the minimal client code to simply upload files which are .html. Any assistance would be great on top of the suggested feature enhancement

**Comment by pseudotensor** [comment]
I think you just mean this, no?

https://github.com/h2oai/h2ogpt/blob/main/docs/README_LangChain.md#database-creation

**Comment by lamw** [comment]
Thank you @pseudotensor, I hadn't looked at that page thinking it might have been referenced in main README

Once the files are loaded into DB, would I simply backup `db_dir_UserData` for future uses, say on another system without having to re-process all files?

**Comment by pseudotensor** [comment]
Yes, in general that's enough for things to work.  If you want links to source files to still work, then the `user_path` directory should also be copied along the with database.  The Chroma database only keeps the text after parsing, not the original source files that are technically not required for anything except staring at them in UI.

**Comment by lamw** [comment]
🙏 Thanks for all the help! First time trying out the solution today
