### ISSUE TITLE
Windows installation command dosent work

### ISSUE THREAD

**Issue by MSZ-MGS** [h2oai/h2ogpt#890]
This command doesent work anymore and I always receive "No GPU" Message.
"pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu117"

However, this works:
pip install torch==2.0.0+cu117 torchvision==0.15.1+cu117 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu117

**Comment by pseudotensor** [comment]
Thanks, I added to instructions.  But I haven't seen this myself when using windows.
