### ISSUE TITLE
How to load a Hugging Face (HF) LLM private model?

### ISSUE THREAD

**Issue by piegu** [h2oai/h2ogpt#894]
Hi,

I have a Llama 2 7B in private mode in the Hugging face hub that I would like to use locally inside the h20gpt interface.

How can I pass the HF api token in order to allow the download of this model?

Thanks you.

Pierre

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#token-access-to-hugging-face-models
