### ISSUE TITLE
Optimizing Concurrent Inference with NVIDIA A100 80 GB GPU for Llama-2 13b Model

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2ogpt#898]
I'm currently utilizing an NVIDIA A100 80 GB GPU to run the Llama-2 13b model, and I've encountered an issue when trying to enable sharing using the `share=True` parameter in the `generate.py` command. Specifically, when two users attempt to access the model through the same network simultaneously, one user's request gets queued.

I'm curious to understand how many users can efficiently access the public URL for parallel inference on the A100 GPU. Additionally, I'm interested in optimizing the `client.py` script to accommodate more concurrent users.

Your guidance on these matters would be greatly appreciated.

Thank you!

**Comment by pseudotensor** [comment]
The --concurrency_count is default 1, one can make it larger to avoid queuing.  However, the best option for concurrency is to use an inference server like vLLM as mentioned in the readme_inference server docs.
