### ISSUE TITLE
 Illegal access to db_dir_MyData

### ISSUE THREAD

**Issue by a3nima** [h2oai/h2ogpt#905]
> Already up to date.
> Using Model thebloke/xwin-lm-13b-v0.1-gptq
> load INSTRUCTOR_Transformer
> max_seq_length  512
> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ E:\TEXT-AI\h2ogpt\generate.py:16 in <module>                                                     │
> │                                                                                                  │
> │   13                                                                                             │
> │   14                                                                                             │
> │   15 if __name__ == "__main__":                                                                  │
> │ ❱ 16 │   entrypoint_main()                                                                       │
> │   17                                                                                             │
> │                                                                                                  │
> │ E:\TEXT-AI\h2ogpt\generate.py:12 in entrypoint_main                                              │
> │                                                                                                  │
> │    9                                                                                             │
> │   10                                                                                             │
> │   11 def entrypoint_main():                                                                      │
> │ ❱ 12 │   H2O_Fire(main)                                                                          │
> │   13                                                                                             │
> │   14                                                                                             │
> │   15 if __name__ == "__main__":                                                                  │
> │                                                                                                  │
> │ E:\TEXT-AI\h2ogpt\src\utils.py:59 in H2O_Fire                                                    │
> │                                                                                                  │
> │     56 │   │                                                                                     │
> │     57 │   │   args.append(f"--{new_key}={value}")                                               │
> │     58 │                                                                                         │
> │ ❱   59 │   fire.Fire(component=component, command=args)                                          │
> │     60                                                                                           │
> │     61                                                                                           │
> │     62 def set_seed(seed: int):                                                                  │
> │                                                                                                  │
> │ e:\TEXT-AI\venv\h2ogpt\lib\site-packages\fire\core.py:141 in Fire                                │
> │                                                                                                  │
> │   138 │   context.update(caller_globals)                                                         │
> │   139 │   context.update(caller_locals)                                                          │
> │   140                                                                                            │
> │ ❱ 141   component_trace = _Fire(component, args, parsed_flag_args, context, name)                │
> │   142                                                                                            │
> │   143   if component_trace.HasError():                                                           │
> │   144 │   _DisplayError(component_trace)                                                         │
> │                                                                                                  │
> │ e:\TEXT-AI\venv\h2ogpt\lib\site-packages\fire\core.py:475 in _Fire                               │
> │                                                                                                  │
> │   472 │     is_class = inspect.isclass(component)                                                │
> │   473 │                                                                                          │
> │   474 │     try:                                                                                 │
> │ ❱ 475 │   │   component, remaining_args = _CallAndUpdateTrace(                                   │
> │   476 │   │   │   component,                                                                     │
> │   477 │   │   │   remaining_args,                                                                │
> │   478 │   │   │   component_trace,                                                               │
> │                                                                                                  │
> │ e:\TEXT-AI\venv\h2ogpt\lib\site-packages\fire\core.py:691 in _CallAndUpdateTrace                 │
> │                                                                                                  │
> │   688 │   loop = asyncio.get_event_loop()                                                        │
> │   689 │   component = loop.run_until_complete(fn(*varargs, **kwargs))                            │
> │   690   else:                                                                                    │
> │ ❱ 691 │   component = fn(*varargs, **kwargs)                                                     │
> │   692                                                                                            │
> │   693   if treatment == 'class':                                                                 │
> │   694 │   action = trace.INSTANTIATED_CLASS                                                      │
> │                                                                                                  │
> │ E:\TEXT-AI\h2ogpt\src\gen.py:1025 in main                                                        │
> │                                                                                                  │
> │   1022 │   │   │   if langchain_type == LangChainTypes.PERSONAL.value:                           │
> │   1023 │   │   │   │   # shouldn't prepare per-user databases here                               │
> │   1024 │   │   │   │   continue                                                                  │
> │ ❱ 1025 │   │   │   persist_directory1, langchain_type = get_persist_directory(langchain_mode1,   │
> │   1026 │   │   │   langchain_mode_types[langchain_mode1] = langchain_type                        │
> │   1027 │   │   │   if langchain_type == LangChainTypes.PERSONAL.value:                           │
> │   1028 │   │   │   │   # shouldn't prepare per-user databases here                               │
> │                                                                                                  │
> │ E:\TEXT-AI\h2ogpt\src\gpt_langchain.py:2858 in get_persist_directory                             │
> │                                                                                                  │
> │   2855 │   │   # ensure consistent                                                               │
> │   2856 │   │   langchain_type = LangChainTypes.SHARED.value                                      │
> │   2857 │   │   persist_directory = makedirs(persist_directory, use_base=True)                    │
> │ ❱ 2858 │   │   check_persist_directory(persist_directory)                                        │
> │   2859 │   │   return persist_directory, langchain_type                                          │
> │   2860 │                                                                                         │
> │   2861 │   # dummy return for prep_langchain() or full personal space                            │
> │                                                                                                  │
> │ E:\TEXT-AI\h2ogpt\src\gpt_langchain.py:2875 in check_persist_directory                           │
> │                                                                                                  │
> │   2872 │   # deal with some cases when see intrinsic names being used as shared                  │
> │   2873 │   for langchain_mode in langchain_modes_intrinsic:                                      │
> │   2874 │   │   if persist_directory == 'db_dir_%s' % langchain_mode:                             │
> │ ❱ 2875 │   │   │   raise RuntimeError("Illegal access to %s" % persist_directory)                │
> │   2876                                                                                           │
> │   2877                                                                                           │
> │   2878 def _make_db(use_openai_embedding=False,                                                  │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> RuntimeError: Illegal access to db_dir_MyData

**Comment by pseudotensor** [comment]
Remove db_dir_MyData or rename.  It was a bug previously to have made that folder.  Likely safe to remove since just purely for ephemeral use when was made.

**Comment by a3nima** [comment]
Thanks, it worked!
