### ISSUE TITLE
 Jetson orin agx 

### ISSUE THREAD

**Issue by MrBrabus75** [h2oai/h2ogpt#908]
Hello,

its possible to install it on Jetson orin agx ? (its nvidia tpu) ubuntu aarch64 (arm64) ?

if yes, can you explain me how ??

thanks you

**Comment by pseudotensor** [comment]
I'd guess it's possible to follow full install for linux and it would work, but some changes will be needed to support torch with TPU. Right now it's only cuda, CPU, or MPS.  I think AMD is not hard either, but it's not added.

If you make a PR we'd add it.

**Comment by MrBrabus75** [comment]
Hello, how can I make a PR so that my request to get H2O working on Jetson AGX Orin with this version of PyTorch is considered?

Pytorch version : https://developer.download.nvidia.cn/compute/redist/jp/v511/pytorch/torch-2.0.0+nv23.05-cp38-cp38-linux_aarch64.whl

**Comment by pseudotensor** [comment]
Hi, it's unclear what needs to be done, but torch version should already be handled by pip install.  However, what I mentioned above is that h2oGPT only at moment allows for cuda, CPU, or MPS when making decisions about parameters or when checking the device used.  It's probably not hard to extend, but I have to fix other things.

**Comment by MrBrabus75** [comment]
@pseudotensor 

I apologize if I wasn't clear earlier. To summarize:

    I'm trying to install H2OGPT on an NVIDIA Jetson AGX Orin.
    This device operates on Ubuntu 20.04 (tegra 5.10.120), which is an ARM64 version.
    The Jetson runs on Python 3.8, and I cannot upgrade to a newer version like Python 3.10 due to specific dependencies on this platform.
    It uses a specific version of PyTorch that requires Python 3.8 and is optimized for CUDA on this platform. You can find this version of PyTorch here: [PyTorch link](https://developer.download.nvidia.cn/compute/redist/jp/v511/pytorch/torch-2.0.0+nv23.05-cp38-cp38-linux_aarch64.whl).
    I aim to get guidance on making H2OGPT work with this particular PyTorch version and the Jetson.

Is it possible to add support for this configuration? If not, could you guide me through the necessary steps to extend the support on my own, such as creating a PR?

Thank you for your understanding.

**Comment by pseudotensor** [comment]
Hi no plans to support at moment unless someone from community adds it.  Thanks!

**Comment by bluciano212** [comment]
Hi MrBrabus75 , I read you are using Single Board Computer Jetson orin agx with ubuntu aarch64 (arm64).
I installed h2o localGPT for CPU on SBC Orange pi 5  Armbian 23.08.0-trunk jammy it's  aarch64 (arm64) also mine .
Orange pi 5 has a Rockchip RK3588S 8-core and NPU 6.0 TOPs , but actually on mine only CPU work
you can start with 

sudo apt-get install python3-pip
sudo apt-get install python3-dev
sudo apt-get install -y build-essential gcc
git clone https://github.com/h2oai/h2ogpt.git
cd h2ogpt
pip install -r requirements.txt
pip install -r reqs_optional/requirements_optional_langchain.txt
pip install -r reqs_optional/requirements_optional_gpt4all.txt
pip uninstall -y pandoc pypandoc pypandoc-binary
ip install -r requirements.txt --extra-index https://download.pytorch.org/whl/cpu
pip install pytest==7.3.1
pip install chromadb-0.4.13
pip install -r reqs_optional/requirements_optional_langchain.gpllike.txt
pip install -r reqs_optional/requirements_optional_langchain.urls.txt
sudo apt-get install -y libmagic-dev poppler-utils tesseract-ocr libtesseract-dev libreoffice

pip install tensorflow  (please note a user suggested me to install this framework for accessing the NPU ,but no clue the NPU is working , maybe in your Jetson will work) 

pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir

I do trial and error , anyway during all trials I did not brick my orange pi 5

**Comment by bluciano212** [comment]
how much RAM has your Jetson orin agx ?
