### ISSUE TITLE
configure the serper api key? help help help 🐤 

### ISSUE THREAD

**Issue by zephirusgit** [h2oai/h2ogpt#914]
Does anyone know how to configure the serper api key? I saw that it has the option to search the internet using Google, with the serper api key that allows you to use 2500 requests for free.
I saw that I got the error message that it was not configured,
I registered on the page to get an API
https://serper.dev
I generated an api, registering,
I tested the api in python and it worked fine.
look in the files where the serpapi_api_key was
and I found it in the file called gpt_langchain.py

 if LangChainAgent.SEARCH.value in langchain_agents:
        output_parser = H2OMRKLOutputParser()

###############################################original say ('SERPAPI_API_KEY'))
        tools = load_tools(["serpapi"], llm=llm, serpapi_api_key=os.environ.get('jsdjsdjdsjdsjsdjapi keyy herejhashsaishas'))

        if inference_server.startswith('openai'):
            agent_type = AgentType.OPENAI_FUNCTIONS
            agent_executor_kwargs = {"handle_parsing_errors": True, 'output_parser': output_parser}
        else:
            agent_type = AgentType.ZERO_SHOT_REACT_DESCRIPTION
            agent_executor_kwargs = {'output_parser': output_parser}
        chain = initialize_agent(tools, llm, agent=agent_type,
                                 agent_executor_kwargs=agent_executor_kwargs,
                                 agent_kwargs=dict(output_parser=output_parser,
                                                   format_instructions=output_parser.get_format_instructions()),
                                 output_parser=output_parser,
                                 max_iterations=10,
                                 verbose=True)
           
                      I saved it and everything but nothing, it still gives an error with everything, it doesn't even launch the chat, because it tries to search first.
                      
                      In the console I can see that it is still not seen
                                 
     File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for H2OSerpAPIWrapper
__root__
  Did not find serpapi_api_key, please add an environment variable `SERPAPI_API_KEY` which contains it, or pass  `serpapi_api_key` as a named parameter. (type=value_error)

**Comment by zephirusgit** [comment]
I tried the example in python and it works, but I don't see it even close to the python source code, enough to understand the error, and I don't understand much about python to adapt it, (the api key not is my api key :p)

import http.client
import json

conn = http.client.HTTPSConnection("google.serper.dev")
payload = json.dumps({
  "q": "here the search"
})
headers = {
  'X-API-KEY': '4323234apiapiapi424',
  'Content-Type': 'application/json'
}
conn.request("POST", "/search", payload, headers)
res = conn.getresponse()
data = res.read()
print(data.decode("utf-8"))

**Comment by zephirusgit** [comment]
I'm going to try the Windows version, although I was running it in PowerShell, the one on GitHub

**Comment by zephirusgit** [comment]
![search](https://github.com/h2oai/h2ogpt/assets/20031912/12943ab5-9912-4096-ad8c-65b4a751a80e)
omg not have the web search option! 😵‍💫 can add it, and the ask from the api key?¿?

**Comment by pseudotensor** [comment]
My documentation is behind on the new experimental features.

But you just need to have an ENV that defines: `SERPAPI_API_KEY` and get the key from https://serpapi.com/ .  They have free number of searches as well.

The windows one-click installer is behind.  I'll update its release in next few days.

**Comment by PiPlusTheta** [comment]
![WhatsApp Image 2024-04-11 at 17 43 14_e4765d04](https://github.com/h2oai/h2ogpt/assets/68808227/035a85db-5ad1-4c70-8a2e-b57ce6951e09)

I encountered an issue while attempting to perform web searches using the SerpApi package. Despite setting the SERPAPI_API_KEY environment variable with the appropriate API key value as instructed, I'm still unable to execute web searches successfully.

![image](https://github.com/h2oai/h2ogpt/assets/68808227/143016d8-43e3-4385-9693-bb7d1a735a0f)


Steps to Reproduce:

    Set the SERPAPI_API_KEY environment variable with the correct API key value.
    Attempt to perform a web search using the SerpApi package.
    Observe the validation error message: "Did not find serpapi_api_key, please add an environment variable SERPAPI_API_KEY which contains it, or pass serpapi_api_key as a named parameter."

Expected Behavior:
After setting the SERPAPI_API_KEY environment variable, I expect to be able to perform web searches using the SerpApi package without encountering validation errors.

Actual Behavior:
Despite setting the SERPAPI_API_KEY environment variable, the validation error persists, preventing me from executing web searches.

**Comment by pseudotensor** [comment]
Hi, I'm not sure what's wrong.  I have to believe that the envs you are setting are not being seen by h2oGPT.

It works fine for me to export the env:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/88374d35-5f90-41b2-9e97-73131f52807e)

**Comment by PiPlusTheta** [comment]
I tried exporting the key from the environment and running search queries using the key in a different Python file, and it worked without any issues. But it's not working in H2oGPT.

**Comment by pseudotensor** [comment]
Not sure what is wrong.  It can't be just h2oGPT since it works for me.  Also, one can't even choose the web search option if gradio_runner.py doesn't see the key.

I tried just all on single command line, both with and without the key, and I always get the expected behavior.

Are you running via docker or directly in python?

**Comment by PiPlusTheta** [comment]
I'm directly running it in python. still no luck.
