### ISSUE TITLE
max_new_tokens & max_max_new_tokens are having no effect on the UI

### ISSUE THREAD

**Issue by MSZ-MGS** [h2oai/h2ogpt#915]
Hi,

I have notices that both parameters max_new_tokens & max_max_new_tokens are not reflected on the UI.
I am using llama cpp.

**Comment by pseudotensor** [comment]
```
python generate.py --base_model='llama' --score_model=None --max_new_tokens=777 --max_max_new_tokens=1043
```

gives in UI:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/ada75d8f-c043-4cd8-a1f1-5c57b553dd46)


![image](https://github.com/h2oai/h2ogpt/assets/2249614/6c5f4c48-01a6-4bd7-84c7-4ea3bd2af8b2)


So things seem to work fine.

**Comment by MSZ-MGS** [comment]
I'll re-install all the requirements again, probably installation issue.

Thanks

**Comment by MSZ-MGS** [comment]
I have re-installed all requirements, still same issues.
This is the command I am doing:
generate.py --base_model='llama' --model_path_llama=AddedModels\llama-2-7b-32k-instruct\llama-2-7b-32k-instruct.Q5_K_M.gguf --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=user_path --llamacpp_dict="{'n_gpu_layers':20,'n_batch':128}" --do_sample=True --top_k_docs=-1 --temperature=0.7 --top_p=0.9 --max_seq_len=16384 --max_new_tokens=8000 --max_max_new_tokens=15000 --repetition_penalty=1.1 --share=False

**Comment by pseudotensor** [comment]
When you say they have no effect, what do you mean exactly?  I showed how they change the UI, I presume that is happening for you?  Or do you mean you expect the model to generate longer responses, but they are still short?  Or do you mean the responses are truncated?  etc.

**Comment by MSZ-MGS** [comment]
> When you say they have no effect, what do you mean exactly? I showed how they change the UI, I presume that is happening for you? Or do you mean you expect the model to generate longer responses, but they are still short? Or do you mean the responses are truncated? etc.

The command:
`python generate.py --base_model='llama' --model_path_llama=AddedModels\llama-2-7b-32k-instruct\llama-2-7b-32k-instruct.Q5_K_M.gguf --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=user_path --llamacpp_dict="{'n_gpu_layers':20,'n_batch':128}" --do_sample=True --top_k_docs=-1 --temperature=0.7 --top_p=0.9 --max_seq_len=16384 --max_new_tokens=4096 --max_max_new_tokens=5000 --repetition_penalty=1.1 --share=False`

![image](https://github.com/h2oai/h2ogpt/assets/65172063/2cd5327c-5333-4ea4-89b4-801aefc1ab0b)

**Comment by pseudotensor** [comment]
Thanks, fixed

**Comment by MSZ-MGS** [comment]
Confirmed,

Thanks
