### ISSUE TITLE
Falcon-180b removed from https://gpt.h2o.ai/?

### ISSUE THREAD

**Issue by kiwipunch** [h2oai/h2ogpt#917]
Hello, 

The Falcon-180b model seems to have been removed from the list of models at https://gpt.h2o.ai/ (Llama, GPT are still available) I am wondering if there had been a problem with the model and that's why it's been removed from the list.

**Comment by pseudotensor** [comment]
The provider we used took away our A100s and requires reservations etc. now.  Falcon180 was not great performer for chat, so we don't consider it a significant loss.

**Comment by pseudotensor** [comment]
Preliminary eval: 

@srini-x plans to add to https://evalgpt.ai/ soon.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/f287b604-af32-4744-a55d-f60b986f2abc)
