### ISSUE TITLE
Getting error in gpt_langchain.py

### ISSUE THREAD

**Issue by imvijith** [h2oai/h2ogpt#918]
gpt_langchain.py", line 3259, in <dictcomp>
    metadata_hash_ids = {os.path.normpath(x['source']): x.get('hashid') for x in metadatas}
gpt_langchain.py", line 3259, in get_existing_hash_ids
    metadata_hash_ids = {os.path.normpath(x['source']): x.get('hashid') for x in metadatas}
gpt_langchain.py", line 3068, in _make_db
    existing_hash_ids = get_existing_hash_ids(db)
fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^

/gen.py", line 1056, in main
    db = prep_langchain(persist_directory1,
generate.py", line 16, in <module>
    entrypoint_main()
generate.py", line 12, in entrypoint_main
    H2O_Fire(main)

Any Idea why I am getting this error?
This is what I am doing and trying to use bunch of pdf to summarize the content(stored in path to doc with pdf).

python generate.py --base_model='llama' --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path='path to doc with pdf'

Using Model llama
Exception occurred invoking consumer for subscription 4691750658df491d82aaeebb0cc11721to topic persistent://default/default/36390129-b0df-4b17-a7b0-a25d0b846b56 'utf-8' codec can't encode character '\ud835' in position 67: surrogates not allowed

Also got this exception first time I ran this? Anything I am missing? just following the MAC_OS starter guide>

**Comment by pseudotensor** [comment]
I'm not sure the order of your message.  You have:
* stack trace
* comment on why error, but no error is seen
* command
* error from llama

So I can't quite follow.

As far as this:
```
Exception occurred invoking consumer for subscription 4691750658df491d82aaeebb0cc11721to topic persistent://default/default/36390129-b0df-4b17-a7b0-a25d0b846b56 'utf-8' codec can't encode character '\ud835' in position 67: surrogates not allowed
```

Seems like an issue with llama.cpp handling of special characters.

**Comment by imvijith** [comment]
@pseudotensor 
Here is the call stack and error is at the end. Trying to use llama with my own dataset in pdf format.

python generate.py --base_model='llama' --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path='/Users/Desktop/dataset'
Using Model llama
Traceback (most recent call last):
  File "h2ogpt/generate.py", line 16, in <module>
    entrypoint_main()
  File "h2ogpt/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "h2ogpt/src/utils.py", line 64, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "h2ogpt/src/gen.py", line 1056, in main
    db = prep_langchain(persist_directory1,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h2ogpt/src/gpt_langchain.py", line 2613, in prep_langchain
    db, num_new_sources, new_sources_metadata = make_db(**langchain_kwargs)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h2ogpt/src/gpt_langchain.py", line 2838, in make_db
    return _make_db(**langchain_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h2ogpt/src/gpt_langchain.py", line 3068, in _make_db
    existing_hash_ids = get_existing_hash_ids(db)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h2ogpt/src/gpt_langchain.py", line 3259, in get_existing_hash_ids
    metadata_hash_ids = {os.path.normpath(x['source']): x.get('hashid') for x in metadatas}
                        
  File "/h2ogpt/src/gpt_langchain.py", line 3259, in <dictcomp>
    metadata_hash_ids = {os.path.normpath(x['source']): x.get('hashid') for x in metadatas}

TypeError: 'NoneType' object is not subscriptable
