### ISSUE TITLE
Error with the model `lmsys/vicuna-13b-v1.5-16k`

### ISSUE THREAD

**Issue by RohanKaran** [h2oai/h2ogpt#926]
`python generate.py --base_model=lmsys/vicuna-13b-v1.5-16k --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --load_8bit=True --langchain_mode=UserData --user_path=user_path --prompt_type=vicuna11 --h2ocolors=False`
Output: "Based on the information in the document document document document ...". It gets stuck on one word.
No actual error is thrown in log.

**Comment by pseudotensor** [comment]
I see similar things.  It's just not a good model.  It's trying to be good at long context, but it just fails to do so in real situations.

Even when one leaves the --max_seq_len unset and so default is used of 2048, I get stuff like this:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/e612d875-66b6-42a4-a72a-39eb6629eaab)

**Comment by pseudotensor** [comment]
By comparison, the original model does fine:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/dbdeb20d-d71a-46ad-afb1-94b039217b70)
