### ISSUE TITLE
Prompt Template

### ISSUE THREAD

**Issue by MSZ-MGS** [h2oai/h2ogpt#931]
More explanation is required for the meaning of the parameters:
promptA
promptB
PreInstruct
PreInput
PreResponse
terminate_response
chat_sep
chat_turn_sep
humanstr
botstr

i.e. for the Llm https://huggingface.co/TheBloke/Llama-2-7B-32K-Instruct-GGML
The template is:
`[INST]
{prompt}
[\INST]`

Example of clarifications:
How this will be substituted in the parameters above?
Which parameters except empty input like  ''  and which one required values like None, True etc... ?
For those parameters not used, can they be removed?.

**Comment by pseudotensor** [comment]
Did you review https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#adding-prompt-templates ?

**Comment by gabriead** [comment]
How does the prompt look like if I upload a document and ask a question about the context?

**Comment by pseudotensor** [comment]
The above LLM stuff is just handling of the LLM's needs.  The question for document has additional prompting for that, for query/summary it looks like: 

https://github.com/h2oai/h2ogpt/blob/2e7a68d0abcd5e690bf52a8b45655a2c37c261e4/src/enums.py#L175-L203

overall template:

https://github.com/h2oai/h2ogpt/blob/b2929fd7072f01af59e837f2165e546ecc6a97e4/docs/README_CLIENT.md#L257-L264
