### ISSUE TITLE
Disabling GPU on h2oGPT GPU-CUDA Installer

### ISSUE THREAD

**Issue by DjToMeK30** [h2oai/h2ogpt#934]
I installed GPU windows version

Can I somehow disable GPU, because I can't run even 3b models on my 6GB Nvidia when uploading custom documents

Do I need to install CPU version or is there some setting to disable running on GPU in GPU version?

Thanks!

**Comment by pseudotensor** [comment]
You can set the env CUDA_VISIBLE_DEVICES=

I.e. to empty string.  And cuda will be avoided.  See readme.md for other envs one can set for windows installer.
