### ISSUE TITLE
Virus Alert in Download: Wacatac.B@ml

### ISSUE THREAD

**Issue by Luckysin13** [h2oai/h2ogpt#937]
This [link ](https://h2o-release.s3.amazonaws.com/h2ogpt/Oct2023/h2oGPT_0.0.1_gpu.exe)contained the file with the virus.

![image](https://github.com/h2oai/h2ogpt/assets/41127191/4866cb0a-d9e6-4cb6-8371-2d149a8ae20d)

**Comment by pseudotensor** [comment]
I seriously doubt, has to be false positive.  You can see posts about how to confirm:

https://answers.microsoft.com/en-us/windows/forum/all/how-can-i-know-if-wacatacbml-is-a-false-positive/33107e01-d390-4579-aa94-625a3402d26a

**Comment by pseudotensor** [comment]
![image](https://github.com/h2oai/h2ogpt/assets/2249614/20baa651-56bc-4031-b90b-4ffc0144cc9d)

**Comment by elsatch** [comment]
Even though I don't have such detailed information as @Luckysin13, I confirm that Microsoft Defender labels the file as infected with a virus. This happens only with the October one-click install. Once the virus is detected, the installer is deleted from the folder. This behavior doesn't happen with the August release.

Here is a screenshot of the downloads menu from Brave browser. As you can see, original file was removed, and the October version (downloaded again) was labeled as containing a virus. 

<img width="201" alt="1x68CYr66b" src="https://github.com/h2oai/h2ogpt/assets/653433/bd6760d9-ffbd-40e3-910a-6e39bc5d4e8e">

At all efects, the GPU version of the installer is not working, as it won't be able to install the software on any Windows system having Microsoft Defender enabled. This protection It is enabled by default in Windowd 10/11 machines.

**Comment by pseudotensor** [comment]
I have windows defender on my windows machine where it was built and installed and nothing was detected.  Not sure how to fix, as I highly doubt actually there is any virus.

**Comment by elsatch** [comment]
Thanks for your fast response.

I installed the October version without GPU support in another machine with
no issues. So both of us had problems only with the GPU version.

So maybe there is an issue with any of the upstream packages needed for the
GPU support. I totally agree that if you built and installed it into a
machine with Defender, it should have warn you somehow. But maybe our local
configurations are different.

I will double check the logs tomorrow, trying to offer some additional
insights. In the mean time, maybe you could get in touch with other
frequent contributors so they could double check it too.

**Comment by pseudotensor** [comment]
I looked at online scanners, but they only take up to 1GB files.  Linux scanner shows nothing, as I showed.  I'll check in windows a bit later.

Thanks for any insights.  I think the .exe file is basically a compressed file, and one should be able to scan the contents to see which individual file is the issue.

**Comment by elsatch** [comment]
I have checked VirusTotal using the URL of the file and it returns a clean status. I have been able to download both files in my Linux machine and extract the content of the October files. Then I copied the files back to my computer and did a manual scan using Windows Defender. No threats were detected in the decompressed exe folder. 

I ran later on a full computer scan, having the uncompressed exe files in one of the drives and no problem was reported.

Checking other repositories and issues like [Blender Launcher](https://github.com/DotBow/Blender-Launcher/issues/43), it seems this error might be related to pyinstaller being used to create some malicious programs. In their case, they reported the false positive to Microsoft and it wasn't flagged with the new virus signature files.

**Comment by sanyaade-projects** [comment]
> Even though I don't have such detailed information as @Luckysin13, I confirm that Microsoft Defender labels the file as infected with a virus. This happens only with the October one-click install. Once the virus is detected, the installer is deleted from the folder. This behavior doesn't happen with the August release.
> 
> Here is a screenshot of the downloads menu from Brave browser. As you can see, original file was removed, and the October version (downloaded again) was labeled as containing a virus.
> 
> <img alt="1x68CYr66b" width="201" src="https://user-images.githubusercontent.com/653433/273766257-bd6760d9-ffbd-40e3-910a-6e39bc5d4e8e.png">
> At all efects, the GPU version of the installer is not working, as it won't be able to install the software on any Windows system having Microsoft Defender enabled. This protection It is enabled by default in Windowd 10/11 machines.

Do you really need anti-virus on development platform/machine?
Any software CI/CD will need to access systems files, modifies libraries, load DLLs, etc... even access ring 0 if it needs. Hence you can turn off your Anti-virus during compilation/builds and turn it on again. Most anti-virus have sentinel built-in to monitor activities.

God blesses!!!

Regards
