### ISSUE TITLE
show_copy_button in both query and response of chat interface

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2ogpt#942]
I pass `show_copy_button=True` which  show copy button for chatbots in the gen.py file and also pass it in the generation command:  `python generate.py --base_model=meta-llama/Llama-2-13b-chat-hf  --score_model=None --langchain_mode='UserData' --user_path=user_path --use_auth_token=True --max_seq_len=4096 --max_max_new_tokens=2048 --show_copy_button=True `

But when asking query then it doesn't show any copy button icon in the chatbot interface.
Please help me to enable copy button in chat interface just like the following screenshot or like h2ogpt interface.

[
![Screenshot from 2023-10-11 12-44-31](https://github.com/h2oai/h2ogpt/assets/137979399/4adc0bbd-3680-4a47-96c5-19cd28051cff)
](url)

**Comment by llmwesee** [comment]
I enabled the show_copy_button by set forcefully show_copy_button=True in the
 `with gr.Row():
        text_output = gr.Chatbot(label=output_label0, visible=not kwargs['model_lock'], show_copy_button=True, sanitize_html=False, render_markdown=True,  height=kwargs['height'] or 400)
        text_output2 = gr.Chatbot(label=output_label0_model2,
                                  visible=False and not kwargs['model_lock'], show_copy_button=True, sanitize_html=False, render_markdown=True, height=kwargs['height'] or 400)
    return text_output, text_output2, text_outputs` 
in the prompt_form.py file but the problem is when asking from the userdata and copy the response it copy the metadata also like `<details><summary><font size="2">Sources</font></summary><font size="2"><font size="2">Sources [Score | Link]:<ul></font><font size="2"><li>0.65 | <font size="2"><a`

So I wanna help regarding there are any solution for just copying the response only not metadata?

**Comment by pseudotensor** [comment]
Hi, I'm not quite clear on the issue.  You want copy-paste, but we enable that by default.  I see in image above the copy-paste button, so what is it you are missing?

**Comment by llmwesee** [comment]
I am seeking a solution to extract and copy query responses from "userdata" or "mydata" while excluding the associated metadata. The goal is to paste the response into a text or other file while omitting any metadata information. Is there a method available for achieving this specific task?

**Comment by pseudotensor** [comment]
Hi, the original issues is fixed now w.r.t. copy button.  The non-model-lock case didn't pass those options into the chatbot, thanks!

cea4d69fd7553812cf50887d72837d3d68dd442c

**Comment by pseudotensor** [comment]
Ah, response but no meta data.  Then you'll have to avoid showing the metadata with:
```
--answer_with_sources=False --append_sources_to_answer=False --show_link_in_sources=False
```
