### ISSUE TITLE
TypeError: 'Textbox' object is not iterable

### ISSUE THREAD

**Issue by Afo92** [h2oai/h2ogpt#947]
Since I cloned the main today, I'm getting this error message with using the UI `TypeError: 'Textbox' object is not iterable`
See the sequence to the error.

1. I type a prompt

![h2oGPT-Error1-ScreenShot01](https://github.com/h2oai/h2ogpt/assets/99554069/8cd3022b-92a8-4d58-8b24-8a7f9d356da9)

2. when I hit Enter "textbox" appears in the prompt row, which i did not type

![h2oGPT-Error1-ScreenShot02](https://github.com/h2oai/h2ogpt/assets/99554069/cdb286a7-7365-4f4c-bb09-fd2b53ed19b5)

3. event so I delete the "textbox" from the prompt and add a new prompt, when I hit enter, "textbox" is getting added both to the prompt field and to the prompt in the chat widow. 

![h2oGPT-Error1-ScreenShot03](https://github.com/h2oai/h2ogpt/assets/99554069/b31be95a-45ca-4a30-b128-9d754e1be7be)

4.  when I click the Clear button I'm getting this error and the clear is not done

![h2oGPT-Error1-ScreenShot04](https://github.com/h2oai/h2ogpt/assets/99554069/d1ba8b69-39c2-48db-8b5c-b35cd7bcced0)

I wonder whether it coule be something in my setup or something in the lastest updates.
Anyone has these issues with recent updates of h2ogpt?

**Comment by pseudotensor** [comment]
I ran llama model and had it say something and then hit clear and didn't see an error, it cleared properly.

**Comment by pseudotensor** [comment]
Thanks.   I guess gradio team made some breaking changes.
