### ISSUE TITLE
Use Client API with Langchain UserData Mode?

### ISSUE THREAD

**Issue by Keykubat60** [h2oai/h2ogpt#949]
Hello,

I am interested in using h2oGPT for a chatbot application that leverages the Client API. I noticed that the Client API primarily supports basic chat functionalities. Is it possible to use the Client API in conjunction with LangChain's UserData mode for more advanced features like document-based chatting?

**Comment by pseudotensor** [comment]
Yes, review the https://github.com/h2oai/h2ogpt/blob/main/docs/README_CLIENT.md including large block there for a piece of code one can use to get upload + question.

More broadly, API calls for all doc related pieces etc. are tested in https://github.com/h2oai/h2ogpt/blob/main/tests/test_client_calls.py

e.g. see the test_client_chat_stream_langchain_steps3 test
