### ISSUE TITLE
Feature request: open browser.

### ISSUE THREAD

**Issue by MSZ-MGS** [h2oai/h2ogpt#953]
Please make the browser open automatically when the llm loaded.
This will help in reducing some steps e.g. opening the browser, writing adress etc...

If that interrupt something, it maigh be sent part of the llm launch parameters e.g. --Autoopenbrowser=True

Thanks...

**Comment by pseudotensor** [comment]
Done, like:
```
python generate.py --open_browser
```

**Comment by MSZ-MGS** [comment]
It worked flawlessly... Thank you!
