### ISSUE TITLE
give the response in one shot and enable copy resposne text

### ISSUE THREAD

**Issue by eslam-gomaa** [h2oai/h2ogpt#961]
Hi 
Thanks for the amazing project !

I have 2 questions:
1. How to let it give the response in one shot instead of waiting too much if the answer is long
2. and how to enable copying the response text

> The code has a copy button but the text not and can't be copied

**Comment by llmwesee** [comment]
I enabled the show_copy_button by set forcefully `show_copy_button=True `  in the
`with gr.Row(): text_output = gr.Chatbot(label=output_label0, visible=not kwargs['model_lock'], show_copy_button=True, sanitize_html=False, render_markdown=True,  height=kwargs['height'] or 400) text_output2 = gr.Chatbot(label=output_label0_model2, visible=False and not kwargs['model_lock'], show_copy_button=True, sanitize_html=False, render_markdown=True, height=kwargs['height'] or 400) return text_output, text_output2, text_outputs` in the **prompt_form.py** file.

**Comment by pseudotensor** [comment]
1. Not sure I know what you mean, please explain
2. I fixed prompt_form for no-model_lock case to have copy button by default.

**Comment by eslam-gomaa** [comment]
I was just looking to enable the copy button, and now it works
Thank you @pseudotensor
