### ISSUE TITLE
GPTQ llama2 model not working, please help

### ISSUE THREAD

**Issue by a3nima** [h2oai/h2ogpt#963]
https://huggingface.co/Xwin-LM/Xwin-LM-13B-V0.1

Im trying to run this model, but can not get it to give any answer except gibberish. Is it somehow not supported or what prompt type/setting do I need to get it working?

**Comment by pseudotensor** [comment]
From the prompt example: https://huggingface.co/Xwin-LM/Xwin-LM-13B-V0.1#huggingface-example

Looks identical to prompter.py's "wizard3" case.

But they are confusing in their page as they either have \n or </s> as separators.  I can't be sure what they intended.

But i added the specific one they mention for conversations -- i.e. prompt_type xwin.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/364cae2e-beae-49e2-a13c-ce670e6d2273)

**Comment by pseudotensor** [comment]
The model you reference is not GPTQ, but maybe you want to use that, and you can using load_gptq.  See docs.

**Comment by a3nima** [comment]
I'm sorry, I will edit the entry post as well, the model I ran with is:
https://huggingface.co/TheBloke/Xwin-LM-13B-V0.1-GPTQ

What I'm trying to run with my new install from yesterday night (have not downloaded the models yet ) will be version 0.2 awq or gptq (from thebloke) with the xwin model, this model has very high scores when tested against gpt and other :)

I guess your prompting tipp still stands for gptq and awq versions?

**Comment by pseudotensor** [comment]
The GPTQ version also works fine.  i earlier added it to FAQ.md:

```
CUDA_VISIBLE_DEVICES=0 python generate.py --base_model=TheBloke/Xwin-LM-13B-v0.2-GPTQ --load_gptq=model --use_safetensors=True --prompt_type=xwin --langchain_mode=UserData --score_model=None --share=False --gradio_offline_level=1 --gptq_dict="{'disable_exllama': True}"
```
