### ISSUE TITLE
start h2ogpt with multiple "Visible Models"

### ISSUE THREAD

**Issue by eslam-gomaa** [h2oai/h2ogpt#964]
How to start h2ogpt with multiple "Visible Models" with the `generate.py` on startup, similar to that example https://gpt.h2o.ai

**Comment by pseudotensor** [comment]
This is what we use for gpt.h2o.ai.  So "vis" is list of models to choose from and we export that string to bash, and "$MODEL_LOCK" is bash variable for the list of dicts of models.

```
export vis="['h2oai/h2ogpt-4096-llama2-70b-chat','h2oai/h2ogpt-4096-llama2-13b-chat','HuggingFaceH4/zephyr-7b-alpha','gpt-3.5-turbo-0613']"
python generate.py --save_dir=saveall_gpt --model_lock="$MODEL_LOCK" --model_lock_columns=3 --auth_filename=all_auth.json --gradio_size=small --height=400 --score_model=None --max_max_new_tokens=2048 --max_new_tokens=1024 --visible_models="$vis" &>> logs.all.gradio_chat.txt &
```

For details on model lock see: https://github.com/h2oai/h2ogpt/blob/main/docs/README_InferenceServers.md#locking-models-for-easy-start-up-or-in-app-comparison
