### ISSUE TITLE
protobuf error

### ISSUE THREAD

**Issue by a3nima** [h2oai/h2ogpt#965]
Today my h2ogpt did not start but instead presented me an error:

Using Model thebloke/xwin-lm-13b-v0.2-gptq
Starting get_model: TheBloke/Xwin-LM-13B-v0.2-GPTQ
bin e:\TEXT-AI\venv\h2ogpt\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ E:\TEXT-AI\h2ogpt\generate.py:16 in <module>                                                     │
│                                                                                                  │
│   13                                                                                             │
│   14                                                                                             │
│   15 if __name__ == "__main__":                                                                  │
│ ❱ 16 │   entrypoint_main()                                                                       │
│   17                                                                                             │
│                                                                                                  │
│ E:\TEXT-AI\h2ogpt\generate.py:12 in entrypoint_main                                              │
│                                                                                                  │
│    9                                                                                             │
│   10                                                                                             │
│   11 def entrypoint_main():                                                                      │
│ ❱ 12 │   H2O_Fire(main)                                                                          │
│   13                                                                                             │
│   14                                                                                             │
│   15 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ E:\TEXT-AI\h2ogpt\src\utils.py:64 in H2O_Fire                                                    │
│                                                                                                  │
│     61 │   │                                                                                     │
│     62 │   │   args.append(f"--{new_key}={value}")                                               │
│     63 │                                                                                         │
│ ❱   64 │   fire.Fire(component=component, command=args)                                          │
│     65                                                                                           │
│     66                                                                                           │
│     67 def set_seed(seed: int):                                                                  │
│                                                                                                  │
│ e:\TEXT-AI\venv\h2ogpt\lib\site-packages\fire\core.py:141 in Fire                                │
│                                                                                                  │
│   138 │   context.update(caller_globals)                                                         │
│   139 │   context.update(caller_locals)                                                          │
│   140                                                                                            │
│ ❱ 141   component_trace = _Fire(component, args, parsed_flag_args, context, name)                │
│   142                                                                                            │
│   143   if component_trace.HasError():                                                           │
│   144 │   _DisplayError(component_trace)                                                         │
│                                                                                                  │
│ e:\TEXT-AI\venv\h2ogpt\lib\site-packages\fire\core.py:475 in _Fire                               │
│                                                                                                  │
│   472 │     is_class = inspect.isclass(component)                                                │
│   473 │                                                                                          │
│   474 │     try:                                                                                 │
│ ❱ 475 │   │   component, remaining_args = _CallAndUpdateTrace(                                   │
│   476 │   │   │   component,                                                                     │
│   477 │   │   │   remaining_args,                                                                │
│   478 │   │   │   component_trace,                                                               │
│                                                                                                  │
│ e:\TEXT-AI\venv\h2ogpt\lib\site-packages\fire\core.py:691 in _CallAndUpdateTrace                 │
│                                                                                                  │
│   688 │   loop = asyncio.get_event_loop()                                                        │
│   689 │   component = loop.run_until_complete(fn(*varargs, **kwargs))                            │
│   690   else:                                                                                    │
│ ❱ 691 │   component = fn(*varargs, **kwargs)                                                     │
│   692                                                                                            │
│   693   if treatment == 'class':                                                                 │
│   694 │   action = trace.INSTANTIATED_CLASS                                                      │
│                                                                                                  │
│ E:\TEXT-AI\h2ogpt\src\gen.py:1260 in main                                                        │
│                                                                                                  │
│   1257 │   │   │   all_kwargs = locals().copy()                                                  │
│   1258 │   │   │   all_kwargs.update(model_dict)                                                 │
│   1259 │   │   │   if model_dict['base_model'] and not login_mode_if_model0:                     │
│ ❱ 1260 │   │   │   │   model0, tokenizer0, device = get_model(reward_type=False,                 │
│   1261 │   │   │   │   │   │   │   │   │   │   │   │   │      **get_kwargs(get_model, exclude_n  │
│   1262 │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   **all_kwargs))        │
│   1263 │   │   │   else:                                                                         │
│                                                                                                  │
│ E:\TEXT-AI\h2ogpt\src\gen.py:1714 in get_model                                                   │
│                                                                                                  │
│   1711 │   │   if load_exllama:                                                                  │
│   1712 │   │   │   tokenizer = tokenizer_loader                                                  │
│   1713 │   │   else:                                                                             │
│ ❱ 1714 │   │   │   tokenizer = tokenizer_loader.from_pretrained(tokenizer_base_model, **tokeniz  │
│   1715 │   │   │   # sets raw (no cushion) limit                                                 │
│   1716 │   │   │   # If using RoPE with scaling, then for non-exllama models (e.g. HF models),   │
│   1717 │   │   │   #  then config -> tokenizer will set model_max_length correctly               │
│                                                                                                  │
│ e:\TEXT-AI\venv\h2ogpt\lib\site-packages\transformers\models\auto\tokenization_auto.py:691 in    │
│ from_pretrained                                                                                  │
│                                                                                                  │
│   688 │   │   │   │   raise ValueError(                                                          │
│   689 │   │   │   │   │   f"Tokenizer class {tokenizer_class_candidate} does not exist or is n   │
│   690 │   │   │   │   )                                                                          │
│ ❱ 691 │   │   │   return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *input   │
│   692 │   │                                                                                      │
│   693 │   │   # Otherwise we have to be creative.                                                │
│   694 │   │   # if model is an encoder decoder, the encoder tokenizer class is used by default   │
│                                                                                                  │
│ e:\TEXT-AI\venv\h2ogpt\lib\site-packages\transformers\tokenization_utils_base.py:1825 in         │
│ from_pretrained                                                                                  │
│                                                                                                  │
│   1822 │   │   │   else:                                                                         │
│   1823 │   │   │   │   logger.info(f"loading file {file_path} from cache at {resolved_vocab_fil  │
│   1824 │   │                                                                                     │
│ ❱ 1825 │   │   return cls._from_pretrained(                                                      │
│   1826 │   │   │   resolved_vocab_files,                                                         │
│   1827 │   │   │   pretrained_model_name_or_path,                                                │
│   1828 │   │   │   init_configuration,                                                           │
│                                                                                                  │
│ e:\TEXT-AI\venv\h2ogpt\lib\site-packages\transformers\tokenization_utils_base.py:1988 in         │
│ _from_pretrained                                                                                 │
│                                                                                                  │
│   1985 │   │                                                                                     │
│   1986 │   │   # Instantiate tokenizer.                                                          │
│   1987 │   │   try:                                                                              │
│ ❱ 1988 │   │   │   tokenizer = cls(*init_inputs, **init_kwargs)                                  │
│   1989 │   │   except OSError:                                                                   │
│   1990 │   │   │   raise OSError(                                                                │
│   1991 │   │   │   │   "Unable to load vocabulary from file. "                                   │
│                                                                                                  │
│ e:\TEXT-AI\venv\h2ogpt\lib\site-packages\transformers\models\llama\tokenization_llama_fast.py:93 │
│ in __init__                                                                                      │
│                                                                                                  │
│    90 │   │   add_eos_token=False,                                                               │
│    91 │   │   **kwargs,                                                                          │
│    92 │   ):                                                                                     │
│ ❱  93 │   │   super().__init__(                                                                  │
│    94 │   │   │   vocab_file=vocab_file,                                                         │
│    95 │   │   │   tokenizer_file=tokenizer_file,                                                 │
│    96 │   │   │   clean_up_tokenization_spaces=clean_up_tokenization_spaces,                     │
│                                                                                                  │
│ e:\TEXT-AI\venv\h2ogpt\lib\site-packages\transformers\tokenization_utils_fast.py:114 in __init__ │
│                                                                                                  │
│   111 │   │   │   fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)                  │
│   112 │   │   elif slow_tokenizer is not None:                                                   │
│   113 │   │   │   # We need to convert a slow tokenizer to build the backend                     │
│ ❱ 114 │   │   │   fast_tokenizer = convert_slow_tokenizer(slow_tokenizer)                        │
│   115 │   │   elif self.slow_tokenizer_class is not None:                                        │
│   116 │   │   │   # We need to create and convert a slow tokenizer to build the backend          │
│   117 │   │   │   slow_tokenizer = self.slow_tokenizer_class(*args, **kwargs)                    │
│                                                                                                  │
│ e:\TEXT-AI\venv\h2ogpt\lib\site-packages\transformers\convert_slow_tokenizer.py:1307 in          │
│ convert_slow_tokenizer                                                                           │
│                                                                                                  │
│   1304 │                                                                                         │
│   1305 │   converter_class = SLOW_TO_FAST_CONVERTERS[tokenizer_class_name]                       │
│   1306 │                                                                                         │
│ ❱ 1307 │   return converter_class(transformer_tokenizer).converted()                             │
│   1308                                                                                           │
│                                                                                                  │
│ e:\TEXT-AI\venv\h2ogpt\lib\site-packages\transformers\convert_slow_tokenizer.py:445 in __init__  │
│                                                                                                  │
│    442 │   │                                                                                     │
│    443 │   │   super().__init__(*args)                                                           │
│    444 │   │                                                                                     │
│ ❱  445 │   │   from .utils import sentencepiece_model_pb2 as model_pb2                           │
│    446 │   │                                                                                     │
│    447 │   │   m = model_pb2.ModelProto()                                                        │
│    448 │   │   with open(self.original_tokenizer.vocab_file, "rb") as f:                         │
│                                                                                                  │
│ e:\TEXT-AI\venv\h2ogpt\lib\site-packages\transformers\utils\sentencepiece_model_pb2.py:91 in     │
│ <module>                                                                                         │
│                                                                                                  │
│     88 │   file=DESCRIPTOR,                                                                      │
│     89 │   create_key=_descriptor._internal_create_key,                                          │
│     90 │   values=[                                                                              │
│ ❱   91 │   │   _descriptor.EnumValueDescriptor(                                                  │
│     92 │   │   │   name="UNIGRAM",                                                               │
│     93 │   │   │   index=0,                                                                      │
│     94 │   │   │   number=1,                                                                     │
│                                                                                                  │
│ e:\TEXT-AI\venv\h2ogpt\lib\site-packages\google\protobuf\descriptor.py:796 in __new__            │
│                                                                                                  │
│    793 │   def __new__(cls, name, index, number,                                                 │
│    794 │   │   │   │   type=None,  # pylint: disable=redefined-builtin                           │
│    795 │   │   │   │   options=None, serialized_options=None, create_key=None):                  │
│ ❱  796 │     _message.Message._CheckCalledFromGeneratedFile()                                    │
│    797 │     # There is no way we can build a complete EnumValueDescriptor with the              │
│    798 │     # given parameters (the name of the Enum is not known, for example).                │
│    799 │     # Fortunately generated files just pass it to the EnumDescriptor()                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by pseudotensor** [comment]
```
If you see an error about protobuf, try:

pip install protobuf==3.20.0
```
https://github.com/h2oai/h2ogpt/blob/main/docs/README_LINUX.md#run

LMK

**Comment by a3nima** [comment]
with protobuf 3.20.0 nothing the starting process got stuck at 
`bin e:\TEXT-AI\venv\h2ogpt\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll`
and nothing happened afterwards (no log either).

**Comment by pseudotensor** [comment]
Ok LMK.

**Comment by a3nima** [comment]
`Already up to date.
No GPUs detected
Using Model thebloke/xwin-lm-13b-v0.2-gptq
Starting get_model: TheBloke/Xwin-LM-13B-v0.2-GPTQ
e:\TEXT-AI\venv\h2ogpt\lib\site-packages\transformers\models\auto\configuration_auto.py:1020: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
e:\TEXT-AI\venv\h2ogpt\lib\site-packages\transformers\tokenization_utils_base.py:1917: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
e:\TEXT-AI\venv\h2ogpt\lib\site-packages\transformers\modeling_utils.py:2478: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
Traceback (most recent call last):
  File "E:\TEXT-AI\h2ogpt\generate.py", line 16, in <module>
    entrypoint_main()
  File "E:\TEXT-AI\h2ogpt\generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "E:\TEXT-AI\h2ogpt\src\utils.py", line 64, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "e:\TEXT-AI\venv\h2ogpt\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "e:\TEXT-AI\venv\h2ogpt\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "e:\TEXT-AI\venv\h2ogpt\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "E:\TEXT-AI\h2ogpt\src\gen.py", line 1260, in main
    model0, tokenizer0, device = get_model(reward_type=False,
  File "E:\TEXT-AI\h2ogpt\src\gen.py", line 1782, in get_model
    return get_hf_model(load_8bit=load_8bit,
  File "E:\TEXT-AI\h2ogpt\src\gen.py", line 1998, in get_hf_model
    model = model_loader(
  File "e:\TEXT-AI\venv\h2ogpt\lib\site-packages\transformers\modeling_utils.py", line 2702, in from_pretrained
    raise RuntimeError("GPU is required to quantize or run quantize model.")
RuntimeError: GPU is required to quantize or run quantize model.`

started with
`python generate.py --base_model=TheBloke/Xwin-LM-13B-v0.2-GPTQ --load_gptq=model --use_safetensors=True --prompt_type=llama2 --langchain_mode=UserData --score_model=None --share=False --gradio_offline_level=1`

**Comment by a3nima** [comment]
A reinstall solved this problem, but now I'm stuck with another one ^^

Traceback (most recent call last):
  File "E:\TEXT-AI\h2ogpt\generate.py", line 16, in <module>
    entrypoint_main()
  File "E:\TEXT-AI\h2ogpt\generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "E:\TEXT-AI\h2ogpt\src\utils.py", line 64, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "e:\TEXT-AI\venv\h2ogpt\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "e:\TEXT-AI\venv\h2ogpt\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "e:\TEXT-AI\venv\h2ogpt\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "E:\TEXT-AI\h2ogpt\src\gen.py", line 1260, in main
    model0, tokenizer0, device = get_model(reward_type=False,
  File "E:\TEXT-AI\h2ogpt\src\gen.py", line 1782, in get_model
    return get_hf_model(load_8bit=load_8bit,
  File "E:\TEXT-AI\h2ogpt\src\gen.py", line 1949, in get_hf_model
    model = get_non_lora_model(base_model, model_loader, load_half,
  File "E:\TEXT-AI\h2ogpt\src\gen.py", line 1506, in get_non_lora_model
    model = model_loader(
  File "e:\TEXT-AI\venv\h2ogpt\lib\site-packages\auto_gptq\modeling\auto.py", line 108, in from_quantized
    return quant_func(
  File "e:\TEXT-AI\venv\h2ogpt\lib\site-packages\auto_gptq\modeling\_base.py", line 902, in from_quantized
    cls.fused_attn_module_type.inject_to_model(
  File "e:\TEXT-AI\venv\h2ogpt\lib\site-packages\auto_gptq\nn_modules\fused_llama_attn.py", line 163, in inject_to_model    raise ValueError("Exllama kernel does not support query/key/value fusion with act-order. Please either use inject_fused_attention=False or disable_exllama=True.")
ValueError: Exllama kernel does not support query/key/value fusion with act-order. Please either use inject_fused_attention=False or disable_exllama=True.

`python generate.py --base_model=TheBloke/Xwin-LM-13B-v0.2-GPTQ --load_gptq=model --use_safetensors=True --prompt_type=xwin --langchain_mode=UserData --score_model=None --share=False --gradio_offline_level=1 `

**Comment by pseudotensor** [comment]
In the code you'll see:
```
        if 'Llama-2-70B-chat-GPTQ' in base_model:
            model_kwargs.update(dict(inject_fused_attention=False))
```
there.  You can add your model to that condition.

**Comment by pseudotensor** [comment]
with latest commit, you can now do:

```
CUDA_VISIBLE_DEVICES=0 python generate.py --base_model=TheBloke/Xwin-LM-13B-v0.2-GPTQ --load_gptq=model --use_safetensors=True --prompt_type=xwin --langchain_mode=UserData --score_model=None --share=False --gradio_offline_level=1 --gptq_dict="{'use inject_fused_attention': False, 'disable_exllama': True}"
```

or

```
CUDA_VISIBLE_DEVICES=0 python generate.py --base_model=TheBloke/Xwin-LM-13B-v0.2-GPTQ --load_gptq=model --use_safetensors=True --prompt_type=xwin --langchain_mode=UserData --score_model=None --share=False --gradio_offline_level=1 --gptq_dict="{'disable_exllama': True}"
```

I had to at least disable exllama, not just the fused attention, unlike message suggests (it suggests can be or, but seems just exllama has to be disabled).

Either scenario seems to be as fast as the other.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/85b7c519-4bbe-479d-9563-efe24a8a0744)

**Comment by a3nima** [comment]
Hi. Whats the CUDA_VISIBLE_DEVICES=0 for? 

Sadly I can only ask one question or say hello whatever. With the first line of your code the second question will be answered with gibberish, with the second line the question stays unanswered :(

**Comment by pseudotensor** [comment]
@a3nima I pushed a temporary fix that seems to work.  Their documentation is off.  In one case they say use </s> and in other parts show just new lines.

**Comment by a3nima** [comment]
with git pull (in my bat file) I should have the fix?  It's not working as intended. tried both of your lines from above. i could say "hi" and "hello" and get two answers, (hi and hello), but its not able to answer to "who are you" in a second question for example.

**Comment by pseudotensor** [comment]
I changed something at least minute thinking it wouldn't matter, but it did.  Some odd tokenization from xwin.  It's fine, it made me generalize some behavior.  Should work now if git pull:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/cb3acfda-ef20-4060-acd9-269d777828d3)

**Comment by pseudotensor** [comment]
That xwin gptq model isn't very efficient.  Still uses 20GB, probably because the fusion or exllama had to be disabled for it.

**Comment by pseudotensor** [comment]
The model uses about 9GB FYI.

I used CUDA_VISIBLE_DEVICES=0 because I have GPUs and wanted to mimic how behaves on 1 GPU.
