### ISSUE TITLE
Confusing parameter name `visible_models` in h2ogpt client

### ISSUE THREAD

**Issue by pira998** [h2oai/h2ogpt#967]
https://github.com/h2oai/h2ogpt/blob/main/client/h2ogpt_client/_core.py#L120 this should be singular name. 

<img width="798" alt="Screenshot 2023-10-17 at 19 45 59" src="https://github.com/h2oai/h2ogpt/assets/46839677/778b82bb-c5ca-4cfd-9dc9-3d47019acda4">

**Comment by pseudotensor** [comment]
It can be multiple models for chat case.  In general it can be string, number, or list.
