### ISSUE TITLE
"Textbox" word added to the question textbox and then added to the question itself.

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#972]
"Textbox" word added to the question textbox and then added to the question itself.
Please attached screenshot
First question :
<img width="1019" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/a2dc7571-973e-48c4-b20d-0d19505f31c6">

Second question:
<img width="873" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/711946f1-3fe9-4456-ae33-16833a851901">

And next error appears when clicking on "Clear" button, seems to be related 
<img width="450" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/935a1219-638a-42f9-a1b7-e7b56684a941">

Log:
```
Traceback (most recent call last):
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1341, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/components/chatbot.py", line 231, in postprocess
    for message_pair in y:
TypeError: 'Textbox' object is not iterable
```

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/issues/947#issuecomment-1760022583

**Comment by pseudotensor** [comment]
Just upgrade all packages to be consistent with requirements.txt as in readme_linux.md etc.  You can try just upgrading gradio, but I can't tell you if that is enough and is not supported.

**Comment by slavag** [comment]
I upgraded gradio and seems to ok.
Thanks
