### ISSUE TITLE
Dependency conflicts when using the "pip install -r requirements.txt --extra-index https://download.pytorch.org/whl/cu117" command

### ISSUE THREAD

**Issue by frivasplata** [h2oai/h2ogpt#976]
I have reinstalled the h2ogpt in my server and I noticed that 2 dependency errors arise when using the command:
pip install -r requirements.txt --extra-index https://download.pytorch.org/whl/cu117

This file (requirements.txt) together with the extra index url are for some reason uninstalling the required torch and numpy versions then the torchvision and openvino packages are not properly installed and now the answers I'm receiving are completely crazy.

Below the error I'm receiving in the server console during the installation, pay attention to the fact that the installation process managed by the pip install command is removing the numpy 1.23.4 and the torch 2.1.0 and then the error arise saying that those versions are missed. Any help with this issue will be very appreciated. 

Installing collected packages: numpy, triton, torch
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.4
    Uninstalling numpy-1.23.4:
      Successfully uninstalled numpy-1.23.4
  Attempting uninstall: triton
    Found existing installation: triton 2.1.0
    Uninstalling triton-2.1.0:
      Successfully uninstalled triton-2.1.0
  Attempting uninstall: torch
    Found existing installation: torch 2.1.0
    Uninstalling torch-2.1.0:
      Successfully uninstalled torch-2.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openvino 2022.3.0 requires numpy<=1.23.4,>=1.16.6, but you have numpy 1.24.3 which is incompatible.
torchvision 0.16.0 requires torch==2.1.0, but you have torch 2.0.1+cu117 which is incompatible.
Successfully installed numpy-1.24.3 torch-2.0.1+cu117 triton-2.0.0

**Comment by pseudotensor** [comment]
`torch 2.1.0` should only be for CPU, so the uninstall makes sense.

torchvision etc. are only installed with DocTR dependency AFAIK, which comes later in instructions.

So I'm guessing you have an existing environment and trying to install things.  Can you try a fresh env and installing things in the steps documented?  I've never hit an issue with following the steps.

Thanks!

**Comment by frivasplata** [comment]
Ok I will do that, thank you

Regards
Fernando Rivasplata

**Comment by frivasplata** [comment]
Hi, I completely removed the conda env (conda remove -n name --all) then I
reinstalled h2ogpt but it has the same issues, it is highly probably that
I'm doing something wrong so if you can help me to find the issue in the
installation sequence I'll appreciate it. Since I decided to reinstall
h2ogpt the model is returning super crazy answers.

Here the installation process command by command I'm following, it seems
that I'm missing something or adding something that I shouldn't. The server
I'm using has 1 x GPU RTX-A6000 with 48Gb of VRAM and CUDA version 12.2, it
was working fine 2 days ago but since I reinstalled it is almost useless,
please help me.

#creating a conda env and installing python 3.10
conda create -n h2ogpt -y
conda activate h2ogpt
conda install python=3.10 -c conda-forge -y
#Cloning the h2ogpt from github
git clone https://github.com/h2oai/h2ogpt.git
cd h2ogpt

#Installing CUDA toolkit
conda install cudatoolkit=11.7 -c conda-forge -y
export CUDA_HOME=$CONDA_PREFIX

#Installing dependencies
pip uninstall -y pandoc pypandoc pypandoc-binary flash-attn
pip install -r requirements.txt --extra-index
https://download.pytorch.org/whl/cu117
# May be required for jq package:
sudo apt-get -y install autoconf libtool
# Required for Doc Q/A: LangChain:
pip install -r reqs_optional/requirements_optional_langchain.txt
--extra-index https://download.pytorch.org/whl/cu117
# Optional: PyMuPDF/ArXiv:
pip install -r reqs_optional/requirements_optional_langchain.gpllike.txt
--extra-index https://download.pytorch.org/whl/cu117
# Optional: Selenium/PlayWright:
pip install -r reqs_optional/requirements_optional_langchain.urls.txt
--extra-index https://download.pytorch.org/whl/cu117
# Optional: support docx, pptx, ArXiv, etc. required by some python packages
sudo apt-get install -y libmagic-dev poppler-utils tesseract-ocr
libtesseract-dev libreoffice
# Improved OCR with DocTR:
conda install -y -c conda-forge pygobject
pip install -r reqs_optional/requirements_optional_doctr.txt --extra-index
https://download.pytorch.org/whl/cu117
# go back to older onnx so Tesseract OCR still works
pip install onnxruntime==1.15.0 onnxruntime-gpu==1.15.0 --extra-index
https://download.pytorch.org/whl/cu117
# Optional: for supporting unstructured package
python -m nltk.downloader all
# Optional but required for PlayWright
playwright install --with-reps
#Control core count for chroma
pip install
https://h2o-release.s3.amazonaws.com/h2ogpt/duckdb-0.8.2.dev4025%2Bg9698e9e6a8.d20230907-cp310-cp310-linux_x86_64.whl
--no-cache-dir --force-reinstall --no-deps



Then I'm running the generate.py with the following attributes:
python generate.py
--base_model=/root/experiments/mistral-7B-1108-v8-linear+lora200alpha128dropout0-1
--load_8bit=True  --score_model=None --temperature=0.01
--visible_submit_buttons=True --visible_side_bar=False
--visible_chat_tab=True --visible_doc_selection_tab=False
--visible_doc_view_tab=False --visible_chat_history_tab=False
--visible_expert_tab=False --visible_models_tab=False
--visible_system_tab=False --visible_tos_tab=False
--visible_hosts_tab=False --chat_tabless=False
--visible_h2ogpt_header=False --append_sources_to_answer=False

Regards
Fernando Rivasplata

**Comment by pseudotensor** [comment]
Hi, you showed all the above, but in that case, what error do you get?  Garbage output?  But no package issues?  Please explain.

**Comment by pseudotensor** [comment]
I'd run your case but it uses a model I don't have.

If I just change to mistral instruct itself I get:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/059f0917-ff78-43f3-8ca5-f893c1ffef60)


Note that "mistral instruct" requires --prompt_type=mistral  but that is chosen automatically if the model name is known. Your model is not known, so you need to pass that to the generate.py line.

That's probably at least one of your issues.

**Comment by frivasplata** [comment]
Thank you, that worked.

Regards
Fernando Rivasplata
