### ISSUE TITLE
Question regarding Q&A and embeddings

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#979]
Hi,
Maybe it's a silly question, but when trying to understand how things are working under the hood.
Let's assume I have chroma db with embeddings made from my texts. So, when I'm asking any question, the embeddings vectors is made from the question and then querying the chroma db with that vector to find similarities. Once similarities are found , what is used to interact with LLM model , is this embeddings vector or the text that this embeddings vector is associated with (made from) ?

Thanks

**Comment by pseudotensor** [comment]
Hi, the LLM just gets the text stored in the database for those that were chosen to be most similar.  So it's just a database look-up for what texts to put into the context of the LLM.
