### ISSUE TITLE
Very slow response

### ISSUE THREAD

**Issue by An28212** [h2oai/h2ogpt#985]
I am very impressed with this repository but I am facing two issue here
1. I am using llama model for Q/A with user documents but its response is very slow. Generally its taking 60-80 sec for simple question's answer . So how to improve response time?
2. I tried to add loader/progress in chat but gradio not allowed me to add.

**Comment by pseudotensor** [comment]
1. Are you using GPU?  Even for CPU I get about 5 tokens/sec  You should use quantized models if you have weak GPU and always if have CPU.  i.e. the --base_model=llama type models discussed throughout documentation and in FAQ.
2. Gradio shows a progress by time and estimated completion, but no extra messages.  I could do that by yielding extra information to another text box, it's just not done as it can be tough to estimate if a document will take a long time or not, and I could only show which document is being parsed.

**Comment by An28212** [comment]
I don't have any GPU. If it without user document its pretty fast but interaction with user document, it's taking 50-60 sec.
This is the command line I am trying,
python generate.py --base_model='llama' --prompt_type=llama2

**Comment by pseudotensor** [comment]
If you want documents handling to be faster you can restrict `max_input_tokens` and `max_seq_len` to smaller values than the default model would allow and we'll reduce the input to LLM.

e.g. for llama-2 default is 4096 but you can make `max_input_tokens=1024` and see how it goes if using top_k_docs=-1.

Or restrict top_k_docs to 4 etc.
