### ISSUE TITLE
langchain errors

### ISSUE THREAD

**Issue by MSZ-MGS** [h2oai/h2ogpt#990]
Started receiving below errors after installing:
langchain==0.0.321
langchain_experimental==0.0.33

![image](https://github.com/h2oai/h2ogpt/assets/65172063/9687671a-928c-4e4b-a8da-98200b675120)

**Comment by pseudotensor** [comment]
Do you mean warnings? Yes they added those warnings.

**Comment by pseudotensor** [comment]
652c4ad6ad1105b3b5a8c9dce610401d11643e88
