### ISSUE TITLE
transformers-4.34.1 Error

### ISSUE THREAD

**Issue by MSZ-MGS** [h2oai/h2ogpt#991]
Error during the installation of transformers-4.34.1.
![image](https://github.com/h2oai/h2ogpt/assets/65172063/a2715e40-c5a2-4e78-9a7d-33b2446acb80)

**Comment by pseudotensor** [comment]
Despite it saying ERROR it's just a warning.  I've asked attention sinks to relax their requirement, you'll have to ignore for now.

**Comment by pseudotensor** [comment]
https://github.com/tomaarsen/attention_sinks/issues/26
