### ISSUE TITLE
make chat completion API migration safe

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#995]
For chat completion the API has to match exactly between server and client, so if the server is some latest h2ogpt, the client has to match.  It's not migration safe.  Only the text completion API is migration safe.

I always update the client API when I change things, and it's fine.  You just have an old wrong version.
@this  can consider making the chat completion API migration safe.  i.e. there's no need to use chat=True for chat completion, the client could manage the conversation state as it already has to.

i.e. this: https://github.com/h2oai/h2ogpt/blob/79f9dd56fac11535c10e826fc25e75ca3d883034/client/h2ogpt_client/_core.py#L299 

can be set to False and the "chatbot" can be purely managed by client, instead of expecting back an update history of the chat from the server.  It's totally useless by design since the history anyways has to be updated by client before asking another question with that updated history.  Instead the client could just maintain the history, and then the nochat API can be used and be migration safe.

**Comment by this** [comment]
@pseudotensor So the `ChatCompletion` API should call the migration safe `/submit_nochat_api` API instead of the `/instruction_bot` API, right?

If we are not passing the `chatbot` param, then how can we pass the chat history to the server? Without passing the whole chat history, the response we get wouldn't be accurate.

**Comment by pseudotensor** [comment]
Yes use submit_nochat_api instead of instruction_bot.

submit_nochat_api includes the "chat_conversation" parameter that is exactly same structure of chatbot parameter.  It's what helium uses to pass conversation to h2ogpt.

https://github.com/h2oai/h2ogpt/blob/1ba437f71a5f35314b1437571069f5d5b7bc21b1/client/h2ogpt_client/_core.py#L126
